### ISSUE TITLE
[Native Image] Missing support for `ServiceLoader` services registered via `module-info`

### ISSUE THREAD

**Issue by JaroslavTulach** [oracle/graal#9952] opened 2024-10-23 16:24 UTC
### Describe the Issue

[Java Platform Module System](https://openjdk.org/jeps/261) defines a way to register services to be located by [ServiceLoader](https://docs.oracle.com/en/java/javase/21/docs/api/java.base/java/util/ServiceLoader.html). However there seems to be no support for such registrations in native image.

### Using the latest version of GraalVM can resolve many issues.

- [x] I tried with the [latest version](https://www.graalvm.org/downloads/) of GraalVM.

### GraalVM Version

I tried two versions:
- `GraalVM CE 21.0.2+13.1 (build 21.0.2+13-jvmci-23.1-b30)`
- Oracle GraalVM 23.0.1+11.1 (build 23.0.1+11-jvmci-b01)

None of them works the way it "should". Looking at the code of [ServiceLoaderFeature](https://github.com/oracle/graal/blob/17d022faecfb96308dae1a76f2411f218522fe86/substratevm/src/com.oracle.svm.hosted/src/com/oracle/svm/hosted/ServiceLoaderFeature.java#L71) explains why it is not working - there is no [ModuleLayer](https://docs.oracle.com/en/java/javase/21/docs/api/java.base/java/lang/ModuleLayer.html#modules()) related code at all - which is probably necessary to extract information from the `module-info.class` of the modules on module path.

### Operating System and Version

Tested on Ubuntu, but this is cross OS problem

### Diagnostic Flag Confirmation

- [ ] I tried the `-H:ThrowMissingRegistrationErrors=` flag.

### Run Command

I have prepared a special repository with [NativeImageModuleDemo](https://github.com/jtulach/NativeImageModularDemo) with a demo Maven project, follow the [read me](https://github.com/jtulach/NativeImageModularDemo/blob/master/README.md) that suggests to:
```
NativeImageModularDemo$ mvn clean install
NativeImageModularDemo$ mvn -q -Pjvm -f api exec:exec
NativeImageModularDemo with following modules:
  Api
Found no API provider. Include Impl JPMS module!
NativeImageModularDemo$ mvn -q -Pjvm -f impl exec:exec
NativeImageModularDemo with following modules:
  Api
  Impl
Hi from Impl!
```
e.g. two modules `Api` and `Impl` are enabled and `Hi from Impl!` gets printed. While with `native-image`:
```
NativeImageModularDemo$ mvn clean install -Pnative
NativeImageModularDemo$ ./impl/target/NativeImageModularDemo
NativeImageModularDemo with following modules:
  Impl
  Api
Found no API provider. Fix native-image support for modular ServiceLoader!
```
e.g. two modules are enabled, but the `ServiceLoader.load` finds no implementation of the interface it is looking for.

### Expected Behavior

Native image version should work just like the JVM one:
```
NativeImageModularDemo$ mvn clean install -Pnative
NativeImageModularDemo$ ./impl/target/NativeImageModularDemo
NativeImageModularDemo with following modules:
  Impl
  Api
Hi from Impl!
```

### Actual Behavior

```
NativeImageModularDemo$ mvn clean install -Pnative
NativeImageModularDemo$ ./impl/target/NativeImageModularDemo
NativeImageModularDemo with following modules:
  Impl
  Api
Found no API provider. Fix native-image support for modular ServiceLoader!
```

### Steps to Reproduce

I have prepared a special repository with [NativeImageModuleDemo](https://github.com/jtulach/NativeImageModularDemo) with a demo Maven project, follow the [read me](https://github.com/jtulach/NativeImageModularDemo/blob/master/README.md) that suggests to:
```
NativeImageModularDemo$ mvn clean install
NativeImageModularDemo$ mvn -q -Pjvm -f api exec:exec
NativeImageModularDemo with following modules:
  Api
Found no API provider. Include Impl JPMS module!
NativeImageModularDemo$ mvn -q -Pjvm -f impl exec:exec
NativeImageModularDemo with following modules:
  Api
  Impl
Hi from Impl!
```
e.g. two modules `Api` and `Impl` are enabled and `Hi from Impl!` gets printed. While with `native-image`:
```
NativeImageModularDemo$ mvn clean install -Pnative
NativeImageModularDemo$ ./impl/target/NativeImageModularDemo
NativeImageModularDemo with following modules:
  Impl
  Api
Found no API provider. Fix native-image support for modular ServiceLoader!
```
e.g. two modules are enabled, but the `ServiceLoader.load` finds no implementation of the interface it is looking for.

**Comment by wirthi** [comment] 2024-10-23 16:41
Thanks Jaroslav for reporting this. I suspect this is a duplicate of #7634 / GR-49635. @olpaw can you confirm?

**Comment by olpaw** [comment] 2024-10-23 16:52
> I suspect this is a duplicate of https://github.com/oracle/graal/issues/7634 / GR-49635. @olpaw can you confirm?

Correct. But I prefer @JaroslavTulach s issue as it is more recent.

**Comment by olpaw** [comment] 2024-10-23 16:54
I will look into that soon :crossed_fingers:

**Comment by olpaw** [comment] 2024-10-28 16:36
@JaroslavTulach I debugged this. The parameterless constructor for a service impl. class gets correctly registered for reflective access and the ServiceLoader at runtime is almost able to do the right thing. But it relies on using LazyClassPathLookupIterator which then refuses to use the parameterless constructor because the implementation class is in a named module. See https://github.com/openjdk/jdk/blob/52382e285fdf853c01605f8e0d7f3f5d34965802/src/java.base/share/classes/java/util/ServiceLoader.java#L1228

Turns out we do not correctly implement ServicesCatalog retrieval at image image runtime. I will find someone to fix this hopefully next week.

**Comment by JaroslavTulach** [comment] 2024-11-22 16:17
Thank you @olpaw for investigating the issue. I tried to [workaround the problem by loading the services in build time](https://github.com/enso-org/enso/pull/10714#issuecomment-2494126650), but no luck so far. Was there **any progress on your side**?

**Comment by ivan-ristovic** [comment] 2024-12-02 10:00
Hi @JaroslavTulach , the PR that adresses this issue is up: https://github.com/oracle/graal/pull/10202

**Comment by ivan-ristovic** [comment] 2024-12-05 13:28
The fix has been merged (#10202) and will be part of GraalVM 24.2

**Closed** 2024-12-10 10:28 UTC
Labels: bug, native-image

**Comment by JaroslavTulach** [comment] 2024-12-16 08:00
> The fix has been merged (#10202) and will be part of GraalVM 24.2.
> We will also backport to GraalVM 23.1.

Thank you! I can confirm that my [NativeImageModuleDemo](https://github.com/jtulach/NativeImageModularDemo) works with 0c2731c6e441a7617013a4cfd4fcce4209e3890b GraalVM. I used:
```bash
graal/vm$ mx --env ni-ce build
graal/vm$ export JAVA_HOME=`mx --env ni-ce graalvm-home`
```
and then used the generated JVM in [NativeImageModuleDemo](https://github.com/jtulach/NativeImageModularDemo) as:
```bash
NativeImageModularDemo$ mvn clean install -Pnative
NativeImageModularDemo$ $ ./impl/target/NativeImageModularDemo 
NativeImageModularDemo with following modules:
  Api
  Impl
Hi from Impl!
```
Everything is working as expected. Thank you!

**Comment by simonis** [comment] 2025-04-18 10:49
> The fix has been merged ([#10202](https://github.com/oracle/graal/pull/10202)) and will be part of GraalVM 24.2.
> 
> We will also backport to GraalVM 23.1.

@ivan-ristovic, what do you mean by "*We will also backport to GraalVM 23.1.*"? Does this only apply to Oracle GraalVM 23.1 or also to the GraalVM 23.1 community edition? From what I can see in the [Release Notes for Oracle GraalVM for JDK 21.0.7](https://docs.oracle.com/en/graalvm/jdk/21/docs/release-notes/#oracle-graalvm-for-jdk-2107), this has indeed been fixed in Oracle GraalVM for JDK 21.0.7

**Comment by ivan-ristovic** [comment] 2025-04-18 16:40
@simonis The fix is backported to the community edition.

**Comment by simonis** [comment] 2025-04-18 21:12
> @simonis The fix is backported to the community edition.

@ivan-ristovic what do you mean by "Community Edition"?

I can't see any changes neither to e.g. https://github.com/graalvm/graalvm-community-jdk21u/blob/master/substratevm/src/com.oracle.svm.core/src/com/oracle/svm/core/jdk/Target_java_lang_ModuleLayer.java nor to https://github.com/oracle/graal/blob/release/graal-vm/23.1/substratevm/src/com.oracle.svm.core/src/com/oracle/svm/core/jdk/Target_java_lang_ModuleLayer.java  in the last two years. So in which Community Version for GraalVM21 23.1 has this backport landed?

**Comment by ivan-ristovic** [comment] 2025-04-18 21:35
> Does this only apply to Oracle GraalVM 23.1 or also to the GraalVM 23.1 community edition?
Sorry for the confusion. The fix is done entirely on the open-sourced GraalVM side. The backport in question targets the Oracle GraalVM for JDK 21.0.7 CPU release. I was under the impression that there was a backport that targeted the Community Edition as well, but that is not the case.
