### ISSUE TITLE
Enable CMS GC for GraalVM CE Java11

### ISSUE THREAD

**Issue by helloguo** [oracle/graal#2143] opened 2020-02-10 22:59 UTC
**Feature request**

Enable CMS GC for GraalVM CE Java11:

**Is your feature request related to a problem? Please describe.**
GraalVM CE 20.0.0-dev for Java11 does not support CMS GC as shown below. It's reasonable not to encourage people to use CMS as CMS is deprecating. However, there's still some workload using CMS because CMS is performing well. In addition, OpenJDK11 is still able to use CMS when explicitly setting the flag. I'm asking to enable CMS GC for GraalVM CE version 20.0 Java11.
```
>java -version
openjdk version "11.0.6" 2020-01-14
OpenJDK Runtime Environment GraalVM CE 20.0.0-dev (build 11.0.6+9-jvmci-20.0-b02)
OpenJDK 64-Bit Server VM GraalVM CE 20.0.0-dev (build 11.0.6+9-jvmci-20.0-b02, mixed mode, sharing)
>java -XX:+UseConcMarkSweepGC HelloWorld
OpenJDK 64-Bit Server VM warning: Option UseConcMarkSweepGC was deprecated in version 9.0 and will likely be removed in a future release.
Error occurred during initialization of VM
JVMCI Compiler does not support selected GC: concurrent mark sweep gc
```

**Describe the solution you'd like.**
Add in `UseConcMarkSweepGC`  line https://github.com/graalvm/labs-openjdk-11/blob/master/src/hotspot/share/jvmci/jvmci_globals.cpp#L199.

**Describe who do you think will benefit the most.**
GraalVM users can enjoy the high quality codegen from Graal compiler as well as CMS GC for some use cases.

**Describe alternatives you've considered.**

**Additional context.**

**Express whether you'd like to help contributing this feature**
If you'd like to contribute, please read the [contribution guide](https://www.graalvm.org/community/contributors/).

**Comment by helloguo** [comment] 2020-02-18 21:40
Ping? It seems version 20.0 is not doable as the release date was passed. How about adding this feature for later release?

**Comment by dougxc** [comment] 2020-02-19 09:35
Hi @helloguo , since GraalVM CE Java8 works with CMS, it should also work on GraalVM CE Java11. At some point it didn't and so checks were added by [JDK-8184349](https://bugs.openjdk.java.net/browse/JDK-8184349) to [JVMCI C++ code](https://github.com/openjdk/jdk/blob/4aab3078a294b0ee6954654a65a15f4fabd5fac4/src/hotspot/share/jvmci/jvmci_globals.cpp#L194). The problem is that this C++ code is Graal agnostic and so doesn't really know what GCs are supported. What is really needed is a mechanism for a JVMCI compiler to communicate low level info (such as the GCs it supports) to the VM without requiring the VM to run any JVMCI Java code (to avoid increasing VM startup). Off the top of my head, something like a `<java.home>/lib/jvmci.properties` file could be used. In the case that there are [multiple JVMCI compilers available](https://github.com/openjdk/jdk/blob/8119f836bf73f11440c5ff6a6343ec11b8c80600/src/jdk.internal.vm.ci/share/classes/jdk.vm.ci.hotspot/src/jdk/vm/ci/hotspot/HotSpotJVMCICompilerConfig.java#L117), you'd probably want to use a `<java.home>/lib/jvmci.<compiler-name>.properties` file.

I suggest opening a [JDK RFE](https://bugs.openjdk.java.net/) for this as it should be fixed in JDK master and subsequently backported to JDK 11u.

**Comment by dougxc** [comment] 2020-02-19 17:41
A correction to the above: While GraalVM CE Java8 will allow you to specify CMS, this is not something we test so I can't guarantee that it's bug free. It would be great if you could test it on your workloads and report whether you see any crashes.

**Comment by fernando-valdez** [comment] 2024-01-24 03:59
This issue has been fixed

**Closed by fernando-valdez** 2024-01-24 03:59 UTC
Labels: feature
