### ISSUE TITLE
Hanged up threads of ExecutorService

### ISSUE THREAD

**Issue by antonliauchuk-tealium** [oracle/graal#3729] opened 2021-08-26 13:49 UTC
**Describe the issue**
hello
We found the issue with executor service in native image mode. Please look into the code:
```         import java.io.IOException;
import java.time.Duration;
import java.time.Instant;
import java.util.concurrent.ExecutorService;
import java.util.concurrent.Executors;
import java.util.concurrent.Future;
import java.util.concurrent.TimeUnit;
public class HangedUpThreads {

	private static Instant start;

	public static void main(String[] args) throws IOException, InterruptedException {
		executorService();
	}

	public static void executorService() {
		System.out.println("------------ Infinite loop is started ------------");
		start = Instant.now();
		while (true) {
			try {
				executorServiceActionWithShutdown();
			} catch (Throwable t) {
				t.printStackTrace();
			}
		}
	}

	public static void executorServiceActionWithShutdown() {
		var taskExecutor = Executors.newSingleThreadExecutor();
		try {
			Future<Integer> futureResult = taskExecutor.submit(() -> {
				Thread.sleep(10);
				return 3 + 1;
			});

			futureResult.get();
		} catch (Exception e) {
			e.printStackTrace();
		} finally {
			shutdown(taskExecutor, 3);
		}
	}

	public static void shutdown(ExecutorService service, int maxRetries) {
		service.shutdownNow();

		try {
			for (int i = 0; i < maxRetries; i++) {
				var retryCount = i + 1;
				var executorWasShutdown = service.awaitTermination(getWaitTime(retryCount), TimeUnit.MILLISECONDS);
				if (executorWasShutdown) {
					return;
				} else {
					System.out.println("Executor was not shutdown, retry number = " + retryCount);
				}
			}
			System.out.println("Executor was not shutdown after several attempts.");
			System.out.println("Hanged up thread was reproduced after " + Duration.between(start, Instant.now()).toSeconds() + " seconds");
			var threadInfo = getAllStackTraces();
			System.out.println("Thread info: " + threadInfo);

			System.out.println("Stop application");
			System.exit(1);
		} catch (InterruptedException e) {
			e.printStackTrace();
		}
	}

	private static long getWaitTime(int retryCount) {
		return (long) Math.pow(2, retryCount) * 1000;
	}

	private static String getAllStackTraces() {
		StringBuilder sb = new StringBuilder();
		var liveThreads = Thread.getAllStackTraces();
		for (Thread key : liveThreads.keySet()) {
			sb.append("Thread " + key.getName());
			sb.append("\n ");
			sb.append("State " + key.getState());
			sb.append("\n ");
			sb.append("Priority " + key.getPriority());
			sb.append("\n ");
			var trace = liveThreads.get(key);
			for (StackTraceElement stackTraceElement : trace) {
				sb.append("\tat " + stackTraceElement);
				sb.append("\n");
			}
		}

		return sb.toString();
	}
}
```
Each time this issue is reproduced after different number of iterations. Stack trace:
```
------------ Infinite loop is started ------------
Executor was not shutdown, retry number = 1
Executor was not shutdown, retry number = 2
Executor was not shutdown, retry number = 3
Executor was not shutdown after several attempts.
Hanged up thread was reproduced after 358 seconds
Thread info: Thread pool-30166-thread-1
 State WAITING
 Priority 5
        at com.oracle.svm.core.posix.headers.Pthread.pthread_cond_wait(Pthread.java)
        at com.oracle.svm.core.posix.thread.PosixParkEvent.condWait(PosixJavaThreads.java:250)
        at com.oracle.svm.core.thread.JavaThreads.park(JavaThreads.java:688)
        at jdk.internal.misc.Unsafe.park(Unsafe.java:49)
        at java.util.concurrent.locks.LockSupport.park(LockSupport.java:194)
        at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2081)
        at java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:433)
        at java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1054)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1114)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.lang.Thread.run(Thread.java:834)
        at com.oracle.svm.core.thread.JavaThreads.threadStartRoutine(JavaThreads.java:519)
        at com.oracle.svm.core.posix.thread.PosixJavaThreads.pthreadStartRoutine(PosixJavaThreads.java:192)
Thread main
 State RUNNABLE
 Priority 5
        at com.oracle.svm.core.thread.JavaThreads.lambda$getAllStackTraces$1(JavaThreads.java:578)
        at com.oracle.svm.core.thread.JavaVMOperation$ThunkOperation.operate(JavaVMOperation.java:142)
        at com.oracle.svm.core.thread.JavaVMOperation.operate(JavaVMOperation.java:125)
        at com.oracle.svm.core.thread.VMOperation.execute(VMOperation.java:89)
        at com.oracle.svm.core.thread.VMOperationControl$WorkQueues.drain(VMOperationControl.java:590)
        at com.oracle.svm.core.thread.VMOperationControl$WorkQueues.executeAllQueuedVMOperations(VMOperationControl.java:544)
        at com.oracle.svm.core.thread.VMOperationControl$WorkQueues.enqueueAndExecute(VMOperationControl.java:481)
        at com.oracle.svm.core.thread.VMOperationControl.enqueue(VMOperationControl.java:264)
        at com.oracle.svm.core.thread.VMOperationControl.enqueue(VMOperationControl.java:223)
        at com.oracle.svm.core.thread.JavaVMOperation.enqueue(JavaVMOperation.java:77)
        at com.oracle.svm.core.thread.JavaVMOperation.enqueueBlockingSafepoint(JavaVMOperation.java:114)
        at com.oracle.svm.core.thread.JavaThreads.getAllStackTraces(JavaThreads.java:576)
        at java.lang.Thread.getAllStackTraces(Thread.java:373)
        at HangedUpThreads.getAllStackTraces(HangedUpThreads.java:76)
        at HangedUpThreads.shutdown(HangedUpThreads.java:60)
        at HangedUpThreads.executorServiceActionWithShutdown(HangedUpThreads.java:41)
        at HangedUpThreads.httpConnectionOutsideIsolate(HangedUpThreads.java:22)
        at HangedUpThreads.main(HangedUpThreads.java:14)
```

**Steps to reproduce the issue**
1. clone repo https://github.com/antonliauchuk-tealium/hanged-up-threads
2. echo "Main-Class: HangedUpThreads" > manifest.txt && javac HangedUpThreads.java && jar -cvfm HangedUpThreads.jar manifest.txt HangedUpThreads.class && native-image -H:EnableURLProtocols=http -H:EnableURLProtocols=https -H:ReflectionConfigurationFiles=reflection-config.json -jar HangedUpThreads.jar
3. ./HangedUpThreads

**Describe GraalVM and your environment:**
 -  GraalVM CE 21.0.0.2
 - OS: macOS Big Sur Version 11.2.1

**More details**
It's very important issue for Isolates. Isolate cannot be closed if executor service was not stopped. Isolates.tearDownIsolate takes a lot of CPU, on 1 vCpu machine, 100% of CPU is busy on infinite teardown operation.

**Comment by oubidar-Abderrahim** [comment] 2021-08-30 14:53
Hi, thank you for reporting this issue. Could you please try using the latest build (21.2.0) and share if the issue is still reproducible? Thank you

**Comment by antonliauchuk-tealium** [comment] 2021-09-01 09:54
hi @oubidar-Abderrahim 
this issue was not reproduced for me with 21.2.0

**Comment by oubidar-Abderrahim** [comment] 2021-09-02 14:26
@antonliauchuk-tealium thank you for your confirmation, We focus always on the latest build for fixing bugs and issues. I will close this issue, if you still need assistance please reopen it.

**Closed as completed by oubidar-Abderrahim** 2021-09-02 14:26 UTC
Labels: bug, native-image
