### ISSUE TITLE
[native-image] MalformedParameterizedTypeException when using Kotlin

### ISSUE THREAD

**Issue by nanodeath** [oracle/graal#374] opened 2018-04-23 21:38 UTC
I'm running the following command and getting a crash. Compiled using Graal 1.0.0 RC and Kotlin 1.2.40.

```
$ native-image -cp <classpath redacted> <class redacted>
    Build on Server(pid: 41671, port: 26682)*
       classlist:   1,418.13 ms
           (cap):   1,088.56 ms
           setup:   1,846.08 ms
    warning: unknown locality of class Lparsecomb/Runes$nextWord$trimmed$1;, assuming class is not local. To remove the warning report an issue to the library or language author. The issue is caused by Lparsecomb/Runes$nextWord$trimmed$1; which is not following the naming convention.
    warning: unknown locality of class Lkata/types/SymbolRegistry$plus$1;, assuming class is not local. To remove the warning report an issue to the library or language author. The issue is caused by Lkata/types/SymbolRegistry$plus$1; which is not following the naming convention.
        analysis:   4,808.20 ms
    fatal error: java.lang.reflect.MalformedParameterizedTypeException
            at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
            at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
            at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
            at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
            at java.util.concurrent.ForkJoinTask.getThrowableException(ForkJoinTask.java:598)
            at java.util.concurrent.ForkJoinTask.get(ForkJoinTask.java:1005)
            at com.oracle.svm.hosted.NativeImageGenerator.run(NativeImageGenerator.java:398)
            at com.oracle.svm.hosted.NativeImageGeneratorRunner.buildImage(NativeImageGeneratorRunner.java:240)
            at com.oracle.svm.hosted.NativeImageGeneratorRunner.build(NativeImageGeneratorRunner.java:337)
            at com.oracle.svm.hosted.server.NativeImageBuildServer.executeCompilation(NativeImageBuildServer.java:378)
            at com.oracle.svm.hosted.server.NativeImageBuildServer.lambda$processCommand$8(NativeImageBuildServer.java:315)
            at com.oracle.svm.hosted.server.NativeImageBuildServer.withJVMContext(NativeImageBuildServer.java:396)
            at com.oracle.svm.hosted.server.NativeImageBuildServer.processCommand(NativeImageBuildServer.java:312)
            at com.oracle.svm.hosted.server.NativeImageBuildServer.processRequest(NativeImageBuildServer.java:256)
            at com.oracle.svm.hosted.server.NativeImageBuildServer.lambda$serve$7(NativeImageBuildServer.java:216)
            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
            at java.lang.Thread.run(Thread.java:748)
    Caused by: java.lang.reflect.MalformedParameterizedTypeException
            at sun.reflect.generics.reflectiveObjects.ParameterizedTypeImpl.validateConstructorArguments(ParameterizedTypeImpl.java:58)
            at sun.reflect.generics.reflectiveObjects.ParameterizedTypeImpl.<init>(ParameterizedTypeImpl.java:51)
            at sun.reflect.generics.reflectiveObjects.ParameterizedTypeImpl.make(ParameterizedTypeImpl.java:92)
            at sun.reflect.generics.factory.CoreReflectionFactory.makeParameterizedType(CoreReflectionFactory.java:105)
            at sun.reflect.generics.visitor.Reifier.visitClassTypeSignature(Reifier.java:140)
            at sun.reflect.generics.tree.ClassTypeSignature.accept(ClassTypeSignature.java:49)
            at sun.reflect.generics.repository.ClassRepository.getSuperInterfaces(ClassRepository.java:108)
            at java.lang.Class.getGenericInterfaces(Class.java:913)
            at com.oracle.svm.hosted.analysis.Inflation.fillGenericInfo(Inflation.java:240)
            at com.oracle.svm.hosted.analysis.Inflation.checkType(Inflation.java:146)
            at java.lang.Iterable.forEach(Iterable.java:75)
            at java.util.Collections$UnmodifiableCollection.forEach(Collections.java:1080)
            at com.oracle.svm.hosted.analysis.Inflation.checkObjectGraph(Inflation.java:123)
            at com.oracle.graal.pointsto.BigBang.checkObjectGraph(BigBang.java:580)
            at com.oracle.graal.pointsto.BigBang.finish(BigBang.java:552)
            at com.oracle.svm.hosted.NativeImageGenerator.doRun(NativeImageGenerator.java:653)
            at com.oracle.svm.hosted.NativeImageGenerator.lambda$run$0(NativeImageGenerator.java:381)
            at java.util.concurrent.ForkJoinTask$AdaptedRunnableAction.exec(ForkJoinTask.java:1386)
            at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
            at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
            at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
            at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
    Error: Processing image build request failed
```

Unfortunately I can't attach source or JARs (as they're company IP), but if there's any other way I can provide more context, please let me know.

Thanks!

**Comment by cstancu** [comment] 2018-04-23 22:14
Thank you for your report. It would help if you could reproduce this with a minimal, non-proprietary, example. The `MalformedParameterizedTypeException` is thrown from `java.lang.Class.getGenericInterfaces()` which is 
>  Thrown when a semantically malformed parameterized type is encountered by a reflective method that needs to instantiate it. For example, if the number of type arguments to a parameterized type is wrong.

This doesn't seem to be a SubstrateVM issue but rather an application issue. My guess is that you have some class path configuration problems (e.g., incompatible versions of the same jar on the class path). 
To find the offending class you can debug the image building process for your app. See [Building images](https://github.com/oracle/graal/tree/master/substratevm#building-images) for details. Hint: you don't actually need to build `native-image` from source; just use `--debug-attach[=<port>]` and do a remote debugging from your IDE (default port is 8000) but you still need the sources.

**Comment by nanodeath** [comment] 2018-04-23 22:27
Messing around with the classpath a bit, if I remove `kotlin-stdlib-1.2.40.jar` I get `java.lang.ClassNotFoundException: kotlin.jvm.functions.Function0`, but if I add it back I get the same stacktrace as listed above. So my current unfounded theory is that it's related to that particular JAR.

I'll try what you suggested.

**Comment by nanodeath** [comment] 2018-04-23 23:12
That was...surprisingly easy to set up, actually. I'm kinda shocked.

Anyway, the exception seems to happen when `Inflation` (at L240) hit the following class:

![image](https://user-images.githubusercontent.com/10625/39157708-fa0b85ba-4710-11e8-968c-b600c906521f.png)

So I'm working on a repro for that.

**Comment by cstancu** [comment] 2018-04-23 23:30
You can try calling `java.lang.Class.getGenericInterfaces()` directly on that class from within your app, with the same setup. I expect you will get the same exception.

**Comment by nanodeath** [comment] 2018-04-23 23:51
Indeed, you're correct. I've created a Kotlin application from scratch and run the following:
```kotlin
import kotlin.reflect.jvm.internal.impl.protobuf.GeneratedMessageLite.*

fun main(args: Array<String>) {
    ExtendableMessage::class.java.genericInterfaces
}
```
which fails even on the standard Oracle JVM.

Correct me if I'm wrong, but this seems like an issue I should raise with JetBrains, correct?

**Comment by nanodeath** [comment] 2018-04-23 23:57
Cross-reference: https://youtrack.jetbrains.com/issue/KT-23962

**Comment by cstancu** [comment] 2018-04-24 00:01
That's correct since JetBrains is the developer of `kotlin-reflect`. Glad you got to the bottom of this. I will close this issue, but let us know if you are successful in running your app on SubstrateVM.

**Closed by cstancu** 2018-04-24 00:01 UTC
Labels: substrate
