### ISSUE TITLE
[Native Image] build for quarkus app.UnsupportedFeatureException: No instances of java.net.Inet4Address are allowed in the image heap as this class should be initialized at image runtime. 

### ISSUE THREAD

**Issue by mostafacs** [oracle/graal#2820] opened 2020-09-01 00:57 UTC
**Describe the issue**
Building image for quarkus project with java version 11 with MySQL an hibernate.

**Steps to reproduce the issue**
1. sorry, I can't put the repo here.
2. **mvn -Pnative clean package**
produced command 
``` /Library/Java/JavaVirtualMachines/graalvm-ce-java11-20.2.0/Contents/Home/bin/native-image -J-Djava.util.logging.manager=org.jboss.logmanager.LogManager -J-DCoordinatorEnvironmentBean.transactionStatusManagerEnable=false -J-Dsun.nio.ch.maxUpdateArraySize=100 -J-Dvertx.logger-delegate-factory-class-name=io.quarkus.vertx.core.runtime.VertxLogDelegateFactory -J-Dvertx.disableDnsResolver=true -J-Dio.netty.leakDetection.level=DISABLED -J-Dio.netty.allocator.maxOrder=1 -J-Duser.language=en -J-Dfile.encoding=UTF-8 --initialize-at-build-time= -H:InitialCollectionPolicy=com.oracle.svm.core.genscavenge.CollectionPolicy\$BySpaceAndTime -H:+JNI -jar sw-api-0.1.0-runner.jar -H:FallbackThreshold=0 -H:+ReportExceptionStackTraces -H:+AddAllCharsets -H:EnableURLProtocols=http,https --enable-all-security-services --no-server -H:-UseServiceLoaderFeature -H:+StackTrace sw-api-0.1.0-runner```

**Describe GraalVM and your environment:**
 - GraalVM version (latest snapshot builds can be found [here](https://github.com/graalvm/graalvm-ce-dev-builds/releases)), or commit id if built from source: **[vm-20.2.0]**
 - JDK major version: **[11]**
 - OS: **[macOS Catalina]**
 - Architecture: **[AMD64]**

Logs: 
```
02:39:25,970 INFO  [org.jbo.threads] JBoss Threads version 3.1.1.Final
[sw-api-0.1.0-runner:11913]     (clinit):   1,348.22 ms,  6.30 GB
[sw-api-0.1.0-runner:11913]   (typeflow):  36,044.93 ms,  6.30 GB
[sw-api-0.1.0-runner:11913]    (objects):  56,364.61 ms,  6.30 GB
[sw-api-0.1.0-runner:11913]   (features):   2,231.69 ms,  6.30 GB
[sw-api-0.1.0-runner:11913]     analysis: 101,536.88 ms,  6.30 GB
Error: No instances of java.net.Inet4Address are allowed in the image heap as this class should be initialized at image runtime. To see how this object got instantiated use -H:+TraceClassInitialization.
Detailed message:
Trace: Object was reached by 
	reading field java.net.InetSocketAddress$InetSocketAddressHolder.addr of
		constant java.net.InetSocketAddress$InetSocketAddressHolder@7af226dc reached by 
	reading field java.net.InetSocketAddress.holder of
		constant java.net.InetSocketAddress@202fa1c8 reached by 
	reading field io.netty.resolver.dns.SingletonDnsServerAddresses.address of
		constant io.netty.resolver.dns.SingletonDnsServerAddresses@128d5865 reached by 
	scanning method io.netty.resolver.dns.DefaultDnsServerAddressStreamProvider.defaultAddresses(DefaultDnsServerAddressStreamProvider.java:139)
Call path from entry point to io.netty.resolver.dns.DefaultDnsServerAddressStreamProvider.defaultAddresses(): 
	at io.netty.resolver.dns.DefaultDnsServerAddressStreamProvider.defaultAddresses(DefaultDnsServerAddressStreamProvider.java:139)
	at io.vertx.core.impl.resolver.DnsResolverProvider.<init>(DnsResolverProvider.java:91)
	at io.vertx.core.impl.VertxImpl.createDnsClient(VertxImpl.java:442)
	at com.oracle.svm.reflect.Vertx_createDnsClient_fdaf24b85d60109c8dc2c64f22ef6b3238cbc4ee_3399.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Method.java:566)
	at com.mysql.cj.jdbc.ha.MultiHostConnectionProxy$JdbcInterfaceProxy.invoke(MultiHostConnectionProxy.java:108)
	at com.sun.proxy.$Proxy332.getCancelTimeoutMutex(Unknown Source)
	at com.mysql.cj.CancelQueryTaskImpl$1.run(CancelQueryTaskImpl.java:88)
	at com.oracle.svm.core.thread.JavaThreads.threadStartRoutine(JavaThreads.java:517)
	at com.oracle.svm.core.posix.thread.PosixJavaThreads.pthreadStartRoutine(PosixJavaThreads.java:192)
	at com.oracle.svm.core.code.IsolateEnterStub.PosixJavaThreads_pthreadStartRoutine_e1f4a8c0039f8337338252cd8734f63a79b5e3df(generated:0)

com.oracle.svm.core.util.UserError$UserException: No instances of java.net.Inet4Address are allowed in the image heap as this class should be initialized at image runtime. To see how this object got instantiated use -H:+TraceClassInitialization.
Detailed message:
Trace: Object was reached by 
	reading field java.net.InetSocketAddress$InetSocketAddressHolder.addr of
		constant java.net.InetSocketAddress$InetSocketAddressHolder@7af226dc reached by 
	reading field java.net.InetSocketAddress.holder of
		constant java.net.InetSocketAddress@202fa1c8 reached by 
	reading field io.netty.resolver.dns.SingletonDnsServerAddresses.address of
		constant io.netty.resolver.dns.SingletonDnsServerAddresses@128d5865 reached by 
	scanning method io.netty.resolver.dns.DefaultDnsServerAddressStreamProvider.defaultAddresses(DefaultDnsServerAddressStreamProvider.java:139)
Call path from entry point to io.netty.resolver.dns.DefaultDnsServerAddressStreamProvider.defaultAddresses(): 
	at io.netty.resolver.dns.DefaultDnsServerAddressStreamProvider.defaultAddresses(DefaultDnsServerAddressStreamProvider.java:139)
	at io.vertx.core.impl.resolver.DnsResolverProvider.<init>(DnsResolverProvider.java:91)
	at io.vertx.core.impl.VertxImpl.createDnsClient(VertxImpl.java:442)
	at com.oracle.svm.reflect.Vertx_createDnsClient_fdaf24b85d60109c8dc2c64f22ef6b3238cbc4ee_3399.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Method.java:566)
	at com.mysql.cj.jdbc.ha.MultiHostConnectionProxy$JdbcInterfaceProxy.invoke(MultiHostConnectionProxy.java:108)
	at com.sun.proxy.$Proxy332.getCancelTimeoutMutex(Unknown Source)
	at com.mysql.cj.CancelQueryTaskImpl$1.run(CancelQueryTaskImpl.java:88)
	at com.oracle.svm.core.thread.JavaThreads.threadStartRoutine(JavaThreads.java:517)
	at com.oracle.svm.core.posix.thread.PosixJavaThreads.pthreadStartRoutine(PosixJavaThreads.java:192)
	at com.oracle.svm.core.code.IsolateEnterStub.PosixJavaThreads_pthreadStartRoutine_e1f4a8c0039f8337338252cd8734f63a79b5e3df(generated:0)

	at com.oracle.svm.core.util.UserError.abort(UserError.java:79)
	at com.oracle.svm.hosted.FallbackFeature.reportAsFallback(FallbackFeature.java:217)
	at com.oracle.svm.hosted.NativeImageGenerator.runPointsToAnalysis(NativeImageGenerator.java:765)
	at com.oracle.svm.hosted.NativeImageGenerator.doRun(NativeImageGenerator.java:555)
	at com.oracle.svm.hosted.NativeImageGenerator.lambda$run$0(NativeImageGenerator.java:468)
	at java.base/java.util.concurrent.ForkJoinTask$AdaptedRunnableAction.exec(ForkJoinTask.java:1407)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
Caused by: com.oracle.graal.pointsto.constraints.UnsupportedFeatureException: No instances of java.net.Inet4Address are allowed in the image heap as this class should be initialized at image runtime. To see how this object got instantiated use -H:+TraceClassInitialization.
Detailed message:
Trace: Object was reached by 
	reading field java.net.InetSocketAddress$InetSocketAddressHolder.addr of
		constant java.net.InetSocketAddress$InetSocketAddressHolder@7af226dc reached by 
	reading field java.net.InetSocketAddress.holder of
		constant java.net.InetSocketAddress@202fa1c8 reached by 
	reading field io.netty.resolver.dns.SingletonDnsServerAddresses.address of
		constant io.netty.resolver.dns.SingletonDnsServerAddresses@128d5865 reached by 
	scanning method io.netty.resolver.dns.DefaultDnsServerAddressStreamProvider.defaultAddresses(DefaultDnsServerAddressStreamProvider.java:139)
Call path from entry point to io.netty.resolver.dns.DefaultDnsServerAddressStreamProvider.defaultAddresses(): 
	at io.netty.resolver.dns.DefaultDnsServerAddressStreamProvider.defaultAddresses(DefaultDnsServerAddressStreamProvider.java:139)
	at io.vertx.core.impl.resolver.DnsResolverProvider.<init>(DnsResolverProvider.java:91)
	at io.vertx.core.impl.VertxImpl.createDnsClient(VertxImpl.java:442)
	at com.oracle.svm.reflect.Vertx_createDnsClient_fdaf24b85d60109c8dc2c64f22ef6b3238cbc4ee_3399.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Method.java:566)
	at com.mysql.cj.jdbc.ha.MultiHostConnectionProxy$JdbcInterfaceProxy.invoke(MultiHostConnectionProxy.java:108)
	at com.sun.proxy.$Proxy332.getCancelTimeoutMutex(Unknown Source)
	at com.mysql.cj.CancelQueryTaskImpl$1.run(CancelQueryTaskImpl.java:88)
	at com.oracle.svm.core.thread.JavaThreads.threadStartRoutine(JavaThreads.java:517)
	at com.oracle.svm.core.posix.thread.PosixJavaThreads.pthreadStartRoutine(PosixJavaThreads.java:192)
	at com.oracle.svm.core.code.IsolateEnterStub.PosixJavaThreads_pthreadStartRoutine_e1f4a8c0039f8337338252cd8734f63a79b5e3df(generated:0)

	at com.oracle.graal.pointsto.constraints.UnsupportedFeatures.report(UnsupportedFeatures.java:126)
	at com.oracle.svm.hosted.NativeImageGenerator.runPointsToAnalysis(NativeImageGenerator.java:762)
```

**Comment by gsmet** [comment] 2020-09-01 07:44
I think this is more something we need to fix in Quarkus.

Could you open a bug in our Quarkus tracker and provide a reproducer project? Thanks!

**Comment by dougxc** [comment] 2020-09-01 07:58
Closing in favor of bug in Quarkus tracker.

**Closed by dougxc** 2020-09-01 07:58 UTC
Labels: bug, native-image

**Comment by rpuch** [comment] 2020-09-09 08:45
The corresponding issue at Quarkus github seems to be https://github.com/quarkusio/quarkus/issues/11923
