### ISSUE TITLE
`native-image` hangs then crashes after a watchdog event 

### ISSUE THREAD

**Issue by pshirshov** [oracle/graal#2863] opened 2020-09-19 21:11 UTC
It's very hard to make a proper report for this issue.

Sometimes (like once per six runs) when I build my project on my CI `native-image` hangs then crashes with the following diagnostics:

[graal_crash.txt](https://github.com/oracle/graal/files/5250609/graal_crash.txt)

Normally my project takes about 1300 seconds to build on that machine (and about 6 minutes on my 3970x desktop). When this happens it takes about 40 minutes to get the crash dump.

Right before the crashdump `native-image` process seems to be stalling, while normally it always consumes at least one CPU.

```
bash-4.2# native-image --version
GraalVM Version 20.2.0 (Java Version 11.0.8)
```

**Comment by pshirshov** [comment] 2020-09-20 18:12
The stage log right before the crash:

```
[info] [app:1508]        setup:   7,236.91 ms,  2.70 GB
[info] [app:1508]     (clinit):  31,708.21 ms, 13.62 GB
[info] [app:1508]   (typeflow): 106,746.74 ms, 13.62 GB
[info] [app:1508]    (objects): 301,815.41 ms, 13.62 GB
[info] [app:1508]   (features):  34,425.50 ms, 13.62 GB
[info] [app:1508]     analysis: 522,923.75 ms, 13.62 GB
[info] [app:1508]     universe:  20,652.29 ms, 13.62 GB
[info] [app:1508]      (parse):  15,162.56 ms, 15.01 GB
[info] [app:1508]     (inline):  26,436.56 ms, 17.81 GB
[error] === Image generator watchdog detected no activity. This can be a sign of a deadlock during image building. Dumping all stack traces. Current time: Sun Sep 20 00:08:14 UTC 2020
```

**Comment by oubidar-Abderrahim** [comment] 2020-09-21 08:36
Could you please provide a reproducer and steps to see this issue

**Comment by oubidar-Abderrahim** [comment] 2020-09-23 10:37
This is might be related to #2283

**Comment by oubidar-Abderrahim** [comment] 2020-11-09 12:20
Since there was no reproducer to confirm, I will assume this is a duplicate of #2283 and close this issue.
If you think otherwise please re-open this ticket and provide a reproducer to confirm the issue.

**Closed by oubidar-Abderrahim** 2020-11-09 12:20 UTC
Labels: bug, native-image
