### ISSUE TITLE
Object type parameters in Java functions cannot be cast to Value in method body

### ISSUE THREAD

**Issue by Kolpa** [oracle/graal#1412] opened 2019-06-20 18:05 UTC
# What is this?
This issue describes a problem with typecasting in the graalvm polyglot api.

# When does it happen?
When using the polyglot api to call a function on java side that uses a type that is not `Value` but `Object`

# What happens?
The truffle runtime casts the parameter based on the target function definition. Since this is not of `Value` type a different Object gets constructed and returned.

# What's the problem?
The returned `Object` cannot be cast back to `Value` since it is not of that type anymore.
This results in not being able to interact with the given parameter.

We came across this issue when trying to build a `swing` gui from a polyglot Language.
In this context the problem naturally occurs when you construct a `swing` `LayoutConstraint` in a polyglot language and then try to add a `Component` with that `LayoutConstraint` to a parent `Component` since the [add](https://docs.oracle.com/javase/8/docs/api/java/awt/Container.html#add-java.awt.Component-java.lang.Object-) function that accepts layout constraints requires them to be of type `Object`.

# Example
There is an example in the following repository https://github.com/Kolpa/graalvm-polyglot-object-cast-sample

/cc @fniephaus

**Comment by chumer** [comment] 2019-07-30 10:10
Here is a smaller reproducible example:
```
  public static class BrokenCaller {
        public void thisIsFine(Value human) {
        }

        public void thisWillBreak(Object human) {
        }
    }

    public static void main(String[] args) {
        try (Context c = Context.newBuilder().allowHostAccess(HostAccess.ALL).build()) {
            c.getBindings("js").putMember("callerInstance", new BrokenCaller());
            c.eval("js", "class Human {\n" +
                            "  constructor(name) {\n" +
                            "    this.name = name;\n" +
                            "  }\n" +
                            "\n" +
                            "  hello() {\n" +
                            "    return this.name;\n" +
                            "  }\n" +
                            "}\n" +
                            "\n" +
                            "const humanInstance = new Human(\"timmy\");\n" +
                            "\n" +
                            "callerInstance.thisIsFine(humanInstance);\n" +
                            "callerInstance.thisWillBreak(humanInstance);");
        }
    }
```
This fails with:
```
Exception in thread "main" TypeError: invokeMember on JavaObject[com.oracle.truffle.js.scriptengine.Test$BrokenCaller@4eb7f003 (com.oracle.truffle.js.scriptengine.Test$BrokenCaller)] failed due to: UnsupportedTypeException
	at <js> :program(Unnamed:14:189-231)
	at org.graalvm.polyglot.Context.eval(Context.java:370)
	at com.oracle.truffle.js.scriptengine.Test.main(Test.java:39)

```

**Comment by chumer** [comment] 2019-07-30 14:02
I did some digging the problem is actually that we get a typeerror here. it seems that the ClassCastException that happens here `(Value) human;` is translated into an interop type error, when then gets translated into a JS error. In this example one would expect a host error pointing tot he cast location in the stack trace.

**Comment by woess** [comment] 2020-03-16 16:59
A fix for the ClassCastException issue has been merged to master and will be released as part of GraalVM 20.1.0.

**Comment by boris-spas** [comment] 2020-03-23 10:42
@woess Can this be closed than? Also, might be nice to link to the merge commit of the fix for future reference...

**Comment by woess** [comment] 2020-03-23 11:08
Fixed as of https://github.com/oracle/graal/commit/6c0d46e1631de1eabe39cbfcfe46a0ed30ba468f

**Closed by woess** 2020-03-23 11:08 UTC
Labels: truffle
