### ISSUE TITLE
Provide option to generate  native binaries for foreign processor architecture using native-image.

### ISSUE THREAD

**Issue by Prashanth-BC** [oracle/graal#906] opened 2019-01-11 11:26 UTC
It would be really great to have an option in native-image tool create the binaries to a different processor architecture than the host processor architecture.
For e.g., As of now, I could not find a way to generate native binaries for an aarch64/arm processor(running Linux)  using the native-image running Linux on x86_64 architecture.

native-image aap<br /> on  `Linux X86_64 / amd64` |    Cross compile for target  processor<br/>→<br/> running `Linux`. | app<br/>`Linux` running on `aarch64`
-- | -- | --

**Comment by cstancu** [comment] 2019-01-11 18:09
Duplicate of #407.

**Closed by cstancu** 2019-01-11 18:09 UTC
