### ISSUE TITLE
Implement method handle support for GraalVM Native Image

### ISSUE THREAD

**Issue by christianwimmer** [oracle/graal#2761] opened 2020-08-18 02:55 UTC

**Comment by kaspernielsen** [comment] 2020-09-26 10:55
Is the plan that every method handle created either via a field/constructor/executable or via java.lang.invoke.MethodHandles as part of an image's build time will work without any additional configuration?

**Comment by loicottet** [comment] 2020-09-28 08:32
Method handles will require some configuration. Whether it will be the existing reflection configuration or a separate one is still open.

**Comment by kaspernielsen** [comment] 2020-09-28 12:22
I'm not sure I understand why you need any configuration. MethodHandles that are strongly reachable after the image creation phase will in 99.99% of all cases be meant for invocation at runtime.

**Comment by christianwimmer** [comment] 2020-09-28 14:53
> MethodHandles that are strongly reachable after the image creation phase will in 99.99% of all cases be meant for invocation at runtime.

Yes, and such method handles will work without configuration. Same as reflection: if you have a `java.lang.reflect.Method` instance strongly reachable in the image heap, it works without further configuration.

But if you create new method method handle at run time, then you need configuration at image build time.

**Comment by kaspernielsen** [comment] 2020-09-28 15:58
Sounds great. I must admit the more I work with MHs the less my need for runtime support for them. Transformations via the various static methods on MethodHandles can mostly be done at image creation time. The only thing I actually miss is being able to bind object instances that cannot be created until runtime. For example, via MethodHandle#bindTo or MethodHandles#insertArguments

**Comment by felixbarny** [comment] 2020-09-29 07:45
Are invokedynamic instructions supported whose bootstrap method returns a dynamically computed `ConstantCallSite`?

**Comment by christianwimmer** [comment] 2020-09-30 17:24
When everything is finished, all aspects of method handles including bootstrap methods will be supported.

**Comment by galderz** [comment] 2020-12-04 15:59
I'm aware `MethodHandle` support is not complete, but there's something about the current status that found slightly surprising and wondered if in the future it'd be improved: @yrodiere was playing with `MethodHandle.Lookup.findVirtual` and it didn't work when used on a non-final method on a non-final class that was not extended in the codebase. You'd get error `...could not be reduced to at most a single call or single field access...`. The example worked when either the class or method was made `final`, but I wondered: if the class is not extended by anyone, couldn't the close world analysis deduce that the class and method were virtually `final`?

**Comment by dufoli** [comment] 2020-12-30 10:15
about how to proceed, I try to analyse how to implement it, am I right ?:
- add a new config file and register it in substratevm/src/com.oracle.svm.agent/src/com/oracle/svm/agent/NativeImageAgent.java
- add load of config in substratevm/src/com.oracle.svm.configure/src/com/oracle/svm/configure/config/ConfigurationSet.java
- create a methodHandleConfigurationParser which extend ConfigurationParser (json format and close to reflection one)
- TraceProcessor process methodHandle and create an AbstractProcessor for TraceProcessor
- add option for the config file in substratevm/src/com.oracle.svm.core/src/com/oracle/svm/core/configure/ConfigurationFiles.java
- add FallbackFeature to collect methodHandle invoke
- add MethodHandleFeature implements Feature to register methodHandle based of config.
- create JavaLandInvokeSubstitutions for : 
  - MethodHandles.Lookup.find*
  - or only MethodHandle.invoke* to call

**Comment by makingthematrix** [comment] 2021-01-02 12:09
Hi,
I got this issue while trying to compile a Scala app for Android. I managed to solve it by adding `--report-unsupported-elements-at-runtime` to the native image args list. 
One quick question: Is this only a compilation issue or is there a real risk that the app will crash in runtime? If it's the latter, is there anything I can do in my code to avoid it? Something I should be especially careful about?

**Comment by s0kil** [comment] 2021-01-02 15:38
@makingthematrix `--report-unsupported-elements-at-runtime` means instead of throwing errors at compile time, it will crash at runtime.

**Comment by makingthematrix** [comment] 2021-01-02 16:20
> @makingthematrix `--report-unsupported-elements-at-runtime` means instead of throwing errors at compile time, it will crash at runtime.

In my case it doesn't crash, so that argument basically fixed the problem. But I wrote only a small sample app to prove that it's possible to write Scala 2.13 on Android: https://github.com/makingthematrix/scala_android_dummyapp
So I'm wondering in what real situations this problem can bite me.

**Comment by johnynek** [comment] 2021-01-02 18:12
For Scala, this sbt plugin will handle replacing a use of method handles in the standard library:

https://github.com/scalameta/sbt-native-image

That may solve scala issues for the short term.

It would still be nice to not need a work around.

**Comment by loicottet** [comment] 2021-01-06 12:05
Full method handles support will be included in the 21.0 release. This will remove the need for `--report-unsupported-elements-at-runtime` and the various substitution hacks that were needed until now, including in the Scala library. Methods accessed through method handles will have to be registered in the same configuration file as the reflection methods, and this config will be able to be automatically generated through the Native Image agent.

**Comment by kaspernielsen** [comment] 2021-01-06 12:23
Is there any to get a warning/error if you create non-direct methods handles at runtime? 
I want to make sure that all my MethodHandles are created at build-time and not accidentally at runtime for maximum effiency.

**Comment by loicottet** [comment] 2021-01-15 13:24
@kaspernielsen sorry for the late reply. There is currently no way of checking that, but you can create an issue to request that feature.

**Closed** 2021-01-22 12:42 UTC
Labels: feature

**Comment by gustavonalle** [comment] 2021-02-24 11:19
Something seems to be missing from the MethodHandle support, getting:

```
Caused by: java.lang.ClassCastException: java.lang.invoke.BoundMethodHandle$Species_LL cannot be cast to java.lang.invoke.SimpleMethodHandle
	at com.oracle.svm.methodhandles.MethodHandleIntrinsic.execute(MethodHandleIntrinsic.java:254)
	at java.lang.invoke.MethodHandle.invokeBasic(MethodHandle.java:80)
	at java.lang.invoke.LambdaForm$NamedFunction.invokeWithArguments(LambdaForm.java:74)
	at java.lang.invoke.LambdaForm.interpretName(LambdaForm.java:981)
	at java.lang.invoke.LambdaForm.interpretWithArguments(LambdaForm.java:958)
	at java.lang.invoke.MethodHandle.invokeBasic(MethodHandle.java:171)
	at java.lang.invoke.MethodHandle.invokeBasic(MethodHandle.java:0)
	at java.lang.invoke.LambdaForm$MH/1417001346.invokeExact_MT(LambdaForm$MH)
	at org.apache.lucene.store.MMapDirectory.lambda$null$0(MMapDirectory.java:404)
	at java.security.AccessController.doPrivileged(AccessController.java:84)
	at org.apache.lucene.store.MMapDirectory.lambda$newBufferCleaner$1(MMapDirectory.java:402)
	... 47 more
```

The exception above is when trying to invoke  the method ```invokeCleaner``` from ```sun.misc.Unsafe```:

```java
final Class<?> unsafeClass = Class.forName("sun.misc.Unsafe");
final MethodHandle unmapper = lookup.findVirtual(unsafeClass, "invokeCleaner", methodType(void.class, ByteBuffer.class));
final Field f = unsafeClass.getDeclaredField("theUnsafe");
f.setAccessible(true);
final Object theUnsafe = f.get(null);
unmapper.bindTo(theUnsafe);

//...
unmapper.invokeExact(buffer);
````

**Comment by loicottet** [comment] 2021-02-24 15:53
@gustavonalle can you open a separate issue for this bug? I'll look into it.

**Comment by gustavonalle** [comment] 2021-02-24 18:25
@loicottet sure, I have a reproducer inside Quarkus only, when trying to create a reproducer for GraalVM directly, got caught in https://github.com/oracle/graal/issues/3241, could you take a look?

**Comment by christianwimmer** [comment] 2023-06-30 08:43
@revintec "Panama" is an umbrella term for many different features. But most of them are currently not support on Native Image, because they are still incubator / preview and changing quickly. So nothing is "specifically disabled", but when you enable preview features and use them then you can get all sorts of strange errors like the one you observed.

We are actively working on the foreign call interface of Panama. For other parts like the vector API we have not started any implementation at all.

**Comment by dreamlike-ocean** [comment] 2023-10-29 05:45
> @revintec "Panama" is an umbrella term for many different features. But most of them are currently not support on Native Image, because they are still incubator / preview and changing quickly. So nothing is "specifically disabled", but when you enable preview features and use them then you can get all sorts of strange errors like the one you observed.
> 
> We are actively working on the foreign call interface of Panama. For other parts like the vector API we have not started any implementation at all.

Does it support vector api in native-image now？

**Comment by christianwimmer** [comment] 2023-10-30 18:01
> Does it support vector api in native-image now?

No, there is no work on vector API support for native image. It does not seem likely that the vector API moves out of the incubator status anytime soon.

**Comment by revintec** [comment] 2024-01-22 18:16
> https://mail.openjdk.org/pipermail/panama-dev/2023-July/019510.html
> 
> Foreign Function & Memory API will (very likely) be stable in Java 22, I'm looking forward to seeing it on GraalVM.

@christianwimmer it seems FFM is finally stable in JDK22 https://openjdk.org/jeps/454
can we have a interoperable FFM in GraalVM for JDK 22(due March 19, 2024 according to release calendar)?

currently I have to cook every native call in my java program to suit native-image... the code was littered with `if(inImageCode())...` and since the calling method(methodHandle vs annotated native method for native-image) is not compatible, signature incompatibilities, and the native-image version doesn't support `errno`(it seems there is no way to support that currently). very painful and ugly

**Comment by christianwimmer** [comment] 2024-01-22 19:26
There is some support for the Foreign Function & Memory API in the upcoming GraalVM for JDK 22, but not everything is working yet and it is not optimize yet, i.e., the parts that are working are likely to be slow compared to the HotSpot VM.

**Comment by revintec** [comment] 2024-02-21 16:15
@christianwimmer from what I've read here
https://www.graalvm.org/release-notes/JDK_21/
it seems GraalVM 21.0.2 should already support FFM
<img width="1001" alt="image" src="https://github.com/oracle/graal/assets/8952734/7ac02d5d-d21a-40bc-8f9f-127a1b5f0e5f">
however there is no documentation, and using standard FFM won't work
```
========================================================================================================================
GraalVM Native Image: Generating 'mainkt' (executable)...
========================================================================================================================
[1/8] Initializing...                                                                                    (3.2s @ 0.10GB)
 Java version: 21.0.2+13-LTS, vendor version: Oracle GraalVM 21.0.2+13.1
 Graal compiler: optimization level: 2, target machine: armv8-a, PGO: off
 C compiler: cc (apple, arm64, 14.0.0)
 Garbage collector: Serial GC (max heap size: 80% of RAM)
 1 user-specific feature(s):
 - com.oracle.svm.thirdparty.gson.GsonFeature
------------------------------------------------------------------------------------------------------------------------
Build resources:
 - 12.09GB of memory (75.6% of 16.00GB system memory, determined at start)
 - 10 thread(s) (100.0% of 10 available processor(s), determined at start)
[2/8] Performing analysis...  [*****]                                                                    (8.9s @ 0.32GB)
    4,298 reachable types   (75.8% of    5,673 total)
    4,734 reachable fields  (50.2% of    9,433 total)
   21,441 reachable methods (50.5% of   42,462 total)
    1,385 types,   249 fields, and 1,006 methods registered for reflection
       57 types,    57 fields, and    52 methods registered for JNI access
        4 native libraries: -framework Foundation, dl, pthread, z

Error: Error loading a referenced type: com.oracle.svm.hosted.substitute.DeletedElementException: Unsupported method jdk.internal.loader.NativeLibrary.findEntry0(long, String) is reachable
To diagnose the issue, you can add the option --report-unsupported-elements-at-runtime. The unsupported element is then reported at run time when it is accessed the first time.
Error encountered while parsing jdk.internal.loader.RawNativeLibraries$RawNativeLibraryImpl.find(RawNativeLibraries.java:170)
Parsing context:
   at jdk.internal.loader.NativeLibrary.lookup(NativeLibrary.java:49)
   at jdk.internal.foreign.SystemLookup.lambda$libLookup$8(SystemLookup.java:112)
   at jdk.internal.foreign.SystemLookup.find(SystemLookup.java:139)
   at MainKt.downcallHandle(Main.kt:24)
   at MainKt.main(Main.kt:31)
   at static root method.(Unknown Source)

Detailed message:

------------------------------------------------------------------------------------------------------------------------
                        1.2s (9.2% of total time) in 85 GCs | Peak RSS: 0.82GB | CPU load: 5.31
========================================================================================================================
Finished generating 'mainkt' in 12.3s.
```
reference code:
```kotlin
import java.lang.foreign.*
import java.lang.foreign.Linker.Option
import java.lang.foreign.Linker.Option.captureStateLayout
import java.lang.foreign.MemoryLayout.PathElement

val linker=Linker.nativeLinker()
val opts=arrayOf(Option.captureCallState("errno"))
val _errno=captureStateLayout()
val errno=_errno.varHandle(PathElement.groupElement("errno"))

fun downcallHandle(name:String,fn:FunctionDescriptor,vararg opts:Option)=linker.defaultLookup().find(name).orElse(null)?.let{
    linker.downcallHandle(it,fn,*opts)
}


fun main(args:Array<String>) {

    val mh=downcallHandle("geteuid",FunctionDescriptor.of(ValueLayout.JAVA_INT,*arrayOfNulls<MemoryLayout>(0)),*opts)

    val arena = Arena.ofConfined()
    val state = arena.allocate(_errno)

    println(mh!!.invokeExact(state)as Int)
    val aa=errno.get(state)as Int
    println(aa)
}
```

**Comment by dreamlike-ocean** [comment] 2024-02-21 16:24
> @christianwimmer from what I've read here
> https://www.graalvm.org/release-notes/JDK_21/
> it seems GraalVM 21.0.2 should already support FFM
> <img width="1001" alt="image" src="https://github.com/oracle/graal/assets/8952734/7ac02d5d-d21a-40bc-8f9f-127a1b5f0e5f">
> however there is no documentation, and using standard FFM won't work
> ```
> ========================================================================================================================
> GraalVM Native Image: Generating 'mainkt' (executable)...
> ========================================================================================================================
> [1/8] Initializing...                                                                                    (3.2s @ 0.10GB)
>  Java version: 21.0.2+13-LTS, vendor version: Oracle GraalVM 21.0.2+13.1
>  Graal compiler: optimization level: 2, target machine: armv8-a, PGO: off
>  C compiler: cc (apple, arm64, 14.0.0)
>  Garbage collector: Serial GC (max heap size: 80% of RAM)
>  1 user-specific feature(s):
>  - com.oracle.svm.thirdparty.gson.GsonFeature
> ------------------------------------------------------------------------------------------------------------------------
> Build resources:
>  - 12.09GB of memory (75.6% of 16.00GB system memory, determined at start)
>  - 10 thread(s) (100.0% of 10 available processor(s), determined at start)
> [2/8] Performing analysis...  [*****]                                                                    (8.9s @ 0.32GB)
>     4,298 reachable types   (75.8% of    5,673 total)
>     4,734 reachable fields  (50.2% of    9,433 total)
>    21,441 reachable methods (50.5% of   42,462 total)
>     1,385 types,   249 fields, and 1,006 methods registered for reflection
>        57 types,    57 fields, and    52 methods registered for JNI access
>         4 native libraries: -framework Foundation, dl, pthread, z
> 
> Error: Error loading a referenced type: com.oracle.svm.hosted.substitute.DeletedElementException: Unsupported method jdk.internal.loader.NativeLibrary.findEntry0(long, String) is reachable
> To diagnose the issue, you can add the option --report-unsupported-elements-at-runtime. The unsupported element is then reported at run time when it is accessed the first time.
> Error encountered while parsing jdk.internal.loader.RawNativeLibraries$RawNativeLibraryImpl.find(RawNativeLibraries.java:170)
> Parsing context:
>    at jdk.internal.loader.NativeLibrary.lookup(NativeLibrary.java:49)
>    at jdk.internal.foreign.SystemLookup.lambda$libLookup$8(SystemLookup.java:112)
>    at jdk.internal.foreign.SystemLookup.find(SystemLookup.java:139)
>    at MainKt.downcallHandle(Main.kt:24)
>    at MainKt.main(Main.kt:31)
>    at static root method.(Unknown Source)
> 
> Detailed message:
> 
> ------------------------------------------------------------------------------------------------------------------------
>                         1.2s (9.2% of total time) in 85 GCs | Peak RSS: 0.82GB | CPU load: 5.31
> ========================================================================================================================
> Finished generating 'mainkt' in 12.3s.
> ```
> reference code:
> ```kotlin
> import java.lang.foreign.*
> import java.lang.foreign.Linker.Option
> import java.lang.foreign.Linker.Option.captureStateLayout
> import java.lang.foreign.MemoryLayout.PathElement
> 
> val linker=Linker.nativeLinker()
> val opts=arrayOf(Option.captureCallState("errno"))
> val _errno=captureStateLayout()
> val errno=_errno.varHandle(PathElement.groupElement("errno"))
> 
> fun downcallHandle(name:String,fn:FunctionDescriptor,vararg opts:Option)=linker.defaultLookup().find(name).orElse(null)?.let{
>     linker.downcallHandle(it,fn,*opts)
> }
> 
> 
> fun main(args:Array<String>) {
> 
>     val mh=downcallHandle("geteuid",FunctionDescriptor.of(ValueLayout.JAVA_INT,*arrayOfNulls<MemoryLayout>(0)),*opts)
> 
>     val arena = Arena.ofConfined()
>     val state = arena.allocate(_errno)
> 
>     println(mh!!.invokeExact(state)as Int)
>     val aa=errno.get(state)as Int
>     println(aa)
> }
> ```

并非全部的符号lookup都会有支持，请参考https://www.graalvm.org/latest/reference-manual/native-image/dynamic-features/foreign-interface/这篇文档
以及可以看看这个https://github.com/dreamlike-ocean/Panama-native-image/blob/master/src/main/java/org/example/PanamaDemo.java 至少这东西在Linux x86 64上跑的很好

**Comment by revintec** [comment] 2024-02-21 17:39
> 并非全部的符号lookup都会有支持，请参考[https://www.graalvm.org/latest/reference-manual/native-image/dynamic-features/foreign-interface/这篇文档](https://www.graalvm.org/latest/reference-manual/native-image/dynamic-features/foreign-interface/%E8%BF%99%E7%AF%87%E6%96%87%E6%A1%A3) 以及可以看看这个https://github.com/dreamlike-ocean/Panama-native-image/blob/master/src/main/java/org/example/PanamaDemo.java 至少这东西在Linux x86 64上跑的很好

thanks for your swift reply! it's of a great help
to summarize, current version can't use `defaultLookup`, but use `loaderLookup`, as seen from here
https://github.com/dreamlike-ocean/Panama-native-image/blob/fb4af048a53a5cb189e072acc38f9ed5320531ae/src/main/java/org/example/PanamaDemo.java#L59
