### ISSUE TITLE
"Address family not supported by protocol" on socket impl creation

### ISSUE THREAD

**Issue by acogoluegnes** [oracle/graal#1696] opened 2019-09-20 11:55 UTC
I'm getting `java.net.SocketException: Address family not supported by protocol` errors with an image built with `native-image`. This happens only on certain environments, on the creation of the socket implementation. Here's a simple program to reproduce:

```java
import javax.net.SocketFactory;
import java.net.Socket;

public class TcpClient {

    public static void main(String[] args) throws Exception {
        Socket socket = SocketFactory.getDefault().createSocket();
        socket.setTcpNoDelay(true);
    }

}
```

```
$ java -version
openjdk version "1.8.0_222"
OpenJDK Runtime Environment (build 1.8.0_222-20190711120915.buildslave.jdk8u-src-tar--b08)
OpenJDK 64-Bit GraalVM CE 19.2.0.1 (build 25.222-b08-jvmci-19.2-b02, mixed mode)
$ javac TcpClient.java
$ native-image TcpClient
```

```
$ ./tcpclient 
Exception in thread "main" java.net.SocketException: Address family not supported by protocol
	at java.net.Socket.createImpl(Socket.java:460)
	at java.net.Socket.getImpl(Socket.java:520)
	at java.net.Socket.setTcpNoDelay(Socket.java:980)
	at TcpClient.main(TcpClient.java:8)
```

I can't provide the exact configuration of an environment where the problem occurs, but here is more info:

```
$ uname -a
Linux ... 4.15.0-60-generic #67~16.04.1-Ubuntu SMP Mon Aug 26 08:57:33 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
```

IPv6 seems disabled on it, even though some configuration refers to it:

```
$ more /etc/hosts
127.0.0.1 localhost [...]

# The following lines are desirable for IPv6 capable hosts
::1 localhost ip6-localhost ip6-loopback [...]
...
```

There's obviously some misconfiguration on the system, but I don't think this is the only reason, as the same program run with the JRE does work.

Note forcing the use of IPv4 on image creation makes the error disappear:

```
$ native-image -Djava.net.preferIPv4Stack=true TcpClient
```

Unfortunately, this makes the native image incompatible with IPv6 only hosts.

Let me know if more information is needed.

**Comment by cstancu** [comment] 2019-09-21 10:53
@acogoluegnes this may be an issue in our `java.net.PlainSocketImpl.socketCreate()` translation and it may go away when using the JNI platform. The JNI platform is an experimental feature for now, but you can enable it by passing `-Dsvm.platform='org.graalvm.nativeimage.impl.InternalPlatform$LINUX_JNI_AMD64` to the `native-image`. If you try this it is probably best to build a GraalVM distribution from the latest master.

**Comment by acogoluegnes** [comment] 2019-09-23 08:11
@cstancu Thanks for the answer. I tried the following on 19.2.0.1:

```
native-image -Dsvm.platform='org.graalvm.nativeimage.impl.InternalPlatform$LINUX_JNI_AMD64' TcpClient
```

And the following on the latest master (30a318fcf4b312985b1387faffd45d631b9654b8):

```
mx native-image -Dsvm.platform='org.graalvm.nativeimage.impl.InternalPlatform$LINUX_JNI_AMD64' TcpClient
```

Both generated images do not throw the `Address family not supported by protocol` error any longer. I'll do more testing with the target program that actually uses the socket.

That's great the error does not show up with the JNI platform, but do you plan to fix the issue with the current translation? Let me know if there's anything I can do to help narrow down the issue.

**Comment by cstancu** [comment] 2019-09-23 09:53
@acogoluegnes we currently focus on finishing up the JNI platform integration. We'll flip the switch soon and make JNI platform the default, whereas the current translation will be deprecated and eventually removed.

**Comment by dmlloyd** [comment] 2019-09-23 12:31
That's a shame, considering that using the JNI platform imposes a dependency on `libjava`, which is difficult to distribute without a JDK making standalone images less practical.  Also considering that with the upcoming Panama, the current translation really represents a closer modeling of what "the future" could be.  And considering the possibility that including JNI may increase image size.  The kicker is that Red Hat has been contributing substantial amounts of translations for JDK 11.

**Comment by acogoluegnes** [comment] 2019-09-24 10:01
@cstancu I had another round of tests, with the target application this time, on latest master (9e61d33792c5a2c59c77a13620c9af59928cd3a8). The command to build the image is the following (from [the original `Makefile`](https://github.com/rabbitmq/rabbitmq-perf-test/blob/c6abf52e93816e621689e199e63b6aaaa0dcaeb7/Makefile#L30-L38))
```
mx native-image -jar perf-test.jar -H:Features="com.rabbitmq.perf.NativeImageFeature" \
            --initialize-at-build-time=io.micrometer \
            --initialize-at-build-time=com.rabbitmq.client \
            --initialize-at-build-time=org.eclipse.jetty \
            --initialize-at-build-time=javax.servlet \
            --initialize-at-build-time=org.slf4j \
            --no-fallback \
            -H:IncludeResources="rabbitmq-perf-test.properties" \
            -Dsvm.platform='org.graalvm.nativeimage.impl.InternalPlatform$LINUX_JNI_AMD64'
```

I don't see the `Address family not supported by protocol` error anymore, the application seems to be working properly (it is a stress tool for RabbitMQ, it uses client sockets).

I didn't have to copy `libjava`, so unless I miss something, @dmlloyd's statement does not apply to this case.

**Comment by thomaswue** [comment] 2019-09-24 11:33
@dmlloyd Please focus the discussion on technical merits of the possible solutions. Whether or not RedHat has contributed patches to one of the solutions is irrelevant.

The main advantage of the JNI platform based solution is that it will enable the support of several different JDK versions (i.e., 8, 11, 13) in parallel. Specifically, such support will be bug-for-bug compatible and with much less effort than what is currently required.

The dependency on libjava can be linked in statically. There is the possibility to use the results from the static analysis to reduce the portion of libjava that needs to be linked. There is an expectation of increased image size for small programs.

If the way the JDK is handling this area changes, we will pick up such change. The main point of the solution is to have less technical difference to the JDK and therefore less maintenance overhead.

There are trade-offs between the current and proposed JNI solution, but so far I think the benefits of the proposed JNI solution weigh far stronger than the downsides.

**Comment by olpaw** [comment] 2019-09-24 12:21
> using the JNI platform imposes a dependency on libjava

@dmlloyd the bits that are taken from e.g. libjava and others are **statically linked into the native image**. This will not generate a runtime dependency to any jdk shared library. You can verify this yourself on master.
```
graal/substratevm> mx native-image -Dsvm.platform='org.graalvm.nativeimage.impl.InternalPlatform$LINUX_JNI_AMD64' HelloJava -H:Log=InvokeCC 
[hellojava:32187]    classlist:   2,451.73 ms
[hellojava:32187]        (cap):     658.19 ms
[hellojava:32187]        setup:   1,982.65 ms
[hellojava:32187]   (typeflow):   3,308.13 ms
[hellojava:32187]    (objects):   2,885.43 ms
[hellojava:32187]   (features):     245.79 ms
[hellojava:32187]     analysis:   6,621.94 ms
[hellojava:32187]     (clinit):      98.08 ms
[hellojava:32187]     universe:     314.38 ms
[hellojava:32187]      (parse):     520.17 ms
[hellojava:32187]     (inline):   1,201.31 ms
[hellojava:32187]    (compile):   5,275.92 ms
[hellojava:32187]      compile:   7,353.68 ms
[hellojava:32187]        image:     462.03 ms
[Use -Dgraal.LogFile=<path> to redirect Graal log output to a file.]
[thread:25] scope: ForkJoinPool-4-worker-1
  [thread:25] scope: ForkJoinPool-4-worker-1.InvokeCC
  Running command: cc -v -o /home/pwoegere/OLabs/issues/GR-18330/graal/substratevm/hellojava -z noexecstack -Wl,--gc-sections -Wl,-x -L/tmp/SVM-2360200452922082943 -L/home/pwoegere/OLabs/issues/GR-18330/graal/vm/mxbuild/linux-amd64/GRAALVM_SVM_BGU/graalvm-svm-19.3.0-dev/jre/lib -L/home/pwoegere/OLabs/issues/GR-18330/graal/vm/mxbuild/linux-amd64/GRAALVM_SVM_BGU/graalvm-svm-19.3.0-dev/jre/lib/svm/clibraries/linux-amd64 -L/home/pwoegere/OLabs/issues/GR-18330/graal/substratevm/mxbuild/linux-amd64/SVM_HOSTED_NATIVE/linux-amd64 /tmp/SVM-2360200452922082943/hellojava.o /home/pwoegere/OLabs/issues/GR-18330/graal/substratevm/mxbuild/linux-amd64/SVM_HOSTED_NATIVE/linux-amd64/libffi.a /home/pwoegere/OLabs/issues/GR-18330/graal/vm/mxbuild/linux-amd64/GRAALVM_SVM_BGU/graalvm-svm-19.3.0-dev/jre/lib/libjava.a /home/pwoegere/OLabs/issues/GR-18330/graal/substratevm/mxbuild/linux-amd64/SVM_HOSTED_NATIVE/linux-amd64/liblibchelper.a /home/pwoegere/OLabs/issues/GR-18330/graal/substratevm/mxbuild/linux-amd64/SVM_HOSTED_NATIVE/linux-amd64/libstrictmath.a /home/pwoegere/OLabs/issues/GR-18330/graal/substratevm/mxbuild/linux-amd64/SVM_HOSTED_NATIVE/linux-amd64/libjvm.a /home/pwoegere/OLabs/issues/GR-18330/graal/vm/mxbuild/linux-amd64/GRAALVM_SVM_BGU/graalvm-svm-19.3.0-dev/jre/lib/libnio.a /home/pwoegere/OLabs/issues/GR-18330/graal/vm/mxbuild/linux-amd64/GRAALVM_SVM_BGU/graalvm-svm-19.3.0-dev/jre/lib/libzip.a /home/pwoegere/OLabs/issues/GR-18330/graal/vm/mxbuild/linux-amd64/GRAALVM_SVM_BGU/graalvm-svm-19.3.0-dev/jre/lib/libnet.a -lm -lpthread -ldl -lpthread -lrt
... more linking related log output ...
[hellojava:32187]        write:     102.98 ms
[hellojava:32187]      [total]:  19,507.62 ms
```
then run:
```
> LD_DEBUG=bindings ./hellojava
```
you will see that no jdk shared library gets used at image runtime.

**Comment by dmlloyd** [comment] 2019-09-25 13:41
> The dependency on libjava can be linked in statically. There is the possibility to use the results from the static analysis to reduce the portion of libjava that needs to be linked. There is an expectation of increased image size for small programs.

Are you thinking of compiling into sections (and/or asking upstream OpenJDK to compile into sections) to be able to use linker-based DCE?  Or something proprietary to Graal to make those determinations?

**Comment by christianwimmer** [comment] 2019-09-25 19:23
@dmlloyd we use `--gc-sections` for linker-based DCE: https://github.com/oracle/graal/blob/f5a0d23cb5978261309157bb078bc1a67dbba17d/substratevm/src/com.oracle.svm.hosted/src/com/oracle/svm/hosted/image/NativeBootImageViaCC.java#L85
The static libraries that we ship as part of GraalVM are built with the compiler flags to put each method into a separate section.

**Comment by dmlloyd** [comment] 2019-09-25 19:35
Great! That explains a lot. I have some testing ahead of me I guess. :)

**Comment by christianwimmer** [comment] 2019-09-25 19:40
It's heavily work in progress, as you can see from the commits to this repository. On JDK 8, most of our tests already pass with the JNI platform. For JDK 11, there is still a few weeks of work to do.

**Comment by humank** [comment] 2019-10-16 08:39
I faced the similar problem, developed a quarkus application, recompiled by native-image, and pack it as an AWS Lambda custom runtime but get the same exeception: 

`Caused by: java.net.SocketException: Address family not supported by protocol
at com.oracle.svm.core.posix.PosixJavaNIOSubstitutions$Util_sun_nio_ch_Net.handleSocketError(PosixJavaNIOSubstitutions.java:1336)
at sun.nio.ch.Net.socket0(Net.java:809)
at sun.nio.ch.Net.serverSocket(Net.java:415)
at sun.nio.ch.ServerSocketChannelImpl.<init>(ServerSocketChannelImpl.java:88)
at sun.nio.ch.SelectorProviderImpl.openServerSocketChannel(SelectorProviderImpl.java:56)
at java.nio.channels.ServerSocketChannel.open(ServerSocketChannel.java:108)
at org.xnio.nio.NioXnioWorker.createTcpConnectionServer(NioXnioWorker.java:172)
at org.xnio.XnioWorker.createStreamConnectionServer(XnioWorker.java:310)
at io.undertow.Undertow.start(Undertow.java:193)`

Based on @cstancu solution, i add the parameter while re-compiling: 
`mvn clean package -Pnative  -DskipTests=true -Dnative=true -Dsvm.platform=org.graalvm.nativeimage.impl.InternalPlatform$LINUX_JNI_AMD64`

I'm curious to know what can I do to diagnose root cause.

**Comment by christianwimmer** [comment] 2019-10-16 21:45
@humank If you switch to the JNI platform, you must at least get a different exception stack trace since `PosixJavaNIOSubstitutions` is no longer used with the JNI platform.

**Comment by cstancu** [comment] 2020-09-25 05:20
The originally reported problem was fixed by switching to JNI platform.

**Closed by cstancu** 2020-09-25 05:20 UTC
Labels: native-image
