### ISSUE TITLE
linker cannot find symbols to edit the windows registry: LNK1120 unresolved extnerals

### ISSUE THREAD

**Issue by kristofdho** [oracle/graal#2363] opened 2020-04-19 12:23 UTC
**Describe the issue**
The linker seems the have issues finding the symbols required for editing the registry through `java.util.prefs.Preferences`. Causing a fatal error LNK1120: x unresolved externals.
These externals should be available in advapi32.lib, which is available to the CL command.

**Steps to reproduce the issue**

1. input file:
```java
import java.util.prefs.Preferences;

public class RegistryPOC {
    public static void main(String[] args) {
        Preferences.userNodeForPackage(RegistryPOC.class);
    }
}
```
2. compile:
```
javac RegistryPOC.java
native-image RegistryPOC
```

**Describe GraalVM and your environment:**
 - GraalVM version: **CE 20.0.0** also tried with building from source commit 014f2c819fd025e8f64fd7718ef23ecbeedca484
 - JDK major version: **11**
 - OS: **windows 10**
 - Architecture: **amd64(?)**

**More details**
output of `native-image --verbose RegistryPOC`
```
C:\registry-poc>native-image --verbose RegistryPOC
Executing [
C:\Program Files\Java\graalvm-ce-java11-20.0.0\bin\java.exe \
-XX:+UnlockExperimentalVMOptions \
-XX:+EnableJVMCI \
-Dtruffle.TrustAllTruffleRuntimeProviders=true \
-Dtruffle.TruffleRuntime=com.oracle.truffle.api.impl.DefaultTruffleRuntime \
-Dgraalvm.ForcePolyglotInvalid=true \
-Dgraalvm.locatorDisabled=true \
-Dsubstratevm.IgnoreGraalVersionCheck=true \
-Djava.lang.invoke.stringConcat=BC_SB \
--add-exports \
jdk.internal.vm.ci/jdk.vm.ci.runtime=ALL-UNNAMED \
--add-exports \
jdk.internal.vm.ci/jdk.vm.ci.code=ALL-UNNAMED \
--add-exports \
jdk.internal.vm.ci/jdk.vm.ci.aarch64=ALL-UNNAMED \
--add-exports \
jdk.internal.vm.ci/jdk.vm.ci.amd64=ALL-UNNAMED \
--add-exports \
jdk.internal.vm.ci/jdk.vm.ci.meta=ALL-UNNAMED \
--add-exports \
jdk.internal.vm.ci/jdk.vm.ci.hotspot=ALL-UNNAMED \
--add-exports \
jdk.internal.vm.ci/jdk.vm.ci.services=ALL-UNNAMED \
--add-exports \
jdk.internal.vm.ci/jdk.vm.ci.common=ALL-UNNAMED \
--add-exports \
jdk.internal.vm.ci/jdk.vm.ci.code.site=ALL-UNNAMED \
--add-exports \
jdk.internal.vm.ci/jdk.vm.ci.code.stack=ALL-UNNAMED \
--add-opens \
jdk.internal.vm.compiler/org.graalvm.compiler.debug=ALL-UNNAMED \
--add-opens \
jdk.internal.vm.compiler/org.graalvm.compiler.nodes=ALL-UNNAMED \
--add-opens \
jdk.unsupported/sun.reflect=ALL-UNNAMED \
--add-opens \
java.base/jdk.internal.module=ALL-UNNAMED \
--add-opens \
java.base/jdk.internal.ref=ALL-UNNAMED \
--add-opens \
java.base/jdk.internal.reflect=ALL-UNNAMED \
--add-opens \
java.base/java.io=ALL-UNNAMED \
--add-opens \
java.base/java.lang=ALL-UNNAMED \
--add-opens \
java.base/java.lang.reflect=ALL-UNNAMED \
--add-opens \
java.base/java.lang.invoke=ALL-UNNAMED \
--add-opens \
java.base/java.lang.ref=ALL-UNNAMED \
--add-opens \
java.base/java.net=ALL-UNNAMED \
--add-opens \
java.base/java.nio=ALL-UNNAMED \
--add-opens \
java.base/java.nio.file=ALL-UNNAMED \
--add-opens \
java.base/java.security=ALL-UNNAMED \
--add-opens \
java.base/javax.crypto=ALL-UNNAMED \
--add-opens \
java.base/java.util=ALL-UNNAMED \
--add-opens \
java.base/java.util.concurrent.atomic=ALL-UNNAMED \
--add-opens \
java.base/sun.security.x509=ALL-UNNAMED \
--add-opens \
java.base/jdk.internal.logger=ALL-UNNAMED \
--add-opens \
org.graalvm.sdk/org.graalvm.nativeimage.impl=ALL-UNNAMED \
--add-opens \
org.graalvm.sdk/org.graalvm.polyglot=ALL-UNNAMED \
--add-opens \
org.graalvm.truffle/com.oracle.truffle.polyglot=ALL-UNNAMED \
--add-opens \
org.graalvm.truffle/com.oracle.truffle.api.impl=ALL-UNNAMED \
-XX:+UseJVMCINativeLibrary \
-Xss10m \
-Xms1g \
-Xmx13516272432 \
-Duser.country=US \
-Duser.language=en \
-Djava.awt.headless=true \
-Dorg.graalvm.version=20.0.0 \
-Dorg.graalvm.config=CE \
-Dcom.oracle.graalvm.isaot=true \
-Djava.system.class.loader=com.oracle.svm.hosted.NativeImageSystemClassLoader \
-Xshare:off \
--module-path \
C:\Program Files\Java\graalvm-ce-java11-20.0.0\lib\truffle\truffle-api.jar \
-javaagent:C:\Program Files\Java\graalvm-ce-java11-20.0.0\lib\svm\builder\svm.jar \
-Djdk.internal.lambda.disableEagerInitialization=true \
-Djdk.internal.lambda.eagerlyInitialize=false \
-Djava.lang.invoke.InnerClassLambdaMetafactory.initializeLambdas=false \
-cp \
C:\Program Files\Java\graalvm-ce-java11-20.0.0\lib\svm\builder\objectfile.jar;C:\Program Files\Java\graalvm-ce-java11-20.0.0\lib\svm\builder\pointsto.jar;C:\Program Files\Java\graalvm-ce-java11-20.0.0\lib\svm\builder\svm.jar \
com.oracle.svm.hosted.NativeImageGeneratorRunner$JDK9Plus \
-imagecp \
C:\Program Files\Java\graalvm-ce-java11-20.0.0\lib\svm\builder\objectfile.jar;C:\Program Files\Java\graalvm-ce-java11-20.0.0\lib\svm\builder\pointsto.jar;C:\Program Files\Java\graalvm-ce-java11-20.0.0\lib\svm\builder\svm.jar;C:\Program Files\Java\graalvm-ce-java11-20.0.0\lib\svm\library-support.jar;C:\registry-poc \
-H:Path=C:\registry-poc \
-H:CLibraryPath=C:\Program Files\Java\graalvm-ce-java11-20.0.0\lib\svm\clibraries\windows-amd64 \
-H:Class=RegistryPOC \
-H:Name=registrypoc
]
[registrypoc:12740]    classlist:   1,289.85 ms,  1.00 GB
[registrypoc:12740]        (cap):   2,405.54 ms,  1.28 GB
[registrypoc:12740]        setup:   4,394.74 ms,  1.28 GB
[registrypoc:12740]   (typeflow):   5,675.12 ms,  1.53 GB
[registrypoc:12740]    (objects):   4,924.72 ms,  1.53 GB
[registrypoc:12740]   (features):     311.97 ms,  1.53 GB
[registrypoc:12740]     analysis:  11,144.06 ms,  1.53 GB
[registrypoc:12740]     (clinit):     209.04 ms,  1.53 GB
[registrypoc:12740]     universe:     580.77 ms,  1.53 GB
[registrypoc:12740]      (parse):   1,105.12 ms,  1.89 GB
[registrypoc:12740]     (inline):   1,073.51 ms,  1.89 GB
[registrypoc:12740]    (compile):   7,201.24 ms,  1.89 GB
[registrypoc:12740]      compile:  10,058.98 ms,  1.89 GB
[registrypoc:12740]        image:   1,141.33 ms,  1.89 GB
[registrypoc:12740]        write:     410.04 ms,  1.89 GB
Fatal error: java.lang.RuntimeException: java.lang.RuntimeException: There was an error linking the native image: Linker command exited with 2

Linker command executed:
CL /MD /Zi /PDBSTRIPPED /FeC:\registry-poc\registrypoc.exe C:\Users\KRISTO~1\AppData\Local\Temp\SVM-3761573275975877800\registrypoc.obj 'C:\Program Files\Java\graalvm-ce-java11-20.0.0\lib\net.lib' 'C:\Program Files\Java\graalvm-ce-java11-20.0.0\lib\java.lib' 'C:\Program Files\Java\graalvm-ce-java11-20.0.0\lib\zip.lib' 'C:\Program Files\Java\graalvm-ce-java11-20.0.0\lib\nio.lib' 'C:\Program Files\Java\graalvm-ce-java11-20.0.0\lib\svm\clibraries\windows-amd64\ffi.lib' 'C:\Program Files\Java\graalvm-ce-java11-20.0.0\lib\svm\clibraries\windows-amd64\strictmath.lib' 'C:\Program Files\Java\graalvm-ce-java11-20.0.0\lib\svm\clibraries\windows-amd64\jvm.lib' 'C:\Program Files\Java\graalvm-ce-java11-20.0.0\lib\svm\clibraries\windows-amd64\libchelper.lib' 'C:\Program Files\Java\graalvm-ce-java11-20.0.0\lib\net.lib' 'C:\Program Files\Java\graalvm-ce-java11-20.0.0\lib\java.lib' 'C:\Program Files\Java\graalvm-ce-java11-20.0.0\lib\zip.lib' 'C:\Program Files\Java\graalvm-ce-java11-20.0.0\lib\nio.lib' 'C:\Program Files\Java\graalvm-ce-java11-20.0.0\lib\svm\clibraries\windows-amd64\ffi.lib' 'C:\Program Files\Java\graalvm-ce-java11-20.0.0\lib\svm\clibraries\windows-amd64\strictmath.lib' 'C:\Program Files\Java\graalvm-ce-java11-20.0.0\lib\svm\clibraries\windows-amd64\jvm.lib' 'C:\Program Files\Java\graalvm-ce-java11-20.0.0\lib\svm\clibraries\windows-amd64\libchelper.lib' '/link /INCREMENTAL:NO /NODEFAULTLIB:LIBCMT' '/LIBPATH:C:\Program Files\Java\graalvm-ce-java11-20.0.0\lib' '/LIBPATH:C:\Program Files\Java\graalvm-ce-java11-20.0.0\lib\svm\clibraries\windows-amd64' advapi32.lib ws2_32.lib secur32.lib iphlpapi.lib userenv.lib

Linker command ouput:
Microsoft (R) C/C++ Optimizing Compiler Version 19.25.28614 for x64
Copyright (C) Microsoft Corporation.  All rights reserved.

cl : Command line warning D9002 : ignoring unknown option '/PDBSTRIPPED'
Microsoft (R) Incremental Linker Version 14.25.28614.0
Copyright (C) Microsoft Corporation.  All rights reserved.

/debug
/out:C:\registry-poc\registrypoc.exe
/INCREMENTAL:NO /NODEFAULTLIB:LIBCMT
"/LIBPATH:C:\Program Files\Java\graalvm-ce-java11-20.0.0\lib"
"/LIBPATH:C:\Program Files\Java\graalvm-ce-java11-20.0.0\lib\svm\clibraries\windows-amd64"
advapi32.lib
ws2_32.lib
secur32.lib
iphlpapi.lib
userenv.lib
C:\Users\KRISTO~1\AppData\Local\Temp\SVM-3761573275975877800\registrypoc.obj
"C:\Program Files\Java\graalvm-ce-java11-20.0.0\lib\net.lib"
"C:\Program Files\Java\graalvm-ce-java11-20.0.0\lib\java.lib"
"C:\Program Files\Java\graalvm-ce-java11-20.0.0\lib\zip.lib"
"C:\Program Files\Java\graalvm-ce-java11-20.0.0\lib\nio.lib"
"C:\Program Files\Java\graalvm-ce-java11-20.0.0\lib\svm\clibraries\windows-amd64\ffi.lib"
"C:\Program Files\Java\graalvm-ce-java11-20.0.0\lib\svm\clibraries\windows-amd64\strictmath.lib"
"C:\Program Files\Java\graalvm-ce-java11-20.0.0\lib\svm\clibraries\windows-amd64\jvm.lib"
"C:\Program Files\Java\graalvm-ce-java11-20.0.0\lib\svm\clibraries\windows-amd64\libchelper.lib"
"C:\Program Files\Java\graalvm-ce-java11-20.0.0\lib\net.lib"
"C:\Program Files\Java\graalvm-ce-java11-20.0.0\lib\java.lib"
"C:\Program Files\Java\graalvm-ce-java11-20.0.0\lib\zip.lib"
"C:\Program Files\Java\graalvm-ce-java11-20.0.0\lib\nio.lib"
"C:\Program Files\Java\graalvm-ce-java11-20.0.0\lib\svm\clibraries\windows-amd64\ffi.lib"
"C:\Program Files\Java\graalvm-ce-java11-20.0.0\lib\svm\clibraries\windows-amd64\strictmath.lib"
"C:\Program Files\Java\graalvm-ce-java11-20.0.0\lib\svm\clibraries\windows-amd64\jvm.lib"
"C:\Program Files\Java\graalvm-ce-java11-20.0.0\lib\svm\clibraries\windows-amd64\libchelper.lib"
jvm.lib(JvmFuncs.obj) : warning LNK4099: PDB 'vc140.pdb' was not found with 'jvm.lib(JvmFuncs.obj)' or at 'C:\registry-poc\vc140.pdb'; linking object as if no debug info
libchelper.lib(cpuid.obj) : warning LNK4099: PDB 'vc140.pdb' was not found with 'libchelper.lib(cpuid.obj)' or at 'C:\registry-poc\vc140.pdb'; linking object as if no debug info
   Creating library C:\registry-poc\registrypoc.lib and object C:\registry-poc\registrypoc.exp
registrypoc.obj : error LNK2001: unresolved external symbol Java_java_util_prefs_WindowsPreferences_WindowsRegCloseKey
registrypoc.obj : error LNK2001: unresolved external symbol Java_java_util_prefs_WindowsPreferences_WindowsRegCreateKeyEx
registrypoc.obj : error LNK2001: unresolved external symbol Java_java_util_prefs_WindowsPreferences_WindowsRegOpenKey
C:\registry-poc\registrypoc.exe : fatal error LNK1120: 3 unresolved externals

        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
        at java.base/java.util.concurrent.ForkJoinTask.getThrowableException(ForkJoinTask.java:600)
        at java.base/java.util.concurrent.ForkJoinTask.get(ForkJoinTask.java:1006)
        at com.oracle.svm.hosted.NativeImageGenerator.run(NativeImageGenerator.java:462)
        at com.oracle.svm.hosted.NativeImageGeneratorRunner.buildImage(NativeImageGeneratorRunner.java:357)
        at com.oracle.svm.hosted.NativeImageGeneratorRunner.build(NativeImageGeneratorRunner.java:501)
        at com.oracle.svm.hosted.NativeImageGeneratorRunner.main(NativeImageGeneratorRunner.java:115)
        at com.oracle.svm.hosted.NativeImageGeneratorRunner$JDK9Plus.main(NativeImageGeneratorRunner.java:528)
Caused by: java.lang.RuntimeException: There was an error linking the native image: Linker command exited with 2

Linker command executed:
CL /MD /Zi /PDBSTRIPPED /FeC:\registry-poc\registrypoc.exe C:\Users\KRISTO~1\AppData\Local\Temp\SVM-3761573275975877800\registrypoc.obj 'C:\Program Files\Java\graalvm-ce-java11-20.0.0\lib\net.lib' 'C:\Program Files\Java\graalvm-ce-java11-20.0.0\lib\java.lib' 'C:\Program Files\Java\graalvm-ce-java11-20.0.0\lib\zip.lib' 'C:\Program Files\Java\graalvm-ce-java11-20.0.0\lib\nio.lib' 'C:\Program Files\Java\graalvm-ce-java11-20.0.0\lib\svm\clibraries\windows-amd64\ffi.lib' 'C:\Program Files\Java\graalvm-ce-java11-20.0.0\lib\svm\clibraries\windows-amd64\strictmath.lib' 'C:\Program Files\Java\graalvm-ce-java11-20.0.0\lib\svm\clibraries\windows-amd64\jvm.lib' 'C:\Program Files\Java\graalvm-ce-java11-20.0.0\lib\svm\clibraries\windows-amd64\libchelper.lib' 'C:\Program Files\Java\graalvm-ce-java11-20.0.0\lib\net.lib' 'C:\Program Files\Java\graalvm-ce-java11-20.0.0\lib\java.lib' 'C:\Program Files\Java\graalvm-ce-java11-20.0.0\lib\zip.lib' 'C:\Program Files\Java\graalvm-ce-java11-20.0.0\lib\nio.lib' 'C:\Program Files\Java\graalvm-ce-java11-20.0.0\lib\svm\clibraries\windows-amd64\ffi.lib' 'C:\Program Files\Java\graalvm-ce-java11-20.0.0\lib\svm\clibraries\windows-amd64\strictmath.lib' 'C:\Program Files\Java\graalvm-ce-java11-20.0.0\lib\svm\clibraries\windows-amd64\jvm.lib' 'C:\Program Files\Java\graalvm-ce-java11-20.0.0\lib\svm\clibraries\windows-amd64\libchelper.lib' '/link /INCREMENTAL:NO /NODEFAULTLIB:LIBCMT' '/LIBPATH:C:\Program Files\Java\graalvm-ce-java11-20.0.0\lib' '/LIBPATH:C:\Program Files\Java\graalvm-ce-java11-20.0.0\lib\svm\clibraries\windows-amd64' advapi32.lib ws2_32.lib secur32.lib iphlpapi.lib userenv.lib

Linker command ouput:
Microsoft (R) C/C++ Optimizing Compiler Version 19.25.28614 for x64
Copyright (C) Microsoft Corporation.  All rights reserved.

cl : Command line warning D9002 : ignoring unknown option '/PDBSTRIPPED'
Microsoft (R) Incremental Linker Version 14.25.28614.0
Copyright (C) Microsoft Corporation.  All rights reserved.

/debug
/out:C:\registry-poc\registrypoc.exe
/INCREMENTAL:NO /NODEFAULTLIB:LIBCMT
"/LIBPATH:C:\Program Files\Java\graalvm-ce-java11-20.0.0\lib"
"/LIBPATH:C:\Program Files\Java\graalvm-ce-java11-20.0.0\lib\svm\clibraries\windows-amd64"
advapi32.lib
ws2_32.lib
secur32.lib
iphlpapi.lib
userenv.lib
C:\Users\KRISTO~1\AppData\Local\Temp\SVM-3761573275975877800\registrypoc.obj
"C:\Program Files\Java\graalvm-ce-java11-20.0.0\lib\net.lib"
"C:\Program Files\Java\graalvm-ce-java11-20.0.0\lib\java.lib"
"C:\Program Files\Java\graalvm-ce-java11-20.0.0\lib\zip.lib"
"C:\Program Files\Java\graalvm-ce-java11-20.0.0\lib\nio.lib"
"C:\Program Files\Java\graalvm-ce-java11-20.0.0\lib\svm\clibraries\windows-amd64\ffi.lib"
"C:\Program Files\Java\graalvm-ce-java11-20.0.0\lib\svm\clibraries\windows-amd64\strictmath.lib"
"C:\Program Files\Java\graalvm-ce-java11-20.0.0\lib\svm\clibraries\windows-amd64\jvm.lib"
"C:\Program Files\Java\graalvm-ce-java11-20.0.0\lib\svm\clibraries\windows-amd64\libchelper.lib"
"C:\Program Files\Java\graalvm-ce-java11-20.0.0\lib\net.lib"
"C:\Program Files\Java\graalvm-ce-java11-20.0.0\lib\java.lib"
"C:\Program Files\Java\graalvm-ce-java11-20.0.0\lib\zip.lib"
"C:\Program Files\Java\graalvm-ce-java11-20.0.0\lib\nio.lib"
"C:\Program Files\Java\graalvm-ce-java11-20.0.0\lib\svm\clibraries\windows-amd64\ffi.lib"
"C:\Program Files\Java\graalvm-ce-java11-20.0.0\lib\svm\clibraries\windows-amd64\strictmath.lib"
"C:\Program Files\Java\graalvm-ce-java11-20.0.0\lib\svm\clibraries\windows-amd64\jvm.lib"
"C:\Program Files\Java\graalvm-ce-java11-20.0.0\lib\svm\clibraries\windows-amd64\libchelper.lib"
jvm.lib(JvmFuncs.obj) : warning LNK4099: PDB 'vc140.pdb' was not found with 'jvm.lib(JvmFuncs.obj)' or at 'C:\registry-poc\vc140.pdb'; linking object as if no debug info
libchelper.lib(cpuid.obj) : warning LNK4099: PDB 'vc140.pdb' was not found with 'libchelper.lib(cpuid.obj)' or at 'C:\registry-poc\vc140.pdb'; linking object as if no debug info
   Creating library C:\registry-poc\registrypoc.lib and object C:\registry-poc\registrypoc.exp
registrypoc.obj : error LNK2001: unresolved external symbol Java_java_util_prefs_WindowsPreferences_WindowsRegCloseKey
registrypoc.obj : error LNK2001: unresolved external symbol Java_java_util_prefs_WindowsPreferences_WindowsRegCreateKeyEx
registrypoc.obj : error LNK2001: unresolved external symbol Java_java_util_prefs_WindowsPreferences_WindowsRegOpenKey
C:\registry-poc\registrypoc.exe : fatal error LNK1120: 3 unresolved externals

        at com.oracle.svm.hosted.image.NativeBootImageViaCC.handleLinkerFailure(NativeBootImageViaCC.java:424)
        at com.oracle.svm.hosted.image.NativeBootImageViaCC.write(NativeBootImageViaCC.java:399)
        at com.oracle.svm.hosted.NativeImageGenerator.doRun(NativeImageGenerator.java:657)
        at com.oracle.svm.hosted.NativeImageGenerator.lambda$run$0(NativeImageGenerator.java:445)
        at java.base/java.util.concurrent.ForkJoinTask$AdaptedRunnableAction.exec(ForkJoinTask.java:1407)
        at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
        at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
        at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
        at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
        at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:177)
Error: Image build request failed with exit status 1
com.oracle.svm.driver.NativeImage$NativeImageError: Image build request failed with exit status 1
        at com.oracle.svm.driver.NativeImage.showError(NativeImage.java:1527)
        at com.oracle.svm.driver.NativeImage.build(NativeImage.java:1289)
        at com.oracle.svm.driver.NativeImage.performBuild(NativeImage.java:1250)
        at com.oracle.svm.driver.NativeImage.main(NativeImage.java:1209)
        at com.oracle.svm.driver.NativeImage$JDK9Plus.main(NativeImage.java:1707)
```

**Comment by aprelkin** [comment] 2020-04-19 14:55
I have the exactly same issue, with the same configuration

**Comment by pquiring** [comment] 2020-04-25 19:03
The pref.lib is missing from the link operation.
You can add the library with this option for now:
-H:NativeLinkerOption=prefs.lib

**Comment by kristofdho** [comment] 2020-04-25 23:20
> The prefs.lib is missing from the link operation.
> You can add the library with this option for now:
> -H:NativeLinkerOption=prefs.lib

This does seem to work indeed, thank you!

**Comment by jogrill** [comment] 2020-05-14 13:43
> The prefs.lib is missing from the link operation.
> You can add the library with this option for now:
> -H:NativeLinkerOption=prefs.lib

I have the same error with the same configuration, but unfortunately this workaround does not work for me. 

`native-image -H:NativeLinkerOption=prefs.lib RegistryPOC`
returns the same error output as without the linker option

also an absolute path to prefs.lib did not work.

Does anyone have an idea what the problem is? Thanks in advance!

**Comment by mickfrancis** [comment] 2020-05-14 14:23
> > The prefs.lib is missing from the link operation.
> > You can add the library with this option for now:
> > -H:NativeLinkerOption=prefs.lib
> 
> I have the same error with the same configuration, but unfortunately this workaround does not work for me.
> 
> `native-image -H:NativeLinkerOption=prefs.lib RegistryPOC`
> returns the same error output as without the linker option
> 
> also an absolute path to prefs.lib did not work.
> 
> Does anyone have an idea what the problem is? Thanks in advance!

Same issue here, I'm afraid - would love to have a solution...

**Comment by kristofdho** [comment] 2020-07-27 12:23
If i'm not mistaken, this should be fixed by https://github.com/oracle/graal/commit/b04d3d30908f54f11239ecda6252e965f50a6c19

**Comment by gradinac** [comment] 2020-07-27 16:50
@kristofdho You are correct, that should indeed solve the linking errors caused by using `java.util.prefs`. If you want, you can test it with the latest nightly GraalVM build available from https://github.com/graalvm/graalvm-ce-dev-builds/releases

**Comment by abamoshe** [comment] 2020-09-11 00:05
> The prefs.lib is missing from the link operation.
> You can add the library with this option for now:
> -H:NativeLinkerOption=prefs.lib

thanks, i had the same issue and this fixed it

**Comment by gradinac** [comment] 2020-09-28 00:59
As the patch for this issue is now on master, I'll close it. Let us know if you run into this error again.

**Closed by gradinac** 2020-09-28 00:59 UTC
Labels: bug, native-image
