### ISSUE TITLE
Native dependencies should not be downloaded when building with --no-native

### ISSUE THREAD

**Issue by galderz** [oracle/graal#2221] opened 2020-03-05 11:25 UTC
`mx build --no-native` should not attempt to download native-only dependencies.

If one invokes `mx build --no-native`, it tries to download libffi sources even though these sources won't really be used, since the native building is skipped:

```
Downloading LIBFFI_SOURCES
Building libffi [depends on LIBFFI_SOURCES]
...
[skipping libffi]
```

**Comment by galderz** [comment] 2020-03-05 11:31
This might be an `mx` bug rather than native image one. Let me know what's the best place to report this.

**Comment by dougxc** [comment] 2020-03-05 12:40
When creating the build schedule, all projects, dists, library and custom dependencies are considered as roots. The schedule then just sorts them such that dependencies are built before things that depend on them. There is currently no easy way to see that a dependency is a native-only dependency.

I'm not saying that this is not fixable just that it's not trivial. If you'd like to have a go at fixing it, I can give you some pointers.

**Comment by zakkak** [comment] 2020-04-24 12:46
Hi @dougxc could you please provide me some pointers to have a look at it?

**Comment by dougxc** [comment] 2020-04-24 20:26
The code that creates the build schedule is here: https://github.com/graalvm/mx/blob/28e6a5c6b77df50886d83fc79ec09a689a13d348/mx.py#L13563-L13583
You need to build the schedule graph and then:
* remove all tasks on a path from a root to an `AbstractNativeBuildTask`
* remove all tasks dominated by an `AbstractNativeBuildTask`

**Comment by zakkak** [comment] 2020-04-27 13:15
Thanks @dougxc!

For clarification:

>     * remove all tasks on a path from a root to an `AbstractNativeBuildTask`

This is to avoid building projects/dists/libraries with broken dependencies, right?
Other than that it does not result in fetching _native_ dependencies.

>     * remove all tasks dominated by an `AbstractNativeBuildTask`

This is the actual removal of the unnecessary dependencies.

Additionally, when you say "remove all tasks" you mean all tasks that are not also dependencies of any non-native project. 
E.g., if a library `X` is used by both a native project `A` and a non-native project `B`, then we still need `X` in the build schedule (to satisfy `B`'s dependency on `X`).

**Comment by dougxc** [comment] 2020-04-27 13:28
> ☝️ This is to avoid building projects/dists/libraries with broken dependencies, right?
Correct.

> ☝️ This is the actual removal of the unnecessary dependencies.

Yes.

> Additionally, when you say "remove all tasks" you mean all tasks that are not also dependencies of any non-native project.

Yes.

**Comment by fernando-valdez** [comment] 2024-01-19 04:03
closing this ticket as the dev provided a solution

**Closed by fernando-valdez** 2024-01-19 04:03 UTC
Labels: bug

**Comment by zakkak** [comment] 2024-01-19 06:56
> closing this ticket as the dev provided a solution

FTR the proposed solution is implemented in https://github.com/graalvm/mx/pull/213 which we didn't end up merging. Nevertheless, the issue is now out-dated so closing this issue is OK. If necessary we will open a new one with up to date details.
