### ISSUE TITLE
Native image compile issue

### ISSUE THREAD

**Issue by gjevardat** [oracle/graal#1096] opened 2019-03-21 16:26 UTC
Hello using the rc-13 version I have issues with META-INF/services. 
I read that now it is handled automatically like described in 
        graal/substratevm/src/com.oracle.svm.hosted/src/com/oracle/svm/hosted/NativeImageGeneratorRunner.java
      

or maybe I miss something and I have to write this json file by myself like here : https://github.com/cstancu/native-image-service-loader-demo

My exact error is
```java
 com.oracle.svm.core.util.UserError$UserException: Error loading service implementations for service `javax.persistence.spi.PersistenceProvider` from URL `jar:file:/Users/greg/IdeaProjects/graalopenjpa/target/graalopenjpa-1.0-SNAPSHOT-jar-with-dependencies.jar!/META-INF/services/javax.persistence.spi.PersistenceProvider`

Caused by: java.io.FileNotFoundException: JAR entry META-INF/services/javax.persistence.spi.PersistenceProvider not found in /Users/greg/IdeaProjects/graalopenjpa/target/graalopenjpa-1.0-SNAPSHOT-jar-with-dependencies.jar
	at sun.net.www.protocol.jar.JarURLConnection.connect(JarURLConnection.java:144)
	at sun.net.www.protocol.jar.JarURLConnection.getInputStream(JarURLConnection.java:152)
	at java.net.URL.openStream(URL.java:1045)
	at com.oracle.svm.hosted.ServiceLoaderFeature.parseServiceResource(ServiceLoaderFeature.java:247)
	at com.oracle.svm.hosted.ServiceLoaderFeature.handleType(ServiceLoaderFeature.java:164)
	... 11 more
```

I'am sure my fat jar build with maven plugin contains all dependencies. 

I'am using
```
graalvm-ce-1.0.0-rc13/Contents/Home/bin/native-image --allow-incomplete-classpath --enable-all-security-services --verbose --report-unsupported-elements-at-runtime -H:+ReportExceptionStackTraces -H:IncludeResources=META-INF/services/*.* -jar  graalopenjpa-1.0-SNAPSHOT-jar-with-dependencies.jar
```
to generate the image

**Comment by cstancu** [comment] 2019-03-21 18:52
You can disable the automated service loader feature with `-H:-UseServiceLoaderFeature`. If you can share a reproducible example I can take a closer look.

**Comment by gjevardat** [comment] 2019-03-21 20:19
Thanks a lot I'll share the code later.
By deactivating the option you mentioned -H:-UseServiceLoaderFeature I could successfully AOT compile the whole Jar. And then at runtime I have something not that surprising:
```java
Exception in thread "main" java.lang.RuntimeException: Failed to instantiate database factory due to [Failed to load provider from META-INF/services]
	at gaia.cu7.om.dal.DbVariStore.configure(DbVariStore.java:972)
	at MyMain.main(MyMain.java:22)
Caused by: javax.persistence.PersistenceException: Failed to load provider from META-INF/services
	at javax.persistence.spi.PersistenceProviderResolverHolder$DefaultPersistenceProviderResolver.getPersistenceProviders(PersistenceProviderResolverHolder.java:115)
	at javax.persistence.Persistence.getProviders(Persistence.java:275)
	at javax.persistence.Persistence.createEntityManagerFactory(Persistence.java:88)
	at gaia.cu7.om.dal.DbVariStore.configure(DbVariStore.java:913)
	... 1 more
Caused by: java.lang.ClassNotFoundException: org.apache.openjpa.persistence.PersistenceProviderImpl
	at com.oracle.svm.core.hub.ClassForNameSupport.forName(ClassForNameSupport.java:51)
	at java.lang.Class.forName(DynamicHub.java:1063)
	at org.apache.geronimo.osgi.locator.ProviderLocator.loadClass(ProviderLocator.java:195)
	at org.apache.geronimo.osgi.locator.ProviderLocator.locateServiceClasses(ProviderLocator.java:524)
	at org.apache.geronimo.osgi.locator.ProviderLocator.getServices(ProviderLocator.java:315)
	at javax.persistence.spi.PersistenceProviderResolverHolder$DefaultPersistenceProviderResolver.getPersistenceProviders(PersistenceProviderResolverHolder.java:108)
	... 4 more
```

**Comment by gjevardat** [comment] 2019-03-21 20:54
Here is my project:
https://github.com/gjevardat/graalopenjpa.git

To reproduce above stack trace:
```bash
mvn package
cd target
native-image --allow-incomplete-classpath --enable-all-security-services --verbose --report-unsupported-elements-at-runtime -H:+ReportExceptionStackTraces -H:IncludeResources=META-INF/services/*.* -H:-UseServiceLoaderFeature -jar  graalopenjpa-1.0-SNAPSHOT-jar-with-dependencies.jar
```

**Comment by cstancu** [comment] 2019-03-21 21:59
I just realized you were using rc13. I tried with rc14 and the image builds succesfully (without the need for `-H:-UseServiceLoaderFeature`). However when I run the image I get:
```
$ ./graalopenjpa-1.0-SNAPSHOT-jar-with-dependencies 
Exception in thread "main" <openjpa-3.0.0-r422266:1833209 fatal user error> org.apache.openjpa.persistence.ArgumentException: localized message key: bad-new-brokerfactory; substitutions: [<<openjpa-3.0.0-r422266:1833209 fatal user error> org.apache.openjpa.util.UserException: localized message key: bad-brokerfactory-class; substitutions: [org.apache.openjpa.jdbc.kernel.JDBCBrokerFactory]>]
	at org.apache.openjpa.kernel.Bootstrap.newBrokerFactory(Bootstrap.java:76)
	at org.apache.openjpa.persistence.PersistenceProviderImpl.getBrokerFactory(PersistenceProviderImpl.java:149)
	at org.apache.openjpa.persistence.PersistenceProviderImpl.createEntityManagerFactory(PersistenceProviderImpl.java:92)
	at org.apache.openjpa.persistence.PersistenceProviderImpl.createEntityManagerFactory(PersistenceProviderImpl.java:155)
	at org.apache.openjpa.persistence.PersistenceProviderImpl.createEntityManagerFactory(PersistenceProviderImpl.java:63)
	at javax.persistence.Persistence.createEntityManagerFactory(Persistence.java:79)
	at MyMain.main(MyMain.java:21)
Caused by: <openjpa-3.0.0-r422266:1833209 fatal user error> org.apache.openjpa.persistence.ArgumentException: localized message key: bad-brokerfactory-class; substitutions: [org.apache.openjpa.jdbc.kernel.JDBCBrokerFactory]
	at org.apache.openjpa.kernel.Bootstrap.getFactoryClass(Bootstrap.java:166)
	at org.apache.openjpa.kernel.Bootstrap.invokeFactory(Bootstrap.java:118)
	at org.apache.openjpa.kernel.Bootstrap.newBrokerFactory(Bootstrap.java:66)
	... 6 more
Caused by: java.lang.ClassNotFoundException: org.apache.openjpa.jdbc.kernel.JDBCBrokerFactory
	at com.oracle.svm.core.hub.ClassForNameSupport.forName(ClassForNameSupport.java:51)
	at java.lang.Class.forName(DynamicHub.java:1083)
	at org.apache.openjpa.kernel.Bootstrap.getFactoryClass(Bootstrap.java:164)
	... 8 more
```

It looks like you need some reflection configuration.

**Comment by gjevardat** [comment] 2019-03-22 06:08
Thanks. Super it's moving forward. No idea on how to configure class reflection, I'll try to find examples and docs

**Comment by cstancu** [comment] 2019-04-20 01:34
You can read the [reflection documentation](https://github.com/oracle/graal/blob/master/substratevm/REFLECTION.md#reflection-on-substrate-vm) for details. This [blog article](https://medium.com/graalvm/instant-netty-startup-using-graalvm-native-image-generation-ed6f14ff7692) also has some details regarding reflection configuration. I will close this issue as the originally reported problem cannot be reproduced. Please feel free to open another issue if you encounter further problems.

**Closed by cstancu** 2019-04-20 01:34 UTC
Labels: substrate
