### ISSUE TITLE
[LLVM] Possible deadlock when two threads are trying to access a critical section

### ISSUE THREAD

**Issue by roxanan-adyen** [oracle/graal#4349] opened 2022-02-23 08:13 UTC
**Describe GraalVM and your environment :**
 - GraalVM version: **22.0.0**
 - **EE**
 - JDK version: **JDK11**
 - OS and OS Version: **macOS bigSur**
 - Architecture: **amd64**
 - The output of `java -Xinternalversion`:
```
 **Java HotSpot(TM) 64-Bit Server VM (11.0.14+8-LTS-jvmci-22.0-b03) for bsd-amd64 JRE (11.0.14+8-LTS-jvmci-22.0-b03), built on Jan  2 2022 15:02:19 by "graal1" with gcc 4.2.1 Compatible Apple LLVM 11.0.0 (clang-1100.0.33.17)**
```

**Have you verified this issue still happens when using the latest snapshot?**
Only tried it with 22.0.0

**Describe the issue**
I have a small C++ program where I try to use std::shared_mutex. This is built as a library that is loaded by a java app. In the java app, I create two threads that will execute the C++ function. At some point, they hang. Please note that it's not all the time, you need to run it a few times.

**How to compile the LLVM bitcode that causes the problem**
 Compile C++ lib:
 ```
 $GRAALVM_MANAGED_LLVM_TOOLCHAIN/clang++ -fPIC -shared -O1 -g deadlock.cpp -lgraalvm-llvm -o deadlock.so
 ```
Where 
```
export GRAALVM_MANAGED_LLVM_TOOLCHAIN=$($GRAALVM_HOME/bin/lli --print-toolchain-path --llvm.managed)
```

**Code snippet or code repository that reproduces the problem**
C++ code: deadlock.cpp:
```
#include <iostream>
#include <mutex>
#include <shared_mutex>
#include <graalvm/llvm/polyglot.h>
#include <pthread.h>

#ifdef __cplusplus
extern "C" {
#endif

std::shared_mutex _mutex;

void exec() {
        long i = 0;
        while (i++ < 10000000000000) {
                long j = 0;
                while (j++ < 100000000000000000) {
                        long a = 1234 * 47364;
                }
        }

}

void shared_section() {
        std::shared_lock<std::shared_mutex> lock(_mutex);
        exec();
}

void unique_section() {
         std::unique_lock<std::shared_mutex> lock(_mutex);
         exec();
         std::cout << "Finished" << "\n";
}
#ifdef __cplusplus
}
#endif
```
Java:
```
import java.io.*;
import org.graalvm.polyglot.*;

class Java2Threads {
       private static void thread_function() {
       try {
                       System.out.println("Java tid " + Thread.currentThread().getId());
                      
                       cpart.invokeMember("shared_section");
                       cpart.invokeMember("unique_section");
               } catch (Exception e) {
                       System.out.println("Exception " + Thread.currentThread().getId());
                       e.printStackTrace();
                       System.exit(-1);
               }
       }

       public static void main(String[] args) throws Exception {
               Context polyglot = Context.newBuilder().allowAllAccess(true).allowIO(true).option("llvm.managed", "true").build();
                       //option("inspect", "true").option("llvm.lazyParsing", "false").option("inspect.Suspend", "false").option("inspect.WaitAttached","true").build();
               File file = new File("deadlock.so");
               Source source = Source.newBuilder("llvm", file).build();
               cpart = polyglot.eval(source);

               Thread myThread = new Thread(() -> { // Lambda Expression
                       thread_function();
               });

               Thread myThread2 = new Thread(() -> { // Lambda Expression
                       thread_function();
               });

               myThread.start();
               myThread2.start();
               myThread.join();
               myThread2.join();
        }
}
```

**Steps to reproduce the problem**
Please include both build steps as well as run steps
1. $GRAALVM_MANAGED_LLVM_TOOLCHAIN/clang++ -std=c++17 -fPIC -shared -O1 -g deadlock.cpp -lgraalvm-llvm -o deadlock.so
2. javac Java2Threads.java && java Java2Threads
 Try java Java2Threads multiple times, at some point threads will hang. 
     
**Expected behavior**
```
Java tid 21
Java tid 22
Finished
Finished
```
Execution will end
**Additional context**
Note: I tried calling pthread_create before creating the threads, but it didn't solve the issue.

**Comment by rschatz** [comment] 2022-02-24 11:00
Thanks for the detailed reproducer. I can reproduce the issue, and I think I know what's the problem. Looks like a race condition in our code that leads to a `pthread_mutex` being effectively duplicated.

**Comment by rschatz** [comment] 2022-03-10 09:27
Should be fixed on the master branch.

**Closed by rschatz** 2022-03-10 09:27 UTC
Labels: llvm
