### ISSUE TITLE
Command line arguments results in ClassNotFoundException

### ISSUE THREAD

**Issue by JohannesLichtenberger** [oracle/graal#8406] opened 2024-02-19 22:55 UTC
I've just created a native image from a little shell for my DB project:

```
#!/bin/bash

source "$HOME/.sdkman/bin/sdkman-init.sh"
sdk use java 21.0.2-graal 1>&2

# ./mvnw clean verify removes target/ and will re-trigger native image creation.
if [ ! -f sirix-query-0.10.6-all ]; then

    # Performance tuning flags, optimization level 3, maximum inlining exploration, and compile for the architecture where the native image is generated.
    NATIVE_IMAGE_OPTS="-O3 -H:TuneInlinerExploration=1 -march=native"
   
    NATIVE_IMAGE_OPTS="$NATIVE_IMAGE_OPTS --enable-preview --initialize-at-build-time=ch.qos.logback --initialize-at-build-time=org.slf4j.impl.StaticLoggerBinder --initialize-at-build-time=org.slf4j.LoggerFactory"
    
    NATIVE_IMAGE_OPTS="$NATIVE_IMAGE_OPTS -DLOGGER_HOME=~/sirix-data --add-exports=java.base/jdk.internal.ref=ALL-UNNAMED --add-exports=java.base/sun.nio.ch=ALL-UNNAMED --add-exports=jdk.unsupported/sun.misc=ALL-UNNAMED --add-exports=jdk.compiler/com.sun.tools.javac.file=ALL-UNNAMED --add-opens=jdk.compiler/com.sun.tools.javac=ALL-UNNAMED --add-opens=java.base/java.lang=ALL-UNNAMED --add-opens=java.base/java.lang.reflect=ALL-UNNAMED --add-opens=java.base/java.io=ALL-UNNAMED --add-opens=java.base/java.util=ALL-UNNAMED"
    
    native-image $NATIVE_IMAGE_OPTS -jar bundles/sirix-query/build/libs/sirix-query-0.10.6-all.jar
fi
```

The generation apparently was successful, but I'm not sure how to add program arguments or what's wrong:

For instance adding "-iq" for interactive query as command line arguments results in:

```
johannes@luna:~/IdeaProjects/sirix$ ./sirix-query-0.10.6-all -iq
java.lang.ClassNotFoundException: io.brackit.query.util.log.UtilLogFactory
	at org.graalvm.nativeimage.builder/com.oracle.svm.core.hub.ClassForNameSupport.forName(ClassForNameSupport.java:122)
	at org.graalvm.nativeimage.builder/com.oracle.svm.core.hub.ClassForNameSupport.forName(ClassForNameSupport.java:86)
	at java.base@21.0.2/java.lang.Class.forName(DynamicHub.java:1356)
	at java.base@21.0.2/java.lang.Class.forName(DynamicHub.java:1319)
	at java.base@21.0.2/java.lang.Class.forName(DynamicHub.java:1312)
	at io.brackit.query.util.log.Logger.<clinit>(Logger.java:54)
	at io.brackit.query.function.fn.Trace.<clinit>(Trace.java:44)
	at io.brackit.query.module.Functions.<clinit>(Functions.java:129)
	at io.brackit.query.compiler.CompileChain.<clinit>(CompileChain.java:80)
	at java.base@21.0.2/java.lang.Class.ensureInitialized(DynamicHub.java:601)
	at io.sirix.query.Main.main(Main.java:148)
	at java.base@21.0.2/java.lang.invoke.LambdaForm$DMH/sa346b79c.invokeStaticInit(LambdaForm$DMH)
Error: null
```

**Comment by fniephaus** [comment] 2024-02-20 09:32
Hi @JohannesLichtenberger, thanks for raising this ticket.

Your application fails resolving a class reflectively (via `Class.forName()`). This means that the Native Image static analysis was unable to detect the use of reflection in your code automatically and that you need to provide metadata via a `reflect-config.json` file to fix this. I hope you find the [docs on reflection](https://www.graalvm.org/latest/reference-manual/native-image/dynamic-features/Reflection/) to be a good starting point.

I hope you don't mind if I close this ticket for now. Feel free to comment if you have any further questions!

**Closed by fniephaus** 2024-02-20 09:32 UTC
Labels: bug, native-image

**Comment by JohannesLichtenberger** [comment] 2024-02-21 19:27
@fniephaus If I'm not completely mistaken my generated native-image worked yesterday, but I just recreated everything and yesterday I moved the scripts to a subfolder named native-image. Furthermore, I'm not sure if the names of the directories have to be named `META-INF/native-image` for automatic inclusion, but I'm using the following to create the necessary config files and `io.brackit.query.util.log.UtilLogFactory` is also mentioned:

```
$JAVA_HOME/bin/java -agentlib:native-image-agent=config-output-dir=META-INF/native-image --enable-preview -DLOGGER_HOME=~/sirix-data --add-exports=java.base/jdk.internal.ref=ALL-UNNAMED --add-exports=java.base/sun.nio.ch=ALL-UNNAMED --add-exports=jdk.unsupported/sun.misc=ALL-UNNAMED --add-exports=jdk.compiler/com.sun.tools.javac.file=ALL-UNNAMED --add-opens=jdk.compiler/com.sun.tools.javac=ALL-UNNAMED --add-opens=java.base/java.lang=ALL-UNNAMED --add-opens=java.base/java.lang.reflect=ALL-UNNAMED --add-opens=java.base/java.io=ALL-UNNAMED --add-opens=java.base/java.util=ALL-UNNAMED -jar ../bundles/sirix-query/build/libs/sirix-query-0.10.6-all.jar -iq
```

```json
{
  "name":"io.brackit.query.util.log.UtilLogFactory",
  "methods":[{"name":"<init>","parameterTypes":[] }]
},
```

Afterwards I'm using this script to create the first image:

```
source "$HOME/.sdkman/bin/sdkman-init.sh"
sdk use java 21.0.2-graal 1>&2

if [ ! -f sirix-shell ]; then
    # Performance tuning flags, optimization level 3, maximum inlining exploration, and compile for the architecture where the native image is generated.
    NATIVE_IMAGE_OPTS="-O3 -H:TuneInlinerExploration=1 -march=native --gc=G1 --strict-image-heap --pgo-instrument --no-fallback"
   
    NATIVE_IMAGE_OPTS="$NATIVE_IMAGE_OPTS --enable-preview --initialize-at-build-time=ch.qos.logback --initialize-at-build-time=org.slf4j.impl.StaticLoggerBinder --initialize-at-build-time=org.slf4j.LoggerFactory --initialize-at-build-time=org.slf4j.helpers.NOPLoggerFactory --initialize-at-build-time=org.slf4j.helpers.SubstituteLoggerFactory"
    
    NATIVE_IMAGE_OPTS="$NATIVE_IMAGE_OPTS -DLOGGER_HOME=~/sirix-data --add-exports=java.base/jdk.internal.ref=ALL-UNNAMED --add-exports=java.base/sun.nio.ch=ALL-UNNAMED --add-exports=jdk.unsupported/sun.misc=ALL-UNNAMED --add-exports=jdk.compiler/com.sun.tools.javac.file=ALL-UNNAMED --add-opens=jdk.compiler/com.sun.tools.javac=ALL-UNNAMED --add-opens=java.base/java.lang=ALL-UNNAMED --add-opens=java.base/java.lang.reflect=ALL-UNNAMED --add-opens=java.base/java.io=ALL-UNNAMED --add-opens=java.base/java.util=ALL-UNNAMED"
    
    native-image $NATIVE_IMAGE_OPTS -jar ../bundles/sirix-query/build/libs/sirix-query-0.10.6-all.jar sirix-shell
fi
```

When running `./sirix-shell -iq` I'm getting the same exception somehow now:

```
johannes@luna:~/IdeaProjects/sirix/native-image$ ./sirix-shell -iq
java.lang.ClassNotFoundException: io.brackit.query.util.log.UtilLogFactory
	at org.graalvm.nativeimage.builder/com.oracle.svm.core.hub.ClassForNameSupport.forName(ClassForNameSupport.java:122)
	at org.graalvm.nativeimage.builder/com.oracle.svm.core.hub.ClassForNameSupport.forName(ClassForNameSupport.java:86)
	at java.base@21.0.2/java.lang.Class.forName(DynamicHub.java:1356)
	at java.base@21.0.2/java.lang.Class.forName(DynamicHub.java:1319)
	at java.base@21.0.2/java.lang.Class.forName(DynamicHub.java:1312)
	at io.brackit.query.util.log.Logger.<clinit>(Logger.java:54)
	at io.brackit.query.function.fn.Trace.<clinit>(Trace.java:44)
	at io.brackit.query.module.Functions.<clinit>(Functions.java:129)
	at io.brackit.query.compiler.CompileChain.<clinit>(CompileChain.java:80)
	at java.base@21.0.2/java.lang.Class.ensureInitialized(DynamicHub.java:601)
	at io.sirix.query.Main.main(Main.java:148)
	at java.base@21.0.2/java.lang.invoke.LambdaForm$DMH/sa346b79c.invokeStaticInit(LambdaForm$DMH)
Error: null
```


Once this is running, I guess I can use something like this to create a new image:

```
source "$HOME/.sdkman/bin/sdkman-init.sh"
sdk use java 21.0.2-graal 1>&2

# Performance tuning flags, optimization level 3, maximum inlining exploration, and compile for the architecture where the native image is generated.
NATIVE_IMAGE_OPTS="-O3 -H:TuneInlinerExploration=1 -march=native --gc=G1 --strict-image-heap --pgo=default.iprof --no-fallback"
   
NATIVE_IMAGE_OPTS="$NATIVE_IMAGE_OPTS --enable-preview --initialize-at-build-time=ch.qos.logback --initialize-at-build-time=org.slf4j.impl.StaticLoggerBinder --initialize-at-build-time=org.slf4j.LoggerFactory --initialize-at-build-time=org.slf4j.helpers.NOPLoggerFactory --initialize-at-build-time=org.slf4j.helpers.SubstituteLoggerFactory"
    
NATIVE_IMAGE_OPTS="$NATIVE_IMAGE_OPTS -DLOGGER_HOME=~/sirix-data --add-exports=java.base/jdk.internal.ref=ALL-UNNAMED --add-exports=java.base/sun.nio.ch=ALL-UNNAMED --add-exports=jdk.unsupported/sun.misc=ALL-UNNAMED --add-exports=jdk.compiler/com.sun.tools.javac.file=ALL-UNNAMED --add-opens=jdk.compiler/com.sun.tools.javac=ALL-UNNAMED --add-opens=java.base/java.lang=ALL-UNNAMED --add-opens=java.base/java.lang.reflect=ALL-UNNAMED --add-opens=java.base/java.io=ALL-UNNAMED --add-opens=java.base/java.util=ALL-UNNAMED"
    
native-image $NATIVE_IMAGE_OPTS -jar ../bundles/sirix-query/build/libs/sirix-query-0.10.6-all.jar sirix-shell
./sirix-shell
```

**Comment by JohannesLichtenberger** [comment] 2024-02-21 23:14
Ok, so it's picked up using `cp /path/to/jar:.`.

However, I don't know what to make of this:

```
johannes@luna:~/IdeaProjects/sirix/native-image$ ./prepare-native-image-metadata.sh
Enter query string (terminate with Control-D):
sirix > jn:load('mycol', (), io:ls('/home/johannes/Desktop/json', '\\.json$'))
sirix > 

Query result
["bla","blubb"] {"foo":true}

Enter query string (terminate with Control-D):
sirix > 
[1]+  Stopped                 ./prepare-native-image-metadata.sh
johannes@luna:~/IdeaProjects/sirix/native-image$ ./prepare-native-image.sh
...
johannes@luna:~/IdeaProjects/sirix/native-image$ ./sirix-shell -iq
Enter query string (terminate with Control-D):
sirix > jn:load('mycol', (), io:ls('/home/johannes/Desktop/json', '\\.json$'))
sirix > 

Query result
Error: java.lang.AssertionError: java.lang.NoSuchFieldException: directMemory: java.util.concurrent.CompletionException: java.lang.AssertionError: java.lang.NoSuchFieldException: directMemory
```

**Comment by JohannesLichtenberger** [comment] 2024-02-21 23:32
@fniephaus and thanks for your help, the GraalVM is amazing. From the Graal JIT Compiler, I got 1/3 better performance vs C2 (or GraalVM vs Temurin for instance) :-) also looking forward to the generational ZGC (with the JIT Compiler so far).

So now I want to test profile-guided optimizations / native images, too.

**Comment by JohannesLichtenberger** [comment] 2024-02-22 17:17
Do you have an idea what to do about: Error: java.lang.AssertionError: java.lang.NoSuchFieldException: directMemory

My first guess is, that it's something from Chronicle

**Comment by JohannesLichtenberger** [comment] 2024-02-22 17:56
Actually it's in the `reflect-config.json` already, so weird, because it now finds `io.brackit.query.util.log.UtilLogFactory` and thus I guess I fixed the classpath:

```json
{
  "name":"jdk.internal.misc.VM",
  "fields":[{"name":"directMemory"}]
},
```

**Comment by fniephaus** [comment] 2024-02-23 09:37
Interesting, do you have a stack trace or a reproducer for this?

**Comment by fniephaus** [comment] 2024-02-23 17:38
Thanks, will take a look at this next week.

**Comment by fniephaus** [comment] 2024-02-26 11:37
Ok, so I looked into it and after adding some stack trace printing, I was presented with this:
```
Caused by: java.lang.AssertionError: java.lang.NoSuchFieldException: directMemory
        at net.openhft.chronicle.core.internal.ClassUtil.getField0(ClassUtil.java:52)
        at net.openhft.chronicle.core.Jvm.getField(Jvm.java:540)
        at net.openhft.chronicle.core.Jvm.maxDirectMemory0(Jvm.java:905)
        at net.openhft.chronicle.core.Jvm.<clinit>(Jvm.java:142)
        at net.openhft.chronicle.core.io.AbstractReferenceCounted.<clinit>(AbstractReferenceCounted.java:39)
        at java.base@21.0.2/java.lang.Class.ensureInitialized(DynamicHub.java:601)
        at java.base@21.0.2/java.lang.Class.ensureInitialized(DynamicHub.java:601)
        at net.openhft.chronicle.bytes.BytesStore.elasticByteBuffer(BytesStore.java:192)
        at net.openhft.chronicle.bytes.Bytes.elasticByteBuffer(Bytes.java:176)
        at net.openhft.chronicle.bytes.Bytes.elasticByteBuffer(Bytes.java:148)
        at io.sirix.io.filechannel.FileChannelWriter.<init>(FileChannelWriter.java:76)
        at io.sirix.io.memorymapped.MMStorage.createWriter(MMStorage.java:185)
        at io.sirix.access.trx.node.AbstractResourceSession.createPageTransaction(AbstractResourceSession.java:239)
        at io.sirix.access.trx.node.AbstractResourceSession.beginNodeTrx(AbstractResourceSession.java:448)
        at io.sirix.access.trx.node.AbstractResourceSession.beginNodeTrx(AbstractResourceSession.java:409)
        at io.sirix.access.LocalDatabase.bootstrapResource(LocalDatabase.java:248)
        at io.sirix.access.LocalDatabase.createResource(LocalDatabase.java:218)
        at io.sirix.query.json.BasicJsonDBStore.createResource(BasicJsonDBStore.java:450)
        at io.sirix.query.json.BasicJsonDBStore.lambda$create$2(BasicJsonDBStore.java:390)
        at java.base@21.0.2/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804)
        ... 8 more
Caused by: java.lang.NoSuchFieldException: directMemory
        at java.base@21.0.2/java.lang.Class.checkField(DynamicHub.java:1041)
        at java.base@21.0.2/java.lang.Class.getDeclaredField(DynamicHub.java:1156)
        at net.openhft.chronicle.core.internal.ClassUtil.getField0(ClassUtil.java:40)
        ... 27 more
```
The relevant line of code is here: https://github.com/OpenHFT/Chronicle-Core/blame/f8648c3ae82fb65cd026969a1d89ae4581c7267b/src/main/java/net/openhft/chronicle/core/Jvm.java#L905
I'm not entirely sure why the catch block does not work, but the problem is the following:

In Native Image, we substitute `directMemory` using an `InjectAccessors` (`DirectMemoryAccessors`):

https://github.com/oracle/graal/blob/087f280904fc6b734868522c9b5a4f12068e26a5/substratevm/src/com.oracle.svm.core/src/com/oracle/svm/core/jdk/Target_jdk_internal_misc_VM.java#L69-L70

Substituted fields annotated with `InjectAccessors` are, however, excluded from reflection:

https://github.com/oracle/graal/blob/087f280904fc6b734868522c9b5a4f12068e26a5/substratevm/src/com.oracle.svm.hosted/src/com/oracle/svm/hosted/substitute/SubstitutionReflectivityFilter.java#L105-L106

So even though the reflection metadata contains:
```json
{
  "name":"jdk.internal.misc.VM",
  "fields":[{"name":"directMemory"}]
},
```

it is unfortunately silently ignored within the build process.

Again, I'm not sure why the `NoSuchFieldException` was not [caught and ignored here](https://github.com/OpenHFT/Chronicle-Core/blame/f8648c3ae82fb65cd026969a1d89ae4581c7267b/src/main/java/net/openhft/chronicle/core/Jvm.java#L908) because then this should have just worked.

Nonetheless, `net.openhft:chronicle-bytes` seems to access JVM internals, assuming it runs on HotSpot, which is definitely not recommended and can cause complicated problems like this when running on SubstrateVM.

Let me try and find out why the catch block does not work...

**Comment by vjovanov** [comment] 2024-02-26 16:01
The problem here is that we did not mention in the error message that the field was substituted. I would like to print this warning at runtime in the error of `java.lang.NoSuchFieldException`. We could append additional text saying something like: `This field was deleted by a substitution in Native Image, please try to rewrite the code such that the value of this field is not used.`. @loicottet could we encode this into our metadata? Also, how does our new reflection implementation play along with substitutions? We should test this in detail.

The exception is ignored here because the exception throw is an `AssertionError` which is not a subclass of `Exception`. This is a bug in `net.openhft.chronicle.core.Jvm.maxDirectMemory0` as it catches the wrong exception.

**Comment by JohannesLichtenberger** [comment] 2024-02-26 16:15
Wow, so I'm not sure, but I guess they are not able to change their internals quickly. Do I have any chance of getting this to work at all? Guess I should have invented an adapter or something in the first place and I already knew it back then...

**Comment by vjovanov** [comment] 2024-02-26 16:36
Well, we will try to chage `getField` to call the injected accessor. Until we make it work (or the library fixes it) your only option is to substitute this method. As an inspiration you can use: https://github.com/oracle/graal/blob/master/substratevm/src/com.oracle.svm.core/src/com/oracle/svm/core/jdk/SecuritySubstitutions.java#L258

**Comment by JohannesLichtenberger** [comment] 2024-02-26 16:39
Maybe I can also switch to heap byte buffers in general (`Bytes::elasticHeapByteBuffer` IIRC. Nonetheless, the Chronicle developers should be aware of issues like this.

**Comment by loicottet** [comment] 2024-02-27 13:03
> @loicottet could we encode this into our metadata?

I think it is possible, we could have the field accessor methods linked in the metadata and return a `Field` with a modified `FieldAccessor`.

> Also, how does our new reflection implementation play along with substitutions? We should test this in detail.

In our reflection implementation, the components of the returned `Field` object are extracted from the original `Field`, unless they are overridden in the `AnalysisField` of the substitution (such as when an annotation is added to the field). And calling `get` or `set` on the `Field` at run-time of course modifies the substituted field, this is why we disabled reflection for fields with `@InjectedAccessors`.

**Comment by JohannesLichtenberger** [comment] 2024-02-27 19:40
I've switched from `BytesStore.elasticByteBuffer` to `BytesStore.elasticHeapByteBuffer` in the whole project AFAICs and rebuilt the native-image, but the exception somehow persists.

@fniephaus: Can I print the stacktrace, too?

**Comment by fniephaus** [comment] 2024-02-28 09:58
Sure, your code seems to swallow relevant exceptions. I used this git patch: [printStackTrace.txt](https://github.com/oracle/graal/files/14431952/printStackTrace.txt)

**Comment by JohannesLichtenberger** [comment] 2024-02-28 11:11
Oh, thought there's a JVM flag such as printStacktraceOnException ;-) though, maybe simply printing the stacktrace is best as you did

**Comment by fniephaus** [comment] 2024-02-28 12:04
Mh no, I don't think so. I would've expected there to be a `--debug` or `--verbose` flag in the sirix shell that provides additional info and relevant stack traces that or otherwise just swallowed and shortened.

**Comment by JohannesLichtenberger** [comment] 2024-03-01 16:18
I've added a flag (`-d`) to print the stacktrace, but still not sure:

```
johannes@luna:~/IdeaProjects/sirix/native-image$ ./sirix-shell -iq -d
Enter query string (terminate with Control-D):
sirix > jn:load('mycol', (), io:ls('/home/johannes/Desktop/json', '\\.json$'))
sirix > 

Query result
Error: java.lang.AssertionError: java.lang.NoSuchFieldException: directMemory: java.util.concurrent.CompletionException: java.lang.AssertionError: java.lang.NoSuchFieldException: directMemory
io.brackit.query.QueryException: java.lang.AssertionError: java.lang.NoSuchFieldException: directMemory: java.util.concurrent.CompletionException: java.lang.AssertionError: java.lang.NoSuchFieldException: directMemory
	at io.sirix.query.function.jn.io.Load.execute(Load.java:125)
	at io.brackit.query.function.FunctionExpr.evaluate(FunctionExpr.java:97)
	at io.brackit.query.Query.run(Query.java:85)
	at io.brackit.query.Query.serialize(Query.java:108)
	at io.brackit.query.Query.serialize(Query.java:104)
	at io.sirix.query.Main.executeQuery(Main.java:235)
	at io.sirix.query.Main.main(Main.java:178)
	at java.base@21.0.2/java.lang.invoke.LambdaForm$DMH/sa346b79c.invokeStaticInit(LambdaForm$DMH)
Enter query string (terminate with Control-D):
```

But I guess it's still wrapping:

```
  static Bytes<ByteBuffer> elasticHeapByteBuffer(@NonNegative int initialCapacity) {
        requireNonNegative(initialCapacity);
        @NotNull BytesStore<?, ByteBuffer> bs = BytesStore.wrap(ByteBuffer.allocate(initialCapacity));
        try {
            return NativeBytes.wrapWithNativeBytes(bs, Bytes.MAX_HEAP_CAPACITY);
        } finally {
            bs.release(INIT);
        }
    }
```

I think I didn't get it in the first place... what's the workaround for now?

kind regards and have a nice weekend
Johannes

**Comment by JohannesLichtenberger** [comment] 2024-03-05 06:59
@fniephaus any workaround I can already do to get the native image running? :-)

**Comment by JohannesLichtenberger** [comment] 2024-03-05 15:32
ok, thanks. Did you file an issue for Chronicle or should I later on? Thanks for all your effort! :-)

**Comment by fniephaus** [comment] 2024-03-05 16:56
I have not, thanks for filing a ticket for this :)
