### ISSUE TITLE
Error creating bean with name 'resourceHandlerMapping': Instantiation of supplied bean failed

### ISSUE THREAD

**Issue by liao-can-jie** [oracle/graal#8071] opened 2023-12-21 09:39 UTC
**Describe the issue**
A clear and concise description of the issue. We recommend using the [latest snapshot builds](https://github.com/graalvm/graalvm-ce-dev-builds/releases) to replicate the issue as  bugs are constantly being fixed in the master branch

**Steps to reproduce the issue**
Please include both build steps as well as run steps
1. **[e.g.: git clone --depth 1 https://git.myrepo.com/projectone ]**
2. **[e.g.: mvn clean package]**

**Describe GraalVM and your environment:**
 - GraalVM version ： Java HotSpot(TM) 64-Bit Server VM GraalVM EE 22.3.2 (build 17.0.7+8-LTS-jvmci-22.3-b15, mixed mode, sharing)
 - JDK major version:  17.0.7+8-LTS
 - OS: window10
 - Architecture: 12th Gen Intel(R) Core(TM) i7-12700

**More details**
Consider adding the `--native-image-info` and  `--verbose` flags when building your native image and paste output below.

Add any other information about the problem here. Especially important are stack traces or log output. Feel free to link to gists or to screenshots if necessary.

**********************************************************************
** Visual Studio 2022 Developer Command Prompt v17.7.0
** Copyright (c) 2022 Microsoft Corporation
**********************************************************************
[vcvarsall.bat] Environment initialized for: 'x64'

C:\Program Files\Microsoft Visual Studio\2022\Community>D:\IdeaProjects\mx-ce-cloud\mx-charge-electricity\mx-ce-oms\target\app.exe
2023-12-22T15:22:57.802+08:00  WARN 12316 --- [           main] c.a.nacos.client.logging.NacosLogging    : Load Logback Configuration of Nacos fail, message: Could not initialize Logback Nacos logging from classpath:nacos-logback.xml

  .   ____          _            __ _ _
 /\\ / ___'_ __ _ _(_)_ __  __ _ \ \ \ \
( ( )\___ | '_ | '_| | '_ \/ _` | \ \ \ \
 \\/  ___)| |_)| | | | | || (_| |  ) ) ) )
  '  |____| .__|_| |_|_| |_\__, | / / / /
 =========|_|==============|___/=/_/_/_/
 :: Spring Boot ::               (v3.0.13)

2023-12-22T15:22:57.805+08:00  WARN 12316 --- [           main] c.a.nacos.client.logging.NacosLogging    : Load Logback Configuration of Nacos fail, message: Could not initialize Logback Nacos logging from classpath:nacos-logback.xml
2023-12-22T15:22:57.805+08:00  INFO 12316 --- [           main] com.mx.ce.oms.MxCeOmsApplication         : Starting AOT-processed MxCeOmsApplication using Java 17.0.7 with PID 12316 (D:\IdeaProjects\mx-ce-cloud\mx-charge-electricity\mx-ce-oms\target\app.exe started by Administrator in C:\Program Files\Microsoft Visual Studio\2022\Community)
2023-12-22T15:22:57.805+08:00  INFO 12316 --- [           main] com.mx.ce.oms.MxCeOmsApplication         : The following 1 profile is active: "test"
2023-12-22T15:22:57.805+08:00  INFO 12316 --- [           main] c.a.c.n.c.NacosConfigDataLoader          : [Nacos Config] Load config[dataId=mx-ce-oms-test.yml, group=DEFAULT_GROUP] success
2023-12-22T15:22:57.806+08:00  INFO 12316 --- [           main] o.s.cloud.context.scope.GenericScope     : BeanFactory id=125fec7b-0834-3175-b3d8-a9f06541b3af
2023-12-22T15:22:57.823+08:00  INFO 12316 --- [           main] o.s.b.w.embedded.tomcat.TomcatWebServer  : Tomcat initialized with port(s): 8094 (http)
2023-12-22T15:22:57.823+08:00  INFO 12316 --- [           main] o.apache.catalina.core.StandardService   : Starting service [Tomcat]
2023-12-22T15:22:57.823+08:00  INFO 12316 --- [           main] o.apache.catalina.core.StandardEngine    : Starting Servlet engine: [Apache Tomcat/10.1.16]
2023-12-22T15:22:57.838+08:00  INFO 12316 --- [           main] o.a.c.c.C.[Tomcat].[localhost].[/]       : Initializing Spring embedded WebApplicationContext
2023-12-22T15:22:57.838+08:00  INFO 12316 --- [           main] w.s.c.ServletWebServerApplicationContext : Root WebApplicationContext: initialization completed in 33 ms
Logging initialized using 'class org.apache.ibatis.logging.stdout.StdOutImpl' adapter.
2023-12-22T15:22:57.853+08:00  INFO 12316 --- [           main] .i.s.PathMatchingResourcePatternResolver : Skipping search for files matching pattern [**/*.xml]: directory [/mapper] does not exist
Registered plugin: 'com.baomidou.mybatisplus.extension.plugins.MybatisPlusInterceptor@74182cb2'
Registered type handler: 'class java.lang.Integer'
Registered type handler: 'class java.lang.Long'
Registered type handler: 'class java.lang.String'
Property 'mapperLocations' was not specified.
2023-12-22T15:22:57.967+08:00  WARN 12316 --- [           main] w.s.c.ServletWebServerApplicationContext : Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'resourceHandlerMapping': Instantiation of supplied bean failed
2023-12-22T15:22:57.967+08:00  INFO 12316 --- [           main] o.apache.catalina.core.StandardService   : Stopping service [Tomcat]
2023-12-22T15:22:57.968+08:00 ERROR 12316 --- [           main] o.s.boot.SpringApplication               : Application run failed

org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'resourceHandlerMapping': Instantiation of supplied bean failed
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.obtainFromSupplier(AbstractAutowireCapableBeanFactory.java:1220) ~[app.exe:6.0.14]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1158) ~[app.exe:6.0.14]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:560) ~[app.exe:6.0.14]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:520) ~[app.exe:6.0.14]
        at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:325) ~[app.exe:6.0.14]
        at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234) ~[app.exe:6.0.14]
        at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:323) ~[app.exe:6.0.14]
        at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:199) ~[app.exe:6.0.14]
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:973) ~[app.exe:6.0.14]
        at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:950) ~[app.exe:6.0.14]
        at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:616) ~[app.exe:6.0.14]
        at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:146) ~[app.exe:3.0.13]
        at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:733) ~[app.exe:3.0.13]
        at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:435) ~[app.exe:3.0.13]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:311) ~[app.exe:3.0.13]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1301) ~[app.exe:3.0.13]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1290) ~[app.exe:3.0.13]
        at com.mx.ce.oms.MxCeOmsApplication.main(MxCeOmsApplication.java:13) ~[app.exe:na]
Caused by: io.github.classgraph.ClassGraphException: Uncaught exception during scan
        at io.github.classgraph.ClassGraph.scan(ClassGraph.java:1606) ~[na:na]
        at io.github.classgraph.ClassGraph.scan(ClassGraph.java:1623) ~[na:na]
        at io.github.classgraph.ClassGraph.scan(ClassGraph.java:1636) ~[na:na]
        at org.webjars.WebJarAssetLocator.scanForWebJars(WebJarAssetLocator.java:188) ~[app.exe:na]
        at org.webjars.WebJarAssetLocator.<init>(WebJarAssetLocator.java:210) ~[app.exe:na]
        at org.webjars.WebJarAssetLocator.<init>(WebJarAssetLocator.java:194) ~[app.exe:na]
        at org.springframework.web.servlet.resource.WebJarsResourceResolver.<init>(WebJarsResourceResolver.java:63) ~[na:na]
        at org.springframework.web.servlet.config.annotation.ResourceChainRegistration.getResourceResolvers(ResourceChainRegistration.java:114) ~[app.exe:6.0.14]
        at org.springframework.web.servlet.config.annotation.ResourceHandlerRegistration.getRequestHandler(ResourceHandlerRegistration.java:215) ~[app.exe:6.0.14]
        at org.springframework.web.servlet.config.annotation.ResourceHandlerRegistry.getRequestHandler(ResourceHandlerRegistry.java:178) ~[app.exe:6.0.14]
        at org.springframework.web.servlet.config.annotation.ResourceHandlerRegistry.getHandlerMapping(ResourceHandlerRegistry.java:168) ~[app.exe:6.0.14]
        at org.springframework.web.servlet.config.annotation.WebMvcConfigurationSupport.resourceHandlerMapping(WebMvcConfigurationSupport.java:589) ~[app.exe:6.0.14]
        at org.springframework.web.servlet.config.annotation.WebMvcConfigurationSupport__BeanDefinitions.lambda$getResourceHandlerMappingInstanceSupplier$7(WebMvcConfigurationSupport__BeanDefinitions.java:158) ~[na:na]
        at org.springframework.util.function.ThrowingBiFunction.apply(ThrowingBiFunction.java:68) ~[app.exe:6.0.14]
        at org.springframework.util.function.ThrowingBiFunction.apply(ThrowingBiFunction.java:54) ~[app.exe:6.0.14]
        at org.springframework.beans.factory.aot.BeanInstanceSupplier.lambda$get$2(BeanInstanceSupplier.java:202) ~[na:na]
        at org.springframework.util.function.ThrowingSupplier.get(ThrowingSupplier.java:58) ~[app.exe:6.0.14]
        at org.springframework.util.function.ThrowingSupplier.get(ThrowingSupplier.java:46) ~[app.exe:6.0.14]
        at org.springframework.beans.factory.aot.BeanInstanceSupplier.invokeBeanSupplier(BeanInstanceSupplier.java:214) ~[na:na]
        at org.springframework.beans.factory.aot.BeanInstanceSupplier.get(BeanInstanceSupplier.java:202) ~[na:na]
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.obtainInstanceFromSupplier(DefaultListableBeanFactory.java:947) ~[app.exe:6.0.14]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.obtainFromSupplier(AbstractAutowireCapableBeanFactory.java:1214) ~[app.exe:6.0.14]
        ... 17 common frames omitted
Caused by: java.lang.IllegalArgumentException: Method "list" could not be invoked: java.lang.reflect.InvocationTargetException
        at nonapi.io.github.classgraph.reflection.ReflectionUtils.invokeMethod(ReflectionUtils.java:231) ~[na:na]
        at io.github.classgraph.ModuleReaderProxy.list(ModuleReaderProxy.java:108) ~[app.exe:4.8.149]
        at io.github.classgraph.ClasspathElementModule.scanPaths(ClasspathElementModule.java:304) ~[na:na]
        at io.github.classgraph.Scanner$4.processWorkUnit(Scanner.java:1091) ~[na:na]
        at io.github.classgraph.Scanner$4.processWorkUnit(Scanner.java:1085) ~[na:na]
        at nonapi.io.github.classgraph.concurrency.WorkQueue.runWorkLoop(WorkQueue.java:246) ~[app.exe:4.8.149]
        at nonapi.io.github.classgraph.concurrency.WorkQueue.access$000(WorkQueue.java:50) ~[app.exe:4.8.149]
        at nonapi.io.github.classgraph.concurrency.WorkQueue$1.call(WorkQueue.java:201) ~[na:na]
        at nonapi.io.github.classgraph.concurrency.WorkQueue$1.call(WorkQueue.java:198) ~[na:na]
        at java.base@17.0.7/java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[app.exe:na]
        at java.base@17.0.7/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[app.exe:na]
        at java.base@17.0.7/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[na:na]
        at java.base@17.0.7/java.lang.Thread.run(Thread.java:833) ~[app.exe:na]
        at org.graalvm.nativeimage.builder/com.oracle.svm.core.thread.PlatformThreads.threadStartRoutine(PlatformThreads.java:775) ~[app.exe:na]
        at org.graalvm.nativeimage.builder/com.oracle.svm.core.windows.WindowsPlatformThreads.osThreadStartRoutine(WindowsPlatformThreads.java:178) ~[na:na]

2023-12-22T15:22:57.970+08:00  WARN 12316 --- [       Thread-6] c.a.nacos.common.notify.NotifyCenter     : [NotifyCenter] Start destroying Publisher

**Comment by solaanan** [comment] 2023-12-25 15:16
Hello @liao-can-jie, could you please provide detailed steps on how to reproduce the issue? This will help us investigate and address the problem more effectively. Thank you!

for example:
1: git clone --depth 1 https://git.myrepo.com/projectone
2: mvn clean package
3: ...

**Comment by solaanan** [comment] 2024-01-31 15:22
Closing this issue due to absence of a reproducer, @liao-can-jie please feel free to reopen or create a new issue if you still need assistance.

**Closed by solaanan** 2024-01-31 15:22 UTC
Labels: bug, native-image
