### ISSUE TITLE
java.lang.NullPointerException in native-image building

### ISSUE THREAD

**Issue by gurinderu** [oracle/graal#2518] opened 2020-05-29 08:46 UTC
**Describe the issue**

**Describe GraalVM and your environment:**
 - GraalVM version: 20.1.0-java11
 - JDK major version: *11
 - OS: macos Catalina 10.15.4 (19E287)
 - Architecture: amd64

**More details**
My native image args Args=--no-server \
  --no-fallback \
  --static \
  --enable-http \
  --enable-https \
  --enable-all-security-services \
  --report-unsupported-elements-at-runtime \
  --allow-incomplete-classpath \
  --install-exit-handlers \
  --initialize-at-build-time \
  --verbose \
  -H:EnableURLProtocols=http,https \
  -H:+TraceClassInitialization \
  -H:+RemoveSaturatedTypeFlows \
  -H:+ReportUnsupportedElementsAtRuntime \
  -H:+ReportExceptionStackTraces \
  -H:UseMuslC=/opt/graalvm/stage/resources/musl/bundle \
  --initialize-at-run-time=ch.qos.logback.classic.AsyncAppender \
  --initialize-at-run-time=ch.qos.logback.core.AsyncAppenderBase 

Stacktrace:
```
[error] Fatal error:java.lang.NullPointerException
[error] 	at com.oracle.graal.pointsto.flow.MethodTypeFlow.getParsingContext(MethodTypeFlow.java:99)
[error] 	at com.oracle.graal.pointsto.util.AnalysisError.parsingContext(AnalysisError.java:122)
[error] 	at com.oracle.graal.pointsto.util.AnalysisError.access$000(AnalysisError.java:37)
[error] 	at com.oracle.graal.pointsto.util.AnalysisError$ParsingError.message(AnalysisError.java:97)
[error] 	at com.oracle.graal.pointsto.util.AnalysisError$ParsingError.<init>(AnalysisError.java:87)
[error] 	at com.oracle.graal.pointsto.util.AnalysisError.parsingError(AnalysisError.java:138)
[error] 	at com.oracle.graal.pointsto.flow.MethodTypeFlow.doParse(MethodTypeFlow.java:336)
[error] 	at com.oracle.graal.pointsto.flow.MethodTypeFlow.ensureParsed(MethodTypeFlow.java:311)
[error] 	at com.oracle.graal.pointsto.flow.MethodTypeFlow.addContext(MethodTypeFlow.java:112)
[error] 	at com.oracle.graal.pointsto.DefaultAnalysisPolicy$DefaultVirtualInvokeTypeFlow.onObservedUpdate(DefaultAnalysisPolicy.java:228)
[error] 	at com.oracle.graal.pointsto.flow.TypeFlow$1.run(TypeFlow.java:433)
[error] 	at com.oracle.graal.pointsto.util.CompletionExecutor.lambda$execute$0(CompletionExecutor.java:173)
[error] 	at java.base/java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1426)
[error] 	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
[error] 	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
[error] 	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
[error] 	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
[error] 	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:177)
[error] Fatal error:java.lang.NullPointerException
[error] 	at com.oracle.graal.pointsto.flow.MethodTypeFlow.getParsingContext(MethodTypeFlow.java:99)
[error] 	at com.oracle.graal.pointsto.util.AnalysisError.parsingContext(AnalysisError.java:122)
[error] 	at com.oracle.graal.pointsto.util.AnalysisError.access$000(AnalysisError.java:37)
[error] 	at com.oracle.graal.pointsto.util.AnalysisError$ParsingError.message(AnalysisError.java:97)
[error] 	at com.oracle.graal.pointsto.util.AnalysisError$ParsingError.<init>(AnalysisError.java:87)
[error] 	at com.oracle.graal.pointsto.util.AnalysisError.parsingError(AnalysisError.java:138)
[error] 	at com.oracle.graal.pointsto.flow.MethodTypeFlow.doParse(MethodTypeFlow.java:336)
[error] 	at com.oracle.graal.pointsto.flow.MethodTypeFlow.ensureParsed(MethodTypeFlow.java:311)
[error] 	at com.oracle.graal.pointsto.flow.MethodTypeFlow.addContext(MethodTypeFlow.java:112)
[error] 	at com.oracle.graal.pointsto.DefaultAnalysisPolicy$DefaultVirtualInvokeTypeFlow.onObservedUpdate(DefaultAnalysisPolicy.java:228)
[error] 	at com.oracle.graal.pointsto.flow.TypeFlow$1.run(TypeFlow.java:433)
[error] 	at com.oracle.graal.pointsto.util.CompletionExecutor.lambda$execute$0(CompletionExecutor.java:173)
[error] 	at java.base/java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1426)
[error] 	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
[error] 	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
[error] 	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
[error] 	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
[error] 	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:177)
[error] Fatal error:java.lang.NullPointerException
[error] 	at com.oracle.graal.pointsto.flow.MethodTypeFlow.getParsingContext(MethodTypeFlow.java:99)
[error] 	at com.oracle.graal.pointsto.util.AnalysisError.parsingContext(AnalysisError.java:122)
[error] 	at com.oracle.graal.pointsto.util.AnalysisError.access$000(AnalysisError.java:37)
[error] 	at com.oracle.graal.pointsto.util.AnalysisError$ParsingError.message(AnalysisError.java:97)
[error] 	at com.oracle.graal.pointsto.util.AnalysisError$ParsingError.<init>(AnalysisError.java:87)
[error] 	at com.oracle.graal.pointsto.util.AnalysisError.parsingError(AnalysisError.java:138)
[error] 	at com.oracle.graal.pointsto.flow.MethodTypeFlow.doParse(MethodTypeFlow.java:336)
[error] 	at com.oracle.graal.pointsto.flow.MethodTypeFlow.ensureParsed(MethodTypeFlow.java:311)
[error] 	at com.oracle.graal.pointsto.flow.MethodTypeFlow.addContext(MethodTypeFlow.java:112)
[error] 	at com.oracle.graal.pointsto.DefaultAnalysisPolicy$DefaultVirtualInvokeTypeFlow.onObservedUpdate(DefaultAnalysisPolicy.java:228)
[error] 	at com.oracle.graal.pointsto.flow.TypeFlow.notifyObservers(TypeFlow.java:470)
[error] 	at com.oracle.graal.pointsto.flow.TypeFlow.update(TypeFlow.java:542)
[error] 	at com.oracle.graal.pointsto.BigBang$2.run(BigBang.java:530)
[error] 	at com.oracle.graal.pointsto.util.CompletionExecutor.lambda$execute$0(CompletionExecutor.java:173)
[error] 	at java.base/java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1426)
[error] 	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
[error] 	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
[error] 	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
[error] 	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
[error] 	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:177)

```

**Comment by cstancu** [comment] 2020-05-29 17:54
@gurinderu can you share code to reproduce this?

**Comment by cstancu** [comment] 2020-05-29 17:59
Looking at the stack trace that seems to be a problem in error reporting whe ` -H:+RemoveSaturatedTypeFlows ` is used. If you  remove that option you should get the actual reason of the parsing error.

**Comment by gurinderu** [comment] 2020-05-29 17:59
@cstancu unfortunately, no.

**Comment by gurinderu** [comment] 2020-05-29 18:01
@cstancu I’ll try to reproduce this bag again, because now i can’t :(

**Comment by cstancu** [comment] 2020-05-30 04:39
This should be fixed by https://github.com/oracle/graal/commit/1c748f19ef98afb69bd3f96cd566b601f90f07a3. Thanks for the report!

**Closed by cstancu** 2020-05-30 04:39 UTC
Labels: bug, native-image
