### ISSUE TITLE
com.oracle.svm.core.util.UserError$UserException

### ISSUE THREAD

**Issue by gmaron-nv** [oracle/graal#1739] opened 2019-10-11 20:05 UTC
Hi everybody!

I want to create a `native-image` using Kotlin and Gradle. 

I executed `native-image` like this > 

```sh
    native-image -jar build/libs/my_own_jar.jar \
        -H:Name=graalvm-demo \
        --allow-incomplete-classpath \
        --initialize-at-build-time=org.jooq.SQLDialect \
        --initialize-at-build-time=org.postgresql.Driver \
        --initialize-at-build-time=org.postgresql.util.SharedTimer \
        -H:+TraceClassInitialization
```

I have this error but I don't know how to solve it >

```sh
Error: Classes that should be initialized at run time got initialized during image building:
 org.jooq.SQLDialect$ThirdParty was unintentionally initialized at build time. org.jooq.SQLDialect$ThirdParty has been initialized without the native-image initialization instrumentation and the stack trace can't be tracked. Try marking this class for build-time initialization with --initialize-at-build-time=org.jooq.SQLDialect$ThirdParty
com.oracle.svm.core.util.UserError$UserException: Classes that should be initialized at run time got initialized during image building:
 org.jooq.SQLDialect$ThirdParty was unintentionally initialized at build time. org.jooq.SQLDialect$ThirdParty has been initialized without the native-image initialization instrumentation and the stack trace can't be tracked. Try marking this class for build-time initialization with --initialize-at-build-time=org.jooq.SQLDialect$ThirdParty
	at com.oracle.svm.core.util.UserError.abort(UserError.java:65)
	at com.oracle.svm.hosted.classinitialization.ConfigurableClassInitialization.checkDelayedInitialization(ConfigurableClassInitialization.java:494)
	at com.oracle.svm.hosted.classinitialization.ClassInitializationFeature.duringAnalysis(ClassInitializationFeature.java:188)
	at com.oracle.svm.hosted.NativeImageGenerator.lambda$runPointsToAnalysis$8(NativeImageGenerator.java:711)
	at com.oracle.svm.hosted.FeatureHandler.forEachFeature(FeatureHandler.java:63)
	at com.oracle.svm.hosted.NativeImageGenerator.runPointsToAnalysis(NativeImageGenerator.java:711)
	at com.oracle.svm.hosted.NativeImageGenerator.doRun(NativeImageGenerator.java:526)
	at com.oracle.svm.hosted.NativeImageGenerator.lambda$run$0(NativeImageGenerator.java:444)
	at java.util.concurrent.ForkJoinTask$AdaptedRunnableAction.exec(ForkJoinTask.java:1386)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
Error: Image build request failed with exit status 1
com.oracle.svm.driver.NativeImage$NativeImageError: Image build request failed with exit status 1
	at com.oracle.svm.driver.NativeImage.showError(NativeImage.java:1447)
	at com.oracle.svm.driver.NativeImage.build(NativeImage.java:1225)
	at com.oracle.svm.driver.NativeImage.performBuild(NativeImage.java:1187)
	at com.oracle.svm.driver.NativeImage.main(NativeImage.java:1146)
```

Also, I put the suggestion which give me the console but with the same issue.

Thanks buddies !

**Comment by ldecleva** [comment] 2019-11-20 16:07
any update?

**Comment by shelajev** [comment] 2019-11-20 16:14
Can you please put a breakpoint into the static initializer of `org.jooq.SQLDialect$ThirdParty` and attach the debugger to the native image generator? Then when it hits you should see where from it gets initialized and either figure out how not to do that or defer that init to runtime too.

**Comment by shelajev** [comment] 2019-11-20 16:15
Wait disregard that, I read it wrong

**Comment by shelajev** [comment] 2019-11-20 16:16
how does it run when you add `--initialize-at-build-time=org.jooq.SQLDialect$ThirdParty`?

**Comment by ldecleva** [comment] 2019-11-20 16:23
Adding --initialize-at-build-time=org.jooq.SQLDialect$ThirdParty

```
Error: Classes that should be initialized at run time got initialized during image building:
 org.jooq.SQLDialect$ThirdParty was unintentionally initialized at build time. org.jooq.SQLDialect$ThirdParty has been initialized without the native-image initialization instrumentation and the stack trace can't be tracked. Try marking this class for build-time initialization with --initialize-at-build-time=org.jooq.SQLDialect$ThirdParty
com.oracle.svm.core.util.UserError$UserException: Classes that should be initialized at run time got initialized during image building:
 org.jooq.SQLDialect$ThirdParty was unintentionally initialized at build time. org.jooq.SQLDialect$ThirdParty has been initialized without the native-image initialization instrumentation and the stack trace can't be tracked. Try marking this class for build-time initialization with --initialize-at-build-time=org.jooq.SQLDialect$ThirdParty
	at com.oracle.svm.core.util.UserError.abort(UserError.java:65)
	at com.oracle.svm.hosted.classinitialization.ConfigurableClassInitialization.checkDelayedInitialization(ConfigurableClassInitialization.java:494)
	at com.oracle.svm.hosted.classinitialization.ClassInitializationFeature.duringAnalysis(ClassInitializationFeature.java:188)
	at com.oracle.svm.hosted.NativeImageGenerator.lambda$runPointsToAnalysis$8(NativeImageGenerator.java:711)
	at com.oracle.svm.hosted.FeatureHandler.forEachFeature(FeatureHandler.java:63)
	at com.oracle.svm.hosted.NativeImageGenerator.runPointsToAnalysis(NativeImageGenerator.java:711)
	at com.oracle.svm.hosted.NativeImageGenerator.doRun(NativeImageGenerator.java:526)
	at com.oracle.svm.hosted.NativeImageGenerator.lambda$run$0(NativeImageGenerator.java:444)
	at java.util.concurrent.ForkJoinTask$AdaptedRunnableAction.exec(ForkJoinTask.java:1386)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)

```

Adding --initialize-at-run-time=org.jooq.SQLDialect$ThirdParty

```
Error: The class org.jooq.SQLDialect has already been initialized; it is too late to register org.jooq.SQLDialect for build-time initialization (from the command line). org.jooq.SQLDialect has been initialized without the native-image initialization instrumentation and the stack trace can't be tracked. Try avoiding this conflict by avoiding to initialize the class that caused initialization of org.jooq.SQLDialect or by not marking org.jooq.SQLDialect for build-time initialization.
com.oracle.svm.core.util.UserError$UserException: The class org.jooq.SQLDialect has already been initialized; it is too late to register org.jooq.SQLDialect for build-time initialization (from the command line). org.jooq.SQLDialect has been initialized without the native-image initialization instrumentation and the stack trace can't be tracked. Try avoiding this conflict by avoiding to initialize the class that caused initialization of org.jooq.SQLDialect or by not marking org.jooq.SQLDialect for build-time initialization.
	at com.oracle.svm.core.util.UserError.abort(UserError.java:65)
	at com.oracle.svm.hosted.classinitialization.ConfigurableClassInitialization.initializeAtRunTime(ConfigurableClassInitialization.java:240)
	at com.oracle.svm.hosted.classinitialization.ConfigurableClassInitialization.initializeAtRunTime(ConfigurableClassInitialization.java:208)
	at com.oracle.svm.hosted.classinitialization.InitKind.lambda$stringConsumer$0(InitKind.java:69)
	at com.oracle.svm.hosted.classinitialization.ClassInitializationFeature.processClassInitializationOptions(ClassInitializationFeature.java:146)
	at com.oracle.svm.hosted.HostedConfiguration.setDefaultIfEmpty(HostedConfiguration.java:71)
	at com.oracle.svm.hosted.NativeImageGenerator.setupNativeImage(NativeImageGenerator.java:819)
	at com.oracle.svm.hosted.NativeImageGenerator.doRun(NativeImageGenerator.java:524)
	at com.oracle.svm.hosted.NativeImageGenerator.lambda$run$0(NativeImageGenerator.java:444)
	at java.util.concurrent.ForkJoinTask$AdaptedRunnableAction.exec(ForkJoinTask.java:1386)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)


```

**Comment by aquatir** [comment] 2020-03-20 14:35
It should be `--initialize-at-build-time='org.jooq.SQLDialect$ThirdParty'`. 

I suggest running native image compilation with `--verbose`. This way if you don't put quotes around you will see output like:
`-H:ClassInitialization=org.jooq.SQLDialect:build_time`

which is clearly not what you want. With quotes it become
`-H:ClassInitialization=org.jooq.SQLDialect$ThirdParty:build_time`

**Comment by hamzaGhaissi** [comment] 2024-01-26 12:04
Closing this since there's no update from the user, if you still facing an issue please open a new github issue and attached your graalvm version and a reproducer.

**Closed by hamzaGhaissi** 2024-01-26 12:04 UTC
Labels: bug, native-image
