### ISSUE TITLE
[GR-55881] Issue with JDK Mission Control and Native Image Application Using JMX

### ISSUE THREAD

**Issue by albertattard** [oracle/graal#9349] opened 2024-07-23 06:02 UTC
I would like to report an issue I've encountered with GraalVM.  While the JDK Mission Control is able to connect to a native image application using JMX, it does not display all fields correctly. Specifically, while `LocalDateTime` fields work well with Java, they fail with the native image, resulting in the following warning:

```
WARNING: Error getting attributes: error unmarshalling return; nested exception is: java.io.EOFException
```

This issue is not limited to application MBeans but also affects the default MBeans available.

To demonstrate this problem, I have created an example which you can find here: [graalvm-observability-jmx](https://github.com/albertattard/graalvm-observability-jmx). Simply build the native image and then run the application. This application will keep running until either the exit operation is executed through JMX or it is manually terminated.

I am using the latest GraalVM 21 version on macOS (M1 chip).

```
java 21.0.4 2024-07-16 LTS
Java(TM) SE Runtime Environment Oracle GraalVM 21.0.4+8.1 (build 21.0.4+8-LTS-jvmci-23.1-b41)
Java HotSpot(TM) 64-Bit Server VM Oracle GraalVM 21.0.4+8.1 (build 21.0.4+8-LTS-jvmci-23.1-b41, mixed mode, sharing)
```

I would appreciate any assistance or guidance you can provide regarding this issue. Thank you very much for your time and support.

**Comment by selhagani** [comment] 2024-07-23 09:49
Hi @albertattard , thank you for reporting this. 

I just reproduced the issue and I confirm the issue you're facing.
We'll take a further look into this and I will keep you updated.

**Comment by albertattard** [comment] 2024-07-23 09:55
Thank you @selhagani. Let me know if you require any further information.

**Comment by fniephaus** [comment] 2024-07-23 11:47
@roberttoyonaga is this something you could look into?

**Comment by roberttoyonaga** [comment] 2024-07-23 13:13
@fniephaus Yup, I can look into this issue.

**Comment by roberttoyonaga** [comment] 2024-07-23 16:12
I was able to reproduce the issue. It looks like the problem is that you [need to add serialization configuration](https://www.graalvm.org/latest/reference-manual/native-image/metadata/#serialization-metadata-in-json) for `LocalDateTime`. 

Adding the below json in serialization-config.json inside the META-INF directory should fix the problem.
```
{
  "types":[

    {
      "name":"java.time.LocalDateTime"
    },
    {
      "name":"java.time.Ser"
    }
  ],
  "lambdaCapturingTypes":[
  ],
  "proxies":[
  ]
}
```
Running the [Native Image Tracing Agent](https://www.graalvm.org/latest/reference-manual/native-image/metadata/AutomaticMetadataCollection/) will help you generate the correct configuration automatically.

It's unfortunate that JMX requires extra configuration, but there isn't a good way of pre-configuring for all use-cases without greatly increasing image size (and remote JMX is already quite heavyweight). Maybe I'll update the JMX docs to suggest users run the tracing agent to generate their custom reflection configuration before using remote JMX.

**Comment by albertattard** [comment] 2024-07-23 16:23
Thank you very much @roberttoyonaga.  I've noticed that some of the attributes that are exposed by the VM have the same issue.  How can I address these too, please?

**Comment by roberttoyonaga** [comment] 2024-07-23 18:38
![image](https://github.com/user-attachments/assets/bcc72090-7263-47c7-bb6a-b660418820e2)
I think `"java.lang.Double"` needs to be added to the serialization config as well. All those _"[N/A]"_ attribute values are doubles. 

I'll open a PR to add  `java.lang.Double` to the remote JMX Feature serialization config. I think it's general and small enough to be added there.

Until that PR is integrated, you can use this for now:
```
{
  "types":[
    {
      "name":"java.time.LocalDateTime"
    },
    {
      "name":"java.lang.Double"
    },
    {
      "name":"java.time.Ser"
    }
  ],
  "lambdaCapturingTypes":[
  ],
  "proxies":[
  ]
}

```

**Comment by albertattard** [comment] 2024-07-23 19:20
That's great @roberttoyonaga.

**Comment by roberttoyonaga** [comment] 2024-07-23 21:16
I've put a PR up here: https://github.com/oracle/graal/pull/9357

**Comment by fniephaus** [comment] 2024-07-24 06:15
Thanks, Robert! I just took a look :)

**Comment by fniephaus** [comment] 2024-08-01 11:44
This just got fixed on the main branch, and hopefully we can still backport it into the JDK 23 release.

**Closed by fniephaus** 2024-08-01 11:44 UTC
Labels: bug, native-image
