### ISSUE TITLE
[GR-37191] Record equals/hashCode use reflection

### ISSUE THREAD

**Issue by TheMode** [oracle/graal#4348] opened 2022-02-23 05:54 UTC
**Describe the issue**
Record `equals` (and I assume `hashCode`, even if untested) currently use reflection, and effectively run much slower (about x10-20 in my case compared to my specialized method comparing the fields directly)

**Describe GraalVM and your environment:**
 - GraalVM 22.0.0.2
 - JDK major version: 17
 - OS: Linux/PopOS
 - Architecture:AMD64

**More details**
I have noticed the issue due to a hot path in my code being weirdly expensive:
https://github.com/Minestom/Minestom/blob/2c0b026e46f271a88cd9824e00f211c25980a7f1/src/main/java/net/minestom/server/listener/PlayerPositionListener.java#L36
https://github.com/Minestom/Minestom/blob/2c0b026e46f271a88cd9824e00f211c25980a7f1/src/main/java/net/minestom/server/entity/Entity.java#L1239
(notice the `Pos#equals` calls)

Flamegraph obtained with perf: ![flamegraph](https://user-images.githubusercontent.com/8581638/155267914-cdc002bb-b9ae-489a-9915-61d7d5904170.svg)

**Comment by TheMode** [comment] 2022-02-25 18:59
Is there any plan to "fix" it? It does make native-image unsuitable for any jdk16+ project, and seem to be, I assume, easily fixable.

**Comment by oubidar-Abderrahim** [comment] 2022-02-28 09:56
Hi, Thank you for reporting this, We will take a look into it and get back to you.

**Comment by oubidar-Abderrahim** [comment] 2022-02-28 10:03
Tracked internally on GR--37191

**Comment by TheMode** [comment] 2022-02-28 21:54
What about specializing those record methods to do not use  method handles? I assume that it would give you more implementation freedom.

**Comment by loicottet** [comment] 2022-03-01 15:34
The problem is that these record methods do not simply use method handles, they are method handles. This makes it more difficult to substitute them out, since we would have to generate alternative methods for every record class in the image. We also want to introduce substitutions only when strictly necessary, and will therefore primarily focus on improving the performance of our method handle implementation.

**Comment by loicottet** [comment] 2022-03-04 07:27
Our goal for this reimplementation would be to use JDK-generated, optimized bytecode method handle invokers when the handle is known at build time, which is the case for record methods. We expect to see a performance similar to a hand-written method in that case.

**Comment by kkriske** [comment] 2022-12-20 23:20
What is the current state of this? Did the mentioned rewrite happen or is there possibly an indication of a timeline when it will happen?

**Comment by loicottet** [comment] 2022-12-21 09:39
This is still on the to-do list with a fairly high priority, but there is no fixed timeline for this change yet.

**Comment by kkriske** [comment] 2023-09-07 15:09
@loicottet This pr https://github.com/oracle/graal/pull/7196 and more specifically the change-log entry below, added in this pr https://github.com/oracle/graal/pull/7262 vaguely mention method handle intrinsification of records:
https://github.com/oracle/graal/blob/35634fae3f3eb851ac9a8b72ae755889790b067a/substratevm/CHANGELOG.md?plain=1#L23

Does that address this issue as well?

**Comment by loicottet** [comment] 2023-09-12 08:23
@peter-hofer can you confirm this?

**Comment by christianwimmer** [comment] 2024-01-05 00:03
The performance problem of `equals`, `hashCode`, and `toString` methods for records will be fixed by #8109.

The plan is to integrate the fix into the upcoming GraalVM for JDK 22, and also backport to GraalVM for JDK 21 in the April CPU release.

**Comment by luneo7** [comment] 2024-04-01 22:18
Can this be backported to `release/graal-vm/23.0` (JDK 17) as well?

**Comment by christianwimmer** [comment] 2024-04-11 04:44
> Can this be backported to `release/graal-vm/23.0` (JDK 17) as well?

This is not planned, since it would require backporting a lot of feature code into JDK 17.

**Closed** 2024-04-11 04:45 UTC
Labels: bug, native-image

**Comment by kristofdho** [comment] 2024-04-22 11:54
> and also backport to GraalVM for JDK 21 in the April CPU

@christianwimmer I'm thorought confused, there still is no 21.0.3 available, and it's not on the release calendar either. Is the release still in the works but delayed? I can't find any information on this.
I know this is not really the place to ask but I've tried asking this on slack as well but I've not been able to reach anyone.

**Comment by luneo7** [comment] 2024-04-22 15:16
There are LibericaNIK builds with the fix https://github.com/bell-sw/LibericaNIK/releases/tag/23.1.3%2B1-21.0.3%2B10

**Comment by kkriske** [comment] 2024-04-22 15:47
Those are Oracle GraalVM downloads which we cannot use due to the license.
The latest CE release is 21.0.2 which does not contain this fix: https://github.com/graalvm/graalvm-ce-builds/releases/
So is the community edition for GraalVM for JDK 21 already unmaintained?

**Comment by christianwimmer** [comment] 2024-04-22 15:59
> Those are Oracle GraalVM downloads which we cannot use due to the license.

Oracle GraalVM 21.0.3 is free to use, for all commercial purposes.

**Comment by kkriske** [comment] 2024-04-22 16:04
That's what Oracle keeps repeating, but unless the license changed, it's not allowed to distibute binaries to paying customers, ergo not usable for us.

**Comment by luneo7** [comment] 2024-04-22 17:08
Yup, that's what we've read from the Graal free license as well... if we use it... as we do charge a "service fee" for our stuff in production, if we use Oracle GraalVM we would be breaking license...
GraalVM CE should be publishing versions though... as there is no new LTS version out there...
