### ISSUE TITLE
"failed: polling page vectors safepoint stub not created yet" in SharedRuntime::get_poll_stub on GraalVM 0.31

### ISSUE THREAD

**Issue by arthurp** [oracle/graal#303] opened 2018-02-19 16:50 UTC
Graal VM crashes (SIGSEGV, or "failed: polling page vectors safepoint stub not created yet" on fastdebug) when executing compiled Scala code. The problem occurs before Truffle initializes and only seems to happen when +UseJVMCICompiler is turned on. The crash is non-deterministic and only occurs quickly in 1 in 10 runs (roughly). It appears to be less frequent on a fast debug build.

Currently reproducing this crash requires running the entire Orc compiler (https://github.com/orc-lang/orc). However, a reference in one of the hs_err files makes me thing I might be able to create a scala-parser-combinators stress test to set this off. I'll try to do that in the next few days. But for now here is the jar which contains the ```scala.util.parsing.combinator.Parsers$$anon$2$$Lambda$477.apply``` method which appeared in the hs_err: http://central.maven.org/maven2/org/scala-lang/modules/scala-parser-combinators_2.12/1.0.6/scala-parser-combinators_2.12-1.0.6.jar.

With a fastdebug libjvm (from @gilles-duboscq via graal-dev) I did get hs_err files. One file (out of many runs) did have a Java level stack trace: [hs_err_pid3981.log](https://github.com/oracle/graal/files/1737543/hs_err_pid3981.log). However, most of the hs_err files have no frames above the pthreads signal handler: [hs_err_pid5402.log](https://github.com/oracle/graal/files/1737547/hs_err_pid5402.log).

**Comment by dougxc** [comment] 2018-02-19 17:03
Great - `hs_err_pid3981.log` shows the problem. The issue is that the stub for handling a signal in code using wide vectors is simply not generated.

**Comment by dougxc** [comment] 2018-02-19 17:11
@arthurp , could you please run the following on both the debug and non-debug binaries and copy the output here:
```
java -XX:+PrintFlagsFinal -version 2>&1 | grep MaxVectorSize
```

**Comment by arthurp** [comment] 2018-02-19 20:23
From ```java -XX:+PrintFlagsFinal -version 2>&1 | grep MaxVectorSize```.

Debug libjvm output:
```
     intx MaxVectorSize                             = 16                                  {C2 product}
```

Non-debug libjvm output:
```
     intx MaxVectorSize                             = 16                                  {C2 product}
```

**Comment by dougxc** [comment] 2018-02-19 20:35
That confirms it - you are [apparently](https://github.com/graalvm/graal-jvmci-8/blob/b6258e95c1150ad7c30d11806c6a142104b2351c/src/cpu/x86/vm/vm_version_x86.cpp#L682) on a machine that does not support vector instructions but Graal is generating vector instructions.

**Comment by tkrodriguez** [comment] 2018-02-19 21:34
It supports vectors but only 16 byte vectors, not the 32 byte vectors implied by other CPU features.  From the hs_err log this is an AMD CPU and vm_version_x86.cpp clamps the vector size to 16 byte there for some reason even though AVX is supported according the CPU features.

Anyway, our vectorization logic needs to respect the smaller vector width on these machines though I'm not sure where that logic would need to live.  We could change the AMD64 arch to disable AVX in this case but that seems heavyweight.  Manually setting -XX:MaxVectorSize=16 should reproduce this problem on an AVX machine.

**Comment by arthurp** [comment] 2018-02-19 22:25
The machine is an AMD FX-8350 (Bulldozer) which lacks AVX2. It does however support AVX with 256 bit registers. I'm curious why the JVM is clamping the vector size to 16. The output from ```java -XX:+PrintFlagsFinal -XX:+PrintMiscellaneous -XX:+Verbose -version``` tells me that it supports ymm 256 bit registers at the OS and CPU level. Here is the relevant output:
```
State of YMM registers after signal handle:
YMM0: cafebabe cafebabe cafebabe cafebabe cafebabe cafebabe cafebabe cafebabe
YMM7: cafebabe cafebabe cafebabe cafebabe cafebabe cafebabe cafebabe cafebabe
YMM8: cafebabe cafebabe cafebabe cafebabe cafebabe cafebabe cafebabe cafebabe
YMM15: cafebabe cafebabe cafebabe cafebabe cafebabe cafebabe cafebabe cafebabe
Logical CPUs per core: 1
UseSSE=4  UseAVX=1  UseAES=1  MaxVectorSize=16
Allocation: no prefetching
PrefetchCopyIntervalInBytes 576
PrefetchScanIntervalInBytes 576
PrefetchFieldsAhead 1
ContendedPaddingWidth 128
CPU:total 8 (initial active 8) (8 cores per cpu, 1 threads per core) family 21 model 2 stepping 0, cmov, cx8, fxsr, mmx, sse, sse2, sse3, ssse3, sse4.1, sse4.2, popcnt, avx, ae
s, clmul, mmxext, 3dnowpref, lzcnt, sse4a, tsc, tscinvbit, tscinv, bmi1
```

**Comment by arthurp** [comment] 2018-02-19 23:58
I've tested with ```-XX:UseAVX=0``` and it appears to be stable with that option (as expected from the discussion above). I'll use this as a work around until the vector size issue is fixed. That being said turning off AVX does appear to affect the performance, so I'd like to be able to use AVX eventually.

**Comment by rschatz** [comment] 2018-03-05 12:16
Hotspot makes assumptions about the compiled code based on the `MaxVectorSize` flag. That means we need to always respect that limit, in addition to checking the CPU capabilities.

This is fixed on master and will appear in the next graalvm release (0.33).

**Closed by rschatz** 2018-03-05 12:16 UTC
Labels: bug, compiler
