### ISSUE TITLE
This is not feature request but a simple question

### ISSUE THREAD

**Issue by Malaska678** [oracle/graal#2848] opened 2020-09-15 02:03 UTC
Is the graal vm for linux amd64 also for android aarch32/aarch64?

**Comment by oubidar-Abderrahim** [comment] 2020-09-15 08:25
We do have a distribution for Aarch64 (you can find the full list [here](https://github.com/graalvm/graalvm-ce-builds/releases/tag/vm-20.2.0). 
There was a discussion about using GraalVM on top of Android in this [thread](https://github.com/oracle/graal/issues/632) a few examples can be found [here](https://github.com/gluonhq/client-samples/).

**Comment by oubidar-Abderrahim** [comment] 2020-09-15 08:25
Duplicate of #632

**Closed by oubidar-Abderrahim** 2020-09-15 08:25 UTC
Labels: question

**Comment by Malaska678** [comment] 2020-09-15 08:28
I already know that

**Comment by Malaska678** [comment] 2020-09-15 08:29
So the one that for linux aarch64 is the one that for android aarch64

**Comment by Malaska678** [comment] 2020-09-15 09:33
Hey! What about 32 bit devices support?

**Comment by oubidar-Abderrahim** [comment] 2020-09-15 10:01
@vjovanov
