### ISSUE TITLE
Image generator watchdog detected no activity

### ISSUE THREAD

**Issue by nirvdrum** [oracle/graal#6108] opened 2023-03-02 18:55 UTC
**Describe the issue**

While building a shared library with Native Image 23.0.0-dev, I ran into a problem where the image possibly deadlocks. This happened several times, but I can't reliably induce the behavior. I'm not sure what's different about my system when the build fails.

**Steps to reproduce the issue**
Please include both build steps as well as run steps
1. Download a GraalVM dev snapshot 
2. `gu install native-image ruby js`
3. `export JAVA_HOME=path/to/GraalVM/distribution`
4. `git clone https://github.com/nirvdrum/native-image-playground.git'
5. `cd native-image-playground`
6. `git checkout ffed96cc3105036205fe78627e6d5ac6fc5e349d`
7. `mvn -P jni-native -D skipTests=true clean package`

**Describe GraalVM and your environment:**
 - GraalVM version (latest snapshot builds can be found [here](https://github.com/graalvm/graalvm-ce-dev-builds/releases)), or commit id if built from source: **23.0.0-dev (8c5b2ca42299ffdc0aecf05280db43ed87fbabca)**
 - JDK major version: **17**
 - OS: **macOS 13.2.1**
 - Architecture: **AArch64**
 - native-maven-plugin version: **0.9.20**

**More details**

```
ative-image-playground ---
[INFO] Skipping native-image tests (parameter 'skipTests' or 'skipNativeTests' is true).
[INFO]
[INFO] --- maven-jar-plugin:3.0.2:jar (default-jar) @ native-image-playground ---
[INFO] Building jar: /Users/nirvdrum/dev/workspaces/native-image-playground/target-jni-native/native-image-playground-1.0-SNAPSHOT.jar
[INFO]
[INFO] --- native-maven-plugin:0.9.20:compile-no-fork (build-native) @ native-image-playground ---
[INFO] Found GraalVM installation from JAVA_HOME variable.
[INFO] Executing: /Users/nirvdrum/dev/bin/graalvm-ce-java17-23.0.0-dev/Contents/Home/bin/native-image -cp /Users/nirvdrum/dev/workspaces/native-image-playground/target-jni-native/native-image-playground-1.0-SNAPSHOT.jar:/Users/nirvdrum/.m2/repository/org/apache/sis/core/sis-referencing/1.0/sis-referencing-1.0.jar:/Users/nirvdrum/.m2/repository/org/apache/sis/core/sis-metadata/1.0/sis-metadata-1.0.jar:/Users/nirvdrum/.m2/repository/javax/measure/unit-api/1.0/unit-api-1.0.jar:/Users/nirvdrum/.m2/repository/org/opengis/geoapi/3.0.1/geoapi-3.0.1.jar:/Users/nirvdrum/.m2/repository/org/apache/sis/core/sis-utility/1.0/sis-utility-1.0.jar --no-fallback --shared -H:Path=/Users/nirvdrum/dev/workspaces/native-image-playground/target-jni-native -H:Name=libjni-runner -H:Class=com.nirvdrum.truffleruby.NativeLibraryRuby --language:js --language:ruby -H:JNIConfigurationFiles=/Users/nirvdrum/dev/workspaces/native-image-playground/src/main/java/../resources/native-jni-config.json
========================================================================================================================
GraalVM Native Image: Generating 'libjni-runner' (shared library)...
========================================================================================================================
Warning: Could not resolve class com.shopify.truffleruby.NativeLibrary for reflection configuration. Reason: java.lang.ClassNotFoundException: com.shopify.truffleruby.NativeLibrary.
Warning: Could not resolve class com.shopify.truffleruby.NativeLibraryRuby for reflection configuration. Reason: java.lang.ClassNotFoundException: com.shopify.truffleruby.NativeLibraryRuby.
[1/8] Initializing...                                                                                    (9.1s @ 0.33GB)
 Version info: 'GraalVM 23.0.0-dev Java 17.0.7+2-jvmci-23.0-b08 CE'
 Java version info: '17.0.7+2-jvmci-23.0-b08'
 C compiler: cc (apple, arm64, 14.0.0)
 Garbage collector: Serial GC (max heap size: unlimited)
 4 user-specific feature(s)
 - com.oracle.svm.truffle.ICU4JFeature: Provides support for ICU4J library.
 - com.oracle.svm.truffle.TruffleBaseFeature: Provides base support for Truffle
 - com.oracle.svm.truffle.TruffleFeature: Enables compilation of Truffle ASTs to machine code
 - org.graalvm.home.HomeFinderFeature: Finds GraalVM paths and its version number
[2/8] Performing analysis...  [*********]                                                              (255.7s @ 5.24GB)
  32,340 (96.42%) of 33,541 types reachable
  51,293 (63.80%) of 80,402 fields reachable
 161,708 (75.44%) of 214,367 methods reachable
  26,883 (12.54%) of 214,367 methods included for runtime compilation
   8,699 types,   102 fields, and 1,570 methods registered for reflection
      66 types,    60 fields, and   257 methods registered for JNI access
       4 native libraries: -framework Foundation, dl, pthread, z
[3/8] Building universe...                                                                              (19.0s @ 3.21GB)
[4/8] Parsing methods...      [*******]                                                                 (56.1s @ 5.20GB)
[5/8] Inlining methods...     [****]                                                                    (47.8s @ 2.79GB)
[6/8] Compiling methods...    [**************]                                                         (207.1s @ 4.19GB)

=== Image generator watchdog detected no activity. This can be a sign of a deadlock during image building. Dumping all stack traces. Current time: Wed Mar 01 20:52:44 EST 2023
"main" Id=1 in RUNNABLE
    at java.base@17.0.7/java.util.HashMap.hash(HashMap.java:338)
    at java.base@17.0.7/java.util.HashMap.getNode(HashMap.java:568)
    at java.base@17.0.7/java.util.HashMap.get(HashMap.java:556)
    at app//com.oracle.svm.core.heap.ReferenceMapEncoder.add(ReferenceMapEncoder.java:78)
    at app//com.oracle.svm.core.code.CodeInfoEncoder.encodeReferenceMaps(CodeInfoEncoder.java:273)
    at app//com.oracle.svm.core.code.CodeInfoEncoder.encodeAllAndInstall(CodeInfoEncoder.java:259)
    at app//com.oracle.svm.hosted.image.NativeImageCodeCache.installCodeInfo(NativeImageCodeCache.java:386)
    at app//com.oracle.svm.hosted.image.NativeImageCodeCache.buildRuntimeMetadata(NativeImageCodeCache.java:363)
    at app//com.oracle.svm.hosted.image.LIRNativeImageCodeCache.layoutMethods(LIRNativeImageCodeCache.java:221)
    at app//com.oracle.svm.hosted.NativeImageGenerator.doRun(NativeImageGenerator.java:692)
    at app//com.oracle.svm.hosted.NativeImageGenerator.run(NativeImageGenerator.java:562)[7/8]
Layouting methods...    [***********]                                                            (127.9s @ 4.46GB)
    at app//com.oracle.svm.hosted.NativeImageGeneratorRunner.buildImage(NativeImageGeneratorRunner.java:408)
    at app//com.oracle.svm.hosted.NativeImageGeneratorRunner.build(NativeImageGeneratorRunner.java:616)
    at app//com.oracle.svm.hosted.NativeImageGeneratorRunner.start(NativeImageGeneratorRunner.java:134)
    at app//com.oracle.svm.hosted.NativeImageGeneratorRunner.main(NativeImageGeneratorRunner.java:94)
    at app//com.oracle.svm.hosted.NativeImageGeneratorRunner$JDK9Plus.main(NativeImageGeneratorRunner.java:630)

"Reference Handler" Id=2 in RUNNABLE
    at java.base@17.0.7/java.lang.ref.Reference.waitForReferencePendingList(Native Method)
    at java.base@17.0.7/java.lang.ref.Reference.processPendingReferences(Reference.java:253)
    at java.base@17.0.7/java.lang.ref.Reference$ReferenceHandler.run(Reference.java:215)

"Finalizer" Id=3 in WAITING on lock=java.lang.ref.ReferenceQueue$Lock@4502c958
    at java.base@17.0.7/java.lang.Object.wait(Native Method)
    at java.base@17.0.7/java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:155)
    at java.base@17.0.7/java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:176)
    at java.base@17.0.7/java.lang.ref.Finalizer$FinalizerThread.run(Finalizer.java:172)

"Signal Dispatcher" Id=4 in RUNNABLE

"JVMCI-native CompilerThread0" Id=7 in RUNNABLE

"Common-Cleaner" Id=12 in TIMED_WAITING on lock=java.lang.ref.ReferenceQueue$Lock@413d4520
    at java.base@17.0.7/java.lang.Object.wait(Native Method)
    at java.base@17.0.7/java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:155)
    at java.base@17.0.7/jdk.internal.ref.CleanerImpl.run(CleanerImpl.java:140)
    at java.base@17.0.7/java.lang.Thread.run(Thread.java:833)
    at java.base@17.0.7/jdk.internal.misc.InnocuousThread.run(InnocuousThread.java:162)

"Notification Thread" Id=13 in RUNNABLE

"Thread-0" Id=14 in RUNNABLE
    at java.management@17.0.7/sun.management.ThreadImpl.dumpThreads0(Native Method)
    at java.management@17.0.7/sun.management.ThreadImpl.dumpAllThreads(ThreadImpl.java:521)
    at java.management@17.0.7/sun.management.ThreadImpl.dumpAllThreads(ThreadImpl.java:509)
    at app//com.oracle.svm.hosted.DeadlockWatchdog.threadDump(DeadlockWatchdog.java:124)
    at app//com.oracle.svm.hosted.DeadlockWatchdog.watchdogThread(DeadlockWatchdog.java:81)
    at app//com.oracle.svm.hosted.DeadlockWatchdog$$Lambda$133/0x0000000300138f90.run(Unknown Source)
    at java.base@17.0.7/java.lang.Thread.run(Thread.java:833)

"ForkJoinPool.commonPool-worker-2" Id=25 in TIMED_WAITING on lock=java.util.concurrent.ForkJoinPool@5a0ab6e0
    at java.base@17.0.7/jdk.internal.misc.Unsafe.park(Native Method)
    at java.base@17.0.7/java.util.concurrent.locks.LockSupport.parkUntil(LockSupport.java:410)
    at java.base@17.0.7/java.util.concurrent.ForkJoinPool.awaitWork(ForkJoinPool.java:1726)
    at java.base@17.0.7/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1623)
    at java.base@17.0.7/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)

"ForkJoinPool-2-worker-6" Id=42 in TIMED_WAITING on lock=java.util.concurrent.ForkJoinPool@43fc363
    at java.base@17.0.7/jdk.internal.misc.Unsafe.park(Native Method)
    at java.base@17.0.7/java.util.concurrent.locks.LockSupport.parkUntil(LockSupport.java:410)
    at java.base@17.0.7/java.util.concurrent.ForkJoinPool.awaitWork(ForkJoinPool.java:1726)
    at java.base@17.0.7/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1623)
    at java.base@17.0.7/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)

"ForkJoinPool-2-worker-7" Id=43 in WAITING on lock=java.util.concurrent.ForkJoinPool@43fc363
    at java.base@17.0.7/jdk.internal.misc.Unsafe.park(Native Method)
    at java.base@17.0.7/java.util.concurrent.locks.LockSupport.park(LockSupport.java:341)
    at java.base@17.0.7/java.util.concurrent.ForkJoinPool.awaitWork(ForkJoinPool.java:1724)
    at java.base@17.0.7/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1623)
    at java.base@17.0.7/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)

"pool-1-thread-1" Id=51 in TIMED_WAITING on lock=java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject@666ada1a
    at java.base@17.0.7/jdk.internal.misc.Unsafe.park(Native Method)
    at java.base@17.0.7/java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:252)
    at java.base@17.0.7/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitNanos(AbstractQueuedSynchronizer.java:1672)
    at java.base@17.0.7/java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:1182)
    at java.base@17.0.7/java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:899)
    at java.base@17.0.7/java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1062)
    at java.base@17.0.7/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1122)
    at java.base@17.0.7/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
    at java.base@17.0.7/java.lang.Thread.run(Thread.java:833)

"ForkJoinPool-3-worker-1" Id=52 in WAITING on lock=java.util.concurrent.ForkJoinPool@35718786
    at java.base@17.0.7/jdk.internal.misc.Unsafe.park(Native Method)
    at java.base@17.0.7/java.util.concurrent.locks.LockSupport.park(LockSupport.java:341)
    at java.base@17.0.7/java.util.concurrent.ForkJoinPool.awaitWork(ForkJoinPool.java:1724)
    at java.base@17.0.7/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1623)
    at java.base@17.0.7/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)

"ForkJoinPool-3-worker-2" Id=53 in TIMED_WAITING on lock=java.util.concurrent.ForkJoinPool@35718786
    at java.base@17.0.7/jdk.internal.misc.Unsafe.park(Native Method)
    at java.base@17.0.7/java.util.concurrent.locks.LockSupport.parkUntil(LockSupport.java:410)
    at java.base@17.0.7/java.util.concurrent.ForkJoinPool.awaitWork(ForkJoinPool.java:1726)
    at java.base@17.0.7/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1623)
    at java.base@17.0.7/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)

"ForkJoinPool-3-worker-3" Id=54 in WAITING on lock=java.util.concurrent.ForkJoinPool@35718786
    at java.base@17.0.7/jdk.internal.misc.Unsafe.park(Native Method)
    at java.base@17.0.7/java.util.concurrent.locks.LockSupport.park(LockSupport.java:341)
    at java.base@17.0.7/java.util.concurrent.ForkJoinPool.awaitWork(ForkJoinPool.java:1724)
    at java.base@17.0.7/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1623)
    at java.base@17.0.7/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)

"ForkJoinPool-3-worker-4" Id=55 in WAITING on lock=java.util.concurrent.ForkJoinPool@35718786
    at java.base@17.0.7/jdk.internal.misc.Unsafe.park(Native Method)
    at java.base@17.0.7/java.util.concurrent.locks.LockSupport.park(LockSupport.java:341)
    at java.base@17.0.7/java.util.concurrent.ForkJoinPool.awaitWork(ForkJoinPool.java:1724)
    at java.base@17.0.7/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1623)
    at java.base@17.0.7/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)

"ForkJoinPool-3-worker-5" Id=56 in WAITING on lock=java.util.concurrent.ForkJoinPool@35718786
    at java.base@17.0.7/jdk.internal.misc.Unsafe.park(Native Method)
    at java.base@17.0.7/java.util.concurrent.locks.LockSupport.park(LockSupport.java:341)
    at java.base@17.0.7/java.util.concurrent.ForkJoinPool.awaitWork(ForkJoinPool.java:1724)
    at java.base@17.0.7/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1623)
    at java.base@17.0.7/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)

"ForkJoinPool-3-worker-6" Id=57 in WAITING on lock=java.util.concurrent.ForkJoinPool@35718786
    at java.base@17.0.7/jdk.internal.misc.Unsafe.park(Native Method)
    at java.base@17.0.7/java.util.concurrent.locks.LockSupport.park(LockSupport.java:341)
    at java.base@17.0.7/java.util.concurrent.ForkJoinPool.awaitWork(ForkJoinPool.java:1724)
    at java.base@17.0.7/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1623)
    at java.base@17.0.7/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)

"ForkJoinPool-3-worker-8" Id=59 in WAITING on lock=java.util.concurrent.ForkJoinPool@35718786
    at java.base@17.0.7/jdk.internal.misc.Unsafe.park(Native Method)
    at java.base@17.0.7/java.util.concurrent.locks.LockSupport.park(LockSupport.java:341)
    at java.base@17.0.7/java.util.concurrent.ForkJoinPool.awaitWork(ForkJoinPool.java:1724)
    at java.base@17.0.7/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1623)
    at java.base@17.0.7/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)


=== Memory statistics (in MB):
=== Used heap size: 9198
=== Free heap size: 3879
=== Maximum heap size: 11655
=== Image generator watchdog is aborting image generation. To configure the watchdog, use the options -H:DeadlockWatchdogInterval=10 and -H:+DeadlockWatchdogExitOnTimeout
Error: Image build request for 'libjni-runner' (pid: 56700, path: /Users/nirvdrum/dev/workspaces/native-image-playground/target-jni-native) failed with exit status 30
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  28:28 min
[INFO] Finished at: 2023-03-01T20:54:23-05:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.graalvm.buildtools:native-maven-plugin:0.9.20:compile-no-fork (build-native) on project native-image-playground: Execution of /Users/nirvdrum/dev/bin/graalvm-ce-java17-23.0.0-dev/Contents/Home/bin/native-image -cp /Users/nirvdrum/dev/workspaces/native-image-playground/target-jni-native/native-image-playground-1.0-SNAPSHOT.jar:/Users/nirvdrum/.m2/repository/org/apache/sis/core/sis-referencing/1.0/sis-referencing-1.0.jar:/Users/nirvdrum/.m2/repository/org/apache/sis/core/sis-metadata/1.0/sis-metadata-1.0.jar:/Users/nirvdrum/.m2/repository/javax/measure/unit-api/1.0/unit-api-1.0.jar:/Users/nirvdrum/.m2/repository/org/opengis/geoapi/3.0.1/geoapi-3.0.1.jar:/Users/nirvdrum/.m2/repository/org/apache/sis/core/sis-utility/1.0/sis-utility-1.0.jar --no-fallback --shared -H:Path=/Users/nirvdrum/dev/workspaces/native-image-playground/target-jni-native -H:Name=libjni-runner -H:Class=com.nirvdrum.truffleruby.NativeLibraryRuby --language:js --language:ruby -H:JNIConfigurationFiles=/Users/nirvdrum/dev/workspaces/native-image-playground/src/main/java/../resources/native-jni-config.json returned non-zero result -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
nirvdrum@Kevins-MacBook-Pro-2 ~/d/w/native-image-playground (trunk) [1]>
nirvdrum@Kevins-MacBook-Pro-2 ~/d/w/native-image-playground (trunk) [1]>
nirvdrum@Kevins-MacBook-Pro-2 ~/d/w/native-image-playground (trunk) [1]>
nirvdrum@Kevins-MacBook-Pro-2 ~/d/w/native-image-playground (trunk) [1]>
nirvdrum@Kevins-MacBook-Pro-2 ~/d/w/native-image-playground (trunk) [1]>
nirvdrum@Kevins-MacBook-Pro-2 ~/d/w/native-image-playground (trunk) [1]>
nirvdrum@Kevins-MacBook-Pro-2 ~/d/w/native-image-playground (trunk) [1]> mvn -P jni-native -D skipTests=true clean package
[INFO] Scanning for projects...
[INFO]
[INFO] ----------< com.shopify.truffleruby:native-image-playground >-----------
[INFO] Building native-image-playground 1.0-SNAPSHOT
[INFO] --------------------------------[ jar ]---------------------------------
[INFO]
[INFO] --- maven-clean-plugin:3.1.0:clean (default-clean) @ native-image-playground ---
[INFO] Deleting /Users/nirvdrum/dev/workspaces/native-image-playground/target-jni-native
[INFO]
[INFO] --- maven-resources-plugin:3.0.2:resources (default-resources) @ native-image-playground ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 1 resource
[INFO]
[INFO] --- maven-compiler-plugin:3.8.0:compile (default-compile) @ native-image-playground ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 6 source files to /Users/nirvdrum/dev/workspaces/native-image-playground/target-jni-native/classes
[INFO] /Users/nirvdrum/dev/workspaces/native-image-playground/src/main/java/com/nirvdrum/truffleruby/NativeImage.java: Some input files use or override a deprecated API.
[INFO] /Users/nirvdrum/dev/workspaces/native-image-playground/src/main/java/com/nirvdrum/truffleruby/NativeImage.java: Recompile with -Xlint:deprecation for details.
[INFO]
[INFO] --- maven-resources-plugin:3.0.2:testResources (default-testResources) @ native-image-playground ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory /Users/nirvdrum/dev/workspaces/native-image-playground/src/test/resources
[INFO]
[INFO] --- maven-compiler-plugin:3.8.0:testCompile (default-testCompile) @ native-image-playground ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 1 source file to /Users/nirvdrum/dev/workspaces/native-image-playground/target-jni-native/test-classes
[INFO]
[INFO] --- maven-surefire-plugin:2.22.1:test (default-test) @ native-image-playground ---
[INFO] Tests are skipped.
[INFO]
[INFO] --- native-maven-plugin:0.9.20:test (test-native) @ native-image-playground ---
[INFO] Skipping native-image tests (parameter 'skipTests' or 'skipNativeTests' is true).
[INFO]
[INFO] --- maven-jar-plugin:3.0.2:jar (default-jar) @ native-image-playground ---
[INFO] Building jar: /Users/nirvdrum/dev/workspaces/native-image-playground/target-jni-native/native-image-playground-1.0-SNAPSHOT.jar
[INFO]
[INFO] --- native-maven-plugin:0.9.20:compile-no-fork (build-native) @ native-image-playground ---
[INFO] Found GraalVM installation from JAVA_HOME variable.

```

**Comment by phejl** [comment] 2023-03-06 19:36
It appeared after upgrading from 22.3-r17 to 22.3.1-r17. Seems it might be similar to https://github.com/oracle/graal/issues/4822. Affected project is using poi libraries as well.

**Comment by oubidar-Abderrahim** [comment] 2023-03-08 15:03
Hi, Thank you for reporting this, we'll take a look into it shortly.

**Comment by oubidar-Abderrahim** [comment] 2023-04-03 12:26
Hi, I tested with the latest snapshot build of 23.0.0 and could not reproduce the issue, could you please verify again with the latest 23.0.0-dev? Thanks

**Comment by oubidar-Abderrahim** [comment] 2023-06-12 09:53
Closing this issue as "could not reproduce".

**Closed by oubidar-Abderrahim** 2023-06-12 09:53 UTC
Labels: bug, native-image
