### ISSUE TITLE
Building app using SWT on Windows doesn't copy SWT DLL to output

### ISSUE THREAD

**Issue by cypressious** [oracle/graal#5892] opened 2023-02-02 21:43 UTC
**Describe the issue**
Building an application that uses SWT as a dependency on Windows doesn't copy the SWT DLL to the output. When running the application on a machine that never executed an SWT applications, it exits with an exception.

**Steps to reproduce the issue**
1. Clone https://github.com/cypressious/native-image-swt-repro
2. In x64 Native Tools Command Prompt navigate to project directory
3. run `gradlew nativeCompile`
4. Delete `C:\Users\<User>\.swt\lib\win32\x86_64\swt-win32-4332.dll`
5. Run built application from `build\native\nativeCompile`
6. Observe error

```
Exception in thread "main" java.lang.UnsatisfiedLinkError: Could not load SWT library. Reasons:
        no swt-win32-4332 in java.library.path
        no swt-win32 in java.library.path
        Can't load library: C:\Users\Kirill\.swt\lib\win32\x86_64\swt-win32-4332.dll
        Can't load library: C:\Users\Kirill\.swt\lib\win32\x86_64\swt-win32.dll

        at org.eclipse.swt.internal.Library.loadLibrary(Unknown Source)
        at org.eclipse.swt.internal.Library.loadLibrary(Unknown Source)
        at org.eclipse.swt.internal.C.<clinit>(Unknown Source)
        at java.base@19.0.1/java.lang.Class.ensureInitialized(DynamicHub.java:533)
        at org.eclipse.swt.widgets.Display.<clinit>(Unknown Source)
        at info.rakhman.native_repro.MainKt.<clinit>(Main.kt:6)
```

**Describe GraalVM and your environment:**
 - GraalVM version: [GraalVM CE 23.0.0-dev-20230130_2334](https://github.com/graalvm/graalvm-ce-dev-builds/releases/tag/23.0.0-dev-20230130_2334)
 - JDK major version: **19**
 - OS: **Windows 10**
 - Architecture: **AMD64**

**Comment by fniephaus** [comment] 2023-02-03 12:28
Thanks for opening the issue, @cypressious. I double checked with a colleague and this behavior seems expected. Native Image may output JDK dependencies but not other dependencies introduced or used by external libraries. I believe the reason why SWT is not working as intended is that your [resource-config.json](https://github.com/cypressious/native-image-swt-repro/blob/3ba677cdb4bc9c1a883bc24178e5528b53bc3202/src/main/resources/META-INF/native-image/resource-config.json) is empty and thus does not contain shared library files. SWT, on the other hand, seems to extract these files from the JAR when not found on the target machine (see [here](https://github.com/eclipse-platform/eclipse.platform.swt/blob/97eac75999dc1cb1e72962d5cbd2c3ea925b7095/bundles/org.eclipse.swt/Eclipse%20SWT%20PI/common/org/eclipse/swt/internal/Library.java#L336)).

Could you try adding the required entries to your `resource-config.json` and see whether this fixes the issue? I'm closing this for now but please feel free to post follow up comments.

**Closed by fniephaus** 2023-02-03 12:28 UTC
Labels: bug, native-image

**Comment by cypressious** [comment] 2023-02-03 18:14
@fniephaus I reran `gradlew -Pagent run` and `gradlew metadataCopy --task run --dir src/main/resources/META-INF/native-image` and this time it added `"pattern":"\\Qswt-win32-4332.dll\\E"` to the `resource-config.json`. However, running `gradlew nativeCompile` still doesn't copy over the file.

**Comment by fniephaus** [comment] 2023-02-03 19:26
Yes, that is expected. As mentioned already, Native Image may output shared libs from the JDK but not those of third party libraries. Your initial agent run didn't see the native library because it was already in the expected location. Removing it caused the agent to detect the copying operation performed by the library (from JAR to disk). Now that the library is in the resources config, it's included in the native executable. When you run it on another system, it should put the native library in the expected location on first execution. If you want to keep your deployment size as small as possible, don't include the library in the executable but ship it in the same directory with your executable. That way, the native library only exists once, outside of the executable.

I hope this helps!

**Comment by cypressious** [comment] 2023-02-03 21:06
Oh, I didn't realize the addition to the `resource-config.json` fixed the issue. The app is running now without the DLL in the user home directory. Thanks for the help 👍

**Comment by fniephaus** [comment] 2023-02-03 21:13
Great, you are welcome! 🙂
