### ISSUE TITLE
GraalVM support for Dart language

### ISSUE THREAD

**Issue by halimpuckjava** [oracle/graal#2893] opened 2020-10-05 09:11 UTC

**Comment by mcraj017** [comment] 2020-10-06 08:05
Hello @halimpuckjava  
thank you for the feature request 

Please provide the information in the form of below template 

Feature request

**1. Is your feature request related to a problem? Please describe.
2. Describe the solution you'd like.
3. Describe who do you think will benefit the most.
4. Describe alternatives you've considered.**
5. Additional context.

**Comment by dougxc** [comment] 2020-10-06 08:45
Duplicate of #437. Please search for existing issues before opening new ones.

**Closed by dougxc** 2020-10-06 08:45 UTC
Labels: feature
