### ISSUE TITLE
TypeNotPresentException: Type com.rometools.rome.feed.WireFeed not present

### ISSUE THREAD

**Issue by wenqiglantz** [oracle/graal#5471] opened 2022-11-20 02:41 UTC
I am trying to build my spring boot 3.0.0-SNAPSHOT app, using GraalVM 23.0.0-dev Java 17 CE, I am running into the following error:

```
Fatal error: java.lang.TypeNotPresentException: Type com.rometools.rome.feed.WireFeed not present
	at java.base/sun.reflect.generics.factory.CoreReflectionFactory.makeNamedType(CoreReflectionFactory.java:117)
	at java.base/sun.reflect.generics.visitor.Reifier.visitClassTypeSignature(Reifier.java:125)
```

All detailed log from my github actions workflow run can be found here, https://github.com/wenqiglantz/customer-service-springboot3/actions/runs/3506099494/jobs/5872894471#step:7:25705.

**Steps to reproduce the issue**
Please include both build steps as well as run steps
1. **git clone https://github.com/wenqiglantz/customer-service-springboot3.git**
2. **mvn clean -Pnative native:compile -Dmaven.test.skip**

**Describe GraalVM and your environment:**
 - GraalVM version: **GraalVM 23.0.0-dev Java 17 CE (Java Version 17.0.5+6-jvmci-23.0-b01)**
 - JDK major version: **17**
 - OS: **ubuntu**
 - Architecture: **[e.g.: AMD64]**

**Comment by oubidar-Abderrahim** [comment] 2022-11-25 10:19
Hi, Thank you for reporting this, we'll take a look into it shortly.

**Comment by oubidar-Abderrahim** [comment] 2022-12-05 15:38
I could not reproduce this issue using `GraalVM CE 23.0.0-dev (build 17.0.6+2-jvmci-23.0-b02)` could you please verify the GraalVM installation you have, maybe re-install it, and let us know if the issue is still there?

**Comment by wenqiglantz** [comment] 2022-12-16 14:51
Thanks @oubidar-Abderrahim!  Yes that original build now succeeds with the latest GraalVM dev build, as can be seen here in this github actions workflow run: https://github.com/wenqiglantz/customer-service-springboot3/actions/runs/3705374440.

However when I tried to build with BuildPacks via github actions workflow, and it failed with error "Fatal error: java.lang.TypeNotPresentException: Type kotlinx.serialization.StringFormat not present" at https://github.com/wenqiglantz/customer-service-springboot3/actions/runs/3705776642/jobs/6280126891#step:9:470.  Not sure if the root cause is related to the original error logged in this issue?  Any insight would be appreciated.

**Comment by oubidar-Abderrahim** [comment] 2022-12-19 16:47
@wenqiglantz what version of BuildPacks you're using? if you're using a version lower than v5.3.1, could you please try v5.3.1?

**Comment by oubidar-Abderrahim** [comment] 2023-02-10 16:11
I'll be closing this issue for now, if you still need assistance you can reopen the issue. Thank you

**Closed by oubidar-Abderrahim** 2023-02-10 16:11 UTC
Labels: bug, native-image
