### ISSUE TITLE
[native-image] Random PosixParkEvent VMError.shouldNotReachHere error at runtime

### ISSUE THREAD

**Issue by dpetrick** [oracle/graal#818] opened 2018-11-22 16:44 UTC
We managed to compile a large Scala codebase into a native image, which is running as expected with the exception of a seemingly random crash (MacOs Sierra 10.12.6, Graal RC9): 
```
[PosixParkEvent.condTimedWait(delayNanos: 100000000): Should not reach here.  mutex: 0x7fcc4a9000e0  cond: 0x7fcc4a900120  deadlineTimeSpec.tv_sec: 1542722165  deadlineTimespec.tv_nsec: 1000000000  status: 22 Invalid argument]
VMError.shouldNotReachHere: park(long): condition variable timed wait
```

I say random, as I can't reproduce this error via any kind of input (the binary is essentially a webserver) - it's rare, it may happen few minutes after starting the binary, sometimes after several hours, and sometimes it can go on for the whole working day without issues, making this issue hard to trace.

I attached a the full output of one crash at the end of this issue, as well as used native-image options.

*What I have tried / investigated already:*
- At first I assumed that `org.LatencyUtils` is the culprit, as it always shows up as current thread in the stack traces, however, after replacing those parts of the application and explicitly throwing out those dependencies during packaging, the crash still occurs, just with `java.lang.Thread` as the current thread.
- I investigated the Graal SDK code that throws the aforementioned error to get an idea of what might be going wrong in either Graal or our application, not knowing where the bug is actually located, to no avail.
- I find the mention of `jni` odd in the error, as our application is not using JNI at all. However, after looking at the svm code, I assume that it is SVM's native integration, not what is usually referred to as JNI in the Java world (?).
- I can't rule out that some dependencies still do something that is essentially unsupported during runtime, as the error might suggest, but finding those in the myriad of dependencies of a larger project is not easy.

I would greatly appreciate pointers to how I could tackle the issue, as I have a hard time interpreting and pinning the error, may it be resources, tools, or experiences with similar errors.

Thanks!

-------
`native-image` options (written in list form because we use an `sbt` plugin):

- `--enable-all-security-services`
- `-H:CLibraryPath=...` for our native bindings
- `--rerun-class-initialization-at-runtime=javax.net.ssl.SSLContext,java.sql.DriverManager, <...>`
- `-H:IncludeResources=<...>`
- `-H:ReflectionConfigurationFiles=<...>`
- `--verbose`

-------
```
[PosixParkEvent.condTimedWait(delayNanos: 100000000): Should not reach here.  mutex: 0x7fcc4a9000e0  cond: 0x7fcc4a900120  deadlineTimeSpec.tv_sec: 1542722165  deadlineTimespec.tv_nsec: 1000000000  status: 22 Invalid argument]
VMError.shouldNotReachHere: park(long): condition variable timed wait

JavaFrameAnchor dump:

  No anchors

DeoptStubPointer address: 0000000000000000

TopFrame info:

  Lookup TotalFrameSize in CodeInfoTable:
  SourceTotalFrameSize 96

VMThreads info:

  VMThread 00007fcc49700000  STATUS_IN_NATIVE  akka.dispatch.MonitorableThreadFactory$AkkaForkJoinWorkerThread@0x114e08f10
  VMThread 00007fcc4a800380  STATUS_IN_NATIVE  org.http4s.blaze.channel.nio1.NIO1SocketServerGroup$AcceptThread@0x115315bd0
  VMThread 00007fcc495066b0  STATUS_IN_NATIVE  org.http4s.blaze.channel.nio1.SelectorLoop@0x115315598
  VMThread 00007fcc4ab00010  STATUS_IN_NATIVE  org.http4s.blaze.channel.nio1.SelectorLoop@0x115314fa0
  VMThread 00007fcc4aa005c0  STATUS_IN_NATIVE  org.http4s.blaze.channel.nio1.SelectorLoop@0x115314898
  VMThread 00007fcc49700c30  STATUS_IN_NATIVE  org.http4s.blaze.channel.nio1.SelectorLoop@0x1153142a0
  VMThread 00007fcc4a8002a0  STATUS_IN_NATIVE  org.http4s.blaze.channel.nio1.SelectorLoop@0x115313ca8
  VMThread 00007fcc495063c0  STATUS_IN_NATIVE  org.http4s.blaze.channel.nio1.SelectorLoop@0x1153136b0
  VMThread 00007fcc4aa004e0  STATUS_IN_NATIVE  org.http4s.blaze.channel.nio1.SelectorLoop@0x1153130b8
  VMThread 00007fcc4a8001c0  STATUS_IN_NATIVE  org.http4s.blaze.channel.nio1.SelectorLoop@0x115312ac0
  VMThread 00007fcc49700b50  STATUS_IN_NATIVE  org.http4s.blaze.channel.nio1.SelectorLoop@0x1153124c8
  VMThread 00007fcc495065d0  STATUS_IN_NATIVE  java.lang.Thread@0x114317aa8
  VMThread 00007fcc4a900000  STATUS_IN_JAVA (safepoints disabled)  org.LatencyUtils.SimplePauseDetector$SimplePauseDetectorThread@0x114306988
  VMThread 00007fcc49600400  STATUS_IN_NATIVE  org.LatencyUtils.PauseDetector$PauseDetectorThread@0x114306790
  VMThread 00007fcc49506260  STATUS_IN_NATIVE  java.lang.Thread@0x11322caf0
  VMThread 00007fcc494001f0  STATUS_IN_NATIVE  java.lang.Thread@0x112e1df60

VM Thread State for current thread 00007fcc4a900000:

  0 (8 bytes): com.oracle.svm.jni.JNIThreadLocalEnvironment.jniFunctions = (bytes)
    00007fcc4a900000: 0000000000000000

  8 (32 bytes): com.oracle.svm.core.genscavenge.ThreadLocalAllocation.pinnedTLAB = (bytes)
    00007fcc4a900008: 0000000000000000 0000000000000000
    00007fcc4a900018: 0000000000000000 0000000000000000


  40 (32 bytes): com.oracle.svm.core.genscavenge.ThreadLocalAllocation.regularTLAB = (bytes)
    00007fcc4a900028: 0000000114500000 0000000114600000
    00007fcc4a900038: 0000000114501460 0000000000000000


  72 (8 bytes): com.oracle.svm.core.genscavenge.PinnedAllocatorImpl.openPinnedAllocator = (Object) null
  80 (8 bytes): com.oracle.svm.core.heap.NoAllocationVerifier.openVerifiers = (Object) null
  88 (8 bytes): com.oracle.svm.core.jdk.IdentityHashCodeSupport.hashCodeGeneratorTL = (Object) null
  96 (8 bytes): com.oracle.svm.core.snippets.SnippetRuntime.currentException = (Object) null
  104 (8 bytes): com.oracle.svm.core.thread.JavaThreads.currentThread = (Object) org.LatencyUtils.SimplePauseDetector$SimplePauseDetectorThread  0000000114306988
  112 (8 bytes): com.oracle.svm.core.thread.ThreadingSupportImpl.activeTimer = (Object) null
  120 (8 bytes): com.oracle.svm.jni.JNIThreadLocalHandles.handles = (Object) null
  128 (8 bytes): com.oracle.svm.jni.JNIThreadLocalPendingException.pendingException = (Object) null
  136 (8 bytes): com.oracle.svm.jni.JNIThreadLocalPinnedObjects.pinnedObjectsListHead = (Object) null
  144 (8 bytes): com.oracle.svm.jni.JNIThreadOwnedMonitors.ownedMonitors = (Object) null
  152 (8 bytes): com.oracle.svm.core.genscavenge.ThreadLocalAllocation.freeList = (Word) 0  0000000000000000
  160 (8 bytes): com.oracle.svm.core.stack.JavaFrameAnchors.lastAnchor = (Word) 0  0000000000000000
  168 (8 bytes): com.oracle.svm.core.thread.VMThreads.IsolateTL = (Word) 4572848128  0000000110902000
  176 (8 bytes): com.oracle.svm.core.thread.VMThreads.OSThreadIdTL = (Word) 4632625152  0000000114204000
  184 (8 bytes): com.oracle.svm.core.thread.VMThreads.nextTL = (Word) 140515381085184  00007fcc49600400
  192 (4 bytes): com.oracle.svm.core.thread.Safepoint.safepointRequested = (int) -125248  fffe16c0
  196 (4 bytes): com.oracle.svm.core.thread.Safepoint.safepointRequestedValueBeforeSafepoint = (int) 0  00000000
  200 (4 bytes): com.oracle.svm.core.thread.ThreadingSupportImpl.currentPauseDepth = (int) 0  00000000
  204 (4 bytes): com.oracle.svm.core.thread.VMOperationControl.isLockOwner = (int) 0  00000000
  208 (4 bytes): com.oracle.svm.core.thread.VMThreads$StatusSupport.safepointsDisabledTL = (int) 1  00000001
  212 (4 bytes): com.oracle.svm.core.thread.VMThreads$StatusSupport.statusTL = (int) 1  00000001

VMOperation dump:

  No VMOperation in progress


RuntimeCodeCache dump:

  == [Recent RuntimeCodeCache operations: ]

  == [RuntimeCodeCache: 0 methods]

Deoptimizer dump:

  == [Recent Deoptimizer Events:
  ]

Dump Counters:


Raw Stacktrace:

  0000000114203bd0: 0000000000000001 0000000114203c80
  0000000114203be0: 0000000112e1e9a0 0000000114203ba0
  0000000114203bf0: 0000000000000000 000000010aa5642f
  0000000114203c00: 00007fffe64a8000 0000000111d987d0
  0000000114203c10: 000000011284d2d0 0000000110902000
  0000000114203c20: 0000000111dc44e8 000000010aa7533f
  0000000114203c30: 0000000110902000 00007fcc4a900000
  0000000114203c40: 0000000111dc44e8 000000010aa752ae
  0000000114203c50: 000000011284d2d0 000000010aa3dd11
  0000000114203c60: 0000000111dc44e8 000000010aa574bf
  0000000114203c70: 0000000001ed8b98 0000000111dc44e8
  0000000114203c80: 000000161284d20a 000000010aa66240
  0000000114203c90: 0000000114501410 000000011284d2d0
  0000000114203ca0: 000000011284d2d0 0000000111dc4500
  0000000114203cb0: 00007fffdd621a6d 00007fffdd7ab022
  0000000114203cc0: 00007fffdd7a76f7 0000000111dc4410
  0000000114203cd0: 000000160000000f 0000000111dc43e0
  0000000114203ce0: 0000000114203d08 0000000005f5e100
  0000000114203cf0: 0000000114501410 0000000114203c90
  0000000114203d00: 0000000000000000 000000005bf41275
  0000000114203d10: 000000003b9aca00 000000010aa6de96
  0000000114203d20: 00000001145013b0 000000010aa2dfc2
  0000000114203d30: 0000000111dc4500 0000000c0000001b
  0000000114203d40: ffffffffffd1e37d 00000005122ff030
  0000000114203d50: 0000738974c0456a 000073896eca646a
  0000000114203d60: 0000000114306988 0000000114501410
  0000000114203d70: 0000000005f5e100 000000010b3b4bf7
  0000000114203d80: 0000000000000000 0000000000000010
  0000000114203d90: 305f646165726854 0000000111dc4500
  0000000114203da0: 0000000000000064 000000010b3b52df
  0000000114203db0: 0000000114501078 000000010aa65ace
  0000000114203dc0: 0000000000000064 00007fcc49506350
  0000000114203dd0: 0000000000000400 000000010b813050
  0000000114203de0: 0000000114501078 0000000c0aa3262c
  0000000114203df0: 0000000114501030 00007fcc4a900000
  0000000114203e00: 0000000114306988 0000000114306bb8
  0000000114203e10: 0000000005f61215 0000000014306988
  0000000114203e20: 0000000000000064 0000000005f5e100
  0000000114203e30: 000000011284d2e8 00000001131399c0
  0000000114203e40: 0000000005f61215 000073896eca5f2a
  0000000114203e50: 0000000114306988 000000010aa6b512
  0000000114203e60: 00007fcc49500001 0000000114204000
  0000000114203e70: 000000010aa02d90 0000000111dc0b58
  0000000114203e80: 0000000114306988 0000000112e1eac8
  0000000114203e90: 0000000000000007 000000010aa02e21
  0000000114203ea0: 0000000000000000 0000000000000000
  0000000114203eb0: 0000000000000007 0000000000000000
  0000000114203ec0: 00007fcc495063c0 0000000114203f10
  0000000114203ed0: 00007fcc495063c0 000000001d0008ff
  0000000114203ee0: 0000000000001103 000000010aa02d90
  0000000114203ef0: 0000000114204000 00007fffdd7a993b
  0000000114203f00: 0000000000001100 0000000114204000
  0000000114203f10: 0000000114203f50 00007fffdd7a9887
  0000000114203f20: 0000000000000000 0000000000000000
  0000000114203f30: 0000000000000000 0000000000000000
  0000000114203f40: 0000000000000000 0000000000000000
  0000000114203f50: 0000000114203f78 00007fffdd7a908d
  0000000114203f60: 0000000000000000 0000000000000000
  0000000114203f70: 0000000000000000 0000000000000000
  0000000114203f80: 0000000000000000 0000000000000000
  0000000114203f90: 0000000000000000 0000000000000000
  0000000114203fa0: 0000000000000000 0000000000000000
  0000000114203fb0: 0000000000000000 0000000000000000
  0000000114203fc0: 0000000000000000 0000000000000000

Stacktrace Stage0:

  RSP 0000000114203bd0 RIP 000000010aa3d07b FrameSize 96
  RSP 0000000114203c30 RIP 000000010aa7533f FrameSize 32
  RSP 0000000114203c50 RIP 000000010aa752ae FrameSize 32
  RSP 0000000114203c70 RIP 000000010aa574bf FrameSize 32
  RSP 0000000114203c90 RIP 000000010aa66240 FrameSize 144
  RSP 0000000114203d20 RIP 000000010aa6de96 FrameSize 96
  RSP 0000000114203d80 RIP 000000010b3b4bf7 FrameSize 48
  RSP 0000000114203db0 RIP 000000010b3b52df FrameSize 48
  RSP 0000000114203de0 RIP 000000010b813050 FrameSize 128
  RSP 0000000114203e60 RIP 000000010aa6b512 FrameSize 64
  RSP 0000000114203ea0 RIP 000000010aa02e21 FrameSize 1

Stacktrace Stage1:

  RSP 0000000114203bd0 RIP 000000010aa3d07b  com.oracle.svm.core.code.ImageCodeInfo@0x112380578 name = image code
  RSP 0000000114203c30 RIP 000000010aa7533f  com.oracle.svm.core.code.ImageCodeInfo@0x112380578 name = image code
  RSP 0000000114203c50 RIP 000000010aa752ae  com.oracle.svm.core.code.ImageCodeInfo@0x112380578 name = image code
  RSP 0000000114203c70 RIP 000000010aa574bf  com.oracle.svm.core.code.ImageCodeInfo@0x112380578 name = image code
  RSP 0000000114203c90 RIP 000000010aa66240  com.oracle.svm.core.code.ImageCodeInfo@0x112380578 name = image code
  RSP 0000000114203d20 RIP 000000010aa6de96  com.oracle.svm.core.code.ImageCodeInfo@0x112380578 name = image code
  RSP 0000000114203d80 RIP 000000010b3b4bf7  com.oracle.svm.core.code.ImageCodeInfo@0x112380578 name = image code
  RSP 0000000114203db0 RIP 000000010b3b52df  com.oracle.svm.core.code.ImageCodeInfo@0x112380578 name = image code
  RSP 0000000114203de0 RIP 000000010b813050  com.oracle.svm.core.code.ImageCodeInfo@0x112380578 name = image code
  RSP 0000000114203e60 RIP 000000010aa6b512  com.oracle.svm.core.code.ImageCodeInfo@0x112380578 name = image code
  RSP 0000000114203ea0 RIP 000000010aa02e21  com.oracle.svm.core.code.ImageCodeInfo@0x112380578 name = image code

Full Stacktrace:

  RSP 0000000114203bd0 RIP 000000010aa3d07b  [image code] com.oracle.svm.core.jdk.VMErrorSubstitutions.shutdown(VMErrorSubstitutions.java:146)
  RSP 0000000114203c30 RIP 000000010aa7533f  [image code] com.oracle.svm.core.jdk.Target_com_oracle_svm_core_util_VMError.shouldNotReachHere(VMErrorSubstitutions.java:63)
  RSP 0000000114203c50 RIP 000000010aa752ae  [image code] com.oracle.svm.core.jdk.Target_com_oracle_svm_core_util_VMError.guarantee(VMErrorSubstitutions.java:97)
  RSP 0000000114203c70 RIP 000000010aa574bf  [image code] com.oracle.svm.core.posix.PosixUtils.checkStatusIs0(PosixUtils.java:480)
  RSP 0000000114203c90 RIP 000000010aa66240  [image code] com.oracle.svm.core.posix.thread.PosixParkEvent.condTimedWait(PosixJavaThreads.java:331)
  RSP 0000000114203d20 RIP 000000010aa6de96  [image code] com.oracle.svm.core.thread.SleepSupport.sleep(JavaThreads.java:1108)
  RSP 0000000114203d80 RIP 000000010b3b4bf7  [image code] com.oracle.svm.core.thread.Target_java_lang_Thread.sleep(JavaThreads.java:910)
  RSP 0000000114203db0 RIP 000000010b3b52df  [image code] java.lang.Thread.sleep(Thread.java:340)
  RSP 0000000114203de0 RIP 000000010b813050  [image code] java.util.concurrent.TimeUnit.sleep(TimeUnit.java:386)
  RSP 0000000114203de0 RIP 000000010b813050  [image code] org.LatencyUtils.TimeServices.sleepNanos(TimeServices.java:62)
  RSP 0000000114203de0 RIP 000000010b813050  [image code] org.LatencyUtils.SimplePauseDetector$SimplePauseDetectorThread.run(SimplePauseDetector.java:116)
  RSP 0000000114203e60 RIP 000000010aa6b512  [image code] com.oracle.svm.core.thread.JavaThreads.threadStartRoutine(JavaThreads.java:479)
  RSP 0000000114203ea0 RIP 000000010aa02e21  [image code] com.oracle.svm.core.posix.thread.PosixJavaThreads.pthreadStartRoutine(PosixJavaThreads.java:199)
  RSP 0000000114203ea0 RIP 000000010aa02e21  [image code] com.oracle.svm.core.code.CEntryPointCallStubs.com_002eoracle_002esvm_002ecore_002eposix_002ethread_002ePosixJavaThreads_002epthreadStartRoutine_0028com_002eoracle_002esvm_002ecore_002ethread_002eJavaThreads_0024ThreadStartData_0029(generated:0)

[Native image heap boundaries:
  ReadOnly Primitives: 0x110902008 .. 0x111d97720
  ReadOnly References: 0x111d98088 .. 0x112849ad8
  Writable Primitives: 0x11284a000 .. 0x112e18db0
  Writable References: 0x112e18dc8 .. 0x113191b00]


[Heap:
  [Young generation:
    [youngSpace:
      aligned: 22977504/22 unaligned: 0/0
      aligned chunks:
        0x113b00000 (0x113b01030-0x113b11470)
        0x113a00000 (0x113a01030-0x113a11998)
        0x113900000 (0x113901030-0x1139238f8)
        0x113600000 (0x113601030-0x113621de0)
        0x113400000 (0x113401030-0x1134014e0)
        0x113200000 (0x113201030-0x113293df0)
        0x113c00000 (0x113c01030-0x113c08bf8)
        0x113e00000 (0x113e01030-0x113e01080)
        0x113d00000 (0x113d01030-0x113d0bcb8)
        0x113f00000 (0x113f01030-0x113f010b0)
        0x114800000 (0x114801030-0x114838508)
        0x114c00000 (0x114c01030-0x114c060c8)
        0x114d00000 (0x114d01030-0x114d1a9d0)
        0x116800000 (0x116801030-0x1168026d0)
        0x116a00000 (0x116a01030-0x116a114e8)
        0x115300000 (0x115301030-0x115317f30)
        0x115200000 (0x115201030-0x11522fd90)
        0x116600000 (0x116601030-0x116631588)
        0x114300000 (0x114301030-0x114320990)
        0x116b00000 (0x116b01030-0x116b17f60)
        0x114f00000 (0x114f01030-0x114fffff8)
        0x114e00000 (0x114e01030-0x114e0fae8)]]
  [Old generation:
    [fromSpace:
      aligned: 0/0 unaligned: 0/0]
    [toSpace:
      aligned: 0/0 unaligned: 0/0]
    [pinnedFromSpace:
      aligned: 0/0 unaligned: 0/0]
    [pinnedToSpace:
      aligned: 0/0 unaligned: 0/0]]
  [Unused:
    aligned: 0/0]]

```

**Comment by Peter-B-Kessler** [comment] 2018-11-26 21:39
Thanks for the report.  You are 1 in a million, or actually, 1 in billion. :-)

The problem is nicely (?) displayed in the error message 
```
[PosixParkEvent.condTimedWait(delayNanos: ....): Should not reach here.  ....  deadlineTimespec.tv_nsec: 1000000000  status: 22 Invalid argument]
```
I am trying to wait with a `timespec.tv_nsec` of 1e9, which is one more than the allowed number of nanoseconds in a `tv_nsec`.  So I get an `Invalid argument` result.  I will go fix it.

**Comment by dpetrick** [comment] 2018-11-27 09:51
That is great to hear @Peter-B-Kessler, thanks a lot!

**Comment by Peter-B-Kessler** [comment] 2018-11-29 00:10
I have committed https://github.com/oracle/graal/commit/23f985ae795f4f3784f9297dba5525cacd9e4b31, which should address this problem.  I could not think of how to write a test case for it.  If you hit this problem again, please reopen the issue.

**Closed by Peter-B-Kessler** 2018-11-29 00:10 UTC
Labels: substrate
