### ISSUE TITLE
NPM run build call in GraalVM hangs indefinitely

### ISSUE THREAD

**Issue by UglyHobbitFeet** [oracle/graal#2866] opened 2020-09-23 17:47 UTC
I have a Vue project in Node that I am trying to build via 'npm run build'.  This works fine using standard NPM.  Using the npm shipped with GraalVM causes it to hang indefinitely. FWIW my Vue project is built in Node and compiled using ES4x for Vert.x. 
I am on a CentOS 7 OS.  I have tried the same with a prior GraalVM build (19.2.1) and get the same error. I am using v4.5.6 of the vue-cli-service package.

package.json snippet:
```
"scripts": {
    "serve": "vue-cli-service serve",
    "build": "vue-cli-service build",
    "lint": "vue-cli-service lint",
    "postinstall": "es4x install",
    "start": "es4x",
  },

```
Ex:
```
> which npm
/bin/npm
> npm -v
6.14.8
> npm run build
> vue-cli-service build
⠴  Building for production...
...Lots of output followed by...
 DONE  Build complete. The dist directory is ready to be deployed.
```

```
> /path/to/graalvm-ce-java8-20.2.0/bin/npm run build
> vue-cli-service build
⠴  Building for production...
<I never get any further output from this. It hangs on the last line shown above>
```

**Comment by oubidar-Abderrahim** [comment] 2020-09-24 08:28
Hi @UglyHobbitFeet could you please provide a small reproducer for this issue?

**Comment by UglyHobbitFeet** [comment] 2020-09-25 16:35
Unfortunately not. The project I have is too big.  I tried creating a
simple hello-world and then using the package.json file from my larger
project, but it did not replicate the issue. So it must be something in the
code and how it's interacting with the Graal version of npm.  Is there any
way that debug flags can be set so I can see when/why it's freezing?

Also FWIW the (graal npm / vue-cli-build command) seems to pretty much pin
my CPU at 100% and consume between 1-2GB of memory. Looking at the process
shows 'Process status - sleeping. Process is waiting for something to
happen'. It's been running for 30 minutes now. Using the non-graal npm
usually has it complete in 30 seconds.

Lastly, I have also opened a ticket with vue-build-cli.  Perhaps something
will come out of a collaboration from both tickets?
https://github.com/vuejs/vue-cli/issues/5898

**Comment by oubidar-Abderrahim** [comment] 2020-09-29 15:49
As a general knowledge about GraalVM. It is expected when using node and npm from GraalVM to take more time than the original node for the simple reason that every language used in GraalVM, including JavaScript, runs over the JVM, so it is compiled first. So, it takes more time to compile.

The Graal JS team is working continuously to reduce the memory and time consumption, it won't be similar to NodeJS but we're trying to get as close as we can. 

That being said and back to the current issue, It is hard to determine the root cause of this issue without a reproducer, especially since the `vue-cli-build` doesn't provide any debug info

It might be something that relies on V8 inner mechanics (for example `node-fiber` rely heavily on some inner V8 engine mechanics that can not be replicated using GraalJS). Again I am just speculating and without an actual reproducer, I can't really investigate further.

**Comment by oubidar-Abderrahim** [comment] 2020-09-29 15:51
@wirthi Do you have any idea that can be helpful in this case?

**Comment by UglyHobbitFeet** [comment] 2020-09-29 16:48
Looking at the package.json for @vue/cli-service (
https://github.com/vuejs/vue-cli/blob/dev/packages/%40vue/cli-service/package.json)
I see at line 113...
devDependencies: {
"fibers": ">=3.1.1 <5.0.0"
}

Assuming that's the case, would this ever be able to be run on Graal?

**Comment by oubidar-Abderrahim** [comment] 2020-09-29 18:30
If `fibers` is the underlying issue then unfortunately it won't be able to run on GraalVM. 

As I said `node-fibers` rely on low-level code of the V8 engine that runs NodeJs. Graal's Node runs on GraalJS Engine, so `fibers` won't be able to call those low-level methods. it is like trying to run a Windows program on a Linux machine. Even `fibers`'s developers stated on their GitHub page that the package is obsolete and should be avoided as much as possible.

**Comment by UglyHobbitFeet** [comment] 2020-09-29 18:36
Thanks, I'll pass this on in the vue-cli issue (
https://github.com/vuejs/vue-cli/issues/5898)

**Comment by wirthi** [comment] 2020-09-30 17:09
Hi,

I don't have any immediate insight here. As mentioned above, `fibers` might not be the immediate problem, as it only is an dev-dependency (whether it is really optional or still used by some feature, I cannot yet tell).

For the way forward we have two options:

1. check our compatibility on `@vue/cli-service`
2. have an example application similar to the usecase reported here (but much smaller so it's easy to debug).

I have looked into `cli-service` already and was able to start its testsuite, but that fails with several different errors, most of which I assume are setup issues on my side. I will have to look deeper into this.

Best,
Christian

**Comment by UglyHobbitFeet** [comment] 2020-10-02 16:58
Thanks for looking into this.

FWIW i've tested with the following versions and they all hang:
v19.2.1-ce-java8, 20.2.0-ce-java8, 20.2.0-ce-java11

**Comment by oubidar-Abderrahim** [comment] 2024-01-16 10:27
Closing this issue, if the issue is still present in the latest builds, please open a new issue and share a reproducer following the template provided

**Closed by oubidar-Abderrahim** 2024-01-16 10:27 UTC
Labels: bug, javascript
