### ISSUE TITLE
Graal ArrayCopy compiler errors

### ISSUE THREAD

**Issue by ppiotrow** [oracle/graal#876] opened 2018-12-19 09:53 UTC
While running my application in docker `oracle/graalvm-ce:1.0.0-rc10` I received such warning. The application works fine. Hope this report will help you.
```
Thread[JVMCI CompilerThread1,9,system]: Compilation of java.util.ArrayList.toArray(Object[]) failed:
org.graalvm.compiler.debug.GraalError: unexpected invoke HotSpotMethod<System.$$YJP$$arraycopy(Object, int, Object, int, int)> in snippet
	at org.graalvm.compiler.hotspot.replacements.arraycopy.ArrayCopySnippets$Templates.instantiate(ArrayCopySnippets.java:539)
	at org.graalvm.compiler.hotspot.replacements.arraycopy.ArrayCopySnippets$Templates.lower(ArrayCopySnippets.java:494)
	at org.graalvm.compiler.hotspot.meta.DefaultHotSpotLoweringProvider.lower(DefaultHotSpotLoweringProvider.java:324)
	at org.graalvm.compiler.hotspot.amd64.AMD64HotSpotLoweringProvider.lower(AMD64HotSpotLoweringProvider.java:84)
	at org.graalvm.compiler.replacements.nodes.BasicArrayCopyNode.lower(BasicArrayCopyNode.java:146)
	at org.graalvm.compiler.phases.common.LoweringPhase$Round.process(LoweringPhase.java:465)
	at org.graalvm.compiler.phases.common.LoweringPhase$Round.access$200(LoweringPhase.java:341)
	at org.graalvm.compiler.phases.common.LoweringPhase$Round$ProcessFrame.preprocess(LoweringPhase.java:405)
	at org.graalvm.compiler.phases.common.LoweringPhase.processBlock(LoweringPhase.java:564)
	at org.graalvm.compiler.phases.common.LoweringPhase$Round.run(LoweringPhase.java:390)
	at org.graalvm.compiler.phases.Phase.run(Phase.java:49)
	at org.graalvm.compiler.phases.BasePhase.apply(BasePhase.java:197)
	at org.graalvm.compiler.phases.BasePhase.apply(BasePhase.java:139)
	at org.graalvm.compiler.phases.PhaseSuite.run(PhaseSuite.java:212)
	at org.graalvm.compiler.phases.common.IncrementalCanonicalizerPhase.run(IncrementalCanonicalizerPhase.java:56)
	at org.graalvm.compiler.phases.common.IncrementalCanonicalizerPhase.run(IncrementalCanonicalizerPhase.java:38)
	at org.graalvm.compiler.phases.BasePhase.apply(BasePhase.java:197)
	at org.graalvm.compiler.phases.BasePhase.apply(BasePhase.java:139)
	at org.graalvm.compiler.phases.common.LoweringPhase.lower(LoweringPhase.java:261)
	at org.graalvm.compiler.phases.common.LoweringPhase.run(LoweringPhase.java:254)
	at org.graalvm.compiler.phases.common.LoweringPhase.run(LoweringPhase.java:93)
	at org.graalvm.compiler.phases.BasePhase.apply(BasePhase.java:197)
	at org.graalvm.compiler.phases.BasePhase.apply(BasePhase.java:139)
	at org.graalvm.compiler.phases.PhaseSuite.run(PhaseSuite.java:212)
	at org.graalvm.compiler.phases.BasePhase.apply(BasePhase.java:197)
	at org.graalvm.compiler.phases.BasePhase.apply(BasePhase.java:139)
	at org.graalvm.compiler.core.GraalCompiler.emitFrontEnd(GraalCompiler.java:266)
	at org.graalvm.compiler.core.GraalCompiler.compile(GraalCompiler.java:180)
	at org.graalvm.compiler.core.GraalCompiler.compileGraph(GraalCompiler.java:165)
	at org.graalvm.compiler.hotspot.HotSpotGraalCompiler.compileHelper(HotSpotGraalCompiler.java:185)
	at org.graalvm.compiler.hotspot.HotSpotGraalCompiler.compile(HotSpotGraalCompiler.java:198)
	at org.graalvm.compiler.hotspot.CompilationTask$HotSpotCompilationWrapper.performCompilation(CompilationTask.java:182)
	at org.graalvm.compiler.hotspot.CompilationTask$HotSpotCompilationWrapper.performCompilation(CompilationTask.java:99)
	at org.graalvm.compiler.core.CompilationWrapper.run(CompilationWrapper.java:172)
	at org.graalvm.compiler.hotspot.CompilationTask.runCompilation(CompilationTask.java:331)
	at org.graalvm.compiler.hotspot.HotSpotGraalCompiler.compileMethod(HotSpotGraalCompiler.java:138)
	at org.graalvm.compiler.hotspot.HotSpotGraalCompiler.compileMethod(HotSpotGraalCompiler.java:105)
	at jdk.vm.ci.hotspot.HotSpotJVMCIRuntime.compileMethod(HotSpotJVMCIRuntime.java:627)
To disable compilation failure notifications, set CompilationFailureAction to Silent (e.g., -Dgraal.CompilationFailureAction=Silent).
To print a message for a compilation failure without retrying the compilation, set CompilationFailureAction to Print (e.g., -Dgraal.CompilationFailureAction=Print).
Retrying compilation of java.util.ArrayList.toArray(Object[])

Warning: adjusting CompilationFailureAction from Diagnose to Print after MaxCompilationProblemsPerAction (2) failed compilations
Thread[JVMCI CompilerThread1,9,system]: Compilation of java.util.ArrayList.addAll(Collection) failed: org.graalvm.compiler.debug.GraalError: unexpected invoke HotSpotMethod<System.$$YJP$$arraycopy(Object, int, Object, int, int)> in snippet
	at org.graalvm.compiler.hotspot.replacements.arraycopy.ArrayCopySnippets$Templates.instantiate(ArrayCopySnippets.java:539)
	at org.graalvm.compiler.hotspot.replacements.arraycopy.ArrayCopySnippets$Templates.lower(ArrayCopySnippets.java:494)
	at org.graalvm.compiler.hotspot.meta.DefaultHotSpotLoweringProvider.lower(DefaultHotSpotLoweringProvider.java:324)
	at org.graalvm.compiler.hotspot.amd64.AMD64HotSpotLoweringProvider.lower(AMD64HotSpotLoweringProvider.java:84)
	at org.graalvm.compiler.replacements.nodes.BasicArrayCopyNode.lower(BasicArrayCopyNode.java:146)
	at org.graalvm.compiler.phases.common.LoweringPhase$Round.process(LoweringPhase.java:465)
	at org.graalvm.compiler.phases.common.LoweringPhase$Round.access$200(LoweringPhase.java:341)
	at org.graalvm.compiler.phases.common.LoweringPhase$Round$ProcessFrame.preprocess(LoweringPhase.java:405)
	at org.graalvm.compiler.phases.common.LoweringPhase.processBlock(LoweringPhase.java:564)
	at org.graalvm.compiler.phases.common.LoweringPhase$Round.run(LoweringPhase.java:390)
	at org.graalvm.compiler.phases.Phase.run(Phase.java:49)
	at org.graalvm.compiler.phases.BasePhase.apply(BasePhase.java:197)
	at org.graalvm.compiler.phases.BasePhase.apply(BasePhase.java:139)
	at org.graalvm.compiler.phases.PhaseSuite.run(PhaseSuite.java:212)
	at org.graalvm.compiler.phases.common.IncrementalCanonicalizerPhase.run(IncrementalCanonicalizerPhase.java:56)
	at org.graalvm.compiler.phases.common.IncrementalCanonicalizerPhase.run(IncrementalCanonicalizerPhase.java:38)
	at org.graalvm.compiler.phases.BasePhase.apply(BasePhase.java:197)
	at org.graalvm.compiler.phases.BasePhase.apply(BasePhase.java:139)
	at org.graalvm.compiler.phases.common.LoweringPhase.lower(LoweringPhase.java:261)
	at org.graalvm.compiler.phases.common.LoweringPhase.run(LoweringPhase.java:254)
	at org.graalvm.compiler.phases.common.LoweringPhase.run(LoweringPhase.java:93)
	at org.graalvm.compiler.phases.BasePhase.apply(BasePhase.java:197)
	at org.graalvm.compiler.phases.BasePhase.apply(BasePhase.java:139)
	at org.graalvm.compiler.phases.PhaseSuite.run(PhaseSuite.java:212)
	at org.graalvm.compiler.phases.BasePhase.apply(BasePhase.java:197)
	at org.graalvm.compiler.phases.BasePhase.apply(BasePhase.java:139)
	at org.graalvm.compiler.core.GraalCompiler.emitFrontEnd(GraalCompiler.java:266)
	at org.graalvm.compiler.core.GraalCompiler.compile(GraalCompiler.java:180)
	at org.graalvm.compiler.core.GraalCompiler.compileGraph(GraalCompiler.java:165)
	at org.graalvm.compiler.hotspot.HotSpotGraalCompiler.compileHelper(HotSpotGraalCompiler.java:185)
	at org.graalvm.compiler.hotspot.HotSpotGraalCompiler.compile(HotSpotGraalCompiler.java:198)
	at org.graalvm.compiler.hotspot.CompilationTask$HotSpotCompilationWrapper.performCompilation(CompilationTask.java:182)
	at org.graalvm.compiler.hotspot.CompilationTask$HotSpotCompilationWrapper.performCompilation(CompilationTask.java:99)
	at org.graalvm.compiler.core.CompilationWrapper.run(CompilationWrapper.java:172)
	at org.graalvm.compiler.hotspot.CompilationTask.runCompilation(CompilationTask.java:331)
	at org.graalvm.compiler.hotspot.HotSpotGraalCompiler.compileMethod(HotSpotGraalCompiler.java:138)
	at org.graalvm.compiler.hotspot.HotSpotGraalCompiler.compileMethod(HotSpotGraalCompiler.java:105)
	at jdk.vm.ci.hotspot.HotSpotJVMCIRuntime.compileMethod(HotSpotJVMCIRuntime.java:627)
```

**Comment by ppiotrow** [comment] 2018-12-19 10:06
After looking at the stack trace more carefully I suppose it might have something to do with YourkitProfiler agent shipped with the application - see `$YJP` in the method call. Could it be it?

**Comment by ppiotrow** [comment] 2018-12-20 08:19
I think we can close the issue. It was thrown in the environment where profiler runs by default. Agent is provided on disk as `libyjpagent.so` and enabled with usual `-J-agentpath(...)`. If I were to solve that now I'd probably start by upgrading agent version which might be a little bit old or contact the company behind profiler with questions about compatibility.

**Comment by christhalinger** [comment] 2019-01-08 20:03
We are seeing the same issue at Twitter. I'm not exactly sure yet how YourKit works but we should get to the bottom of this. Graal needs to work with YourKit. Can we reopen this ticket?

**Comment by christhalinger** [comment] 2019-01-09 00:45
Is it possible the problem is that we don't use a `BytecodeProvider` when registering `java.lang.System` plugins while for all the other ones we do?

```
$ grep "new Registration" src/org.graalvm.compiler.hotspot/src/org/graalvm/compiler/hotspot/meta/HotSpotGraphBuilderPlugins.java 
        Registration r = new Registration(plugins, Object.class, bytecodeProvider);
        Registration r = new Registration(plugins.getInvocationPlugins(), Class.class, bytecodeProvider);
        Registration r = new Registration(plugins, reflectionClass, bytecodeProvider);
            r = new Registration(plugins, Unsafe.class, replacementBytecodeProvider);
            r = new Registration(plugins, "jdk.internal.misc.Unsafe", replacementBytecodeProvider);
        Registration r = new Registration(plugins, constantPoolClass, bytecodeProvider);
        Registration r = new Registration(plugins, System.class);
        Registration r = new Registration(plugins, Array.class, bytecodeProvider);
            final Registration utf16r = new Registration(plugins, "java.lang.StringUTF16", bytecodeProvider);
        Registration r = new Registration(plugins, Thread.class, bytecodeProvider);
            Registration r = new Registration(plugins, "com.sun.crypto.provider.CipherBlockChaining", bytecodeProvider);
            r = new Registration(plugins, "com.sun.crypto.provider.AESCrypt", bytecodeProvider);
        Registration r = new Registration(plugins, BigInteger.class, bytecodeProvider);
            Registration r = new Registration(plugins, "sun.security.provider.SHA", bytecodeProvider);
            Registration r = new Registration(plugins, "sun.security.provider.SHA2", bytecodeProvider);
            Registration r = new Registration(plugins, "sun.security.provider.SHA5", bytecodeProvider);
            Registration r = new Registration(plugins, "com.sun.crypto.provider.GHASH");
            Registration r = new Registration(plugins, CRC32.class, bytecodeProvider);
            Registration r = new Registration(plugins, "java.util.zip.CRC32C", bytecodeProvider);
```

**Comment by dougxc** [comment] 2019-01-09 17:08
I think you may be onto something @christhalinger. We don't need to use a `BytecodeProvider` when registering the plugins for `System` plugins since none of the plugins are based on method substitutions. However, `ArrayCopyNode` used by the plugin for `arraycopy` is lowered by a snippet. All snippets should be parsed with a `ClassfileBytecodeProvider` but maybe this particular one isn't. /cc @tkrodriguez

**Comment by tkrodriguez** [comment] 2019-01-09 18:10
I suspect the problem is JVMTI native method prefix support.  https://docs.oracle.com/javase/8/docs/platform/jvmti/jvmti.html#SetNativeMethodPrefix  To enable instrumentation of native methods it allows renaming of the original native method to something new and provide a regular Java implementation of the original entry point.  I think this means that snippets call their original native implementation can still see the effects of instrumentation even if they properly use a ClassfileBytecodeProvider.

I'm not quite sure how Graal should be handling a native prefix in general.  We're certainly swallowing any instrumentation which was wrapped around the original arraycopy call or any other instrumented native method that has an intrisic.  I assume C1/C2 ends up doing the same thing.

As far as handling this in the snippet I suspect we need to stop inlining if we encounter a call to the original method which could be done with a plugin.

**Comment by christhalinger** [comment] 2019-01-09 20:41
Ahh, I didn't know about `SetNativeMethodPrefix` but seems to be used here.

**Comment by dougxc** [comment] 2019-01-12 15:36
Any chance you could have a look at it Chris? If not, please provide clear instructions on how to reproduce with YourKit and an example and we will look at it.

**Comment by tkrodriguez** [comment] 2019-01-14 18:15
I think there are only a few solutions.  We somehow figure out that native prefix is being used and associate our intrinsics with the renamed native entry point, which seems ugly and I think required help from HotSpot.  Or we explicitly make the call to the original method not inlined into snippets, even if it has bytecodes.  It's likely that this won't affect what we parse for most of our snippets.  It's certainly what we'd expect for arraycopy but I don't know about any other cases.  I think that arraycopy is the only actual snippet that has a self call.  All the others are method substitutions which should be ok right?

**Comment by dougxc** [comment] 2019-01-14 18:57
I don't like the solution requiring detecting use of a native prefix as there can be many and getting at them doesn't look so easy. For method substitutions we do indeed [disable](https://github.com/oracle/graal/blob/c60a822e94cdd19c718681e4f8084013d6ab7207/compiler/src/org.graalvm.compiler.java/src/org/graalvm/compiler/java/BytecodeParser.java#L1768) inlining for a self call. So dealing with the special case of arraycopy should be sufficient.

**Comment by tkrodriguez** [comment] 2019-01-14 21:11
Actually isn't the problem here https://github.com/oracle/graal/blob/master/compiler/src/org.graalvm.compiler.java/src/org/graalvm/compiler/java/BytecodeParser.java#L2313.  The partial intrinsic path is unconditionally inlining the original method.  Maybe we want to disable partial intrinsic exit for snippets?

**Comment by tkrodriguez** [comment] 2019-01-15 00:07
There's already some snippet specific logic to deal with argument mismatch in partial intrinsics.   https://github.com/oracle/graal/blob/master/compiler/src/org.graalvm.compiler.replacements/src/org/graalvm/compiler/replacements/ReplacementsImpl.java#L520  Maybe that should just set a flag in IntrinsicContext to disable the inlining of the call to the original?

**Comment by tkrodriguez** [comment] 2019-01-15 00:52
There's already some snippet specific logic to deal with argument mismatch in partial intrinsics.   https://github.com/oracle/graal/blob/master/compiler/src/org.graalvm.compiler.replacements/src/org/graalvm/compiler/replacements/ReplacementsImpl.java#L520  Maybe that should just set a flag in IntrinsicContext to disable the inlining of the call to the original?  I think that's probably the right fix.

**Comment by dougxc** [comment] 2019-01-15 15:59
Yep, that sounds right.

**Comment by dougxc** [comment] 2019-01-15 16:02
Want to give it a go @christhalinger ?

**Comment by tkrodriguez** [comment] 2019-01-15 20:37
I think it would be possible to write a test case using java.lang.Instrument since it provides support for setting the native prefix.

**Comment by christhalinger** [comment] 2019-01-18 21:14
Sorry, was busy running a conference😀 What's the current status? Do you want us to try something or write a test case?

**Comment by dougxc** [comment] 2019-01-18 22:08
It would be great if you guys could have a shot at disabling inlining of a call in a snippet to the original method being handled by the snippet. Either that or provide an easy way to reproduce/test a fix.

**Comment by mur47x111** [comment] 2019-03-15 10:27
Should be fixed by https://github.com/oracle/graal/commit/b301cbfa0d40ed4541a76cdff8be2c92133b6cbb

**Closed** 2019-04-01 10:16 UTC
Labels: bug, compiler

**Comment by dougxc** [comment] 2019-04-01 11:17
@christhalinger it would be great if you can verify this fixes the YourKit usage case.
