### ISSUE TITLE
DateTimeFormatter with Locale.ROOT is not working

### ISSUE THREAD

**Issue by psuzn** [oracle/graal#6733] opened 2023-06-05 06:30 UTC
**Describe the issue**
A native image containing code to parse the `LocalDateTime` with `Locale.ROOT` throws `java.time.format.DateTimeParseException` 

Sample code

```kotlin
import java.time.LocalDateTime
import java.time.format.DateTimeFormatter

fun main() {
    val dateTime = LocalDateTime.parse(
        "4714-11-24 00:00:00 BC",
        DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm:ss G", java.util.Locale.ROOT)
    )

    print(dateTime.toString())
}
```

**Steps to reproduce the issue**
Please include both build steps as well as run steps
1. `git clone https://github.com/gran-software-solutions/graalvm-datetime-issue.git`
2. `./gradlew nativeRun`

**Describe GraalVM and your environment:**
 - GraalVM version  GraalVM CE 22.3.2 (build 17.0.7+7-jvmci-22.3-b18)
 - JDK major version:  openjdk 17.0.7 2023-04-18
 - OS: macOS Ventura(13.4)
 - Architecture: arm64

**More details**
Here's the stack trace.
```
> Task :nativeRun FAILED
Exception in thread "main" java.time.format.DateTimeParseException: Text '4714-11-24 00:00:00 BC' could not be parsed at index 20
        at java.base@17.0.6/java.time.format.DateTimeFormatter.parseResolved0(DateTimeFormatter.java:2052)
        at java.base@17.0.6/java.time.format.DateTimeFormatter.parse(DateTimeFormatter.java:1954)
        at java.base@17.0.6/java.time.LocalDateTime.parse(LocalDateTime.java:494)
        at MainKt.main(Main.kt:5)
        at MainKt.main(Main.kt)

```

**Comment by pejovica** [comment] 2023-06-09 12:54
This is a duplicate of #5510, which has been fixed recently.

**Closed by pejovica** 2023-06-09 12:54 UTC
Labels: bug, native-image
