### ISSUE TITLE
The regression of JNI modularity since 19.3

### ISSUE THREAD

**Issue by ziyilin** [oracle/graal#1976] opened 2019-12-11 16:22 UTC
**The issue**:
We found the way of compiling an application using JNI library which is built by SVM as "shared" has changed since 19.3.

**Background**:

We have a big but stable Java library, and a lightweight but unstable Java application. The library does not change, and consumes a lot of resources to get compiled. The application is changed quite often but very small. At the very beginning, we had to build the application and library together into one executable. We waited a long time each time the application changed to get everything compiled. 

And then we find a way to build them seperately as two modules:  Firstly build the library into a shared so. Then change the dependencies from the application to the library into JNI calls. Finally compile the application into an executable file.

But since 19.3, we find the third step hes been changed. It requires to compile application and library together, otherwise, any JNI call causes a segment fault. 

**Reproducing sample**:

I made a very simple example to show the issue:
[JNIModularitySample.zip](https://github.com/oracle/graal/files/3951162/JNIModularitySample.zip)
demo.Main and demo.Native class simulate the application, and demo.lib.* simulate the library. Please read compileAndRun.sh and change the variable to run it to see the difference.

If 19.3 does not support JNI modularity any more, what is the new way to achieve our requirement?

**Comment by olpaw** [comment] 2019-12-18 11:01
Hi @ziyilin I cannot reproduce a segfault when I use `sh compileAndRun.sh`. When I use `graalvm-ce-java8-19.3.0` I get
```
> sh compileAndRun.sh 
Using GraalVM 19.3
Compile libnativeimple.so
Build on Server(pid: 15168, port: 35983)*
[libnativeimpl:15168]    classlist:   1,822.07 ms
...
[libnativeimpl:15168]      [total]:  17,291.07 ms
Test call as JNI
3
-1
Compile main as native image
Build on Server(pid: 15168, port: 35983)
[demo.main:15168]    classlist:     195.10 ms
...
[demo.main:15168]      [total]:  11,422.31 ms
Test native to native call by JNI
3
-1
```
With `graalvm-ce-java11-19.3.0` I do run in a problem but not a segfault:
```
> sh compileAndRun.sh 
Using GraalVM 19.3
Compile libnativeimple.so
Build on Server(pid: 15600, port: 35991)*
[libnativeimpl:15600]    classlist:   1,550.38 ms
...
[libnativeimpl:15600]      [total]:  25,166.30 ms
Test call as JNI
3
-1
Compile main as native image
Build on Server(pid: 15600, port: 35991)
[demo.main:15600]    classlist:     184.20 ms
...
[demo.main:15600]      [total]:  16,072.58 ms
Test native to native call by JNI
Exception in thread "main" java.lang.UnsatisfiedLinkError: no nativeimpl in java.library.path
	at com.oracle.svm.core.jdk.NativeLibrarySupport.loadLibrary(NativeLibrarySupport.java:131)
	at java.lang.ClassLoader.loadLibrary(Target_java_lang_ClassLoader.java:126)
	at java.lang.Runtime.loadLibrary0(Runtime.java:829)
	at java.lang.Runtime.loadLibrary(Runtime.java:235)
	at java.lang.System.loadLibrary(System.java:360)
	at demo.Main.main(Main.java:7)
```
But that is easily worked around with using `./demo.main -Djava.library.path=$PWD` instead of `./demo.main -Djava.library.path=.`

**Comment by ziyilin** [comment] 2019-12-18 11:19
Sorry I didn't make it clear. 
The attached script does not reproduce the segment fault because the classpath for building the main native image includes both the classes in library and application sides. If you change  `cp19_3` to the same as `cp19_2`, it will reproduce the segment fault.

**Comment by olpaw** [comment] 2020-09-25 07:18
@ziyilin does this issue still have any relevance or can we close it?

**Closed** 2020-09-25 07:42 UTC
Labels: native-image, question
