### ISSUE TITLE
Graal compiler error in 1.0.0-EE-RC8

### ISSUE THREAD

**Issue by lenborje** [oracle/graal#770] opened 2018-11-01 10:46 UTC
Got this when I ran a benchmark to compare the Community and the Enterprise editions. The Enterprise edition failed with a graal compiler error.

I've attached the 'graal_diagnostics_15423.zip' produced by the error.

`Thread[JVMCI CompilerThread1,9,system]: Compilation of java.math.BigInteger.oddModPow(BigInteger, BigInteger) failed: org.graalvm.compiler.debug.GraalError: failed guarantee: no FrameState at DeoptimizingNode 971|Deopt
        at org.graalvm.compiler.debug.GraalError.guarantee(GraalError.java:86)
        at org.graalvm.compiler.phases.common.FrameStateAssignmentPhase$FrameStateAssignmentClosure.processNode(FrameStateAssignmentPhase.java:69)
        at org.graalvm.compiler.phases.common.FrameStateAssignmentPhase$FrameStateAssignmentClosure.processNode(FrameStateAssignmentPhase.java:61)
        at org.graalvm.compiler.phases.graph.ReentrantNodeIterator.apply(ReentrantNodeIterator.java:125)
        at org.graalvm.compiler.phases.graph.ReentrantNodeIterator.apply(ReentrantNodeIterator.java:102)
        at org.graalvm.compiler.phases.common.FrameStateAssignmentPhase.run(FrameStateAssignmentPhase.java:127)
        at org.graalvm.compiler.phases.Phase.run(Phase.java:49)
        at org.graalvm.compiler.phases.BasePhase.apply(BasePhase.java:197)
        at org.graalvm.compiler.phases.BasePhase.apply(BasePhase.java:139)
        at org.graalvm.compiler.phases.PhaseSuite.run(PhaseSuite.java:212)
        at org.graalvm.compiler.phases.BasePhase.apply(BasePhase.java:197)
        at org.graalvm.compiler.phases.BasePhase.apply(BasePhase.java:139)
        at org.graalvm.compiler.core.GraalCompiler.emitFrontEnd(GraalCompiler.java:261)
        at org.graalvm.compiler.core.GraalCompiler.compile(GraalCompiler.java:180)
        at org.graalvm.compiler.core.GraalCompiler.compileGraph(GraalCompiler.java:165)
        at org.graalvm.compiler.hotspot.HotSpotGraalCompiler.compileHelper(HotSpotGraalCompiler.java:191)
        at org.graalvm.compiler.hotspot.HotSpotGraalCompiler.compile(HotSpotGraalCompiler.java:204)
        at org.graalvm.compiler.hotspot.CompilationTask$HotSpotCompilationWrapper.performCompilation(CompilationTask.java:181)
        at org.graalvm.compiler.hotspot.CompilationTask$HotSpotCompilationWrapper.performCompilation(CompilationTask.java:98)
        at org.graalvm.compiler.core.CompilationWrapper.run(CompilationWrapper.java:172)
        at org.graalvm.compiler.hotspot.CompilationTask.runCompilation(CompilationTask.java:330)
        at org.graalvm.compiler.hotspot.HotSpotGraalCompiler.compileMethod(HotSpotGraalCompiler.java:144)
        at org.graalvm.compiler.hotspot.HotSpotGraalCompiler.compileMethod(HotSpotGraalCompiler.java:111)
        at jdk.vm.ci.hotspot.HotSpotJVMCIRuntime.compileMethod(HotSpotJVMCIRuntime.java:525)
`
[graal_diagnostics_15423.zip](https://github.com/oracle/graal/files/2538138/graal_diagnostics_15423.zip)

**Comment by thomaswue** [comment] 2018-11-01 12:45
Thanks for the report. We will look into this asap.

**Comment by dougxc** [comment] 2018-11-01 13:29
Hi @lenborje , thanks for the report. I have a couple of questions and suggestions:
1. Can you please add these options to see if the problem goes away: `-XX:-UseMontgomeryMultiplyIntrinsic -XX:-UseMontgomerySquareIntrinsic`.
2. Is it possible to get a hold of the benchmark and a command line to reproduce?
3. Is the above stack trace from the same execution that produced the diagnostics zip file?

**Comment by lenborje** [comment] 2018-11-01 15:10
1.  The `-XX:-UseMontgomerySquareIntrinsic` helps!
2. Sure! The benchmark is a trivial JMH benchmark. I've included the code below. The error is triggered by the "benchGraalEE" test with params `candidatePrime=31` and `certainty=1`.
3. Well... As JMH invoked the test in several iterations, I just hit Ctrl-C and grabbed the latest.


`package com.cinnober.rat;`

`import org.openjdk.jmh.annotations.\*;`
`import java.math.\*;`
`import java.util.concurrent.\*;`
  
`@SuppressWarnings("unused")`
`  @BenchmarkMode(Mode.AverageTime)`
`  @OutputTimeUnit(TimeUnit.NANOSECONDS)`
`  @Warmup(iterations = 5, time = 1, timeUnit = TimeUnit.SECONDS)`
`  @Measurement(iterations = 5, time = 1, timeUnit = TimeUnit.SECONDS)`
  `@Fork(1)`
  `@State(Scope.Benchmark)`
  `public class GraalTest {`

    @Param({"31", "65", "1111", "370248451"})
    public long candidatePrime;

    @Param({"1", "8", "15"})
    public int certainty;

    @Benchmark
    public boolean bench() {
        return BigInteger.valueOf(candidatePrime).isProbablePrime(certainty);
    }

    @Benchmark
    @Fork(jvm="/Library/Java/JavaVirtualMachines/graalvm-ce-1.0.0-rc8/Contents/Home/bin/java")
    public boolean benchGraalCE() {
        return BigInteger.valueOf(candidatePrime).isProbablePrime(certainty);
    }

    @Benchmark
    @Fork(jvm="/Library/Java/JavaVirtualMachines/graalvm-ee-1.0.0-rc8/Contents/Home/bin/java")
    public boolean benchGraalEE() {
        return BigInteger.valueOf(candidatePrime).isProbablePrime(certainty);
    }

    @Benchmark
    @Fork(jvm="/Library/Java/JavaVirtualMachines/graalvm-ee-1.0.0-rc8/Contents/Home/bin/java", jvmArgsAppend={"-XX:-UseMontgomerySquareIntrinsic"})
    public boolean benchGraalEE_wo1() {
        return BigInteger.valueOf(candidatePrime).isProbablePrime(certainty);
    }

    @Benchmark
    @Fork(jvm="/Library/Java/JavaVirtualMachines/graalvm-ee-1.0.0-rc8/Contents/Home/bin/java", jvmArgsAppend={"-XX:-UseMontgomeryMultiplyIntrinsic"})
    public boolean benchGraalEE_wo2() {
        return BigInteger.valueOf(candidatePrime).isProbablePrime(certainty);
    }

    @Benchmark
    @Fork(jvm="/Library/Java/JavaVirtualMachines/graalvm-ee-1.0.0-rc8/Contents/Home/bin/java", jvmArgsAppend={"-XX:-UseMontgomeryMultiplyIntrinsic", "-XX:-UseMontgomerySquareIntrinsic"})
    public boolean benchGraalEE_wo3() {
        return BigInteger.valueOf(candidatePrime).isProbablePrime(certainty);
    }
 }
`

**Comment by wirthi** [comment] 2023-02-23 16:24
I am closing this ticket. I cannot reproduce it with our latest release 22.3.0, on neither JDK 17 nor JDK 19. Tried with CE and EE as in your code.

**Closed by wirthi** 2023-02-23 16:24 UTC
Labels: bug, compiler

**Comment by lenborje** [comment] 2023-02-23 18:24
Oh, it was many commits ago.... Anyway, thanks for testing.
