### ISSUE TITLE
ZonedDateTime.format() using DateFormatter has unusual results

### ISSUE THREAD

**Issue by itspa1** [oracle/graal#2615] opened 2020-06-25 16:53 UTC
**Describe the issue**
When using ZonedDateTime and formatting using a DateFormatter, different results are being generated using a runnable jar and native-image built binary.

**Steps to reproduce the issue**
a basic snippet is given in the description.

**Describe GraalVM and your environment:**
 - GraalVM version **[20.1.0]**
 - JDK major version: **11**
 - OS: **Linux (although this was compiled on docker)**
 - Architecture: **AMD64**

**More details**
so, to give an overview of what is happening, first I'll give an overview of what went wrong, so I have a DateTimeFormatter to format time to the particular timezone from utc,
```
TimeZone timeZone = TimeZone.getDefault(); //this defaults from the system. which is IST
ZoneId defaultZone = ZoneId.of(timeZone.getID());
DateTimeFormatter moment = DateTimeFormatter.ofPattern("yyyy-MM-dd'T'HH:mm:ssX").withZone(defaultZone);
ZonedDateTime parsedTime = ZonedDateTime.parse((String) message.get("timestamp"), moment) //passing the timestamp which i get from utc to a ZonedDateTime
//next this is where i convert it to a timestamp string
System.out.println(parsedTime);
System.out.println(parsedTime.format(moment));
```
So, with the above code, when running it as a runnable jar file, I get the current output (which is as expected)
```
2020-06-25T22:12:25+05:30[Asia/Kolkata]
2020-06-25T22:12:25+0530
2020-06-25T22:12:28+05:30[Asia/Kolkata]
2020-06-25T22:12:28+0530
```
So, when I run the same after compiling it with native-image compiled binary file, I get this output (which I think is formatting it to UTC, since it is -5:30)
```
2020-06-25T16:44:18+05:30[Asia/Kolkata]
2020-06-25T16:44:18+0530
2020-06-25T16:44:21+05:30[Asia/Kolkata]
2020-06-25T16:44:21+0530
```
I'm not sure entirely what is going wrong since it says Asia/Kolkata in the parsedTime but it actually is -5:30(UTC).
Any help is appreciated.

**Comment by Impeekay** [comment] 2020-07-01 06:30
Any updates on this? @cstancu

**Comment by jaikiran** [comment] 2020-07-02 10:08
I can't reproduce this against 20.1.0 or latest upstream of Graal. What exactly is the value of a `message.get("timestamp")`? Can you print it out? Either way, that probably isn't the issue.

You mention about using docker to compile this. What is the output of `date` within that container? Does it match your expectations of current time in UTC?

**Comment by Impeekay** [comment] 2020-07-02 10:19
@jaikiran thanks for the reply, `date` within the container is an IST time because I've set the timezone of the container to IST from the host. Are you implying that this would have an effect?

**Comment by jaikiran** [comment] 2020-07-02 10:21
> Are you implying that this would have an effect?

No, I was just trying to rule out docker from the equation.

So, in the program you pasted, the only "input" is the `message.get("timestamp")` value. If you can print that string out and show us what that string looks like, that might help us try and reproduce it, by using the exact same string.

**Comment by Impeekay** [comment] 2020-07-02 11:03
@jaikiran sure, sure I'll try to compile everything again and get back. Thank you

**Comment by Impeekay** [comment] 2020-08-06 12:28
@jaikiran @cstancu sorry for the late reply, going by the same example provided earlier. consider the below
```
2020-08-06T12:21:21Z
2020-08-06T17:51:21+05:30[Asia/Kolkata]
2020-08-06T17:51:21+0530
```
The first line shows the `message.get("timestamp")`, the second shows the parsed time and the third line shows the formatted parsed time. the above also shows the expected behavior.

The below output shows the lines in the same order and shows the output that I'm getting from the native-image compiled binary.
```
2020-08-06T12:21:21Z
2020-08-06T12:21:21+05:30[Asia/Kolkata]
2020-08-06T12:21:21+0530
```
I'm lost at his point debugging this.

**Comment by oubidar-Abderrahim** [comment] 2023-12-06 15:47
Hi @itspa1 
Could you please verify if this issue is still present in our latest GraalVM version? if yes, please share a full reproducer (`message` variable is not identifiable in the above code you shared) Thank you

**Comment by oubidar-Abderrahim** [comment] 2024-01-09 10:23
closing this issue as not reproducible, if you still face this issue on our latest GraalVM version, please reopen and share a complete reproducer of the issue. Thank you

**Closed by oubidar-Abderrahim** 2024-01-09 10:23 UTC
Labels: bug, native-image
