### ISSUE TITLE
Socket io streams on virtual thread intermittently stuck with native-image 

### ISSUE THREAD

**Issue by danielkec** [oracle/graal#5540] opened 2022-11-30 11:56 UTC
**Describe the issue**
Deadlocked request has been reported for Helidon Nima on Windows native-image(helidon-io/helidon/issues/5273). We have been able to narrow the issue to combination of socket io streams on virtual thread. Intermittent issue is easily reproducible
on Windows with `Invoke-WebRequest`(1:5), on Linux with `curl` appears give or take 1:1200-4000   

**Steps to reproduce the issue**
1. `javac --enable-preview --release 19 Main.java`
2. `native-image --enable-preview Main`
3. `./main` - keep running 
4. `for i in {1..10000}; do curl --trace - localhost:8081/test$i; echo; done`

Reproducer Main.java
```java
import java.io.IOException;
import java.io.OutputStream;
import java.net.InetSocketAddress;
import java.net.ServerSocket;
import java.net.Socket;
import java.net.StandardSocketOptions;
import java.nio.charset.StandardCharsets;
import java.util.Scanner;
import java.util.concurrent.CompletableFuture;
import java.util.concurrent.Executors;

public class Main {
    public static void main(String[] args) throws IOException {
        ServerSocket serverSocket = new ServerSocket();
        serverSocket.setOption(StandardSocketOptions.SO_REUSEADDR, true);
        serverSocket.setOption(StandardSocketOptions.SO_RCVBUF, 4096);
        InetSocketAddress address = new InetSocketAddress("localhost", 8081);
        serverSocket.bind(address);
        System.out.println("Ready at " + address);
        while (true) {
            Socket socket = serverSocket.accept();
            CompletableFuture.runAsync(() -> {
                        try (Scanner scanner = new Scanner(socket.getInputStream(), StandardCharsets.UTF_8)) {
                            Scanner s = scanner.useDelimiter("\r\n");
                            String line;
                            String content = null;
                            while (s.hasNext()) {
                                line = s.next();
                                if (line.equals("")) break;
                                if (line.startsWith("GET")) content = "{\"info\":\"" + line + "\"}";
                            }

                            OutputStream os = socket.getOutputStream();
                            os.write("HTTP/1.1 200 OK\r\n".getBytes());
                            os.write("Date: Tue, 29 Nov 2022 21:14:59 +0100\r\n".getBytes());
                            os.write("Connection: Close\r\n".getBytes());
                            os.write(("Content-Length: " + content.length() + "\r\n").getBytes());
                            os.write("Content-Type: application/json\r\n".getBytes());
                            os.write("\r\n".getBytes());
                            os.write(content.getBytes());
                            socket.getInputStream().close();
                        } catch (IOException e) {
                            e.printStackTrace();
                        }
                    }, Executors.newVirtualThreadPerTaskExecutor())
                    .whenComplete((unused, throwable) -> {
                        try {
                            socket.close();
                        } catch (IOException e) {
                            e.printStackTrace();
                        }
                    });
        }
    }
}

```

**Describe GraalVM and your environment:**
 - GraalVM version: `GraalVM 22.3.0 Java 19 CE (Java Version 19.0.1+10-jvmci-22.3-b08)`
 - JDK major version: `19.0.1+10-jvmci-22.3-b08`
 - OS: `5.4.0-132-generic #148~18.04.1-Ubuntu SMP Mon Oct 24 20:41:14 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux`
 - Architecture: `x86_64`
```
 Version info: 'GraalVM 22.3.0 Java 19 CE'
 Java version info: '19.0.1+10-jvmci-22.3-b08'
 C compiler: gcc (linux, x86_64, 7.5.0)
 Garbage collector: Serial GC
```

**Comment by peter-hofer** [comment] 2022-12-07 18:11
Thank you @danielkec and @lost22git for reporting this and creating a reproducer, I'm looking into this.

**Comment by peter-hofer** [comment] 2023-04-28 06:23
Fixed in f4e1fe1d5a9ac675ad7453cc793d9ad2b788f466.

**Closed by peter-hofer** 2023-04-28 06:23 UTC
Labels: bug, native-image

**Comment by danielkec** [comment] 2023-04-28 07:11
PR #5656

**Comment by peter-hofer** [comment] 2023-04-28 07:28
@danielkec I doubt that it's significant since it's only for the duration of class initialization.
