### ISSUE TITLE
Segmentation fault with running Micronaut native image apps with latest Alpine glibc docker

### ISSUE THREAD

**Issue by ilopmar** [oracle/graal#3159] opened 2021-01-27 14:21 UTC
**Describe the issue**

In Micronaut we use the docker image `frolvlad/alpine-glibc:alpine-3.12` for running native image applications. Recently that docker image has been upgraded to use alpine-3.13 and the apps now fail with a segmentation fault.

**Steps to reproduce the issue**

- `git clone https://github.com/micronaut-graal-tests/micronaut-servlet-graal`
- `cd micronaut-servlet-graal`
- `git checkout issue-alpine-3.13`
- Use GraalVM 21.0 release (it doesn't matter if it's Java 8 or 11)
- `./build-native-image.sh`

Start a docker container:
- `docker run -it --rm -v $PWD:/app frolvlad/alpine-glibc:alpine-3.13 sh`
- `apk add libstdc++`
- `/app/servlet-jetty`

The app fails with:

```
/ # / # /app/servlet-jetty

/app/servlet-jetty: /usr/lib/libstdc++.so.6: no version information available (required by /app/servlet-jetty)
/app/servlet-jetty: /usr/lib/libstdc++.so.6: no version information available (required by /app/servlet-jetty)
/app/servlet-jetty: Relink `/usr/lib/libgcc_s.so.1' with `/usr/glibc-compat/lib/libc.so.6' for IFUNC symbol `memset'
Segmentation fault (core dumped)
```

Doing the same but with `frolvlad/alpine-glibc:alpine-3.12` version makes it work again.

**Describe GraalVM and your environment:**
 - GraalVM version: **21.0.0 (for both Java 8 and 11). It also happens with latest `master`**
 - JDK major version: **8 and 11**
 - OS: **Linux Alpine**
 - Architecture: **AMD64**

**Comment by mcraj017** [comment] 2021-01-29 05:11
@ilopmar thanks for reporting the issue
we will check it out and update you

**Comment by mcraj017** [comment] 2021-01-29 08:37
@ilopmar while reproducing the error, I am getting error:
`/ # /app/servlet-jetty
/app/servlet-jetty: line 1: �����H: not found
/app/servlet-jetty: line 6: syntax error: unexpected word (expecting ")")`

here is the full console output

[console.log](https://github.com/oracle/graal/files/5892660/console.log)

**Comment by ilopmar** [comment] 2021-01-29 08:43
@mcraj017 I think the problem is that you are using Mac, so when creating the native image you are creating a binary that is Mac only. Then, when trying to run that binary in the Linux Alpine container, it fails.

**Comment by gradinac** [comment] 2021-03-02 12:07
Hey @ilopmar!
I've tried this on Ubuntu 20.04 && GraalVM master (Java 11) - it seems to work properly:
```
$ docker run -it --rm -v $PWD:/app frolvlad/alpine-glibc:alpine-3.13 sh
Unable to find image 'frolvlad/alpine-glibc:alpine-3.13' locally
alpine-3.13: Pulling from frolvlad/alpine-glibc
ba3557a56b15: Pull complete 
f2d1d2b92dd5: Pull complete 
Digest: sha256:b522e0d06a3492bec319f70db74f6da75e28c07662efb9d8dba42e357acc1de2
Status: Downloaded newer image for frolvlad/alpine-glibc:alpine-3.13
/ # apk add libstdc++
fetch https://dl-cdn.alpinelinux.org/alpine/v3.13/main/x86_64/APKINDEX.tar.gz
fetch https://dl-cdn.alpinelinux.org/alpine/v3.13/community/x86_64/APKINDEX.tar.gz
(1/1) Installing libstdc++ (10.2.1_pre1-r3)
Executing glibc-bin-2.33-r0.trigger
/usr/glibc-compat/sbin/ldconfig: /usr/glibc-compat/lib/ld-linux-x86-64.so.2 is not a symbolic link

OK: 19 MiB in 18 packages
/ # /app/servlet-jetty 
 __  __ _                                  _   
|  \/  (_) ___ _ __ ___  _ __   __ _ _   _| |_ 
| |\/| | |/ __| '__/ _ \| '_ \ / _` | | | | __|
| |  | | | (__| | | (_) | | | | (_| | |_| | |_ 
|_|  |_|_|\___|_|  \___/|_| |_|\__,_|\__,_|\__|
  Micronaut (v2.3.4-SNAPSHOT)

12:45:26.756 [main] INFO  org.eclipse.jetty.server.Server - jetty-9.4.35.v20201120; built: 2020-11-20T21:17:03.964Z; git: bdc54f03a5e0a7e280fab27f55c3c75ee8da89fb; jvm 11.0.10
12:45:26.758 [main] INFO  o.e.j.server.handler.ContextHandler - Started i.m.s.j.@7b907319{/,null,AVAILABLE}
12:45:26.758 [main] INFO  o.e.jetty.server.AbstractConnector - Started ServerConnector@799d227d{HTTP/1.1, (http/1.1)}{localhost:8080}
12:45:26.759 [main] INFO  org.eclipse.jetty.server.Server - Started @20ms
12:45:26.759 [main] INFO  io.micronaut.runtime.Micronaut - Startup completed in 20ms. Server Running: http://localhost:8080/
```
Which host distro are you using?
I think this issue may be related to a mismatch of the library versions between the host system used to build the native-image and the compat layer ones that are used to run it.

**Comment by ilopmar** [comment] 2021-03-05 08:31
Hi @gradinac, sorry for the delay. I know what's going on and why it is working for you. Some time after I submitted the issue I enabled the `-H:+StaticExecutableWithDynamicLibC` flag in that branch, that's why it is working.
I've updated the original issue with a new branch that reproduces the issue. Please try now using the branch `issue-alpine-3.13` and you can reproduce the problem.

Sorry again for the inconvenience, I always try to create specific branches for these issues but I forgot about this.

**Comment by IgorEulalio** [comment] 2021-04-12 03:11
This problem been solved?

**Comment by ilopmar** [comment] 2021-04-12 08:15
I've just tried compiling GraalVM from master branch and it still fails with the same error.

**Comment by MuFengZiYu** [comment] 2021-06-23 02:57
when i am running my application in [ frolvlad/alpine-glibc:alpine-3.12] . The message is  " error while loading shared libraries: libstdc++.so.6: cannot open shared object file". 
It has been compiled by springci/graalvm-ce:stable-java11-0.10.x and running well. But the graalvm images are fat.
I'm trying to figure out an available base image.

**Comment by MuFengZiYu** [comment] 2021-06-23 03:03
> when i am running my application in [ frolvlad/alpine-glibc:alpine-3.12] . The message is " error while loading shared libraries: libstdc++.so.6: cannot open shared object file".
> It has been compiled by springci/graalvm-ce:stable-java11-0.10.x and running well. But the graalvm images are fat.
> I'm trying to figure out an available base image.

but when i add "apk add libstdc++" i worked again.

**Comment by gradinac** [comment] 2023-05-24 12:23
Hey @ilopmar, this ticket fell through the cracks, sorry for that. :/

Hmm, if this worked with `-H:+StaticExecutableWithDynamicLibC`, I suspect that one of the dependency libraries that was used to compile the app is different from what is in the frolvlad image - I would either try with a different libstdc++, or a different glibc version on the host system.

I think this is more of an issue with the setup of the environment in which the app is running. In a case like this, I would either deploy it using `-H:+StaticExecutableWithDynamicLibC`, or ditch the custom docker image entirely and create a fully static executable (in case you don't need any JNI libraries) using https://www.graalvm.org/latest/reference-manual/native-image/guides/build-static-executables/

Due to the above, I'll close this ticket - but we can re-open it if any more issues arise with the above alternative approaches

**Closed by gradinac** 2023-05-24 12:23 UTC
Labels: bug, native-image
