### ISSUE TITLE
Index out of bound on latest RC when using native-image

### ISSUE THREAD

**Issue by machaval** [oracle/graal#746] opened 2018-10-18 01:59 UTC
``` fatal errors detected:
fatal error: java.lang.IndexOutOfBoundsException: index -1
	at java.util.concurrent.atomic.AtomicReferenceArray.checkedByteOffset(AtomicReferenceArray.java:78)
	at java.util.concurrent.atomic.AtomicReferenceArray.get(AtomicReferenceArray.java:125)
	at com.oracle.graal.pointsto.flow.context.object.AnalysisObject.getInstanceFieldTypeStore(AnalysisObject.java:213)
	at com.oracle.graal.pointsto.flow.context.object.AnalysisObject.getInstanceFieldFlow(AnalysisObject.java:199)
	at com.oracle.graal.pointsto.flow.LoadFieldTypeFlow$LoadInstanceFieldTypeFlow.onObservedUpdate(LoadFieldTypeFlow.java:159)
	at com.oracle.graal.pointsto.flow.TypeFlow.notifyObservers(TypeFlow.java:347)
	at com.oracle.graal.pointsto.flow.TypeFlow.update(TypeFlow.java:389)
	at com.oracle.graal.pointsto.BigBang$2.run(BigBang.java:508)
	at com.oracle.graal.pointsto.util.CompletionExecutor.lambda$execute$0(CompletionExecutor.java:174)
	at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1402)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
fatal error: java.lang.IndexOutOfBoundsException: index -1
	at java.util.concurrent.atomic.AtomicReferenceArray.checkedByteOffset(AtomicReferenceArray.java:78)
	at java.util.concurrent.atomic.AtomicReferenceArray.get(AtomicReferenceArray.java:125)
	at com.oracle.graal.pointsto.flow.context.object.AnalysisObject.getInstanceFieldTypeStore(AnalysisObject.java:213)
	at com.oracle.graal.pointsto.flow.context.object.AnalysisObject.getInstanceFieldFlow(AnalysisObject.java:199)
	at com.oracle.graal.pointsto.flow.LoadFieldTypeFlow$LoadInstanceFieldTypeFlow.onObservedUpdate(LoadFieldTypeFlow.java:159)
	at com.oracle.graal.pointsto.flow.TypeFlow.notifyObservers(TypeFlow.java:347)
	at com.oracle.graal.pointsto.flow.TypeFlow.update(TypeFlow.java:389)
	at com.oracle.graal.pointsto.BigBang$2.run(BigBang.java:508)
	at com.oracle.graal.pointsto.util.CompletionExecutor.lambda$execute$0(CompletionExecutor.java:174)
	at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1402)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
Error: Processing image build request failed```

**Comment by cstancu** [comment] 2018-10-23 05:44
Can you give more context and steps to reproduce this? Without that and having seen a similar stack trace before I **think** that this problem can be caused by trying to build the native image with an incomplete class path, i.e., the app that you are trying to build the image from has some optional library dependencies which you probably don't use. We are currently working on a general solution for these issues and plan to release it in rc9.

**Comment by zharinov** [comment] 2018-11-06 18:18
Well, I have this problem as well.
I'm trying to run minimal query with H2 database local build (with direct ByteBuffer problem in image heap resolved).
Additional dependencies such as `lucene` and `slf4j-api` are explicitly written in my build config.
Command line:
```
native-image --language:js \
--tool:truffle  \
--verbose \
-H:ReflectionConfigurationFiles=reflect.conf.json \
--report-unsupported-elements-at-runtime \
app-standalone.jar
```

**Comment by cstancu** [comment] 2018-11-06 18:43
I think this is the same issue as https://github.com/oracle/graal/issues/772 which I was able to reproduce and isolate. We will have a fix soon.

**Comment by cstancu** [comment] 2019-03-15 01:25
The `IndexOutOfBoundsException` has been fixed in the meantime. If the underlying problem still persists now you should at least get a more intuitive error message. Please open a fresh issue if that's the case.

**Closed by cstancu** 2019-03-15 01:25 UTC
Labels: substrate
