### ISSUE TITLE
[native-image] wrong type in AnalysisObject

### ISSUE THREAD

**Issue by johanvos** [oracle/graal#995] opened 2019-02-19 12:20 UTC
In `AnalysisObject.getInstanceFieldTypeStore()`, I get an `ArrayIndexOutOfBoundException` since the store is empty (for `Object`) while we try to retrieve it's element at position 2.

I noticed that in all calls to` getInstanceFieldTypeStore(BigBang bb, AnalysisField field)` the `field` corresponds to `this`, but printing the values of this and field when it fails show

`this`: `0x0000000100000002:!S:Object`
`this.type`: `AnalysisType<java.lang.Object, allocated: true, inHeap: true, inTypeCheck: true>`
`field`: `AnalysisField<ProtectionDomain.codesource accessed: false reads: true written: true>` 

complete stacktrace:
    ```
    at java.base/java.lang.invoke.VarHandle$1.apply(VarHandle.java:2011)
        at java.base/java.lang.invoke.VarHandle$1.apply(VarHandle.java:2008)
        at java.base/jdk.internal.util.Preconditions$1.apply(Preconditions.java:159)
        at java.base/jdk.internal.util.Preconditions$1.apply(Preconditions.java:156)
        at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:62)
        at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70)
        at java.base/jdk.internal.util.Preconditions.checkIndex(Preconditions.java:248)
        at java.base/java.lang.invoke.VarHandleObjects$Array.getVolatile(VarHandleObjects.java:438)
        at java.base/java.lang.invoke.VarHandleGuards.guard_LI_L(VarHandleGuards.java:646)
        at java.base/java.util.concurrent.atomic.AtomicReferenceArray.get(AtomicReferenceArray.java:100)
        at com.oracle.graal.pointsto.flow.context.object.AnalysisObject.getInstanceFieldTypeStore(AnalysisObject.java:218)
        at com.oracle.graal.pointsto.flow.context.object.AnalysisObject.getInstanceFieldFlow(AnalysisObject.java:200)
        at com.oracle.graal.pointsto.flow.LoadFieldTypeFlow$LoadInstanceFieldTypeFlow.onObservedUpdate(LoadFieldTypeFlow.java:159)
        at com.oracle.graal.pointsto.flow.TypeFlow.notifyObservers(TypeFlow.java:347)
        at com.oracle.graal.pointsto.flow.TypeFlow.update(TypeFlow.java:389)
        at com.oracle.graal.pointsto.BigBang$2.run(BigBang.java:508)
        at com.oracle.graal.pointsto.util.CompletionExecutor.lambda$execute$0(CompletionExecutor.java:169)
        at java.base/java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1426)
        at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
        at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
        at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
        at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
        at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:177)

```

**Comment by rkennke** [comment] 2019-02-19 15:30
I also see this bug when trying to comile spring-petclinic.

**Comment by cstancu** [comment] 2019-02-19 20:03
Thanks for the report. This is the same problem as https://github.com/oracle/graal/issues/985. I am working on a solution.

**Comment by cstancu** [comment] 2019-02-20 04:27
The issue is fixed in https://github.com/oracle/graal/commit/9f0546754bfb1bf2a1963f0c4358a67aaeab63b1. The problem was with the `DynamicHub.getProtectionDomain()` substitution: it declared `Object` return type instead of `ProtectionDomain`, so the points-to analysis was not applying the expected type narrowing. I also improved the error reporting: instead of an `ArrayIndexOutOfBoundException` now you would get `AnalysisError$FieldNotPresentError: Field java.security.ProtectionDomain.codesource is not present on type java.lang.Object. Error encountered while analysing java.security.ProtectionDomain.getCodeSource()`.

**Closed by cstancu** 2019-02-20 04:27 UTC
Labels: substrate
