### ISSUE TITLE
Logback requires a lot of configuration to work with SubstrateVM

### ISSUE THREAD

**Issue by sdeleuze** [oracle/graal#807] opened 2018-11-15 14:41 UTC
Logback configuration does not work with SubstrateVM, see this [repro project](https://github.com/sdeleuze/graal-issues/tree/master/logback).

```
In regular JVM
-2018-11-15 15:34:12.276 -DEBUG -  --- [           main] ROOT                                     : Message 1
-2018-11-15 15:34:12.281 - WARN -  --- [           main] ROOT                                     : Message 2
```

As GraalVM native image
```
%PARSER_ERROR[clr] %PARSER_ERROR[clr] %PARSER_ERROR[clr] %PARSER_ERROR[clr] %PARSER_ERROR[clr] %PARSER_ERROR[clr] %PARSER_ERROR[clr] %PARSER_ERROR[m]%PARSER_ERROR[n]%PARSER_ERROR[clr] %PARSER_ERROR[clr] %PARSER_ERROR[clr] %PARSER_ERROR[clr] %PARSER_ERROR[clr] %PARSER_ERROR[clr] %PARSER_ERROR[clr] %PARSER_ERROR[m]%PARSER_ERROR[n]
```

Tested with GraalVM 1.0.0 RC9

**Comment by dsyer** [comment] 2018-11-16 11:52
It works for me with this JSON in `-H:ReflectionConfigurationFiles`:

```
[
    {
        "name" : "com.sample.ColorConverter",
        "allPublicConstructors": true,
        "allPublicMethods": true,
        "allDeclaredMethods": true
    },
    {
		"name": "ch.qos.logback.classic.pattern.DateConverter",
		"allDeclaredConstructors": true
	},
	{
		"name": "ch.qos.logback.classic.pattern.MessageConverter",
		"allDeclaredConstructors": true
	},
 	{
 		"name": "ch.qos.logback.classic.pattern.ThrowableProxyConverter",
 		"allDeclaredConstructors": true
 	},
 	{
 		"name": "ch.qos.logback.classic.pattern.NopThrowableInformationConverter",
 		"allDeclaredConstructors": true
 	},
 	{
 		"name": "ch.qos.logback.classic.pattern.ContextNameConverter",
 		"allDeclaredConstructors": true
 	},
 	{
 		"name": "ch.qos.logback.core.pattern.color.BoldYellowCompositeConverter",
 		"allDeclaredConstructors": true
 	},
 	{
 		"name": "ch.qos.logback.classic.pattern.LoggerConverter",
 		"allDeclaredConstructors": true
 	},
 	{
 		"name": "ch.qos.logback.core.pattern.ReplacingCompositeConverter",
 		"allDeclaredConstructors": true
 	},
 	{
 		"name": "ch.qos.logback.core.pattern.color.BoldBlueCompositeConverter",
 		"allDeclaredConstructors": true
 	},
 	{
 		"name": "ch.qos.logback.core.pattern.color.CyanCompositeConverter",
 		"allDeclaredConstructors": true
 	},
 	{
 		"name": "ch.qos.logback.core.pattern.color.RedCompositeConverter",
 		"allDeclaredConstructors": true
 	},
 	{
 		"name": "ch.qos.logback.core.pattern.color.WhiteCompositeConverter",
 		"allDeclaredConstructors": true
 	},
 	{
 		"name": "ch.qos.logback.classic.pattern.PropertyConverter",
 		"allDeclaredConstructors": true
 	},
    {
 		"name": "ch.qos.logback.classic.pattern.ExtendedThrowableProxyConverter",
 		"allDeclaredConstructors": true
 	},
 	{
 		"name": "ch.qos.logback.classic.pattern.RootCauseFirstThrowableProxyConverter",
 		"allDeclaredConstructors": true
 	},
 	{
 		"name": "ch.qos.logback.classic.pattern.MethodOfCallerConverter",
 		"allDeclaredConstructors": true
 	},
 	{
 		"name": "ch.qos.logback.classic.pattern.LevelConverter",
 		"allDeclaredConstructors": true
 	},
 	{
 		"name": "ch.qos.logback.core.pattern.IdentityCompositeConverter",
 		"allDeclaredConstructors": true
 	},
 	{
 		"name": "ch.qos.logback.core.pattern.color.BoldWhiteCompositeConverter",
 		"allDeclaredConstructors": true
 	},
 	{
 		"name": "ch.qos.logback.classic.pattern.MarkerConverter",
 		"allDeclaredConstructors": true
 	},
 	{
 		"name": "ch.qos.logback.core.pattern.color.BoldCyanCompositeConverter",
 		"allDeclaredConstructors": true
 	},
 	{
 		"name": "ch.qos.logback.core.pattern.color.BoldMagentaCompositeConverter",
 		"allDeclaredConstructors": true
 	},
 	{
 		"name": "ch.qos.logback.classic.pattern.RelativeTimeConverter",
 		"allDeclaredConstructors": true
 	},
 	{
 		"name": "ch.qos.logback.core.pattern.color.MagentaCompositeConverter",
 		"allDeclaredConstructors": true
 	},
 	{
 		"name": "ch.qos.logback.classic.pattern.ClassOfCallerConverter",
 		"allDeclaredConstructors": true
 	},
 	{
 		"name": "ch.qos.logback.classic.pattern.LineOfCallerConverter",
 		"allDeclaredConstructors": true
 	},
 	{
 		"name": "ch.qos.logback.classic.pattern.FileOfCallerConverter",
 		"allDeclaredConstructors": true
 	},
 	{
 		"name": "ch.qos.logback.core.pattern.color.BoldGreenCompositeConverter",
 		"allDeclaredConstructors": true
 	},
 	{
 		"name": "ch.qos.logback.classic.pattern.LocalSequenceNumberConverter",
 		"allDeclaredConstructors": true
 	},
 	{
 		"name": "ch.qos.logback.core.pattern.color.YellowCompositeConverter",
 		"allDeclaredConstructors": true
 	},
 	{
 		"name": "ch.qos.logback.classic.pattern.ExtendedThrowableProxyConverter",
 		"allDeclaredConstructors": true
 	},
 	{
 		"name": "ch.qos.logback.classic.pattern.color.HighlightingCompositeConverter",
 		"allDeclaredConstructors": true
 	},
 	{
 		"name": "ch.qos.logback.core.pattern.color.GrayCompositeConverter",
 		"allDeclaredConstructors": true
 	},
 	{
 		"name": "ch.qos.logback.classic.pattern.MDCConverter",
 		"allDeclaredConstructors": true
 	},
 	{
 		"name": "ch.qos.logback.classic.pattern.ClassOfCallerConverter",
 		"allDeclaredConstructors": true
 	},
 	{
 		"name": "ch.qos.logback.core.pattern.color.BoldRedCompositeConverter",
 		"allDeclaredConstructors": true
 	},
 	{
 		"name": "ch.qos.logback.core.pattern.color.GreenCompositeConverter",
 		"allDeclaredConstructors": true
 	},
 	{
 		"name": "ch.qos.logback.core.pattern.color.BlackCompositeConverter",
 		"allDeclaredConstructors": true
 	},
 	{
 		"name": "ch.qos.logback.classic.pattern.ThreadConverter",
 		"allDeclaredConstructors": true
 	},
 	{
 		"name": "ch.qos.logback.classic.pattern.LineSeparatorConverter",
 		"allDeclaredConstructors": true
 	}
]
```

**Comment by sdeleuze** [comment] 2018-11-19 10:57
Indeed, I have updated the repro project accordingly.

That said, could GraalVM team have a look to see if there is something that could be improved in GraalVM reflection support to avoid this huge configuration for a basic need?

**Comment by cstancu** [comment] 2019-03-10 00:17
@sdeleuze the [Assisted Configuration of Native Image Builds](https://github.com/oracle/graal/blob/master/substratevm/CONFIGURE.md) should make it easier to discover the reflectivelly accessed elements. Reflection configuration is still required for reflective access and we don't plan to change that. Enabling reflective access for all elements, without any config, although possible, would increase the size of the generated image due to the needed metadata. I tried your repo and your example works as expected. I am closing this issue as not a bug.

**Closed by cstancu** 2019-03-10 00:17 UTC
Labels: substrate

**Comment by cstancu** [comment] 2019-03-10 00:25
@rahulsom did you try using `--delay-class-initialization-to-runtime=...` as mentioned in the error message? You can read more about [class initialization on `native-image`](https://medium.com/graalvm/understanding-class-initialization-in-graalvm-native-image-generation-d765b7e4d6ed). Please open another issue and provide a reproducible example if you still have problems.

**Comment by aleksmelnikov** [comment] 2020-07-20 17:22
I've got a similar error when I try build a simple project with `RollingFileAppender`.

```
$ native-image --no-server -cp build/libs/t2-0.1-all.jar t2.Application                                                  
[t2.application:329199]    classlist:   7,109.67 ms,  0.96 GB
[t2.application:329199]        (cap):     957.93 ms,  0.96 GB
[t2.application:329199]        setup: 443,169.68 ms,  0.96 GB
WARNING GR-10238: VarHandle for static field is currently not fully supported. Static field private static volatile java.lang.System$Logger jdk.internal.event.EventHelper.securityLogger is not properly marked for Unsafe access!
[t2.application:329199]     (clinit):   1,678.75 ms,  2.35 GB
[t2.application:329199]   (typeflow):  36,498.92 ms,  2.35 GB
[t2.application:329199]    (objects):  31,191.14 ms,  2.35 GB
[t2.application:329199]   (features):   4,341.22 ms,  2.35 GB
[t2.application:329199]     analysis:  76,870.64 ms,  2.35 GB
Warning: Aborting stand-alone image build. Detected a FileDescriptor in the image heap. File descriptors opened during image generation are no longer open at image run time, and the files might not even be present anymore at image run time.  To see how this object got instantiated use -H:+TraceClassInitialization. The object was probably created by a class initializer and is reachable from a static field. You can request class initialization at image run time by using the option --initialize-at-run-time=<class-name>. Or you can write your own initialization methods and call them explicitly from your main entry point.
Detailed message:
Trace: Object was reached by
        reading field java.io.FileOutputStream.fd of
                constant java.io.FileOutputStream@51b7510d reached by
        reading field ch.qos.logback.core.recovery.ResilientFileOutputStream.fos of
                constant ch.qos.logback.core.recovery.ResilientFileOutputStream@2dea633a reached by
        reading field ch.qos.logback.core.OutputStreamAppender.outputStream of
                constant ch.qos.logback.core.rolling.RollingFileAppender@7f308709 reached by
        reading field ch.qos.logback.core.status.StatusBase.origin of
                constant ch.qos.logback.core.status.InfoStatus@5a32b5cb reached by
        indexing into array
                constant java.lang.Object[]@34ded872 reached by
        reading field java.util.ArrayList.elementData of
                constant java.util.ArrayList@f6b08fc3 reached by
        reading field ch.qos.logback.core.BasicStatusManager.statusList of
                constant ch.qos.logback.core.BasicStatusManager@40845bbd reached by
        reading field ch.qos.logback.core.ContextBase.sm of
                constant ch.qos.logback.classic.LoggerContext@38c3294b reached by
        reading field ch.qos.logback.classic.Logger.loggerContext of
                constant ch.qos.logback.classic.Logger@26a36799 reached by
        scanning method io.micronaut.runtime.Micronaut.start(Micronaut.java:149)
Call path from entry point to io.micronaut.runtime.Micronaut.start():
        at io.micronaut.runtime.Micronaut.start(Micronaut.java:60)
        at io.micronaut.runtime.Micronaut.run(Micronaut.java:294)
        at io.micronaut.runtime.Micronaut.run(Micronaut.java:280)
        at t2.Application.main(Application.java:8)
        at com.oracle.svm.core.JavaMainWrapper.runCore(JavaMainWrapper.java:149)
        at com.oracle.svm.core.JavaMainWrapper.run(JavaMainWrapper.java:184)
        at com.oracle.svm.core.code.IsolateEnterStub.JavaMainWrapper_run_5087f5482cc9a6abc971913ece43acb471d2631b(generated:0)

Warning: Use -H:+ReportExceptionStackTraces to print stacktrace of underlying exception
[t2.application:329326]    classlist:   2,630.35 ms,  0.96 GB
[t2.application:329326]        (cap):     916.28 ms,  0.96 GB
```

So look at: `java.io.FileOutputStream.fd` <--- 
May be error is here: 
```
    @TargetClass(java.io.FileOutputStream.class)
    static final class Target_java_io_FileOutputStream {
        @Alias//
        FileDescriptor fd;
    }
```
May be this class should be without `static` like:
```
    @TargetClass(java.io.FileOutputStream.class)
    final class Target_java_io_FileOutputStream {
        @Alias//
        FileDescriptor fd;
    }
```
Could anybody build graalvm with this change and test the error?
