### ISSUE TITLE
Running native image with error 'ClassNotFoundException: com.kute.boot3.SpringBoot3DemoApplication__ApplicationContextInitializer'

### ISSUE THREAD

**Issue by kute** [oracle/graal#5683] opened 2022-12-29 08:52 UTC
Having build a native image with the maven plugin `native-image-maven-plugin` and then running the image with some errors.

Env:
 GraalVM Version info: 'GraalVM 22.3.0 Java 17 CE'
 Java version info: '17.0.5+8-jvmci-22.3-b08'
OS: MacOS Ventura 13.1
Spring boot : spring boot 3.0.1

MainClass

```
package com.kute.boot3;

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;

@SpringBootApplication
public class SpringBoot3DemoApplication {
    public static void main(String[] args) {
        SpringApplication.run(SpringBoot3DemoApplication.class, args);
    }
}
```

pom.xml

```
<plugin>
                <groupId>org.graalvm.nativeimage</groupId>
                <artifactId>native-image-maven-plugin</artifactId>
                <version>21.2.0</version>
                <executions>
                    <execution>
                        <goals>
                            <goal>native-image</goal>
                        </goals>
                        <phase>package</phase>
                    </execution>
                </executions>
                <configuration>
                    <skip>false</skip>
                    <imageName>spring-boot-3-demo-image</imageName>
                    <buildArgs>
                        --no-fallback
                        --initialize-at-build-time=ch.qos.logback
                        --initialize-at-build-time=org.slf4j
                    </buildArgs>
                    <mainClass>com.kute.boot3.SpringBoot3DemoApplication</mainClass>
                </configuration>
            </plugin>
```

Then execute package with `mvn clean package -U -Dmaven.test.skip=true` , generate the image file  `spring-boot-3-demo-image` under target dir.

Then execute the image with `./target/spring-boot-3-demo-image` and it errors.

```
15:41:45.427 [main] DEBUG org.springframework.context.aot.AotApplicationContextInitializer - Initializing ApplicationContext with AOT
15:41:45.427 [main] ERROR org.springframework.boot.SpringApplication - Application run failed
java.lang.IllegalArgumentException: Could not find class [com.kute.boot3.SpringBoot3DemoApplication__ApplicationContextInitializer]
        at org.springframework.util.ClassUtils.resolveClassName(ClassUtils.java:333)
        at org.springframework.context.aot.AotApplicationContextInitializer.instantiateInitializer(AotApplicationContextInitializer.java:80)
        at org.springframework.context.aot.AotApplicationContextInitializer.initialize(AotApplicationContextInitializer.java:71)
        at org.springframework.context.aot.AotApplicationContextInitializer.lambda$forInitializerClasses$0(AotApplicationContextInitializer.java:61)
        at org.springframework.boot.SpringApplication.applyInitializers(SpringApplication.java:603)
        at org.springframework.boot.SpringApplication.prepareContext(SpringApplication.java:383)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:307)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1302)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1291)
        at com.kute.boot3.SpringBoot3DemoApplication.main(SpringBoot3DemoApplication.java:17)
Caused by: java.lang.ClassNotFoundException: com.kute.boot3.SpringBoot3DemoApplication__ApplicationContextInitializer
        at java.base@17.0.5/java.lang.Class.forName(DynamicHub.java:1132)
        at org.springframework.util.ClassUtils.forName(ClassUtils.java:283)
```

Then i found the `SpringBoot3DemoApplication__ApplicationContextInitializer` 

`org.springframework.boot.SpringApplication`

<img width="1515" alt="image" src="https://user-images.githubusercontent.com/5119587/209927544-37f45881-9f51-48d9-8c34-5477e2bb32d9.png">

**Comment by fniephaus** [comment] 2022-12-29 12:22
@sdeleuze any idea what's going on here?

**Comment by gardellajuanpablo** [comment] 2022-12-29 15:02
Same issue by using:

```
						<plugin>
							<groupId>org.springframework.boot</groupId>
							<artifactId>spring-boot-maven-plugin</artifactId>
							<configuration>
								<image>
									<builder>paketobuildpacks/builder:tiny</builder>
									<env>
										<BP_NATIVE_IMAGE>true</BP_NATIVE_IMAGE>
										<BP_NATIVE_IMAGE_BUILD_ARGUMENTS>--no-fallback</BP_NATIVE_IMAGE_BUILD_ARGUMENTS>
									</env>
								</image>
							</configuration>
							<executions>
								<execution>
									<id>process-aot</id>
									<goals>
										<goal>process-aot</goal>
									</goals>
								</execution>
							</executions>
						</plugin>
						<plugin>
							<groupId>org.graalvm.buildtools</groupId>
							<artifactId>native-maven-plugin</artifactId>
							<configuration>
								<classesDirectory>${project.build.outputDirectory}</classesDirectory>
								<metadataRepository>
									<enabled>true</enabled>
								</metadataRepository>
								<requiredVersion>22.3</requiredVersion>
							</configuration>
							<executions>
								<execution>
									<id>add-reachability-metadata</id>
									<goals>
										<goal>add-reachability-metadata</goal>
									</goals>
								</execution>
							</executions>
						</plugin>

```
I am not using spring-boot-parent. Built using `mvn -Pnative spring-boot:build-image`.

**Comment by fniephaus** [comment] 2022-12-29 15:12
Are you sure you need to set `mainClass` in your `pom.xml`? AFAIK, Spring should take care of this for you. I'm assuming you've added `native-image-maven-plugin` so that you can add additional `buildArgs`?

**Comment by oeresundsgruppen** [comment] 2022-12-29 23:42
Would be great with a fix for this...

**Comment by kute** [comment] 2022-12-30 02:38
> Are you sure you need to set `mainClass` in your `pom.xml`? AFAIK, Spring should take care of this for you. I'm assuming you've added `native-image-maven-plugin` so that you can add additional `buildArgs`?

Yes, it will show the error below if i don't add the `mainClass` .

```
Error: Please specify class (or <module>/<mainclass>) containing the main entry point method. (see --help)
```

**Comment by kute** [comment] 2022-12-30 03:06
It works by using the plugin `native-maven-plugin` instead of  the `native-image-maven-plugin` and generates the class `com.kute.boot3.SpringBoot3DemoApplication__ApplicationContextInitializer` under the dir `target/spring-aot/sources/com/kute/boot3/SpringBoot3DemoApplication__ApplicationContextInitializer.java`.

SpringBoot3DemoApplication__ApplicationContextInitializer.java

```
/**
 * {@link ApplicationContextInitializer} to restore an application context based on previous AOT processing.
 */
public class SpringBoot3DemoApplication__ApplicationContextInitializer implements ApplicationContextInitializer<GenericApplicationContext> {
  @Override
  public void initialize(GenericApplicationContext applicationContext) {
    DefaultListableBeanFactory beanFactory = applicationContext.getDefaultListableBeanFactory();
    beanFactory.setAutowireCandidateResolver(new ContextAnnotationAutowireCandidateResolver());
    beanFactory.setDependencyComparator(AnnotationAwareOrderComparator.INSTANCE);
    new SpringBoot3DemoApplication__BeanFactoryRegistrations().registerBeanDefinitions(beanFactory);
    new SpringBoot3DemoApplication__BeanFactoryRegistrations().registerAliases(beanFactory);
  }
}
```

The pom.xml below and  generate the image `target/spring-boot-3-demo` by executing the `mvn -Pnative -DskipTests package`.

```
<profiles>
        <profile>
            <id>native</id>
            <build>
                <plugins>
                    <plugin>
                        <groupId>org.graalvm.buildtools</groupId>
                        <artifactId>native-maven-plugin</artifactId>
                        <version>0.9.19</version>
                        <extensions>true</extensions>
                        <executions>
                            <execution>
                                <id>build-native</id>
                                <goals>
                                    <goal>compile-no-fork</goal>
                                </goals>
                                <phase>package</phase>
                            </execution>
                            <execution>
                                <id>test-native</id>
                                <goals>
                                    <goal>test</goal>
                                </goals>
                                <phase>test</phase>
                            </execution>
                        </executions>
                        <configuration>
                        </configuration>
                    </plugin>
                </plugins>
            </build>
        </profile>
    </profiles>
```

It has no error when executing the image with `./target/spring-boot-3-demo`.

**Comment by fniephaus** [comment] 2022-12-30 07:35
Right, the initial post mentioned the wrong plugin and a very old GraalVM release:

```xml
<groupId>org.graalvm.nativeimage</groupId>
<artifactId>native-image-maven-plugin</artifactId>
<version>21.2.0</version>
```

[Here's the documentation](https://graalvm.github.io/native-build-tools/) for the Native Build Tools and the right plugin is:

```xml
<groupId>org.graalvm.buildtools</groupId>
<artifactId>native-maven-plugin</artifactId>
<version>${native.maven.plugin.version}</version>
```

Can this be closed?

**Comment by oeresundsgruppen** [comment] 2022-12-30 21:21
Not sure, it is solved; using native-maven-plugin, springboot 3.0.1, spring 6.0.3, have set mainclass - still have above error on ApplicationContextInitializer not found...

**Comment by sdeleuze** [comment] 2023-01-02 15:25
You should not have to configure the main class, it is detected automatically.

Please provide a reproducer to allow us to have a deeper look.

**Comment by oeresundsgruppen** [comment] 2023-01-02 20:36
Think its due to me mixing spring experimental (native and aot), with spring-framework 6 + boot 3. Boot 3 is supposed to have support for native and aot without experimental dependencies...

**Closed** 2023-01-03 09:33 UTC
Labels: bug, native-image, spring

**Comment by klopfdreh** [comment] 2023-01-10 11:04
@oeresundsgruppen you are right with the mixture of dependencies, but https://github.com/oracle/graal/issues/5683#issuecomment-1367392664 is showing a correct maven configuration for Spring Boot 3 native support configured with maven. 

The gradle configuration can be found here: https://github.com/spring-projects/spring-boot/blob/main/spring-boot-project/spring-boot-starters/spring-boot-starter-parent/build.gradle#L231 and also a hint is also mentioned here: https://docs.spring.io/spring-boot/docs/3.0.0/reference/html/native-image.html#native-image.testing.with-native-build-tools.maven.

For me the same issue occurred with Spring Boot Maven Plugin 3.0.1, Native Maven Plugin 0.9.19.

**Comment by oeresundsgruppen** [comment] 2023-01-10 21:46
@klopfdreh - thanks for hint with spring-boot:build-image, builds with java17 (not 19), but still gives log4j error - java.lang.NoSuchMethodException: org.apache.logging.log4j.message.DefaultFlowMessageFactory

**Comment by gardellajuanpablo** [comment] 2023-01-12 16:19
Just FYI, for linux OS with [ecryptfs](https://www.ecryptfs.org/), you can face following weird issue: "Unable to compile generated source .. File name too long". The reason is a limitation on [file names to 143 characters](https://bugs.launchpad.net/ecryptfs/+bug/344878). I mention it here for future reference, as this is one of the first results on google.

**Comment by padeledicq** [comment] 2023-02-01 14:16
> @klopfdreh - thanks for hint with spring-boot:build-image, builds with java17 (not 19), but still gives log4j error - java.lang.NoSuchMethodException: org.apache.logging.log4j.message.DefaultFlowMessageFactory

I have the exact same issue. Did you manage to solve it?

**Comment by klopfdreh** [comment] 2023-02-01 16:44
Hey @padeledicq - have a look at the linked issue: „ Native compiled docker image causes class not found exception for ApplicationContextInitializer“ - my issue was solved and I don’t know if it is exact the same than yours.

**Comment by oeresundsgruppen** [comment] 2023-02-02 21:57
It builds , but still have NoSuchMethodException: org.apache.logging.log4j.message.DefaultFlowMessageFactory.<init>() - latest spring/boot on java17

**Comment by schrer** [comment] 2023-05-01 13:05
@oeresundsgruppen I think I had the same issue (maybe only similar, don't remember the exact error message), no Spring, but also Java 17. I switched to logback, which solved the issue. For me that was fairly easy, since my project is still fairly small, so not a universally good workaround. Can't offer any better suggestions unfortunately.

**Comment by arunswaminathank** [comment] 2023-07-07 11:18
mvn compile or build is not generating the spring aot source files. 
Run mvn spring-boot:process-aot command to generate the **__ApplicationContextInitializer files.
After that include that folder in  <classpath> of build plugin - native-maven-plugin

**Comment by sdeleuze** [comment] 2023-07-10 07:51
Don't forget `-Pnative` as documented.
