### ISSUE TITLE
JVM crash with SIGSEGV

### ISSUE THREAD

**Issue by vbotteman** [oracle/graal#2065] opened 2020-01-13 08:05 UTC
We're  using GraalVM CE 19.2.0 and had 2 similar JVM crashes.

```
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x00007f0144458955, pid=13912, tid=0x00007f0114fff700
#
# JRE version: OpenJDK Runtime Environment (8.0_222-b08) (build 1.8.0_222-20190711120915.buildslave.jdk8u-src-tar--b08)
# Java VM: OpenJDK 64-Bit GraalVM CE 19.2.0 (25.222-b08-jvmci-19.2-b02 mixed mode linux-amd64 compressed oops)
# Problematic frame:
# V  [libjvm.so+0x4af955]  CMSATBBufferClosure::do_buffer(void**, unsigned long)+0x4a5
#
```

Error files:
[app2_hs_err_pid20510.log](https://github.com/oracle/graal/files/4052536/app2_hs_err_pid20510.log)
[app2_hs_err_pid13912.log](https://github.com/oracle/graal/files/4052537/app2_hs_err_pid13912.log)

**Comment by tkrodriguez** [comment] 2020-01-13 18:01
Those crashes happened after 2-3 days so I'm guessing reproducibility is low.  Have you tried a more recent GraalVM release?  I think 19.3.1 should be out soon.  Have you run a non-GraalVM JDK in the same configuration without problem or have you only used GraalVM on this setup?

**Comment by vbotteman** [comment] 2020-01-14 08:07
We have a JVM crash about every 2 days. These crashes only occur on our production servers. So far we were unable to reproduce it on test servers. We use GraalVM for about half a year but the crashes started 2 or 3 weeks ago when the load on our application increased. Before that we used OpenJDK and had no crashes but the load was a lot less.

**Comment by tkrodriguez** [comment] 2020-01-16 20:08
Hmm.  That sort of looks like a missing null check on one of the arguments to the crypt intrinsic.  I'll see if anything changed there or it's an existing problem.

**Comment by tkrodriguez** [comment] 2020-01-17 20:06
It looks like AESCrypt.K is null, which we're loading in intrinsic so we end up passing a bogus pointer to the stub.  K is set during initialization of the cipher so I don't know how it could be null.  The same C2 intrinsic doesn't include a null check of this value either.  We can of course handle the NULL here but I wonder if there's some deeper problem.  Any chance you see any exceptions from AESCrypt.decryptBlock in your logs?  Or any other crypto related exceptions?

**Comment by vbotteman** [comment] 2020-01-17 22:43
I can't find any exception related to crypto in our logging. Is there anything else I can check?

**Comment by tkrodriguez** [comment] 2020-01-18 01:22
not really.  I searched on google to see there were any hs_err files out there with a similar crash but didn't find anything so I think it must be new.  I'm wondering if this is something that just appeared with 8u242.  There seem to be some keystore fixes in that release so maybe it's related.  I'm going to dig into the code and what changed in the release to see if there are any clues.

**Comment by tkrodriguez** [comment] 2020-01-20 19:28
Looking up the call path I think we must be applying this intrinsic where the cipher isn't an AESCrypt.  From the call stack, 
```v  ~StubRoutines::cipherBlockChaining_decryptAESCrypt
J 81063 JVMCI-native com.sun.crypto.provider.CipherBlockChaining.decrypt([BII[BI)I (40 bytes) @ 0x00007f19759ec1ae [0x00007f19759ec0a0+0x10e]
j  com.sun.crypto.provider.FeedbackCipher.decryptFinal([BII[BI)I+8
j  com.sun.crypto.provider.CipherCore.finalNoPadding([BI[BII)I+162
j  com.sun.crypto.provider.CipherCore.fillOutputBuffer([BI[BII[B)I+8
J 44051 C1 com.sun.crypto.provider.CipherCore.doFinal([BII)[B (124 bytes) @ 0x00007f197259e7e4 [0x00007f197259e500+0x2e4]
j  com.sun.crypto.provider.PKCS12PBECipherCore.implDoFinal([BII)[B+7
j  com.sun.crypto.provider.PKCS12PBECipherCore$PBEWithSHA1AndRC2_40.engineDoFinal([BII)[B+7
j  javax.crypto.Cipher.doFinal([B)[B+30
j  sun.security.pkcs12.PKCS12KeyStore.engineLoad(Ljava/io/InputStream;[C)V+556
j  java.security.KeyStore.load(Ljava/io/InputStream;[C)V+6
```

I think the cipher should be an RC2Crypt.  We do include a dynamic test that it's really an AESCrypt before using the intrinsic code but it seems like that must be failing.  I'll see if I can exercise the same path.

**Comment by vbotteman** [comment] 2020-01-21 09:32
I tried passing a wrong p12 file or an incomplete p12 file but both cases are handled nicely and doesn't crash the JVM. It would have surprised me. The last couple of days the JVM is stable.

**Comment by tkrodriguez** [comment] 2020-01-21 22:16
I put together a test case that uses KeyStore.load with pkcs12 keystore and I don't see a crash either.  I do see some recompilation anomalies that need to be fixed but nothing that would lead to a crash of the kind you saw.  So you've only seen this once?  I'll fix the issues I've seen ana maybe make the code more robust in the face of null, just in case.

**Comment by tkrodriguez** [comment] 2021-01-08 20:29
Just FYI, i just tracked this down to a missing dependence on the class hierarchy.  We were compiling the intrinsic when AESCrypt was the only symmetric cipher and not throwing out this code once other ciphers were loaded.  I'll update as soon as I know which releases the fix will go into.

**Comment by tkrodriguez** [comment] 2021-01-14 18:09
The fix for the AES crash should appear in all our next update releases.  In particular, 19.3.5 will include it.  https://github.com/oracle/graal/commit/f4d095e8205  I'm closing this issue as this seems resolved.  Please reopen if there are further problems.

**Closed by tkrodriguez** 2021-01-14 18:09 UTC
