### ISSUE TITLE
It reports  "Exception in thread "main" java.lang.UnsatisfiedLinkError: no awt in java.library.path"  when starting.

### ISSUE THREAD

**Issue by opjk** [oracle/graal#3038] opened 2020-12-01 06:53 UTC
**Describe the issue**
My project is a desktop Application  coding with openJFX 15, openJDK 11 and springboot 2.4.0.  
It works fine  starting with ' java -jar  ' command ,  but don't  work  with native image. 
It reports  "Exception in thread "main" java.lang.UnsatisfiedLinkError: no awt in java.library.path"  when starting.

 
**Describe GraalVM and your environment:**
 - JDK major version: **[ GraalVM CE 20.3.0 (build 11.0.9+10-jvmci-20.3-b06) ]**
 - OS: **[ deepin v20 ]**
 - Architecture: **[AMD64]**

**More details**
Consider adding the `--native-image-info` and  `--verbose` flags when building your native image and paste output below.

Add any other information about the problem here. Especially important are stack traces or log output. Feel free to link to gists or to screenshots if necessary.
```
Exception in thread "main" java.lang.UnsatisfiedLinkError: no awt in java.library.path
at com.oracle.svm.core.jdk.NativeLibrarySupport.loadLibrary(NativeLibrarySupport.java:131)
at java.lang.ClassLoader.loadLibrary(ClassLoader.java:270)
at java.lang.Runtime.loadLibrary0(Runtime.java:830)
at java.lang.Runtime.loadLibrary(Runtime.java:232)
at java.lang.System.loadLibrary(System.java:351)
at java.awt.Toolkit$3.run(Toolkit.java:1395)
at java.awt.Toolkit$3.run(Toolkit.java:1393)
at java.security.AccessController.doPrivileged(AccessController.java:84)
at java.awt.Toolkit.loadLibraries(Toolkit.java:1392)
at java.awt.Toolkit.(Toolkit.java:1425)
at com.oracle.svm.core.classinitialization.ClassInitializationInfo.invokeClassInitializer(ClassInitializationInfo.java:351)
at com.oracle.svm.core.classinitialization.ClassInitializationInfo.initialize(ClassInitializationInfo.java:271)
at java.awt.SystemTray.isSupported(SystemTray.java:221)
at de.felixroske.jfxsupport.AbstractJavaFxApplicationSupport.launch(AbstractJavaFxApplicationSupport.java:279)
at com.gridnt.confbox.gui.ConfBoxApplication.main(ConfBoxApplication.java:24)
```
**Gradle  configuration about native image:**

```
apply plugin: "org.openjfx.javafxplugin"
apply plugin: 'com.github.ayltai.spring-graalvm-native-plugin'

javafx {
    version = "15"
    modules = ["javafx.base", "javafx.controls", "javafx.fxml"
               , "javafx.graphics", "javafx.media", "javafx.swing", "javafx.web"
    ]
}

nativeImage {
    mainClassName = 'com.ConfBoxApplication'
    javaVersion = "11"
    reportExceptionStackTraces = true
    removeUnusedAutoConfig = true
    removeYamlSupport = true
    maxHeapSize = '8G'
    initializeAtBuildTime = ['org.apache.commons.logging.LogFactory']
}

```

**Comment by oubidar-Abderrahim** [comment] 2020-12-02 09:32
Could you please share a small reproducer for this issue? there isn't currently much information to debug

**Comment by zakkak** [comment] 2020-12-03 09:17
Possible duplicate of https://github.com/oracle/graal/issues/2842

**Closed** 2021-05-17 10:42 UTC
Labels: bug, native-image
