### ISSUE TITLE
Espresso doesn't support `Value.asValue(IOException).newInstance(...)`

### ISSUE THREAD

**Issue by JaroslavTulach** [oracle/graal#7435] opened 2023-09-16 13:46 UTC
**Describe GraalVM and your environment :**

```bash
$ /graalvm/bin/java --version
openjdk 17.0.7 2023-04-18
OpenJDK Runtime Environment GraalVM CE 17.0.7+7.1 (build 17.0.7+7-jvmci-23.0-b12)
OpenJDK 64-Bit Server VM GraalVM CE 17.0.7+7.1 (build 17.0.7+7-jvmci-23.0-b12, mixed mode, sharing)

```

**Have you verified this issue still happens when using the latest snapshot?**

No, I haven't, but I assume it does. Checking whether the following program works is a quick check for someone who has the latest snapshot.

**Describe the issue**

Save following snippet as `Espressotest.java` and execute as `/graalvm/bin/java -ea Espressotest.java`:

```java
import java.io.IOException;

import org.graalvm.polyglot.Context;
import org.graalvm.polyglot.Value;

public class Espressotest {
    public static void main(String[] args) {
        var ctx = Context.newBuilder("java")
            .option("java.PolyglotInterfaceMappings", "java.lang.Runnable")
            .option("java.Polyglot", "true")
            .allowAllAccess(true)
            .build();
        compare(ctx);
    }

    private static void compare(Context ctx) {
        var v1 = instantiate(ctx.asValue(IOException.class), "456");
        var espressoClass = ctx.getBindings("java").getMember("java.io.IOException");
        var v2 = instantiate(espressoClass, "456");
        System.err.println("result as " + v1 + " in JVM and as " + v2 + " in Espresso");
    }

    private static Value instantiate(Value clazz, String text) {
        assert clazz != null : "We got a clazz";
        assert clazz.canInstantiate() : "Can be instantiated";
        var instance = clazz.newInstance(text);
        return instance.invokeMember("getMessage");
    }
}
```

It fails for me with:
```
com.oracle.truffle.espresso.meta.EspressoError: failed guarantee: Espresso interop only supports static methods and public instance method
        at com.oracle.truffle.espresso.meta.EspressoError.guarantee(EspressoError.java:107)
        at com.oracle.truffle.espresso.nodes.interop.InvokeEspressoNode.checkValidInvoke(InvokeEspressoNode.java:160)
        at com.oracle.truffle.espresso.nodes.interop.InvokeEspressoNode.doCached(InvokeEspressoNode.java:93)
        at com.oracle.truffle.espresso.nodes.interop.InvokeEspressoNodeGen.executeAndSpecialize(InvokeEspressoNodeGen.java:148)
        at com.oracle.truffle.espresso.nodes.interop.InvokeEspressoNodeGen.executeMethod(InvokeEspressoNodeGen.java:102)
        at com.oracle.truffle.espresso.nodes.interop.InvokeEspressoNode.execute(InvokeEspressoNode.java:56)
        at com.oracle.truffle.espresso.impl.Klass$Instantiate.doObject(Klass.java:434)
        at com.oracle.truffle.espresso.impl.KlassGen$InteropLibraryExports$Cached.instantiateAndSpecialize(KlassGen.java:405)
        at com.oracle.truffle.espresso.impl.KlassGen$InteropLibraryExports$Cached.instantiate(KlassGen.java:303)
        at org.graalvm.truffle/com.oracle.truffle.api.interop.InteropLibrary$Asserts.instantiate(InteropLibrary.java:3131)

```

**Expected behavior**

No failure. The program shall print:
```
result as 456 in JVM and as 456  in Espresso
```

**Additional context**

I discovered this problem while working on 
- https://github.com/enso-org/enso/pull/6966

btw. I got our [core test suite working with Espresso](https://github.com/enso-org/enso/pull/6966#issuecomment-1722239609). _1663 tests succeeded. 541 tests failed._ Not perfect, but certainly not completely desperate...

</details>

**Comment by mukel** [comment] 2023-09-17 15:20
Thanks for the clean report. I can reproduce it, the issue is caused by method overload selection for constructors, which use a different path than regular instance methods.

**Comment by JaroslavTulach** [comment] 2023-10-31 12:43
Alfonso, do you plan to integrate a fix? What's your ETA? Or rather, ping me when I am supposed to test it. Thank you.

**Comment by mukel** [comment] 2023-12-07 14:08
Fixed in https://github.com/oracle/graal/pull/7946

**Closed by mukel** 2023-12-07 14:08 UTC
Labels: truffle, java on truffle
