### ISSUE TITLE
[LLVM] Sharing context between threads cause crash when `stat` syscall is used.

### ISSUE THREAD

**Issue by roxanan-adyen** [oracle/graal#4133] opened 2021-12-16 09:28 UTC
**Describe GraalVM and your environment :**
 - GraalVM version or commit id if built from source: **21.2.0**
 - CE or EE: **EE**
 - JDK version: **JDK11**
 - OS and OS Version: * macOS bigSur**
 - Architecture: **amd64**
 - The output of `java -Xinternalversion`:
```
Java HotSpot(TM) 64-Bit Server VM (11.0.12+8-LTS-jvmci-21.2-b06) for bsd-amd64 JRE (11.0.12+8-LTS-jvmci-21.2-b06), built on Jul  1 2021 04:44:57 by "graal2" with gcc 4.2.1 Compatible Apple LLVM 11.0.0 (clang-1100.0.33.17)
```

**Have you verified this issue still happens when using the latest snapshot?**
Yes, I tried 21.3.0 version and I had the same issue. 

**Describe the issue**
I created a simple C shared library with the managed tools where I use `stat` syscall. I use this library in a java app. If I load the library in the main thread and in the same thread I execute the C side, everything works fine. But if I load the library in main thread and execute the C function in another thread, this causes a crash in `stat` syscall. This only happens in the file given as parameter to `stat` doesn't exist in the filesystem.  

**How to compile the LLVM bitcode that causes the problem**
 I used llvm managed tools to compile the C library.
 ```
 $GRAALVM_MANAGED_LLVM_TOOLCHAIN/clang -fPIC -shared crash_stat.c -lgraalvm-llvm -o crash.so
 ``` 
Where 
```
export GRAALVM_MANAGED_LLVM_TOOLCHAIN=$($GRAALVM_HOME/bin/lli --print-toolchain-path --llvm.managed)
```

**Code snippet or code repository that reproduces the problem**
This is the C code -- crash_stat.c:
```
#include<stdio.h>
#include <sys/stat.h>
#include <errno.h>
#include <string.h>

int my_function() {
    printf("C started\n");
    struct stat statbuf;
    int rc = stat("random_filename", &statbuf);
    printf("stat returned %d\n", rc);
    if (rc == -1) {
        printf("%s\n", strerror(errno));
    }

    return 0;
}
```

This is the Java class where I use only on thread. 
```
import java.io.*;
import org.graalvm.polyglot.*;

class JavaMainThread {
    public static void main(String[] args) throws Exception {
        Context polyglot = Context.newBuilder().allowAllAccess(true).allowIO(true).option("llvm.managed", "true").build();
        File file = new File("crash.so");
        Source source = Source.newBuilder("llvm", file).build();
        Value cpart = polyglot.eval(source);
        cpart.invokeMember("my_function");

    }
}
```
This is the Java class where I use 2 threads.
```
import java.io.*;
import org.graalvm.polyglot.*;

class Java2Threads {
    public static void main(String[] args) throws Exception {
        Context polyglot = Context.newBuilder().allowAllAccess(true).allowIO(true).option("llvm.managed", "true").build();
        File file = new File("crash.so");
        Source source = Source.newBuilder("llvm", file).build();
        Value cpart = polyglot.eval(source);

        Thread myThread = new Thread(() -> { // Lambda Expression
            System.out.println("MyThread running" + Thread.currentThread().getId());
            cpart.invokeMember("my_function");
        });

        myThread.start();
        myThread.join();

    }
}
```

**Steps to reproduce the problem**
1. GRAALVM_MANAGED_LLVM_TOOLCHAIN/clang -fPIC -shared crash_stat.c -lgraalvm-llvm -o crash.so
2. javac JavaMainThread.java && java JavaMainThread
 Output:
```
C started
stat returned -1
No such file or directory
```
3. javac Java2Threads.java && java Java2Threads 
Output:
```
MyThread running20
C started
Exception in thread "Thread-5" Illegal null pointer access in 'load i64'.
        at <llvm> my_function(crash_stat.c:9:165)
        at org.graalvm.sdk/org.graalvm.polyglot.Value.invokeMember(Value.java:921)
        at Java2Threads.lambda$main$0(Java2Threads.java:13)
        at java.base/java.lang.Thread.run(Thread.java:834)
```

Note: If the file exists, java2Threads doesn't crash. 

**Expected behavior**
Calling `stat` in another thread should not have unpredictable behavior. 

**Additional context**

**Comment by rschatz** [comment] 2021-12-16 13:14
I'm currently debugging that issue, I have a suspicion what it is. Definitely looks like an issue on our side. Thanks for reporting!

**Comment by rschatz** [comment] 2021-12-16 13:21
Internally tracked as GR-35890.

**Comment by ortix** [comment] 2022-01-03 12:05
Hi @rschatz, do you have any update regarding this issue?

**Comment by rschatz** [comment] 2022-01-10 09:12
Yes. We're not initializing some internal libc datastructures for threads that are created "externally", i.e. not with `pthread_create` but e.g. as in your example from Java.

I have a fix for it. The fix will be in the upcoming GraalVM 22.0.0 release.

**Comment by rschatz** [comment] 2022-01-10 09:38
For reference: This is the minimal reproducer regression test I added: https://github.com/oracle/graal/commit/a98c149337e02638cabb71f20ef856049c1aadc6

**Closed by rschatz** 2022-01-10 09:38 UTC
Labels: llvm

**Comment by roxanan-adyen** [comment] 2022-01-11 08:15
@rschatz Thanks a lot for solving this. Looking forward to the next release!

**Comment by roxanan-adyen** [comment] 2022-01-19 12:41
Hey @rschatz! I managed to download the new release and the issue is gone. Thanks once again for solving this!

**Comment by rschatz** [comment] 2022-02-03 10:49
Awesome, thanks for confirming!
