### ISSUE TITLE
Native-image dont working without stdio.h

### ISSUE THREAD

**Issue by Batman-Igor** [oracle/graal#3357] opened 2021-04-17 15:09 UTC
Hello everybody! I started to study GraalVM and trying to create native-image of "Hello World" project.
I had a Visual Studio 19 and also I download MinGW libs (dont know I need it or not, but it had stdio.h). 

When I'm trying to create native-image I have a problem:
```
C:\ProgrammingProjects\Java\GraalTest>native-image HelloWorld
[helloworld:9504]    classlist:   1,611.27 ms,  1.14 GB
[helloworld:9504]        (cap):     343.77 ms,  1.14 GB
[helloworld:9504]        setup:   1,001.11 ms,  1.14 GB
Error: Error compiling query code (in C:\Users\DevOS\AppData\Local\Temp\SVM-7738420043804611757\JNIHeaderDirectives.c). Compiler command ''C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.28.29910\bin\Hostx64\x64\cl.exe' /WX /W4 /wd4244 /wd4245 /wd4800 /wd4804 /wd4214 '-IC:\ProgrammingTools\graalvm\include' '-IC:\ProgrammingTools\graalvm\include\win32' '/FeC:\Users\DevOS\AppData\Local\Temp\SVM-7738420043804611757\JNIHeaderDirectives.exe' 'C:\Users\DevOS\AppData\Local\Temp\SVM-7738420043804611757\JNIHeaderDirectives.c' ' output included error: [JNIHeaderDirectives.c, C:\Users\DevOS\AppData\Local\Temp\SVM-7738420043804611757\JNIHeaderDirectives.c(1): fatal error C1083: ?? г¤ ?вбп ?вЄалвм д ?? ўЄ?оз??Ё?: stdio.h: No such file or directory,]
Error: Use -H:+ReportExceptionStackTraces to print stacktrace of underlying exception
Error: Image build request failed with exit status 1
```

I'm trying to hind the answer, but any solution didn't help me with that problem.

Some information:
- working in Hyper-V
- have the last version on GraalVM
- Also had last version of Visual Studio (and there are no problem with compiling code in VS)

**Comment by mcraj017** [comment] 2021-04-21 05:47
@Batman-Igor Please follow this link
https://www.graalvm.org/docs/getting-started/windows/
and if you still face error, please share the reproducer

**Comment by LilWayne7** [comment] 2021-04-21 06:00
> @Batman-Igor Please follow this link
> https://www.graalvm.org/docs/getting-started/windows/
> and if you still face error, please share the reproducer 

Thank you very much! I missed one thing (x64 Native Tools Command Prompt) and start it from usual cmd

**Comment by mcraj017** [comment] 2021-04-21 06:11
ok great, closing it now

**Closed by mcraj017** 2021-04-21 06:11 UTC
Labels: bug, native-image

**Comment by jacodg** [comment] 2022-02-15 12:41
I've had a similar problem (Cannot open include file: 'stdio.h') which turned out to be a lack of rights on my Windows machine / account. Searching for a solution didn't point into this direction and I basically only found this page. After I found the following:

https://stackoverflow.com/questions/35777997/stdio-h-in-visual-studio
https://stackoverflow.com/questions/54184448/microsoft-c-compiler-fatal-error-c1083-cannot-open-include-file-stdio-h
https://social.msdn.microsoft.com/Forums/vstudio/en-US/5402a5ae-82e5-4370-9297-5be12152ce5e/standard-users-cannot-open-windowsh-using-x64-native-tools

I switch user in Windows an logged in with an admin account and the problem was gone. I'm adding this comment here for those who struggle with the same problem and having a hard time relating the error message to the actual cause (a Windows account with limited rights).

**Comment by deliciouslytyped** [comment] 2023-05-18 00:59
Found this looking for a similar issue on linux, I needed to install build-essential. I didn't look into precisely what was missing.

**Comment by Enaium** [comment] 2025-01-29 14:29
I have done to install `msvc` and `windows sdk`, but it still throws the error.
I found some solutions.

1. New `INCLUDE` to environment.

```
C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\<version>\include;
C:\Program Files (x86)\Windows Kits\10\Include\<version>\ucrt;
C:\Program Files (x86)\Windows Kits\10\Include\<version>\shared;
C:\Program Files (x86)\Windows Kits\10\Include\<version>\um
```

2. New `LIB` to environment.

```
C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\<version>\lib\x64;
C:\Program Files (x86)\Windows Kits\10\Lib\<version>\ucrt\x64;
C:\Program Files (x86)\Windows Kits\10\Lib\<version>\um\x64
```
