### ISSUE TITLE
[GR-48362] Native-image --module-path does not accept a directory

### ISSUE THREAD

**Issue by Thihup** [oracle/graal#7271] opened 2023-08-24 11:49 UTC
**Describe the issue**
In the `java` command and in the `native-image --help`, it it possible to pass a directory of modules to the `--module-path` argument. However, the native-image only allows passing the full path to a jar.

It is possible to see it using `native-image --list-modules`

In the `native-image --help` it states that

```
    -p <module path>
    --module-path <module path>...
                          A : separated list of directories, each directory
                          is a directory of modules.
```

**Steps to reproduce the issue**

```bash
# Download a modular jar (in this case, ASM 9.5)
wget https://repo1.maven.org/maven2/org/ow2/asm/asm/9.5/asm-9.5.jar
mkdir mods
mv asm-9.5.jar mods
native-image --module-path mods --list-modules
```

It should not appear in the `org.objectweb.asm@9.5 mods/asm-9.5.jar open` line. Now changing to `native-image --module-path mods/asm-9.5.jar --list-modules` it shows up.

**Describe GraalVM and your environment:**
 - GraalVM CE 21-dev+34.1 (build 21+34-jvmci-23.1-b12)
 - JDK major version: 21-dev
 - OS: Ubuntu 22.04
 - Architecture: x86_64

**Comment by oubidar-Abderrahim** [comment] 2023-08-30 10:45
Hi thank you for reporting this, I tried to reproduce the issue but I get the following stacktrace in both cases (folder and JAR)
```
Exception in thread "main" java.util.NoSuchElementException: No value present
	at java.base@17.0.7/java.util.Optional.orElseThrow(Optional.java:377)
	at org.graalvm.nativeimage.driver/com.oracle.svm.driver.NativeImage.completeImageBuild(NativeImage.java:1084)
	at org.graalvm.nativeimage.driver/com.oracle.svm.driver.NativeImage.build(NativeImage.java:1592)
	at org.graalvm.nativeimage.driver/com.oracle.svm.driver.NativeImage.performBuild(NativeImage.java:1557)
	at org.graalvm.nativeimage.driver/com.oracle.svm.driver.NativeImage.main(NativeImage.java:1531)
```
Is there a missing step here?

**Comment by fniephaus** [comment] 2024-01-16 08:31
Hi @Thihup, I cannot reproduce this anymore on master. It also appears to be fixed in the latest [dev build](https://github.com/graalvm/graalvm-ce-dev-builds/releases) in case you like to try that out.

```
$ graalvm-community-openjdk-21.0.1+12.1/bin/native-image --module-path mods --list-modules
org.graalvm.nativeimage.librarysupport file:///home/fniephaus/Downloads/graalvm-community-openjdk-21.0.1+12.1/lib/svm/library-support.jar
org.objectweb.asm@9.5 file:///home/fniephaus/dev/tmp/GR-48362/mods/asm-9.5.jar open
org.postgresql.jdbc@42.7.1-all file:///home/fniephaus/dev/tmp/GR-48362/mods/postgresql-42.7.1-all.jar automatic

java.base@21.0.1
java.compiler@21.0.1
...
```

**Closed by fniephaus** 2024-01-16 08:31 UTC
Labels: bug, native-image
