### ISSUE TITLE
Fatal error C1083: Cannot open include file: 'unistd.h'

### ISSUE THREAD

**Issue by wh81752** [oracle/graal#5916] opened 2023-02-07 14:29 UTC
**Describe the issue**
I cannot get over the dreaded  "unistd.h" problem:
```
..
[1/7] Initializing...                                                                                    (0.0s @ 0.52GB)Error: Error compiling query code (in C:\Users\HAEFELW\AppData\Local\Temp\SVM-7069224817615501992\Substitutions_NativeInfoDirectives.c). Compiler command ''C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.29.30133\bin\HostX64\x64\cl.exe' /WX /W4 /wd4201 /wd4244 /wd4245 /wd4800 /wd4804 /wd4214 '/FeC:\Users\HAEFELW\AppData\Local\Temp\SVM-7069224817615501992\Substitutions_NativeInfoDirectives.exe' 'C:\Users\HAEFELW\AppData\Local\Temp\SVM-7069224817615501992\Substitutions_NativeInfoDirectives.c'' output included error: [Substitutions_NativeInfoDirectives.c, C:\Users\HAEFELW\AppData\Local\Temp\SVM-7069224817615501992\Substitutions_NativeInfoDirectives.c(11): fatal error C1083: Cannot open include file: 'unistd.h': No such file or directory]
Error: Use -H:+ReportExceptionStackTraces to print stacktrace of underlying exception
```

This error does not appear at all when building a simple 'HelloWorld" (i.e. javac HelloWorld.java && native-image HelloWorld.class.

It appears when I try to build a Micronaut App.

**Steps to reproduce the issue**
```mvn  -Dpackaging=native-image```
Maven project with Micronaut. The project is a migrated SpringBoot project. The code is confidential, so I cannot share. Building and running the micronaut project works fine. It's just that building a native image on Windows fails for really unknown reasons.

**Describe GraalVM and your environment:**

 - GraalVM version: **GraalVM CE 22.3.1 (build 17.0.6+10-jvmci-22.3-b13)**
 - JDK major version: **17**
 - OS: **Windows 10 Enterprise (10.0.19042) **
 - Architecture: **[e.g.: AMD64]**
 - Visual Studio 19

**More details**

**Comment by oubidar-Abderrahim** [comment] 2023-02-13 14:43
Hi, Thank you for reaching out about this, could you please share a small code example without any confidential code that we can use to reproduce this issue?

**Comment by justin-tay** [comment] 2023-03-09 08:39
I just encountered this. This was because one of my dependencies was pulling `jboss-logmanager` which was pulling `wildfly-commons` which has this bug https://github.com/wildfly/wildfly-common/issues/49 on this line https://github.com/wildfly/wildfly-common/blob/964418238a43c8fd70572b21d9462835a9820f44/src/main/java/org/wildfly/common/net/Substitutions.java#L112. Although it has since been fixed in `wildfly-common` `jboss-logmanager` is still using the version that is broken.

**Closed** 2023-03-14 15:02 UTC
Labels: bug, native-image

**Comment by wh81752** [comment] 2023-07-07 07:47
> I just encountered this. This was because one of my dependencies was pulling `jboss-logmanager` which was pulling `wildfly-commons` which has this bug [wildfly/wildfly-common#49](https://github.com/wildfly/wildfly-common/issues/49) on this line https://github.com/wildfly/wildfly-common/blob/964418238a43c8fd70572b21d9462835a9820f44/src/main/java/org/wildfly/common/net/Substitutions.java#L112. Although it has since been fixed in `wildfly-common` `jboss-logmanager` is still using the version that is broken.

Thanks for this jint. I will try it myself. I suspect something in this direction.
