### ISSUE TITLE
"Fatal error reported via JNI: JVM_LatestUserDefinedLoader called:  Unimplemented" while running JMX client native-image

### ISSUE THREAD

**Issue by aivanise** [oracle/graal#3415] opened 2021-05-17 15:15 UTC
**Describe the issue**

I'm trying to compile a native image of a simple JMX invoker which works fine in jvm but fails with Exception in thread "main" java.io.IOException: Failed to retrieve RMIServer stub: javax.naming.NoInitialContextException: Need to specify class name in environment or system property, or in an application resource file: java.naming.factory.initial

**Steps to reproduce the issue**

1. javac JmxInvoke.java
2. native-image --static --no-fallback -cp . JmxInvoke
3. ./jmxinvoke service:jmx:rmi:///jndi/rmi://swrint:30241/jmxrmi 'java.lang:type=Memory' gc

Exception in thread "main" java.io.IOException: Failed to retrieve RMIServer stub: javax.naming.NoInitialContextException: Need to specify class name in environment or system property, or in an application resource file: java.naming.factory.initial
        at javax.management.remote.rmi.RMIConnector.connect(RMIConnector.java:370)
        at javax.management.remote.JMXConnectorFactory.connect(JMXConnectorFactory.java:270)
        at javax.management.remote.JMXConnectorFactory.connect(JMXConnectorFactory.java:229)
        at JmxInvoke.main(JmxInvoke.java:7)
Caused by: javax.naming.NoInitialContextException: Need to specify class name in environment or system property, or in an application resource file: java.naming.factory.initial
        at javax.naming.spi.NamingManager.getInitialContext(NamingManager.java:702)
        at javax.naming.InitialContext.getDefaultInitCtx(InitialContext.java:305)
        at javax.naming.InitialContext.getURLOrDefaultInitCtx(InitialContext.java:342)
        at javax.naming.InitialContext.lookup(InitialContext.java:409)
        at javax.management.remote.rmi.RMIConnector.findRMIServerJNDI(RMIConnector.java:1839)
        at javax.management.remote.rmi.RMIConnector.findRMIServer(RMIConnector.java:1813)
        at javax.management.remote.rmi.RMIConnector.connect(RMIConnector.java:302)
        ... 3 more

**Describe GraalVM and your environment:**
 - GraalVM version 21.1.0
 - JDK major version: 11
 - OS: Linux CentOS 8.3.2011
 - Architecture: x86_64

**More details**

```
$ java -agentlib:native-image-agent=config-output-dir=META-INF/native-image/ -cp . JmxInvoke service:jmx:rmi:///jndi/rmi://swrint:30241/jmxrmi 'java.lang:type=Memory' gc
kroot@cjmx-builder:~\[root@cjmx-builder ~]# native-image --verbose --native-image-info -H:+AllowIncompleteClasspath --static --no-fallback -cp . JmxInvoke
Apply file:///root/META-INF/native-image/jni-config.json
Apply file:///root/META-INF/native-image/reflect-config.json
Apply file:///root/META-INF/native-image/resource-config.json
Apply file:///root/META-INF/native-image/proxy-config.json
Apply file:///root/META-INF/native-image/serialization-config.json
Executing [
/root/graalvm-ce-java11-21.1.0/bin/java \
-XX:+UseParallelGC \
-XX:+UnlockExperimentalVMOptions \
-XX:+EnableJVMCI \
-Dtruffle.TrustAllTruffleRuntimeProviders=true \
-Dtruffle.TruffleRuntime=com.oracle.truffle.api.impl.DefaultTruffleRuntime \
-Dgraalvm.ForcePolyglotInvalid=true \
-Dgraalvm.locatorDisabled=true \
-Dsubstratevm.IgnoreGraalVersionCheck=true \
--add-exports=java.base/jdk.internal.module=ALL-UNNAMED \
--add-exports=jdk.internal.vm.ci/jdk.vm.ci.aarch64=ALL-UNNAMED \
--add-exports=jdk.internal.vm.ci/jdk.vm.ci.amd64=ALL-UNNAMED \
--add-exports=jdk.internal.vm.ci/jdk.vm.ci.code.site=ALL-UNNAMED \
--add-exports=jdk.internal.vm.ci/jdk.vm.ci.code.stack=ALL-UNNAMED \
--add-exports=jdk.internal.vm.ci/jdk.vm.ci.code=ALL-UNNAMED \
--add-exports=jdk.internal.vm.ci/jdk.vm.ci.common=ALL-UNNAMED \
--add-exports=jdk.internal.vm.ci/jdk.vm.ci.hotspot.aarch64=ALL-UNNAMED \
--add-exports=jdk.internal.vm.ci/jdk.vm.ci.hotspot.amd64=ALL-UNNAMED \
--add-exports=jdk.internal.vm.ci/jdk.vm.ci.hotspot.sparc=ALL-UNNAMED \
--add-exports=jdk.internal.vm.ci/jdk.vm.ci.hotspot=ALL-UNNAMED \
--add-exports=jdk.internal.vm.ci/jdk.vm.ci.meta=ALL-UNNAMED \
--add-exports=jdk.internal.vm.ci/jdk.vm.ci.runtime=ALL-UNNAMED \
--add-exports=jdk.internal.vm.ci/jdk.vm.ci.services=ALL-UNNAMED \
--add-exports=jdk.internal.vm.ci/jdk.vm.ci.sparc=ALL-UNNAMED \
--add-opens=jdk.internal.vm.compiler/org.graalvm.compiler.debug=ALL-UNNAMED \
--add-opens=jdk.internal.vm.compiler/org.graalvm.compiler.nodes=ALL-UNNAMED \
--add-opens=jdk.unsupported/sun.reflect=ALL-UNNAMED \
--add-opens=java.base/jdk.internal.module=ALL-UNNAMED \
--add-opens=java.base/jdk.internal.ref=ALL-UNNAMED \
--add-opens=java.base/jdk.internal.reflect=ALL-UNNAMED \
--add-opens=java.base/java.io=ALL-UNNAMED \
--add-opens=java.base/java.lang=ALL-UNNAMED \
--add-opens=java.base/java.lang.reflect=ALL-UNNAMED \
--add-opens=java.base/java.lang.invoke=ALL-UNNAMED \
--add-opens=java.base/java.lang.ref=ALL-UNNAMED \
--add-opens=java.base/java.net=ALL-UNNAMED \
--add-opens=java.base/java.nio=ALL-UNNAMED \
--add-opens=java.base/java.nio.file=ALL-UNNAMED \
--add-opens=java.base/java.security=ALL-UNNAMED \
--add-opens=java.base/javax.crypto=ALL-UNNAMED \
--add-opens=java.base/java.util=ALL-UNNAMED \
--add-opens=java.base/java.util.concurrent.atomic=ALL-UNNAMED \
--add-opens=java.base/sun.security.x509=ALL-UNNAMED \
--add-opens=java.base/jdk.internal.logger=ALL-UNNAMED \
--add-opens=org.graalvm.sdk/org.graalvm.nativeimage.impl=ALL-UNNAMED \
--add-opens=org.graalvm.sdk/org.graalvm.polyglot=ALL-UNNAMED \
--add-opens=org.graalvm.truffle/com.oracle.truffle.polyglot=ALL-UNNAMED \
--add-opens=org.graalvm.truffle/com.oracle.truffle.api.impl=ALL-UNNAMED \
-XX:+UseJVMCINativeLibrary \
-Xss10m \
-Xms1g \
-Xmx6553600000 \
-Duser.country=US \
-Duser.language=en \
-Djava.awt.headless=true \
-Dorg.graalvm.version=21.1.0 \
-Dorg.graalvm.config=CE \
-Dcom.oracle.graalvm.isaot=true \
-Djava.system.class.loader=com.oracle.svm.hosted.NativeImageSystemClassLoader \
-Dawt.toolkit=sun.awt.X11.XToolkit \
-Djava.awt.graphicsenv=sun.awt.X11GraphicsEnvironment \
-Djava.awt.printerjob=sun.print.PSPrinterJob \
-Xshare:off \
--module-path \
/root/graalvm-ce-java11-21.1.0/lib/truffle/truffle-api.jar \
-Djdk.internal.lambda.disableEagerInitialization=true \
-Djdk.internal.lambda.eagerlyInitialize=false \
-Djava.lang.invoke.InnerClassLambdaMetafactory.initializeLambdas=false \
-javaagent:/root/graalvm-ce-java11-21.1.0/lib/svm/builder/svm.jar \
-cp \
/root/graalvm-ce-java11-21.1.0/lib/svm/builder/svm.jar:/root/graalvm-ce-java11-21.1.0/lib/svm/builder/objectfile.jar:/root/graalvm-ce-java11-21.1.0/lib/svm/builder/llvm-platform-specific-shadowed.jar:/root/graalvm-ce-java11-21.1.0/lib/svm/builder/svm-llvm.jar:/root/graalvm-ce-java11-21.1.0/lib/svm/builder/javacpp-shadowed.jar:/root/graalvm-ce-java11-21.1.0/lib/svm/builder/llvm-wrapper-shadowed.jar:/root/graalvm-ce-java11-21.1.0/lib/svm/builder/pointsto.jar \
'com.oracle.svm.hosted.NativeImageGeneratorRunner$JDK9Plus' \
-watchpid \
7317 \
-imagecp \
/root/graalvm-ce-java11-21.1.0/lib/svm/library-support.jar:/root \
-H:Path=/root \
-H:+DumpTargetInfo \
-H:+AllowIncompleteClasspath \
-H:+StaticExecutable \
-H:FallbackThreshold=0 \
-H:JNIConfigurationResources@file:///root/META-INF/native-image/jni-config.json=META-INF/native-image/jni-config.json \
-H:ReflectionConfigurationResources@file:///root/META-INF/native-image/reflect-config.json=META-INF/native-image/reflect-config.json \
-H:ResourceConfigurationResources@file:///root/META-INF/native-image/resource-config.json=META-INF/native-image/resource-config.json \
-H:DynamicProxyConfigurationResources@file:///root/META-INF/native-image/proxy-config.json=META-INF/native-image/proxy-config.json \
-H:SerializationConfigurationResources@file:///root/META-INF/native-image/serialization-config.json=META-INF/native-image/serialization-config.json \
-H:CLibraryPath=/root/graalvm-ce-java11-21.1.0/lib/svm/clibraries/linux-amd64 \
'-H:Class@explicit main-class=JmxInvoke' \
'-H:Name@main-class lower case as image name=jmxinvoke' \
]
[jmxinvoke:7337]    classlist:   2,143.97 ms,  0.96 GB
[jmxinvoke:7337]        (cap):     547.54 ms,  0.96 GB
WARNING: Could not resolve jdk.jmx.remote.internal.rmi.PRef for reflection configuration. Reason: java.lang.ClassNotFoundException: jdk.jmx.remote.internal.rmi.PRef.
[jmxinvoke:7337]        setup:   2,446.83 ms,  0.96 GB
# Building image for target platform: org.graalvm.nativeimage.Platform$LINUX_AMD64
# Using native toolchain:
#   Name: GNU project C and C++ compiler (gcc)
#   Vendor: redhat
#   Version: 8.3.1
#   Target architecture: x86_64
#   Path: /usr/bin/gcc
# Using CLibrary: com.oracle.svm.core.posix.linux.libc.GLibC
[jmxinvoke:7337]     (clinit):     411.05 ms,  2.60 GB
# Static libraries:
#   graalvm-ce-java11-21.1.0/lib/svm/clibraries/linux-amd64/liblibchelper.a
#   graalvm-ce-java11-21.1.0/lib/static/linux-amd64/glibc/libnet.a
#   graalvm-ce-java11-21.1.0/lib/static/linux-amd64/glibc/libextnet.a
#   graalvm-ce-java11-21.1.0/lib/static/linux-amd64/glibc/libnio.a
#   graalvm-ce-java11-21.1.0/lib/static/linux-amd64/glibc/libjava.a
#   graalvm-ce-java11-21.1.0/lib/static/linux-amd64/glibc/libfdlibm.a
#   graalvm-ce-java11-21.1.0/lib/static/linux-amd64/glibc/libzip.a
#   graalvm-ce-java11-21.1.0/lib/svm/clibraries/linux-amd64/libjvm.a
# Other libraries: pthread,dl,z,rt
[jmxinvoke:7337]   (typeflow):  14,567.08 ms,  2.60 GB
[jmxinvoke:7337]    (objects):  13,359.51 ms,  2.60 GB
[jmxinvoke:7337]   (features):     907.55 ms,  2.60 GB
[jmxinvoke:7337]     analysis:  29,787.91 ms,  2.60 GB
[jmxinvoke:7337]     universe:     871.53 ms,  2.60 GB
[jmxinvoke:7337]      (parse):   3,994.95 ms,  2.60 GB
[jmxinvoke:7337]     (inline):   4,717.92 ms,  2.95 GB
[jmxinvoke:7337]    (compile):  23,784.65 ms,  2.96 GB
[jmxinvoke:7337]      compile:  33,800.38 ms,  2.96 GB
[jmxinvoke:7337]        image:   2,943.92 ms,  2.98 GB
[jmxinvoke:7337]        write:     602.63 ms,  2.98 GB
# Printing build artifacts to: jmxinvoke.build_artifacts.txt
[jmxinvoke:7337]      [total]:  72,827.02 ms,  2.98 GB
kroot@cjmx-builder:~\[root@cjmx-builder ~]# ./jmxinvoke service:jmx:rmi:///jndi/rmi://swrint:30241/jmxrmi 'java.lang:type=Memory' gc
Fatal error reported via JNI: JVM_LatestUserDefinedLoader called:  Unimplemented

JavaFrameAnchor dump:

  Anchor 00007ffd44530fd0 LastJavaSP 00007ffd44530fb0 LastJavaIP 0000000000e1ed37
  
TopFrame info:

  TotalFrameSize in CodeInfoTable 80
  
VMThreads info:

  VMThread 00000000023a1b00  STATUS_IN_JAVA (safepoints disabled)  java.lang.Thread@0x7fdef29c8708
  
VM Thread State for current thread 00000000023a1b00:

  0 (8 bytes): com.oracle.svm.jni.JNIThreadLocalEnvironment.jniFunctions = (bytes) 
    00000000023a1b00: 00007fdef2803010
  
  8 (8 bytes): com.oracle.svm.core.graal.snippets.StackOverflowCheckImpl.stackBoundaryTL = (Word) 140725741412352  00007ffd43d3e000
  16 (4 bytes): com.oracle.svm.core.thread.Safepoint.safepointRequested = (int) 2147451469  7fff824d
  20 (4 bytes): com.oracle.svm.core.thread.VMThreads$StatusSupport.statusTL = (int) 1  00000001
  24 (32 bytes): com.oracle.svm.core.genscavenge.ThreadLocalAllocation.regularTLAB = (bytes) 
    00000000023a1b18: 00007fdef2300000 00007fdef2400000
    00000000023a1b28: 00007fdef233ec78 0000000000000000
    
  
  56 (8 bytes): com.oracle.svm.core.thread.JavaThreads.currentThread = (Object) java.lang.Thread  00007fdef29c8708
  64 (8 bytes): com.oracle.svm.core.stack.JavaFrameAnchors.lastAnchor = (Word) 140725749747664  00007ffd44530fd0
  72 (8 bytes): com.oracle.svm.core.heap.NoAllocationVerifier.openVerifiers = (Object) null
  80 (8 bytes): com.oracle.svm.core.identityhashcode.IdentityHashCodeSupport.hashCodeGeneratorTL = (Object) java.util.SplittableRandom  00007fdef2328830
  88 (8 bytes): com.oracle.svm.core.snippets.ExceptionUnwind.currentException = (Object) null
  96 (8 bytes): com.oracle.svm.core.thread.ThreadingSupportImpl.activeTimer = (Object) null
  104 (8 bytes): com.oracle.svm.graal.isolated.IsolatedCompileClient.currentClient = (Object) null
  112 (8 bytes): com.oracle.svm.graal.isolated.IsolatedCompileContext.currentContext = (Object) null
  120 (8 bytes): com.oracle.svm.jni.JNIObjectHandles.handles = (Object) com.oracle.svm.core.handles.ThreadLocalHandles  00007fdef23013c8
  128 (8 bytes): com.oracle.svm.jni.JNIThreadLocalPendingException.pendingException = (Object) null
  136 (8 bytes): com.oracle.svm.jni.JNIThreadLocalPinnedObjects.pinnedObjectsListHead = (Object) null
  144 (8 bytes): com.oracle.svm.jni.JNIThreadOwnedMonitors.ownedMonitors = (Object) null
  152 (8 bytes): com.oracle.svm.core.thread.VMThreads.IsolateTL = (Word) 140595524796416  00007fdef2500000
  160 (8 bytes): com.oracle.svm.core.thread.VMThreads.OSThreadHandleTL = (Word) 37357696  00000000023a0880
  168 (8 bytes): com.oracle.svm.core.thread.VMThreads.OSThreadIdTL = (Word) 37357696  00000000023a0880
  176 (8 bytes): com.oracle.svm.core.thread.VMThreads.nextTL = (Word) 0  0000000000000000
  184 (8 bytes): com.oracle.svm.core.thread.VMThreads.unalignedIsolateThreadMemoryTL = (Word) 37362400  00000000023a1ae0
  192 (4 bytes): com.oracle.svm.core.graal.snippets.StackOverflowCheckImpl.yellowZoneStateTL = (int) 1  00000001
  196 (4 bytes): com.oracle.svm.core.snippets.ImplicitExceptions.implicitExceptionsAreFatal = (int) 0  00000000
  200 (4 bytes): com.oracle.svm.core.thread.ThreadingSupportImpl.currentPauseDepth = (int) 0  00000000
  204 (4 bytes): com.oracle.svm.core.thread.VMThreads$ActionOnExitSafepointSupport.actionTL = (int) 0  00000000
  208 (4 bytes): com.oracle.svm.core.thread.VMThreads$ActionOnTransitionToJavaSupport.actionTL = (int) 0  00000000
  212 (4 bytes): com.oracle.svm.core.thread.VMThreads$StatusSupport.safepointsDisabledTL = (int) 1  00000001
  
VMOperation dump:

  No VMOperation in progress
  
  The 10 most recent VM operation status changes (oldest first):
    
  
Dump Counters:

  
Raw Stacktrace:

  00007ffd44530f50: 00007fdef233ec58 00000000010d4600
  00007ffd44530f60: 00000000023a1b00 000000000000000a
  00007ffd44530f70: 00000000023a1b00 00007fdef2500000
  00007ffd44530f80: 00007ffd44530fd0 0000000000e1ed37
  00007ffd44530f90: 0000000000000002 0000000001006f84
  00007ffd44530fa0: 000000000000000a 0000000000e1ed4a
  00007ffd44530fb0: 00007fdef233dfe8 000000000045629a
  00007ffd44530fc0: 00007fdef233ec58 00000001f233df18
  
Stacktrace Stage 0:

  SP 00007ffd44530f50 IP 0000000000416b46  FrameSize 80
  SP 00007ffd44530fb0 IP 0000000000e1ed37  FrameSize 64
  SP 00007ffd44530ff0 IP 0000000000e8ff21  FrameSize 64
  SP 00007ffd44531030 IP 00000000009e8877  FrameSize 80
  SP 00007ffd44531080 IP 00000000009e62a1  FrameSize 48
  SP 00007ffd445310b0 IP 00000000009ebb52  FrameSize 64
  SP 00007ffd445310f0 IP 00000000009e9b23  FrameSize 80
  SP 00007ffd44531140 IP 00000000009e9282  FrameSize 48
  SP 00007ffd44531170 IP 0000000000e81a59  FrameSize 64
  SP 00007ffd445311b0 IP 000000000063baaa  FrameSize 64
  SP 00007ffd445311f0 IP 00000000006422a6  FrameSize 64
  SP 00007ffd44531230 IP 0000000000dce004  FrameSize 32
  SP 00007ffd44531250 IP 0000000000dc94a8  FrameSize 48
  SP 00007ffd44531280 IP 0000000000dc8fb7  FrameSize 80
  SP 00007ffd445312d0 IP 0000000000dc59c9  FrameSize 160
  SP 00007ffd44531370 IP 0000000000daea40  FrameSize 32
  SP 00007ffd44531390 IP 00000000004020bb  FrameSize 64
  SP 00007ffd445313d0 IP 000000000041c6c6  FrameSize 112
  
Stacktrace Stage 1:

  SP 00007ffd44530f50 IP 0000000000416b46  com.oracle.svm.core.code.CodeInfo@0x7fdef295c200 name = image code
  SP 00007ffd44530fb0 IP 0000000000e1ed37  com.oracle.svm.core.code.CodeInfo@0x7fdef295c200 name = image code
  SP 00007ffd44530ff0 IP 0000000000e8ff21  com.oracle.svm.core.code.CodeInfo@0x7fdef295c200 name = image code
  SP 00007ffd44531030 IP 00000000009e8877  com.oracle.svm.core.code.CodeInfo@0x7fdef295c200 name = image code
  SP 00007ffd44531080 IP 00000000009e62a1  com.oracle.svm.core.code.CodeInfo@0x7fdef295c200 name = image code
  SP 00007ffd445310b0 IP 00000000009ebb52  com.oracle.svm.core.code.CodeInfo@0x7fdef295c200 name = image code
  SP 00007ffd445310f0 IP 00000000009e9b23  com.oracle.svm.core.code.CodeInfo@0x7fdef295c200 name = image code
  SP 00007ffd44531140 IP 00000000009e9282  com.oracle.svm.core.code.CodeInfo@0x7fdef295c200 name = image code
  SP 00007ffd44531170 IP 0000000000e81a59  com.oracle.svm.core.code.CodeInfo@0x7fdef295c200 name = image code
  SP 00007ffd445311b0 IP 000000000063baaa  com.oracle.svm.core.code.CodeInfo@0x7fdef295c200 name = image code
  SP 00007ffd445311f0 IP 00000000006422a6  com.oracle.svm.core.code.CodeInfo@0x7fdef295c200 name = image code
  SP 00007ffd44531230 IP 0000000000dce004  com.oracle.svm.core.code.CodeInfo@0x7fdef295c200 name = image code
  SP 00007ffd44531250 IP 0000000000dc94a8  com.oracle.svm.core.code.CodeInfo@0x7fdef295c200 name = image code
  SP 00007ffd44531280 IP 0000000000dc8fb7  com.oracle.svm.core.code.CodeInfo@0x7fdef295c200 name = image code
  SP 00007ffd445312d0 IP 0000000000dc59c9  com.oracle.svm.core.code.CodeInfo@0x7fdef295c200 name = image code
  SP 00007ffd44531370 IP 0000000000daea40  com.oracle.svm.core.code.CodeInfo@0x7fdef295c200 name = image code
  SP 00007ffd44531390 IP 00000000004020bb  com.oracle.svm.core.code.CodeInfo@0x7fdef295c200 name = image code
  SP 00007ffd445313d0 IP 000000000041c6c6  com.oracle.svm.core.code.CodeInfo@0x7fdef295c200 name = image code
  
Stacktrace Stage 2:

  SP 00007ffd44530f50 IP 0000000000416b46  [image code] com.oracle.svm.core.code.IsolateEnterStub.JNIFunctions_FatalError_dea4272cf8e20ff701a0a73f7a6d5d75e3401653(IsolateEnterStub.java:0)
  SP 00007ffd44530fb0 IP 0000000000e1ed37  [image code] jdk.internal.misc.VM.latestUserDefinedLoader0(VM.java)
  SP 00007ffd44530ff0 IP 0000000000e8ff21  [image code] jdk.internal.misc.VM.latestUserDefinedLoader(VM.java:317)
  SP 00007ffd44530ff0 IP 0000000000e8ff21  [image code] sun.rmi.server.MarshalInputStream.latestUserDefinedLoader(MarshalInputStream.java:264)
  SP 00007ffd44530ff0 IP 0000000000e8ff21  [image code] sun.rmi.server.MarshalInputStream.resolveClass(MarshalInputStream.java:198)
  SP 00007ffd44531030 IP 00000000009e8877  [image code] java.io.ObjectInputStream.readNonProxyDesc(ObjectInputStream.java:1995)
  SP 00007ffd44531080 IP 00000000009e62a1  [image code] java.io.ObjectInputStream.readClassDesc(ObjectInputStream.java:1862)
  SP 00007ffd445310b0 IP 00000000009ebb52  [image code] java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2169)
  SP 00007ffd445310f0 IP 00000000009e9b23  [image code] java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1679)
  SP 00007ffd44531140 IP 00000000009e9282  [image code] java.io.ObjectInputStream.readObject(ObjectInputStream.java:493)
  SP 00007ffd44531170 IP 0000000000e81a59  [image code] java.io.ObjectInputStream.readObject(ObjectInputStream.java:451)
  SP 00007ffd44531170 IP 0000000000e81a59  [image code] sun.rmi.registry.RegistryImpl_Stub.lookup(RegistryImpl_Stub.java:127)
  SP 00007ffd445311b0 IP 000000000063baaa  [image code] com.sun.jndi.rmi.registry.RegistryContext.lookup(RegistryContext.java:133)
  SP 00007ffd445311f0 IP 00000000006422a6  [image code] com.sun.jndi.toolkit.url.GenericURLContext.lookup(GenericURLContext.java:207)
  SP 00007ffd44531230 IP 0000000000dce004  [image code] javax.naming.InitialContext.lookup(InitialContext.java:409)
  SP 00007ffd44531250 IP 0000000000dc94a8  [image code] javax.management.remote.rmi.RMIConnector.findRMIServerJNDI(RMIConnector.java:1839)
  SP 00007ffd44531280 IP 0000000000dc8fb7  [image code] javax.management.remote.rmi.RMIConnector.findRMIServer(RMIConnector.java:1813)
  SP 00007ffd445312d0 IP 0000000000dc59c9  [image code] javax.management.remote.rmi.RMIConnector.connect(RMIConnector.java:302)
  SP 00007ffd44531370 IP 0000000000daea40  [image code] javax.management.remote.JMXConnectorFactory.connect(JMXConnectorFactory.java:270)
  SP 00007ffd44531390 IP 00000000004020bb  [image code] javax.management.remote.JMXConnectorFactory.connect(JMXConnectorFactory.java:229)
  SP 00007ffd44531390 IP 00000000004020bb  [image code] JmxInvoke.main(JmxInvoke.java:7)
  SP 00007ffd445313d0 IP 000000000041c6c6  [image code] com.oracle.svm.core.JavaMainWrapper.runCore(JavaMainWrapper.java:146)
  SP 00007ffd445313d0 IP 000000000041c6c6  [image code] com.oracle.svm.core.JavaMainWrapper.run(JavaMainWrapper.java:182)
  SP 00007ffd445313d0 IP 000000000041c6c6  [image code] com.oracle.svm.core.code.IsolateEnterStub.JavaMainWrapper_run_5087f5482cc9a6abc971913ece43acb471d2631b(IsolateEnterStub.java:0)
  
[Heap settings and statistics: 
  Supports isolates: true
  Object reference size: 8
  Incremental collections: 0
  Complete collections: 0]

[Native image heap boundaries: 
  ReadOnly Primitives: 0x7fdef2501028 .. 0x7fdef26958d8
  ReadOnly References: 0x7fdef26958e8 .. 0x7fdef2802848
  ReadOnly Relocatables: 0x7fdef2803000 .. 0x7fdef28f0af8
  Writable Primitives: 0x7fdef28f1000 .. 0x7fdef2979148
  Writable References: 0x7fdef2979158 .. 0x7fdef2c17780
  Writable Huge: 0x0 .. 0x0
  ReadOnly Huge: 0x7fdef2d00030 .. 0x7fdef307f6a8]


[Heap:
  [Young generation: 
    [Eden: 
      [edenSpace:
        aligned: 0/0 unaligned: 0/0]]
    [Survivors: 
      ]]
  [Old generation: 
    [oldFromSpace:
      aligned: 0/0 unaligned: 0/0]
    [oldToSpace:
      aligned: 0/0 unaligned: 0/0]
    ]
  [Unused:
    aligned: 0/0]]



```

**Comment by mcraj017** [comment] 2021-05-21 04:58
@aivanise please rpovide reproducer

**Comment by aivanise** [comment] 2021-05-21 07:47
here is a shell script that reproduces the issue. It assumes JAVA_JOME and PATH are set to include graalvm

```
cat<<"EOF" | > JmxInvoke.java
import javax.management.*;
import javax.management.remote.*;

public class JmxInvoke {

    public static void main(String... args) throws Exception {
        JMXConnectorFactory.connect(new JMXServiceURL(args[0]))
            .getMBeanServerConnection().invoke(new ObjectName(args[1]), args[2], new Object[]{}, new String[]{});
    }

}
EOF
cat<<"EOF"> Sleep5Seconds.java
class Sleep5Seconds {
    public static void main(String[] args) throws Exception {
      Thread.sleep(5000);
    }
}
EOF

javac JmxInvoke.java
javac Sleep5Seconds.java
# test and build a compilation path for native-image
java -Dcom.sun.management.jmxremote.port=30241 -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.ssl=false -cp . Sleep5Seconds& 
sleep 2; # wait for it to warm up
java -agentlib:native-image-agent=config-output-dir=META-INF/native-image/ -cp . JmxInvoke service:jmx:rmi:///jndi/rmi://localhost:30241/jmxrmi 'java.lang:type=Memory' gc
sleep 5
# and build a static exe
native-image -H:+AllowIncompleteClasspath --static --no-fallback  -cp . JmxInvoke
# now test
java -Dcom.sun.management.jmxremote.port=30241 -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.ssl=false -cp . Sleep5Seconds& 
sleep 2; 
./jmxinvoke service:jmx:rmi:///jndi/rmi://localhost:30241/jmxrmi 'java.lang:type=Memory' gc

```

**Comment by mcraj017** [comment] 2021-05-31 05:49
@aivanise thanks for the reproducer
We will check it out and get back to you

**Comment by mcraj017** [comment] 2021-05-31 06:53
@aivanise I dont see java.io.IOException: Failed to retrieve RMIServer stub
I only encountered: 
./jmxinvoke service:jmx:rmi:///jndi/rmi://localhost:30241/jmxrmi 'java.lang:type=Memory' gc
Fatal error reported via JNI: JVM_LatestUserDefinedLoader called:  Unimplemented
please confirm if you are only getting this error

**Comment by aivanise** [comment] 2021-05-31 07:16
Yeah, that's the error I'm getting when trying to do the assisted build. With non-assisted build, the build passes, but I'm getting the runtime error from the summary.

**Comment by mcraj017** [comment] 2021-06-01 00:57
@aivanise thanks for the reply
the title of issue specify that you are getting `javax.naming.NoInitialContextException` 
I just want to confirm that now you are only getting `Fatal error reported via JNI: JVM_LatestUserDefinedLoader called: Unimplemented`
So that we can change the title

**Comment by aivanise** [comment] 2021-06-01 13:55
yeah, go ahead

**Comment by mcraj017** [comment] 2021-06-02 01:57
@aivanise Bug has been raised internally

**Comment by christianwimmer** [comment] 2021-06-06 05:02
Looks like a duplicate of https://github.com/oracle/graal/issues/3132

**Closed by christianwimmer** 2021-06-06 05:02 UTC
Labels: bug, native-image
