### ISSUE TITLE
Runtime/Compile Error in Play Dev Mode

### ISSUE THREAD

**Issue by schmitch** [oracle/graal#488] opened 2018-06-21 13:11 UTC
Currently when running Playframework Dev Mode on a GraalVM (1.0.0-rc2) I **rarely** get the following error after multiple "compilations":

```
play.api.UnexpectedException: Unexpected exception[ExecutionError: com.google.common.util.concurrent.ExecutionError: com.google.common.util.concurrent.ExecutionError: java.lang.NoClassDefFoundError: java/lang/Boolea밽]
	at play.core.server.DevServerStart$$anon$1.reload(DevServerStart.scala:186)
	at play.core.server.DevServerStart$$anon$1.get(DevServerStart.scala:124)
	at play.core.server.AkkaHttpServer.handleRequest(AkkaHttpServer.scala:222)
	at ...
```
I also attached the full stack trace:
[graalvm_error.txt](https://github.com/oracle/graal/files/2123704/graalvm_error.txt)

Currently I guess the error happens on class loading, since play uses multiple class loaders to actually have a smooth way of reloading the application.
What's confusing is that the `java.lang.NoClassDefFoundError: java/lang/Boolea밽` always differs, but is always `java/lang/Bool`. The last characters are sometimes different.
It's also strange because it **only** happens on GraalVM not on OpenJDK, Java JDK. The error happens at least on Linux and Mac with the Enterprise edition. 

However I never tried the CE edition since it does not work on mac and this is just for development.
When running Play on Prod Mode on GraalVM CE it actually never triggers such an error. (i.e. there is on DevServerStart anyway.

The error might also be a problem in the cglib used by Guice. However I still couldn't track down the problem yet since it happens too rarely.

**Comment by mur47x111** [comment] 2018-06-21 14:52
Hi @schmitch thanks for the bug report. Could you please add `-Dgraal.Vectorization=false` to your Java command and see if the issue is still there?

**Comment by mur47x111** [comment] 2018-06-25 17:23
Hi @schmitch , is the issue gone with `-Dgraal.Vectorization=false`? If so, it is likely the same bug that I have encountered, and the bugfix will be integrated in the next release.

**Comment by schmitch** [comment] 2018-06-25 17:28
Actually I only had one day to test it.
And actually it never occurred on this day.

So I guess the issue is gone with `-Dgraal.Vectorization=false`.

**Comment by mur47x111** [comment] 2018-06-26 10:02
Please test without `-Dgraal.Vectorization=false` when the next release is available, and reopen the issue if it would occur again. Thanks

**Closed by mur47x111** 2018-06-26 10:02 UTC
