### ISSUE TITLE
[GR-44282] BeforeAnalysisAccess#registerMethodOverrideReachabilityHandler not getting invoked as expected in GraalVM 22.2

### ISSUE THREAD

**Issue by mpeddada1** [oracle/graal#5194] opened 2022-10-11 01:17 UTC
**Describe the issue**
Upgrading from GraalVM 22.1 to GraalVM 22.2 is resulting in changed behavior in reachability handlers. 

**Steps to reproduce the issue**
Reproducer: https://github.com/mpeddada1/graalvm22.2-reachability 
As seen in the reproducer, the method,  `BeforeAnalysisAccess.registerMethodOverrideReachabilityHandler()` in [ a custom `Feature` implementation](https://github.com/mpeddada1/graalvm22.2-reachability/blob/641a05b625d94e0386044af698618465a9fc4b8f/child-module/src/main/java/com/example/MyNativeImageFeature.java#L53) , doesn't get invoked.when using graalvm 22.2. This leads to classes not being registered for reflection and results in runtime errors like this:

```
Failures (1):
  JUnit Vintage:MySampleTest:testSample
    MethodSource [className = 'com.example.MySampleTest', methodName = 'testSample', methodParameterTypes = '']
    => java.lang.RuntimeException: Generated message class "com.example.MySampleClass" missing method "getName".
       com.anotherpackage.GeneratedMessage.retrieveMethod(GeneratedMessage.java:31)
       com.anotherpackage.GeneratedMessage.access$000(GeneratedMessage.java:5)
       com.anotherpackage.GeneratedMessage$MethodAccessor.<init>(GeneratedMessage.java:20)
       com.anotherpackage.GeneratedMessage$A.initializeMethodAccessor(GeneratedMessage.java:11)
       com.example.MySampleClass.invokeAccessor(MySampleClass.java:13)
       [...]
     Caused by: java.lang.NoSuchMethodException: com.example.MySampleClass.getName()
       java.lang.Class.getMethod(DynamicHub.java:2108)
       com.anotherpackage.GeneratedMessage.retrieveMethod(GeneratedMessage.java:28)
       [...]
```

However, that same method is invoked when using graal-sdk 22.1.0 and runs successfully.

**Describe GraalVM and your environment:**
 - GraalVM version (latest snapshot builds can be found [here](https://github.com/graalvm/graalvm-ce-dev-builds/releases)), or commit id if built from source: 22.2.0
 - JDK major version: 11
 - OS: Linux

**More details**
[Concurrent reachability handlers were enabled by default](https://github.com/oracle/graal/pull/4471) starting with 22.2.0 so I wonder if we're hitting some sort of a race condition?

**Workaround**:  Adding the `-H:-RunReachabilityHandlersConcurrently` parameter results in a successful build.

**Comment by fniephaus** [comment] 2022-10-12 09:20
Could you please retry with a recent dev build? 22.3 will be released this month.

**Comment by mpeddada1** [comment] 2022-10-18 18:18
Hi @fniephaus apologies for the delay and thanks for the suggestion! Using the recent dev build of 22.3 still seems to result in the same issue: 
```

Failures (1):
  JUnit Vintage:MySampleTest:testSample
    MethodSource [className = 'com.example.MySampleTest', methodName = 'testSample', methodParameterTypes = '']
    => java.lang.RuntimeException: Generated message class "com.example.MySampleClass" missing method "getName".
       com.anotherpackage.GeneratedMessage.retrieveMethod(GeneratedMessage.java:31)
       com.anotherpackage.GeneratedMessage.access$000(GeneratedMessage.java:5)
       com.anotherpackage.GeneratedMessage$MethodAccessor.<init>(GeneratedMessage.java:20)
       com.anotherpackage.GeneratedMessage$A.initializeMethodAccessor(GeneratedMessage.java:11)
       com.example.MySampleClass.invokeAccessor(MySampleClass.java:13)
       [...]
     Caused by: java.lang.NoSuchMethodException: com.example.MySampleClass.getName()
       java.base@11.0.17/java.lang.Class.getMethod(DynamicHub.java:2108)
       com.anotherpackage.GeneratedMessage.retrieveMethod(GeneratedMessage.java:28)
       [...]
```

Here is a full stacktrace that we're seeing: https://gist.github.com/mpeddada1/9989f8b8fc600d398ceb982380cf45b3

**Comment by fniephaus** [comment] 2022-10-19 08:29
What if you set `export USE_NATIVE_IMAGE_JAVA_PLATFORM_MODULE_SYSTEM=true` before running this? Maybe this has something to do with the builder running on the module path.

**Comment by fniephaus** [comment] 2022-10-19 08:32
Assigning to @cstancu since the workaround is to use `-H:-RunReachabilityHandlersConcurrently`.

**Comment by mpeddada1** [comment] 2022-10-19 20:49
Thanks again @fniephaus! That is indeed an interesting idea. Unfortunately, running `export USE_NATIVE_IMAGE_JAVA_PLATFORM_MODULE_SYSTEM=true` also results in the same failure:

```
**********VALUE of USE_NATIVE_IMAGE_JAVA_PLATFORM_MODULE_SYSTEM************
true
com.example.MySampleTest > testSample FAILED


Failures (1):
  JUnit Vintage:MySampleTest:testSample
    MethodSource [className = 'com.example.MySampleTest', methodName = 'testSample', methodParameterTypes = '']
    => java.lang.RuntimeException: Generated message class "com.example.MySampleClass" missing method "getName".
       com.anotherpackage.GeneratedMessage.retrieveMethod(GeneratedMessage.java:31)
       com.anotherpackage.GeneratedMessage.access$000(GeneratedMessage.java:5)
       com.anotherpackage.GeneratedMessage$MethodAccessor.<init>(GeneratedMessage.java:20)
       com.anotherpackage.GeneratedMessage$A.initializeMethodAccessor(GeneratedMessage.java:11)
       com.example.MySampleClass.invokeAccessor(MySampleClass.java:13)
       [...]
     Caused by: java.lang.NoSuchMethodException: com.example.MySampleClass.getName()
       java.base@11.0.17/java.lang.Class.getMethod(DynamicHub.java:2108)
       com.anotherpackage.GeneratedMessage.retrieveMethod(GeneratedMessage.java:28)
       [...]
```
For documentation purposes, I've also updated the [reproducer](https://github.com/mpeddada1/graalvm22.2-reachability) with these troubleshooting results.

**Comment by fniephaus** [comment] 2023-02-17 09:12
Thanks a lot for the reproducer. I can confirm this still happens in a current `23.0.0-dev` build and I believe we've isolated the issue and are working on a fix.

**Closed** 2023-03-09 09:07 UTC
Labels: bug, native-image
