### ISSUE TITLE
-H:+PrintAnalysisCallTree obscures actual error due to insufficient checking in final block

### ISSUE THREAD

**Issue by starksm64** [oracle/graal#878] opened 2018-12-21 20:34 UTC
If the -H:+PrintAnalysisCallTree option is provided to the native-image tool and there is an error that prevents the BigBang object from being created, the actual error ends up being obscured because there is no check that the build was far enough to actually do a call tree analysis. For example:

```shell
Scotts-iMacPro:graal-tests starksm$ $GRAALVM_HOME/bin/native-image -cp target/classes -H:LogFile=native.log -H:+LogVerbose npe.RandomPassword
Build on Server(pid: 15148, port: 50838)
[npe.randompassword:15148]    classlist:     151.39 ms
[npe.randompassword:15148]        setup:      43.92 ms
error: substitution target for npe.RawClearPasswordSub is not loaded. Use field `onlyWith` in the `TargetClass` annotation to make substitution only active when needed.
Error: Processing image build request failed
```

and when run with -H:+PrintAnalysisCallTree:

```shell
Scotts-iMacPro:graal-tests starksm$ $GRAALVM_HOME/bin/native-image -cp target/classes -H:LogFile=native.log -H:+LogVerbose -H:+PrintAnalysisCallTree npe.RandomPassword
Build on Server(pid: 15148, port: 50838)
[npe.randompassword:15148]    classlist:     155.21 ms
[npe.randompassword:15148]        setup:      44.78 ms
fatal error: java.lang.NullPointerException
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at java.util.concurrent.ForkJoinTask.getThrowableException(ForkJoinTask.java:598)
	at java.util.concurrent.ForkJoinTask.get(ForkJoinTask.java:1005)
	at com.oracle.svm.hosted.NativeImageGenerator.run(NativeImageGenerator.java:418)
	at com.oracle.svm.hosted.NativeImageGeneratorRunner.buildImage(NativeImageGeneratorRunner.java:278)
	at com.oracle.svm.hosted.NativeImageGeneratorRunner.build(NativeImageGeneratorRunner.java:375)
	at com.oracle.svm.hosted.server.NativeImageBuildServer.executeCompilation(NativeImageBuildServer.java:391)
	at com.oracle.svm.hosted.server.NativeImageBuildServer.lambda$processCommand$8(NativeImageBuildServer.java:328)
	at com.oracle.svm.hosted.server.NativeImageBuildServer.withJVMContext(NativeImageBuildServer.java:409)
	at com.oracle.svm.hosted.server.NativeImageBuildServer.processCommand(NativeImageBuildServer.java:325)
	at com.oracle.svm.hosted.server.NativeImageBuildServer.processRequest(NativeImageBuildServer.java:269)
	at com.oracle.svm.hosted.server.NativeImageBuildServer.lambda$serve$7(NativeImageBuildServer.java:229)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.NullPointerException
	at com.oracle.graal.pointsto.reports.CallTreePrinter.buildCallTree(CallTreePrinter.java:155)
	at com.oracle.graal.pointsto.reports.CallTreePrinter.print(CallTreePrinter.java:61)
	at com.oracle.svm.hosted.NativeImageGenerator.doRun(NativeImageGenerator.java:764)
	at com.oracle.svm.hosted.NativeImageGenerator.lambda$run$0(NativeImageGenerator.java:401)
	at java.util.concurrent.ForkJoinTask$AdaptedRunnableAction.exec(ForkJoinTask.java:1386)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
Error: Processing image build request failed
Scotts-iMacPro:graal-tests starksm$ 
```

The code in the finally block should validate the object required for the call tree analysis to avoid obscuring what the actual error is.

**Comment by cstancu** [comment] 2018-12-21 23:52
Thank you for your report. This is a duplicate of #845 and will be fixed by https://github.com/oracle/graal/pull/871.

**Closed by cstancu** 2018-12-21 23:52 UTC
