### ISSUE TITLE
Map like object for truffle languages

### ISSUE THREAD

**Issue by rahmanusta** [oracle/graal#580] opened 2018-08-01 06:57 UTC
I'm calling a ruby method, it has two argument filename and options. I tried to set second argument as HashMap from java side, but it looks it doesn't accept. `Unknown identifier: dup (NoMethodError)`

```ruby
  def convert_file filename, options = {}
    ::File.open(filename, 'rb') {|file| self.convert file, options }
  end
```

Do we have have map like object in graal ?

**Comment by eregon** [comment] 2018-08-01 08:46
Hello and thank you for the report.
Could you provide a full example to reproduce and analyze the issue?

`Unknown identifier: dup (NoMethodError)` means the method `dup` was called on your HashMap. But there is no `HashMap#dup`.

I would guess your `self.convert` method calls `dup` on the `options`, or calls a method that calls `dup`.
Access to a Java `Map` with `[]`/`[]=` in Ruby should work.

**Comment by rahmanusta** [comment] 2018-08-01 10:20
I'm invoking Asciidoctor.convert_file method in https://github.com/asciidoctor/asciidoctor library. Because it is a 3rd party library, I don't aim to change code. I just want to be able to set second argument from Java side. My assumption was to use Hashmap, but it doesn't work. What is the correct/proper way to set second argument from Java side ?

I call function the function like below

```
// eval asciidoctor require

Value asciidoctor = context.eval("ruby", "Asciidoctor");
Value convertFile = asciidoctor.getMember("convert_file");

Map<Object, Object> options = new HashMap<>();
options.put("to_file",true);
options.put("safe","safe");
Value execute = function.execute("/Users/usta/projects/asciidoctor-native/README.adoc", options);
```
Thank you.

**Comment by eregon** [comment] 2018-08-01 12:05
FWIW, the `dup` comes from AsciiDoctor itself:
https://github.com/asciidoctor/asciidoctor/blob/v1.5.7.1/lib/asciidoctor.rb#L1427
I found this by using the `ruby.debug` option (same as Ruby's `-d`):
```java
Context context = Context.newBuilder().allowAllAccess(true)
      .option("ruby.debug", "true").build();
```
which then prints:
```
Exception `NoMethodError' at graalvm-ce-1.0.0-rc3/jre/languages/ruby/lib/ruby/gems/2.4.0/gems/asciidoctor-1.5.7.1/lib/asciidoctor.rb:1427:in `convert' - Unknown identifier: dup
```

I think the simplest in this case would be to create an empty Ruby Hash from Java, and then `putMember()` the mappings you want in it:
```java
import org.graalvm.polyglot.*;
import java.util.HashMap;
import java.util.Map;

public class Test {
  public static void main(String[] args) {
    Context context = Context.newBuilder().allowAllAccess(true)
      .option("ruby.debug", "true").build();

    context.eval("ruby", "require 'asciidoctor'");

    Value asciidoctor = context.eval("ruby", "Asciidoctor");
    Value convertFile = asciidoctor.getMember("convert_file");

    // Map<Object, Object> options = new HashMap<>();
    Value options = context.eval("ruby", "{}");
    options.putMember("to_file", true);
    options.putMember("safe", "safe");
    System.out.println(options);

    convertFile.execute("README.adoc", options);
  }
}
```

and that doesn't fail.

But this doesn't work as intended yet, because Asciidoctor expects Symbols as the Hash's keys, not Strings, as shown by `System.out.println(options);`: `{"to_file"=>true, "safe"=>"safe"}`.
`Value#putMember()` only accepts String and is not meant for accessing dictionary keys, so we'll make our own setter:

```java
import org.graalvm.polyglot.*;
import java.util.HashMap;
import java.util.Map;

public class Test {
  public static void main(String[] args) {
    Context context = Context.newBuilder().allowAllAccess(true)
      .option("ruby.debug", "true").build();

    context.eval("ruby", "require 'asciidoctor'");

    Value asciidoctor = context.eval("ruby", "Asciidoctor");
    Value convertFile = asciidoctor.getMember("convert_file");

    Value options = context.eval("ruby", "{}");
    Value set = context.eval("ruby", "-> h, k, v { h[k.to_sym] = v }");  
    set.execute(options, "to_file", true);
    set.execute(options, "safe", "safe");
    System.out.println(options);

    convertFile.execute("README.adoc", options);
  }
}
```

And that works.

I used README.adoc from https://github.com/asciidocfx/AsciidocFX/blob/master/README.adoc.

I think that solves the issue, so I will close it, but please comment if it doesn't work for you, or open a new issue.

**Closed by eregon** 2018-08-01 12:05 UTC
Labels: ruby

**Comment by rahmanusta** [comment] 2018-08-01 12:10
Wow, great explanation! Thanks!! :)
