### ISSUE TITLE
The program compiled on Intel macOS 13 cannot run, segmentation fault.

### ISSUE THREAD

**Issue by fenginsc** [oracle/graal#6960] opened 2023-07-09 12:38 UTC
This program is very simple, but you cannot use the Graalvm Native Image default O2 optimization level on Intel macOS 13 Ventura to compile.
If you try to run the compiled program, the Segmentation Fault will be displayed.
Try to optimize the O1 level, everything is normal, or change the operating system to macOS 12 Monterey, so it is normal to use the default O2 level.
Code is as follows:
```
public static void main(String[] args) {
      Scanner scanner = new Scanner(System.in);
      while(true){
          String input = scanner.nextLine();
          System.out.println(input);
      }
}
```
```
Java version: 17.0.7+8-LTS, vendor version: Oracle GraalVM 17.0.7+8.1
Graal compiler: optimization level: 2, target machine: x86-64-v3, PGO: off
C compiler: cc (apple, x86_64, 14.0.0)
Garbage collector: Serial GC (max heap size: 80% of RAM)
```
The files in the compressed package are compiled by the default O2 optimization level on the macOS 13 Ventura, which cannot run.
[demoTest_jar.zip](https://github.com/oracle/graal/files/11995160/demoTest_jar.zip)

**Comment by fniephaus** [comment] 2023-07-09 12:51
This appears to be a duplicate of https://github.com/oracle/graal/issues/5778. Please take a look at the other ticket, it includes a workaround. We hope Apple soon helps us to resolve this.

**Comment by fenginsc** [comment] 2023-07-09 13:03
> This appears to be a duplicate of #5778. Please take a look at the other ticket, it includes a workaround. We hope Apple soon helps us to resolve this.

Thanks for your reply, but I don't think this is the same problem, because I'm using the same compiler version on macOS 12 as on macOS 13, both are C compiler: cc (apple, x86_64, 14.0.3), the difference is only the OS version, and when I change the compile level from the default -O2 to -O1 everything works fine I think it is the optimization phase that triggers some problem, and it doesn't seem to be an Apple problem.

**Comment by fniephaus** [comment] 2023-07-09 13:09
I still think this could be the same issue. You could check by downgrading your Xcode to 12.5.1 as described in the workaround section of https://github.com/oracle/graal/issues/5778. It's possible that you run into the issue less often with `-O1`. Maybe @lewurm knows more about this?

**Comment by fenginsc** [comment] 2023-07-09 13:25
The current situation is that I use the same version of command line tools on macOS 12 and macOS 13, both versions are C compiler: cc (apple, x86_64, 14.0.3).
On macOS 12 using the default -O2 level compile, compile normal, run normal, put the compiled program on macOS 13 also works fine.
On macOS 13 using the default -O2 level compile, compile normal, run error(segmentation fault.), put the compiled program on macOS 12 also run error, but when I recompiled with the -O1 level on macOS 13, everything worked fine, and when I put the compiled program on macOS 12, everything worked fine too!
I'll try downgrading xcode to 12.5.1 on macOS 13 sometime and try again, but I think it's possible that the real problem is not that simple.
thanks.

**Comment by lewurm** [comment] 2023-07-10 20:13
Thanks for your report @fenginsc.

> Thanks for your reply, but I don't think this is the same problem, because I'm using the same compiler version on macOS 12 as on macOS 13, both are C compiler: cc (apple, x86_64, 14.0.3), the difference is only the OS version, and when I change the compile level from the default -O2 to -O1 everything works fine I think it is the optimization phase that triggers some problem, and it doesn't seem to be an Apple problem.

The relevant toolchain piece is the linker (not the compiler) for the issue described in #5778.  Can you check which linker version is used on your macOS 12 and macOS 13 system? Use `ld -version_details | jq .version` to determine it.

If your linker versions _are_ the same, this would be indeed interesting.  Could you try to run native image with `-H:-DeleteLocalSymbols -H:+PreserveFramePointer`, then run the produced binary with `lldb` to obtain a back trace at the crashing site (see #5778 for some instructions) and post it here.

**Comment by lewurm** [comment] 2023-07-11 08:59
Thank you @fenginsc.  Are you building with the same GraalVM version on both machines?  With the same `JAVA_HOME` set?  The binaries export a different set of symbols, for example the macOS 13 binary does contain `_SVMIntrinsicStubsGen_calcStringAttributesUTF16Valid_7d08ca48f143f17516afa3d9a179629da6be7030` while it does not exist in the macOS 12 binary.  Do you have the same localization set on both machines? Check with `locale` on the terminal.

**Comment by lewurm** [comment] 2023-07-11 09:06
Another thing that would be interesting: Do the CPUs on both machines support the same instruction exstensions? You can check via `sysctl -a | grep machdep.cpu.features`.

If the differ, you can force the micro architecture to something like `-march=compatibility` as a native image flag.

**Comment by lewurm** [comment] 2023-07-11 09:45
When you run native image, do both print this?
```
Graal compiler: optimization level: 2, target machine: x86-64-v3, PGO: off
```


> Incidentally, when I recompiled on macOS 13 using -O1, it worked fine, using the default -O2 would not work.

The bug in #5778 is very delicate regarding code layout changes, so I'm not surprised.  And it's 100% this bug, looking at your two binaries:
```
$ nm latest_darwin_amd64_macos12/demo | grep FactoryMethodHolder_ConcurrentHashMap_constructor
0000000100034510 t _FactoryMethodHolder_ConcurrentHashMap_constructor_2afe0a04130fb4e136801f0f8e658b2dfc52f6ed_33b15af2e30873df782ab83beaba62935549fab3
0000000100034730 t _FactoryMethodHolder_ConcurrentHashMap_constructor_745c37dfcd3d4724b68b69ad024bdf180bf5480a_2e2d7042b12b26d0a86df1ba78fd1c804467b929
00000001000347d0 t _FactoryMethodHolder_ConcurrentHashMap_constructor_e6b0c8a42b8cf6025d9c17a7a8332c18e0069929_2296cc947c93fadc7d80db1f386d4b6ff0b62dc8

$ nm latest_darwin_amd64_macos13/demo | grep FactoryMethodHolder_ConcurrentHashMap_constructor
0000000100035d70 t _FactoryMethodHolder_ConcurrentHashMap_constructor_2afe0a04130fb4e136801f0f8e658b2dfc52f6ed_33b15af2e30873df782ab83beaba62935549fab3
0000000100035f50 t _FactoryMethodHolder_ConcurrentHashMap_constructor_745c37dfcd3d4724b68b69ad024bdf180bf5480a_2e2d7042b12b26d0a86df1ba78fd1c804467b929
0000000100036fd0 t _FactoryMethodHolder_ConcurrentHashMap_constructor_e6b0c8a42b8cf6025d9c17a7a8332c18e0069929_2296cc947c93fadc7d80db1f386d4b6ff0b62dc8
```

In the macOS 13 binary you see a big gap between the last two symbols. If you look there with a disassembler you see a page full of `nop` instructions, which is exactly the symptom of the ld64 bug described in #5778.

So what we are doing here is more of an acadamic exercise to figure out _why_ the same tooling behaves differently on your two different setups. I appreciate your help identifying it, but I also understand if you just want to get things done and try the suggested workaround in #5778 🙂

**Comment by fenginsc** [comment] 2023-07-11 09:55
> `When you run native image, do both print this?`
yes.

Ok, so that means it's an OS issue, anyway, let's hope it's resolved soon, thanks for your help.

**Comment by lewurm** [comment] 2023-07-11 10:07
> `When you run native image, do both print this?`
> yes.

Hmm... this is odd, are you _sure_ both print `x86-64-v3`? My guess would be that on macOS 12 it will print `x86-64`, `x86-64-v1` or `compatibility`.

I tried to determine the detected CPU features at build time like this:
```
$ lldb -- ./latest_darwin_amd64_macos12/demo
(lldb) target create "./latest_darwin_amd64_macos12/demo"
Current executable set to '/Users/lewurm/Downloads/Test/latest_darwin_amd64_macos12/demo' (x86_64).
(lldb) b checkCPUFeaturesOrExit
Breakpoint 1: where = demo`checkCPUFeaturesOrExit, address = 0x00000001005b88a0
(lldb) r
Process 31345 launched: '/Users/lewurm/Downloads/Test/latest_darwin_amd64_macos12/demo' (x86_64)
warning: libobjc.A.dylib is being read from process memory. This indicates that LLDB could not read from the host's in-memory shared cache. This will likely reduce debugging performance.

Process 31345 stopped
* thread #1, queue = 'com.apple.main-thread', stop reason = breakpoint 1.1
    frame #0: 0x00000001005b88a0 demo`checkCPUFeaturesOrExit
demo`checkCPUFeaturesOrExit:
->  0x1005b88a0 <+0>: pushq  %rbp
    0x1005b88a1 <+1>: movq   %rsp, %rbp
    0x1005b88a4 <+4>: pushq  %rbx
    0x1005b88a5 <+5>: pushq  %rax
Target 0: (demo) stopped.
(lldb) x/59b $rdi
0x100d06b40: 0xfe 0xfe 0xfe 0xff 0xfe 0xff 0xfe 0xfe
0x100d06b48: 0xff 0xff 0xff 0xff 0xff 0xff 0xff 0xff
0x100d06b50: 0xff 0xff 0xff 0xff 0xff 0xff 0xff 0xff
0x100d06b58: 0xff 0xff 0xff 0xff 0xff 0xff 0xff 0xff
0x100d06b60: 0xff 0xff 0xff 0xff 0xff 0xff 0xff 0xff
0x100d06b68: 0xff 0xff 0xff 0xff 0xff 0xff 0xff 0xff
0x100d06b70: 0xff 0xff 0xff 0xff 0xff 0xff 0xff 0xff
0x100d06b78: 0xff 0xff 0xff
```
This byte array correspons to this C struct:
https://github.com/oracle/graal/blob/be125392368c6ebbd3e5351956e2493056381495/substratevm/src/com.oracle.svm.native.libchelper/include/amd64cpufeatures.h#L28-L41
where `0xfe` is `true`. So e.g. `fSSE3` is not set.

If you do the same with the other binary:
```
$ lldb -- ./latest_darwin_amd64_macos13/demo
(lldb) target create "./latest_darwin_amd64_macos13/demo"
Current executable set to '/Users/lewurm/Downloads/Test/latest_darwin_amd64_macos13/demo' (x86_64).
(lldb) b checkCPUFeaturesOrExit
Breakpoint 1: where = demo`checkCPUFeaturesOrExit, address = 0x00000001005f4c90
(lldb) r
Process 31482 launched: '/Users/lewurm/Downloads/Test/latest_darwin_amd64_macos13/demo' (x86_64)
warning: libobjc.A.dylib is being read from process memory. This indicates that LLDB could not read from the host's in-memory shared cache. This will likely reduce debugging performance.

Process 31482 stopped
* thread #1, queue = 'com.apple.main-thread', stop reason = breakpoint 1.1
    frame #0: 0x00000001005f4c90 demo`checkCPUFeaturesOrExit
demo`checkCPUFeaturesOrExit:
->  0x1005f4c90 <+0>: pushq  %rbp
    0x1005f4c91 <+1>: movq   %rsp, %rbp
    0x1005f4c94 <+4>: pushq  %rbx
    0x1005f4c95 <+5>: pushq  %rax
Target 0: (demo) stopped.
(lldb) x/59b $rdi
0x100d46b40: 0xfe 0xfe 0xfe 0xff 0xfe 0xff 0xfe 0xfe
0x100d46b48: 0xfe 0xfe 0xff 0xfe 0xfe 0xfe 0xfe 0xff
0x100d46b50: 0xff 0xff 0xfe 0xfe 0xff 0xff 0xff 0xfe
0x100d46b58: 0xfe 0xff 0xff 0xff 0xff 0xff 0xff 0xff
0x100d46b60: 0xff 0xff 0xff 0xfe 0xff 0xff 0xff 0xff
0x100d46b68: 0xff 0xff 0xff 0xff 0xff 0xff 0xff 0xff
0x100d46b70: 0xff 0xff 0xff 0xff 0xff 0xff 0xff 0xff
0x100d46b78: 0xff 0xff 0xff
```
You see that the byte at `0x11d46b48` differs, thus `fSSE3` is detected.

**Comment by fenginsc** [comment] 2023-07-11 10:24
On macOS 12 it does show:
``` Graal compiler: optimization level: 2, target machine: x86-64-v3, PGO: off ```
It is possible that I uploaded the binary file incorrectly before, this was my mistake, I will upload a new one, please check it, thanks.
[Test.zip](https://github.com/oracle/graal/files/12013617/Test.zip)

**Comment by lewurm** [comment] 2023-07-11 10:28
> It is possible that I uploaded the binary file incorrectly before, this was my mistake, I will upload a new one, please check it, thanks.
> [Test.zip](https://github.com/oracle/graal/files/12013617/Test.zip)

Thanks again.  Unfortunately it seems that the macOS 12 binary hasn't been built with `-H:-DeleteLocalSymbols` (and potentially `-H:+PreserveFramePointer`) this time?

**Comment by fenginsc** [comment] 2023-07-11 10:32
Oh no, I forgot about it. Fix it now.
[Test2.zip](https://github.com/oracle/graal/files/12013685/Test2.zip)

**Comment by lewurm** [comment] 2023-07-11 10:42
Thanks, we are getting closer.

macOS 12 binary contains this symbol:
```
_FactoryMethodHolder_TimeZoneNames_zh_constructor_b8e1990a937bf177ce778badbad696b6206e3d02_cb33305378db346dab3e1b5a70f75d2ea1d7987c
```

while the macOS 13 binary contains:
```
_FactoryMethodHolder_TimeZoneNames_en_constructor_8f49368e45b806b46cdc245e841d7aa34b0c14c1_cedaf2bde8fb13ecd6c7d348ec8c55a91ce8d3c5
```

So the system language is configured differently on both systems I assume.  I thought `locale` would tell, but that doesn't seem the case on macOS. Can you check the output of `defaults read -g AppleLanguages` on both systems?

**Comment by fenginsc** [comment] 2023-07-11 11:25
macOS 12:
```
{
    "en-CN",
    "zh-Hans-CN"
}
```
macOS 13:
```
{
    "en-CN"
}
```
I removed it to make them consistent, after I recompiled the program.
[Test2.zip](https://github.com/oracle/graal/files/12014063/Test2.zip)

**Comment by lewurm** [comment] 2023-07-13 07:55
Thanks again!

While the binaries look _very_ similar, you are right that the macOS 12 one works properly and the macOS 13 variant suffers from the ld64 bug.  This is interesting, and I do not have a good explanation for that. Maybe it's related to `dyld` which, as far as I understand, ships with the OS and not the developer toolchain. Note that the macOS 12 binary contains those symbols:
```
[...]
0000000100d36000 d __dyld_private
[...] 
                 U dyld_stub_binder
```
while the macOS 13 binary does _not_.  I do not really know what to do with that information though 😅

**Comment by fenginsc** [comment] 2023-07-13 11:18
You're welcome, I also think it might be an OS issue, if you have time, you can reproduce the problem, and finally I hope this problem will be solved soon, thanks!

**Closed** 2023-09-20 14:03 UTC
Labels: bug, native-image
