### ISSUE TITLE
Native image creation fails from javax.sql java.sql declared type incompatibilities

### ISSUE THREAD

**Issue by jwoolston** [oracle/graal#1761] opened 2019-10-20 02:54 UTC
I have an app which uses the H2 database engine and is failing to create a native image. The command line and output are as follows:

````
graalvm-ce-19.2.1/bin/native-image --no-fallback -H:+TraceClassInitialization --report-unsupported-elements-at-runtime --allow-incomplete-classpath -H:-UseServiceLoaderFeature --initialize-at-build-time=org.h2.Driver -jar /home/jared/Work/GIT/my_app_name/daemon/build/libs/my_app_name.jar my_app_name_native

Error: Unsupported features in 6 methods
Detailed message:
Error: Field java.sql.DriverInfo.driver has declared type java.sql.Driver which is incompatible with types in state: MTypeMObject<3:[0x00000A280000916B:!S:Driver, 0x00000A3300009176:!S:Driver, 0x00000A3600009179:!S:Driver]>
Error: Field org.h2.jdbcx.JdbcConnectionPool.dataSource has declared type javax.sql.ConnectionPoolDataSource which is incompatible with types in state: 1TypeMObject<[0x000006BD00008E00:!S:JdbcDataSource]>
Error: Parameter 0 of java.sql.DriverManager.registerDriver(Driver) has declared type java.sql.Driver which is incompatible with types in state: 1TypeMObject<[0x00000A280000916B:!S:Driver]>
Call path from entry point to java.sql.DriverManager.registerDriver(Driver): 
	no path found from entry point to target method

Error: Parameter 0 of java.sql.DriverManager.registerDriver(Driver, DriverAction) has declared type java.sql.Driver which is incompatible with types in state: 1TypeMObject<[0x00000A280000916B:!S:Driver]>
Call path from entry point to java.sql.DriverManager.registerDriver(Driver, DriverAction): 
	no path found from entry point to target method

Error: Parameter 1 of java.sql.DriverInfo.<init>(Driver, DriverAction) has declared type java.sql.Driver which is incompatible with types in state: 1TypeMObject<[0x00000A280000916B:!S:Driver]>
Call path from entry point to java.sql.DriverInfo.<init>(Driver, DriverAction): 
	no path found from entry point to target method

Error: Parameter 1 of org.h2.jdbcx.JdbcConnectionPool.<init>(ConnectionPoolDataSource) has declared type javax.sql.ConnectionPoolDataSource which is incompatible with types in state: 1TypeMObject<[0x000006BD00008E00:!S:JdbcDataSource]>
Call path from entry point to org.h2.jdbcx.JdbcConnectionPool.<init>(ConnectionPoolDataSource): 
	at org.h2.jdbcx.JdbcConnectionPool.<init>(JdbcConnectionPool.java:77)
	at org.h2.jdbcx.JdbcConnectionPool.create(JdbcConnectionPool.java:112)
	at com.my_app_name.database.H2Source.<init>(H2Source.java:90)
	at com.my_app_name.database.H2Source.<init>(H2Source.java:55)
	at com.my_app_name.core.system.SystemManager.<init>(SystemManager.java:66)
	at com.my_app_name.core.system.SystemManager.getInstance(SystemManager.java:87)
	at com.my_app_name.daemon.Main.main(Main.java:107)
	at com.oracle.svm.core.JavaMainWrapper.runCore(JavaMainWrapper.java:151)
	at com.oracle.svm.core.JavaMainWrapper.run(JavaMainWrapper.java:186)
	at com.oracle.svm.core.code.IsolateEnterStub.JavaMainWrapper_run_5087f5482cc9a6abc971913ece43acb471d2631b(generated:0)

Error: Use -H:+ReportExceptionStackTraces to print stacktrace of underlying exception
Error: Image build request failed with exit status 1
```

I have looked into what is described in #727 (incomplete classpath) but the classes in question come from the runtime so I am a bit confused. I know there is some weirdness between Java 8 and Java 9 with these packages but even if I build my jar with the Graal SDK I get these issues. I am somewhat confused on what I should do next to attempt to further diagnose the issue.

**Comment by wirthi** [comment] 2024-01-24 14:36
I am closing this older ticket; Native Image has been significantly improved since this ticket was created 4 years ago.

If the problem persists on a recent version of GraalVM, feel free to reopen (ideally with a reproducer)

**Closed by wirthi** 2024-01-24 14:36 UTC
