### ISSUE TITLE
Time to think about allowing cross compiling in native-image ?

### ISSUE THREAD

**Issue by janftacnik** [oracle/graal#2757] opened 2020-08-16 18:02 UTC
**Feature request**

With Visual Studio 2019 support for ARM64 compilation (and programs to run on Windows on ARM) has been 
strongly improved. Even without having full GraalVM running on Windows on ARM it looks to make sense to
start thinking about enabling cross compilation on Windows from X64 host to ARM64 target - mostly because
it now seems to be reasonably simple task with good support for cross compilation in Visual Studio.

I made very simple experiment - I have a program consisting of one Java class.

So for standard setup:
**********************************************************************
** Visual Studio 2019 Developer Command Prompt v16.7.1
** Copyright (c) 2020 Microsoft Corporation
**********************************************************************
[vcvarsall.bat] Environment initialized for: 'x64'

I did simply
C:\Develop>native-image -cp . lpr
[lpr:516]    classlist:   2,396.28 ms,  0.96 GB
[lpr:516]        (cap):   3,677.68 ms,  0.96 GB
[lpr:516]        setup:   6,283.76 ms,  0.96 GB
[lpr:516]     (clinit):     211.91 ms,  1.70 GB
[lpr:516]   (typeflow):   9,647.58 ms,  1.70 GB
[lpr:516]    (objects):   6,263.82 ms,  1.70 GB
[lpr:516]   (features):     385.09 ms,  1.70 GB
[lpr:516]     analysis:  16,804.16 ms,  1.70 GB
[lpr:516]     universe:     485.71 ms,  1.70 GB
[lpr:516]      (parse):   2,591.59 ms,  1.70 GB
[lpr:516]     (inline):   1,792.78 ms,  1.70 GB
[lpr:516]    (compile):  12,601.66 ms,  2.33 GB
[lpr:516]      compile:  17,753.86 ms,  2.33 GB
[lpr:516]        image:   1,477.32 ms,  2.33 GB
[lpr:516]        write:     512.24 ms,  2.33 GB
[lpr:516]      [total]:  46,091.14 ms,  2.33 GB

and all was fine.

Then I prepared command line with cross compilation setup:
I have opened plain command line and used:
call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Auxiliary\Build\vcvarsamd64_arm64.bat"

**********************************************************************
** Visual Studio 2019 Developer Command Prompt v16.7.1
** Copyright (c) 2020 Microsoft Corporation
**********************************************************************
[vcvarsall.bat] Environment initialized for: 'x64_arm64'

Testing very simply:
cl
Microsoft (R) C/C++ Optimizing Compiler Version 19.27.29111 for ARM64
Copyright (C) Microsoft Corporation.  All rights reserved.

usage: cl [ option... ] filename... [ /link linkoption... ]

Now trying to use native-image gives:

C:\Develop>native-image -cp . lpr
[lpr:8876]    classlist:   3,044.79 ms,  0.96 GB
[lpr:8876]        setup:   1,106.70 ms,  0.96 GB
Error: Native-image building on Windows currently only supports target architecture: AMD64 (ARM64 unsupported)
Error: Use -H:+ReportExceptionStackTraces to print stacktrace of underlying exception
Error: Image build request failed with exit status 1

Linux native-image has support for ARM64, so code generation should not be a problem, Visual Studio
should do heavy lifting so naively one would expect that trying to enable cross compilation for this
combination - going from Intel 64bit to ARM64 bit could potentially be worth trying. It would certainly help
when one would attempt to port whole GraalVM to Windows on ARM. And knowing MacOS in ARM is comming
reasonably soon it may be worth giving ARM a liitle more attention.

**Comment by christianwimmer** [comment] 2020-08-18 03:27
Cross-compilation between architectures is generally possible, and we are working on improving the support for it.
We are also working to improve AArch64 support (at this time it is "mostly working"). Right now our focus for AArch64 is Linux, but there is actually not much code that is both OS and architecture specific.

For AArch64 support on Windows, most work will probably be necessary to implement the architecture-specific relocations for the object file writing.

Contributions in that area are of course always welcome.

**Comment by janftacnik** [comment] 2020-08-21 08:18
Hi Christian,

 

We are probably not very far from having GraalVM for Windows on Arm.

 

I did small experiment using following steps:

 

1.	Fist I have downloaded sources of GraalVM and after few trials configured development environment to be able

to compile GraalVM for standard amd64 target on Windows. It has worked (I just did mx build in compiler subdirectory) 

and the resulting distribution has worked.

2.	On  my Windows on Arm machine I have reproduced similar development environment – Visual Studio compiler, Git, mx etc.

I have modified mx very gently by recognizing combination windows-aarch64 and modified suite.py in simplest possible

way – claiming that ninja support is the same for amd64 as well as for aarch64 on windows.

3.	Microsoft has produced early release of native ARM64 Java15 sdk, and I used that as a first step on WoA, but it did not get me very far 

(see compilation_on_ar.log) because that Java  is missing JVMCI Support. All the java sdk versions with that support published by GraalVM group are 64 bit

so I had to try something else - I had to move to cross compiling.

4.	I have setup cross compilation environment on my regular Intel based Windows machine and I have forced by hand identification of platform to ARM64

In mx (just to try how far will I get, I am including mx.py). I have used sdk that I have compiled in the step 1, just to prove it was Ok. 

This time I got further (see Coss_compilation.log) but as could be expected I have failed not having prepared arm64 support for real binaries to be 

produced. Of course I am not an expert but I got the feeling it would be all doable if I would get some guidance where to look and what to

modify to eventually succeed.

 

So I would be grateful if you could just glance over my log files from compilation attempts and possibly comment on what I should

look into to move it further.

 

Cheers

 

Jan Ftacnik

**Comment by fniephaus** [comment] 2023-12-22 08:46
I hope you don't mind if we closed this as a duplicate of https://github.com/oracle/graal/issues/407. Thanks for your experiment reports. Unfortunately, neither Windows ARM support nor general cross-compilation support is currently planned for Native Image. Further experiments and contributions are, of course, always welcome!

**Closed by fniephaus** 2023-12-22 08:46 UTC
Labels: feature
