### ISSUE TITLE
native-image build fails with UnsuportedFeatureException: type is not available in this platform

### ISSUE THREAD

**Issue by mpopa-np** [oracle/graal#1931] opened 2019-12-04 13:32 UTC
trying to create a native image of a jar built with java 8
Using: graalvm-ee-java8-darwin-amd64-19.3.0
On MacOs: High Sierra 10.13.6

I see the following error:
Fatal error: com.oracle.graal.pointsto.constraints.UnsupportedFeatureException: type is not available in this platform: org.graalvm.compiler.hotspot.management.libgraal.runtime.SVMHotSpotGraalRuntimeMBean
	at com.oracle.graal.pointsto.meta.AnalysisUniverse.createType(AnalysisUniverse.java:214)
	at com.oracle.graal.pointsto.meta.AnalysisUniverse.lookupAllowUnresolved(AnalysisUniverse.java:205)
	at com.oracle.graal.pointsto.meta.AnalysisUniverse.lookup(AnalysisUniverse.java:182)
	at com.oracle.graal.pointsto.meta.AnalysisUniverse.lookup(AnalysisUniverse.java:75)
	at com.oracle.graal.pointsto.infrastructure.UniverseMetaAccess$1.apply(UniverseMetaAccess.java:52)
	at com.oracle.graal.pointsto.infrastructure.UniverseMetaAccess$1.apply(UniverseMetaAccess.java:49)
	at java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1660)
	at com.oracle.graal.pointsto.infrastructure.UniverseMetaAccess.lookupJavaType(UniverseMetaAccess.java:84)
	at com.oracle.graal.pointsto.meta.AnalysisMetaAccess.lookupJavaType(AnalysisMetaAccess.java:47)
	at com.oracle.graal.pointsto.ObjectScanner.doScan(ObjectScanner.java:337)
	at com.oracle.graal.pointsto.ObjectScanner.access$400(ObjectScanner.java:62)
	at com.oracle.graal.pointsto.ObjectScanner$3$1.run(ObjectScanner.java:414)
	at com.oracle.graal.pointsto.util.CompletionExecutor.lambda$execute$0(CompletionExecutor.java:171)
	at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1402)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
Error: Image build request failed with exit status 1
com.oracle.svm.driver.NativeImage$NativeImageError: Image build request failed with exit status 1
	at com.oracle.svm.driver.NativeImage.showError(NativeImage.java:1482)
	at com.oracle.svm.driver.NativeImage.build(NativeImage.java:1260)
	at com.oracle.svm.driver.NativeImage.performBuild(NativeImage.java:1222)
	at com.oracle.svm.driver.NativeImage.main(NativeImage.java:1181)

Attached complete log:
[native-image-log.txt](https://github.com/oracle/graal/files/3922035/native-image-log.txt)

thank you in advance

**Comment by cstancu** [comment] 2019-12-04 19:16
Duplicate of https://github.com/oracle/graal/issues/1922?

**Comment by mpopa-np** [comment] 2019-12-04 19:23
Yes, looks like it;

**Closed** 2019-12-04 19:31 UTC
