### ISSUE TITLE
[GR-38413] Add support for -XX:+ExitOnOutOfMemoryError

### ISSUE THREAD

**Issue by vsevel** [oracle/graal#4509] opened 2022-04-26 09:56 UTC
**Feature request**

**Is your feature request related to a problem? Please describe.**
When we get an `OOM`, we want the pod to restart automatically. We need the `ExitOnOutOfMemoryError` for this.

**Describe the solution you'd like.**
Support for the `ExitOnOutOfMemoryError` flag in GraalVM Native Image.

**Describe who do you think will benefit the most.**
GraalVM users.

**Describe alternatives you've considered.**
A hack is to allocate a heap that will make the memory of the container grow bigger than its limit. But that is hard to tune.

**Additional context.**
N/A

**Express whether you'd like to help contributing this feature**
If you'd like to contribute, please read the [contribution guide](https://www.graalvm.org/community/contributors/).

**Comment by dougxc** [comment] 2022-04-26 12:01
This should already work since it is a HotSpot feature and GraalVM is built on top of HotSpot. Are you able to provide a reproducer showing that it does not work?

**Comment by dougxc** [comment] 2022-04-26 19:09
Ah, you want this feature for GraalVM Native Image, not GraalVM JVM (I know this can be confusing!)

@peter-hofer is there already something like this for Native Image?

**Comment by fniephaus** [comment] 2022-04-27 06:35
I don't think this is supported yet, it certainly isn't for G1GC that comes with GraalVM EE Native Image. I'm sure @christianhaeubl knows more about this though.

I've updated the [initial issue description](https://github.com/oracle/graal/issues/4509#issue-1215704420) to make clear this is about Native Image and am tracking this internally via GR-38413.

**Comment by vsevel** [comment] 2022-04-27 07:51
thanks @fniephaus

**Comment by christianhaeubl** [comment] 2022-04-27 10:10
This feature is currently not supported by Native Image, regardless of the used garbage collector. It should be fairly simple to implement though because the HotSpot JVM only exits if an `OutOfMemoryError` is thrown by object allocation routines in the VM (see https://bugs.java.com/bugdatabase/view_bug.do?bug_id=8257790).

**Comment by zakkak** [comment] 2022-04-29 13:08
WIP PR https://github.com/oracle/graal/pull/4520

**Comment by fniephaus** [comment] 2022-05-02 11:38
This has been fixed in https://github.com/oracle/graal/pull/4520/commits/de89b2f24659419808ab0bc037f9e64199823946.

@vsevel you can test this in a few hours using the next [GraalVM dev build](https://github.com/graalvm/graalvm-ce-dev-builds/). The new feature will ship with GraalVM 22.2. Please feel free to re-open if something is not working for you.

**Closed by fniephaus** 2022-05-02 11:38 UTC
Labels: feature, native-image
