### ISSUE TITLE
UPX compression broken for Windows native images produced with 22.x

### ISSUE THREAD

**Issue by axelfontaine** [oracle/graal#4340] opened 2022-02-20 09:12 UTC
**Describe the issue**
See https://github.com/upx/upx/issues/559
And https://github.com/oracle/graal/pull/4051#issuecomment-1036002461

as originally reported by @joerg-wille

I face the exact same issue as well.

**Comment by rubyFeedback** [comment] 2022-02-20 17:08
Would be kind of cool to generate binaries for windows, from linux as such, too. :D
(For me upx works very well on linux; then again most everything in regards to compiling something works better for me on linux. Sorry for the semi-off topic pass-by comment here.)

**Comment by david-sitsky** [comment] 2022-03-29 03:27
Hi - I have been hit by this exact issue with GraalVM 22.0.0.2 Java 11 CE on Windows 10.  The [upx/upx#559](https://github.com/upx/upx/issues/559) issue describes some workarounds for changes in the GraalVM source code.  For an end-user, are there any command-line arguments to native-image which will disable the use of WindowsImageHeapProviderFeature?  Are there any other workarounds?

**Comment by david-sitsky** [comment] 2022-03-31 00:53
I can confirm using 7zip to remove the com/oracle/svm/core/windows/WindowsImageHeapProviderFeature.class entry within the  lib/svm/builder/svm.jar file fixes my issue.  It would be nice if this can be solved in the official distribution though.

**Comment by sanshengshui** [comment] 2022-08-05 14:26
I have been hit by this exact issue with GraalVM 22.1.0 Java 11 CE on Windows10.

**Comment by sebthom** [comment] 2022-08-05 14:47
We are also hitting this issue.

@pejovica @peter-hofer you developed/approved PR https://github.com/oracle/graal/pull/4051 which breaks the compatibility with  apparently any kind of exe compression as explained here https://github.com/upx/upx/issues/559#issuecomment-1032047038 would be great to get your feedback on this issue. @fernando-valdez does not seem to be active on github so I wonder why he got assigned this issue and if anyone actively developing graalvm is actually monitoring this issue.

**Comment by ArloL** [comment] 2022-10-25 17:10
Removing `WindowsImageHeapProviderFeature` does not work for 22.3.0 since the code was moved to `WindowsFeature`.

I unsuccessfully tried removing `WindowsImageHeapProvider.class` and `WindowsFeature.class`. Any other ideas?

**Comment by ikappaki** [comment] 2022-11-24 22:05
Hi @fernando-valdez,

You appear to be assigned to this issue, woudl it be possible to provide us with an indication whether this is likely to be looked at or  perhaps suggest otherwise? We are currently stuck on older graalvm versions on MS-Windows waiting for a resolution on this issue.

Thanks

**Comment by sadaaithal** [comment] 2023-11-14 23:36
@markus-oberhumer I can confirm that both `upx -1` and `upx -2` works for me. Without the flag, the compressed exe just fails with ERROR CODE 193

**Comment by theotherp** [comment] 2023-11-20 20:19
For me `upx -1` does not work (and neither does `upx -2`.

**Comment by oubidar-Abderrahim** [comment] 2024-01-16 11:01
If this issue is still relevant in the latest GraalVM versions, please create a new issue for it and follow the template provided. Thank you

**Closed by oubidar-Abderrahim** 2024-01-16 11:01 UTC
Labels: bug, native-image

**Comment by BullyWiiPlaza** [comment] 2024-01-28 14:16
> If this issue is still relevant in the latest GraalVM versions, please create a new issue for it and follow the template provided. Thank you

Hello, I used `GraalVM Runtime Environment GraalVM CE 21.0.2+13.1 (build 21.0.2+13-jvmci-23.1-b30)` from [here](https://github.com/graalvm/graalvm-ce-builds/releases/tag/jdk-21.0.2) and the issue persisted. Why do we need a new issue if this one can be re-opened?

**Comment by sean-scott-lr** [comment] 2024-02-20 19:22
I am unable to use upx with a graal native image on OSX aarch as well.
GraalVM CE 21.0.2+13.1
upx 4.1.1

echo $?
127

**Comment by sergeevabc** [comment] 2025-05-11 14:17
Hey, Oracle, there is a [solution for this issue][1] you could easily implement. It works!

[1]: https://github.com/upx/upx/issues/670#issuecomment-2869306660
