### ISSUE TITLE
[native-image] UnsatisfiedLinkError java.lang.reflect.Field.getTypeAnnotationBytes0

### ISSUE THREAD

**Issue by aclement** [oracle/graal#1685] opened 2019-09-16 18:27 UTC
I'm trying to get a spring app compiling, making great progress but hit this, not quite sure where to address it: (Graal 19.2.0)

```
java.lang.UnsatisfiedLinkError: java.lang.reflect.Field.getTypeAnnotationBytes0()[B [symbol: Java_java_lang_reflect_Field_getTypeAnnotationBytes0 or Java_java_lang_reflect_Field_getTypeAnnotationBytes0__]
	at com.oracle.svm.jni.access.JNINativeLinkage.getOrFindEntryPoint(JNINativeLinkage.java:145)
	at com.oracle.svm.jni.JNIGeneratedMethodSupport.nativeCallAddress(JNIGeneratedMethodSupport.java:57)
	at java.lang.reflect.Field.getTypeAnnotationBytes0(Field.java)
	at java.lang.reflect.Field.getAnnotatedType(Field.java:1170)
	at org.hibernate.validator.internal.metadata.provider.AnnotationMetaDataProvider.findCascadingMetaData(AnnotationMetaDataProvider.java:618)
```
I've tried fiddling with entries in reflect config and in jni config but it doesn't seem to make any difference. How should I address it? thanks.

**Comment by dsyer** [comment] 2019-09-19 11:19
You can get the same error (same code path) trivially like this:

```java
public class Fields {
	public static String field = "HI";
	public static void main(String[] args) throws Exception {
		new Fields().run();
	}
	private void run() throws Exception {
		System.err.println(Fields.class.getField("field").getAnnotatedType().getType());
	}
}
```

```
$ native-image --report-unsupported-elements-at-runtime --no-fallback -H:+ReportExceptionStackTraces -H:Name=fields -cp target/classes/ Fields
$  ./fields 
Exception in thread "main" java.lang.UnsatisfiedLinkError: java.lang.reflect.Field.getTypeAnnotationBytes0()[B [symbol: Java_java_lang_reflect_Field_getTypeAnnotationBytes0 or Java_java_lang_reflect_Field_getTypeAnnotationBytes0__]
	at com.oracle.svm.jni.access.JNINativeLinkage.getOrFindEntryPoint(JNINativeLinkage.java:145)
	at com.oracle.svm.jni.JNIGeneratedMethodSupport.nativeCallAddress(JNIGeneratedMethodSupport.java:57)
	at java.lang.reflect.Field.getTypeAnnotationBytes0(Field.java)
	at java.lang.reflect.Field.getAnnotatedType(Field.java:1170)
	at Fields.run(Fields.java:10)
	at Fields.main(Fields.java:6)
```

**Comment by cstancu** [comment] 2019-09-19 11:46
The problem is that the native method `Field.getTypeAnnotationBytes0()` is missing. The proper fix is to add a substitution for `Field.getAnnotatedType()`, the only caller of `Field.getTypeAnnotationBytes0()`. I will push a fix for it soon.

(@dsyer in your example the `fields.json` is not needed, the analysis can infer that field as being reflectively accessed since the class and field name parameters are constant in `Fields.class.getField("field")`).

**Comment by cstancu** [comment] 2019-09-21 09:11
Fixed by https://github.com/oracle/graal/commit/fa58e36e0b8337b5e9d9dcc136d60095da3d90a8 which will be part of the 19.3.0 release.

**Closed by cstancu** 2019-09-21 09:11 UTC
Labels: native-image
