### ISSUE TITLE
Thread.currentThread().getContextClassLoader() returns null in Windows image

### ISSUE THREAD

**Issue by borkdude** [oracle/graal#1287] opened 2019-05-14 15:21 UTC
My compiled native image for Windows fails with a `NullPointerException`. The `null` is returned from a call to a library which basically does:

```
Thread.currentThread().getContextClassLoader()
```

This returns `null` in the Windows image, but in the linux and MacOS images it returns a non-null object.

The specific line where the error happens is:
https://github.com/clojure/clojure/blob/master/src/clj/clojure/java/io.clj#L450

**Comment by borkdude** [comment] 2019-05-14 15:26
Might be related to #1281 ?

**Comment by pejovica** [comment] 2020-04-30 11:39
@borkdude Thanks for the report. It was probably related to #1281, and since I can't reproduce it anymore, I'll close it as resolved.

**Closed by pejovica** 2020-04-30 11:39 UTC
Labels: bug, native-image
