### ISSUE TITLE
native-image does not populate GSS Oid mechanisms

### ISSUE THREAD

**Issue by avimalka** [oracle/graal#4700] opened 2022-07-05 08:56 UTC
When building with native-image GSSManager does not detect any Oid .
It seems like GSSManager does not have any Provider populated at all.

How to reproduce:
`Sample.java`
-------------
```
import org.ietf.jgss.*;

public class Sample {
  public static void main(String[] args) throws org.ietf.jgss.GSSException {
  GSSManager gssManager = GSSManager.getInstance();
  gssManager.createName("AAA", GSSName.NT_USER_NAME);
  }
}
```
-------------
javac Sample.java
java -agentlib:native-image-agent=config-output-dir=META-INF/native-image Sample
native-image --no-fallback Sample

Tested with:
GraalVM CE 22.1.0 Java 17

Stacktrace (for the native executable)
Exception in thread "main" GSSException: Unsupported mechanism requested: 1.2.840.113554.1.2.2
        at sun.security.jgss.ProviderList.getMechFactory(ProviderList.java:199)
        at sun.security.jgss.ProviderList.getMechFactory(ProviderList.java:166)
        at sun.security.jgss.GSSManagerImpl.getNameElement(GSSManagerImpl.java:183)
        at sun.security.jgss.GSSNameImpl.getElement(GSSNameImpl.java:469)
        at sun.security.jgss.GSSNameImpl.init(GSSNameImpl.java:202)
        at sun.security.jgss.GSSNameImpl.<init>(GSSNameImpl.java:171)
        at sun.security.jgss.GSSNameImpl.<init>(GSSNameImpl.java:152)
        at sun.security.jgss.GSSManagerImpl.createName(GSSManagerImpl.java:109)
        at Sample.main(Sample.java:6)

**Comment by oubidar-Abderrahim** [comment] 2022-07-19 15:57
Hi, Thank you for reporting this, could you please provide a complete example to reproduce? I'm not familiar with GSSManager

**Comment by avimalka** [comment] 2022-07-31 10:57
Hi.

It's related to Kerberos ticket authentication, So it will be very difficult to reproduce the whole environment .

I noticed that there is issue #2745 which was resolved recently which describes similar issue, But looking at version 22.2.0 I still have the same issue.
Any idea if the fix is part of 22.2 ?

**Comment by oubidar-Abderrahim** [comment] 2022-08-16 14:03
That fix was part of 22.2

**Comment by louis2845** [comment] 2023-02-09 21:57
Is this bug still being worked on? This is still a bug for me in 22.3.1

**Comment by louis2845** [comment] 2023-02-14 13:38
The attached code should recreate the problem exactly. Is there anything else you'd like me to include to help diagnose the problem?

**Comment by oubidar-Abderrahim** [comment] 2023-02-15 14:29
We'll continue the discussion in #5950 to keep 1 thread per issue

**Comment by oubidar-Abderrahim** [comment] 2023-02-15 14:29
duplicate of #5950

**Closed by oubidar-Abderrahim** 2023-02-15 14:29 UTC
Labels: bug, native-image
