### ISSUE TITLE
Debug symbols have wrong line numbers in native image

### ISSUE THREAD

**Issue by dsyer** [oracle/graal#2550] opened 2020-06-08 10:53 UTC
```
$ gdb commandlinerunner
...
(gdb) b CLR.java:17
No line 17 in file "CLR.java".
```

Line 17 is in the source file, and the debug information if in the binary as well (we checked with `objdump`).

I can set a breakpoint with a function name instead of line number:

```
(gdb) b CLR.java:com.example.commandlinerunner.CLR::run(java.lang.String[])(void) 
Breakpoint 1 at 0xdc0e0
```

but when the program stops it reports the wrong line number:

```
Thread 1 "commandlinerunn" hit Breakpoint 1, 0x00005555556300e0 in com.example.commandlinerunner.CLR::run(java.lang.String[])(void) () at com/example/commandlinerunner/CLR.java:7
7	import org.springframework.boot.SpringApplication;
(gdb)

(Should be line 17.)
```

**Comment by adinn** [comment] 2020-06-08 13:05
Hi Dave,

Thanks for reporting this. there are actually a few things that were going wrong here. I'll take them in turn.

1) The line number issue appears to be [a known problem](https://github.com/oracle/graal/issues/2431) that manifests in gdb 9.x versions. I tried debugging the binary using a gdb8 build and that version of gdb finds the correct line numbers. This [bug has been fixed](https://github.com/oracle/graal/pull/2433) in the main tree but it looks like the fix did not get into 20.1.

So, debugging with gdb 9.x should work ok in the next release.

2) The jdk sources were not found when you tried building with jdk8. That's another thing that has been fixed in the main repo but does not appear to have made it into into the 20.1 release. The problem is that for jdk8 the src.zip file is being looked up using System property java.home to locate the base dir. Unfortunately, with JDK8 java.home is set to $JAVA_HOME/jre while the src.zip file is actually in $JAVA_HOME/src.zip.

So, once again this should be workign correctly in the next release.

3) Sources were not found for any of the SubstrateVM classes. The debug info code assumes that for every substrate jar in the classpath (like svm.jar or pointsto.jar) it will find a corresponding source zip (like svm.src.zip or pointsto.src.zip). That works with a source build but it's not so for the current release.

I'll raise a separate issue to see if we can do something about this.

4) The source for the application were not being found. There are two reasons for that.

4.1) For the local app under test the script runs in dir target/native-image and copies the classes built by maven from target/classes into target/native-image/BOOT-INF/classes. The latter is the location added to the classpath. Now if the debug info code sees a path entry ending in target classes or, failing that, classes it looks for a parallel src dir to find the sources. Iy will use src/main/java or src/java or just src in that order. So, if the script had added target/classes as the classpath the app sources would have been found in src/main/java. However, instead it is looking below target/native-image/BOOT-INF and since target/native-image/BOOT-INF/src does not exist the debug info code does not find any app sources.

As we identified in or slack conversation you can fix this by pointing the script at the source tree root -H:DebugInfoSourceSearchPath=../../src/main/java

4.2) The script also adds a suite of Spring jars and other jars to the classpath that have been copied into in target/native-image/BOOT-INF/lib e.g. spring-aop-5.2.6.RELEASE.jar, spring-beans-5.2.6.RELEASE.jar, spring-graalvm-native-0.7.0.BUILD-SNAPSHOT.jar etc.

In this case the debug info code tries to resolve sources for these jars by looking for a correpsondingly named sources jar e.g. spring-aop-5.2.6.RELEASE-sources.jar, spring-beans-5.2.6.RELEASE-sources.jar, spring-graalvm-native-0.7.0.BUILD-SNAPSHOT-sources.jar, etc. So, even when sources for the app classes CLR and CommandlinerunnerApplication have been found the sources for Spring code they call into still cannot be found. If this compiel and build process had been done under maen then, of course, the jars woudl ahve come fro the local .m2/repository tree and it woudl be easy to download the corresponding source jars right next to them. This can be fixed either by A) ensuring the code that populates the lib dir also populates it with he associated sourec jars or B) adding an -H:DebugInfoSourceSearchPath option for each jar in target/native-image/BOOT-INF/lib that points to the corresponding source jar.

So, in both these cases the problem is that the dbeug info code is not able to locate source code and the build process needs to be updated to ensure they are available and/or can be located.

Finally, thanks very much for trying to get this to work and helping me identify the problems. I'll post another comment to let you know when I have raised the issue about shipping SubstartevM source zips.

**Comment by adinn** [comment] 2020-06-08 13:19
Hi Dave,

I've opened this issue #2551 to address making Graal class .src.zip files available.

I'll close this issue as there is not really anything else I can do from the Graal side that has not already been done.

**Closed** 2020-09-24 01:00 UTC
Labels: bug, native-image

**Comment by cstancu** [comment] 2020-09-24 01:01
(@adinn I closed this assuming that was your intention. I assigned #2551 to @gilles-duboscq )

**Comment by adinn** [comment] 2020-09-24 08:21
@cstancu Yes thanks.
