### ISSUE TITLE
[native-image] Use of Graphics fails

### ISSUE THREAD

**Issue by fellmann** [oracle/graal#1163] opened 2019-04-14 13:37 UTC
Minimum Example1.java:

```java
import java.awt.Graphics;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;

import javax.imageio.ImageIO;

public class Example1 {
	public static void main(String[] args) throws IOException {
		BufferedImage bufferedImage = new BufferedImage(200, 200, BufferedImage.TYPE_INT_ARGB);
		Graphics graphics = bufferedImage.getGraphics();
		graphics.drawString("test", 100, 100);
		graphics.dispose();
		ImageIO.write(bufferedImage, "PNG", new File("test.png"));
	}
}
```

The code can be executued with GraalVM: `sudo docker run -v $(pwd):/work -w /work oracle/graalvm-ce:1.0.0-rc15 sh -c "javac Example1.java && java Example1"`

But it is not working as Native Image: `sudo docker run -v $(pwd):/work -w /work oracle/graalvm-ce:1.0.0-rc15 sh -c "native-image Example1 && ./example1"`

Error:
```
Exception in thread "main" java.lang.Error: Could not find class: null
	at java.awt.GraphicsEnvironment.createGE(GraphicsEnvironment.java:117)
	at java.awt.GraphicsEnvironment.getLocalGraphicsEnvironment(GraphicsEnvironment.java:82)
	at java.awt.image.BufferedImage.createGraphics(BufferedImage.java:1181)
	at java.awt.image.BufferedImage.getGraphics(BufferedImage.java:1170)
	at Example1.main(Example1.java:11)

```

**Comment by DougTidwell** [comment] 2019-06-13 12:48
I'm having the same problem...works great in a JAR, fails spectacularly as a native image. I'm building the native image via Quarkus, so I'm using graalvm-ce-1.0.0-rc16. When I invoke my code, I get this error: 

UT005023: Exception handling request to /overlayImage: org.jboss.resteasy.spi.UnhandledException: java.lang.UnsupportedOperationException: Not implemented yet for GraalVM native images

After a relatively long stack trace, I get this more specific message: 

Caused by: java.lang.UnsupportedOperationException: Not implemented yet for GraalVM native images 
  at javax.imageio.ImageIO.read(ImageIO.java:133)
  at com.redhat.coderland.ImageOverlay.incomingImage(ImageOverlay.java:49)

May or may not be relevant: The call that fails isn't accessing the file system, it's trying to create an image from a base64 string passed in to the method. Here's the line that fails: 

      BufferedImage baseImage =
          ImageIO.read(new ByteArrayInputStream
                       (Base64.getDecoder().decode(imageData)));

Hope this sheds some light on the problem.

**Comment by rsvoboda** [comment] 2019-10-08 15:03
@cstancu any plans for java.awt.Graphics support in Substrate VM ?

I hit this problem when playing with JFreeChart and JFreeSVG in native mode using Quarkus.
https://github.com/rsvoboda/rsvoboda-playground/tree/master/jfreesvg/jfreesvg-quarkus

**Comment by sherl0cks** [comment] 2020-01-16 18:04
@cstancu bumping this. If there are no plans, it would be good to for the community to begin coalescing around an alternative.

**Comment by NO-ob** [comment] 2020-02-03 13:58
Not sure if it's exactly the same thing but I had an issue in my program not being able to write files after making a native image
```
    public void writeImage(File imageFile, Image fullImage) {
        this.fullImage = fullImage;
        try {
            BufferedImage image = ImageIO.read(new URL(item.getFileURL()));
            ImageIO.write(image, item.getFileURL().substring(item.getFileURL().lastIndexOf(".")+1),imageFile);

        } catch (IOException e){
            System.out.println("ImageWindowController::saveImage");
            System.out.println("\n Failed to Write File \n" + item.getFileURL().substring(item.getFileURL().lastIndexOf("/")+1) + "\n");
        }
    }
```


```
Caused by: java.lang.UnsatisfiedLinkError: com.sun.imageio.plugins.jpeg.JPEGImageReader.initJPEGImageReader()J [symbol: Java_com_sun_imageio_plugins_jpeg_JPEGImageReader_initJPEGImageReader or Java_com_sun_imageio_plugins_jpeg_JPEGImageReader_initJPEGImageReader__]
        at com.oracle.svm.jni.access.JNINativeLinkage.getOrFindEntryPoint(JNINativeLinkage.java:145)
        at com.oracle.svm.jni.JNIGeneratedMethodSupport.nativeCallAddress(JNIGeneratedMethodSupport.java:57)
        at com.sun.imageio.plugins.jpeg.JPEGImageReader.initJPEGImageReader(JPEGImageReader.java)
        at com.sun.imageio.plugins.jpeg.JPEGImageReader.<init>(JPEGImageReader.java:232)
        at com.sun.imageio.plugins.jpeg.JPEGImageReaderSpi.createReaderInstance(JPEGImageReaderSpi.java:85)
        at javax.imageio.spi.ImageReaderSpi.createReaderInstance(ImageReaderSpi.java:320)
        at javax.imageio.ImageIO$ImageReaderIterator.next(ImageIO.java:532)
        at javax.imageio.ImageIO$ImageReaderIterator.next(ImageIO.java:516)
        at javax.imageio.ImageIO.read(ImageIO.java:1463)
        at javax.imageio.ImageIO.read(ImageIO.java:1420)
        at loliSnatcher.ImageWriter.writeImage(ImageWriter.java:25)
        at loliSnatcher.ImageWindowController.saveImage(ImageWindowController.java:102)

```

I managed to fix it by adding 
```
        <dependency>
            <groupId>com.github.jai-imageio</groupId>
            <artifactId>jai-imageio-core</artifactId>
            <version>1.4.0</version>
        </dependency>
```
as a maven dependency

**Comment by NO-ob** [comment] 2020-02-03 15:08
Also bumping everything in my application works when built for native except the ability to save images

**Comment by sherl0cks** [comment] 2020-02-03 15:28
I’m using https://commons.apache.org/proper/commons-imaging/ as a replacement which so far works just fine in a native Linux executable.

**Comment by NO-ob** [comment] 2020-02-03 20:05
Just incase anyone wants to write iamges from a url to a file I managed to use this instead of Imageio        
``` 
try {
            InputStream initialStream = new URL(item.getFileURL()).openStream();
            OutputStream outStream = new FileOutputStream(imageFile);
            byte[] buffer = new byte[8 * 1024];
            int bytesRead;
            while ((bytesRead = initialStream.read(buffer)) != -1) {
                outStream.write(buffer, 0, bytesRead);
            }
            initialStream.close();
            outStream.flush();
            outStream.close();
        } catch (IOException e){
            e.printStackTrace();
        }
```
This seems to work better too since it works with more filetypes and saves gif/video properly

**Comment by smil2k** [comment] 2020-03-25 08:41
> I’m using https://commons.apache.org/proper/commons-imaging/ as a replacement which so far works just fine in a native Linux executable.

How do you get the imagedata without using bufferedimage?

Can you post some code here?

**Comment by sherl0cks** [comment] 2020-03-25 16:23
@smil2k take a look at https://commons.apache.org/proper/commons-imaging/sampleusage.html. You only replace `FileIO` which has native extensions to each platform (e.g. Linux vs Windows). `BufferedImage` works as normal.

**Comment by SetoKaiba** [comment] 2020-06-03 05:16
Hi. Is there any alternative to Graphics2D? The library that I'm using for captcha is using it. Thank you.

**Comment by SetoKaiba** [comment] 2020-06-03 10:50
Hi. When will this feature be added? I don't have a way to draw an image as the captcha code without Graphics. And it seems that there's no alternative. @cstancu

**Comment by smil2k** [comment] 2020-06-04 12:51
@sherl0cks: Can you send some example code which compiles with graal into native image and uses buffered images? For me it did not, first I needed to provide the color profiles, then it was stopped somewhere again with "not implemented", thrown at runtime!

**Comment by sherl0cks** [comment] 2020-06-04 16:07
I no longer have code on this, my team moved to python for image manipulation. My suspicion is that your not implemented is related to ImageIO, not buffered images, but I'm not in a position to help at this time.

**Comment by sherl0cks** [comment] 2020-10-13 23:58
@cstancu I'm looking at some code again that needs `ImageIO` in graal. Any way to support you and help get this feature built?

**Comment by sherl0cks** [comment] 2020-10-14 22:33
@vjovanov Any thoughts on how we may collaborate here?

**Comment by vjovanov** [comment] 2020-10-24 23:55
20.3 will include AWT and Swing that work on JDK 11. Please try it out in a few days on the master branch or wait for 20.3 release.

**Comment by IvanLuchkin** [comment] 2020-11-02 15:25
@vjovanov This is great news but what about javax.imageio.ImageIO?

**Comment by jerboaa** [comment] 2020-11-26 13:19
At revision c92adba1183a11ab75bdb2ab437a79502a66f565 of graal master I'm getting (producing the native image works) the following trace on the initial ImageIO example from the reporter:

```
$ native-image Example1 graal-issue-1163
[graal-issue-1163:22214]    classlist:   1,789.06 ms,  0.96 GB
[graal-issue-1163:22214]        (cap):     472.43 ms,  0.96 GB
[graal-issue-1163:22214]        setup:   2,065.96 ms,  0.96 GB
[graal-issue-1163:22214]     (clinit):     449.75 ms,  2.29 GB
[graal-issue-1163:22214]   (typeflow):   9,233.10 ms,  2.29 GB
[graal-issue-1163:22214]    (objects):   9,714.72 ms,  2.29 GB
[graal-issue-1163:22214]   (features):     590.63 ms,  2.29 GB
[graal-issue-1163:22214]     analysis:  20,385.93 ms,  2.29 GB
[graal-issue-1163:22214]     universe:     588.62 ms,  2.29 GB
[graal-issue-1163:22214]      (parse):   2,749.90 ms,  2.29 GB
[graal-issue-1163:22214]     (inline):   3,021.43 ms,  2.30 GB
[graal-issue-1163:22214]    (compile):  14,004.08 ms,  3.29 GB
[graal-issue-1163:22214]      compile:  20,759.73 ms,  3.29 GB
[graal-issue-1163:22214]        image:   2,236.85 ms,  4.74 GB
[graal-issue-1163:22214]        write:     400.21 ms,  4.74 GB
[graal-issue-1163:22214]      [total]:  48,410.97 ms,  4.74 GB
$ ./graal-issue-1163 
Exception in thread "main" java.lang.NoSuchFieldError: java.awt.image.ColorModel.pData
	at com.oracle.svm.jni.functions.JNIFunctions$Support.getFieldID(JNIFunctions.java:1106)
	at com.oracle.svm.jni.functions.JNIFunctions.GetFieldID(JNIFunctions.java:408)
	at java.awt.image.ColorModel.initIDs(ColorModel.java)
	at java.awt.image.ColorModel.<clinit>(ColorModel.java:220)
	at com.oracle.svm.core.classinitialization.ClassInitializationInfo.invokeClassInitializer(ClassInitializationInfo.java:351)
	at com.oracle.svm.core.classinitialization.ClassInitializationInfo.initialize(ClassInitializationInfo.java:271)
	at java.awt.image.BufferedImage.<clinit>(BufferedImage.java:287)
	at com.oracle.svm.core.classinitialization.ClassInitializationInfo.invokeClassInitializer(ClassInitializationInfo.java:351)
	at com.oracle.svm.core.classinitialization.ClassInitializationInfo.initialize(ClassInitializationInfo.java:271)
	at Example1.main(Example1.java:10)
```

So there is still work left to do for ImageIO to work.

**Comment by vjovanov** [comment] 2020-11-26 14:51
Have you generated the config first with an agent? AWT is still not supported without configuration.

**Comment by jerboaa** [comment] 2020-11-26 14:56
> Have you generated the config first with an agent? AWT is still not supported without configuration.

I have not. Let me try that now.

**Comment by jerboaa** [comment] 2020-11-26 19:55
OK that seems to work for png images illustrated in `Example1.java`:

```
$ rm -rf META-INF/native-image/* && java -agentlib:native-image-agent=config-output-dir=META-INF/native-image Example1
$ native-image Example1 graal-issue-1163 
[graal-issue-1163:55973]    classlist:   1,677.60 ms,  0.96 GB
[graal-issue-1163:55973]        (cap):     460.19 ms,  0.96 GB
[graal-issue-1163:55973]        setup:   1,930.53 ms,  0.96 GB
[graal-issue-1163:55973]     (clinit):     465.25 ms,  2.24 GB
[graal-issue-1163:55973]   (typeflow):  11,971.34 ms,  2.24 GB
[graal-issue-1163:55973]    (objects):  12,522.57 ms,  2.24 GB
[graal-issue-1163:55973]   (features):     900.19 ms,  2.24 GB
[graal-issue-1163:55973]     analysis:  26,571.84 ms,  2.24 GB
[graal-issue-1163:55973]     universe:     822.20 ms,  2.24 GB
[graal-issue-1163:55973]      (parse):   4,000.64 ms,  2.27 GB
[graal-issue-1163:55973]     (inline):  10,430.50 ms,  2.91 GB
[graal-issue-1163:55973]    (compile):  25,809.22 ms,  3.60 GB
[graal-issue-1163:55973]      compile:  41,916.14 ms,  3.60 GB
[graal-issue-1163:55973]        image:   3,146.05 ms,  3.61 GB
[graal-issue-1163:55973]        write:     512.69 ms,  3.61 GB
[graal-issue-1163:55973]      [total]:  76,750.03 ms,  3.61 GB
$ ./graal-issue-1163 
$ ls test.png 
test.png
```

**Comment by vjovanov** [comment] 2020-11-26 20:39
Can we close the issue?

**Closed by vjovanov** 2020-11-26 20:39 UTC
Labels: native-image

**Comment by smil2k** [comment] 2020-11-26 21:27
@jerboaa: for the record, could you tell me how did you created the "config with an agent" for graalvm?

**Comment by vjovanov** [comment] 2020-11-26 21:29
We have documentation on that: 

https://github.com/oracle/graal/blob/master/substratevm/BuildConfiguration.md

**Comment by jerboaa** [comment] 2020-11-27 09:08
@smil2k See https://github.com/oracle/graal/issues/1163#issuecomment-734459532 The `-agentlib:native-image-agent[...]` part generates files in `META-INF/native-image` which then the `native-image` invocation picks up. Consider also adding `--verbose` so as to see how this config is being picked up.

**Comment by jerboaa** [comment] 2020-11-27 19:45
@vjovanov One small issue left. See https://github.com/oracle/graal/issues/3031

**Comment by dilipdhankecha2530** [comment] 2022-12-17 04:56
```
  .   ____          _            __ _ _
 /\\ / ___'_ __ _ _(_)_ __  __ _ \ \ \ \
( ( )\___ | '_ | '_| | '_ \/ _` | \ \ \ \
 \\/  ___)| |_)| | | | | || (_| |  ) ) ) )
  '  |____| .__|_| |_|_| |_\__, | / / / /
 =========|_|==============|___/=/_/_/_/
 :: Spring Boot ::                (v3.0.0)

2022-12-17T00:42:33.826+05:30  INFO 10967 --- [           main] com.example.demo.DemoApplication         : Starting AOT-processed DemoApplication using Java 17.0.5 with PID 10967 (/home/dilip/Desktop/demo/build/native/nativeCompile/demo started by dilip in /home/dilip/Desktop/demo)
2022-12-17T00:42:33.826+05:30  INFO 10967 --- [           main] com.example.demo.DemoApplication         : No active profile set, falling back to 1 default profile: "default"
2022-12-17T00:42:33.832+05:30  INFO 10967 --- [           main] com.example.demo.DemoApplication         : Started DemoApplication in 0.016 seconds (process running for 0.019)
Exception in thread "main" java.lang.NoSuchFieldError: java.awt.image.ColorModel.pData
	at org.graalvm.nativeimage.builder/com.oracle.svm.core.jni.functions.JNIFunctions$Support.getFieldID(JNIFunctions.java:1271)
	at org.graalvm.nativeimage.builder/com.oracle.svm.core.jni.functions.JNIFunctions.GetFieldID(JNIFunctions.java:425)
	at java.desktop@17.0.5/java.awt.image.ColorModel.initIDs(ColorModel.java)
	at java.desktop@17.0.5/java.awt.image.ColorModel.<clinit>(ColorModel.java:221)
	at java.desktop@17.0.5/java.awt.image.Raster.<clinit>(Raster.java:172)
	at org.apache.pdfbox.pdmodel.PDDocument.<clinit>(PDDocument.java:107)
	at com.example.demo.DemoApplication.main(DemoApplication.java:20
```
	
While creating a native build with spring 3.0 at that time AWT has not supported any idea or any suggestion for to achieve this issue.

You can refer to this issue as well https://github.com/spring-projects/spring-framework/issues/29704.
