### ISSUE TITLE
rebuild-images custom native-image args are overridden by macros

### ISSUE THREAD

**Issue by Taig** [oracle/graal#2717] opened 2020-07-28 09:41 UTC
`rebuild-images [custom native-image args]...` are being overridden, e.g. when running `rebuild-images --verbose ruby -H:-DetectUserDirectoriesInImageHeap` the verbose output shows the command `native-image -H:-DetectUserDirectoriesInImageHeap --no-server --macro:truffleruby-launcher`. Adding a `--verbose` flag to this reveals that the actual arguments passed to `native-image` are ordered like this:

```
-H:-DetectUserDirectoriesInImageHeap \
...
-H:+DetectUserDirectoriesInImageHeap \
...
```

This is confusing because the `gu install ruby` asks me to rebuild the image, which fails with an error message that suggests adding the `-H:-DetectUserDirectoriesInImageHeap` flag which then turns out to have no effect.

```
Fatal error:com.oracle.graal.pointsto.util.AnalysisError$ParsingError: Error encountered while parsing com.sun.org.apache.xerces.internal.impl.xs.XMLSchemaValidator.reset(com.sun.org.apache.xerces.internal.xni.parser.XMLComponentManager) 
Parsing context:
	parsing com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl$JAXPSAXParser.resetSchemaValidator(SAXParserImpl.java:722)
	...
Caused by: com.oracle.graal.pointsto.constraints.UnsupportedFeatureException: Detected a string in the image heap that contains a user directory. This means that file system information from the native image build is persisted and available at image run time, which is most likely an error.
String that is problematic: http://apache.org/xml/properties/validation/schema/root-type-definition
Disallowed substring with user directory: /root
This check can be disabled using the option -H:-DetectUserDirectoriesInImageHeap
	at com.oracle.svm.hosted.image.DisallowedImageHeapObjectFeature.replacer(DisallowedImageHeapObjectFeature.java:102)
	...
```

However running `native-image --verbose --no-server --macro:truffleruby-launcher -H:-DetectUserDirectoriesInImageHeap` as a workaround is fine for now.

**Comment by olpaw** [comment] 2020-07-28 09:57
The order of arguments passed to `native-image` is significant. It looks like `--macro:truffleruby-launcher` expands to `-H:+DetectUserDirectoriesInImageHeap` (among other things). If you want to override this expansion you have to place `-H:-DetectUserDirectoriesInImageHeap` after `--macro:truffleruby-launcher`. This is not unusual and also not a bug in the native-image command.

**Comment by Taig** [comment] 2020-07-28 10:14
I understood that the macro expands to arguments and the order is significant. My point is, that when running `gu rebuild-images ruby -H:-DetectUserDirectoriesInImageHeap`, the additionally supplied arguments should perhaps be added after the macro expansion.

**Comment by sdedic** [comment] 2020-07-28 10:18
Note: `gu` only adds `--verbose` on its own (if `-v` flag is on the commandline). The order (and therefore priority) of the remaining parameters passed to `native-image` is the same as specified by the user on the commandline. 
@olpaw - what's the thing that should be fixed in `gu` ?

**Comment by olpaw** [comment] 2020-07-28 11:50
@sdedic 
```
gu rebuild-images --verbose ruby -H:-DetectUserDirectoriesInImageHeap
```
should translate to
```
native-image --no-server --macro:truffleruby-launcher -H:-DetectUserDirectoriesInImageHeap
```
instead of the current
```
native-image -H:-DetectUserDirectoriesInImageHeap --no-server --macro:truffleruby-launcher
```
I.e. for
```
gu rebuild-images [--verbose] polyglot|libpolyglot|js|llvm|python|ruby|R... [custom native-image args]
```
the `[custom native-image args]` have to be put after all other options passed to native-image

**Comment by olpaw** [comment] 2020-07-28 12:01
@sdedic sorry. This is nothing that needs fixing on the side of `gu`. The problem is in `mx.substratevm/rebuild-images.{cmd,sh}`.
There the args order is messed up.

**Closed** 2020-07-28 17:34 UTC
Labels: bug, native-image
