### ISSUE TITLE
[native-image] NPE when running native-image -jar

### ISSUE THREAD

**Issue by KengoTODA** [oracle/graal#816] opened 2018-11-21 22:25 UTC
When I tried to build [SpotBugs v3.1.8](https://github.com/spotbugs/spotbugs/releases/tag/3.1.8) with graalvm-ce-1.0.0-rc9, `native-image` command faced NPE [in this line](https://github.com/spotbugs/spotbugs/blob/3.1.8/spotbugs/src/main/java/edu/umd/cs/findbugs/ba/AnalysisContext.java#L554). I guess that `AnalysisContext.currentAnalysisContext()` returned `null`.

<details><summary>native-server command log</summary>

```
Build on Server(pid: 29344, port: 51348)
[spotbugs:29344]    classlist:   1,321.48 ms
[spotbugs:29344]        (cap):   1,591.02 ms
[spotbugs:29344]        setup:   2,737.13 ms
[spotbugs:29344]     analysis:  16,815.23 ms
error: unsupported features in 4 methods
Detailed message:
Error: Class initialization failed: edu.umd.cs.findbugs.Analyze
Original exception that caused the problem: java.lang.ExceptionInInitializerError
	at sun.misc.Unsafe.ensureClassInitialized(Native Method)
	at com.oracle.svm.hosted.ClassInitializationFeature.ensureClassInitialized(ClassInitializationFeature.java:352)
	at com.oracle.svm.hosted.ClassInitializationFeature.computeInitKindAndMaybeInitializeClass(ClassInitializationFeature.java:315)
	at com.oracle.svm.hosted.ClassInitializationFeature.computeInitKindAndMaybeInitializeClass(ClassInitializationFeature.java:291)
	at com.oracle.svm.hosted.ClassInitializationFeature.maybeInitializeHosted(ClassInitializationFeature.java:128)
	at com.oracle.svm.hosted.SVMHost.registerType(SVMHost.java:165)
	at com.oracle.graal.pointsto.meta.AnalysisUniverse.createType(AnalysisUniverse.java:252)
	at com.oracle.graal.pointsto.meta.AnalysisUniverse.lookupAllowUnresolved(AnalysisUniverse.java:193)
	at com.oracle.graal.pointsto.meta.AnalysisUniverse.lookup(AnalysisUniverse.java:170)
	at com.oracle.graal.pointsto.meta.AnalysisMethod.getDeclaringClass(AnalysisMethod.java:314)
	at com.oracle.graal.pointsto.meta.AnalysisMethod.<init>(AnalysisMethod.java:114)
	at com.oracle.graal.pointsto.meta.AnalysisUniverse.createMethod(AnalysisUniverse.java:395)
	at com.oracle.graal.pointsto.meta.AnalysisUniverse.lookupAllowUnresolved(AnalysisUniverse.java:383)
	at com.oracle.graal.pointsto.infrastructure.WrappedConstantPool.lookupMethod(WrappedConstantPool.java:104)
	at org.graalvm.compiler.java.BytecodeParser.lookupMethod(BytecodeParser.java:3928)
	at org.graalvm.compiler.java.BytecodeParser.genInvokeStatic(BytecodeParser.java:1422)
	at com.oracle.svm.hosted.phases.SharedGraphBuilderPhase$SharedBytecodeParser.genInvokeStatic(SharedGraphBuilderPhase.java:168)
	at org.graalvm.compiler.java.BytecodeParser.processBytecode(BytecodeParser.java:4868)
	at org.graalvm.compiler.java.BytecodeParser.iterateBytecodesForBlock(BytecodeParser.java:3141)
	at org.graalvm.compiler.java.BytecodeParser.processBlock(BytecodeParser.java:2950)
	at org.graalvm.compiler.java.BytecodeParser.build(BytecodeParser.java:888)
	at org.graalvm.compiler.java.BytecodeParser.buildRootMethod(BytecodeParser.java:782)
	at org.graalvm.compiler.java.GraphBuilderPhase$Instance.run(GraphBuilderPhase.java:95)
	at org.graalvm.compiler.phases.Phase.run(Phase.java:49)
	at org.graalvm.compiler.phases.BasePhase.apply(BasePhase.java:197)
	at org.graalvm.compiler.phases.Phase.apply(Phase.java:42)
	at org.graalvm.compiler.phases.Phase.apply(Phase.java:38)
	at com.oracle.graal.pointsto.flow.MethodTypeFlowBuilder.parse(MethodTypeFlowBuilder.java:204)
	at com.oracle.graal.pointsto.flow.MethodTypeFlowBuilder.apply(MethodTypeFlowBuilder.java:323)
	at com.oracle.graal.pointsto.flow.MethodTypeFlow.doParse(MethodTypeFlow.java:310)
	at com.oracle.graal.pointsto.flow.MethodTypeFlow.ensureParsed(MethodTypeFlow.java:300)
	at com.oracle.graal.pointsto.flow.MethodTypeFlow.addContext(MethodTypeFlow.java:107)
	at com.oracle.graal.pointsto.flow.SpecialInvokeTypeFlow.onObservedUpdate(InvokeTypeFlow.java:421)
	at com.oracle.graal.pointsto.flow.TypeFlow.notifyObservers(TypeFlow.java:347)
	at com.oracle.graal.pointsto.flow.TypeFlow.update(TypeFlow.java:389)
	at com.oracle.graal.pointsto.BigBang$2.run(BigBang.java:508)
	at com.oracle.graal.pointsto.util.CompletionExecutor.lambda$execute$0(CompletionExecutor.java:174)
	at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1402)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
Caused by: java.lang.NullPointerException
	at edu.umd.cs.findbugs.ba.AnalysisContext.lookupSystemClass(AnalysisContext.java:554)
	at edu.umd.cs.findbugs.Analyze.<clinit>(Analyze.java:33)
	... 42 more
Error: Class initialization failed: edu.umd.cs.findbugs.detect.InefficientToArray
Original exception that caused the problem: java.lang.ExceptionInInitializerError
	at sun.misc.Unsafe.ensureClassInitialized(Native Method)
	at com.oracle.svm.hosted.ClassInitializationFeature.ensureClassInitialized(ClassInitializationFeature.java:352)
	at com.oracle.svm.hosted.ClassInitializationFeature.computeInitKindAndMaybeInitializeClass(ClassInitializationFeature.java:315)
	at com.oracle.svm.hosted.ClassInitializationFeature.computeInitKindAndMaybeInitializeClass(ClassInitializationFeature.java:291)
	at com.oracle.svm.hosted.ClassInitializationFeature.maybeInitializeHosted(ClassInitializationFeature.java:128)
	at com.oracle.svm.hosted.SVMHost.registerType(SVMHost.java:165)
	at com.oracle.graal.pointsto.meta.AnalysisUniverse.createType(AnalysisUniverse.java:252)
	at com.oracle.graal.pointsto.meta.AnalysisUniverse.lookupAllowUnresolved(AnalysisUniverse.java:193)
	at com.oracle.graal.pointsto.meta.AnalysisUniverse.lookup(AnalysisUniverse.java:170)
	at com.oracle.graal.pointsto.meta.AnalysisUniverse.lookup(AnalysisUniverse.java:69)
	at com.oracle.graal.pointsto.infrastructure.UniverseMetaAccess.lookupJavaType0(UniverseMetaAccess.java:91)
	at com.oracle.graal.pointsto.infrastructure.UniverseMetaAccess.lookupJavaType(UniverseMetaAccess.java:82)
	at com.oracle.graal.pointsto.meta.AnalysisMetaAccess.lookupJavaType(AnalysisMetaAccess.java:48)
	at com.oracle.svm.hosted.ameta.HostedDynamicHubFeature.replace(HostedDynamicHubFeature.java:52)
	at com.oracle.graal.pointsto.meta.AnalysisUniverse.replaceObject(AnalysisUniverse.java:517)
	at com.oracle.svm.hosted.ameta.AnalysisConstantReflectionProvider.replaceObject(AnalysisConstantReflectionProvider.java:123)
	at com.oracle.svm.hosted.ameta.AnalysisConstantReflectionProvider.interceptValue(AnalysisConstantReflectionProvider.java:107)
	at com.oracle.svm.hosted.ameta.AnalysisConstantReflectionProvider.readValue(AnalysisConstantReflectionProvider.java:101)
	at com.oracle.svm.hosted.ameta.AnalysisConstantReflectionProvider.readFieldValue(AnalysisConstantReflectionProvider.java:76)
	at com.oracle.graal.pointsto.ObjectScanner.scanField(ObjectScanner.java:114)
	at com.oracle.graal.pointsto.ObjectScanner.doScan(ObjectScanner.java:271)
	at com.oracle.graal.pointsto.ObjectScanner.finish(ObjectScanner.java:312)
	at com.oracle.graal.pointsto.ObjectScanner.scanBootImageHeapRoots(ObjectScanner.java:81)
	at com.oracle.graal.pointsto.ObjectScanner.scanBootImageHeapRoots(ObjectScanner.java:63)
	at com.oracle.graal.pointsto.BigBang.checkObjectGraph(BigBang.java:591)
	at com.oracle.graal.pointsto.BigBang.finish(BigBang.java:562)
	at com.oracle.svm.hosted.NativeImageGenerator.doRun(NativeImageGenerator.java:691)
	at com.oracle.svm.hosted.NativeImageGenerator.lambda$run$0(NativeImageGenerator.java:402)
	at java.util.concurrent.ForkJoinTask$AdaptedRunnableAction.exec(ForkJoinTask.java:1386)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
Caused by: java.lang.NullPointerException
	at edu.umd.cs.findbugs.ba.AnalysisContext.lookupSystemClass(AnalysisContext.java:554)
	at edu.umd.cs.findbugs.detect.InefficientToArray.<clinit>(InefficientToArray.java:72)
	... 33 more
Error: Detected a ZipFile object in the image heap. A ZipFile object contains pointers to unmanaged C memory and file descriptors, and these resources are no longer available at image run time. The object was probably created by a class initializer and is reachable from a static field. By default, all class initialization is done during native image building.You can manually delay class initialization to image run time by using the option --delay-class-initialization-to-runtime=<class-name>. Or you can write your own initialization methods and call them explicitly from your main entry point.
Trace: 	object org.apache.bcel.util.ClassPath$Zip
	object org.apache.bcel.util.ClassPath$PathEntry[]
	object org.apache.bcel.util.ClassPath
	method org.apache.bcel.util.SyntheticRepository.getInstance()
Call path from entry point to org.apache.bcel.util.SyntheticRepository.getInstance(): 
	at org.apache.bcel.util.SyntheticRepository.getInstance(SyntheticRepository.java:43)
	at org.apache.bcel.classfile.JavaClass.<init>(JavaClass.java:98)
	at org.apache.bcel.classfile.ClassParser.parse(ClassParser.java:190)
	at edu.umd.cs.findbugs.classfile.engine.bcel.JavaClassAnalysisEngine.analyze(JavaClassAnalysisEngine.java:58)
	at edu.umd.cs.findbugs.classfile.engine.bcel.JavaClassAnalysisEngine.analyze(JavaClassAnalysisEngine.java:42)
	at edu.umd.cs.findbugs.classfile.impl.AnalysisCache.getClassAnalysis(AnalysisCache.java:262)
	at edu.umd.cs.findbugs.FindBugs2.analyzeApplication(FindBugs2.java:968)
	at edu.umd.cs.findbugs.FindBugs2.execute(FindBugs2.java:281)
	at edu.umd.cs.findbugs.FindBugs.runMain(FindBugs.java:401)
	at edu.umd.cs.findbugs.FindBugs2.main(FindBugs2.java:1185)
	at edu.umd.cs.findbugs.LaunchAppropriateUI.launch(LaunchAppropriateUI.java:106)
	at edu.umd.cs.findbugs.LaunchAppropriateUI.main(LaunchAppropriateUI.java:198)
	at com.oracle.svm.core.JavaMainWrapper.run(JavaMainWrapper.java:164)
	at com.oracle.svm.core.code.CEntryPointCallStubs.com_002eoracle_002esvm_002ecore_002eJavaMainWrapper_002erun_0028int_002corg_002egraalvm_002enativeimage_002ec_002etype_002eCCharPointerPointer_0029(generated:0)
Error: com.oracle.graal.pointsto.constraints.UnsupportedFeatureException: Unsupported type sun.misc.URLClassPath$JarLoader is reachable
To diagnose the issue, you can add the option --report-unsupported-elements-at-runtime. The unsupported element is then reported at run time when it is accessed the first time.
Trace: 
	at parsing sun.misc.URLClassPath$3.run(URLClassPath.java:575)
Call path from entry point to sun.misc.URLClassPath$3.run(): 
	at sun.misc.URLClassPath$3.run(URLClassPath.java:567)
	at sun.misc.URLClassPath$3.run(URLClassPath.java:565)
	at com.oracle.svm.core.jdk.Target_java_security_AccessController.doPrivileged(SecuritySubstitutions.java:97)
	at sun.misc.URLClassPath.getLoader(URLClassPath.java:564)
	at sun.misc.URLClassPath.getLoader(URLClassPath.java:529)
	at sun.misc.URLClassPath.getNextLoader(URLClassPath.java:494)
	at sun.misc.URLClassPath.findResource(URLClassPath.java:224)
	at java.net.URLClassLoader$2.run(URLClassLoader.java:572)
	at java.net.URLClassLoader$2.run(URLClassLoader.java:570)
	at com.oracle.svm.core.jdk.Target_java_security_AccessController.doPrivileged(SecuritySubstitutions.java:72)
	at java.util.ServiceLoader$LazyIterator.hasNext(ServiceLoader.java:398)
	at java.util.ServiceLoader$1.hasNext(ServiceLoader.java:474)
	at javax.xml.transform.FactoryFinder$1.run(FactoryFinder.java:279)
	at com.oracle.svm.core.jdk.Target_java_security_AccessController.doPrivileged(SecuritySubstitutions.java:62)
	at javax.security.auth.Subject$SecureSet.contains(Subject.java:1190)
	at java.util.AbstractCollection.containsAll(AbstractCollection.java:318)
	at java.util.JumboEnumSet.containsAll(JumboEnumSet.java:251)
	at com.oracle.svm.core.amd64.AMD64CPUFeatureAccess.verifyHostSupportsArchitecture(AMD64CPUFeatureAccess.java:158)
	at com.oracle.svm.core.JavaMainWrapper.run(JavaMainWrapper.java:138)
	at com.oracle.svm.core.code.CEntryPointCallStubs.com_002eoracle_002esvm_002ecore_002eJavaMainWrapper_002erun_0028int_002corg_002egraalvm_002enativeimage_002ec_002etype_002eCCharPointerPointer_0029(generated:0)

Error: Processing image build request failed
```
</details>

### command to test

```sh
#!/usr/bin/env bash
cd $(mktemp -d)
echo running test at $(pwd)
wget http://repo.maven.apache.org/maven2/com/github/spotbugs/spotbugs/3.1.8/spotbugs-3.1.8.zip
unzip spotbugs-3.1.8.zip
cd spotbugs-3.1.8
native-image -jar lib/spotbugs.jar
```

@shelajev this is the error that I tweeted and [you requested to report](https://twitter.com/shelajev/status/1065218243504287744). It seems that we have several NPE open issues, but I cannot judge it's same with mine or not. Thank you!

**Comment by cstancu** [comment] 2018-11-29 19:56
Thanks for the straightforward reproducer! The NPE is thrown from an application code `<clinit>` that we run at image build time. To avoid that you can build the image with `--delay-class-initialization-to-runtime=edu.umd.cs.findbugs.detect.InefficientToArray,edu.umd.cs.findbugs.Analyze`. You should also add `--report-unsupported-elements-at-runtime` to avoid loading `sun.misc.URLClassPath$JarLoader` which is currently unsupported. After this you are left with one error:
```
Error: Detected a ZipFile object in the image heap. A ZipFile object contains pointers to unmanaged C memory and file descriptors, and these resources are no longer available at image run time. The object was probably created by a class initializer and is reachable from a static field. By default, all class initialization is done during native image building.You can manually delay class initialization to image run time by using the option --delay-class-initialization-to-runtime=<class-name>. Or you can write your own initialization methods and call them explicitly from your main entry point.
Trace: 	object org.apache.bcel.util.ClassPath$Zip
	object org.apache.bcel.util.ClassPath$PathEntry[]
	object org.apache.bcel.util.ClassPath
	method org.apache.bcel.util.SyntheticRepository.getInstance()
Call path from entry point to org.apache.bcel.util.SyntheticRepository.getInstance(): 
	at org.apache.bcel.util.SyntheticRepository.getInstance(SyntheticRepository.java:43)
	at org.apache.bcel.classfile.JavaClass.<init>(JavaClass.java:98)
	at org.apache.bcel.classfile.ClassParser.parse(ClassParser.java:190)
	at edu.umd.cs.findbugs.classfile.engine.bcel.JavaClassAnalysisEngine.analyze(JavaClassAnalysisEngine.java:58)
	at edu.umd.cs.findbugs.classfile.engine.bcel.JavaClassAnalysisEngine.analyze(JavaClassAnalysisEngine.java:42)
	at edu.umd.cs.findbugs.classfile.impl.AnalysisCache.getClassAnalysis(AnalysisCache.java:262)
	at edu.umd.cs.findbugs.FindBugs2.analyzeApplication(FindBugs2.java:968)
	at edu.umd.cs.findbugs.FindBugs2.execute(FindBugs2.java:281)
	at edu.umd.cs.findbugs.FindBugs.runMain(FindBugs.java:401)
	at edu.umd.cs.findbugs.FindBugs2.main(FindBugs2.java:1185)
	at edu.umd.cs.findbugs.LaunchAppropriateUI.launch(LaunchAppropriateUI.java:106)
	at edu.umd.cs.findbugs.LaunchAppropriateUI.main(LaunchAppropriateUI.java:198)
	at com.oracle.svm.core.JavaMainWrapper.run(JavaMainWrapper.java:164)
	at com.oracle.svm.core.code.IsolateEnterStub.JavaMainWrapper_run_5087f5482cc9a6abc971913ece43acb471d2631b(generated:0)
Error: No instances are allowed in the image heap for a class that is initialized or reinitialized at image runtime: org.apache.bcel.util.SyntheticRepository
Trace: 	field org.apache.bcel.Repository.repository
```
This requires investigating which class initializer(s) trigger the `ZipFile` object creation. At this point this process is mostly manual and requires some familiarity with the application code. You can read more about [Class Initialization in the context of GraalVM Native Image Generation](https://medium.com/graalvm/understanding-class-initialization-in-graalvm-native-image-generation-d765b7e4d6ed). Following the method in the article (i.e., using `jdb`) I found this additional classes that need delayed initialization: `edu.umd.cs.findbugs.Analyze,org.apache.bcel.util.SyntheticRepository,org.apache.bcel.util.ClassPath,org.apache.bcel.Repository,edu.umd.cs.findbugs.ba.AnalysisContext`. The complete build command is then:
```
native-image  --report-unsupported-elements-at-runtime --delay-class-initialization-to-runtime=edu.umd.cs.findbugs.detect.InefficientToArray,edu.umd.cs.findbugs.Analyze,org.apache.bcel.util.SyntheticRepository,org.apache.bcel.util.ClassPath,org.apache.bcel.Repository,edu.umd.cs.findbugs.ba.AnalysisContext -jar lib/spotbugs.jar
```
Now I can successfully build the `spotbugs` executable. Running it with `./spotbugs -textui` yields the usage text.  Running with ` ./spotbugs -gui` fails. The initial error is due to a missing reflection configuration, however I expect that getting the GUI to work to be more complicated, I didn't look further. Also, please note that trying to use  the `sun.misc.URLClassPath$JarLoader` it will throw a runtime exception due to the `--report-unsupported-elements-at-runtime` above.

**Comment by cstancu** [comment] 2018-11-29 19:57
I will close this issue for now. Please open another one if you run into other problems.

**Closed by cstancu** 2018-11-29 19:57 UTC
Labels: substrate

**Comment by KengoTODA** [comment] 2018-12-05 03:12
Thanks, now I can build native image in my local.

However it cannot analyse jar file because `SystemProperties.getProperty("java.class.path")` returns `null` at [here](https://github.com/spotbugs/spotbugs/blob/e9ed483854682badf7e28fa9a8954a4d63008679/spotbugs/src/main/java/edu/umd/cs/findbugs/classfile/impl/ClassPathBuilder.java#L468). Not sure we have workaround or not.
