### ISSUE TITLE
Read modules from a directory

### ISSUE THREAD

**Issue by bowbahdoe** [oracle/graal#8132] opened 2024-01-09 22:00 UTC
**Feature request**

Please include the following information:

**Is your feature request related to a problem? Please describe.**
When using the `--module-path` flag on the `native-image` tool, if a directory is given that directory is not scanned for modules. Other java tooling like `javac`, `jlink`, `java`, etc. will find jars and exploded directories in the folder, so this creates an  annoying inconsistency.

**Describe the solution you'd like.**
I'd like it if `--module-path` worked the same as for other jdk tools

**Describe who do you think will benefit the most.**
GraalVM users who are using the command line directly

**Describe alternatives you've considered.**
Exploding the path out on the command line with all the jars. This also works with other jdk tools, but IDEs don't know how to deal with dependencies if they aren't coming from maven, gradle, or are flat in a folder.

**Additional context.**
I have a small reproducer in [this repo](https://github.com/bowbahdoe/jresolve-classpath-example/blob/main/Justfile), but it should be easy enough to fabricate in other ways.

**Express whether you'd like to help contributing this feature**
I would not like to contribute this feature. I have other stuff to do.

**Comment by fniephaus** [comment] 2024-01-10 10:01
Closing this as a duplicate of https://github.com/oracle/graal/issues/7271.

**Closed by fniephaus** 2024-01-10 10:01 UTC
Labels: feature
