### ISSUE TITLE
core-dump / segfault on ubuntu 22.04

### ISSUE THREAD

**Issue by mpalourdio** [oracle/graal#8736] opened 2024-04-09 13:31 UTC
Hi,

With version CE (and non CE) , on my ubuntu 22.0.4, I experience core-dump, segfault without any clue. The projets builds correctly on an other machine (linux mint 21), and github actions for example. (`graalvm/setup-graalvm@v1`)
 
**Steps to reproduce the issue**
Please include both build steps as well as run steps
1. Clone https://github.com/mpalourdio/SpringBootAngularHTML5
2.  mvn -Pnative native:compile

**Describe GraalVM and your environment:**
```
 $ java --version
openjdk 21.0.2 2024-01-16
OpenJDK Runtime Environment GraalVM CE 21.0.2+13.1 (build 21.0.2+13-jvmci-23.1-b30)
OpenJDK 64-Bit Server VM GraalVM CE 21.0.2+13.1 (build 21.0.2+13-jvmci-23.1-b30, mixed mode, sharing
```
 - OS: ubuntu 22.0.4
 - Architecture: `6.5.0-27-generic #28~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Fri Mar 15 10:51:06 UTC 2 x86_64 x86_64 x86_64 GNU/Linux`. Tested too with `5.19.17-051917-generic #202210240939`

**More details**
A core dump is generated, with a lot of

```
Stack trace of thread 7430:
                #0  0x00007bbb8ae91117 __futex_abstimed_wait_common64 (libc.so.6 + 0x91117)
                #1  0x00007bbb8ae93e9b __pthread_cond_wait_common (libc.so.6 + 0x93e9b)
                #2  0x00007bbb8a65f947 n/a (/home/m1bida/Téléchargements/graalvm-community-openjdk-21+35.1/lib/server/libjvm.so + 0xcd0947)
                #3  0x00007bbb8a60cf3c n/a (/home/m1bida/Téléchargements/graalvm-community-openjdk-21+35.1/lib/server/libjvm.so + 0xc7df3c)
                #4  0x00007bbb89fd9a66 n/a (/home/m1bida/Téléchargements/graalvm-community-openjdk-21+35.1/lib/server/libjvm.so + 0x64aa66)
                #5  0x00007bbb89fdd809 n/a (/home/m1bida/Téléchargements/graalvm-community-openjdk-21+35.1/lib/server/libjvm.so + 0x64e809)
                #6  0x00007bbb8a282958 n/a (/home/m1bida/Téléchargements/graalvm-community-openjdk-21+35.1/lib/server/libjvm.so + 0x8f3958)
                #7  0x00007bbb8a82e138 n/a (/home/m1bida/Téléchargements/graalvm-community-openjdk-21+35.1/lib/server/libjvm.so + 0xe9f138)
                #8  0x00007bbb8a6544ba n/a (/home/m1bida/Téléchargements/graalvm-community-openjdk-21+35.1/lib/server/libjvm.so + 0xcc54ba)
                #9  0x00007bbb8ae94ac3 start_thread (libc.so.6 + 0x94ac3)
                #10 0x00007bbb8af26850 __clone3 (libc.so.6 + 0x126850)
```
The maven outputs only states
```
[INFO] --- resources:3.3.1:resources (default-resources) @ springbootangularhtml5 ---
Erreur de segmentation (core dumped)```
```
Sometimes it goes to nearly the end, sometime not.
Let me know if you need more information. Thanks !

**Comment by mpalourdio** [comment] 2024-04-09 18:10
Seems like it an agent, installed on both our corporate desktops and servers that make the native compilation impossible.

It's cortex XDR : https://docs-cortex.paloaltonetworks.com/p/XDR

**Comment by fernando-valdez** [comment] 2024-04-10 01:14
Hi, I am glad you found the root cause of the problem. I am closing this issue.

**Closed by fernando-valdez** 2024-04-10 01:14 UTC
Labels: bug
