### ISSUE TITLE
Immediate segfault with Kotlin hello world

### ISSUE THREAD

**Issue by mikehearn** [oracle/graal#6837] opened 2023-06-20 11:35 UTC
Using latest Oracle GraalVM distribution on latest macOS Intel

**Steps to reproduce the issue**

```kotlin
fun main() { println("Hello World!") }
```

1. `kotlinc -d out.jar -include-runtime Hello.kt`
2. `native-image -jar out.jar`
3. `./out`

```
❯ lldb ./out
(lldb) target create "./out"
Current executable set to '/tmp/ni-test/out' (x86_64).
(lldb) r
Process 17798 launched: '/tmp/ni-test/out' (x86_64)
Process 17798 stopped
* thread #1, queue = 'com.apple.main-thread', stop reason = EXC_BAD_ACCESS (code=1, address=0x2a01034)
    frame #0: 0x00000001001dcb1a out`___lldb_unnamed_symbol2686 + 970
out`___lldb_unnamed_symbol2686:
->  0x1001dcb1a <+970>: movl   0x4(%rax), %ecx
    0x1001dcb1d <+973>: cmpl   0x5c(%rsp), %ecx
    0x1001dcb21 <+977>: ja     0x1001dcc7e               ; <+1326>
    0x1001dcb27 <+983>: movq   0x20(%rsp), %rdi
Target 0: (out) stopped.
```

[native_library_info_20230620_133102.txt](https://github.com/oracle/graal/files/11799925/native_library_info_20230620_133102.txt)
[target_info_20230620_133051.txt](https://github.com/oracle/graal/files/11799926/target_info_20230620_133051.txt)

**Comment by mikehearn** [comment] 2023-06-24 19:45
This appears to affect any native image? Also with a Python hello world compiled with graalpy.

**Comment by fniephaus** [comment] 2023-06-26 08:21
Looks like a duplicate of https://github.com/oracle/graal/issues/5778. Please add a comment if you think it's something else.

**Closed** 2023-06-26 08:21 UTC
Labels: bug, native-image
