### ISSUE TITLE
NPE with new "Inline before static analysis"

### ISSUE THREAD

**Issue by zakkak** [oracle/graal#3470] opened 2021-06-14 11:17 UTC
**Describe the issue**
180908f27dbdefb822938d4f447fea8a587cd011 combined with `-H:-ParseOnce` breaks "jpa-oracle" quarkus integration test.

**Steps to reproduce the issue**
Please include both build steps as well as run steps
1. Build latest GraalVM sources
2. `export GRAALVM_HOME=/path/to/freshly/build/graalvm`
2. `wget https://github.com/quarkusio/quarkus/archive/refs/tags/2.0.0.CR3.tar.gz`
3. `tar xf 2.0.0.CR3.tar.gz`
4. `cd quarkus-2.0.0.CR3`
5. `./mvnw -Dnative -Dquarkus.native.additional-build-args=-H:-ParseOnce -pl integration-tests/jpa-oracle package`

**Describe GraalVM and your environment:**
 - GraalVM version: **180908f27dbdefb822938d4f447fea8a587cd011**
 - JDK major version: **11**
 - OS: **Fedora 34**
 - Architecture: **AMD64**

**More details**
```
Fatal error:com.oracle.graal.pointsto.util.AnalysisError$ParsingError: Error encountered while parsing oracle.jdbc.proxy.ProxyFactory.proxyForCache(java.lang.Object, java.lang.Object, java.util.Map, java.lang.reflect.Method) 
Parsing context:
   at oracle.jdbc.proxy.ProxyFactory.proxyFor(ProxyFactory.java:158)
   at oracle.jdbc.proxy.ProxyFactory.proxyFor(ProxyFactory.java:144)
   at oracle.jdbc.driver.OracleDriver.babelfishConnect(OracleDriver.java:1015)
   at oracle.jdbc.driver.OracleDriver.connect(OracleDriver.java:676)
   at oracle.jdbc.driver.OracleDriver.connect(OracleDriver.java:602)
   at com.oracle.svm.reflect.OracleDriver_connect_8af0cff7e696a994e201c11f0784956ffac49905_202.invoke(Unknown Source)
   at java.base@11.0.11/java.lang.reflect.Method.invoke(Method.java:566)
   at app//com.oracle.svm.core.containers.Metrics.systemMetrics(Metrics.java:62)
   at app//com.oracle.svm.core.containers.Container.metrics(Container.java:44)
   at app//com.oracle.svm.core.ContainerInfo.<init>(ContainerInfo.java:34)
   at app//com.oracle.svm.core.Containers.memoryLimitInBytes(Containers.java:162)
   at app//com.oracle.svm.core.heap.PhysicalMemory.doInitialize(PhysicalMemory.java:146)
   at app//com.oracle.svm.core.heap.PhysicalMemory.tryInitialize(PhysicalMemory.java:115)
   at app//com.oracle.svm.core.genscavenge.HeapPolicy.samplePhysicalMemorySize(HeapPolicy.java:364)
   at app//com.oracle.svm.core.genscavenge.ThreadLocalAllocation.runSlowPathHooks(ThreadLocalAllocation.java:161)
   at app//com.oracle.svm.core.genscavenge.ThreadLocalAllocation.slowPathNewArray(ThreadLocalAllocation.java:199)

	at com.oracle.graal.pointsto.util.AnalysisError.parsingError(AnalysisError.java:126)
	at com.oracle.graal.pointsto.flow.MethodTypeFlow.createTypeFlow(MethodTypeFlow.java:311)
	at com.oracle.graal.pointsto.flow.MethodTypeFlow.ensureTypeFlowCreated(MethodTypeFlow.java:282)
	at com.oracle.graal.pointsto.flow.MethodTypeFlow.addContext(MethodTypeFlow.java:103)
	at com.oracle.graal.pointsto.DefaultAnalysisPolicy$DefaultSpecialInvokeTypeFlow.onObservedUpdate(DefaultAnalysisPolicy.java:363)
	at com.oracle.graal.pointsto.flow.TypeFlow.notifyObservers(TypeFlow.java:471)
	at com.oracle.graal.pointsto.flow.TypeFlow.update(TypeFlow.java:540)
	at com.oracle.graal.pointsto.BigBang$2.run(BigBang.java:539)
	at com.oracle.graal.pointsto.util.CompletionExecutor.executeCommand(CompletionExecutor.java:190)
	at com.oracle.graal.pointsto.util.CompletionExecutor.lambda$executeService$0(CompletionExecutor.java:174)
	at java.base/java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1426)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
Caused by: java.lang.NullPointerException
	at com.oracle.graal.pointsto.flow.MethodTypeFlowBuilder.registerUsedElements(MethodTypeFlowBuilder.java:249)
	at com.oracle.svm.hosted.analysis.flow.SVMMethodTypeFlowBuilder.registerUsedElements(SVMMethodTypeFlowBuilder.java:78)
	at com.oracle.graal.pointsto.flow.MethodTypeFlowBuilder.parse(MethodTypeFlowBuilder.java:180)
	at com.oracle.graal.pointsto.flow.MethodTypeFlowBuilder.apply(MethodTypeFlowBuilder.java:321)
	at com.oracle.graal.pointsto.flow.MethodTypeFlow.createTypeFlow(MethodTypeFlow.java:293)
	... 14 more
```

a6d646c3d3a is the last working commit.
Running with single parsing enabled also works:
```
./mvnw -Dnative -pl integration-tests/jpa-oracle package
```
but increases compilation times and memory usage as described in #3435

**Comment by christianwimmer** [comment] 2021-06-17 17:33
I have not tried to reproduce the failure, but since the exception stack trace is exactly the same as https://github.com/oracle/graal/issues/3469 I hope it is also fixed by https://github.com/oracle/graal/commit/f648801d7187ed2f567fd8a56bfe6435c9d6b5dd
If it still happens, please re-open.

**Closed by christianwimmer** 2021-06-17 17:33 UTC
Labels: bug, native-image, quarkus

**Comment by zakkak** [comment] 2021-06-22 12:00
I confirm that the issue is no longer reproducible, thanks Christian!
