### ISSUE TITLE
Class file version > 52

### ISSUE THREAD

**Issue by knyttl** [oracle/graal#1190] opened 2019-04-25 07:38 UTC
Do you plan to support JDK11, so that classes with version > 52 can be run with Graal as well?

```
java.lang.UnsupportedClassVersionError: XXX has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0
```

**Comment by dougxc** [comment] 2019-04-30 08:04
Yes, support for JDK11 is a work in progress. I'm closing this as a duplicate of #651.

**Closed by dougxc** 2019-04-30 08:04 UTC
