### ISSUE TITLE
[native-image] -H:-SpawnIsolates crashes on AArch64

### ISSUE THREAD

**Issue by tshull226** [oracle/graal#1839] opened 2019-11-19 17:50 UTC
When running the simple HelloWorld example, disabling SpawnIsolates results in a core dump.

@bobmcwhirter @sanzinger Do you know if this worked in the past?

**Comment by tshull226** [comment] 2019-11-26 02:36
I think I have found the root cause of the problem. I should have a patch prepared shortly.

**Comment by tshull226** [comment] 2019-11-26 17:34
I have this working now, but would like some input on the best way to fix it. In a nutshell, the issue is that sometimes "ldr imm9/12" was being used instead of "adrp ldr / adrp add". One of the places this happens is in AArch64Move.java

@adinn @theRealAph within AArch64Move.java, two of the crb.recordDataReferenceInCode calls are being linked to a regular "ldr" instruction, not "adrp ldr" (lines 180 and 540). Was this intentional? Is this is okay for HotSpot? If you think they should be left this way, then I can leave AArch64Move.java as is and add my fix directly to SubstrateAArch64Backend.java; otherwise I can fix this.

**Comment by tshull226** [comment] 2019-11-28 04:26
Sorry, I misspoke in my previous comment - I didn't realize when loadAddress is passed a pc-relative address it automatically generates an adrp/add combo,not a ldr literal. However, SVM is unable to create the proper element in the data section for the ldr on line 540 of AArch64Move.java. It looks like it is currently just creating one .rodata section which is too far away. For now, in the case of SVM it is necessary to have a adrp/ldr in its place. The question still remains though whether to change the code emitted within AArch64Move.java, or to replace the node in SubstrateAArch64Backend.java with the appropriate assembly.

**Comment by tshull226** [comment] 2019-11-28 15:45
I submitted a PR with a fix #1903 

In the PR I updated AArch64Move.java. If you would rather have me resolve the problem in SubstrateAArch64Backend.java so Graal is unchanged please let me know.

**Comment by adinn** [comment] 2019-11-28 16:13
Hi Thomas,

The specific line in AArch64Move was written by Chris Thalinger rather than me or the other Andrew so neither of us can provide a rationale for why it was first written as is. I'm not especially committed to fixing this in one place or the other. If the problem only arises because of .rodata section being too far away then maybe just fix it in substrate? Or do you see any other reason to change this in the generic back end code?

**Comment by theRealAph** [comment] 2019-11-28 16:59
We discussed this some time ago. I guess the problem is that SVM can generate huge executable files, ones that GCC would choke on, or at least require special command-line options to generate. In HotSpot we know what the worst-case range can be, so we can generate the best code.
Having said all of that, there is already a bug (which I never got around to fixing) in AArch64's jaotc when you try to compile the entire Java library -- you see exactly this offset overflow. So we should fix it generically.

**Comment by sanzinger** [comment] 2019-12-18 13:36
To make a long story short, the option `-SpawnIsolates` will be removed in the long run. As well as the the `-MultiThreaded` option. So I would suggest to not put much effort into getting `-SpawnIsolates` running.

**Closed by sanzinger** 2019-12-18 13:36 UTC
