### ISSUE TITLE
Graalvm native-image windows support

### ISSUE THREAD

**Issue by OmerBasriKAYA** [oracle/graal#5561] opened 2022-12-02 16:53 UTC
I am trying to convert my jar file using graalvm native image. However, it gives an error like,

native-image -jar NativeTest.jar
```
Error: Platform specified as windows-amd64 isn't supported.
Error: Image build request failed with exit status 1
```

**Comment by rakrishna1** [comment] 2022-12-03 07:04
What is the Windows OS and version you are using ?
Is it 32 bit or 64 bit ?
give a sample java code you are trying to convert to executable ?

**Comment by OmerBasriKAYA** [comment] 2022-12-03 15:12
OS Version: Windows 10 Pro 22H2 19045.2251 (x64)

`public class NativeTest {

	public static void main(String[] args) {
		System.out.println("test");
	}

}`

thanks.

**Comment by rakrishna1** [comment] 2022-12-03 16:15
Mine is a Windows 10 Pro x64.
I am using Graalvm 22.3 for Java 19.
and Native build works fine for me.
Here are the steps I used:

javac -d build NativeTest.java
jar --create --file NativeTest.jar --main-class NativeTest -C build .
native-image -jar NativeTest.jar

What is the exact output you get in the last ?

C:\GraalVM\samples>javac -d build NativeTest.java

C:\GraalVM\samples>jar --create --file NativeTest.jar --main-class NativeTest -C build .

C:\GraalVM\samples>native-image -jar NativeTest.jar
========================================================================================================================
GraalVM Native Image: Generating 'NativeTest' (executable)...
========================================================================================================================
[1/7] Initializing...                                                                                   (12.1s @ 0.20GB)
 Version info: 'GraalVM 22.3.0 Java 19 CE'
 Java version info: '19.0.1+10-jvmci-22.3-b08'
 C compiler: cl.exe (microsoft, x64, 19.27.29111)
 Garbage collector: Serial GC
[2/7] Performing analysis...  [****]                                                                    (22.8s @ 0.74GB)
   2,882 (74.55%) of  3,866 classes reachable
   3,433 (50.77%) of  6,762 fields reachable
  12,966 (43.60%) of 29,741 methods reachable
      25 classes,     0 fields, and   330 methods registered for reflection
      61 classes,    51 fields, and    52 methods registered for JNI access
       1 native library: version
[3/7] Building universe...                                                                               (3.0s @ 1.22GB)
[4/7] Parsing methods...      [**]                                                                       (2.4s @ 0.73GB)
[5/7] Inlining methods...     [***]                                                                      (1.6s @ 1.13GB)
[6/7] Compiling methods...    [*****]                                                                   (23.8s @ 1.11GB)
[7/7] Creating image...                                                                                  (4.2s @ 1.50GB)
   4.30MB (37.59%) for code area:     7,337 compilation units
   6.96MB (60.82%) for image heap:   93,528 objects and 5 resources
 186.95KB ( 1.60%) for other data
  11.45MB in total
------------------------------------------------------------------------------------------------------------------------
Top 10 packages in code area:                               Top 10 object types in image heap:
 652.20KB java.util                                          929.08KB byte[] for code metadata
 330.03KB java.lang                                          926.22KB java.lang.String
 271.63KB java.text                                          851.95KB byte[] for general heap data
 223.63KB java.util.regex                                    634.31KB java.lang.Class
 194.41KB java.util.concurrent                               553.12KB byte[] for java.lang.String
 151.48KB java.math                                          225.16KB com.oracle.svm.core.hub.DynamicHubCompanion
 132.40KB com.oracle.svm.core.code                           217.62KB java.lang.Object[]
 120.79KB com.oracle.svm.core.genscavenge                    195.66KB java.util.HashMap$Node
 119.00KB java.util.stream                                   163.72KB java.lang.String[]
 115.66KB java.lang.invoke                                   157.36KB java.util.concurrent.ConcurrentHashMap$Node
   1.99MB for 117 more packages                                1.57MB for 777 more object types
------------------------------------------------------------------------------------------------------------------------
                        1.1s (0.7% of total time) in 20 GCs | Peak RSS: 2.60GB | CPU load: 2.45
------------------------------------------------------------------------------------------------------------------------
Produced artifacts:
 C:\GraalVM\samples\NativeTest.build_artifacts.txt (txt)
 C:\GraalVM\samples\NativeTest.exe (executable)
========================================================================================================================
Finished generating 'NativeTest' in 2m 47s.

**Comment by OmerBasriKAYA** [comment] 2022-12-03 16:33
my full output,

D:\graalvm-ce-java17-22.3.0\bin>javac -d build NativeTest.java
D:\graalvm-ce-java17-22.3.0\bin>jar --create --file NativeTest.jar --main-class NativeTest -C build .
D:\graalvm-ce-java17-22.3.0\bin>java -jar NativeTest.jar
test
D:\graalvm-ce-java17-22.3.0\bin>native-image -jar NativeTest.jar
Error: Platform specified as windows-amd64 isn't supported.
Error: Image build request failed with exit status 1
D:\graalvm-ce-java17-22.3.0\bin>

**Comment by rakrishna1** [comment] 2022-12-03 19:45
I wonder if you are using "x64 Native Tools Command Prompt."

**Comment by OmerBasriKAYA** [comment] 2022-12-04 03:38
Yes, im using x64 Natie Tools Command Prompt for VS 2019



**********************************************************************
** Visual Studio 2019 Developer Command Prompt v16.8.5
** Copyright (c) 2020 Microsoft Corporation
**********************************************************************
[vcvarsall.bat] Environment initialized for: 'x64'

C:\Program Files (x86)\Microsoft Visual Studio\2019\Community>D:
D:\>cd graalvm-ce-java17-22.3.0
D:\graalvm-ce-java17-22.3.0>cd bin
D:\graalvm-ce-java17-22.3.0\bin>native-image NativeTest.jar
Error: Platform specified as windows-amd64 isn't supported.
Error: Image build request failed with exit status 1
D:\graalvm-ce-java17-22.3.0\bin>

**Comment by oubidar-Abderrahim** [comment] 2022-12-07 10:02
Hi, Thank you for reaching out. I suspect that you've downloaded a GraalVM installation for another OS (Linux or macOS) and you're trying to use it in Windows.

You can verify the release file in your installation folder to know for sure. In all cases, please re-download GraalVM for Windows platform and re-install native-image using `gu` and give it a second try.

**Comment by OmerBasriKAYA** [comment] 2022-12-07 19:04
actually i'm pretty sure i downloaded GraalVM for windows.
I downloaded the Windows (amd64) one here, am I wrong?
https://github.com/graalvm/graalvm-ce-builds/releases

**Comment by viniciusxyz** [comment] 2023-01-08 05:03
@OmerBasriKAYA  Just confirming, I just did a native build on Windows and it's working fine, remembering that on Windows we have some requirements that must be met, those extra steps are [here](https://www.graalvm.org/22.3/docs/getting-started/windows/#prerequisites-for-using-native-image-on-windows).

**Comment by oubidar-Abderrahim** [comment] 2023-01-20 16:21
We couldn't reproduce the bug on our end. I'll close this issue. please reopen if there is anything we can help with. Thank you

**Closed by oubidar-Abderrahim** 2023-01-20 16:21 UTC
Labels: native-image

**Comment by tugalsan** [comment] 2023-03-29 08:02
@OmerBasriKAYA Did you tried it on windows 11. No matter what i did, i could not able to run native-image command.

**Comment by tugalsan** [comment] 2023-03-29 08:34
Removing C++ ATL also had no effect
<img width="215" alt="image" src="https://user-images.githubusercontent.com/12820361/228475650-9052113d-10a5-4572-aa46-29c1668fe37b.png">
