### ISSUE TITLE
[LLVM] Error building on macOS 11.3

### ISSUE THREAD

**Issue by chrisseaton** [oracle/graal#3383] opened 2021-04-28 21:41 UTC
```
chrisseaton@Chriss-MacBook-Pro sulong % ../../mx/mx build
JAVA_HOME: /Users/chrisseaton/.sdkman/candidates/java/current
27 unsatisfied dependencies were removed from build (use -v to list them)
24 non-default dependencies were removed from build (use -v to list them, mx build --all to build them)
Compiling com.oracle.truffle.llvm.toolchain.config with javac-daemon(JDK 16)... [/Users/chrisseaton/Documents/graal/sulong/mxbuild/projects/com.oracle.truffle.llvm.toolchain.config/bin/com/oracle/truffle/llvm/toolchain/config/LLVMConfig.class does not exist]
WARNING: Found multiple locations for 'dependency:sdk:LAUNCHER_COMMON' in 'GRAALVM_C8649C1BBC_JAVA16': ['graalvm-c8649c1bbc-java16-21.2.0-dev/lib/graalvm/launcher-common.jar', 'graalvm-c8649c1bbc-java16-21.2.0-dev/lib/graalvm/launcher-common.jar']
WARNING: Found multiple locations for 'dependency:sulong:SULONG_LAUNCHER' in 'GRAALVM_C8649C1BBC_JAVA16': ['graalvm-c8649c1bbc-java16-21.2.0-dev/lib/graalvm/sulong-launcher.jar', 'graalvm-c8649c1bbc-java16-21.2.0-dev/lib/graalvm/sulong-launcher.jar']
Compiling com.oracle.truffle.llvm.tests.pipe with javac-daemon(JDK 16)... [/Users/chrisseaton/Documents/graal/sulong/mxbuild/tests/com.oracle.truffle.llvm.tests.pipe/bin/com/oracle/truffle/llvm/tests/pipe/CaptureOutput.class does not exist]
Archiving SULONG_GRAALVM_DOCS... [/Users/chrisseaton/Documents/graal/sulong/mxbuild/darwin-amd64/dists/sulong-graalvm-docs.tar does not exist]
Archiving SULONG_LEGACY... [/Users/chrisseaton/Documents/graal/sulong/mxbuild/dists/sulong-legacy.tar does not exist]
Archiving SULONG_CORE_HOME... [/Users/chrisseaton/Documents/graal/sulong/mxbuild/darwin-amd64/dists/sulong-core-home.tar does not exist]
WARNING: Found multiple locations for 'dependency:sdk:LAUNCHER_COMMON' in 'GRAALVM_C8649C1BBC_JAVA16': ['graalvm-c8649c1bbc-java16-21.2.0-dev/lib/graalvm/launcher-common.jar', 'graalvm-c8649c1bbc-java16-21.2.0-dev/lib/graalvm/launcher-common.jar']
WARNING: Found multiple locations for 'dependency:sulong:SULONG_LAUNCHER' in 'GRAALVM_C8649C1BBC_JAVA16': ['graalvm-c8649c1bbc-java16-21.2.0-dev/lib/graalvm/sulong-launcher.jar', 'graalvm-c8649c1bbc-java16-21.2.0-dev/lib/graalvm/sulong-launcher.jar']Archiving SULONG_TOOLCHAIN_CONFIG... [dependency com.oracle.truffle.llvm.toolchain.config updated]

Building com.oracle.truffle.llvm.tests.pipe.native_amd64 with Ninja... [dependency com.oracle.truffle.llvm.tests.pipe updated]
Building com.oracle.truffle.llvm.tests.native_amd64 with Ninja...
Archiving SULONG_TEST_NATIVE... [dependency com.oracle.truffle.llvm.tests.native updated]
Compiling com.oracle.truffle.llvm.toolchain.launchers with javac-daemon(JDK 16)... [/Users/chrisseaton/Documents/graal/sulong/mxbuild/projects/com.oracle.truffle.llvm.toolchain.launchers/bin/com/oracle/truffle/llvm/toolchain/launchers/Linker.class does not exist]
Compiling com.oracle.truffle.llvm.launcher with javac-daemon(JDK 16)... [/Users/chrisseaton/Documents/graal/sulong/mxbuild/projects/com.oracle.truffle.llvm.launcher/bin/com/oracle/truffle/llvm/launcher/LLVMLauncher.class does not exist]
Generating bootstrap-toolchain-launchers... [dependency com.oracle.truffle.llvm.toolchain.launchers updated]
Archiving SULONG_LAUNCHER... [dependency com.oracle.truffle.llvm.launcher updated]
Archiving SULONG_TOOLCHAIN_LAUNCHERS... [dependency com.oracle.truffle.llvm.toolchain.launchers updated]
Generating bootstrap-toolchain-launchers-no-home... [dependency com.oracle.truffle.llvm.toolchain.launchers updated]
Archiving SULONG_BOOTSTRAP_TOOLCHAIN... [dependency bootstrap-toolchain-launchers updated]
Archiving SULONG_BOOTSTRAP_TOOLCHAIN_NO_HOME... [dependency bootstrap-toolchain-launchers-no-home updated]
Compiling com.oracle.truffle.api.exception with javac-daemon(JDK 16)... [/Users/chrisseaton/Documents/graal/truffle/mxbuild/src/com.oracle.truffle.api.exception/bin/com/oracle/truffle/api/exception/ExceptionAccessor.class[2021-04-28 22:36:55] is older than /Users/chrisseaton/Documents/graal/truffle/mxbuild/src/com.oracle.truffle.api.interop/bin/com/oracle/truffle/api/interop/NumberUtils.class[2021-04-28 22:39:45]]
Compiling com.oracle.truffle.api.object.dsl with javac-daemon(JDK 16)... [/Users/chrisseaton/Documents/graal/truffle/mxbuild/src/com.oracle.truffle.api.object.dsl/bin/com/oracle/truffle/api/object/dsl/Volatile.class[2021-04-28 22:36:56] is older than /Users/chrisseaton/Documents/graal/truffle/mxbuild/src/com.oracle.truffle.api.object/bin/com/oracle/truffle/api/object/ShapeListener.class[2021-04-28 22:39:47]]
Compiling com.oracle.truffle.object with javac-daemon(JDK 16)... [/Users/chrisseaton/Documents/graal/truffle/mxbuild/src/com.oracle.truffle.object/bin/META-INF/services/com.oracle.truffle.api.object.LayoutFactory[2021-04-28 22:36:56] is older than /Users/chrisseaton/Documents/graal/truffle/mxbuild/src/com.oracle.truffle.api.object/bin/com/oracle/truffle/api/object/ShapeListener.class[2021-04-28 22:39:47]]
Building com.oracle.truffle.llvm.libraries.bitcode.libcxx_amd64 with Ninja... [dependency SULONG_BOOTSTRAP_TOOLCHAIN_NO_HOME updated]
Compiling com.oracle.truffle.nfi.api with javac-daemon(JDK 16)... [/Users/chrisseaton/Documents/graal/truffle/mxbuild/src/com.oracle.truffle.nfi.api/bin/com/oracle/truffle/nfi/api/SignatureLibrary.class[2021-04-28 22:36:55] is older than /Users/chrisseaton/Documents/graal/truffle/mxbuild/src/com.oracle.truffle.api.interop/bin/com/oracle/truffle/api/interop/NumberUtils.class[2021-04-28 22:39:45]]
Compiling com.oracle.truffle.polyglot with javac-daemon(JDK 16)... [dependency com.oracle.truffle.api.exception updated]
Compiling com.oracle.truffle.api.object.dsl.test with javac-daemon(JDK 16)... [dependency com.oracle.truffle.object updated]
CMake Error at cmake/modules/CheckCompilerVersion.cmake:97 (message):
  libstdc++ version must be at least 5.1.
Call Stack (most recent call first):
  cmake/config-ix.cmake:13 (include)
  CMakeLists.txt:623 (include)
```

**Comment by rschatz** [comment] 2021-04-29 13:43
Unfortunately I don't have macOS 11 yet, and on my machine it doesn't reproduce (macOS 10.15).

The symbol it doesn't find is supposed to be defined in `wchar.h`. At least it's there on my system (in `/Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include/wchar.h`) it is defined there. Is this still there on the newer version?

Also we did recently change our build process to use CMake+Ninja instead of GNU make for building: https://github.com/oracle/graal/commit/836d28b0e752aec61210ddfa42c45ca57a6a0135
Could you double-check whether the issue was introduced by that change?

**Comment by chrisseaton** [comment] 2021-04-29 13:45
I've never even seen `#include_next` before in this header!

**Comment by chrisseaton** [comment] 2021-04-29 22:56
I hacked a fix by just removing `libc++`.

On ec3ea38955a61bf2e70306e7291a5ff9f8da5196:

```diff
From 396230dead7c871659a9943ad8ececa8a6aed26d Mon Sep 17 00:00:00 2001
From: Chris Seaton <chris.seaton@shopify.com>
Date: Thu, 29 Apr 2021 23:44:25 +0100
Subject: [PATCH] FIX

---
 sulong/mx.sulong/suite.py                     | 43 -------------------
 .../CMakeLists.txt                            |  7 ---
 2 files changed, 50 deletions(-)

diff --git a/sulong/mx.sulong/suite.py b/sulong/mx.sulong/suite.py
index 820bceaefab..826975d4cdd 100644
--- a/sulong/mx.sulong/suite.py
+++ b/sulong/mx.sulong/suite.py
@@ -628,12 +628,10 @@ suite = {
       "vpath" : True,
       "ninja_targets" : [
         "<lib:sulong>",
-        "<lib:sulong++>",
       ],
       "ninja_install_targets" : ["install"],
       "results" : [
         "bin/<lib:sulong>",
-        "bin/<lib:sulong++>",
       ],
       "buildDependencies" : [
         "sdk:LLVM_TOOLCHAIN",
@@ -725,45 +723,6 @@ suite = {
       },
       "license" : "BSD-new",
     },
-    "com.oracle.truffle.llvm.libraries.bitcode.libcxx" : {
-      "subDir" : "projects",
-      "vpath" : True,
-      "sourceDir" : "<path:sdk:LLVM_ORG_SRC>/llvm",
-      "class" : "CMakeNinjaProject",
-      # NinjaBuildTask uses only 1 job otherwise
-      "max_jobs" : "8",
-      "ninja_targets" : ["<lib:c++abi>", "<lib:c++>"],
-      "ninja_install_targets" : ["install-libcxxabi", "install-libcxx"],
-      "results" : ["native"],
-      "cmakeConfig" : {
-        "LLVM_ENABLE_PROJECTS" : "libcxx;libcxxabi",
-        "LLVM_INCLUDE_DOCS" : "NO",
-        "LLVM_INCLUDE_BENCHMARKS": "NO",
-        "LLVM_TARGETS_TO_BUILD" : "X86",
-        "LIBCXXABI_INCLUDE_TESTS": "NO",
-        "LIBCXXABI_LINK_TESTS_WITH_SHARED_LIBCXX" : "YES",
-        "LIBCXXABI_LIBCXX_INCLUDES" : "<path:sdk:LLVM_ORG_SRC>/libcxx/include",
-        "LIBCXXABI_LIBCXX_PATH" : "<path:sdk:LLVM_ORG_SRC>/libcxx",
-        "LIBCXXABI_ENABLE_STATIC" : "NO",
-        "LIBCXX_INCLUDE_BENCHMARKS": "NO",
-        "LIBCXX_INCLUDE_TESTS": "NO",
-        # using "default" will choose the in-tree version libc++abi and add a build dependency
-        # from libc++ to libc++abi
-        "LIBCXX_CXX_ABI" : "default",
-        "LIBCXX_ENABLE_STATIC" : "NO",
-        "LIBCXX_ENABLE_EXPERIMENTAL_LIBRARY" : "NO",
-        "CMAKE_C_COMPILER" : "<path:SULONG_BOOTSTRAP_TOOLCHAIN_NO_HOME>/bin/clang",
-        "CMAKE_CXX_COMPILER" : "<path:SULONG_BOOTSTRAP_TOOLCHAIN_NO_HOME>/bin/clang++",
-        "CMAKE_INSTALL_PREFIX" : "native",
-      },
-      "buildDependencies" : [
-        "sdk:LLVM_ORG_SRC",
-        "SULONG_BOOTSTRAP_TOOLCHAIN_NO_HOME",
-        "sdk:LLVM_TOOLCHAIN",
-        "NATIVE_MODE_SUPPORT",
-      ],
-      "clangFormat" : False,
-    },
 
     "com.oracle.truffle.llvm.tests.cmake" : {
       "description" : "Common CMake files",
@@ -1430,11 +1389,9 @@ suite = {
       "platformDependent" : True,
       "layout" : {
         "./": [
-          "dependency:com.oracle.truffle.llvm.libraries.bitcode.libcxx/*",
         ],
         "./native/lib/" : [
           "dependency:com.oracle.truffle.llvm.libraries.bitcode/bin/<lib:sulong>",
-          "dependency:com.oracle.truffle.llvm.libraries.bitcode/bin/<lib:sulong++>",
           "dependency:com.oracle.truffle.llvm.libraries.native/bin/*",
           "dependency:com.oracle.truffle.llvm.libraries.graalvm.llvm.libs/bin/*",
         ],
diff --git a/sulong/projects/com.oracle.truffle.llvm.libraries.bitcode/CMakeLists.txt b/sulong/projects/com.oracle.truffle.llvm.libraries.bitcode/CMakeLists.txt
index b59a2f8d82c..3266669d437 100644
--- a/sulong/projects/com.oracle.truffle.llvm.libraries.bitcode/CMakeLists.txt
+++ b/sulong/projects/com.oracle.truffle.llvm.libraries.bitcode/CMakeLists.txt
@@ -86,10 +86,3 @@ add_library(sulong SHARED
 target_include_directories(sulong PRIVATE ${GRAALVM_LLVM_INCLUDE_DIR})
 target_link_options(sulong PRIVATE -nostdlib)
 install(TARGETS sulong DESTINATION bin)
-
-add_library(sulong++ SHARED libsulongxx/exception_support.cpp)
-target_include_directories(sulong++ PRIVATE ${LIBCXX_SRC}/libcxx/src ${LIBCXX_SRC}/libcxxabi/src)
-target_compile_definitions(sulong++ PRIVATE LIBCXXABI_SILENT_TERMINATE)
-target_compile_options(sulong++ PRIVATE -std=c++11 -stdlib=libc++ -Wno-undefined-internal)
-target_link_options(sulong++ PRIVATE -stdlib=libc++ -Wno-undefined-internal)
-install(TARGETS sulong++ DESTINATION bin)
-- 
2.31.1


```

On 7b97b5c09468ec1a8c3187353b4781c38272a728 for TruffleRuby:

```diff
From 8c0dc93e3ae4ae8497d40e543a47361c7c04556e Mon Sep 17 00:00:00 2001
From: Chris Seaton <chris.seaton@shopify.com>
Date: Thu, 29 Apr 2021 23:44:25 +0100
Subject: [PATCH] FIX

---
 sulong/mx.sulong/suite.py                     | 42 -------------------
 .../CMakeLists.txt                            |  7 ----
 2 files changed, 49 deletions(-)

diff --git a/sulong/mx.sulong/suite.py b/sulong/mx.sulong/suite.py
index 31e864fa041..32b5c96b13e 100644
--- a/sulong/mx.sulong/suite.py
+++ b/sulong/mx.sulong/suite.py
@@ -619,12 +619,10 @@ suite = {
       "vpath" : True,
       "ninja_targets" : [
         "<lib:sulong>",
-        "<lib:sulong++>",
       ],
       "ninja_install_targets" : ["install"],
       "results" : [
         "bin/<lib:sulong>",
-        "bin/<lib:sulong++>",
       ],
       "buildDependencies" : [
         "sdk:LLVM_TOOLCHAIN",
@@ -716,44 +714,6 @@ suite = {
       },
       "license" : "BSD-new",
     },
-    "com.oracle.truffle.llvm.libraries.bitcode.libcxx" : {
-      "subDir" : "projects",
-      "vpath" : True,
-      "sourceDir" : "<path:sdk:LLVM_ORG_SRC>/llvm",
-      "class" : "CMakeNinjaProject",
-      # NinjaBuildTask uses only 1 job otherwise
-      "max_jobs" : "8",
-      "ninja_targets" : ["<lib:c++abi>", "<lib:c++>"],
-      "ninja_install_targets" : ["install-libcxxabi", "install-libcxx"],
-      "results" : ["native"],
-      "cmakeConfig" : {
-        "LLVM_ENABLE_PROJECTS" : "libcxx;libcxxabi",
-        "LLVM_INCLUDE_DOCS" : "NO",
-        "LLVM_TARGETS_TO_BUILD" : "X86",
-        "LIBCXXABI_INCLUDE_TESTS": "NO",
-        "LIBCXXABI_LINK_TESTS_WITH_SHARED_LIBCXX" : "YES",
-        "LIBCXXABI_LIBCXX_INCLUDES" : "<path:sdk:LLVM_ORG_SRC>/libcxx/include",
-        "LIBCXXABI_LIBCXX_PATH" : "<path:sdk:LLVM_ORG_SRC>/libcxx",
-        "LIBCXXABI_ENABLE_STATIC" : "NO",
-        "LIBCXX_INCLUDE_BENCHMARKS": "NO",
-        "LIBCXX_INCLUDE_TESTS": "NO",
-        # using "default" will choose the in-tree version libc++abi and add a build dependency
-        # from libc++ to libc++abi
-        "LIBCXX_CXX_ABI" : "default",
-        "LIBCXX_ENABLE_STATIC" : "NO",
-        "LIBCXX_ENABLE_EXPERIMENTAL_LIBRARY" : "NO",
-        "CMAKE_C_COMPILER" : "<path:SULONG_BOOTSTRAP_TOOLCHAIN_NO_HOME>/bin/clang",
-        "CMAKE_CXX_COMPILER" : "<path:SULONG_BOOTSTRAP_TOOLCHAIN_NO_HOME>/bin/clang++",
-        "CMAKE_INSTALL_PREFIX" : "native",
-      },
-      "buildDependencies" : [
-        "sdk:LLVM_ORG_SRC",
-        "SULONG_BOOTSTRAP_TOOLCHAIN_NO_HOME",
-        "sdk:LLVM_TOOLCHAIN",
-        "NATIVE_MODE_SUPPORT",
-      ],
-      "clangFormat" : False,
-    },
 
     "com.oracle.truffle.llvm.tests.debug.native" : {
       "subDir" : "tests",
@@ -1445,11 +1405,9 @@ suite = {
       "platformDependent" : True,
       "layout" : {
         "./": [
-          "dependency:com.oracle.truffle.llvm.libraries.bitcode.libcxx/*",
         ],
         "./native/lib/" : [
           "dependency:com.oracle.truffle.llvm.libraries.bitcode/bin/<lib:sulong>",
-          "dependency:com.oracle.truffle.llvm.libraries.bitcode/bin/<lib:sulong++>",
           "dependency:com.oracle.truffle.llvm.libraries.native/bin/*",
           "dependency:com.oracle.truffle.llvm.libraries.graalvm.llvm.libs/bin/*",
         ],
diff --git a/sulong/projects/com.oracle.truffle.llvm.libraries.bitcode/CMakeLists.txt b/sulong/projects/com.oracle.truffle.llvm.libraries.bitcode/CMakeLists.txt
index b59a2f8d82c..3266669d437 100644
--- a/sulong/projects/com.oracle.truffle.llvm.libraries.bitcode/CMakeLists.txt
+++ b/sulong/projects/com.oracle.truffle.llvm.libraries.bitcode/CMakeLists.txt
@@ -86,10 +86,3 @@ add_library(sulong SHARED
 target_include_directories(sulong PRIVATE ${GRAALVM_LLVM_INCLUDE_DIR})
 target_link_options(sulong PRIVATE -nostdlib)
 install(TARGETS sulong DESTINATION bin)
-
-add_library(sulong++ SHARED libsulongxx/exception_support.cpp)
-target_include_directories(sulong++ PRIVATE ${LIBCXX_SRC}/libcxx/src ${LIBCXX_SRC}/libcxxabi/src)
-target_compile_definitions(sulong++ PRIVATE LIBCXXABI_SILENT_TERMINATE)
-target_compile_options(sulong++ PRIVATE -std=c++11 -stdlib=libc++ -Wno-undefined-internal)
-target_link_options(sulong++ PRIVATE -stdlib=libc++ -Wno-undefined-internal)
-install(TARGETS sulong++ DESTINATION bin)
-- 
2.31.1


```

**Comment by chrisseaton** [comment] 2021-04-29 23:24
@rschatz it's not Ninja that makes the difference.

**Comment by rschatz** [comment] 2021-04-30 07:53
:(

Thanks for checking. So it's either the MacOS version or some other setup problem.

**Comment by rschatz** [comment] 2021-04-30 10:31
Ok, I updated my Mac to 11.3, and I can reproduce the problem. Looking into it...

**Comment by rschatz** [comment] 2021-04-30 13:11
Looks like it's specifically the MacOSX11.3 sdk. Looks like our LLVM toolchain build just doesn't work at all for C++ with that SDK. I still haven't found out why.

Not a real fix, but you can work around the issue by specifying `SDKROOT` manually to an older version, for example this works on my machine:
```
SDKROOT=/Library/Developer/CommandLineTools/SDKs/MacOSX11.1.sdk mx build
```

**Comment by rschatz** [comment] 2021-04-30 15:13
Looks like an include directory with C++ headers from the SDK appears on the include path on newer SDKs, and that's redundant with an include path from the LLVM toolchain we ship.

I haven't figured out how to prevent that, but I can offer you a workaround: You can just remove the headers from our shipped LLVM toolchain:
Just add `include/c++` to the excludes list here https://github.com/oracle/graal/blob/ec3ea38955a61bf2e70306e7291a5ff9f8da5196/sdk/mx.sdk/suite.py#L466

That's just a workaround, not a real solution, since it breaks the build on every other platform (including older MacOS SDKs). Also I'm not sure if the result of that build would work correctly on older MacOS versions.

**Comment by chrisseaton** [comment] 2021-05-02 00:03
I wasn't able to fix using `SDKROOT=/Library/Developer/CommandLineTools/SDKs/MacOSX11.1.sdk` for a copy of `MacOSX11.1.sdk` copied from an old computer - I guess it's a bit more complex in reality, maybe symlinks to other places and things.

**Comment by chrisseaton** [comment] 2021-05-03 14:51
Thanks https://github.com/oracle/graal/issues/3383#issuecomment-830165381 worked though.

**Comment by rschatz** [comment] 2021-05-05 19:11
Apparently this is a general issue with upstream LLVM too.

At least compiling a small c++ example fails with both our version of LLVM, and also with upstream LLVM 10 and 11. It works with upstream LLVM 12.

I am working on updating our LLVM toolchain to version 12, and that should solve this issue, but it might take a while. These major version updates always lead to some unexpected compatibility issues that we have to fix first.

**Comment by chrisseaton** [comment] 2021-05-05 20:07
We're at least not blocked from forward progress now. And we are successfully using C++ extensions.

Could we have something in mx to remove this include?

**Comment by rschatz** [comment] 2021-05-07 09:46
Looks like it's this issue: https://reviews.llvm.org/D89001
I'll try to backport that as a quick fix.

**Comment by rschatz** [comment] 2021-05-28 08:59
Should be fixed (https://github.com/oracle/graal/commit/5ffba7c6464624f6f395b484565c737594fd16e2, backported the upstream fix to LLVM 10). We'll update to LLVM 12 at a later time.

**Closed by rschatz** 2021-05-28 08:59 UTC
Labels: llvm
