### ISSUE TITLE
Exception on image build w/ invoke dynamic and Groovy

### ISSUE THREAD

**Issue by ascheman** [oracle/graal#1016] opened 2019-02-28 06:22 UTC
I have a project with groovy (and Spring and Lombok and other libs). Trying to create a native image out of it, I get the following exception:

```
Build on Server(pid: 38798, port: 51733)
[org.dukecon.server.formes2dukecon.formestodukecon:38798]    classlist:  18,338.19 ms
[org.dukecon.server.formes2dukecon.formestodukecon:38798]        (cap):   4,151.05 ms
[org.dukecon.server.formes2dukecon.formestodukecon:38798]        setup:   4,911.54 ms
Warning: class initialization of class org.codehaus.groovy.control.XStreamUtils failed with exception java.lang.NoClassDefFoundError: com/thoughtworks/xstream/io/HierarchicalStreamDriver. This class will be initialized at run time because either option --report-unsupported-elements-at-runtime or option --allow-incomplete-classpath is used for image building. Use the option --delay-class-initialization-to-runtime=org.codehaus.groovy.control.XStreamUtils to explicitly request delayed initialization of this class.
Warning: class initialization of class org.codehaus.groovy.control.XStreamUtils failed with exception java.lang.NoClassDefFoundError: com/thoughtworks/xstream/io/HierarchicalStreamDriver. This class will be initialized at run time because either option --report-unsupported-elements-at-runtime or option --allow-incomplete-classpath is used for image building. Use the option --delay-class-initialization-to-runtime=org.codehaus.groovy.control.XStreamUtils to explicitly request delayed initialization of this class.
Warning: class initialization of class org.codehaus.groovy.control.XStreamUtils failed with exception java.lang.NoClassDefFoundError: com/thoughtworks/xstream/io/HierarchicalStreamDriver. This class will be initialized at run time because either option --report-unsupported-elements-at-runtime or option --allow-incomplete-classpath is used for image building. Use the option --delay-class-initialization-to-runtime=org.codehaus.groovy.control.XStreamUtils to explicitly request delayed initialization of this class.
Warning: class initialization of class org.codehaus.groovy.control.XStreamUtils failed with exception java.lang.NoClassDefFoundError: com/thoughtworks/xstream/io/HierarchicalStreamDriver. This class will be initialized at run time because either option --report-unsupported-elements-at-runtime or option --allow-incomplete-classpath is used for image building. Use the option --delay-class-initialization-to-runtime=org.codehaus.groovy.control.XStreamUtils to explicitly request delayed initialization of this class.
Warning: class initialization of class org.codehaus.groovy.control.XStreamUtils failed with exception java.lang.NoClassDefFoundError: com/thoughtworks/xstream/io/HierarchicalStreamDriver. This class will be initialized at run time because either option --report-unsupported-elements-at-runtime or option --allow-incomplete-classpath is used for image building. Use the option --delay-class-initialization-to-runtime=org.codehaus.groovy.control.XStreamUtils to explicitly request delayed initialization of this class.
Warning: class initialization of class org.codehaus.groovy.control.XStreamUtils failed with exception java.lang.NoClassDefFoundError: com/thoughtworks/xstream/io/HierarchicalStreamDriver. This class will be initialized at run time because either option --report-unsupported-elements-at-runtime or option --allow-incomplete-classpath is used for image building. Use the option --delay-class-initialization-to-runtime=org.codehaus.groovy.control.XStreamUtils to explicitly request delayed initialization of this class.
Warning: class initialization of class org.codehaus.groovy.control.XStreamUtils failed with exception java.lang.NoClassDefFoundError: com/thoughtworks/xstream/io/HierarchicalStreamDriver. This class will be initialized at run time because either option --report-unsupported-elements-at-runtime or option --allow-incomplete-classpath is used for image building. Use the option --delay-class-initialization-to-runtime=org.codehaus.groovy.control.XStreamUtils to explicitly request delayed initialization of this class.
[org.dukecon.server.formes2dukecon.formestodukecon:38798]     analysis: 147,306.69 ms
Error: com.oracle.graal.pointsto.constraints.UnsupportedFeatureException: Invoke with MethodHandle argument could not be reduced to at most a single call: java.lang.invoke.MutableCallSite.<init>(MethodHandle)
Detailed message:
Error: com.oracle.graal.pointsto.constraints.UnsupportedFeatureException: Invoke with MethodHandle argument could not be reduced to at most a single call: java.lang.invoke.MutableCallSite.<init>(MethodHandle)
Trace:
        at parsing java.lang.invoke.SwitchPoint.<init>(SwitchPoint.java:124)
Call path from entry point to java.lang.invoke.SwitchPoint.<init>():
        at java.lang.invoke.SwitchPoint.<init>(SwitchPoint.java:123)
        at org.codehaus.groovy.vmplugin.v7.IndyInterface.invalidateSwitchPoints(IndyInterface.java:124)
        at org.codehaus.groovy.vmplugin.v7.Java7.invalidateCallSites(Java7.java:70)
        at org.codehaus.groovy.reflection.ClassInfo.incVersion(ClassInfo.java:130)
        at groovy.lang.MetaClassImpl.incVersion(MetaClassImpl.java:3542)
        at com.oracle.svm.reflect.MetaClassImpl_incVersion_9d01b8e1ce338987cd3a80782b75238de3bbab02_1077.invoke(Unknown Source)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:101)
        at org.codehaus.groovy.runtime.callsite.StaticMetaMethodSite$StaticMetaMethodSiteNoUnwrapNoCoerce.invoke(StaticMetaMethodSite.java:149)
        at org.codehaus.groovy.runtime.callsite.StaticMetaMethodSite.call(StaticMetaMethodSite.java:89)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:119)
        at org.dukecon.server.formes2dukecon.FormesToDukecon.main(FormesToDukecon.groovy:21)
        at com.oracle.svm.core.JavaMainWrapper.run(JavaMainWrapper.java:152)
        at com.oracle.svm.core.code.IsolateEnterStub.JavaMainWrapper_run_5087f5482cc9a6abc971913ece43acb471d2631b(generated:0)

com.oracle.svm.core.util.UserError$UserException: com.oracle.graal.pointsto.constraints.UnsupportedFeatureException: Invoke with MethodHandle argument could not be reduced to at most a single call: java.lang.invoke.MutableCallSite.<init>(MethodHandle)
Detailed message:
Error: com.oracle.graal.pointsto.constraints.UnsupportedFeatureException: Invoke with MethodHandle argument could not be reduced to at most a single call: java.lang.invoke.MutableCallSite.<init>(MethodHandle)
Trace:
        at parsing java.lang.invoke.SwitchPoint.<init>(SwitchPoint.java:124)
Call path from entry point to java.lang.invoke.SwitchPoint.<init>():
        at java.lang.invoke.SwitchPoint.<init>(SwitchPoint.java:123)
        at org.codehaus.groovy.vmplugin.v7.IndyInterface.invalidateSwitchPoints(IndyInterface.java:124)
        at org.codehaus.groovy.vmplugin.v7.Java7.invalidateCallSites(Java7.java:70)
        at org.codehaus.groovy.reflection.ClassInfo.incVersion(ClassInfo.java:130)
        at groovy.lang.MetaClassImpl.incVersion(MetaClassImpl.java:3542)
        at com.oracle.svm.reflect.MetaClassImpl_incVersion_9d01b8e1ce338987cd3a80782b75238de3bbab02_1077.invoke(Unknown Source)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:101)
        at org.codehaus.groovy.runtime.callsite.StaticMetaMethodSite$StaticMetaMethodSiteNoUnwrapNoCoerce.invoke(StaticMetaMethodSite.java:149)
        at org.codehaus.groovy.runtime.callsite.StaticMetaMethodSite.call(StaticMetaMethodSite.java:89)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:119)
        at org.dukecon.server.formes2dukecon.FormesToDukecon.main(FormesToDukecon.groovy:21)
        at com.oracle.svm.core.JavaMainWrapper.run(JavaMainWrapper.java:152)
        at com.oracle.svm.core.code.IsolateEnterStub.JavaMainWrapper_run_5087f5482cc9a6abc971913ece43acb471d2631b(generated:0)

        at com.oracle.svm.core.util.UserError.abort(UserError.java:67)
        at com.oracle.svm.hosted.NativeImageGenerator.runPointsToAnalysis(NativeImageGenerator.java:701)
        at com.oracle.svm.hosted.NativeImageGenerator.doRun(NativeImageGenerator.java:492)
        at com.oracle.svm.hosted.NativeImageGenerator.lambda$run$0(NativeImageGenerator.java:410)
        at java.util.concurrent.ForkJoinTask$AdaptedRunnableAction.exec(ForkJoinTask.java:1386)
        at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
        at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
        at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
        at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
Error: Processing image build request failed
```

It is an open source project and I will soon publish a version where you could see the error. I already took a look into the issue with @jtulach and he recommended to raise an issue here for further investigation.

**Comment by ascheman** [comment] 2019-02-28 07:02
How to reproduce the error:

* Check out the sample project with the specific branch
```
git clone https://github.com/dukecon/dukecon_server
cd dukecon_server
git checkout bug/graalvm-1016
```
* Perform a Maven build: `mvn clean package`
* Optionally run the desired main class: `java -cp converters/target/converters-1.6-SNAPSHOT.jar org.dukecon.server.formes2dukecon.FormesToDukecon` - it should do _nothing_
* Run the native-image conversion the first time:
```
native-image -cp converters/target/converters-1.6-SNAPSHOT.jar --report-unsupported-elements-at-runtime --allow-incomplete-classpath --delay-class-initialization-to-runtime=org.codehaus.groovy.control.XStreamUtils -H:+ReportExceptionStackTraces org.dukecon.server.formes2dukecon.FormesToDukecon
Build on Server(pid: 5759, port: 64543)*
[org.dukecon.server.formes2dukecon.formestodukecon:5759]    classlist:   9,086.70 ms
[org.dukecon.server.formes2dukecon.formestodukecon:5759]        (cap):   1,774.90 ms
[org.dukecon.server.formes2dukecon.formestodukecon:5759]        setup:   3,258.57 ms
Warning: class initialization of class groovy.grape.GrapeIvy failed with exception java.lang.NoClassDefFoundError: org/apache/ivy/core/module/descriptor/DependencyDescriptor. This class will be initialized at run time because either option --report-unsupported-elements-at-runtime or option --allow-incomplete-classpath is used for image building. Use the option --delay-class-initialization-to-runtime=groovy.grape.GrapeIvy to explicitly request delayed initialization of this class.
[org.dukecon.server.formes2dukecon.formestodukecon:5759]   (typeflow):  10,545.54 ms
[org.dukecon.server.formes2dukecon.formestodukecon:5759]    (objects):  21,167.69 ms
[org.dukecon.server.formes2dukecon.formestodukecon:5759]   (features):     331.02 ms
[org.dukecon.server.formes2dukecon.formestodukecon:5759]     analysis:  32,440.83 ms
[org.dukecon.server.formes2dukecon.formestodukecon:5759]     universe:     601.11 ms
[org.dukecon.server.formes2dukecon.formestodukecon:5759]      (parse):   2,631.95 ms
[org.dukecon.server.formes2dukecon.formestodukecon:5759]     (inline):   7,275.49 ms
[org.dukecon.server.formes2dukecon.formestodukecon:5759]    (compile):  20,176.70 ms
[org.dukecon.server.formes2dukecon.formestodukecon:5759]      compile:  32,035.84 ms
[org.dukecon.server.formes2dukecon.formestodukecon:5759]        image:   4,830.11 ms
[org.dukecon.server.formes2dukecon.formestodukecon:5759]        write:     943.25 ms
[org.dukecon.server.formes2dukecon.formestodukecon:5759]      [total]:  83,470.43 ms
```
* Although it will happily create the image, the image will not run by now due to another error:
```
./org.dukecon.server.formes2dukecon.formestodukecon
Exception in thread "main" groovy.lang.MissingMethodException: No signature of method: static java.time.LocalDate.now() is applicable for argument types: () values: []
Possible solutions: next(), any(), tap(groovy.lang.Closure), use([Ljava.lang.Object;), is(java.lang.Object), any(groovy.lang.Closure)
        at groovy.lang.MetaClassImpl.invokeStaticMissingMethod(MetaClassImpl.java:1525)
        at groovy.lang.MetaClassImpl.invokeStaticMethod(MetaClassImpl.java:1511)
        at org.codehaus.groovy.runtime.callsite.StaticMetaClassSite.call(StaticMetaClassSite.java:50)
        at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:115)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:119)
        at org.dukecon.server.formes2dukecon.FormesToDukecon.main(FormesToDukecon.groovy:21)
```
* Now perform the `native-image` create again to get the error
```
native-image -cp converters/target/converters-1.6-SNAPSHOT.jar --report-unsupported-elements-at-runtime --allow-incomplete-classpath --delay-class-initialization-to-runtime=org.codehaus.groovy.control.XStreamUtils -H:+ReportExceptionStackTraces org.dukecon.server.formes2dukecon.FormesToDukecon
...
```
* I can reproduce both errors by stopping the `NativeImageBuildServer` so I guess it is a problem in the build server daemon?
* Btw: I am using `graalvm-ce-1.0.0-rc12` on OS X: `Darwin godestorm 18.2.0 Darwin Kernel Version 18.2.0: Thu Dec 20 20:46:53 PST 2018; root:xnu-4903.241.1~1/RELEASE_X86_64 x86_64`

**Comment by cstancu** [comment] 2019-03-01 07:08
I am unable to replicate the issue. When I try `mvn clean package` I get:
```
[FATAL] Non-resolvable parent POM for org.dukecon:dukecon-server:1.6-SNAPSHOT: Could not transfer artifact org.springframework.boot:spring-boot-starter-parent:pom:2.1.2.RELEASE from/to dukecon (${nexus.repository.prot}://${nexus.repository.host}${nexus.repository.port}${nexus.repository.base}/content/groups/public/): Cannot access ${nexus.repository.prot}://${nexus.repository.host}${nexus.repository.port}${nexus.repository.base}/content/groups/public/ with type default using the available connector factories: BasicRepositoryConnectorFactory and 'parent.relativePath' points at wrong local POM @ line 6, column 13
```

Did you push all your changes out? In the meantime, looking at your report I can say:

1. If you think that the problem is with the build server you can disable it with `native-image --no-server ...`. (Running `native-image --help-extra` will show you more options regarding the build server.)

2. From the image build failure I see that you get `Invoke with MethodHandle argument could not be reduced to at most a single call` errors. The native-image `MethodHandle` support is limited to cases where the `MethodHandle` object is a compile time constant. In that case we can constant fold and recursively inline until we get to a concrete method invocation. There is more work to be done to gracefully recover when we find a non-constant `MethodHandle` argument during image build time and report the problem at runtime instead. This can pose problems with `groovy` and other language implementations that rely heavily on the `MethodHandle` API.

3. In general for `groovy` we should be able to run most workloads as long as you use static compilation, i.e., either `@CompileStatic` for methods/types or per application using a compiler configuration like:
```
    import groovy.transform.CompileStatic
    withConfig(configuration) {
        ast(CompileStatic)
    }
```

4. The runtime error that you see when you succesfuly build an image `groovy.lang.MissingMethodException: No signature of method: static java.time.LocalDate.now() is applicable for argument types: () values: []` is most likely due to the fact that you are missing some reflection configuration. You can read more about reflection configurations [here](https://github.com/oracle/graal/blob/master/substratevm/REFLECTION.md).

**Comment by ascheman** [comment] 2019-03-05 07:01
Thanks so far!

I have fixed the repositories problem in the POM - it always worked since I do have a mirroring `settings.xml` locally as well as on my Jenkins.

The `@CompileStatic` seems to have fixed the sample now: The generated static binary does not abort anymore.

Will try to get a more complex code sample working.

**Comment by JaroslavTulach** [comment] 2019-03-05 15:16
Glad to hear the sample started working!

**Comment by cstancu** [comment] 2019-03-05 16:55
@ascheman thank you for reporting back! I'll close this issue for now, please reopen if you run into the same problem or open new issue if you have further problems.

**Closed by cstancu** 2019-03-05 16:55 UTC
Labels: substrate
