### ISSUE TITLE
Incompatible change of initialization policy for java.io.RandomAccessFile

### ISSUE THREAD

**Issue by mipastgt** [oracle/graal#2901] opened 2020-10-06 15:30 UTC
**Describe the issue**
When I build an application of mine via Gluons client-maven-plugin (JavaFX toolchain, but probably not relevant to this issue) I get the following exception at the end of the native-image build:
```
[Di. Okt. 06 17:02:18 MESZ 2020][INFO] [SUB] Error: Incompatible change of initialization policy for java.io.RandomAccessFile: trying to change RERUN for JDK native code support via JNI to BUILD_TIME super type of org.apache.fontbox.ttf.BufferedRandomAccessFile
[Di. Okt. 06 17:02:18 MESZ 2020][INFO] [SUB] com.oracle.svm.core.util.UserError$UserException: Incompatible change of initialization policy for java.io.RandomAccessFile: trying to change RERUN for JDK native code support via JNI to BUILD_TIME super type of org.apache.fontbox.ttf.BufferedRandomAccessFile
[Di. Okt. 06 17:02:18 MESZ 2020][INFO] [SUB] 	at com.oracle.svm.core.util.UserError.abort(UserError.java:68)
[Di. Okt. 06 17:02:18 MESZ 2020][INFO] [SUB] 	at com.oracle.svm.hosted.classinitialization.ClassInitializationConfiguration.insertRec(ClassInitializationConfiguration.java:99)
[Di. Okt. 06 17:02:18 MESZ 2020][INFO] [SUB] 	at com.oracle.svm.hosted.classinitialization.ClassInitializationConfiguration.insertRec(ClassInitializationConfiguration.java:113)
[Di. Okt. 06 17:02:18 MESZ 2020][INFO] [SUB] 	at com.oracle.svm.hosted.classinitialization.ClassInitializationConfiguration.insertRec(ClassInitializationConfiguration.java:113)
[Di. Okt. 06 17:02:18 MESZ 2020][INFO] [SUB] 	at com.oracle.svm.hosted.classinitialization.ClassInitializationConfiguration.insertRec(ClassInitializationConfiguration.java:113)
[Di. Okt. 06 17:02:18 MESZ 2020][INFO] [SUB] 	at com.oracle.svm.hosted.classinitialization.ClassInitializationConfiguration.insert(ClassInitializationConfiguration.java:64)
[Di. Okt. 06 17:02:18 MESZ 2020][INFO] [SUB] 	at com.oracle.svm.hosted.classinitialization.ConfigurableClassInitialization.forceInitializeHosted(ConfigurableClassInitialization.java:472)
[Di. Okt. 06 17:02:18 MESZ 2020][INFO] [SUB] 	at com.oracle.svm.hosted.classinitialization.ConfigurableClassInitialization.forceInitializeHosted(ConfigurableClassInitialization.java:476)
[Di. Okt. 06 17:02:18 MESZ 2020][INFO] [SUB] 	at com.oracle.svm.hosted.classinitialization.ClassInitializationFeature.lambda$initializeSafeDelayedClasses$11(ClassInitializationFeature.java:319)
[Di. Okt. 06 17:02:18 MESZ 2020][INFO] [SUB] 	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
[Di. Okt. 06 17:02:18 MESZ 2020][INFO] [SUB] 	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:177)
[Di. Okt. 06 17:02:18 MESZ 2020][INFO] [SUB] 	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:177)
[Di. Okt. 06 17:02:18 MESZ 2020][INFO] [SUB] 	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:177)
[Di. Okt. 06 17:02:18 MESZ 2020][INFO] [SUB] 	at java.base/java.util.HashMap$KeySpliterator.forEachRemaining(HashMap.java:1603)
[Di. Okt. 06 17:02:18 MESZ 2020][INFO] [SUB] 	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
[Di. Okt. 06 17:02:18 MESZ 2020][INFO] [SUB] 	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
[Di. Okt. 06 17:02:18 MESZ 2020][INFO] [SUB] 	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
[Di. Okt. 06 17:02:18 MESZ 2020][INFO] [SUB] 	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
[Di. Okt. 06 17:02:18 MESZ 2020][INFO] [SUB] 	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
[Di. Okt. 06 17:02:18 MESZ 2020][INFO] [SUB] 	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:497)
[Di. Okt. 06 17:02:18 MESZ 2020][INFO] [SUB] 	at com.oracle.svm.hosted.classinitialization.ClassInitializationFeature.initializeSafeDelayedClasses(ClassInitializationFeature.java:316)
[Di. Okt. 06 17:02:18 MESZ 2020][INFO] [SUB] 	at com.oracle.svm.hosted.classinitialization.ClassInitializationFeature.afterAnalysis(ClassInitializationFeature.java:256)
[Di. Okt. 06 17:02:18 MESZ 2020][INFO] [SUB] 	at com.oracle.svm.hosted.NativeImageGenerator.lambda$runPointsToAnalysis$9(NativeImageGenerator.java:753)
[Di. Okt. 06 17:02:18 MESZ 2020][INFO] [SUB] 	at com.oracle.svm.hosted.FeatureHandler.forEachFeature(FeatureHandler.java:70)
[Di. Okt. 06 17:02:18 MESZ 2020][INFO] [SUB] 	at com.oracle.svm.hosted.NativeImageGenerator.runPointsToAnalysis(NativeImageGenerator.java:753)
[Di. Okt. 06 17:02:18 MESZ 2020][INFO] [SUB] 	at com.oracle.svm.hosted.NativeImageGenerator.doRun(NativeImageGenerator.java:555)
[Di. Okt. 06 17:02:18 MESZ 2020][INFO] [SUB] 	at com.oracle.svm.hosted.NativeImageGenerator.lambda$run$0(NativeImageGenerator.java:468)
[Di. Okt. 06 17:02:18 MESZ 2020][INFO] [SUB] 	at java.base/java.util.concurrent.ForkJoinTask$AdaptedRunnableAction.exec(ForkJoinTask.java:1407)
[Di. Okt. 06 17:02:18 MESZ 2020][INFO] [SUB] 	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
[Di. Okt. 06 17:02:18 MESZ 2020][INFO] [SUB] 	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
[Di. Okt. 06 17:02:18 MESZ 2020][INFO] [SUB] 	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
[Di. Okt. 06 17:02:18 MESZ 2020][INFO] [SUB] 	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
[Di. Okt. 06 17:02:18 MESZ 2020][INFO] [SUB] 	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
[Di. Okt. 06 17:02:18 MESZ 2020][INFO] [SUB] Error: Image build request failed with exit status 1
[Di. Okt. 06 17:02:18 MESZ 2020][INFO] [SUB] com.oracle.svm.driver.NativeImage$NativeImageError: Image build request failed with exit status 1
[Di. Okt. 06 17:02:18 MESZ 2020][INFO] [SUB] 	at com.oracle.svm.driver.NativeImage.showError(NativeImage.java:1558)
[Di. Okt. 06 17:02:18 MESZ 2020][INFO] [SUB] 	at com.oracle.svm.driver.NativeImage.build(NativeImage.java:1308)
[Di. Okt. 06 17:02:18 MESZ 2020][INFO] [SUB] 	at com.oracle.svm.driver.NativeImage.performBuild(NativeImage.java:1269)
[Di. Okt. 06 17:02:18 MESZ 2020][INFO] [SUB] 	at com.oracle.svm.driver.NativeImage.main(NativeImage.java:1228)
[Di. Okt. 06 17:02:18 MESZ 2020][INFO] [SUB] 	at com.oracle.svm.driver.NativeImage$JDK9Plus.main(NativeImage.java:1740)
```
The problem seems to be in some external code inside of apaches PDFBox (2.0.20) which I am using in my program.

**Describe GraalVM and your environment:**
 - GraalVM version graalvm-ce-java11-20.2.0
 - JDK major version: 11
 - OS: macOS Mojava 10.14.6
 - Architecture: AMD64

**Comment by fernando-valdez** [comment] 2020-10-06 15:36
Hello @mipastgt, 
Thanks for reporting this issue.
Can you please share a reproducer?

**Comment by mipastgt** [comment] 2020-10-06 17:02
I don't have a reproducer right now because this happened in a large project outside of my own code. I thought you might just have a look at the two relevant classes (which are both available on the internet) and see immediately what's going wrong.

**Comment by mipastgt** [comment] 2020-10-07 10:14
Here is a trivial and tiny example maven project which reproduces the issue.
Just call `mvn clean package` to reproduce the bug.
[PDFBoxBugReport.zip](https://github.com/oracle/graal/files/5339760/PDFBoxBugReport.zip)
I hope this helps to fix the problem.

**Comment by mipastgt** [comment] 2020-10-16 13:49
Does a similar fix like in this issue https://github.com/oracle/graal/issues/1462 also apply here?

**Comment by fernando-valdez** [comment] 2021-06-15 20:22
Hello @mipastgt,
I tested again the reproducer, but this time I used GraalVM 21.1.0 Java 11. The problem seems to be fixed in this version.
I also removed the following flags from the pom file:  `-H:+TraceClassInitialization` `-H:+IncludeAllTimeZones`

**Closed by fernando-valdez** 2021-06-15 20:22 UTC
Labels: bug, native-image
