### ISSUE TITLE
VM bug in EE: failed bzip2 decompression

### ISSUE THREAD

**Issue by arlebedev** [oracle/graal#2534] opened 2020-06-03 06:59 UTC
Using Apache commons-compress to read BZip2 file causes this error:
```
09:43:05.054 [main] ERROR STDERR - Exception in thread "main" java.io.IOException: BZip2 CRC error
09:43:05.055 [main] ERROR STDERR - 	at org.apache.commons.compress@1.20/org.apache.commons.compress.compressors.bzip2.BZip2CompressorInputStream.endBlock(BZip2CompressorInputStream.java:349)
09:43:05.055 [main] ERROR STDERR - 	at org.apache.commons.compress@1.20/org.apache.commons.compress.compressors.bzip2.BZip2CompressorInputStream.setupNoRandPartA(BZip2CompressorInputStream.java:828)
09:43:05.055 [main] ERROR STDERR - 	at org.apache.commons.compress@1.20/org.apache.commons.compress.compressors.bzip2.BZip2CompressorInputStream.setupNoRandPartB(BZip2CompressorInputStream.java:877)
09:43:05.055 [main] ERROR STDERR - 	at org.apache.commons.compress@1.20/org.apache.commons.compress.compressors.bzip2.BZip2CompressorInputStream.read0(BZip2CompressorInputStream.java:229)
09:43:05.055 [main] ERROR STDERR - 	at org.apache.commons.compress@1.20/org.apache.commons.compress.compressors.bzip2.BZip2CompressorInputStream.read(BZip2CompressorInputStream.java:177)
09:43:05.055 [main] ERROR STDERR - 	at java.base/java.io.InputStream.read(InputStream.java:205)
```
```kotlin
val input = BZip2CompressorInputStream(Files.newInputStream(Paths.get(filePath)))
val buf = ByteArray(0x4000)
while (true) {
    input.read(buf)
}
```
Just create `BZip2CompressorInputStream` and read everything from it on any big bz2 file (mine is several GB, but it occurs on reading some first ~100MB). Decompressed data integrity also looks suspicious (I did not check, but I see parsing errors in my app before the error which are not present on other VMs), probably some test with checksum verification should be created.
It is only enterprise edition bug, community edition as well as OpenJDK do not have this bug.
Reproduced on EE 19.3.1 and EE 20.0.1 on Ubuntu 18.04.4 AMD64.
Other evidence found: https://i.reddit.com/r/admincraft/comments/fwhvu7/anyone_having_problems_starting_a_fresh_papermc/

**Comment by davleopo** [comment] 2020-06-03 13:23
@arlebedev thanks for the bug report, I can reproduce the issue with a simple java program following your example. I will start investigating!

**Comment by gergo-** [comment] 2020-06-08 15:02
Thanks for the report and the reproducer, @arlebedev. A fix for this will appear in GraalVM EE 20.2.0 and probably also in 19.3.3 and 20.1.1. Until then you can work around this by passing `-Dgraal.VectorizeNegativeStride=false` on the command line.

**Comment by budgidiere** [comment] 2020-11-22 20:00
This error is still happening on 20.3.0 EE. Any word on it being fixed?

**Comment by gergo-** [comment] 2020-11-23 09:54
Thanks for this report. I can confirm that this is still happening, and I'm investigating.

**Comment by gergo-** [comment] 2020-11-27 16:48
Thanks again for reporting this @budgidiere. This is a new variant of the original problem. A new fix for this problem will be included in the 21.0.0 and 20.3.1 releases scheduled for January 19th. The 19.3.x series should not be affected by this new variant of the problem, which was caused by an interaction of my original fix with later changes on the 20.x tree.
As before, the workaround is to pass `-Dgraal.VectorizeNegativeStride=false` on the command line.

**Closed by gergo-** 2020-11-27 16:48 UTC
Labels: bug, compiler

**Comment by budgidiere** [comment] 2020-11-30 02:53
Thank you.

**Comment by duplexsystem** [comment] 2021-01-19 22:51
I just tested 21.0.0 EE and I no longer have to use `-Dgraal.VectorizeNegativeStride=false`. Issue is resolved.
