### ISSUE TITLE
Native executable Startup slow for first time

### ISSUE THREAD

**Issue by halimpuckjava** [oracle/graal#3658] opened 2021-08-08 13:14 UTC
hi

when generate a native executable (spring boot application) with graalvm 21.1.0.r8-grl, for the first time is take +3 sec to startup (too slow) however in second startup it take <= 100 ms

![Screenshot from 2021-08-08 14-06-04](https://user-images.githubusercontent.com/20538231/128633148-c86b82c7-42c3-4d95-be7f-25d7e5e2735f.png)
![Screenshot from 2021-08-08 14-05-47](https://user-images.githubusercontent.com/20538231/128633150-145aab25-d56c-45b5-b78a-5c4092f88809.png)

**Comment by rodrigar-mx** [comment] 2021-08-10 18:01
Hi @halimpuckjava. Should not be the case. Could you please share a reproducer?

**Comment by halimpuckjava** [comment] 2021-08-10 20:00
pox.xml
```
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>
	<parent>
		<groupId>org.springframework.boot</groupId>
		<artifactId>spring-boot-starter-parent</artifactId>
		<version>2.5.3</version>
		<relativePath/> <!-- lookup parent from repository -->
	</parent>
	<groupId>com.example</groupId>
	<artifactId>demo</artifactId>
	<version>0.0.1-SNAPSHOT</version>
	<name>demo</name>
	<description>Demo project for Spring Boot</description>
	<properties>
		<java.version>1.8</java.version>
		<repackage.classifier/>
		<maven.test.skip>true</maven.test.skip>
		<kotlin.version>1.5.21</kotlin.version>
		<spring-native.version>0.10.2</spring-native.version>
	</properties>
	<dependencies>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-data-r2dbc</artifactId>
		</dependency>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-webflux</artifactId>
		</dependency>
		<dependency>
			<groupId>com.fasterxml.jackson.module</groupId>
			<artifactId>jackson-module-kotlin</artifactId>
		</dependency>
		<dependency>
			<groupId>io.projectreactor.kotlin</groupId>
			<artifactId>reactor-kotlin-extensions</artifactId>
		</dependency>
		<dependency>
			<groupId>org.jetbrains.kotlin</groupId>
			<artifactId>kotlin-reflect</artifactId>
		</dependency>
		<dependency>
			<groupId>org.jetbrains.kotlin</groupId>
			<artifactId>kotlin-stdlib-jdk8</artifactId>
		</dependency>
		<dependency>
			<groupId>org.jetbrains.kotlinx</groupId>
			<artifactId>kotlinx-coroutines-reactor</artifactId>
		</dependency>
		<dependency>
			<groupId>org.springframework.experimental</groupId>
			<artifactId>spring-native</artifactId>
			<version>0.10.2</version>
		</dependency>

		<!--<dependency>
			<groupId>com.h2database</groupId>
			<artifactId>h2</artifactId>
			<scope>runtime</scope>
		</dependency>
		<dependency>
			<groupId>io.r2dbc</groupId>
			<artifactId>r2dbc-h2</artifactId>
			<scope>runtime</scope>
		</dependency>-->
		<dependency>
			<groupId>io.r2dbc</groupId>
			<artifactId>r2dbc-postgresql</artifactId>
			<scope>runtime</scope>
		</dependency>
		<dependency>
			<groupId>org.postgresql</groupId>
			<artifactId>postgresql</artifactId>
			<scope>runtime</scope>
		</dependency>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-test</artifactId>
			<scope>test</scope>
		</dependency>
		<dependency>
			<groupId>io.projectreactor</groupId>
			<artifactId>reactor-test</artifactId>
			<scope>test</scope>
		</dependency>
	</dependencies>

	<build>
		<sourceDirectory>${project.basedir}/src/main/kotlin</sourceDirectory>
		<testSourceDirectory>${project.basedir}/src/test/kotlin</testSourceDirectory>
		<plugins>
			<plugin>
				<groupId>org.springframework.boot</groupId>
				<artifactId>spring-boot-maven-plugin</artifactId>
				<configuration>
					<classifier>${repackage.classifier}</classifier>
					<image>
						<builder>paketobuildpacks/builder:tiny</builder>
						<env>
							<BP_NATIVE_IMAGE>true</BP_NATIVE_IMAGE>
						</env>
					</image>
				</configuration>
			</plugin>
			<plugin>
				<groupId>org.jetbrains.kotlin</groupId>
				<artifactId>kotlin-maven-plugin</artifactId>
				<configuration>
					<args>
						<arg>-Xjsr305=strict</arg>
					</args>
					<compilerPlugins>
						<plugin>spring</plugin>
					</compilerPlugins>
				</configuration>
				<dependencies>
					<dependency>
						<groupId>org.jetbrains.kotlin</groupId>
						<artifactId>kotlin-maven-allopen</artifactId>
						<version>${kotlin.version}</version>
					</dependency>
				</dependencies>
			</plugin>
			<plugin>
				<groupId>org.springframework.experimental</groupId>
				<artifactId>spring-aot-maven-plugin</artifactId>
				<version>0.10.2</version>
				<executions>
					<execution>
						<id>test-generate</id>
						<goals>
							<goal>test-generate</goal>
						</goals>
					</execution>
					<execution>
						<id>generate</id>
						<goals>
							<goal>generate</goal>
						</goals>
					</execution>
				</executions>
			</plugin>
		</plugins>
	</build>
	<repositories>
		<repository>
			<id>spring-release</id>
			<name>Spring release</name>
			<url>https://repo.spring.io/release</url>
		</repository>
	</repositories>

	<pluginRepositories>
		<pluginRepository>
			<id>spring-release</id>
			<name>Spring release</name>
			<url>https://repo.spring.io/release</url>
		</pluginRepository>
	</pluginRepositories>

	<profiles>
		<profile>
			<id>native</id>
			<properties>
				<repackage.classifier>exec</repackage.classifier>
				<native-buildtools.version>0.9.1</native-buildtools.version>
			</properties>
			<dependencies>
				<dependency>
					<groupId>org.graalvm.buildtools</groupId>
					<artifactId>junit-platform-native</artifactId>
					<version>0.9.1</version>
					<scope>test</scope>
				</dependency>
			</dependencies>
			<build>
				<plugins>
					<plugin>
						<groupId>org.graalvm.buildtools</groupId>
						<artifactId>native-maven-plugin</artifactId>
						<version>0.9.1</version>
						<executions>
							<execution>
								<id>test-native</id>
								<phase>test</phase>
								<goals>
									<goal>test</goal>
								</goals>
							</execution>
							<execution>
								<id>build-native</id>
								<phase>package</phase>
								<goals>
									<goal>build</goal>
								</goals>
							</execution>
						</executions>
					</plugin>
				</plugins>
			</build>
		</profile>
	</profiles>

</project>
```

DemoApp.kt 
```
data class Person(@Id val id: Int, val name: String)

@SpringBootApplication
@TypeHint(types = [Person::class], typeNames = ["com.example.demo.Person"])
class DemoApplication

interface PersonRepository : CoroutineCrudRepository<Person, Int>

val routing = beans {
	bean {
		coRouter {
			val personRepository = ref<PersonRepository>()
			GET("") { ok().bodyAndAwait(personRepository.findAll()) }
			GET("/person/{id}") { it.pathVariable("id").let { ok().bodyValueAndAwait(personRepository.findById(it.toInt()) ?: throw Exception("Person not found")) } }
			POST("/save") { ok().bodyValueAndAwait(personRepository.save(Person(id = 10, name = "layla"))) }
		}
	}
}

fun main() {
	runApplication<DemoApplication> {
		addInitializers(routing)
	}
}
```

i use kotlin 1.5.21,  spring boot 2.5.3,  graalvm 21.1.0-r8 (default jdk)

**Comment by rodrigar-mx** [comment] 2021-08-11 23:41
Hi @halimpuckjava. I reproduced your demo application, and I launch it in approximately 100ms the first time. Similar time in subsequent launches. Let me analyze possible causes why on your side is taking more time. As an extra suggestion, I encourage you using graalvm with java 11. Native Image on Java 8 has only 50% of the features compared to Java 11. Since the output is anyhow a binary executable (or a shared library), all of the performance tunings are done on Java 11+, making it faster. It would be wise to base all further development with Native Image on Java 11+.

**Comment by halimpuckjava** [comment] 2021-08-12 10:13
hi @rodrigar-mx  i will try your suggestion

**Comment by halimpuckjava** [comment] 2021-08-12 17:26
hi @rodrigar-mx 

i try with java 11 (graalvm 21.2.0.r11-grl), after generation of native build, i start more fast (then java 8) less 80 ms, however after restart my computer and launch it again it take too mauch time +5 sec
![Screenshot from 2021-08-12 18-22-18](https://user-images.githubusercontent.com/20538231/129240761-de56282b-799c-4d86-b3c2-b56a4d3d8d6a.png)

for second launch it take 50 ms
![Screenshot from 2021-08-12 18-24-13](https://user-images.githubusercontent.com/20538231/129241260-1d75df60-442c-45ff-b208-e0e08c6aba23.png)

**Comment by rodrigar-mx** [comment] 2021-08-12 20:47
First launch after system restart:
![image](https://user-images.githubusercontent.com/87209110/129266586-2df747cb-ddf7-4279-97ee-40669cae0eca.png)
Second launch after system restart:
![image-1](https://user-images.githubusercontent.com/87209110/129266597-400369fa-9e7f-4167-a762-bc047825a463.png)
Maybe the great difference relates to your machine or OS. I tested it in both MacOS and Linux, and I never exceeded more than half a second. Have you tried testing other native executable or launching your app in a different machine?

**Comment by halimpuckjava** [comment] 2021-08-12 21:48
@rodrigar-mx  thanks for replay

my OS is Ubuntu 21.04, maybe this version of Ubuntu has some issue, please what distribution & version of Linux you make your tests ?

**Comment by rodrigar-mx** [comment] 2021-08-12 21:53
I use OracleLinux 7.9. Let me test also in Ubuntu inside a VM.

**Comment by rodrigar-mx** [comment] 2021-08-13 17:21
Tried in Ubuntu 20.04 and still fast. Immediately just after system reboot may be slow (1s for me) because other services are still starting and processes are competing for system resources, but if you wait some seconds it should be fast as always (~100ms). Please take a closer look to your system processes during start up. I will close the issue because I do not found any problems, but please feel free to reopen it for any inquiry.

**Closed by rodrigar-mx** 2021-08-13 17:21 UTC
Labels: feature
