### ISSUE TITLE
Compiling Truffle Languages Causes "Unexpected number of values in state to merge.  Please report this problem."

### ISSUE THREAD

**Issue by smarr** [oracle/graal#4494] opened 2022-04-14 23:59 UTC
As previously reported on Slack: https://graalvm.slack.com/archives/CMY62M6FM/p1647383947905679
I am running into issues compiling Truffle-based languages with the native image compiler.

@lewurm https://github.com/oracle/graal/commit/f638f17227a41757d00d00526d496e6183ae30d2 would be related, though it's not a fix.

Currently, I am seeing for instance:

```
Failed generating 'som-native' after 1m 18s.
Fatal error: com.oracle.svm.core.util.VMError$HostedError: Unexpected number of values in state to merge. Please report this problem.
****Merge FrameState****
com.oracle.truffle.api.TruffleStackTrace$LazyStackTrace.toString(TruffleStackTrace.java:386) [bci: 33]
locals: [_]
stack: [44]
locks: []
************************
bci: 33, duringCall: false, rethrowException: false
DeoptSourceFrameInfo: locals-1, stack-2, locks-0.
Merge FrameState: locals-1, stack-1, locks-0.
	at com.oracle.svm.core.util.VMError.shouldNotReachHere(VMError.java:68)
	at com.oracle.svm.hosted.code.CompilationInfoSupport$DeoptSourceFrameInfo.mergeStateInfo(CompilationInfoSupport.java:112)
	at com.oracle.svm.hosted.code.CompilationInfoSupport.lambda$registerDeoptEntry$2(CompilationInfoSupport.java:175)
	at java.base/java.util.concurrent.ConcurrentHashMap.compute(ConcurrentHashMap.java:1940)
	at com.oracle.svm.hosted.code.CompilationInfoSupport.registerDeoptEntry(CompilationInfoSupport.java:175)
	at com.oracle.svm.graal.hosted.GraalFeature.registerDeoptEntries(GraalFeature.java:786)
	at com.oracle.svm.graal.hosted.GraalFeature.beforeCompilation(GraalFeature.java:723)
	at com.oracle.svm.hosted.NativeImageGenerator.lambda$doRun$4(NativeImageGenerator.java:623)
	at com.oracle.svm.hosted.FeatureHandler.forEachFeature(FeatureHandler.java:74)
	at com.oracle.svm.hosted.NativeImageGenerator.doRun(NativeImageGenerator.java:623)
	at com.oracle.svm.hosted.NativeImageGenerator.run(NativeImageGenerator.java:514)
	at com.oracle.svm.hosted.NativeImageGeneratorRunner.buildImage(NativeImageGeneratorRunner.java:407)
	at com.oracle.svm.hosted.NativeImageGeneratorRunner.build(NativeImageGeneratorRunner.java:585)
	at com.oracle.svm.hosted.NativeImageGeneratorRunner.main(NativeImageGeneratorRunner.java:128)
	at com.oracle.svm.hosted.NativeImageGeneratorRunner$JDK9Plus.main(NativeImageGeneratorRunner.java:615)
Error: Image build request failed with exit status 1
```

To reproduce:

```
git clone --recursive -b truffle-update https://github.com/smarr/SOMns
cd SOMns
ant native 
```

This will use a recent version of Graal in the `libs/truffle` git submodule.
For convenience, one may want to use `ant compile-native` to only use the native image builder to build the SOMns native image (assuming all dependency were already built).

The problem is similar on the TruffleSOM branch before put the string concatenation stuff behind a boundary. So, this is very likely related to string concatenation. The last commit on the `truffle-update` branch from above, is also putting a `@TruffleBoundary` on a concatenating method. Though, for the above issue, that's not an option.

**Comment by smarr** [comment] 2022-04-23 18:51
Just for context, there was an older issue here, which might be related: https://github.com/oracle/graal/issues/3448 

cc @teshull

**Comment by teshull** [comment] 2022-04-25 07:22
Yeah, this definitely looks related to string concatenation. String concatenation is disallowed in JIT code  - see https://github.com/oracle/graal/blob/c3a8400d83304360e9455f658ada21b94f92c58d/substratevm/src/com.oracle.svm.truffle/src/com/oracle/svm/truffle/TruffleFeature.java#L589.

However, it looks like now things are failing before the blocklist check is performed I guess. Soon I'll try to fix this error message

**Comment by smarr** [comment] 2022-04-25 08:49
Thanks, just a note: The issue will not reproduce directly on the mentioned branch.

In the meanwhile, I added a commit with various boundaries. So, the one before the last `cac44992f99b7585613269248807b6e90cc0d75f`, would reproduce it.

**Comment by teshull** [comment] 2022-06-13 09:41
We merged a changed over the weekend so that by default the blocklist check will be reached w/o this error message popping up. I confirmed this new behavior with your reproducer

**Closed by teshull** 2022-06-13 09:41 UTC
Labels: bug, native-image
