### ISSUE TITLE
Error on compilation of constant

### ISSUE THREAD

**Issue by codemonstur** [oracle/graal#1677] opened 2019-09-12 21:37 UTC
I get the error below when I try to compile a relatively simple project. The error refers to a constant that I declare like so `public static final RedisDb parsed_urls = newRedisDb(4);`.
The newRedisDb is a staticly imported function that wraps the number in a type like so:
```
    public interface RedisDb {
        int getId();

        static RedisDb newRedisDb(final int id) {
            return () -> id;
        }
    }
```
This constant really doesn't change at all ever. So the message that something has changed during runtime is baffling to me. This is the error:
```
[target/myapp:17]    classlist:  20,109.49 ms
[target/myapp:17]        (cap):   3,056.07 ms
[target/myapp:17]        setup:   6,985.39 ms
[target/myapp:17]   (typeflow):  32,717.95 ms
[target/myapp:17]    (objects):  10,862.09 ms
[target/myapp:17]   (features):     584.57 ms
[target/myapp:17]     analysis:  44,730.91 ms
[target/myapp:17]     (clinit):     757.05 ms
[target/myapp:17]     universe:   2,563.12 ms
[target/myapp:17]      (parse):   9,599.36 ms
[target/myapp:17]     (inline):  20,819.72 ms
[target/myapp:17]    (compile):  56,570.85 ms
[target/myapp:17]      compile:  88,918.13 ms
[target/myapp:17]        image:      12.15 ms
Fatal error: com.oracle.svm.core.util.VMError$HostedError: com.oracle.svm.core.util.UserError$UserException: Image heap writing found an object whose class was not seen as instantiated during static analysis. Did a static field or an object referenced from a static field change during native image generation? For example, a lazily initialized cache could have been initialized during image generation, in which case you need to force eager initialization of the cache before static analysis or reset the cache using a field value recomputation.
  object: common.db.Redis$RedisDb$$Lambda$296/1921408917@3f46325c of class: common.db.Redis$RedisDb$$Lambda$296/1921408917
  reachable through:
    root: HostedField<Constants.parsed_urls location: 264   AnalysisField<Constants.parsed_urls accessed: false reads: true written: true>>

        at com.oracle.svm.core.util.VMError.shouldNotReachHere(VMError.java:70)
        at com.oracle.svm.hosted.NativeImageGenerator.doRun(NativeImageGenerator.java:641)
        at com.oracle.svm.hosted.NativeImageGenerator.lambda$run$0(NativeImageGenerator.java:444)
        at java.util.concurrent.ForkJoinTask$AdaptedRunnableAction.exec(ForkJoinTask.java:1386)
        at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
        at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
        at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
        at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
Caused by: com.oracle.svm.core.util.UserError$UserException: Image heap writing found an object whose class was not seen as instantiated during static analysis. Did a static field or an object referenced from a static field change during native image generation? For example, a lazily initialized cache could have been initialized during image generation, in which case you need to force eager initialization of the cache before static analysis or reset the cache using a field value recomputation.
  object: common.db.Redis$RedisDb$$Lambda$296/1921408917@3f46325c of class: common.db.Redis$RedisDb$$Lambda$296/1921408917
  reachable through:
    root: HostedField<Constants.parsed_urls location: 264   AnalysisField<Constants.parsed_urls accessed: false reads: true written: true>>

        at com.oracle.svm.core.util.UserError.abort(UserError.java:65)
        at com.oracle.svm.hosted.image.NativeImageHeap.addObjectToBootImageHeap(NativeImageHeap.java:347)
        at com.oracle.svm.hosted.image.NativeImageHeap.addObject(NativeImageHeap.java:277)
        at com.oracle.svm.hosted.image.NativeImageHeap.addStaticFields(NativeImageHeap.java:177)
        at com.oracle.svm.hosted.image.NativeImageHeap.addInitialObjects(NativeImageHeap.java:106)
        at com.oracle.svm.hosted.NativeImageGenerator.doRun(NativeImageGenerator.java:619)
        ... 6 more
Error: Image build request failed with exit status 1
```
I'm using `oracle/graalvm-ce:19.2.0` and `native-image --static --no-server --no-fallback -jar target/$(JAR) target/$(IMAGE)`

**Comment by cstancu** [comment] 2020-09-25 05:22
The root cause of this issue has been fixed in the meantime.

**Closed by cstancu** 2020-09-25 05:22 UTC
Labels: native-image
