### ISSUE TITLE
Cannot resolve FileSystem root resource in Native Image

### ISSUE THREAD

**Issue by bclozel** [oracle/graal#5020] opened 2022-09-20 17:03 UTC
**Describe the issue**
When adding resources to the native image, the native image `FileSystemProvider` is used to resolve resources at runtime. The root directory of this file system is not available; this prevents applications from listing all available resources in the application.
This is being extracted from #1108, which conflates several issues.

**Steps to reproduce the issue**
Please include both build steps as well as run steps
1. `git clone git@github.com:bclozel/native-resources.git`
3. `./gradlew nativeCompile`

**Describe GraalVM and your environment:**
```
java -version
openjdk version "17.0.4" 2022-07-19
OpenJDK Runtime Environment GraalVM CE 22.2.0 (build 17.0.4+8-jvmci-22.2-b06)
OpenJDK 64-Bit Server VM GraalVM CE 22.2.0 (build 17.0.4+8-jvmci-22.2-b06, mixed mode, sharing)
```
 - CE 22.2.0
 - JDK major version: 17
 - OS: macOS Monterey
 - Architecture: AMD64

The [repo README explains how to reproduce the behavior step by step](https://github.com/bclozel/native-resources/blob/main/README.md).

Please tag this issue with the "Spring" tag.

**Comment by jovanstevanovic** [comment] 2022-09-21 15:40
Since you have permission, could you assign this issue to me? (and close #1108)

**Comment by bclozel** [comment] 2022-09-21 15:43
@jovanstevanovic Sorry I don't have permission on this repository.

**Comment by bclozel** [comment] 2022-09-26 14:08
I've updated my sample with a different yet related problem - how slashes are dealt with when walking the filesystem. I can create a different issue for this if you think this is a different problem; I'm not just familiar with this area, [see this section](https://github.com/bclozel/native-resources/blob/main/README.md#problem-2-looking-up-the-first-directory).

**Comment by sbrannen** [comment] 2022-09-26 14:40
@bclozel, doesn't it also fail if you run your example with `/first` or `/first/` (leading slash)?

I believe the issue is that `java.nio.file.FileSystem.getPath(String, String...)` in the native image implementation does not _clean_ the resulting path.

For example, when using the OS file system on a Mac, you can supply a trailing slash (`first/`), any number of leading slashes (`/first`, `/////first`), or a combination of both (`///first/`), and the standard `FileSystem` always returns `/first` as the path _within_ the file system.

**Comment by bclozel** [comment] 2022-09-26 14:59
@sbrannen No it doesn't fail in my sample

```
./build/native/nativeCompile/native-resources resource:/// /first
Sep 26, 2022 4:59:04 PM org.example.Main main
INFO: scheme: resource:///, root: /first
Sep 26, 2022 4:59:04 PM org.example.Main lambda$main$0
INFO: root directory: /
Sep 26, 2022 4:59:04 PM org.example.Main lambda$main$1
INFO: |- /first
Sep 26, 2022 4:59:04 PM org.example.Main lambda$main$1
INFO: |- /first/first.txt
```

**Comment by sbrannen** [comment] 2022-09-26 15:04
OK. Thanks for checking. I'll get back to you if I come up with anything else definitive.

**Comment by sbrannen** [comment] 2022-09-26 15:13
If you get a `Path` from the empty string `""` with the native image `FileSystem` (`fileSystem.getPath("")`) and then invoke `resolve(...)` on that `Path`, you get the following exception.

```
java.lang.ArrayIndexOutOfBoundsException: Index -1 out of bounds for length 0
       com.oracle.svm.core.jdk.resources.NativeImageResourcePath.resolve(NativeImageResourcePath.java:302)
       com.oracle.svm.core.jdk.resources.NativeImageResourcePath.resolve(NativeImageResourcePath.java:327)
```

Whereas, a `Path` created by the standard OS `FileSystem` does not throw an exception in that scenario.

**Comment by jovanstevanovic** [comment] 2022-09-26 15:26
The fix for root path resolution is on the merge queue.

Regarding trailing slashes and empty strings, I would suggest not merging them as a part of this issue, so please derivate all edge cases in separate GH issue(s), and I'll take a look afterward. 

@sbrannen What is the output (return value) in OS `FileSystem` with an empty string as an argument?  OOB exception is undoubtedly not something that you expect.

**Comment by sbrannen** [comment] 2022-09-26 16:08
> What is the output (return value) in OS `FileSystem` with an empty string as an argument? OOB exception is undoubtedly not something that you expect.

```java
System.out.println("FileSystems.getDefault().getPath(\"\"): [%s]".formatted(FileSystems.getDefault().getPath("")));
System.out.println("FileSystems.getDefault().getPath(\"\").resolve(\"test\"): [%s]".formatted(FileSystems.getDefault().getPath("").resolve("test")));
```

Prints:

```
FileSystems.getDefault().getPath(""): []
FileSystems.getDefault().getPath("").resolve("test"): [test]
```

**Comment by sbrannen** [comment] 2022-09-26 18:22
> Could you create a separate issue for the behavior you're describing? This issue is going to be closed when the merge goes in.

I raised #5081 to address that.

**Closed** 2022-10-04 11:03 UTC
Labels: bug, native-image, spring

**Comment by sdeleuze** [comment] 2022-10-04 13:40
Could you please make sure it is backported to [release/graal-vm/22.3](https://github.com/oracle/graal/tree/release/graal-vm/22.3) and update the milestone of this issue accordingly?

**Comment by jovanstevanovic** [comment] 2022-10-05 08:45
@sdeleuze Yes, I'm trying to backport it now.
