### ISSUE TITLE
Native image build failure with graalVM 22.3.1 when using GraalJS : class is part of the image builder itself (in jrt:/org.graalvm.sdk) and must not be passed via -cp Error

### ISSUE THREAD

**Issue by nadeemahmad770** [oracle/graal#9756] opened 2024-09-26 12:42 UTC
**Describe GraalVM and your environment :**
 - GraalVM version or commit id if built from source: **[ graalvm-ce-java17-22.3.1 ]**
 - CE or EE: **[ CE ]**
 - JDK version: **[ JDK17 ]**
 - OS and OS Version: **[ Linux, Windows ]**
 - Architecture: **[ amd64]**
 - The output of `java -Xinternalversion`:
```
 **Java HotSpot(TM) 64-Bit Server VM (25.202-b08) for windows-amd64**
```

**Have you verified this issue still happens when using the latest snapshot?** No, with [GraalVM CE 24.2.0] it works fine.
You can find snapshot builds here: https://github.com/graalvm/graalvm-ce-dev-builds/releases

**Issue: Class-path entry file:///workspace/BOOT-INF/lib/graal-sdk-22.3.1.jar 
contains class org.graalvm.nativeimage.Platform$LINUX_AMD64. This class is part of the image builder itself (in jrt:/org.graalvm.sdk) and must not be passed via -cp. This can be caused by a fat-jar that illegally includes svm.jar (or graal-sdk.jar) due to its build-time dependency on it. **

**Code snippet or code repository that reproduces the issue**
```
**Maven entry:  <dependency>
            <groupId>org.graalvm.js</groupId>
            <artifactId>js</artifactId>
            <version>22.3.1</version>
        </dependency>

Code: 

public double evaluateFormula(String formula, String formulaKey) {
        if (formula.isBlank() || context == null) {
            return 0.0;
        }
        try {
            Value result = context.eval(Constants.SCRIPT_ENGINE_JS, formula);
            return result.asDouble();
        } catch (Exception e) {
            throw new BusinessException(messageService.getMessage(MessageConstants.FORMULA_SCRIPT_ERROR),
                    messageService.getMessage(MessageConstants.FORMULA_EVALUATION_ERROR, formulaKey), HttpStatus.BAD_REQUEST);
        }
    }
**
```

**Steps to reproduce the issue**
Please include both build steps as well as run steps
build:  mvn -Pnative spring-boot:build-image

**Expected behavior**
Native-build creation should not fail.

**Additional context**

```
    Executing native-image --no-fallback -H:+StaticExecutableWithDynamicLibC @/workspace/META-INF/native-image/argfile --initialize-at-build-time=ch.qos.logback,org.slf4j,org.springframework.context.support.ReloadableResourceBundleMessageSource,com.x.y.SystemConfig --trace-class-initialization=ch.qos.logback.core.util.Loader,ch.qos.logback.core.util.StatusPrinter,ch.qos.logback.core.status.StatusBase,org.slf4j.LoggerFactory,ch.qos.logback.classic.Level,ch.qos.logback.classic.Logger,ch.qos.logback.core.status.InfoStatus,org.springframework.context.support.ReloadableResourceBundleMessageSource,org.graalvm.polyglot,org.graalvm.js -H:+ReportExceptionStackTraces -H:Name=/layers/paketo-buildpacks_native-image/native-image/com.x.y.App -cp /workspace:/workspace/BOOT-INF/classes:/workspace/BOOT-INF/lib/logback-classic-1.4.14.jar:/workspace/BOOT-INF/lib/logback-core-1.4.14.jar:/workspace/BOOT-INF/lib/log4j-to-slf4j-2.21.1.jar:/workspace/BOOT-INF/lib/log4j-api-2.21.1.jar:/workspace/BOOT-INF/lib/jul-to-slf4j-2.0.12.jar:/workspace/BOOT-INF/lib/jakarta.annotation-api-2.1.1.jar:/workspace/BOOT-INF/lib/snakeyaml-2.2.jar:/workspace/BOOT-INF/lib/spring-boot-actuator-autoconfigure-3.2.3.jar:/workspace/BOOT-INF/lib/spring-boot-actuator-3.2.3.jar:/workspace/BOOT-INF/lib/jackson-databind-2.15.4.jar:/workspace/BOOT-INF/lib/jackson-annotations-2.15.4.jar:/workspace/BOOT-INF/lib/jackson-core-2.15.4.jar:/workspace/BOOT-INF/lib/jackson-datatype-jsr310-2.15.4.jar:/workspace/BOOT-INF/lib/micrometer-observation-1.12.3.jar:/workspace/BOOT-INF/lib/micrometer-commons-1.12.3.jar:/workspace/BOOT-INF/lib/micrometer-jakarta9-1.12.3.jar:/workspace/BOOT-INF/lib/micrometer-core-1.12.3.jar:/workspace/BOOT-INF/lib/HdrHistogram-2.1.12.jar:/workspace/BOOT-INF/lib/LatencyUtils-2.0.3.jar:/workspace/BOOT-INF/lib/spring-aop-6.1.4.jar:/workspace/BOOT-INF/lib/spring-beans-6.1.4.jar:/workspace/BOOT-INF/lib/spring-security-config-6.2.2.jar:/workspace/BOOT-INF/lib/spring-context-6.1.4.jar:/workspace/BOOT-INF/lib/spring-security-web-6.2.2.jar:/workspace/BOOT-INF/lib/spring-expression-6.1.4.jar:/workspace/BOOT-INF/lib/springdoc-openapi-starter-webflux-ui-2.3.0.jar:/workspace/BOOT-INF/lib/springdoc-openapi-starter-webflux-api-2.3.0.jar:/workspace/BOOT-INF/lib/springdoc-openapi-starter-common-2.3.0.jar:/workspace/BOOT-INF/lib/swagger-core-jakarta-2.2.19.jar:/workspace/BOOT-INF/lib/commons-lang3-3.13.0.jar:/workspace/BOOT-INF/lib/swagger-annotations-jakarta-2.2.19.jar:/workspace/BOOT-INF/lib/swagger-models-jakarta-2.2.19.jar:/workspace/BOOT-INF/lib/jackson-dataformat-yaml-2.15.4.jar:/workspace/BOOT-INF/lib/swagger-ui-5.10.3.jar:/workspace/BOOT-INF/lib/spring-boot-3.2.3.jar:/workspace/BOOT-INF/lib/spring-boot-autoconfigure-3.2.3.jar:/workspace/BOOT-INF/lib/jakarta.xml.bind-api-4.0.1.jar:/workspace/BOOT-INF/lib/jakarta.activation-api-2.1.2.jar:/workspace/BOOT-INF/lib/byte-buddy-1.14.12.jar:/workspace/BOOT-INF/lib/spring-core-6.1.4.jar:/workspace/BOOT-INF/lib/spring-jcl-6.1.4.jar:/workspace/BOOT-INF/lib/reactor-core-3.6.3.jar:/workspace/BOOT-INF/lib/tomcat-embed-el-10.1.19.jar:/workspace/BOOT-INF/lib/hibernate-validator-8.0.1.Final.jar:/workspace/BOOT-INF/lib/jakarta.validation-api-3.0.2.jar:/workspace/BOOT-INF/lib/jboss-logging-3.5.3.Final.jar:/workspace/BOOT-INF/lib/classmate-1.6.0.jar:/workspace/BOOT-INF/lib/jackson-datatype-jdk8-2.15.4.jar:/workspace/BOOT-INF/lib/jackson-module-parameter-names-2.15.4.jar:/workspace/BOOT-INF/lib/reactor-netty-http-1.1.16.jar:/workspace/BOOT-INF/lib/netty-codec-http-4.1.107.Final.jar:/workspace/BOOT-INF/lib/netty-common-4.1.107.Final.jar:/workspace/BOOT-INF/lib/netty-buffer-4.1.107.Final.jar:/workspace/BOOT-INF/lib/netty-transport-4.1.107.Final.jar:/workspace/BOOT-INF/lib/netty-codec-4.1.107.Final.jar:/workspace/BOOT-INF/lib/netty-handler-4.1.107.Final.jar:/workspace/BOOT-INF/lib/netty-codec-http2-4.1.107.Final.jar:/workspace/BOOT-INF/lib/netty-resolver-dns-4.1.107.Final.jar:/workspace/BOOT-INF/lib/netty-resolver-4.1.107.Final.jar:/workspace/BOOT-INF/lib/netty-codec-dns-4.1.107.Final.jar:/workspace/BOOT-INF/lib/netty-resolver-dns-native-macos-4.1.107.Final-osx-x86_64.jar:/workspace/BOOT-INF/lib/netty-resolver-dns-classes-macos-4.1.107.Final.jar:/workspace/BOOT-INF/lib/netty-transport-native-epoll-4.1.107.Final-linux-x86_64.jar:/workspace/BOOT-INF/lib/netty-transport-native-unix-common-4.1.107.Final.jar:/workspace/BOOT-INF/lib/netty-transport-classes-epoll-4.1.107.Final.jar:/workspace/BOOT-INF/lib/reactor-netty-core-1.1.16.jar:/workspace/BOOT-INF/lib/netty-handler-proxy-4.1.107.Final.jar:/workspace/BOOT-INF/lib/netty-codec-socks-4.1.107.Final.jar:/workspace/BOOT-INF/lib/spring-web-6.1.4.jar:/workspace/BOOT-INF/lib/spring-webflux-6.1.4.jar:/workspace/BOOT-INF/lib/aspectjweaver-1.9.21.jar:/workspace/BOOT-INF/lib/HikariCP-5.0.1.jar:/workspace/BOOT-INF/lib/spring-jdbc-6.1.4.jar:/workspace/BOOT-INF/lib/hibernate-core-6.4.2.Final.jar:/workspace/BOOT-INF/lib/jakarta.persistence-api-3.1.0.jar:/workspace/BOOT-INF/lib/jakarta.transaction-api-2.0.1.jar:/workspace/BOOT-INF/lib/hibernate-commons-annotations-6.0.6.Final.jar:/workspace/BOOT-INF/lib/jandex-3.1.2.jar:/workspace/BOOT-INF/lib/jaxb-runtime-4.0.4.jar:/workspace/BOOT-INF/lib/jaxb-core-4.0.4.jar:/workspace/BOOT-INF/lib/angus-activation-2.0.1.jar:/workspace/BOOT-INF/lib/txw2-4.0.4.jar:/workspace/BOOT-INF/lib/istack-commons-runtime-4.1.2.jar:/workspace/BOOT-INF/lib/jakarta.inject-api-2.0.1.jar:/workspace/BOOT-INF/lib/antlr4-runtime-4.13.0.jar:/workspace/BOOT-INF/lib/spring-data-jpa-3.2.3.jar:/workspace/BOOT-INF/lib/spring-data-commons-3.2.3.jar:/workspace/BOOT-INF/lib/spring-orm-6.1.4.jar:/workspace/BOOT-INF/lib/spring-tx-6.1.4.jar:/workspace/BOOT-INF/lib/spring-aspects-6.1.4.jar:/workspace/BOOT-INF/lib/postgresql-42.7.2.jar:/workspace/BOOT-INF/lib/checker-qual-3.42.0.jar:/workspace/BOOT-INF/lib/spring-context-support-6.1.4.jar:/workspace/BOOT-INF/lib/caffeine-3.1.8.jar:/workspace/BOOT-INF/lib/error_prone_annotations-2.21.1.jar:/workspace/BOOT-INF/lib/gson-2.8.9.jar:/workspace/BOOT-INF/lib/json-20210307.jar:/workspace/BOOT-INF/lib/jetty-reactive-httpclient-4.0.3.jar:/workspace/BOOT-INF/lib/reactive-streams-1.0.4.jar:/workspace/BOOT-INF/lib/jetty-client-12.0.6.jar:/workspace/BOOT-INF/lib/jetty-alpn-client-12.0.6.jar:/workspace/BOOT-INF/lib/jetty-http-12.0.6.jar:/workspace/BOOT-INF/lib/jetty-util-12.0.6.jar:/workspace/BOOT-INF/lib/jetty-io-12.0.6.jar:/workspace/BOOT-INF/lib/slf4j-api-2.0.12.jar:/workspace/BOOT-INF/lib/spring-security-core-6.2.2.jar:/workspace/BOOT-INF/lib/spring-security-crypto-6.2.2.jar:/workspace/BOOT-INF/lib/js-scriptengine-22.3.1.jar:/workspace/BOOT-INF/lib/graal-sdk-22.3.1.jar:/workspace/BOOT-INF/lib/spring-boot-jarmode-layertools-3.2.3.jar com.x.y.app

Error: Class-path entry file:///workspace/BOOT-INF/lib/graal-sdk-22.3.1.jar contains class org.graalvm.nativeimage.Platform$LINUX_AMD64. 
This class is part of the image builder itself (in jrt:/org.graalvm.sdk) and must not be passed via -cp. This can be caused by a fat-jar that illegally includes svm.jar 
(or graal-sdk.jar) due to its build-time dependency on it. As a workaround, -H:+AllowDeprecatedBuilderClassesOnImageClasspath allows turning this error into a warning. 
Note that this option is deprecated and will be removed in a future version.

com.oracle.svm.core.util.UserError$UserException: Class-path entry file:///workspace/BOOT-INF/lib/graal-sdk-22.3.1.jar 
contains class org.graalvm.nativeimage.Platform$LINUX_AMD64. This class is part of the image builder itself (in jrt:/org.graalvm.sdk) and must not be passed via -cp. 
This can be caused by a fat-jar that illegally includes svm.jar (or graal-sdk.jar) due to its build-time dependency on it. 
As a workaround, -H:+AllowDeprecatedBuilderClassesOnImageClasspath allows turning this error into a warning. Note that this option is deprecated and will be removed in a future version.

[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  02:19 min

```
Note: when using AllowDeprecatedBuilderClassesOnImageClasspath in build argument getting below error

Error: Could not find option 'AllowDeprecatedBuilderClassesOnImageClasspath'. Use -H:PrintFlags= to list all available options.
Error: Image build request failed with exit status 1

**Comment by selhagani** [comment] 2024-09-26 16:06
Certainly! Here's a more formal and polite version:

Hi @nadeemahmad770,

Thank you for reaching out to us. I would like to inform you that the version graalvm-ce-java17-22.3.1 is no longer supported. For the Community Edition, we recommend using the latest available version. Since the issue is resolved with the updated version, I suggest continuing with that one.

Thank you for your understanding!

**Closed** 2024-09-26 16:06 UTC
Labels: truffle
