### ISSUE TITLE
Execution test-native of goal org.graalvm.buildtools:native-maven-plugin:0.9.18:test failed: Test configuration file wasn't found.

### ISSUE THREAD

**Issue by liudonghua123** [oracle/graal#5498] opened 2022-11-25 03:49 UTC
**Describe the issue**

I tried to build a simple midi player using `javax.sound.midi.MidiSystem`. I also followed the guidence on https://www.graalvm.org/dev/reference-manual/native-image/guides/use-native-image-maven-plugin/. But when I execute `mvn -Pnative package` or `mvn -Pnative -Dagent package`, it failed with `Execution test-native of goal org.graalvm.buildtools:native-maven-plugin:0.9.18:test failed: Test configuration file wasn't found.`. The test is ok when `mvn clean package`.

**Steps to reproduce the issue**

1. git clone https://github.com/liudonghua123/fun_player -b java
2. cd fun_player 
3. run the followings
    mvn clean package
    mvn -Pnative -Dagent exec:exec@java-agent
    mvn -Pnative -Dagent package
4. or
    mvn clean compile
    mvn -Pnative package

**Describe GraalVM and your environment:**

```
D:\code\python\fun_player>java -version
openjdk version "17.0.1" 2021-10-19
OpenJDK Runtime Environment GraalVM CE 21.3.0 (build 17.0.1+12-jvmci-21.3-b05)
OpenJDK 64-Bit Server VM GraalVM CE 21.3.0 (build 17.0.1+12-jvmci-21.3-b05, mixed mode, sharing)

D:\code\python\fun_player>ver

Microsoft Windows [Version 10.0.22621.819]

D:\code\python\fun_player>
```

**More details**
Consider adding the `--native-image-info` and  `--verbose` flags when building your native image and paste output below.

Add any other information about the problem here. Especially important are stack traces or log output. Feel free to link to gists or to screenshots if necessary.
```
D:\code\python\fun_player>mvn clean compile
[INFO] Scanning for projects...
[INFO]
[INFO] ----------------< com.liudonghua.examples:midi_player >-----------------
[INFO] Building midi_player 0.1.0
[INFO] --------------------------------[ jar ]---------------------------------
[INFO]
[INFO] --- maven-clean-plugin:2.5:clean (default-clean) @ midi_player ---
[INFO] Deleting D:\code\python\fun_player\target
[INFO]
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ midi_player ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory D:\code\python\fun_player\src\main\resources
[INFO]
[INFO] --- maven-compiler-plugin:3.8.1:compile (default-compile) @ midi_player ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 1 source file to D:\code\python\fun_player\target\classes
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  11.450 s
[INFO] Finished at: 2022-11-25T11:26:04+08:00
[INFO] ------------------------------------------------------------------------

D:\code\python\fun_player>mvn -Pnative package
[INFO] Scanning for projects...
[INFO] Found GraalVM installation from GRAALVM_HOME variable.
[INFO]
[INFO] ----------------< com.liudonghua.examples:midi_player >-----------------
[INFO] Building midi_player 0.1.0
[INFO] --------------------------------[ jar ]---------------------------------
[INFO]
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ midi_player ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory D:\code\python\fun_player\src\main\resources
[INFO]
[INFO] --- maven-compiler-plugin:3.8.1:compile (default-compile) @ midi_player ---
[INFO] Nothing to compile - all classes are up to date
[INFO]
[INFO] --- maven-resources-plugin:2.6:testResources (default-testResources) @ midi_player ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory D:\code\python\fun_player\src\test\resources
[INFO]
[INFO] --- maven-compiler-plugin:3.8.1:testCompile (default-testCompile) @ midi_player ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 1 source file to D:\code\python\fun_player\target\test-classes
[INFO]
[INFO] --- maven-surefire-plugin:2.12.4:test (default-test) @ midi_player ---
[INFO] Surefire report directory: D:\code\python\fun_player\target\surefire-reports

-------------------------------------------------------
 T E S T S
-------------------------------------------------------
Running com.liudonghua.examples.AppTest
Tests run: 0, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.005 sec

Results :

Tests run: 0, Failures: 0, Errors: 0, Skipped: 0

[INFO]
[INFO] --- native-maven-plugin:0.9.18:merge-agent-files (test-native) @ midi_player ---
[INFO] Merging agent 1 files into D:\code\python\fun_player\target\native\agent-output\test
[INFO]
[INFO] --- native-maven-plugin:0.9.18:test (test-native) @ midi_player ---
[ERROR] Test configuration file wasn't found. Make sure that test execution wasn't skipped.
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  37.134 s
[INFO] Finished at: 2022-11-25T11:27:09+08:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.graalvm.buildtools:native-maven-plugin:0.9.18:test (test-native) on project midi_player: Execution test-native of goal org.graalvm.buildtools:native-maven-plugin:0.9.18:test failed: Test configuration file wasn't found. -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/PluginExecutionException

D:\code\python\fun_player>mvn -Pnative package -DskipTests
[INFO] Scanning for projects...
[INFO] Found GraalVM installation from GRAALVM_HOME variable.
[INFO]
[INFO] ----------------< com.liudonghua.examples:midi_player >-----------------
[INFO] Building midi_player 0.1.0
[INFO] --------------------------------[ jar ]---------------------------------
[INFO]
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ midi_player ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory D:\code\python\fun_player\src\main\resources
[INFO]
[INFO] --- maven-compiler-plugin:3.8.1:compile (default-compile) @ midi_player ---
[INFO] Nothing to compile - all classes are up to date
[INFO]
[INFO] --- maven-resources-plugin:2.6:testResources (default-testResources) @ midi_player ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory D:\code\python\fun_player\src\test\resources
[INFO]
[INFO] --- maven-compiler-plugin:3.8.1:testCompile (default-testCompile) @ midi_player ---
[INFO] Nothing to compile - all classes are up to date
[INFO]
[INFO] --- maven-surefire-plugin:2.12.4:test (default-test) @ midi_player ---
[INFO] Tests are skipped.
[INFO]
[INFO] --- native-maven-plugin:0.9.18:merge-agent-files (test-native) @ midi_player ---
[WARNING] Skipping merging of agent files since there are no input directories.
[INFO]
[INFO] --- native-maven-plugin:0.9.18:test (test-native) @ midi_player ---
[INFO] Skipping native-image tests (parameter 'skipTests' or 'skipNativeTests' is true).
[INFO]
[INFO] --- maven-jar-plugin:3.2.2:jar (default-jar) @ midi_player ---
[INFO] Building jar: D:\code\python\fun_player\target\midi_player-0.1.0.jar
[INFO]
[INFO] --- maven-assembly-plugin:2.2-beta-5:single (default) @ midi_player ---
[INFO] Building jar: D:\code\python\fun_player\target\midi_player-0.1.0-jar-with-dependencies.jar
[INFO]
[INFO] --- native-maven-plugin:0.9.18:build (build-native) @ midi_player ---
[WARNING] 'native:build' goal is deprecated. Use 'native:compile-no-fork' instead.
[INFO] Executing: D:\apps\graalvm-ce-java17-21.3.0\bin\native-image.cmd @target\tmp\native-image-3108419745089923060.args
[midi_player:8024]    classlist:  15,511.32 ms,  0.96 GB
# Printing Dashboard BGV dump header to: D:\code\python\fun_player\fortune.bgv
[midi_player:8024]        (cap):  15,039.97 ms,  0.96 GB
[midi_player:8024]        setup:  32,520.48 ms,  0.96 GB
[midi_player:8024]     (clinit):     991.83 ms,  1.90 GB
[midi_player:8024]   (typeflow):  26,653.74 ms,  1.90 GB
[midi_player:8024]    (objects):  39,345.91 ms,  1.90 GB
[midi_player:8024]   (features):  12,003.63 ms,  1.90 GB
[midi_player:8024]     analysis:  82,009.00 ms,  1.90 GB
# Printing Dashboard PointsTo analysis BGV dump to: D:\code\python\fun_player\fortune.bgv
[midi_player:8024]     universe:   4,706.39 ms,  1.91 GB
[midi_player:8024]      (parse):   3,294.21 ms,  1.91 GB
[midi_player:8024]     (inline):   5,369.91 ms,  2.58 GB
[midi_player:8024]    (compile):  74,615.04 ms,  3.86 GB
# Printing Dashboard Code-Breakdown BGV dump to: D:\code\python\fun_player\fortune.bgv
[midi_player:8024]      compile:  92,497.74 ms,  3.86 GB
# Printing Dashboard Heap-Breakdown BGV dump to: D:\code\python\fun_player\fortune.bgv
[midi_player:8024]        image:  22,674.52 ms,  3.86 GB
[midi_player:8024]        write:   3,897.27 ms,  3.86 GB
Print of Dashboard dump output ended.
[midi_player:8024]      [total]: 269,799.63 ms,  3.86 GB
# Printing build artifacts to: D:\code\python\fun_player\target\midi_player.build_artifacts.txt
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  05:07 min
[INFO] Finished at: 2022-11-25T11:32:34+08:00
[INFO] ------------------------------------------------------------------------

D:\code\python\fun_player>
```

**Comment by cforce** [comment] 2022-11-30 15:50
same here

**Comment by oubidar-Abderrahim** [comment] 2022-12-01 10:44
Hi @liudonghua123, thank you for reporting this issue. GraalVM 21.3.0 is an outdated version that has many bugs that we fixed in the later versions. Please use one of the latest versions: GraalVM 22.3.0 or GraalVM 21.3.4 and let us know if the issue is still happening.

**Comment by oubidar-Abderrahim** [comment] 2022-12-05 16:51
As a workaround, you can build the image using `native-image -H:ConfigurationFileDirectories=target\native\agent-output --no-fallback -H:DashboardDump=fortune -H:+DashboardAll -jar target\midi_player-0.1.0-jar-with-dependencies.jar`

The issue is tracked internally on GR 42860

**Comment by cforce** [comment] 2022-12-06 13:40
Does not work for me
[INFO] 
[INFO] --- native-maven-plugin:0.9.19:test (test-native) @ cloud-function-dynamodb-lambda ---
[ERROR] Test configuration file wasn't found. Make sure that test execution wasn't skipped.


<img width="1145" alt="image" src="https://user-images.githubusercontent.com/393286/205927599-a2cd6121-bf56-467e-9249-ef885d43b5bc.png">

**Comment by wirthi** [comment] 2022-12-07 15:50
@liudonghua123 That seems to be an issue with the native-build-tools. I think you would get a better and faster answer at https://github.com/graalvm/native-build-tools

**Closed** 2023-10-30 22:16 UTC
Labels: bug, native-image
