### ISSUE TITLE
SIGBUS error using TruffleString

### ISSUE THREAD

**Issue by nirvdrum** [oracle/graal#4314] opened 2022-02-10 23:10 UTC
**Describe GraalVM and your environment :**
 - GraalVM version or commit id if built from source: **749e1e32ba4**
 - CE or EE: **CE**
 - JDK version: **11**
 - OS and OS Version: **macOS 12.2**
 - Architecture: **AMD64 through Rosetta on M1**
 - The output of `java -Xinternalversion`:
```
 OpenJDK 64-Bit Server VM (11.0.13+8-jvmci-22.0-b02) for bsd-amd64 JRE (11.0.13+8-jvmci-22.0-b02), built on Nov 22 2021 14:39:18 by "graal" with clang 4.2.1 Compatible Apple LLVM 10.0.0 (clang-1000.11.45.5)
```

**Describe the issue**

While working on TruffleRuby's adoption of TruffleString, I ran into an issue where using `TruffleString.CodePointAtIndexNode` instead of `TruffleString.CodePointAtByteIndexNode` to get the first codepoint in a string results in a SIGBUS error:

```
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGBUS (0xa) at pc=0x000000010c6a583f, pid=91223, tid=29443
#
# JRE version: OpenJDK Runtime Environment GraalVM 22.1.0-dev (11.0.13+8) (build 11.0.13+8-jvmci-22.0-b02)
# Java VM: OpenJDK 64-Bit Server VM GraalVM 22.1.0-dev (11.0.13+8-jvmci-22.0-b02, mixed mode, sharing, tiered, jvmci, jvmci compiler, compressed oops, g1 gc, bsd-amd64)
# Problematic frame:
# V  [libjvm.dylib+0x63d83f]truffleruby 22.1.0-dev-d2a7021c, like ruby 3.0.2, GraalVM CE JVM [x86_64-darwin]
```

**Steps to reproduce the issue**
Please include both build steps as well as run steps
1. `mkdir truffleruby-ws && cd truffleruby-ws`
2. `git clone --depth 2 https://github.com/shopify/truffleruby --branch tstring-sigbus-issue`
3. `export JT_ENV=jvm-ce`
4. Run `jt build`
5. Run `jt test fast`

Unfortunately, I haven't been able to replicate the issue on x86_64 Linux. It happens reliably on an Apple M1 using Rosetta. I haven't narrowed down a smaller reproduction.

If you go to the commit's parent (`git checkout HEAD^`) and rebuild, the test suite runs without issue.

**Comment by djoooooe** [comment] 2022-02-11 10:09
Unfortunately i don't have a Mac to test this on, could you check if commenting out
`
registerTStringReadPlugins(r, true);
registerTStringReadPlugins(r, false);
registerTStringWritePlugins(r, true);
registerTStringWritePlugins(r, false);
`
in https://github.com/oracle/graal/blob/a10a2870f0c101ff5cf9fdeb5335a85934533326/compiler/src/org.graalvm.compiler.truffle.compiler.amd64/src/org/graalvm/compiler/truffle/compiler/amd64/substitutions/TruffleAMD64InvocationPlugins.java#L342 helps?

**Comment by eregon** [comment] 2022-02-14 10:22
cc @lewurm

**Comment by nirvdrum** [comment] 2022-02-14 18:57
Making those changes did not help, unfortunately.

I've been running the TruffleRuby test suite in a loop all day. I'm not sure that the codepoint methods are at fault, even though using it seems to induce the issue more regularly. I tried rolling back to earlier commits and could get a SIGBUS issue there as well. Unfortunately, not reliably. But I can see it happen ~20% of the time. I'll try bisecting, but that's going to take some time to work out since it doesn't happen on every invocation.

**Comment by lewurm** [comment] 2022-02-15 12:13
If you can repro it without the `CodePointAtByteIndexNode` changes, then it's probably unrelated to TruffleStrings. Should be some relief for @djoooooe 😄 I also doubt that bisecting will get you anywhere, this issue is probably around since forever and potentially Rosetta 2 is to blame, or at least a combination of it.

```
# Problematic frame:
# V  [libjvm.dylib+0x63d83f]truffleruby 22.1.0-dev-d2a7021c, like ruby 3.0.2, GraalVM CE JVM [x86_64-darwin]
```
This hints that this is a crash in the JVM itself.  It's a bummer that no `hs_err_pid*.log` is generated by the JVM, nor it is printing a full stack trace. I don't know why this is the case. I can repro it with similar probabilites as @nirvdrum, but I don't even get the `[libjvm.dylib+0x63d83f]` part. However the `pc` in the first line has the same offset.

```
# this is a x86_64 JDK
$ cd /Users/lewurm/.mx/jdks/labsjdk-ce-11-jvmci-22.0-b02/Contents/Home/
$ lldb
(lldb) target create --no-dependents --arch x86_64 bin/java
Current executable set to '/Users/lewurm/.mx/jdks/labsjdk-ce-11-jvmci-22.0-b02/Contents/Home/bin/java' (x86_64).
(lldb) target modules add lib/server/libjvm.dylib
# base is pc=0x000000010c6a583f - [libjvm.dylib+0x63d83f]
(lldb) target modules load --file lib/server/libjvm.dylib __TEXT 0x10C068000
section '__TEXT' loaded at 0x10c068000
(lldb) image list
[  0] 79D7C6F9-D050-3BF7-BC47-D3EFEA6A74F8 java[0x0000000100000000] /Users/lewurm/.mx/jdks/labsjdk-ce-11-jvmci-22.0-b02/Contents/Home/bin/java
[  1] 3B861619-B016-383A-B943-A2C38F9E86A1 0x000000010c068000 lib/server/libjvm.dylib
(lldb) image lookup -a 0x000000010c6a583f
      Address: libjvm.dylib[0x000000000063d83f] (libjvm.dylib.__TEXT.__text + 6538575)
      Summary: libjvm.dylib`nmethodLocker::lock_nmethod(CompiledMethod*, bool) + 39
(lldb) x/20i 0x000000010c6a583f-39
0x10c6a5818: 55                    pushq  %rbp
0x10c6a5819: 48 89 e5              movq   %rsp, %rbp
0x10c6a581c: 53                    pushq  %rbx
0x10c6a581d: 50                    pushq  %rax
0x10c6a581e: 48 89 fb              movq   %rdi, %rbx
0x10c6a5821: 48 85 db              testq  %rbx, %rbx
0x10c6a5824: 74 1d                 je     0x10c6a5843               ; <+43>
0x10c6a5826: 48 8b 03              movq   (%rbx), %rax
0x10c6a5829: 48 89 df              movq   %rbx, %rdi
0x10c6a582c: ff 50 58              callq  *0x58(%rax)
0x10c6a582f: 84 c0                 testb  %al, %al
0x10c6a5831: 75 10                 jne    0x10c6a5843               ; <+43>
0x10c6a5833: 48 81 c3 48 01 00 00  addq   $0x148, %rbx              ; imm = 0x148
0x10c6a583a: b8 01 00 00 00        movl   $0x1, %eax
0x10c6a583f: f0                    lock                         # <== crash is happening here
0x10c6a5840: 0f c1 03              xaddl  %eax, (%rbx)
0x10c6a5843: 48 83 c4 08           addq   $0x8, %rsp
0x10c6a5847: 5b                    popq   %rbx
0x10c6a5848: 5d                    popq   %rbp
0x10c6a5849: c3                    retq
```

It's happening in this code:
https://github.com/graalvm/labs-openjdk-11/blob/a79393e64d1f244c00dca966736af40d781f0079/src/hotspot/share/code/nmethod.cpp#L2048-L2056

Unfortunately we don't even have a register dump from the HotSpot crash handler, so it's hard to say anything 😕 

@eregon I'm confused about why a crashed JVM doesn't abort the harness.  Does the harness spawn a fresh JVM for each test? Can I specify to run everything in a single JVM instance?

**Comment by eregon** [comment] 2022-02-15 13:44
> I tried rolling back to earlier commits and could get a SIGBUS issue there as well.

Is that commits before the first commit to adopt TruffleString?

> @eregon I'm confused about why a crashed JVM doesn't abort the harness. Does the harness spawn a fresh JVM for each test? Can I specify to run everything in a single JVM instance?

`jt test fast` only runs in-process specs.
However there is still an initial mspec process that `execve()` to a mspec-run process which runs everything.
You can find out the mspec-run command line as the mspec process prints it before execve, like:
```
$PWD/mxbuild/truffleruby-jvm/languages/ruby/bin/ruby --vm.ea --vm.esa --experimental-options --core-load-path=$PWD/src/main/ruby/truffleruby --polyglot --experimental-options --pattern-matching $PWD/spec/mspec/bin/mspec-run -B spec/truffleruby.mspec --excl-tag fails --excl-tag slow
```
Running that shouldn't create any subprocess.

**Comment by nirvdrum** [comment] 2022-02-15 14:56
> > I tried rolling back to earlier commits and could get a SIGBUS issue there as well.
> 
> Is that commits before the first commit to adopt TruffleString?

I'm sorry, I should have been more precise. I rolled back to the commit just before the one using either codepoint function. There are a lot of other usages of TruffleString beyond that. I've only seen the issue with builds including TruffleString. I have not bisected yet to see when the issue might have been introduced.

**Comment by lewurm** [comment] 2022-02-16 10:15
I did some more poking, also with Rosetta itself. See https://gist.github.com/lewurm/527dd29aec1bd6103548d505146f3c98 for a writeup. TL;DR: It doesn't make any sense to me 😅 

I also tried to built labsjdk11 manually and added an assert that the address `&nm->_lock_count` is never unaligned. With that I'm not able to reproduce it anymore. Then I tried to remove the assert, build again, and I _still_ can't reproduce it anymore. The generated code for this method looks the same as in the downloaded binary though. This might hints there is more funky stuff going on.

I'm out of ideas honestely.  Maybe try with a custom labsjdk11 build as well (DM me on Slack if you need any help).

**Comment by lewurm** [comment] 2024-01-23 16:06
I'm closing this, hopefully nobody is using TruffleString on Rosetta 2 anymore 😉

**Closed by lewurm** 2024-01-23 16:06 UTC
Labels: truffle
