### ISSUE TITLE
MethodHandle / MethodType differences between JVM and native-image

### ISSUE THREAD

**Issue by mhalbritter** [oracle/graal#5209] opened 2022-10-12 14:17 UTC
I have this test code

```java
        MethodType a = MethodType.methodType(Void.TYPE, ByteBuffer.class);
        MethodType b = MethodHandles.lookup()
                .findVirtual(Test.class, "onWholeMessage", MethodType.methodType(void.class, ByteBuffer.class))
                .bindTo(new Test())
                        .type();

        System.out.println("a == b: " + (a == b));
        System.out.println("a equals b: " + (a.equals(b)));
```

with `Test` defined as this:

```java
    static class Test {
        public void onWholeMessage(ByteBuffer wholeMessage) {

        }
    }
```

When run on the JVM, this prints:

```
a == b: true
a equals b: true
```

When run on GraalVM native-image, this prints:

```
a == b: false
a equals b: true
```

On the JVM, it always returns the same reference, while on native image it returns a different reference.

Problem now is, that Jetty doesn't use the (in my mind correct) `equals` call, but uses a reference equality, [for example here](https://github.com/eclipse/jetty.project/blob/jetty-10.0.x/jetty-websocket/websocket-core-common/src/main/java/org/eclipse/jetty/websocket/core/internal/messages/ByteBufferMessageSink.java#L41).

This let Jetty fail on native-image. I think this is a bug in the Jetty code, but I wanted to double check with you. What do you think?

**Comment by wirthi** [comment] 2022-10-13 09:33
Hi @mhalbritter 

I assume you did provide a configuration for that usecase (manually or by the tracing agent) or are pulling that information from the metadata repo?

Maybe @loicottet can have a look and see if that is a bug on our side or a configuration problem on yours.

-- Christian

**Comment by loicottet** [comment] 2022-10-13 09:38
This is indeed a bug, I'm aware of it and planning on fixing it soon. It is caused by Native Image resetting the JDK cache of `MethodType` instances at the end of the build. It should keep instances that are present in the image heap to avoid recreating them at runtime and causing this error.

**Comment by loicottet** [comment] 2023-12-18 13:29
The issue is fixed on master.

**Closed by loicottet** 2023-12-18 13:29 UTC
Labels: bug, native-image
