### ISSUE TITLE
Deadlock on context.close(true)

### ISSUE THREAD

**Issue by hejcz** [oracle/graal#3505] opened 2021-06-22 17:41 UTC
**Describe GraalVM and your environment :**
 - GraalVM version or commit id if built from source: **21.1.0**
 - CE or EE: **CE**
 - JDK version: **JDK16**
 - OS and OS Version: **Debian GNU/Linux 10.9**
 - Architecture: **amd64**
 - The output of `java -Xinternalversion`: OpenJDK 64-Bit Server VM (16.0.1+9-24) for linux-amd64 JRE (16.0.1+9-24), built on Mar 26 2021 18:09:28 by "mach5one" with gcc 10.2.0

**Have you verified this issue still happens when using the latest snapshot?**
No.

**Describe the issue**
In some rare cases closing graal's context results in deadlock. We run js scripts from java. We have:
- single engine shared acrossed all contexts
- single context per thread
- protection against infinite js scripts implemented as a task scheduled on `Executors.newSingleThreadScheduledExecutor()` doing `context.cancel(true)` after specified timeout.

If I read thread dump correctly, some handler, invoked on context close, locked an engine and then wanted to lock some truffle node. At the same time CompileRegexNodeGen was executing executeAndSpecialize locking the node and then when it wanted to parse regex it couldn't lock an engine. There were > 100 threads locked in the similar place to "request-processing-thread-21" (below).

**Code snippet or code repository that reproduces the issue**
This repo shows how we use and configure graal (this repo is for older graalvm version though).
https://github.com/hejcz/graal-infinite-loop-example/blob/main/src/test/java/io/github/hejcz/TestExecutor.java

**Steps to reproduce the issue**
Can't reproduce it outside production.

**Expected behavior**
Closing context doesn't result in deadlock.

**Additional context**
Add any other context about the problem here. Specially important are stack traces or log output. Feel free to link to gists or to screenshots if necesary
<details><summary>Details</summary>

```
Found one Java-level deadlock:
=============================
"request-processing-thread-0":
  waiting for ownable synchronizer 0x00000011f1da3790, (a java.util.concurrent.locks.ReentrantLock$NonfairSync),
  which is held by "request-processing-thread-142"

"request-processing-thread-142":
  waiting to lock monitor 0x00007f445801e4b0 (object 0x000000116fbe0cb8, a java.lang.Object),
  which is held by "pool-32-thread-1"

"pool-32-thread-1":
  waiting for ownable synchronizer 0x00000012599398b8, (a java.util.concurrent.locks.ReentrantLock$NonfairSync),
  which is held by "request-processing-thread-21"

"request-processing-thread-21":
  waiting to lock monitor 0x00007f445801e4b0 (object 0x000000116fbe0cb8, a java.lang.Object),
  which is held by "pool-32-thread-1"

"pool-32-thread-1":
	at jdk.internal.misc.Unsafe.park(java.base@16.0.1/Native Method)
	- parking to wait for  <0x00000012599398b8> (a java.util.concurrent.locks.ReentrantLock$NonfairSync)
	at java.util.concurrent.locks.LockSupport.park(java.base@16.0.1/LockSupport.java:211)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer.acquire(java.base@16.0.1/AbstractQueuedSynchronizer.java:714)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer.acquire(java.base@16.0.1/AbstractQueuedSynchronizer.java:937)
	at java.util.concurrent.locks.ReentrantLock$Sync.lock(java.base@16.0.1/ReentrantLock.java:153)
	at java.util.concurrent.locks.ReentrantLock.lock(java.base@16.0.1/ReentrantLock.java:322)
	at com.oracle.truffle.api.instrumentation.InstrumentationHandler.visitRoot(org.graalvm.truffle/InstrumentationHandler.java:1098)
	at com.oracle.truffle.api.instrumentation.InstrumentationHandler.visitRoots(org.graalvm.truffle/InstrumentationHandler.java:556)
	at com.oracle.truffle.api.instrumentation.InstrumentationHandler.addExecutionBinding(org.graalvm.truffle/InstrumentationHandler.java:343)
	at com.oracle.truffle.api.instrumentation.InstrumentationHandler.attachListener(org.graalvm.truffle/InstrumentationHandler.java:869)
	at com.oracle.truffle.api.instrumentation.InstrumentationHandler.access$2700(org.graalvm.truffle/InstrumentationHandler.java:97)
	at com.oracle.truffle.api.instrumentation.InstrumentationHandler$AbstractInstrumenter.attachExecutionEventListener(org.graalvm.truffle/InstrumentationHandler.java:2367)
	at com.oracle.truffle.api.instrumentation.Instrumenter.attachExecutionEventListener(org.graalvm.truffle/Instrumenter.java:89)
	at com.oracle.truffle.polyglot.PolyglotEngineImpl$CancelHandler.enableCancel(org.graalvm.truffle/PolyglotEngineImpl.java:1465)
	- locked <0x000000116fbe0cb8> (a java.lang.Object)
	at com.oracle.truffle.polyglot.PolyglotEngineImpl$CancelHandler.cancel(org.graalvm.truffle/PolyglotEngineImpl.java:1436)
	at com.oracle.truffle.polyglot.PolyglotEngineImpl$CancelHandler.cancel(org.graalvm.truffle/PolyglotEngineImpl.java:1424)
	at com.oracle.truffle.polyglot.PolyglotContextImpl.closeAndMaybeWait(org.graalvm.truffle/PolyglotContextImpl.java:1132)
	at com.oracle.truffle.polyglot.PolyglotContextImpl.cancel(org.graalvm.truffle/PolyglotContextImpl.java:1125)
	at com.oracle.truffle.polyglot.PolyglotContextImpl.close(org.graalvm.truffle/PolyglotContextImpl.java:1113)
	at org.graalvm.polyglot.Context.close(org.graalvm.sdk/Context.java:770)
	at io.github.hejcz.utils.js.GraalScriptExecutor.lambda$runScriptWithTimeout$14(GraalScriptExecutor.java:350)
	at io.github.hejcz.utils.js.GraalScriptExecutor$$Lambda$3184/0x00000017c23d33b8.run(Unknown Source)
	at java.util.concurrent.Executors$RunnableAdapter.call(java.base@16.0.1/Executors.java:515)
	at java.util.concurrent.FutureTask.run(java.base@16.0.1/FutureTask.java:264)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(java.base@16.0.1/ScheduledThreadPoolExecutor.java:304)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(java.base@16.0.1/ThreadPoolExecutor.java:1130)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(java.base@16.0.1/ThreadPoolExecutor.java:630)
	at java.lang.Thread.run(java.base@16.0.1/Thread.java:831)
	
	
"request-processing-thread-21":
	at com.oracle.truffle.polyglot.PolyglotLanguage.allocateInstance(org.graalvm.truffle/PolyglotLanguage.java:243)
	- waiting to lock <0x000000116fbe0cb8> (a java.lang.Object)
	at com.oracle.truffle.polyglot.PolyglotLanguageContext.ensureCreated(org.graalvm.truffle/PolyglotLanguageContext.java:476)
	at com.oracle.truffle.polyglot.PolyglotLanguageContext.ensureInitialized(org.graalvm.truffle/PolyglotLanguageContext.java:586)
	at com.oracle.truffle.polyglot.PolyglotContextImpl.getContextInitialized(org.graalvm.truffle/PolyglotContextImpl.java:456)
	at com.oracle.truffle.polyglot.EngineAccessor$EngineImpl.parseForLanguage(org.graalvm.truffle/EngineAccessor.java:243)
	at com.oracle.truffle.api.TruffleLanguage$Env.parseInternal(org.graalvm.truffle/TruffleLanguage.java:2477)
	at com.oracle.truffle.js.runtime.RegexCompilerInterface.compile(RegexCompilerInterface.java:63)
	at com.oracle.truffle.js.nodes.CompileRegexNode.doCompile(CompileRegexNode.java:96)
	at com.oracle.truffle.js.nodes.CompileRegexNodeGen.executeAndSpecialize(CompileRegexNodeGen.java:90)
	at com.oracle.truffle.js.nodes.CompileRegexNodeGen.executeCompile(CompileRegexNodeGen.java:54)
	at com.oracle.truffle.js.nodes.CompileRegexNode.compile(CompileRegexNode.java:69)
	at com.oracle.truffle.js.builtins.ConstructorBuiltins$ConstructRegExpNode.constructRegExpImpl(ConstructorBuiltins.java:1059)
	at com.oracle.truffle.js.builtins.ConstructorBuiltins$ConstructRegExpNode.constructRegExp(ConstructorBuiltins.java:1019)
	at com.oracle.truffle.js.builtins.ConstructorBuiltinsFactory$ConstructRegExpNodeGen.executeAndSpecialize(ConstructorBuiltinsFactory.java:993)
	at com.oracle.truffle.js.builtins.ConstructorBuiltinsFactory$ConstructRegExpNodeGen.execute(ConstructorBuiltinsFactory.java:972)
	at com.oracle.truffle.js.nodes.function.JSBuiltinNode$LazyBuiltinNode.execute(JSBuiltinNode.java:178)
	at com.oracle.truffle.js.nodes.JavaScriptNodeWrapper.execute(JavaScriptNodeWrapper.java:45)
	at com.oracle.truffle.js.nodes.function.FunctionRootNode.executeInRealm(FunctionRootNode.java:147)
	at com.oracle.truffle.js.runtime.JavaScriptRealmBoundaryRootNode.execute(JavaScriptRealmBoundaryRootNode.java:93)
	at org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.executeRootNode(jdk.internal.vm.compiler/OptimizedCallTarget.java:613)
	at org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.profiledPERoot(jdk.internal.vm.compiler/OptimizedCallTarget.java:584)
	at org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.callBoundary(jdk.internal.vm.compiler/OptimizedCallTarget.java:534)
	at org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.doInvoke(jdk.internal.vm.compiler/OptimizedCallTarget.java:518)
	at org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.callDirect(jdk.internal.vm.compiler/OptimizedCallTarget.java:481)
	at org.graalvm.compiler.truffle.runtime.OptimizedDirectCallNode.call(jdk.internal.vm.compiler/OptimizedDirectCallNode.java:71)
	at com.oracle.truffle.js.nodes.function.JSFunctionCallNode$UnboundJSFunctionCacheNode.executeCall(JSFunctionCallNode.java:1258)
	at com.oracle.truffle.js.nodes.function.JSFunctionCallNode.executeAndSpecialize(JSFunctionCallNode.java:305)
	at com.oracle.truffle.js.nodes.function.JSFunctionCallNode.executeCall(JSFunctionCallNode.java:251)
	at com.oracle.truffle.js.nodes.function.JSNewNode.doNewReturnThis(JSNewNode.java:148)
	at com.oracle.truffle.js.nodes.function.JSNewNodeGen.executeAndSpecialize(JSNewNodeGen.java:108)
	at com.oracle.truffle.js.nodes.function.JSNewNodeGen.execute(JSNewNodeGen.java:84)
	at com.oracle.truffle.js.nodes.JavaScriptNodeWrapper.execute(JavaScriptNodeWrapper.java:45)
	at com.oracle.truffle.js.nodes.access.JSWriteCurrentFrameSlotNodeGen.execute_generic4(JSWriteCurrentFrameSlotNodeGen.java:163)
	at com.oracle.truffle.js.nodes.access.JSWriteCurrentFrameSlotNodeGen.execute(JSWriteCurrentFrameSlotNodeGen.java:86)
	at com.oracle.truffle.js.nodes.JavaScriptNodeWrapper.executeVoid(JavaScriptNodeWrapper.java:274)
	at com.oracle.truffle.js.nodes.control.AbstractBlockNode.executeVoid(AbstractBlockNode.java:80)
	at com.oracle.truffle.js.nodes.control.AbstractBlockNode.executeVoid(AbstractBlockNode.java:55)
	at org.graalvm.compiler.truffle.runtime.OptimizedBlockNode.executeVoid(jdk.internal.vm.compiler/OptimizedBlockNode.java:120)
	at com.oracle.truffle.js.nodes.control.AbstractBlockNode.executeVoid(AbstractBlockNode.java:70)
	at com.oracle.truffle.js.nodes.control.VoidBlockNode.execute(VoidBlockNode.java:61)
	at com.oracle.truffle.js.nodes.JavaScriptNodeWrapper.execute(JavaScriptNodeWrapper.java:45)
	at com.oracle.truffle.js.nodes.function.FunctionBodyNode.execute(FunctionBodyNode.java:73)
	at com.oracle.truffle.js.nodes.instrumentation.DeclareTagProvider$MaterializedFunctionBodyNode.execute(DeclareTagProvider.java:155)
	at com.oracle.truffle.js.nodes.JavaScriptNodeWrapper.execute(JavaScriptNodeWrapper.java:45)
	at com.oracle.truffle.js.nodes.function.FunctionRootNode.executeInRealm(FunctionRootNode.java:147)
	at com.oracle.truffle.js.runtime.JavaScriptRealmBoundaryRootNode.execute(JavaScriptRealmBoundaryRootNode.java:93)
	at org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.executeRootNode(jdk.internal.vm.compiler/OptimizedCallTarget.java:613)
	at org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.profiledPERoot(jdk.internal.vm.compiler/OptimizedCallTarget.java:584)
	at org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.callBoundary(jdk.internal.vm.compiler/OptimizedCallTarget.java:534)
	at org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.doInvoke(jdk.internal.vm.compiler/OptimizedCallTarget.java:518)
	at org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.callDirect(jdk.internal.vm.compiler/OptimizedCallTarget.java:481)
	at org.graalvm.compiler.truffle.runtime.OptimizedDirectCallNode.call(jdk.internal.vm.compiler/OptimizedDirectCallNode.java:71)
	at com.oracle.truffle.js.nodes.function.JSFunctionCallNode$UnboundJSFunctionCacheNode.executeCall(JSFunctionCallNode.java:1258)
	at com.oracle.truffle.js.nodes.function.JSFunctionCallNode.executeAndSpecialize(JSFunctionCallNode.java:305)
	at com.oracle.truffle.js.nodes.function.JSFunctionCallNode.executeCall(JSFunctionCallNode.java:251)
	at com.oracle.truffle.js.nodes.function.JSFunctionCallNode$CallNode.execute(JSFunctionCallNode.java:521)
	at com.oracle.truffle.js.nodes.JavaScriptNodeWrapper.execute(JavaScriptNodeWrapper.java:45)
	at com.oracle.truffle.js.nodes.control.DiscardResultNode.execute(DiscardResultNode.java:88)
	at com.oracle.truffle.js.nodes.unary.JSUnaryNodeWrapper.execute(JSUnaryNodeWrapper.java:45)
	at com.oracle.truffle.js.nodes.control.AbstractBlockNode.executeGeneric(AbstractBlockNode.java:85)
	at com.oracle.truffle.js.nodes.control.AbstractBlockNode.executeGeneric(AbstractBlockNode.java:55)
	at org.graalvm.compiler.truffle.runtime.OptimizedBlockNode.executeGeneric(jdk.internal.vm.compiler/OptimizedBlockNode.java:81)
	at com.oracle.truffle.js.nodes.control.AbstractBlockNode.execute(AbstractBlockNode.java:75)
	at com.oracle.truffle.js.nodes.function.FunctionBodyNode.execute(FunctionBodyNode.java:73)
	at com.oracle.truffle.js.nodes.instrumentation.DeclareTagProvider$MaterializedFunctionBodyNode.execute(DeclareTagProvider.java:155)
	at com.oracle.truffle.js.nodes.JavaScriptNodeWrapper.execute(JavaScriptNodeWrapper.java:45)
	at com.oracle.truffle.js.nodes.function.FunctionRootNode.executeInRealm(FunctionRootNode.java:147)
	at com.oracle.truffle.js.runtime.JavaScriptRealmBoundaryRootNode.execute(JavaScriptRealmBoundaryRootNode.java:93)
	at org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.executeRootNode(jdk.internal.vm.compiler/OptimizedCallTarget.java:613)
	at org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.profiledPERoot(jdk.internal.vm.compiler/OptimizedCallTarget.java:584)
	at org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.callBoundary(jdk.internal.vm.compiler/OptimizedCallTarget.java:534)
	at org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.doInvoke(jdk.internal.vm.compiler/OptimizedCallTarget.java:518)
	at org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.callIndirect(jdk.internal.vm.compiler/OptimizedCallTarget.java:463)
	at org.graalvm.compiler.truffle.runtime.OptimizedIndirectCallNode.call(jdk.internal.vm.compiler/OptimizedIndirectCallNode.java:52)
	at com.oracle.truffle.js.nodes.function.JSFunctionCallNode$GenericJSFunctionCacheNode.executeCall(JSFunctionCallNode.java:1616)
	at com.oracle.truffle.js.nodes.function.JSFunctionCallNode.executeCall(JSFunctionCallNode.java:247)
	at com.oracle.truffle.js.nodes.interop.JSInteropExecuteNode.doDefault(JSInteropExecuteNode.java:68)
	at com.oracle.truffle.js.nodes.interop.JSInteropExecuteNodeGen.execute(JSInteropExecuteNodeGen.java:38)
	at com.oracle.truffle.js.runtime.builtins.JSFunctionObject.execute(JSFunctionObject.java:140)
	at com.oracle.truffle.js.runtime.builtins.JSFunctionObjectGen$InteropLibraryExports$Cached.execute(JSFunctionObjectGen.java:126)
	at com.oracle.truffle.api.interop.InteropLibraryGen$CachedDispatch.execute(org.graalvm.truffle/InteropLibraryGen.java:7592)
	at com.oracle.truffle.polyglot.PolyglotValue$InteropCodeCache$AbstractExecuteNode.executeShared(org.graalvm.truffle/PolyglotValue.java:3097)
	at com.oracle.truffle.polyglot.PolyglotValue$InteropCodeCache$ExecuteNode.executeImpl(org.graalvm.truffle/PolyglotValue.java:3178)
	at com.oracle.truffle.polyglot.HostToGuestRootNode.execute(org.graalvm.truffle/HostToGuestRootNode.java:134)
	at org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.executeRootNode(jdk.internal.vm.compiler/OptimizedCallTarget.java:613)
	at org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.profiledPERoot(jdk.internal.vm.compiler/OptimizedCallTarget.java:584)
	at org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.doInvoke(jdk.internal.vm.compiler/OptimizedCallTarget.java:518)
	at org.graalvm.compiler.truffle.runtime.GraalRuntimeSupport.callProfiled(jdk.internal.vm.compiler/GraalRuntimeSupport.java:143)
	at com.oracle.truffle.polyglot.PolyglotValue$InteropValue.execute(org.graalvm.truffle/PolyglotValue.java:4537)
	at org.graalvm.polyglot.Value.execute(org.graalvm.sdk/Value.java:834)
	at io.github.hejcz.utils.js.GraalScriptExecutor.runScript(GraalScriptExecutor.java:382)
	at io.github.hejcz.utils.js.GraalScriptExecutor.runScriptWithTimeout(GraalScriptExecutor.java:352)
	...
	at java.util.concurrent.ThreadPoolExecutor.runWorker(java.base@16.0.1/ThreadPoolExecutor.java:1130)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(java.base@16.0.1/ThreadPoolExecutor.java:630)
	at java.lang.Thread.run(java.base@16.0.1/Thread.java:831)

```
</details>

**Comment by hejcz** [comment] 2021-06-23 08:07
I managed to reproduce the issue under debugger.

```
@Test
    void shouldHandleRegex() throws IOException, InterruptedException {
        Context context = Context.newBuilder().build();
        String script = "(function abc() { 'some test text'.match('tes') })();";
        ScheduledExecutorService executorService = Executors.newSingleThreadScheduledExecutor();
        try {
            executorService.schedule(() -> context.close(true), 3, TimeUnit.SECONDS);
            context.eval(Source.newBuilder("js", script, "test").build());
        } finally {
            executorService.shutdown();
            executorService.awaitTermination(10, TimeUnit.SECONDS);
        }
    }
```

Link to video:
https://drive.google.com/file/d/1kTSwkZSNE0eVuT6MdHOgSd_h_po06bHd/view?usp=sharing

**Comment by hejcz** [comment] 2021-06-24 14:09
@chumer does someone look into this issue?

**Comment by mcraj017** [comment] 2021-06-25 05:27
@hejcz thanks for reporting the issue
we will check it out and get back to you

**Comment by chumer** [comment] 2021-06-25 10:05
There is indeed a problem with lock ordering in 21.1.
This should be fixed in 21.2 as the code changed substantially (we no longer use instrumentation for cancellation).
I couldn't quite follow your video to reproduce though, but the thread dump is enough to see what is going on.

The problem is that we attach the cancel instrumentation while we hold the engine lock. We must not do this. We should have our own lock to enable the cancel instrumentation to guarantee lock ordering. 

Could you try to reproduce with latest 21.2?
https://github.com/graalvm/graalvm-ce-dev-builds/releases/tag/21.2.0-dev-20210617_2202

**Comment by chumer** [comment] 2021-06-25 10:07
Also be aware that our JDK 16 support in 21.1 is only experimental. But this issue is not really related to the JDK version.

**Comment by hejcz** [comment] 2021-06-25 14:54
I'll test 21.2.0-dev next week and let you know whether bug still occurs.

**Comment by hejcz** [comment] 2021-06-28 07:43
@chumer right now we use:
- org.graalvm.compiler:compiler.jar
- org.graalvm.compiler:compiler-management.jar
- org.graalvm.truffle:truffle-api.jar
- org.graalvm.sdk:graal-sdk.jar
- org.graalvm.js:js.jar
and their dependencies. How to get them? I believe they're not in graalvm-ce-java16-linux-amd64-dev.tar.gz. Do I need to build the project myself (any guide if so)?

**Comment by jchalou** [comment] 2021-06-28 14:28
@hejcz We don't have a public maven repo for snapshot builds. Please find the required jars in the attached zip file.

[graal-maven-21.3.0-SNAPSHOT.zip](https://github.com/oracle/graal/files/6727041/graal-maven-21.3.0-SNAPSHOT.zip)

**Comment by hejcz** [comment] 2021-06-28 14:38
@jchalou thanks, could you share 21.2.0 version as well?

**Comment by jchalou** [comment] 2021-06-28 16:13
@hejcz Sure here it is:

[graal-maven-21.2.0-SNAPSHOT.zip](https://github.com/oracle/graal/files/6727726/graal-maven-21.2.0-SNAPSHOT.zip)

I have some bad news though. `context.close(true)` does not work on the latest version of JDK16 because of the JVMCI version. You will get this message: "Thread local handshakes are not supported on this platform. A possible reason may be that the underlying JVMCI version is too old.".
Early access JDK17 won't have that issue, but I just checked and it seems that graal compiler has some issues there. I will investigate further and get back to you.

**Comment by hejcz** [comment] 2021-06-28 16:26
Could you provide some more details on this news? Is it possible to make `context.close(true)` work on JDK 16 or is it impossible for some reason?

**Comment by jchalou** [comment] 2021-06-28 16:29
@hejcz It depends on the JVMCI version. I will find out whether JVMCI will be updated for some later version of JDK16 and get back to you. Please note that GraalVM doesn't have that problem. JVMCI changes are always backported there, co `context.close(true)` works even for JDK8-based GraalVM.

**Comment by hejcz** [comment] 2021-06-28 16:59
@jchalou I'm confused as we use JDK 16 with graal compiler 21.1.0 and `context.close(true)` seems to work (beside occasional deadlock). So it seems something changed in version 21.2.0 what results in "Thread local handshakes are not supported on this platform. A possible reason may be that the underlying JVMCI version is too old." (I checked it does).

**Comment by jchalou** [comment] 2021-06-28 20:05
@hejcz Yes, there is a significant change in 21.2 as indicated by @chumer in his first comment ("This should already be fixed in 21.2 as the code changed substantially (we no longer use instrumentation for cancellation)"). Namely, the cancel operation (`context.close(true)`) uses completely different mechanism in 21.2 called "Truffle safepoints" and that required changes in JVMCI which are no problem for GraalVM, but for OpenJDK, these changes end up only in the next available release. I will find out exactly which OpenJDK versions include or will include the required JVMCI changes. As for graal version 21.1 you can continue using it with your current JDK16. We also plan to backport a fix for the deadlock. However, other than using GraalVM, we don't have a solution for you at the moment that will both be deadlock-free and will work on your current JDK16.

**Comment by hejcz** [comment] 2021-06-28 20:10
Thanks for clarification. Do I understand correctly that "backport a fix for the deadlock" means there will be some 21.1.x version with fix?

**Comment by jchalou** [comment] 2021-06-29 07:55
Yes, the plan is to backport to 21.1. I cannot guarantee that this will happen, but we will do our best.

**Comment by hejcz** [comment] 2021-06-29 09:49
One more question - does it mean than version 21.2 (and following) won't work on any OpenJDK until they update JVMCI?

**Comment by jchalou** [comment] 2021-06-29 10:13
Short answer: Yes. Long answer: Regular closing of a context (`context.close()`) will work with graal version 21.2+ on any OpenJDK where graal version 21.1 works. Only cancel-close (`context.close(true)`) and interrupt (`context.interrupt()`) requires the JVMCI changes on graal version 21.2+. And that will work only on OpenJDK17+ and (hopefully) on a later version of OpenJDK16. I am still trying to clarify the situation with OpenJDK16.

**Comment by jchalou** [comment] 2021-06-29 11:17
The following is the list of JDKs that include the necessary JVMCI changes. "Other JDK" means other than GraalVM. This is the relevant change: https://bugs.openjdk.java.net/browse/JDK-8264016. 

Other JDK 11: Oracle JDK 11.0.13 (2021-10-19), OpenJDK is still to be determined.
Other JDK 16: No current plans to update JVMCI.
Other JDK 17: The new JVMCI version is already integrated into early access builds.

So it doesn't seem that the `context.close(true)` will work on OpenJDK16 with graal version 21.2+, unless you remove graal compiler from the upgrade-module-path and use the fallback runtime. But that means that compilation won't work and performance will be severely affected.

**Comment by hejcz** [comment] 2021-06-29 12:22
Thanks, please let me know once it's determined if there will be a fix in 21.1.

**Comment by jchalou** [comment] 2021-06-29 13:25
Ok, will do.

**Comment by hejcz** [comment] 2021-06-29 15:05
@jchalou most likely we won't use JDK 17 before an official release. However downgrade to 20.3 might be an option. We upgraded to 21.1 solely because of https://github.com/oracle/graaljs/issues/429. Could you confirm that 20.3 got a fix for that issue?

**Comment by jchalou** [comment] 2021-06-29 15:18
@hejcz Version 20.3.3 will be released on July 20th, same as 21.2.0.

**Comment by hejcz** [comment] 2021-07-01 07:58
@jchalou I checked commits on 20.3 branch and there are some JVMCI updates. Are these changes compatibile with JDK16?

**Comment by jchalou** [comment] 2021-07-01 14:01
@hejcz There are still things that need to be backported to 20.3.3 to make it work with JDK16. I am on it, I will keep you posted.

**Comment by jchalou** [comment] 2021-07-04 19:18
@hejcz  20.3.3 is compatible with JDK16. You can check yourself, the following snapshot should be very close to the version that will be released on July 20th.

[graal-maven-20.3.3-SNAPSHOT.zip](https://github.com/oracle/graal/files/6760476/graal-maven-20.3.3-SNAPSHOT.zip)

**Comment by hejcz** [comment] 2021-07-21 14:01
@jchalou in 20.3.3 release we haven't experienced any problems for now. It seems to work as expected! Thank you!

**Comment by jchalou** [comment] 2021-07-21 19:46
You're welcome!

**Closed** 2021-07-26 07:28 UTC
Labels: tracking, truffle
