### ISSUE TITLE
Building native-image throws a NPE using GraalVM CE 21.3.0

### ISSUE THREAD

**Issue by INPUTsys-Chris** [oracle/graal#3977] opened 2021-11-02 13:43 UTC
We encounter an internal NPE while compiling a simple webapp embedded in Tomcat-embed (version 9.0.54) on Windows.
Both the Java 11 and 17 versions are affected. It also happens with current 22.0 DEV version (tried only the Java 17 version).

Output:

```
D:\appdir>native-image --no-server --allow-incomplete-classpath --enable-https --initialize-at-build-time=org.eclipse.jdt,org.apache.el.parser.SimpleNode,javax.servlet.jsp.JspFactory,org.apache.jasper.servlet.JasperInitializer,org.apache.jasper.runtime.JspFactoryImpl-da -cp "app/WEB-INF/classes;app/WEB-INF/lib/*;apache-tomcat-embed/*;lib/javax.inject.jar" --no-fallback -J-Xmx16G -H:ConfigurationFileDirectories=graalvmconfig -H:+JNI -H:TempDirectory=tmp -H:+ReportUnsupportedElementsAtRuntime -H:+ReportExceptionStackTraces -H:EnableURLProtocols=http,https,jar,jrt -H:IncludeResources='.*/.*$' -H:+AddAllFileSystemProviders -H:+IncludeAllLocales -H:Name=app -jar Test.jar
Warning: Ignoring server-mode native-image argument --no-server.
[Test:5024]    classlist:   3,417.31 ms,  0.94 GB
[Test:5024]        (cap):   1,708.90 ms,  0.94 GB
The URL protocol jar is not tested and might not work as expected.
Supported URL protocols enabled by default: file,resource. Supported URL protocols available on demand: http,https.
The URL protocol jrt is not tested and might not work as expected.
Supported URL protocols enabled by default: file,resource. Supported URL protocols available on demand: http,https.
[Test:5024]        setup:   3,639.85 ms,  0.94 GB
The bundle named: org.apache.tomcat.util.threads.res.LocalStrings, has not been found. If the bundle is part of a module, verify the bundle name is a fully qualified class name. Otherwise verify the bundle path is accessible in the classpath.
The bundle named: org.apache.tomcat.util.threads.res.LocalStrings, has not been found. If the bundle is part of a module, verify the bundle name is a fully qualified class name. Otherwise verify the bundle path is accessible in the classpath.
[Test:5024]     (clinit):   1,011.26 ms,  7.93 GB
[Test:5024]   (typeflow):  16,093.95 ms,  7.93 GB
[Test:5024]    (objects):  32,729.94 ms,  7.93 GB
[Test:5024]   (features): 536,427.11 ms,  7.93 GB
[Test:5024]     analysis: 588,933.01 ms,  7.93 GB
[Test:5024]     universe:   4,270.10 ms,  7.83 GB
[Test:5024]      (parse):   2,177.09 ms,  7.83 GB
[Test:5024]     (inline):   9,287.11 ms,  7.35 GB
[Test:5024]    (compile):  60,845.29 ms,  7.44 GB
[Test:5024]      compile:  76,483.86 ms,  7.44 GB
Fatal error: java.lang.NullPointerException: Cannot read field "index" because "entry" is null
        at jdk.internal.vm.compiler/org.graalvm.compiler.core.common.util.FrequencyEncoder.getIndex(FrequencyEncoder.java:114)
        at com.oracle.svm.core.code.MethodMetadataEncoder.encodeMethodMetadata(MethodMetadataEncoder.java:172)
        at com.oracle.svm.core.code.MethodMetadataEncoder.encodeAllAndInstall(MethodMetadataEncoder.java:83)
        at com.oracle.svm.core.code.CodeInfoEncoder.encodeAllAndInstall(CodeInfoEncoder.java:256)
        at com.oracle.svm.hosted.image.NativeImageCodeCache.buildRuntimeMetadata(NativeImageCodeCache.java:252)
        at com.oracle.svm.hosted.image.LIRNativeImageCodeCache.layoutMethods(LIRNativeImageCodeCache.java:107)
        at com.oracle.svm.hosted.NativeImageGenerator.doRun(NativeImageGenerator.java:614)
        at com.oracle.svm.hosted.NativeImageGenerator.run(NativeImageGenerator.java:493)
        at com.oracle.svm.hosted.NativeImageGeneratorRunner.buildImage(NativeImageGeneratorRunner.java:415)
        at com.oracle.svm.hosted.NativeImageGeneratorRunner.build(NativeImageGeneratorRunner.java:573)
        at com.oracle.svm.hosted.NativeImageGeneratorRunner.main(NativeImageGeneratorRunner.java:126)
        at com.oracle.svm.hosted.NativeImageGeneratorRunner$JDK9Plus.main(NativeImageGeneratorRunner.java:603)
[Test:5024]      [total]: 688,954.78 ms,  7.44 GB
# Printing build artifacts to: D:\appdir\Test.build_artifacts.txt
Error: Image build request failed with exit status 1
```

It's important to notice that if we use 21.2.0 agent generated config files the problems goes away. So somehow the agent creates invalid files or the files are incorrectly parsed.

Both variants are attached here:

[configfiles.zip](https://github.com/oracle/graal/files/7461060/configfiles.zip)

**Comment by rodrigar-mx** [comment] 2021-11-06 00:56
Hi @INPUTsys-Chris. Thanks for sharing the issue. Is it possible for you to share the web app you are having problems with?

**Comment by INPUTsys-Chris** [comment] 2021-11-13 13:39
@rodrigar-mx

Sorry for my late reply. I can't share the original app but I will try to find time to test with a simpler app next week.

**Comment by INPUTsys-Chris** [comment] 2021-11-16 15:19
[graalvm_3977.zip](https://github.com/oracle/graal/files/7547506/graalvm_3977.zip)

Here is a simple app demonstrating the NPE. It includes an embedded tomcat and the app, together with the batch script used to compile.

I couldn't reproduce the error with a config generated with this app, so I included the config of the original app.

It hope that's sufficient for you to debug your compilation.

Thank you.

**Comment by rodrigar-mx** [comment] 2021-11-19 23:01
Hi @INPUTsys-Chris. Thanks for sharing. I observed that if building the config files with the tracing agent, no error appears. And that when using the config files you have included, the error presents.  I also detected that the problematic file seems to be `reflect-config.json`, and that when changing the entry in that file
```
{
  "name":"com.vaadin.flow.component.grid.Grid",
  "queryAllDeclaredMethods":true,
  "methods":[{"name":"confirmUpdate","parameterTypes":["int"] }]
}
```
to just
```
{
  "name":"com.vaadin.flow.component.grid.Grid",
}
```
error is gone. Could you try it out and confirm it? I am still investigating possible causes.

**Comment by INPUTsys-Chris** [comment] 2021-11-20 12:36
Yes, I can confirm that fixes the issue for me.

I had to remove the extra comma but I guess that's just a copy/paste error on your side.

**Comment by bojanv55** [comment] 2021-11-28 11:29
@rodrigar-mx  I have the same problem with spring-native app. When I set-up for debugging and listening for null-pointer, I can see that this one is making a problem:

`[Lcom.fasterxml.jackson.databind.JsonSerializer;`

The thing is that I do not have this defined in the `reflect-config.json` at all, so not sure how to solve it? If I add it manually it still complains about null-pointer (maybe different one this time, but cannot see which one since it takes so long to hit that breakpoint).

**Comment by bojanv55** [comment] 2021-11-28 17:29
I managed to solve this problem after adding these 3 lines to `reflect-config.json`

```
  {
    "name":"[Lcom.fasterxml.jackson.databind.JsonSerializer;"
  },
  {
    "name":"[Lcom.fasterxml.jackson.databind.JsonDeserializer;"
  },
  {
    "name":"[Lorg.springframework.context.ApplicationContextInitializer;"
  },
```

Not sure how these were not picked-up by `native-image-agent`?

**Comment by andgeno** [comment] 2021-11-28 18:46
Is there actually a way to debug this kind of error?

```
Fatal error:java.lang.NullPointerException: Cannot read field "index" because "entry" is null
        at jdk.internal.vm.compiler/org.graalvm.compiler.core.common.util.FrequencyEncoder.getIndex(FrequencyEncoder.java:114)
        at com.oracle.svm.core.code.MethodMetadataEncoder.encodeMethodMetadata(MethodMetadataEncoder.java:200)
        at com.oracle.svm.core.code.MethodMetadataEncoder.encodeAllAndInstall(MethodMetadataEncoder.java:97)
        at com.oracle.svm.core.code.CodeInfoEncoder.encodeAllAndInstall(CodeInfoEncoder.java:266)
        at com.oracle.svm.hosted.image.NativeImageCodeCache.buildRuntimeMetadata(NativeImageCodeCache.java:272)
        at com.oracle.svm.hosted.image.LIRNativeImageCodeCache.layoutMethods(LIRNativeImageCodeCache.java:106)
        at com.oracle.svm.hosted.NativeImageGenerator.doRun(NativeImageGenerator.java:608)
        at com.oracle.svm.hosted.NativeImageGenerator.run(NativeImageGenerator.java:488)
        at com.oracle.svm.hosted.NativeImageGeneratorRunner.buildImage(NativeImageGeneratorRunner.java:403)
        at com.oracle.svm.hosted.NativeImageGeneratorRunner.build(NativeImageGeneratorRunner.java:569)
        at com.oracle.svm.hosted.NativeImageGeneratorRunner.main(NativeImageGeneratorRunner.java:122)
        at com.oracle.svm.hosted.NativeImageGeneratorRunner$JDK9Plus.main(NativeImageGeneratorRunner.java:599)
```

I'm totally lost on how to debug this in order to find out what is causing this error. It seemslike this is an error within GraalVM itself.

**Comment by bojanv55** [comment] 2021-11-28 19:22
@andgeno What I actually did (using intellij), I put breakpoint to this line:

![image](https://user-images.githubusercontent.com/1422698/143782698-81934fa4-1fa0-461d-ba9c-c9afe1484b17.png)

and then made a change in `native-image.cmd` where I added debugging support to port 8888:

`"%location%..\lib\svm\bin\native-image.exe" --debug-attach=8888  %*`

and then I waited native compilation process to show `Listening for transport dt_socket at address: 8888`

Then I run remote java debug session to the port 8888, and wait for it to hit the breakpoint. Then I can see what was the actual error in the debug window...

**Comment by INPUTsys-Chris** [comment] 2021-11-29 06:51
> 
> I'm totally lost on how to debug this in order to find out what is causing this error. It seems like this is an error within GraalVM itself.

You're right. The exception is a NullPointerException and it's an internal error.

**Comment by rodrigar-mx** [comment] 2021-12-03 22:30
Hi @INPUTsys-Chris @bojanv55 @andgeno. I have reported this error with the native image team. An answer will be provided accordingly.

**Comment by andgeno** [comment] 2021-12-03 22:51
Maybe this helps to further debug this error:

Using the debugger didn't help me so I decided to brute force through this. So in my case, I found out that the `reflect-config.json` (generated via `spring-aot-maven-plugin`) was causing the NPE I posted above. 

My config contains an entry like this:
```
[
  {
    "name": "org.springframework.boot.SpringApplication",
    "queryAllDeclaredMethods": true
  }
]
```

When I removed `queryAllDeclaredMethods` from this, the error disappeared and everything was working.

**Comment by INPUTsys-Chris** [comment] 2022-03-01 16:02
@rodrigar-mx did you get feedback from the native-image team?

**Comment by rodrigar-mx** [comment] 2022-03-01 23:58
Hi @INPUTsys-Chris. Not yet, the issue is still in queue. Any update or question we will let you know. You can try latest [22.1.0](https://github.com/graalvm/graalvm-ce-dev-builds/releases) dev build to generate the config files and build again, and share if there was any progress.

**Comment by INPUTsys-Chris** [comment] 2022-03-02 10:07
@rodrigar-mx I tried the latest 22.1 dev build and the error doesn't occur any more. Thats good. But I can't say if the bug is still in there, the generated config files are much smaller now. Don't know if that is by design or an error in the dev build.

**Comment by rodrigar-mx** [comment] 2022-03-02 20:22
Glad it works now. The error is probably already fixed. I am going to close this issue for now. If you find again the error in future versions, feel free to reopen this issue or create a new one.

**Closed by rodrigar-mx** 2022-03-02 20:22 UTC
Labels: native-image
