### ISSUE TITLE
Graal gives undeterministic results

### ISSUE THREAD

**Issue by connglli** [oracle/graal#4756] opened 2022-07-25 13:31 UTC
**Describe the issue**

This is a JIT bug where Graal gives a different output from the interpreter or HotSpot's C1/C2 compiler.

**Steps to reproduce the issue**

1. javac T.java
2. java T >aaa
3. java T >bbb
4. diff aaa bbb

The results of aaa and bbb are different, while expected to be the same; both aaa and bbb are different from the results of the interpreter.

**Describe GraalVM and your environment:**
 - GraalVM version: 22.3.0-dev
 - JDK major version: 11.0.16
 - OS: Ubuntu 20.04
 - Architecture: x86_64

**More details**

The following is the source of our tests:

``` java
class T {
  short s;

  float a(long l) {
    int i = 114, j, k = 14;
    double d[] = new double[256];
    do {
      for (j = 1; j < 2; j++) {
        s *= l | 1;
        ++k;
      }
      k &= j;
      l = k;
      k = 35427;
    } while ((i += 3) < 205);
    return Double.doubleToLongBits(b(d));
  }

  double b(double[] a) {
    for (int j = 0; j < a.length; j++) s += j;
    return s;
  }

  void f() {
    for (int ax$27 = 0; ax$27 < 12702; ax$27 += 1)
      a(0L);
    System.out.println(s);
  }

  public static void main(String[] strArr) {
    T t = new T();
    t.f();
  }
}
```

Result of the interpreter:

```
$ java -Xint T
20992
```

Result of Graal compiler (undeterministic):

```
$ java T
19456

$ java T
-11776
```

**Comment by connglli** [comment] 2022-08-09 10:42
Seems like this is also a duplicate of #4754? I currrently cannot reproduce it with the newest development build.

**Comment by gergo-** [comment] 2022-08-09 13:59
This is also fixed by 169807, so yes, it's also a duplicate of #4754. I will close it accordingly.

The nondeterminism seems to come from the fact that the method `a` both reads and writes the field `s`. Therefore calls to `a` are not independent, even though it is always called with the same value for the parameter `l`. Depending on the exact time when the compilation of `a` is complete, execution will spend more or fewer iterations of `a` in an incorrectly compiled version of the method. Therefore small, unavoidable timing variations can affect the result.

**Closed by gergo-** 2022-08-09 13:59 UTC
Labels: bug
