### ISSUE TITLE
DebugInfo file+line info generation for susbtitutions is using the wrong source file

### ISSUE THREAD

**Issue by adinn** [oracle/graal#3420] opened 2021-05-19 12:01 UTC
The debug info generator is currently generating the wrong file info for some method and field substitutions.

This can be shown by running any native app that uses method substitutions. Placing a break on at substituted method entry will use the right line number but display the code in the file for the original method.

The failure happens on Graal 21.1 and on the latest head.

The problem is actually a combination of several errors. One of them is down to a change to the way class SubstitutionMethod and SubstitutionField report the declaring class for a substituted method/field. The fix should include a modification to the debuginfotest test code (class hello.Hello) to ensure that it tests break points for substituted methods, ensuring that any future changes which might cause similar problems are caught early.

**Comment by mcraj017** [comment] 2021-05-24 04:43
@adinn thanks for reporting the issue
please provide a reproducer for this issue

**Comment by christianwimmer** [comment] 2021-06-04 02:58
@adinn The Oracle GraalVM support team (@mcraj017 in this case) is monitoring GitHub issues and triaging them before raising them internally.
Now issues like this one is something that is a bit confusing for them, because they do not know that this is an issue for a component that you are actually working on so a bug that you are (hopefully) going to fix eventually.

We have a few options on how to make that transparent for the support team:
1) You can immediately assign the issue to yourself, or someone else you know who might eventually look at it. Then it is clear that you are responsible for the issue.
2) We can come up with a special label for such issues.

The first is probably the easiest. What do you think?

**Comment by christianwimmer** [comment] 2021-06-06 03:51
> Unfortunately, I'm not clear how I am supposed to achieve that. Likewise, I am not clear how to link the PR for a fix to the original issue -- as you can see I raised PR #3421 right after creating the issue but it is still not linked.

Interesting. I guess I need to find out how more people can be allowed to assign issues (and if there is a good reason why this is restricted in the first place). @shelajev  do you know?

**Comment by zakkak** [comment] 2021-06-07 10:38
> Likewise, I am not clear how to link the PR for a fix to the original issue -- as you can see I raised PR #3421 right after creating the issue but it is still not linked.

@adinn the easiest way to achieve this is to add to the description of the PR `fixes #3420` or `closes #3420`, see [here](https://docs.github.com/en/issues/tracking-your-work-with-issues/creating-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword) for more details. 

> Interesting. I guess I need to find out how more people can be allowed to assign issues (and if there is a good reason why this is restricted in the first place).

+1 we have started a similar discussion in https://github.com/oracle/graal/issues/2767 as well, so @RoxaBee might able to answer about the "Triage" privilege.

**Comment by mcraj017** [comment] 2021-06-08 01:25
I have attached the PR with this issue
Closing it now

**Closed by mcraj017** 2021-06-08 01:25 UTC
Labels: bug, native-image
