### ISSUE TITLE
Native: java.awt.AWTError: Toolkit not found: sun.awt.X11.XToolkit

### ISSUE THREAD

**Issue by travispeloton** [oracle/graal#4807] opened 2022-08-10 20:32 UTC
**Describe the issue**
I'm building a native image to run on AWS Lambda. I got it to work, but am unable to get a library (Batik) to work with it.

Had to install the following additional X11 libs into the Docker image that I'm using for builds:

```
yum install -y freetype-devel libXrender-devel libXi-devel libX11.i686
```

I'm sending the `native-image-maven-plugin` Maven plugin the following option:

```
<buildArgs combine.children="append">
    <!-- ... -->
    -Djava.awt.headless=false
</buildArgs>
```

It builds, but at runtime I get:

```
Toolkit not found: sun.awt.X11.XToolkit: java.awt.AWTError
--
java.awt.AWTError: Toolkit not found: sun.awt.X11.XToolkit
at java.awt.Toolkit$2.run(Toolkit.java:595)
at java.awt.Toolkit$2.run(Toolkit.java:583)
at java.security.AccessController.executePrivileged(AccessController.java:169)
at java.security.AccessController.doPrivileged(AccessController.java:83)
at java.awt.Toolkit.getDefaultToolkit(Toolkit.java:582)
at org.apache.batik.bridge.CursorManager.<clinit>(CursorManager.java:102)
at org.apache.batik.bridge.BridgeContext.<init>(BridgeContext.java:1162)
at org.apache.batik.bridge.BridgeContext.<init>(BridgeContext.java:292)
at org.apache.batik.transcoder.SVGAbstractTranscoder.createBridgeContext(SVGAbstractTranscoder.java:338)
at org.apache.batik.transcoder.SVGAbstractTranscoder.createBridgeContext(SVGAbstractTranscoder.java:314)
at org.apache.batik.transcoder.SVGAbstractTranscoder.transcode(SVGAbstractTranscoder.java:196)
at org.apache.batik.transcoder.image.ImageTranscoder.transcode(ImageTranscoder.java:92)
at org.apache.batik.transcoder.XMLAbstractTranscoder.transcode(XMLAbstractTranscoder.java:142)
at org.apache.batik.transcoder.SVGAbstractTranscoder.transcode(SVGAbstractTranscoder.java:158)
...
at java.lang.reflect.Method.invoke(Method.java:566)
```

**Describe GraalVM and your environment:**
- Graal: 22.2.0
- JDK: java11
 - OS: Running `amazon/aws-lambda-provided:al2` Docker image, which appears to be RedHat
 - Architecture: **AMD64**

**Comment by fniephaus** [comment] 2022-08-10 20:54
AWT is highly reflective and requires proper app-specific configuration. Have you created configuration for Native Image with the tracing agent yet? Also, AWT will currently only work with JDK11/17 on Windows and with JDK11 on Linux. macOS is not yet supported.

**Comment by travispeloton** [comment] 2022-08-10 21:17
I need to figure out how to run the app with the Lambda emulator (ugg) in order to do the tracing.

```
                                --initialize-at-build-time=sun.awt.X11.XToolkit
                                -H:+ReportExceptionStackTraces
```

Indicated another missing installed library. Next thing it appears to be asking for is a DISPLAY, which i'm guessing could be a virtual framebuffer library.

**Comment by fniephaus** [comment] 2022-08-10 21:28
Initializing `XToolkit` at build-time does not sound like a good idea: most of the AWT components hold references to native windowing code. You don't want any of these handles to end up in your native executable because they won't be valid at run-time anymore. I suggest initializing sun.awt at run-time and instead, try to avoid that the toolkit is invoked at build-time.

**Comment by travispeloton** [comment] 2022-08-11 17:29
I'm not clear on what you are suggesting. How do I initialize `sun.awt` at runtime to avoid the `sun.awt.X11.XToolkit` error above?

**Comment by fniephaus** [comment] 2022-08-12 07:43
No, you have to make sure that `sun.awt.X11.XToolkit` is not called at build time so that all of `sun.awt` can be initialized at run-time. Maybe set `--initialize-at-run-time=sun.awt` explicitly and then check in which static initializer the toolkit is requested.

**Comment by bflorat** [comment] 2022-08-24 19:23
Same here for a Swing app (see #4749). I tried your suggestion but no luck so far:
Note that I use Graalvm java 11 under Ubuntu :

 java -version
openjdk version "11.0.15" 2022-04-19
OpenJDK Runtime Environment GraalVM CE 22.1.0 (build 11.0.15+10-jvmci-22.1-b06)
OpenJDK 64-Bit Server VM GraalVM CE 22.1.0 (build 11.0.15+10-jvmci-22.1-b06, mixed mode, sharing)

I created native-image configurartion using :

```
java -agentlib:native-image-agent=config-output-dir=META-INF/native-image -Xms30M -Xmx2G -Djava.library.path=lib -cp jajuk.jar:lib/* org.jajuk.Main
```

Then, I removed all references to sun.awt in every META-INF/native-image directory and built using:
```
native-image  -Djava.awt.headless=false --initialize-at-run-time=sun.awt  --no-fallback -H:+ReportExceptionStackTraces  --verbose -cp "jajuk.jar:lib/*"  org.jajuk.Main
```
-> the build work but I still get the same error:

```
native-image  -Djava.awt.headless=false --initialize-at-run-time=sun.awt  --no-fallback -H:+ReportExceptionStackTraces  --verbose -cp "jajuk.jar:lib/*"  org.jajuk.Main
Warning: Invalid classpath entry: /usr/local/share/java/unix.jar
Warning: Invalid classpath entry: /usr/local/share/java/hexdump.jar
Warning: Invalid classpath entry: /usr/local/share/java/debug-disable.jar
Warning: Invalid classpath entry: /home/bflorat/Downloads/jajuk-11.0/lib/xbean.jar
Executing [
/home/bflorat/prog/graalvm-ce-java11-22.1.0/bin/java \
-XX:+UseParallelGC \
-XX:+UnlockExperimentalVMOptions \
-XX:+EnableJVMCI \
-Dtruffle.TrustAllTruffleRuntimeProviders=true \
-Dtruffle.TruffleRuntime=com.oracle.truffle.api.impl.DefaultTruffleRuntime \
-Dgraalvm.ForcePolyglotInvalid=true \
-Dgraalvm.locatorDisabled=true \
-Dsubstratevm.IgnoreGraalVersionCheck=true \
--add-exports=java.base/com.sun.crypto.provider=ALL-UNNAMED \
--add-exports=java.base/jdk.internal.event=ALL-UNNAMED \
--add-exports=java.base/jdk.internal.loader=ALL-UNNAMED \
--add-exports=java.base/jdk.internal.logger=ALL-UNNAMED \
--add-exports=java.base/jdk.internal.misc=ALL-UNNAMED \
--add-exports=java.base/jdk.internal.module=ALL-UNNAMED \
--add-exports=java.base/jdk.internal.org.objectweb.asm=ALL-UNNAMED \
--add-exports=java.base/jdk.internal.perf=ALL-UNNAMED \
--add-exports=java.base/jdk.internal.ref=ALL-UNNAMED \
--add-exports=java.base/jdk.internal.reflect=ALL-UNNAMED \
--add-exports=java.base/jdk.internal.vm.annotation=ALL-UNNAMED \
--add-exports=java.base/sun.invoke.util=ALL-UNNAMED \
--add-exports=java.base/sun.net=ALL-UNNAMED \
--add-exports=java.base/sun.nio.ch=ALL-UNNAMED \
--add-exports=java.base/sun.reflect.annotation=ALL-UNNAMED \
--add-exports=java.base/sun.reflect.generics.factory=ALL-UNNAMED \
--add-exports=java.base/sun.reflect.generics.reflectiveObjects=ALL-UNNAMED \
--add-exports=java.base/sun.reflect.generics.repository=ALL-UNNAMED \
--add-exports=java.base/sun.reflect.generics.scope=ALL-UNNAMED \
--add-exports=java.base/sun.reflect.generics.tree=ALL-UNNAMED \
--add-exports=java.base/sun.security.jca=ALL-UNNAMED \
--add-exports=java.base/sun.security.provider=ALL-UNNAMED \
--add-exports=java.base/sun.security.ssl=ALL-UNNAMED \
--add-exports=java.base/sun.security.util=ALL-UNNAMED \
--add-exports=java.base/sun.security.x509=ALL-UNNAMED \
--add-exports=java.base/sun.text.spi=ALL-UNNAMED \
--add-exports=java.base/sun.util.calendar=ALL-UNNAMED \
--add-exports=java.base/sun.util.cldr=ALL-UNNAMED \
--add-exports=java.base/sun.util.locale.provider=ALL-UNNAMED \
--add-exports=java.base/sun.util.locale=ALL-UNNAMED \
--add-exports=java.base/sun.util.resources=ALL-UNNAMED \
--add-exports=java.base/sun.util=ALL-UNNAMED \
--add-exports=java.desktop/sun.java2d.pipe=ALL-UNNAMED \
--add-exports=java.desktop/sun.java2d=ALL-UNNAMED \
--add-exports=java.management/com.sun.jmx.mbeanserver=ALL-UNNAMED \
--add-exports=java.management/sun.management=ALL-UNNAMED \
--add-exports=java.xml.crypto/org.jcp.xml.dsig.internal.dom=ALL-UNNAMED \
--add-exports=jdk.internal.vm.ci/jdk.vm.ci.aarch64=ALL-UNNAMED \
--add-exports=jdk.internal.vm.ci/jdk.vm.ci.amd64=ALL-UNNAMED \
--add-exports=jdk.internal.vm.ci/jdk.vm.ci.code.site=ALL-UNNAMED \
--add-exports=jdk.internal.vm.ci/jdk.vm.ci.code.stack=ALL-UNNAMED \
--add-exports=jdk.internal.vm.ci/jdk.vm.ci.code=ALL-UNNAMED \
--add-exports=jdk.internal.vm.ci/jdk.vm.ci.common=ALL-UNNAMED \
--add-exports=jdk.internal.vm.ci/jdk.vm.ci.hotspot.aarch64=ALL-UNNAMED \
--add-exports=jdk.internal.vm.ci/jdk.vm.ci.hotspot.amd64=ALL-UNNAMED \
--add-exports=jdk.internal.vm.ci/jdk.vm.ci.hotspot.sparc=ALL-UNNAMED \
--add-exports=jdk.internal.vm.ci/jdk.vm.ci.hotspot=ALL-UNNAMED \
--add-exports=jdk.internal.vm.ci/jdk.vm.ci.meta=ALL-UNNAMED \
--add-exports=jdk.internal.vm.ci/jdk.vm.ci.runtime=ALL-UNNAMED \
--add-exports=jdk.internal.vm.ci/jdk.vm.ci.services=ALL-UNNAMED \
--add-exports=jdk.internal.vm.ci/jdk.vm.ci.sparc=ALL-UNNAMED \
--add-exports=jdk.jfr/jdk.jfr.events=ALL-UNNAMED \
--add-exports=jdk.jfr/jdk.jfr.internal.handlers=ALL-UNNAMED \
--add-exports=jdk.jfr/jdk.jfr.internal.jfc=ALL-UNNAMED \
--add-exports=jdk.jfr/jdk.jfr.internal=ALL-UNNAMED \
--add-exports=jdk.management/com.sun.management.internal=ALL-UNNAMED \
-XX:+UseJVMCINativeLibrary \
-Xss10m \
-Xms1g \
-Xmx14g \
-Djava.awt.headless=true \
-Dorg.graalvm.version=22.1.0 \
-Dorg.graalvm.config=CE \
-Dcom.oracle.graalvm.isaot=true \
-Djava.system.class.loader=com.oracle.svm.hosted.NativeImageSystemClassLoader \
-Xshare:off \
-Djdk.internal.lambda.disableEagerInitialization=true \
-Djdk.internal.lambda.eagerlyInitialize=false \
-Djava.lang.invoke.InnerClassLambdaMetafactory.initializeLambdas=false \
-Djava.awt.headless=false \
-javaagent:/home/bflorat/prog/graalvm-ce-java11-22.1.0/lib/svm/builder/svm.jar \
-cp \
/home/bflorat/prog/graalvm-ce-java11-22.1.0/lib/svm/builder/llvm-wrapper-shadowed.jar:/home/bflorat/prog/graalvm-ce-java11-22.1.0/lib/svm/builder/objectfile.jar:/home/bflorat/prog/graalvm-ce-java11-22.1.0/lib/svm/builder/llvm-platform-specific-shadowed.jar:/home/bflorat/prog/graalvm-ce-java11-22.1.0/lib/svm/builder/pointsto.jar:/home/bflorat/prog/graalvm-ce-java11-22.1.0/lib/svm/builder/svm-llvm.jar:/home/bflorat/prog/graalvm-ce-java11-22.1.0/lib/svm/builder/native-image-base.jar:/home/bflorat/prog/graalvm-ce-java11-22.1.0/lib/svm/builder/javacpp-shadowed.jar:/home/bflorat/prog/graalvm-ce-java11-22.1.0/lib/svm/builder/svm.jar \
--module-path \
/home/bflorat/prog/graalvm-ce-java11-22.1.0/lib/truffle/truffle-api.jar \
'com.oracle.svm.hosted.NativeImageGeneratorRunner$JDK9Plus' \
-watchpid \
1154990 \
-imagecp \
'/home/bflorat/Downloads/jajuk-11.0/jajuk.jar:/home/bflorat/Downloads/jajuk-11.0/lib/*:/usr/local/share/java/unix.jar:/usr/local/share/java/hexdump.jar:/usr/local/share/java/debug-disable.jar:/home/bflorat/Downloads/jajuk-11.0/lib/xbean.jar:/home/bflorat/Downloads/jajuk-11.0/lib:/home/bflorat/prog/graalvm-ce-java11-22.1.0/lib/svm/library-support.jar' \
-H:Path=/home/bflorat/Downloads/jajuk-11.0 \
-H:ClassInitialization=sun.awt:run_time \
-H:FallbackThreshold=0 \
-H:+ReportExceptionStackTraces \
-H:CLibraryPath=/home/bflorat/prog/graalvm-ce-java11-22.1.0/lib/svm/clibraries/linux-amd64 \
'-H:Class@explicit main-class=org.jajuk.Main' \
'-H:Name@main-class lower case as image name=org.jajuk.main'
]
========================================================================================================================
GraalVM Native Image: Generating 'org.jajuk.main' (executable)...
========================================================================================================================
[1/7] Initializing...                                                                                    (5.8s @ 0.29GB)
 Version info: 'GraalVM 22.1.0 Java 11 CE'
 C compiler: gcc (linux, x86_64, 11.2.0)
 Garbage collector: Serial GC
[2/7] Performing analysis...  [********]                                                                (46.0s @ 3.71GB)
  10,638 (88.24%) of 12,056 classes reachable
  19,661 (66.07%) of 29,758 fields reachable
  52,093 (61.24%) of 85,067 methods reachable
     226 classes,     0 fields, and 1,142 methods registered for reflection
      67 classes,    80 fields, and    57 methods registered for JNI access
[3/7] Building universe...                                                                               (3.5s @ 2.29GB)
[4/7] Parsing methods...      [**]                                                                       (3.0s @ 3.38GB)
[5/7] Inlining methods...     [*****]                                                                    (3.8s @ 3.36GB)
[6/7] Compiling methods...    [******]                                                                  (35.4s @ 3.90GB)
[7/7] Creating image...                                                                                  (4.2s @ 5.00GB)
  24.14MB (47.45%) for code area:   31,030 compilation units
  21.43MB (42.13%) for image heap:   7,363 classes and 256,394 objects
   5.30MB (10.42%) for other data
  50.87MB in total
------------------------------------------------------------------------------------------------------------------------
Top 10 packages in code area:                               Top 10 object types in image heap:
 974.30KB java.util                                            5.15MB byte[] for code metadata
 824.78KB com.sun.org.apache.xalan.internal.xsltc.compiler     3.18MB byte[] for general heap data
 717.10KB javax.swing                                          2.84MB java.lang.Class
 522.11KB c.s.org.apache.xerces.internal.impl.xs.traversers    2.51MB java.lang.String
 492.83KB java.lang                                            1.81MB byte[] for java.lang.String
 481.20KB com.sun.org.apache.xerces.internal.impl            997.31KB com.oracle.svm.core.hub.DynamicHubCompanion
 481.11KB java.awt                                           521.70KB java.lang.String[]
 462.30KB com.sun.imageio.plugins.tiff                       459.15KB byte[] for reflection metadata
 450.10KB org.jajuk.base                                     432.33KB java.util.HashMap$Node
 448.48KB com.sun.crypto.provider                            257.86KB java.util.concurrent.ConcurrentHashMap$Node
      ... 433 additional packages                                 ... 1676 additional object types
                                           (use GraalVM Dashboard to see all)
------------------------------------------------------------------------------------------------------------------------
                       12.5s (11.6% of total time) in 34 GCs | Peak RSS: 6.99GB | CPU load: 5.95
------------------------------------------------------------------------------------------------------------------------
Produced artifacts:
 /home/bflorat/Downloads/jajuk-11.0/org.jajuk.main (executable)
 /home/bflorat/Downloads/jajuk-11.0/org.jajuk.main.build_artifacts.txt
========================================================================================================================
Finished generating 'org.jajuk.main' in 1m 46s.
bflorat  ~  Downloads  jajuk-11.0  ./org.jajuk.main
java.awt.AWTError: Toolkit not found: sun.awt.X11.XToolkit
        at java.awt.Toolkit$2.run(Toolkit.java:595)
        at java.awt.Toolkit$2.run(Toolkit.java:583)
        at java.security.AccessController.executePrivileged(AccessController.java:169)
        at java.security.AccessController.doPrivileged(AccessController.java:83)
        at java.awt.Toolkit.getDefaultToolkit(Toolkit.java:582)
        at java.awt.Toolkit.getEventQueue(Toolkit.java:1494)
        at java.awt.EventQueue.invokeLater(EventQueue.java:1312)
        at javax.swing.SwingUtilities.invokeLater(SwingUtilities.java:1421)
        at org.jajuk.Main.main(Main.java:89)
[ERROR] 106 / null
java.awt.AWTError: Toolkit not found: sun.awt.X11.XToolkit
        at java.awt.Toolkit$2.run(Toolkit.java:595)
        at java.awt.Toolkit$2.run(Toolkit.java:583)
        at java.security.AccessController.executePrivileged(AccessController.java:169)
        at java.security.AccessController.doPrivileged(AccessController.java:83)
        at java.awt.Toolkit.getDefaultToolkit(Toolkit.java:582)
        at java.awt.Toolkit.getEventQueue(Toolkit.java:1494)
        at java.awt.EventQueue.invokeLater(EventQueue.java:1312)
        at javax.swing.SwingUtilities.invokeLater(SwingUtilities.java:1421)
        at org.jajuk.Main.main(Main.java:89)
[DEBUG] Exit with code: 1

```
Idea idea ?

**Comment by fniephaus** [comment] 2022-08-24 19:39
@bflorat are you sure the reachability metadata that you generated with the agent is part of your app's jar? it needs to be a resource under `META-INF/native-image/`. The `reflect-config.json` should probably contain `sun.awt.X11.XToolkit`, which makes it reachable. That the class is not found at run-time makes me think that the metadata is not being picked up.

**Comment by travispeloton** [comment] 2022-08-24 20:34
For my use-case, I was able to get past my issue by using the Native tracing tool, and added the generated metadata to `META-INF/native-image/`. Unfortunately, AWS Lambda still complained about needing a `DISPLAY`, so I built a full Docker image. Still trying to test that out. Thanks for the help.

**Comment by bflorat** [comment] 2022-08-24 20:39
@fniephaus : No, when I put the generated native-image content into the jajuk.jar itself, I get the same error that #4749  (the build fails with : 
```
/usr/bin/ld: org.jajuk.main.o: warning: relocation in read-only section `.svm_heap'
/usr/bin/ld: /home/bflorat/prog/graalvm-ce-java11-22.1.0/lib/static/linux-amd64/glibc/libawt_xawt.a(awt_Robot.o): in function `Java_sun_awt_X11_XRobotPeer_setup':
awt_Robot.c:(.text.Java_sun_awt_X11_XRobotPeer_setup+0x1fd): undefined reference to `XTestQueryExtension'
/usr/bin/ld: awt_Robot.c:(.text.Java_sun_awt_X11_XRobotPeer_setup+0x222): undefined reference to `XTestGrabControl'
/usr/bin/ld: warning: creating DT_TEXTREL in a PIE
collect2: error: ld returned 1 exit status
        at com.oracle.svm.hosted.image.NativeImageViaCC.handleLinkerFailure(NativeImageViaCC.java:505)
        at com.oracle.svm.hosted.image.NativeImageViaCC.write(NativeImageViaCC.java:452)
        at com.oracle.svm.hosted.NativeImageGenerator.doRun(NativeImageGenerator.java:695)
        at com.oracle.svm.hosted.NativeImageGenerator.run(NativeImageGenerator.java:515)
        at com.oracle.svm.hosted.NativeImageGeneratorRunner.buildImage(NativeImageGeneratorRunner.java:407)
        at com.oracle.svm.hosted.NativeImageGeneratorRunner.build(NativeImageGeneratorRunner.java:585)
        at com.oracle.svm.hosted.NativeImageGeneratorRunner.main(NativeImageGeneratorRunner.java:128)
        at com.oracle.svm.hosted.NativeImageGeneratorRunner$JDK9Plus.main(NativeImageGeneratorRunner.java:615)
------------------------------------------------------------------------------------------------------------------------
                       21.8s (14.5% of total time) in 55 GCs | Peak RSS: 8.59GB | CPU load: 5.79
========================================================================================================================
Failed generating 'org.jajuk.main' after 2m 30s.
Error: Image build request failed with exit status 1
com.oracle.svm.driver.NativeImage$NativeImageError: Image build request failed with exit status 1
        at com.oracle.svm.driver.NativeImage.showError(NativeImage.java:1678)
        at com.oracle.svm.driver.NativeImage.build(NativeImage.java:1389)
        at com.oracle.svm.driver.NativeImage.performBuild(NativeImage.java:1350)
        at com.oracle.svm.driver.NativeImage.main(NativeImage.java:1337)

```
)
I attached the META-INF zipped directory. And, yes it contains many sun.awt references ...

When I launch the native-image command from the same directory as META-INF/native messaging, the build is ok but it fails at runtime...

[META-INF.zip](https://github.com/oracle/graal/files/9419290/META-INF.zip)

**Comment by fniephaus** [comment] 2022-08-25 07:49
The generated config needs to be used, otherwise it will not work at all. Now that you do this, the problem mentioned in this issue is resolved, so I'm closing this. However, it seems that Native Image doesn't support `XTestGrabControl` correctly at this point, which we should discuss in #4749. If you could provide a short reproducer there, that'd be great. We are currently revising AWT support for Linux and this would be a good test case for that.

**Closed by fniephaus** 2022-08-25 07:49 UTC
Labels: bug, native-image

**Comment by dev2007** [comment] 2024-03-27 12:01
add sun.awt.X11.XToolkit into reflect-config.json is worked.thans.
