### ISSUE TITLE
Can't use HttpURLConnection due to reflection

### ISSUE THREAD

**Issue by lbialy** [oracle/graal#357] opened 2018-04-20 13:33 UTC
A trivial example using `scalaj-http` library (a wrapper for HttpURLConnection) crashes in runtime when compiled to native binary with `native-image` tool. Here's a stack trace:
```
java.lang.AssertionError: Should not here
	at java.lang.Throwable.<init>(Throwable.java:265)
	at java.lang.Error.<init>(Error.java:70)
	at java.lang.AssertionError.<init>(AssertionError.java:58)
	at java.lang.AssertionError.<init>(AssertionError.java:74)
	at sun.util.logging.LoggingSupport.ensureAvailable(LoggingSupport.java:76)
	at sun.util.logging.LoggingSupport.isLoggable(LoggingSupport.java:114)
	at sun.util.logging.PlatformLogger$JavaLoggerProxy.isLoggable(PlatformLogger.java:656)
	at sun.util.logging.PlatformLogger.isLoggable(PlatformLogger.java:270)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1147)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1050)
	at sun.net.www.protocol.http.HttpURLConnection.connect(HttpURLConnection.java:984)
	at scalaj.http.DefaultConnectFunc$.apply(Http.scala:471)
	at scalaj.http.DefaultConnectFunc$.apply(Http.scala:469)
	at scalaj.http.HttpRequest.doConnection(Http.scala:355)
	at scalaj.http.HttpRequest.exec(Http.scala:335)
	at scalaj.http.HttpRequest.asString(Http.scala:455)
```
That assertion is a null check for this field in `sun.util.logging.LoggingSupport`:
```
    private static final LoggingProxy proxy = (LoggingProxy)AccessController.doPrivileged(new PrivilegedAction<LoggingProxy>() {
        public LoggingProxy run() {
            try {
                Class var1 = Class.forName("java.util.logging.LoggingProxyImpl", true, (ClassLoader)null);
                Field var2 = var1.getDeclaredField("INSTANCE");
                var2.setAccessible(true);
                return (LoggingProxy)var2.get((Object)null);
            } catch (ClassNotFoundException var3) {
                return null;
            } catch (NoSuchFieldException var4) {
                throw new AssertionError(var4);
            } catch (IllegalAccessException var5) {
                throw new AssertionError(var5);
            }
        }
    });
```

I assume that `Class.forName` doesn't work and ClassNotFoundException is thrown, which results in `proxy` field being set to null.

**Comment by cstancu** [comment] 2018-04-21 01:48
Thank you for the detailed report. Your diagnosis is correct: the call to `Class.forName()` throws a `ClassNotFoundException`. `Class.forName()` is supported only for classes preregistered during image generation. See [com.oracle.svm.thirdparty.ICU4JFeature.registerShimClass()](https://github.com/oracle/graal/blob/master/substratevm/src/com.oracle.svm.thirdparty/src/com/oracle/svm/thirdparty/ICU4JFeature.java) for an example. A similar approach should be possible for `sun.util.logging.LoggingSupport`.

**Comment by lbialy** [comment] 2018-04-21 05:14
Ahhh, nice! I tried to import that class and/or copy & paste it into my project, but that didn't work due to package visibility.

**Comment by cstancu** [comment] 2018-04-21 20:56
Alternatively you can patch the `scalaj-http` code using the SubstrateVM substitution mechanism:
```
// ScalajHttpSubstitutions.java

import java.net.HttpURLConnection;
import java.util.function.BooleanSupplier;

import org.graalvm.nativeimage.Feature;
import org.graalvm.nativeimage.ImageSingletons;

import com.oracle.svm.core.annotate.AutomaticFeature;
import com.oracle.svm.core.annotate.Substitute;
import com.oracle.svm.core.annotate.TargetClass;

@AutomaticFeature
final class ScalajHttpFeature implements Feature {

    static final class IsEnabled implements BooleanSupplier {
        @Override
        public boolean getAsBoolean() {
            return ImageSingletons.contains(ScalajHttpFeature.class);
        }
    }

    @Override
    public boolean isInConfiguration(IsInConfigurationAccess access) {
        return access.findClassByName("scalaj.http.Http") != null;
    }
}

@TargetClass(className = "scalaj.http.HttpRequest", onlyWith = ScalajHttpFeature.IsEnabled.class)
final class Target_scalaj_http_HttpRequest {
    @Substitute
    private void closeStreams(HttpURLConnection conn) {
        try {
            conn.getInputStream().close();
        } catch (Exception e) {
            // empty catch block
        }
        try {
            conn.getErrorStream().close();
            return;
        } catch (NullPointerException e) {
            return;
        } catch (Exception e) {
            return;
        }
    }
}

public final class ScalajHttpSubstitutions {
}
```
This is essentially injecting a catch for the `NullPointerException` in the original `scalaj.http.HttpRequest.closeStreams()`. To use it you need to first compile it with `javac` and then add it to the `native-image` classpath.
The commands bellow assume that you cloned the latest sources and your working directory is in `graal/substratevm`. (More info about the build process is in the  [README.md](https://github.com/oracle/graal/blob/master/substratevm/README.md)). Your working directory should also contain `ScalajHttpSubstitutions.java`, `HttpGet.scala` and `scalaj-http_2.12-2.3.0.jar`.

```
$ mx build
$ scalac -cp ".:./scalaj-http_2.12-2.3.0.jar:${SCALA_HOME}/lib/scala-xml_2.12-1.0.6.jar" HttpGet.scala
$ javac -cp "./svmbuild/native-image-root/lib/svm/builder/svm.jar:./svmbuild/native-image-root/lib/boot/graal-sdk.jar" ScalajHttpSubstitutions.java
$ ./native-image -cp ".:./scalaj-http_2.12-2.3.0.jar:${SCALA_HOME}/lib/scala-xml_2.12-1.0.6.jar:${SCALA_HOME}/lib/scala-library.jar" -H:EnableURLProtocols=http HttpGet
```
This should generate an `httpget` executable when run should produce something like:
```
$ ./httpget 
HttpResponse({
   "time": "08:44:13 PM",
   "milliseconds_since_epoch": 1524343453235,
   "date": "04-21-2018"
}
,200,Map(Access-Control-Allow-Origin -> Vector(*), Content-Length -> Vector(100), Content-Type -> Vector(application/json; charset=ISO-8859-1), Date -> Vector(Sat, 21 Apr 2018 20:44:13 GMT), Server -> Vector(Google Frontend), Status -> Vector(HTTP/1.1 200 OK), X-Cloud-Trace-Context -> Vector(29a7e399d17fd76a0ce6eacb4b0522cc)))
```

**Comment by lbialy** [comment] 2018-04-23 08:34
Is this the prospective way of dealing with such issues? Shim libraries that need to be on classpath during native image compilation? If so we should probably add support for such concepts to build tools like maven, gradle or sbt.

**Comment by cstancu** [comment] 2018-04-23 17:05
@lbialy in the long run ideally you wouldn't need any substitutions or any special patch to run a library on SubstrateVM. A better approach is to 'fix' the library and make it native-image compatible. This is up to the library maintainer, but since this is a strong restriction on SVM and wouldn't change the functionality of  scalaj-http you can try and submit a PR to scalaj-http.

**Comment by cstancu** [comment] 2018-04-24 00:37
In the feature we will look into relaxing our restrictions around implicit exceptions thrown from within the same method. For now the substitution class is the way to go.

I will close this issue. Let us know if you run into more problems.

**Closed by cstancu** 2018-04-24 00:37 UTC
Labels: substrate

**Comment by RomanIakovlev** [comment] 2018-05-29 06:52
I've come here via internet search for the same stack trace as mentioned by @cstancu in https://github.com/oracle/graal/issues/357#issuecomment-383322363, however I'm not sure if root cause is the same.

The stack trace looks like this:

```
Exception in thread "main" java.lang.reflect.InvocationTargetException
        at java.lang.Throwable.<init>(Throwable.java:310)
        at java.lang.Exception.<init>(Exception.java:102)
        at java.lang.ReflectiveOperationException.<init>(ReflectiveOperationException.java:89)
        at java.lang.reflect.InvocationTargetException.<init>(InvocationTargetException.java:72)
        at com.oracle.svm.reflect.proxies.Proxy_2_Main_main.invoke(Unknown Source)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at com.oracle.svm.core.JavaMainWrapper.run(JavaMainWrapper.java:199)
        at Lcom/oracle/svm/core/code/CEntryPointCallStubs;.com_002eoracle_002esvm_002ecore_002eJavaMainWrapper_002erun_0028int_002corg_002egraalvm_002enativeimage_002ec_002etype_002eCCharPointerPointer_0029(generated:0)
Caused by: java.lang.NullPointerException
        at java.lang.Throwable.<init>(Throwable.java:250)
        at java.lang.Exception.<init>(Exception.java:54)
        at java.lang.RuntimeException.<init>(RuntimeException.java:51)
        at java.lang.NullPointerException.<init>(NullPointerException.java:60)
        at com.oracle.svm.core.snippets.SnippetRuntime.throwNullPointerException(SnippetRuntime.java:206)
        at org.apache.commons.compress.utils.IOUtils.copy(IOUtils.java:77)
        at org.apache.commons.compress.utils.IOUtils.copy(IOUtils.java:60)
        at org.apache.commons.compress.utils.IOUtils.toByteArray(IOUtils.java:221)
```
It comes from Apache Commons compression library, and the code immediately before the exception is the following:

```
public static long copy(final InputStream input, final OutputStream output, final int buffersize) throws IOException {
        final byte[] buffer = new byte[buffersize]; // Exception happens here
        int n = 0;
        long count=0;
        while (-1 != (n = input.read(buffer))) {
            output.write(buffer, 0, n);
            count += n;
        }
        return count;
    }
```
Is this the same issue? If not, should I create a new issue?
