### ISSUE TITLE
cannot handle more than 4038 open sockets [native image]

### ISSUE THREAD

**Issue by pmlopes** [oracle/graal#742] opened 2018-10-17 12:20 UTC
When a native image running either a server or a client tries to handle more the 4038 sockets concurrently (think high load process) the image crashes with a NPE at:

```
WARNING: Failed to register an accepted channel: [id: 0x0c58af4f, L:0.0.0.0/0.0.0.0:8080]
java.lang.NullPointerException
        at sun.nio.ch.EPollArrayWrapper.isEventsHighKilled(EPollArrayWrapper.java:174)
        at sun.nio.ch.EPollArrayWrapper.setUpdateEvents(EPollArrayWrapper.java:190)
        at sun.nio.ch.EPollArrayWrapper.add(EPollArrayWrapper.java:239)
        at sun.nio.ch.EPollSelectorImpl.implRegister(EPollSelectorImpl.java:178)
        at sun.nio.ch.SelectorImpl.register(SelectorImpl.java:132)
        at java.nio.channels.spi.AbstractSelectableChannel.register(AbstractSelectableChannel.java:212)
        at io.netty.channel.nio.AbstractNioChannel.doRegister(AbstractNioChannel.java:386)
        at io.netty.channel.AbstractChannel$AbstractUnsafe.register0(AbstractChannel.java:504)
        at io.netty.channel.AbstractChannel$AbstractUnsafe.access$200(AbstractChannel.java:423)
        at io.netty.channel.AbstractChannel$AbstractUnsafe$1.run(AbstractChannel.java:482)
        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:404)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:464)
        at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:884)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.lang.Thread.run(Thread.java:748)
        at com.oracle.svm.core.thread.JavaThreads.threadStartRoutine(JavaThreads.java:475)
        at com.oracle.svm.core.posix.thread.PosixJavaThreads.pthreadStartRoutine(PosixJavaThreads.java:199)
```

Looking at the stacktrace we can identify the as:

```java
...
synchronized(this.updateLock) {
...
```

Where `updateLock` is a `private final Object = new Object()` which should never mutate during the object lifecycle or be null at any method call.

**Comment by FroMage** [comment] 2018-10-18 08:16
Just got the same issue with another NIO lib:

```
XNIO001007: A channel event listener threw an exception: java.lang.NullPointerException
	at sun.nio.ch.EPollArrayWrapper.isEventsHighKilled(EPollArrayWrapper.java:174)
	at sun.nio.ch.EPollArrayWrapper.setUpdateEvents(EPollArrayWrapper.java:190)
	at sun.nio.ch.EPollArrayWrapper.add(EPollArrayWrapper.java:239)
	at sun.nio.ch.EPollSelectorImpl.implRegister(EPollSelectorImpl.java:178)
	at sun.nio.ch.SelectorImpl.register(SelectorImpl.java:132)
	at java.nio.channels.spi.AbstractSelectableChannel.register(AbstractSelectableChannel.java:212)
	at java.nio.channels.SelectableChannel.register(SelectableChannel.java:280)
	at org.xnio.nio.WorkerThread.registerChannel(WorkerThread.java:685)
	at org.xnio.nio.QueuedNioTcpServer.accept(QueuedNioTcpServer.java:378)
	at org.xnio.nio.QueuedNioTcpServer.accept(QueuedNioTcpServer.java:58)
	at org.xnio.ChannelListeners$10.handleEvent(ChannelListeners.java:289)
	at org.xnio.ChannelListeners$10.handleEvent(ChannelListeners.java:286)
	at org.xnio.ChannelListeners.invokeChannelListener(ChannelListeners.java:92)
	at org.xnio.nio.QueuedNioTcpServer$1.run(QueuedNioTcpServer.java:129)
	at org.xnio.nio.WorkerThread.safeRun(WorkerThread.java:582)
	at org.xnio.nio.WorkerThread.run(WorkerThread.java:466)
	at com.oracle.svm.core.thread.JavaThreads.threadStartRoutine(JavaThreads.java:475)
	at com.oracle.svm.core.posix.thread.PosixJavaThreads.pthreadStartRoutine(PosixJavaThreads.java:199)
```

**Comment by dmlloyd** [comment] 2018-10-18 16:36
Might some of the more recent NIO JDK rewrites have been backported to Java 8?  And if so... might the native substitutions be out of date?

**Comment by Peter-B-Kessler** [comment] 2018-10-19 22:21
The Linux boxes I have access to will not let me `sudo`, so the first steps of `reproducer/run` are a showstopper for me.

**Comment by Peter-B-Kessler** [comment] 2018-10-19 23:56
I see http://hg.openjdk.java.net/jdk8u/jdk8u/jdk/file/b5c6ff776bee/src/solaris/classes/sun/nio/ch/EPollArrayWrapper.java#l174 as
```
168    /**
169     * Returns {@code true} if updates for the given key (file
170     * descriptor) are killed.
171     */
172    private boolean isEventsHighKilled(Integer key) {
173        assert key >= MAX_UPDATE_ARRAY_SIZE;
174        Byte value = eventsHigh.get(key);
175        return (value != null && value == KILLED);
176    }
```
so what might be null at 174 is `eventsHigh`, rather than `this.updateLock` you cite above.  `eventsHigh` *will be* null if, in the constructor it is not assigned at line 139 by
```
073     private static final int OPEN_MAX         = IOUtil.fdLimit();
...
082     // maximum size of updatesLow
083     private static final int MAX_UPDATE_ARRAY_SIZE = AccessController.doPrivileged(
084         new GetIntegerAction("sun.nio.ch.maxUpdateArraySize", Math.min(OPEN_MAX, 64*1024)));
...
137         // eventHigh needed when using file descriptors > 64k
138         if (OPEN_MAX > MAX_UPDATE_ARRAY_SIZE)
139             eventsHigh = new HashMap<>();
```
Among the problems is that, while you are building your image, we have baked into the image the values of `OPEN_MAX` and `MAX_UPDATE_ARRAY_SIZE` because they are part of the [static initialization](https://github.com/oracle/graal/blob/master/substratevm/LIMITATIONS.md#static-initializers) of the class.  On an unscientific sample of Linux boxes, I see `ulimit -n` as 65536, so `eventsHigh` might be left as null when the constructor runs at runtime.

It looks like you could build an image with `-Dsun.nio.ch.maxUpdateArraySize=` set to some large value to get more of your events in the `eventsLow` array, or set to some small value to force the use of the `eventsHigh` map.  But I have not tried either of those.  On the third hand, you could tweak the `ulimit -n` value from your `./run` script *before* building the image and see if that bakes values into the image such things run as you expect.  I am not knowledgable enough in this part of the platform to be able to advise you on which approach would be best.  The HotSpot Java Virtual Machine will evaluate the system properties and initialize the static fields at runtime, if that is any guide.

Or it could be some other problem.  I am interested to know if you agree with my hypothesis.

I do not understand why 4038 sockets is the breaking point, but there are a lot of things I do not understand.

**Comment by Peter-B-Kessler** [comment] 2018-10-31 18:16
I have pushed https://github.com/oracle/graal/commit/ee41fb463925b36d03d59bb3f42f9e2311570e1c to re-initialize the static fields of `EPollArrayWrapper` at runtime.  I am curious to know if that addresses your issue.

**Comment by Peter-B-Kessler** [comment] 2018-11-27 18:58
If my push addresses your problem, would you please close this issue?  Thanks.

**Comment by pmlopes** [comment] 2018-11-28 18:49
Sorry, I haven't tested it yet, maybe @FroMage did?

**Closed** 2019-05-08 23:45 UTC
Labels: substrate
