### ISSUE TITLE
CreateProcess failed: The system cannot find the file specified

### ISSUE THREAD

**Issue by panwarab** [oracle/graal#1430] opened 2019-06-25 16:03 UTC
Getting this issue while creating running the command `mx build`
```
[1/9] CC src\closures.obj
FAILED: src/closures.obj
cl -nologo -showIncludes -IC:\Code\opensource\graal\truffle\mxbuild\windows-amd64\src\libffi\libffi-3.2.1\include -IC:\Code\opensource\graal\truffle\mxbuild\windows-amd64\src\libffi\libffi-3.2.1\src -MD -O2 -c C:\Code\opensource\graal\truffle\mxbuild\windows-amd64\src\libffi\libffi-3.2.1\src\closures.c -Fosrc\closures.obj
CreateProcess failed: The system cannot find the file specified.
[2/9] CC src\java_raw_api.obj
FAILED: src/java_raw_api.obj
cl -nologo -showIncludes -IC:\Code\opensource\graal\truffle\mxbuild\windows-amd64\src\libffi\libffi-3.2.1\include -IC:\Code\opensource\graal\truffle\mxbuild\windows-amd64\src\libffi\libffi-3.2.1\src -MD -O2 -c C:\Code\opensource\graal\truffle\mxbuild\windows-amd64\src\libffi\libffi-3.2.1\src\java_raw_api.c -Fosrc\java_raw_api.obj
CreateProcess failed: The system cannot find the file specified.
[3/9] CC src\prep_cif.obj
FAILED: src/prep_cif.obj
cl -nologo -showIncludes -IC:\Code\opensource\graal\truffle\mxbuild\windows-amd64\src\libffi\libffi-3.2.1\include -IC:\Code\opensource\graal\truffle\mxbuild\windows-amd64\src\libffi\libffi-3.2.1\src -MD -O2 -c C:\Code\opensource\graal\truffle\mxbuild\windows-amd64\src\libffi\libffi-3.2.1\src\prep_cif.c -Fosrc\prep_cif.obj
CreateProcess failed: The system cannot find the file specified.
[4/9] CPP src\x86\win64.asm
FAILED: src/x86/win64.asm
cl -nologo -showIncludes -EP -P -IC:\Code\opensource\graal\truffle\mxbuild\windows-amd64\src\libffi\libffi-3.2.1\include -IC:\Code\opensource\graal\truffle\mxbuild\windows-amd64\src\libffi\libffi-3.2.1\src -MD -O2 -c C:\Code\opensource\graal\truffle\mxbuild\windows-amd64\src\libffi\libffi-3.2.1\src\x86\win64.S -Fisrc\x86\win64.asm
CreateProcess failed: The system cannot find the file specified.
ninja: build stopped: subcommand failed.
```

**Comment by abhiroj** [comment] 2019-06-27 12:17
@chumer @mekul

**Comment by chumer** [comment] 2019-06-27 14:30
@rschatz we already support Windows?

**Comment by abhiroj** [comment] 2019-06-28 16:48
@rschatz could you please have a look into it?

**Comment by pquiring** [comment] 2019-07-29 14:19
You need cl.exe in your path (Microsoft VC++ compiler)

**Comment by fernando-valdez** [comment] 2024-01-25 01:14
Closing this issue as the problem is no longer applicable.

**Closed by fernando-valdez** 2024-01-25 01:14 UTC
