### ISSUE TITLE
Failed to cancel current process

### ISSUE THREAD

**Issue by bmsantos** [oracle/graal#267] opened 2017-12-07 02:37 UTC
Let me start by stating that this project 🎸 !

The issue: Can't cancel current process when ruby interop is called.

```javascript
const express = require('express');
const app = express();

const BigInteger = Java.type('java.math.BigInteger');

app.get('/', (req, res) => {
  let text = `How to fix JS numbers... ${BigInteger.valueOf(2).pow(100).toString(16)} ... use Java!`;
  text += Interop.eval('application/x-r', 'paste("Hello from R", runif(100))');
  text += Interop.eval('application/x-python', '" - And from Python: " + "Hello " * 3');
  text += Interop.eval('application/x-ruby', '" - And from Ruby: " + Math.sqrt(9).to_s');
  return res.send(`Result: ${text}`);
});

app.listen(3000, () => console.log('Example app listening on port 3000!'));
```

Execution goes fine but when one tries to cancel the process using Ctrl-C the following error is displayed. 

```bash
○ → node --jvm --polyglot server.js
Example app listening on port 3000!
^CException in thread "Polyglot-ruby-0" com.oracle.truffle.api.vm.PolyglotIllegalStateException: Multi threaded access requested by thread Thread[Polyglot-ruby-0,9,system] but is not allowed for language(s) regex, js.
	at com.oracle.truffle.api.vm.PolyglotContextImpl.throwDeniedThreadAccess(PolyglotContextImpl.java:453)
	at com.oracle.truffle.api.vm.PolyglotContextImpl.checkAllThreadAccesses(PolyglotContextImpl.java:357)
	at com.oracle.truffle.api.vm.PolyglotContextImpl.enterThreadChanged(PolyglotContextImpl.java:290)
	at com.oracle.truffle.api.vm.PolyglotContextImpl.enter(PolyglotContextImpl.java:261)
	at com.oracle.truffle.api.vm.PolyglotLanguageContext.enter(PolyglotLanguageContext.java:125)
	at com.oracle.truffle.api.vm.PolyglotLanguageContext.enterThread(PolyglotLanguageContext.java:178)
	at com.oracle.truffle.api.vm.PolyglotThread.run(PolyglotThread.java:50)
```

This only happens when the Ruby interop is used.

Platform:
OS name: "mac os x", version: "10.13.1", arch: "x86_64", family: "mac"

Java/GraalVM:
java version "1.8.0_151"
Java(TM) SE Runtime Environment (build 1.8.0_151-b12)
Java HotSpot(TM) 64-Bit Server VM (build 25.71-b01-internal-jvmci-0.38, mixed mode)

**Comment by chrisseaton** [comment] 2018-01-09 11:42
This problem is explained here

https://github.com/graalvm/truffleruby/blob/b91179d8917d09dcdfb3fe08c5b61363fecd527c/doc/user/interop.md#threading-and-interop

The issue is that Ruby is multi-threaded, and JavaScript isn't compatible with that. We're looking at some options for how to make this work, such as a GIL when calling from Ruby to JavaScript.

In the mean time you can use the JVM option `-Dtruffleruby.single_threaded=true`, which I think you set with `--jvm.Dtruffleruby.single_threaded=true` for the `node` binary. This turns Ruby into a single-threaded mode which is compatible with JavaScript.

However I'm afraid that option isn't in 0.30.2, the latest GraalVM release, at the moment.

**Comment by thomaswue** [comment] 2018-03-11 16:51
@chrisseaton Is this problem fixed in latest release?

**Comment by chrisseaton** [comment] 2018-03-12 00:55
The problem has gone away entirely in 0.32. Ruby will automatically be single-threaded when you use it from JavaScript.

**Closed** 2018-03-12 12:17 UTC
Labels: bug, ruby
