### ISSUE TITLE
[Truffle] fails to build 

### ISSUE THREAD

**Issue by zakkak** [oracle/graal#271] opened 2017-12-19 11:36 UTC
Truffle version: JDK-8193439-48-g45e6fef966
GraalVM: 0.30.1 JDK 8
OS: Ubuntu 17.10
[truffle-build.log](https://github.com/graalvm/graal/files/1571485/truffle-build.log)

**Comment by PRIESt512** [comment] 2018-01-02 13:06
Ooo, I have a similar error, like you:
`Exception in thread "main" java.util.ServiceConfigurationError: com.oracle.truffle.api.TruffleRuntimeAccess: Provider org.graalvm.compiler.truffle.hotspot.HotSpotTruffleRuntimeAccess not a subtype`
The code that throws an exception:
`PolyglotEngine engine = PolyglotEngine.newBuilder().build();`
I wanted to run an example - [Truffle Tutorial: Embedding Truffle Languages in Java](http://graalvm.github.io/graal/truffle/javadoc/com/oracle/truffle/tutorial/embedding/package-summary.html)

**Comment by dougxc** [comment] 2018-01-09 10:58
Duplicate of #275.

**Closed** 2018-01-09 10:58 UTC
