### ISSUE TITLE
[native-image] Building fails in WSL

### ISSUE THREAD

**Issue by neon-dev** [oracle/graal#1241] opened 2019-05-06 15:36 UTC
Since there's not yet real Windows support, let alone for Windows 10, I tried to build a native-image in WSL (Debian) via Maven.
I'm using native-image-maven-plugin version 1.0.0-rc16, so the most recent one. The project is a simple Hello World without any external libs.

This is the error I get: `host C compiler or linker does not seem to work: java.lang.RuntimeException: returned 1`

And here the relevant console output with stack traces:
```
[INFO] --- native-image-maven-plugin:1.0.0-rc16:native-image (default) @ native-image-test ---
[INFO] ImageClasspath Entry: de.tle:native-image-test:jar:1.0-SNAPSHOT (file:///mnt/c/Users/-/IdeaProjects/test/Native%20Image%20Test/target/native-image-test-1.0-SNAPSHOT.jar)
[INFO] WorkingDirectory: /mnt/c/Users/-/IdeaProjects/test/Native Image Test/target
[INFO] ImageClasspath: /mnt/c/Users/-/IdeaProjects/test/Native Image Test/target/native-image-test-1.0-SNAPSHOT.jar
[INFO] BuildArgs: [-H:+ReportExceptionStackTraces, -H:Class=Main]
[main:21523]    classlist:   1,153.11 ms
[main:21523]        (cap):   1,578.42 ms
[main:21523]        setup:   2,409.04 ms
[main:21523]   (typeflow):   1,839.24 ms
[main:21523]    (objects):     452.54 ms
[main:21523]   (features):      88.52 ms
[main:21523]     analysis:   2,422.93 ms
[main:21523]     universe:     129.51 ms
[main:21523]      (parse):     217.05 ms
[main:21523]     (inline):     891.70 ms
[main:21523]    (compile):   1,865.34 ms
[main:21523]      compile:   3,128.52 ms
[main:21523]        image:     216.27 ms
[main:21523]        write:     104.02 ms
Fatal error: java.lang.RuntimeException: java.lang.RuntimeException: host C compiler or linker does not seem to work: java.lang.RuntimeException: returned 1

Running command: cc -v -o /mnt/c/Users/-/IdeaProjects/test/Native Image Test/target/main -z noexecstack -Wl,--defsym -Wl,main=IsolateEnterStub__JavaMainWrapper__run__5087f5482cc9a6abc971913ece43acb471d2631b__a61fe6c26e84dd4037e4629852b5488bfcc16e7e -L/tmp/SVM-3384069634760586164 -L/mnt/c/Users/-/bin/java/openjdk1.8.0_202-jvmci-0.59-linux/jre/lib -L/mnt/c/Users/-/IdeaProjects/test/Native Image Test/target/native-image-maven-plugin/1.0.0-rc16/linux-amd64 /tmp/SVM-3384069634760586164/main.o -lffi -lpthread -ldl -lpthread -lz -lpthread -ldl -lstrictmath -llibchelper -lrt -lrt -lrt -lrt -lrt -lcrypt

Using built-in specs.
COLLECT_GCC=cc
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-linux-gnu/6/lto-wrapper
Target: x86_64-linux-gnu
Configured with: ../src/configure -v --with-pkgversion='Debian 6.3.0-18+deb9u1' --with-bugurl=file:///usr/share/doc/gcc-6/README.Bugs --enable-languages=c,ada,c++,java,go,d,fortran,objc,obj-c++ --prefix=/usr --program-suffix=-6 --program-prefix=x86_64-linux-gnu- --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --libdir=/usr/lib --enable-nls --with-sysroot=/ --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --with-default-libstdcxx-abi=new --enable-gnu-unique-object --disable-vtable-verify --enable-libmpx --enable-plugin --enable-default-pie --with-system-zlib --disable-browser-plugin --enable-java-awt=gtk --enable-gtk-cairo --with-java-home=/usr/lib/jvm/java-1.5.0-gcj-6-amd64/jre --enable-java-home --with-jvm-root-dir=/usr/lib/jvm/java-1.5.0-gcj-6-amd64 --with-jvm-jar-dir=/usr/lib/jvm-exports/java-1.5.0-gcj-6-amd64 --with-arch-directory=amd64 --with-ecj-jar=/usr/share/java/eclipse-ecj.jar --with-target-system-zlib --enable-objc-gc=auto --enable-multiarch --with-arch-32=i686 --with-abi=m64 --with-multilib-list=m32,m64,mx32 --enable-multilib --with-tune=generic --enable-checking=release --build=x86_64-linux-gnu --host=x86_64-linux-gnu --target=x86_64-linux-gnu
Thread model: posix
gcc version 6.3.0 20170516 (Debian 6.3.0-18+deb9u1)
COMPILER_PATH=/usr/lib/gcc/x86_64-linux-gnu/6/:/usr/lib/gcc/x86_64-linux-gnu/6/:/usr/lib/gcc/x86_64-linux-gnu/:/usr/lib/gcc/x86_64-linux-gnu/6/:/usr/lib/gcc/x86_64-linux-gnu/
LIBRARY_PATH=/usr/lib/gcc/x86_64-linux-gnu/6/:/usr/lib/gcc/x86_64-linux-gnu/6/../../../x86_64-linux-gnu/:/usr/lib/gcc/x86_64-linux-gnu/6/../../../../lib/:/lib/x86_64-linux-gnu/:/lib/../lib/:/usr/lib/x86_64-linux-gnu/:/usr/lib/../lib/:/usr/lib/gcc/x86_64-linux-gnu/6/../../../:/lib/:/usr/lib/
COLLECT_GCC_OPTIONS='-v' '-o' '/mnt/c/Users/-/IdeaProjects/test/Native Image Test/target/main' '-z' 'noexecstack' '-L/tmp/SVM-3384069634760586164' '-L/mnt/c/Users/-/bin/java/openjdk1.8.0_202-jvmci-0.59-linux/jre/lib' '-L/mnt/c/Users/-/IdeaProjects/test/Native Image Test/target/native-image-maven-plugin/1.0.0-rc16/linux-amd64' '-mtune=generic' '-march=x86-64'
 /usr/lib/gcc/x86_64-linux-gnu/6/collect2 -plugin /usr/lib/gcc/x86_64-linux-gnu/6/liblto_plugin.so -plugin-opt=/usr/lib/gcc/x86_64-linux-gnu/6/lto-wrapper -plugin-opt=-fresolution=/tmp/ccsF6Jz1.res -plugin-opt=-pass-through=-lgcc -plugin-opt=-pass-through=-lgcc_s -plugin-opt=-pass-through=-lc -plugin-opt=-pass-through=-lgcc -plugin-opt=-pass-through=-lgcc_s --sysroot=/ --build-id --eh-frame-hdr -m elf_x86_64 --hash-style=gnu -dynamic-linker /lib64/ld-linux-x86-64.so.2 -pie -o /mnt/c/Users/-/IdeaProjects/test/Native Image Test/target/main -z noexecstack /usr/lib/gcc/x86_64-linux-gnu/6/../../../x86_64-linux-gnu/Scrt1.o /usr/lib/gcc/x86_64-linux-gnu/6/../../../x86_64-linux-gnu/crti.o /usr/lib/gcc/x86_64-linux-gnu/6/crtbeginS.o -L/tmp/SVM-3384069634760586164 -L/mnt/c/Users/-/bin/java/openjdk1.8.0_202-jvmci-0.59-linux/jre/lib -L/mnt/c/Users/-/IdeaProjects/test/Native Image Test/target/native-image-maven-plugin/1.0.0-rc16/linux-amd64 -L/usr/lib/gcc/x86_64-linux-gnu/6 -L/usr/lib/gcc/x86_64-linux-gnu/6/../../../x86_64-linux-gnu -L/usr/lib/gcc/x86_64-linux-gnu/6/../../../../lib -L/lib/x86_64-linux-gnu -L/lib/../lib -L/usr/lib/x86_64-linux-gnu -L/usr/lib/../lib -L/usr/lib/gcc/x86_64-linux-gnu/6/../../.. --defsym main=IsolateEnterStub__JavaMainWrapper__run__5087f5482cc9a6abc971913ece43acb471d2631b__a61fe6c26e84dd4037e4629852b5488bfcc16e7e /tmp/SVM-3384069634760586164/main.o -lffi -lpthread -ldl -lpthread -lz -lpthread -ldl -lstrictmath -llibchelper -lrt -lrt -lrt -lrt -lrt -lcrypt -lgcc --as-needed -lgcc_s --no-as-needed -lc -lgcc --as-needed -lgcc_s --no-as-needed /usr/lib/gcc/x86_64-linux-gnu/6/crtendS.o /usr/lib/gcc/x86_64-linux-gnu/6/../../../x86_64-linux-gnu/crtn.o
/usr/bin/ld: /mnt/c/Users/-/IdeaProjects/test/Native Image Test/target/native-image-maven-plugin/1.0.0-rc16/linux-amd64/libffi.a(prep_cif.o): unable to initialize decompress status for section .debug_info
/usr/bin/ld: /mnt/c/Users/-/IdeaProjects/test/Native Image Test/target/native-image-maven-plugin/1.0.0-rc16/linux-amd64/libffi.a(prep_cif.o): unable to initialize decompress status for section .debug_info
/usr/bin/ld: /mnt/c/Users/-/IdeaProjects/test/Native Image Test/target/native-image-maven-plugin/1.0.0-rc16/linux-amd64/liblibchelper.a(getEnviron.o): unable to initialize decompress status for section .debug_info
/usr/bin/ld: /mnt/c/Users/-/IdeaProjects/test/Native Image Test/target/native-image-maven-plugin/1.0.0-rc16/linux-amd64/liblibchelper.a(getEnviron.o): unable to initialize decompress status for section .debug_info
/usr/bin/ld: /mnt/c/Users/-/IdeaProjects/test/Native Image Test/target/native-image-maven-plugin/1.0.0-rc16/linux-amd64/liblibchelper.a(cpuid.o): unable to initialize decompress status for section .debug_info
/usr/bin/ld: /mnt/c/Users/-/IdeaProjects/test/Native Image Test/target/native-image-maven-plugin/1.0.0-rc16/linux-amd64/liblibchelper.a(cpuid.o): unable to initialize decompress status for section .debug_info
/mnt/c/Users/-/IdeaProjects/test/Native Image Test/target/native-image-maven-plugin/1.0.0-rc16/linux-amd64/liblibchelper.a: error adding symbols: File format not recognized
collect2: error: ld returned 1 exit status

        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
        at java.util.concurrent.ForkJoinTask.getThrowableException(ForkJoinTask.java:593)
        at java.util.concurrent.ForkJoinTask.get(ForkJoinTask.java:1005)
        at com.oracle.svm.hosted.NativeImageGenerator.run(NativeImageGenerator.java:459)
        at com.oracle.svm.hosted.NativeImageGeneratorRunner.buildImage(NativeImageGeneratorRunner.java:289)
        at com.oracle.svm.hosted.NativeImageGeneratorRunner.build(NativeImageGeneratorRunner.java:427)
        at com.oracle.svm.hosted.NativeImageGeneratorRunner.main(NativeImageGeneratorRunner.java:109)
Caused by: java.lang.RuntimeException: host C compiler or linker does not seem to work: java.lang.RuntimeException: returned 1

Running command: cc -v -o /mnt/c/Users/-/IdeaProjects/test/Native Image Test/target/main -z noexecstack -Wl,--defsym -Wl,main=IsolateEnterStub__JavaMainWrapper__run__5087f5482cc9a6abc971913ece43acb471d2631b__a61fe6c26e84dd4037e4629852b5488bfcc16e7e -L/tmp/SVM-3384069634760586164 -L/mnt/c/Users/-/bin/java/openjdk1.8.0_202-jvmci-0.59-linux/jre/lib -L/mnt/c/Users/-/IdeaProjects/test/Native Image Test/target/native-image-maven-plugin/1.0.0-rc16/linux-amd64 /tmp/SVM-3384069634760586164/main.o -lffi -lpthread -ldl -lpthread -lz -lpthread -ldl -lstrictmath -llibchelper -lrt -lrt -lrt -lrt -lrt -lcrypt

Using built-in specs.
COLLECT_GCC=cc
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-linux-gnu/6/lto-wrapper
Target: x86_64-linux-gnu
Configured with: ../src/configure -v --with-pkgversion='Debian 6.3.0-18+deb9u1' --with-bugurl=file:///usr/share/doc/gcc-6/README.Bugs --enable-languages=c,ada,c++,java,go,d,fortran,objc,obj-c++ --prefix=/usr --program-suffix=-6 --program-prefix=x86_64-linux-gnu- --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --libdir=/usr/lib --enable-nls --with-sysroot=/ --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --with-default-libstdcxx-abi=new --enable-gnu-unique-object --disable-vtable-verify --enable-libmpx --enable-plugin --enable-default-pie --with-system-zlib --disable-browser-plugin --enable-java-awt=gtk --enable-gtk-cairo --with-java-home=/usr/lib/jvm/java-1.5.0-gcj-6-amd64/jre --enable-java-home --with-jvm-root-dir=/usr/lib/jvm/java-1.5.0-gcj-6-amd64 --with-jvm-jar-dir=/usr/lib/jvm-exports/java-1.5.0-gcj-6-amd64 --with-arch-directory=amd64 --with-ecj-jar=/usr/share/java/eclipse-ecj.jar --with-target-system-zlib --enable-objc-gc=auto --enable-multiarch --with-arch-32=i686 --with-abi=m64 --with-multilib-list=m32,m64,mx32 --enable-multilib --with-tune=generic --enable-checking=release --build=x86_64-linux-gnu --host=x86_64-linux-gnu --target=x86_64-linux-gnu
Thread model: posix
gcc version 6.3.0 20170516 (Debian 6.3.0-18+deb9u1)
COMPILER_PATH=/usr/lib/gcc/x86_64-linux-gnu/6/:/usr/lib/gcc/x86_64-linux-gnu/6/:/usr/lib/gcc/x86_64-linux-gnu/:/usr/lib/gcc/x86_64-linux-gnu/6/:/usr/lib/gcc/x86_64-linux-gnu/
LIBRARY_PATH=/usr/lib/gcc/x86_64-linux-gnu/6/:/usr/lib/gcc/x86_64-linux-gnu/6/../../../x86_64-linux-gnu/:/usr/lib/gcc/x86_64-linux-gnu/6/../../../../lib/:/lib/x86_64-linux-gnu/:/lib/../lib/:/usr/lib/x86_64-linux-gnu/:/usr/lib/../lib/:/usr/lib/gcc/x86_64-linux-gnu/6/../../../:/lib/:/usr/lib/
COLLECT_GCC_OPTIONS='-v' '-o' '/mnt/c/Users/-/IdeaProjects/test/Native Image Test/target/main' '-z' 'noexecstack' '-L/tmp/SVM-3384069634760586164' '-L/mnt/c/Users/-/bin/java/openjdk1.8.0_202-jvmci-0.59-linux/jre/lib' '-L/mnt/c/Users/-/IdeaProjects/test/Native Image Test/target/native-image-maven-plugin/1.0.0-rc16/linux-amd64' '-mtune=generic' '-march=x86-64'
 /usr/lib/gcc/x86_64-linux-gnu/6/collect2 -plugin /usr/lib/gcc/x86_64-linux-gnu/6/liblto_plugin.so -plugin-opt=/usr/lib/gcc/x86_64-linux-gnu/6/lto-wrapper -plugin-opt=-fresolution=/tmp/ccsF6Jz1.res -plugin-opt=-pass-through=-lgcc -plugin-opt=-pass-through=-lgcc_s -plugin-opt=-pass-through=-lc -plugin-opt=-pass-through=-lgcc -plugin-opt=-pass-through=-lgcc_s --sysroot=/ --build-id --eh-frame-hdr -m elf_x86_64 --hash-style=gnu -dynamic-linker /lib64/ld-linux-x86-64.so.2 -pie -o /mnt/c/Users/-/IdeaProjects/test/Native Image Test/target/main -z noexecstack /usr/lib/gcc/x86_64-linux-gnu/6/../../../x86_64-linux-gnu/Scrt1.o /usr/lib/gcc/x86_64-linux-gnu/6/../../../x86_64-linux-gnu/crti.o /usr/lib/gcc/x86_64-linux-gnu/6/crtbeginS.o -L/tmp/SVM-3384069634760586164 -L/mnt/c/Users/-/bin/java/openjdk1.8.0_202-jvmci-0.59-linux/jre/lib -L/mnt/c/Users/-/IdeaProjects/test/Native Image Test/target/native-image-maven-plugin/1.0.0-rc16/linux-amd64 -L/usr/lib/gcc/x86_64-linux-gnu/6 -L/usr/lib/gcc/x86_64-linux-gnu/6/../../../x86_64-linux-gnu -L/usr/lib/gcc/x86_64-linux-gnu/6/../../../../lib -L/lib/x86_64-linux-gnu -L/lib/../lib -L/usr/lib/x86_64-linux-gnu -L/usr/lib/../lib -L/usr/lib/gcc/x86_64-linux-gnu/6/../../.. --defsym main=IsolateEnterStub__JavaMainWrapper__run__5087f5482cc9a6abc971913ece43acb471d2631b__a61fe6c26e84dd4037e4629852b5488bfcc16e7e /tmp/SVM-3384069634760586164/main.o -lffi -lpthread -ldl -lpthread -lz -lpthread -ldl -lstrictmath -llibchelper -lrt -lrt -lrt -lrt -lrt -lcrypt -lgcc --as-needed -lgcc_s --no-as-needed -lc -lgcc --as-needed -lgcc_s --no-as-needed /usr/lib/gcc/x86_64-linux-gnu/6/crtendS.o /usr/lib/gcc/x86_64-linux-gnu/6/../../../x86_64-linux-gnu/crtn.o
/usr/bin/ld: /mnt/c/Users/-/IdeaProjects/test/Native Image Test/target/native-image-maven-plugin/1.0.0-rc16/linux-amd64/libffi.a(prep_cif.o): unable to initialize decompress status for section .debug_info
/usr/bin/ld: /mnt/c/Users/-/IdeaProjects/test/Native Image Test/target/native-image-maven-plugin/1.0.0-rc16/linux-amd64/libffi.a(prep_cif.o): unable to initialize decompress status for section .debug_info
/usr/bin/ld: /mnt/c/Users/-/IdeaProjects/test/Native Image Test/target/native-image-maven-plugin/1.0.0-rc16/linux-amd64/liblibchelper.a(getEnviron.o): unable to initialize decompress status for section .debug_info
/usr/bin/ld: /mnt/c/Users/-/IdeaProjects/test/Native Image Test/target/native-image-maven-plugin/1.0.0-rc16/linux-amd64/liblibchelper.a(getEnviron.o): unable to initialize decompress status for section .debug_info
/usr/bin/ld: /mnt/c/Users/-/IdeaProjects/test/Native Image Test/target/native-image-maven-plugin/1.0.0-rc16/linux-amd64/liblibchelper.a(cpuid.o): unable to initialize decompress status for section .debug_info
/usr/bin/ld: /mnt/c/Users/-/IdeaProjects/test/Native Image Test/target/native-image-maven-plugin/1.0.0-rc16/linux-amd64/liblibchelper.a(cpuid.o): unable to initialize decompress status for section .debug_info
/mnt/c/Users/-/IdeaProjects/test/Native Image Test/target/native-image-maven-plugin/1.0.0-rc16/linux-amd64/liblibchelper.a: error adding symbols: File format not recognized
collect2: error: ld returned 1 exit status

        at com.oracle.svm.hosted.image.NativeBootImageViaCC.write(NativeBootImageViaCC.java:308)
        at com.oracle.svm.hosted.NativeImageGenerator.doRun(NativeImageGenerator.java:655)
        at com.oracle.svm.hosted.NativeImageGenerator.lambda$run$0(NativeImageGenerator.java:442)
        at java.util.concurrent.ForkJoinTask$AdaptedRunnableAction.exec(ForkJoinTask.java:1386)
        at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
        at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
        at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
        at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 11.775 s
[INFO] Finished at: 2019-05-06T14:49:53+00:00
[INFO] Final Memory: 24M/798M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal com.oracle.substratevm:native-image-maven-plugin:1.0.0-rc16:native-image (default) on project native-image-test: Error creating native image: Image build request failed with exit status 1 -> [Help 1]
```

I hope it's not my fault, because the system is missing some dependencies or something similar.
I tried RC15 as well, without any difference. RC14 and below throw another error: `HotSpotJVMCIUnsupportedOperationError: jdk.vm.ci.hotspot.HotSpotJVMCICompilerFactory.getCompilationLevelAdjustment() is no longer supported. Use jdk.vm.ci.hotspot.HotSpotJVMCICompilerFactory.excludeFromJVMCICompilation() instead.`

**Comment by olpaw** [comment] 2019-05-06 16:04
@neon-dev looks like you do not have GCC and binutils installed in your WSL Linux.
Try: sudo apt install gcc” and “sudo apt install g++”.

**Comment by neon-dev** [comment] 2019-05-06 17:21
@olpaw thanks for the fast response.
GCC is installed, but not g++ and binutils. I was basically trial&error-ing because there's no guide that shows a definitive list of dependencies. https://www.graalvm.org/docs/reference-manual/aot-compilation/ just doesn't list what you stated here.
I'll try and update you tomorrow, since I won't have access to my Win 10 machine for the rest of the day.

**Comment by olpaw** [comment] 2019-05-06 17:31
You will also need zlib headers. For more info see https://github.com/oracle/graal/blob/master/substratevm/README.md#quick-start

**Comment by neon-dev** [comment] 2019-05-06 17:32
Got that also

**Comment by neon-dev** [comment] 2019-05-07 07:22
Ok my bad, binutils is also already present (via [`build-essential`](https://packages.debian.org/sid/build-essential) -> [`dpkg-dev`](https://packages.debian.org/sid/dpkg-dev)). So I should have everything needed.

**Comment by olpaw** [comment] 2019-05-07 09:03
I tested building a HelloWorld image on WSL on my Win10 VBox it it worked as expected.
@neon-dev are you still having trouble with building / image building on WSL?

**Comment by neon-dev** [comment] 2019-05-07 10:18
Unfortunately yes, still the same problem. What other info can I provide to find the problem? As I wrote in the issue I'm building with the Maven plugin via the JVMCI enabled JDK8, so I don't have the GraalVM installed. Maybe the issue only affects this constellation.

**Comment by neon-dev** [comment] 2019-05-07 10:27
Here's a reproducer: [Native Image Test.zip](https://github.com/oracle/graal/files/3152112/Native.Image.Test.zip)

**Comment by olpaw** [comment] 2019-05-08 17:36
The reason you see this is that
https://search.maven.org/artifact/com.oracle.substratevm/native-image-maven-plugin/1.0.0-rc16/maven-plugin
depends on
https://search.maven.org/artifact/com.oracle.substratevm/svm-hosted-native-linux-amd64/1.0.0-rc16/tar.gz
which is built on a Linux machine with a recent version of binutils that makes use of compressed data alignment in the debuginfo sections. The version of binutils provided by WSL (Ubuntu Xenial) is outdated (2.26) and cannot handle *.a files created with newer binutils. So this bug is basically a duplicate of https://github.com/oracle/graal/issues/921#issuecomment-456011677

You have 2 options:
* Use a different WSL Linux distribution that has a newer binutils package.
* Build yourself a newer binutils in your existing WSL and put it on `PATH`

**Comment by neon-dev** [comment] 2019-05-08 18:09
My WSL is the Debian version and my error message is not the same as in the linked issue, but the versions found in https://packages.debian.org/search?keywords=binutils&searchon=names&suite=stable&section=all are all below 2.32, so I assume it actually is the same issue then. I will check tomorrow and post here in case it's not.

Thank you for your time.
I suggest adding all the missing information in the [manual](https://www.graalvm.org/docs/reference-manual/aot-compilation/#prerequisites) to avoid this in the future :)
To be exact:

- Mention the the binutils dependency
- Add a hint like "Make sure that binutils version is >=2.32 by typing `ld -v`"
- Maybe also add a snippet like
  ```
  sudo apt-get update
  sudo apt-get install build-essential zlib1g-dev
  ```
  or only list these packets if you don't want to name a specific package manager. Because glibc-devel and zlib-devel are not found in Ubuntu's or Debian's default repositories. Don't know about defaul repos of other distros though.

**Comment by olpaw** [comment] 2019-05-09 08:07
Since this only affects building via the `native-image-maven-plugin` it's probably better to ask the maintainer of the `com.oracle.substratevm:svm-hosted-native-linux-amd64` artifact to build with an older version of binutils so that we do not force users to have binutils >=2.32 installed on their system.

> I suggest adding all the missing information in the manual

The current section reads:
_For compilation native-image depends on the local toolchain, so please make sure: glibc-devel, zlib-devel (header files for the C library and zlib) and gcc are available on your system._

So we are already saying you need a toolchain (which always includes a linker). We can add something like: _On distributions based on Debian the required packages are `build-essential` and `zlib1g-dev`_. cc @olyagpl

**Comment by neon-dev** [comment] 2019-05-09 09:58
Indeed I had binutils 2.28 installed. Updating to 2.32 solved the issue and building now works. Thanks so much for your help, would have never found this out by myself!


> ask the maintainer [...] to build with an older version of binutils

Good idea.

> So we are already saying you need a toolchain (which always includes a linker).

I really think it'd be helpful to add more noob friendly documentation. Not everyone wanting to build native images is an experienced linux user who knows the relation and dependencies of these things.

**Closed** 2019-05-09 10:20 UTC
Labels: substrate

**Comment by olpaw** [comment] 2019-05-14 12:25
@neon-dev the `19.0.0` `com.oracle.substratevm:svm-hosted-native-linux-amd64` artifact is built with an older version on binutils that should not have the same problem as the 1.0.0-rc16 artifact. Please retry with `19.0.0` to check if it now also works with the default binutils of WSL Debian.

**Comment by neon-dev** [comment] 2019-05-15 13:52
@olpaw I had major issues downgrading libc6 but now that I'm back on a stock WSL distro (and binutils 2.28) I could test v19.
The first build attempt failed, but just because I needed to update JVMCI enabled [JDK](https://github.com/graalvm/openjdk8-jvmci-builder/releases). After that everything worked out of the box :)
Thanks again, looking forward to full Windows support and maybe even cross compilation support some time in the future. Great work :smiley:
