### ISSUE TITLE
Access checking fails due to wrong `getCallerClass()` results

### ISSUE THREAD

**Issue by dmlloyd** [oracle/graal#1479] opened 2019-07-08 16:03 UTC
I don't know the exact issue but I think `Reflection.getCallerClass()` is (maybe only sometimes) wrong now.  If you look at the stack trace of quarkusio/quarkus#3074, you can see that the result of `Reflection.getCallerClass()` within `Constructor` was `com.sun.xml.bind.v2.runtime.ClassBeanInfoImpl`, which is one frame lower than the class which should have been returned.  I'm thinking it might be a result of oracle/graal@a14d2f1, specifically the factoring out of `StackTraceUtils`. The problem occurs in 19.1.0 but not 19.0.x.

Reference: https://github.com/quarkusio/quarkus/pull/3074

/cc @christianwimmer

**Comment by christianwimmer** [comment] 2019-07-09 03:51
Fixed in 506f2f188e732219020af3d82b2ec6a97446109a

**Closed by christianwimmer** 2019-07-09 03:51 UTC
Labels: native-image

**Comment by gsmet** [comment] 2019-07-09 09:48
@christianwimmer cool thanks. Any idea when the next micro release is due? We can't upgrade Quarkus to use 19.1.0 until this one is fixed.

Thanks!

**Comment by christianwimmer** [comment] 2019-07-09 16:51
@gsmet There should be a 19.1.1 soon for the Oracle's July critical patch update. I'll work to get it in there.

In general, we would like to test Quarkus before we make a release (ideally in our gate before every merge). Can you provide @cstancu with some input on what and how to test automatically?

**Comment by dmlloyd** [comment] 2019-07-09 16:56
It's quite easy.  You do need to have Apache Maven on your PATH though.

* Check out the project
* Set JAVA_HOME either to the GraalVM distro or to a JVMCI-enabled JDK (only Java 8 is supported but 11 should come soon)
* Set GRAALVM_HOME to the GraalVM distro
* `mvn clean install -Dnative`

It takes quite a while to build all the integration tests with native unfortunately.

**Comment by christianwimmer** [comment] 2019-07-09 18:13
Is there a possibility to run the same tests without needing the Quarkus repository, i.e., just with a Quarkus release on Maven?

**Comment by dmlloyd** [comment] 2019-07-09 21:50
The integration tests are not runnable without checking out the source at present.

**Comment by cstancu** [comment] 2019-07-09 22:50
@dmlloyd I tried the quarkus integration tests with the GraalVM latest master and `Quarkus - Integration Tests - Vert.x` fails with ```Error: Already registered: sun.nio.ch.DatagramChannelImpl.disconnect0(FileDescriptor, boolean)
com.oracle.svm.core.util.UserError$UserException: Already registered: sun.nio.ch.DatagramChannelImpl.disconnect0(FileDescriptor, boolean)```. This is likely because you still have the substitution in your repo and in the meantime, we integrated the PR for the same substitution in our repo.

**Comment by cstancu** [comment] 2019-07-09 22:52
@dmlloyd Is it possible to make a Quarkus release variant that also includes the integration tests? That would make it easier for us to integrate them in our internal CI.

**Comment by bobmcwhirter** [comment] 2019-07-09 22:55
Yeah until there is a release and Q rebases we will have this sorta issue.
We have our workarounds that we can only remove once stuff is upstream and
released.

**Comment by christianwimmer** [comment] 2019-07-10 17:01
How many workarounds are there in Quarkus? Can you push them all out before we make the next release?

In the meantime and to run with multiple different GraalVM release, you can make substitutions conditional on the GraalVM version number by using the `onlyWith` attribute of substitutions.

Currently we have a bit of a testing issue: until we reach a point where you can test the Quarkus master with the most recent GraalVM release, and we can test the most recent Quarkus release with GraalVM master, there will always be a manual integration step that discovers some problems.

For us it is also difficult (for various non-technical reasons) to test based on the Quarkus source code, so having a way to run the Quarkus test only using Maven artifacts would be very helpful.

**Comment by dmlloyd** [comment] 2019-07-10 17:04
> How many workarounds are there in Quarkus?

Usually not many.  In fact I'm surprised about the Vert.x problem because nothing like that came up in my last round of tests, just a few days ago.

Using `onlyWith` is a good idea; I'll pass that on.

**Comment by dmlloyd** [comment] 2019-07-10 17:10
What's the best API to query to get the current GraalVM version?

**Comment by christianwimmer** [comment] 2019-07-10 17:28
The system property `org.graalvm.version` contains the GraalVM version string.

@olpaw @gilles-duboscq we should probably add a GraalVM API (either in `ImageInfo` or even better somewhere that is native image independent) to do version comparisons by string, i.e., to ask queries like "am I running on GraalVM version `19.1` or higher".

**Comment by dmlloyd** [comment] 2019-07-11 12:36
https://github.com/quarkusio/quarkus/pull/3188 should hopefully fix the problem.

**Comment by cstancu** [comment] 2019-07-11 20:01
@dmlloyd I can confirm that the latest Quarkus master now successfully builds with the latest GraalVM master using `mvn clean install -Dnative`.
