### ISSUE TITLE
Cross-Platform Support for native-image

### ISSUE THREAD

**Issue by nathanila** [oracle/graal#765] opened 2018-10-26 18:13 UTC
Please enhance native-image so it can create Linux, Mac and Windows executables regardless of what OS native-image is currently running on.  For example, I would like to run native-image on Linux to produce a Linux, a Mac and a Windows executable.

This will make it easy to run on a build pipeline (e.g. Hudson or Jenkins).  Without this, then I have to figure out how to run a Mac and Windows machine and make them accessible from the build pipeline.  I suppose I could run Mac and Windows in VMs but this is difficult as well.

I realize Graal does not currently support Windows.  I am anticipating that it will soon.

**Comment by cstancu** [comment] 2018-10-27 07:56
Duplicate of #407.

**Closed by cstancu** 2018-10-27 07:56 UTC
