### ISSUE TITLE
Incorrect behaviour when compiling the Scala compiler 

### ISSUE THREAD

**Issue by vjovanov** [oracle/graal#423] opened 2018-05-17 13:06 UTC
To reproduce:
```
git clone git@github.com:scala/scala.git
cd scala
sbt -java-home <path-to-graal-vm> compiler/compile
```
The failure is:
```
java.util.NoSuchElementException: key not found: method matchEnd7
	at scala.collection.MapOps.default(Map.scala:203)
	at scala.collection.MapOps.default$(Map.scala:202)
	at scala.collection.AbstractMap.default(Map.scala:318)
	at scala.collection.MapOps.apply(Map.scala:122)
	at scala.collection.MapOps.apply$(Map.scala:121)
	at scala.collection.AbstractMap.apply(Map.scala:318)
```
The method that misbehaves is probably 
```
scala.tools.nsc.backend.jvm.BCodeIdiomatic$LabelDefsFinder.traverse
```
as changing it with `println` statements made the bug go away. 
Big thanks to @lrytz for finding the bug and identifying the method that fails.

**Comment by lrytz** [comment] 2018-05-17 14:42
That looks unexpected. Is it a fresh checkout / can you run `git clean -dffx`? `MapLike` is something from 2.12 land, should not show up/exist in 2.13.

**Comment by dougxc** [comment] 2018-05-17 15:38
After running `git clean -dffx`, I can now reproduce - thanks.

**Comment by lrytz** [comment] 2018-05-18 06:44
Once diagnosed or fixed, we'd be interested to hear what the issue was. Is the Scala compiler emitting exotic bytecode patterns?

For a long while, we had intermittent failures on CI that we could never nail down (https://github.com/scala/bug/issues/9264). That was on HotSpot. We could not reproduce the issue reliably. Maybe there is a small chance the the issue we're seeing here on Graal is related.

**Comment by dougxc** [comment] 2018-05-22 12:54
@lrytz what kind of println statements make the problem go away? Adding `-XX:CompileCommand=exclude,scala.tools.nsc.backend.jvm.BCodeIdiomatic\$LabelDefsFinder::traverse` confirms your suspicion that the problem is in the compilation of `scala.tools.nsc.backend.jvm.BCodeIdiomatic$LabelDefsFinder.traverse` and I'm now trying to work out which Graal phase is causing the problem.

**Comment by dougxc** [comment] 2018-05-22 14:15
@lrytz II know it's a big ask, but is there anyway you can boil this error down to a simple(r) reproducer?

**Comment by mukel** [comment] 2018-05-22 17:19
Triggers only on `graal-enterprise`

**Comment by lrytz** [comment] 2018-05-22 18:39
@dougxc to minimize the number of players in the game, you can run `java` directly without sbt, and use the scala compiler "as a library".

Download 2.13.0-M4 from https://downloads.lightbend.com/scala/2.13.0-M4/scala-2.13.0-M4.tgz

```
➜  scala13 git:(2.13.x) ✗ git checkout v2.13.0-M4
➜  scala13 git:(a002630512) ✗ find src/compiler -name '*.scala' > files
➜  scala13 git:(a002630512) ✗ S=/Users/luc/scala/scala-2.13.0-M4
➜  scala13 git:(a002630512) ✗ /Library/Java/JavaVirtualMachines/graalvm-1.0.0-rc1/Contents/Home/bin/java -Xmx1536m -Xms1536m -Xss5m -classpath $S/lib/scala-compiler.jar:$S/lib/scala-library.jar:$S/lib/scala-reflect.jar scala.tools.nsc.Main -cp $S/lib/scala-compiler.jar:$S/lib/scala-library.jar:$S/lib/scala-reflect.jar @files -d sandbox
java.util.NoSuchElementException: key not found: method matchEnd7
	at scala.collection.MapOps.default(Map.scala:203)
	at scala.collection.MapOps.default$(Map.scala:202)
	at scala.collection.AbstractMap.default(Map.scala:318)
	at scala.collection.MapOps.apply(Map.scala:122)
	at scala.collection.MapOps.apply$(Map.scala:121)
	at scala.collection.AbstractMap.apply(Map.scala:318)
	at scala.tools.nsc.backend.jvm.BCodeBodyBuilder$PlainBodyBuilder.genApply(BCodeBodyBuilder.scala:654)
```

I don't have a good idea how to minimize the issue further. Compiling fewer files will probably lead to different profiles and might not trigger the bug in Graal.

**Comment by mukel** [comment] 2018-05-23 09:32
Narrowed it down to `-Dgraal.OptimizeLoopAccesses=false` which is one of the latest phases.

**Comment by mukel** [comment] 2018-05-24 14:51
A fix is being merged, will be out for RC2.
The culprit was one of the optimization phases that went rogue with the `List` implementation in Scala, specifically with the mutable `var next` trick. The pattern was exotic enough that we couldn't reproduce it in Java.

**Comment by lrytz** [comment] 2018-05-24 20:46
Is the fix in one of the recent commits here https://github.com/oracle/graal/commits/master/compiler?

Could you share what the exotic bytecode pattern is? Mutable varialbes seem pretty common in Java 😃.

**Comment by dougxc** [comment] 2018-05-24 21:06
The fix is in an enterprise extension so unfortunately it won't show up on GitHub. The problem (as I understand it) was that a node was hoisted outside a loop but one of its usages was not rewired correctly. In any case, the fix will be part of the next GraalVM release.

**Comment by mukel** [comment] 2018-05-24 21:33
Until then you can disable the phase by passing `-Dgraal.OptimizeLoopAccesses=false`

Not a bytecode pattern; but a very particular "code pattern" that aligned with other very unlikely conditions to trigger the bug. `scalac` is exotic on it's own :wink:.

**Comment by dougxc** [comment] 2018-06-04 12:36
Please re-open this issue if there's still a problem in the next GraalVM release (in the next few days).

**Closed by dougxc** 2018-06-04 12:36 UTC
Labels: bug, compiler
