### ISSUE TITLE
Support JNA in native-image

### ISSUE THREAD

**Issue by xtron** [oracle/graal#1701] opened 2019-09-25 14:18 UTC
Many libraries in java use JNA (libvirt for example), but it doesn't work in native image.

**Comment by xtron** [comment] 2019-09-25 18:52
Test repo: https://github.com/xtron/jni

**make jar:**

`mvn clean package`

**make native:**

`native-image -H:ResourceConfigurationFiles=./resources.json -H:+JNI --no-fallback -jar ./target/jni-1.0-SNAPSHOT.jar 
`
Test native:
`Exception in thread "main" java.lang.UnsatisfiedLinkError: Unsupported JNI version 0x0, required by /home/xtron/.cache/JNA/temp/jna6845982115619605957.tmp
	at com.oracle.svm.jni.JNILibraryInitializer.initialize(JNILibraryLoadFeature.java:87)
	at com.oracle.svm.core.jdk.NativeLibrarySupport.loadLibrary0(NativeLibrarySupport.java:152)
	at com.oracle.svm.core.jdk.NativeLibrarySupport.loadLibrary(NativeLibrarySupport.java:93)
	at java.lang.ClassLoader.loadLibrary(Target_java_lang_ClassLoader.java:126)
	at java.lang.Runtime.load0(Runtime.java:809)
	at java.lang.Runtime.load(Runtime.java:248)
	at java.lang.System.load(System.java:373)
	at com.sun.jna.Native.loadNativeDispatchLibraryFromClasspath(Native.java:1018)
	at com.sun.jna.Native.loadNativeDispatchLibrary(Native.java:988)
	at com.sun.jna.Native.<clinit>(Native.java:195)
	at com.oracle.svm.core.hub.ClassInitializationInfo.invokeClassInitializer(ClassInitializationInfo.java:350)
	at com.oracle.svm.core.hub.ClassInitializationInfo.initialize(ClassInitializationInfo.java:270)
	at java.lang.Class.ensureInitialized(DynamicHub.java:467)
	at ru.tionix.jni.Main.main(Main.java:10)
`

**test jar:**

`java -jar ./target/jni-1.0-SNAPSHOT.jar 
`

**Version:**

`java -version
openjdk version "1.8.0_222"
OpenJDK Runtime Environment (build 1.8.0_222-20190711120915.buildslave.jdk8u-src-tar--b08)
OpenJDK 64-Bit GraalVM CE 19.2.0.1 (build 25.222-b08-jvmci-19.2-b02, mixed mode)
`

**Comment by cstancu** [comment] 2019-09-29 13:03
Duplicate of #673

**Closed by cstancu** 2019-09-29 13:03 UTC
