### ISSUE TITLE
setAccessible forbidden in JDK 11 in some cases

### ISSUE THREAD

**Issue by johanvos** [oracle/graal#1002] opened 2019-02-23 19:52 UTC
After applying PR #1001 , there is a problem left with Method.setAccessible:
 
Caused by: java.lang.reflect.InaccessibleObjectException: Unable to make public final java.lang.String com.sun.proxy.jdk.proxy1.$Proxy108.value() accessible: module jdk.proxy1 does not "exports com.sun.proxy.jdk.proxy1" to unnamed module @57a31d39
	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:340)
	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:280)
	at java.base/java.lang.reflect.Method.checkCanSetAccessible(Method.java:198)
	at java.base/java.lang.reflect.Method.setAccessible(Method.java:192)
	at com.oracle.svm.hosted.annotation.AnnotationSubstitutionField.readValue(AnnotationSubstitutionField.java:106)

**Comment by cstancu** [comment] 2019-02-25 04:27
Is the error that you see `Caused by: java.lang.reflect.InaccessibleObjectException: Unable to make public final java.lang.String com.sun.proxy.jdk.proxy1.$Proxy124.value() accessible: module jdk.proxy1 does not "exports com.sun.proxy.jdk.proxy1" to unnamed module @18456020
` or similar? I get that at `com.oracle.svm.hosted.annotation.AnnotationSubstitutionField.readValue(AnnotationSubstitutionField.java:106)`.

The problem seems to be with using reflection to read annotations since annotations are generated in the `jdk.proxy1` module, a dynamically created module. I found [this email thread](https://jigsaw-dev.openjdk.java.narkive.com/971RUHGP/is-there-really-a-jdk-proxy1-module) which gives some insights into what might be wrong.

I tried to programmatically get a handle to `jdk.proxy1` to open it to unnamed modules as the email thread suggests. I tried:
`Modules.addOpensToAllUnnamed(Modules.loadModule("jdk.proxy1"), "com.sun.proxy.jdk.proxy1");`
but I get `java.lang.module.FindException: Module jdk.proxy1 not found`.

The next suggestion is to reflect on the proxy interface, i.e., the annotation interface, instead of the generated proxy class. So instead of:

```
Method reflectionMethod = proxy.getClass().getDeclaredMethod(accessorMethod.getName());
```
I tried:

```
Class<?> annotationInterface = proxy.getClass().getInterfaces()[0];
Method reflectionMethod = annotationInterface.getDeclaredMethod(accessorMethod.getName());
```

This seems to work, although if it is actually possible open `jdk.proxy1` I would prefer that.

Additionally you need to open `java.base`:`jdk.internal.vm.annotation` to unnamed modules. I did that programatically using `Modules.addOpensToAllUnnamed(Modules.loadModule("java.base"), "jdk.internal.vm.annotation")`. I added that in the `com.oracle.svm.hosted.annotation.AnnotationSupport` constructor but anywhere before the code in `AnnotationSubstitutionField.readValue()` is executed should work.

**Comment by cstancu** [comment] 2019-02-27 05:44
Fixed by https://github.com/oracle/graal/commit/823361be9081a0e04454fe959ac0c51799d6d3a7.

**Closed by cstancu** 2019-02-27 05:44 UTC
Labels: substrate

**Comment by verhas** [comment] 2019-07-26 12:35
I figured out with your help that I bumped on the same issue in my code. Let add the following:

For me, it seems more reasonable to use

```java
Method reflectionMethod = proxy.annotationType().getDeclaredMethod(accessorMethod.getName());
```

instead of

```java
Class<?> annotationInterface = proxy.getClass().getInterfaces()[0];
Method reflectionMethod = annotationInterface.getDeclaredMethod(accessorMethod.getName());
```

Your approach assumes that the actual class implementation of the annotation interface of which an instance of is referenced by the variable `proxy` implements only one interface. Although not likely that this changes, it is not guaranteed.

**Comment by gsstar9028** [comment] 2020-04-28 17:05
hey is this fixed?

**Comment by cstancu** [comment] 2020-04-29 17:18
@gsstar9028 yes this should be working as intended. 
@verhas, sorry for the late reply, I missed your comment. Since then that code has evolved and we now use a [constant-annotation-marker interface](https://github.com/oracle/graal/blob/master/substratevm/src/com.oracle.svm.hosted/src/com/oracle/svm/hosted/annotation/AnnotationSupport.java#L123) to identify the ahead-of-time allocated annotation proxy objects for certain optimizations.
