### ISSUE TITLE
[native-image] NPE at runtime when trying to use Locale other than default Locale

### ISSUE THREAD

**Issue by maxum2610** [oracle/graal#1645] opened 2019-08-30 09:00 UTC

**Comment by maxum2610** [comment] 2019-08-30 09:27
A Nullpointer exception is thrown when trying to use a different Locale than the default one on JDK11.
example: 
this statement (taken from hsqldb-2.5.0.jar):

 java.util.GregorianCalendar gc = new java.util.GregorianCalendar(TimeZone.getTimeZone("GMT"), Locale.UK);

will fail if the dault Locale is set to en/US.

Set -Duser.language=en and -Duser.country=GB at compile time, and it works ok.

Possible cause is that com.oracle.svm.core.jdk.LocalizationResourceBundles loads Locale specific cache data at compile time only for the default Locale.

Allowing only one Locale is not usable for applications requiring different Locales. Also many modules require Locale specific data, such as hsqldb. Perhaps Locale definitions should be autodetected at compile time and the relevant LocalizationSupport data loaded for all Locals found, not just the default one.

Also getting the correct translation from a specific resource Bundle does not work. The string from the default locale bundle is returned. This issue already exists see #911.

[Fri Aug 30 10:55:51 CEST 2019][FINE] ==================== RUN TASK ====================
[Fri Aug 30 10:55:51 CEST 2019][FINE] Running at /Users/brunoposthuma/WORK/ACSY/maventestproject/target/client
[Fri Aug 30 10:55:51 CEST 2019][INFO] [SUB] Hello, JAVA main, argc = 1, argv = 0x7ffee38a8fd0
[Fri Aug 30 10:55:51 CEST 2019][INFO] [SUB] 2019-08-30 10:55:51.867 maventestproject[51518:2697266] Starting Gluon VM...
[Fri Aug 30 10:55:51 CEST 2019][INFO] [SUB] Starting Hello
[Fri Aug 30 10:55:51 CEST 2019][INFO] [SUB] DUMPING System.properties:
[Fri Aug 30 10:55:51 CEST 2019][INFO] [SUB] java.specification.version: 11
[Fri Aug 30 10:55:51 CEST 2019][INFO] [SUB] org.graalvm.nativeimage.kind: shared
[Fri Aug 30 10:55:51 CEST 2019][INFO] [SUB] sun.jnu.encoding: UTF-8
[Fri Aug 30 10:55:51 CEST 2019][INFO] [SUB] java.class.path: 
[Fri Aug 30 10:55:51 CEST 2019][INFO] [SUB] user.name: brunoposthuma
[Fri Aug 30 10:55:51 CEST 2019][INFO] [SUB] path.separator: :
[Fri Aug 30 10:55:51 CEST 2019][INFO] [SUB] java.vm.vendor: Oracle Corporation
[Fri Aug 30 10:55:51 CEST 2019][INFO] [SUB] os.version: 10.14.5
[Fri Aug 30 10:55:51 CEST 2019][INFO] [SUB] java.endorsed.dirs: 
[Fri Aug 30 10:55:51 CEST 2019][INFO] [SUB] file.encoding: UTF-8
[Fri Aug 30 10:55:51 CEST 2019][INFO] [SUB] java.vendor.url: https://www.graalvm.org/
[Fri Aug 30 10:55:51 CEST 2019][INFO] [SUB] java.vm.name: Substrate VM
[Fri Aug 30 10:55:51 CEST 2019][INFO] [SUB] java.vm.specification.version: 11
[Fri Aug 30 10:55:51 CEST 2019][INFO] [SUB] os.name: Mac OS X
[Fri Aug 30 10:55:51 CEST 2019][INFO] [SUB] jdk.lang.Process.launchMechanism: FORK
[Fri Aug 30 10:55:51 CEST 2019][INFO] [SUB] java.io.tmpdir: /var/folders/zk/vl99t9gn7r9c6p4hcc_59mkh0000gn/T/
[Fri Aug 30 10:55:51 CEST 2019][INFO] [SUB] java.version: 11.0.2
[Fri Aug 30 10:55:51 CEST 2019][INFO] [SUB] user.home: /Users/brunoposthuma
[Fri Aug 30 10:55:51 CEST 2019][INFO] [SUB] user.dir: /Users/brunoposthuma/WORK/ACSY/maventestproject/target/client
[Fri Aug 30 10:55:51 CEST 2019][INFO] [SUB] os.arch: x86_64
[Fri Aug 30 10:55:51 CEST 2019][INFO] [SUB] java.specification.vendor: Oracle Corporation
[Fri Aug 30 10:55:51 CEST 2019][INFO] [SUB] java.vm.specification.name: Java Virtual Machine Specification
[Fri Aug 30 10:55:51 CEST 2019][INFO] [SUB] org.graalvm.nativeimage.imagecode: runtime
[Fri Aug 30 10:55:51 CEST 2019][INFO] [SUB] file.separator: /
[Fri Aug 30 10:55:51 CEST 2019][INFO] [SUB] line.separator: 
[Fri Aug 30 10:55:51 CEST 2019][INFO] [SUB] 
[Fri Aug 30 10:55:51 CEST 2019][INFO] [SUB] java.library.path: 
[Fri Aug 30 10:55:51 CEST 2019][INFO] [SUB] java.vendor: Oracle Corporation
[Fri Aug 30 10:55:51 CEST 2019][INFO] [SUB] java.vm.specification.vendor: Oracle Corporation
[Fri Aug 30 10:55:51 CEST 2019][INFO] [SUB] java.specification.name: Java Platform API Specification
[Fri Aug 30 10:55:51 CEST 2019][INFO] [SUB] java.vm.version: GraalVM 20.0.0-ea+17
[Fri Aug 30 10:55:51 CEST 2019][INFO] [SUB] java.ext.dirs: 
[Fri Aug 30 10:55:51 CEST 2019][INFO] [SUB] java.class.version: 55.0
[Fri Aug 30 10:55:51 CEST 2019][INFO] [SUB] Setting java.home=/macos-x86_64/maventestproject.app/Contents/Resources/java.home
[Fri Aug 30 10:55:51 CEST 2019][INFO] [SUB] Setting java.util.logging.config.file=/macos-x86_64/maventestproject.app/Contents/Resources/java.home/conf/logging.properties
[Fri Aug 30 10:55:51 CEST 2019][INFO] [SUB] Trying GregorianCalendar
[Fri Aug 30 10:55:51 CEST 2019][INFO] [SUB] Trying DriverManager.getConnection
[Fri Aug 30 10:55:51 CEST 2019][INFO] [SUB] databaseDirectory=/Users/brunoposthuma/WORK/ACSY/Database/acsy/global/params
[Fri Aug 30 10:55:51 CEST 2019][INFO] [SUB] testing resource bundles:
[Fri Aug 30 10:55:51 CEST 2019][INFO] [SUB] default Locale = en_GB
[Fri Aug 30 10:55:51 CEST 2019][INFO] [SUB] test.string for Locale nl_BE = From Bundle_en_GB
[Fri Aug 30 10:55:51 CEST 2019][INFO] [SUB] test.string for Locale nl_BE = From Bundle_en_GB
[Fri Aug 30 10:55:51 CEST 2019][INFO] [SUB] This bug is known
[Fri Aug 30 10:55:51 CEST 2019][INFO] [SUB] Trying DecimalFormatSymbols.getInstance(new Locale("nl","BE"))
[Fri Aug 30 10:55:51 CEST 2019][INFO] [SUB] Error for new Locale("nl-BE")
[Fri Aug 30 10:55:51 CEST 2019][INFO] [SUB] java.lang.NullPointerException
[Fri Aug 30 10:55:51 CEST 2019][INFO] [SUB] 	at jdk.internal.loader.BootLoader.hasClassPath(BootLoader.java:101)
[Fri Aug 30 10:55:51 CEST 2019][INFO] [SUB] 	at java.util.ServiceLoader$LazyClassPathLookupIterator.nextProviderClass(ServiceLoader.java:1189)
[Fri Aug 30 10:55:51 CEST 2019][INFO] [SUB] 	at java.util.ServiceLoader$LazyClassPathLookupIterator.hasNextService(ServiceLoader.java:1220)
[Fri Aug 30 10:55:51 CEST 2019][INFO] [SUB] 	at java.util.ServiceLoader$LazyClassPathLookupIterator.hasNext(ServiceLoader.java:1264)
[Fri Aug 30 10:55:51 CEST 2019][INFO] [SUB] 	at java.util.ServiceLoader$2.hasNext(ServiceLoader.java:1299)
[Fri Aug 30 10:55:51 CEST 2019][INFO] [SUB] 	at java.util.ServiceLoader$3.hasNext(ServiceLoader.java:1384)
[Fri Aug 30 10:55:51 CEST 2019][INFO] [SUB] 	at sun.util.resources.Bundles$2.run(Bundles.java:255)
[Fri Aug 30 10:55:51 CEST 2019][INFO] [SUB] 	at sun.util.resources.Bundles$2.run(Bundles.java:253)
[Fri Aug 30 10:55:51 CEST 2019][INFO] [SUB] 	at java.security.AccessController.doPrivileged(AccessController.java:68)
[Fri Aug 30 10:55:51 CEST 2019][INFO] [SUB] 	at sun.util.resources.Bundles.loadBundleFromProviders(Bundles.java:252)
[Fri Aug 30 10:55:51 CEST 2019][INFO] [SUB] 	at sun.util.resources.Bundles.findBundleOf(Bundles.java:201)
[Fri Aug 30 10:55:51 CEST 2019][INFO] [SUB] 	at sun.util.resources.Bundles.findBundleOf(Bundles.java:160)
[Fri Aug 30 10:55:51 CEST 2019][INFO] [SUB] 	at sun.util.resources.Bundles.loadBundleOf(Bundles.java:145)
[Fri Aug 30 10:55:51 CEST 2019][INFO] [SUB] 	at sun.util.resources.Bundles.of(Bundles.java:106)
[Fri Aug 30 10:55:51 CEST 2019][INFO] [SUB] 	at sun.util.resources.LocaleData$1.run(LocaleData.java:185)
[Fri Aug 30 10:55:51 CEST 2019][INFO] [SUB] 	at sun.util.resources.LocaleData$1.run(LocaleData.java:182)
[Fri Aug 30 10:55:51 CEST 2019][INFO] [SUB] 	at java.security.AccessController.doPrivileged(AccessController.java:68)
[Fri Aug 30 10:55:51 CEST 2019][INFO] [SUB] 	at sun.util.resources.LocaleData.getBundle(LocaleData.java:182)
[Fri Aug 30 10:55:51 CEST 2019][INFO] [SUB] 	at sun.util.resources.LocaleData.getNumberFormatData(LocaleData.java:178)
[Fri Aug 30 10:55:51 CEST 2019][INFO] [SUB] 	at sun.util.locale.provider.LocaleResources.getDecimalFormatSymbolsData(LocaleResources.java:177)
[Fri Aug 30 10:55:51 CEST 2019][INFO] [SUB] 	at java.text.DecimalFormatSymbols.initialize(DecimalFormatSymbols.java:628)
[Fri Aug 30 10:55:51 CEST 2019][INFO] [SUB] 	at java.text.DecimalFormatSymbols.<init>(DecimalFormatSymbols.java:113)
[Fri Aug 30 10:55:51 CEST 2019][INFO] [SUB] 	at sun.util.locale.provider.DecimalFormatSymbolsProviderImpl.getInstance(DecimalFormatSymbolsProviderImpl.java:85)
[Fri Aug 30 10:55:51 CEST 2019][INFO] [SUB] 	at java.text.DecimalFormatSymbols.getInstance(DecimalFormatSymbols.java:180)
[Fri Aug 30 10:55:51 CEST 2019][INFO] [SUB] 	at be.digitalsolutions.maventestproject.Hello.<init>(Hello.java:143)
[Fri Aug 30 10:55:51 CEST 2019][INFO] [SUB] 	at be.digitalsolutions.maventestproject.Hello.main(Hello.java:178)
[Fri Aug 30 10:55:51 CEST 2019][INFO] [SUB] Trying DecimalFormatSymbols.getInstance(Locale.FRENCH)
[Fri Aug 30 10:55:51 CEST 2019][INFO] [SUB] Error for Locale.FRENCH
[Fri Aug 30 10:55:51 CEST 2019][INFO] [SUB] java.lang.NullPointerException
[Fri Aug 30 10:55:51 CEST 2019][INFO] [SUB] 	at jdk.internal.loader.BootLoader.hasClassPath(BootLoader.java:101)
[Fri Aug 30 10:55:51 CEST 2019][INFO] [SUB] 	at java.util.ServiceLoader$LazyClassPathLookupIterator.nextProviderClass(ServiceLoader.java:1189)
[Fri Aug 30 10:55:51 CEST 2019][INFO] [SUB] 	at java.util.ServiceLoader$LazyClassPathLookupIterator.hasNextService(ServiceLoader.java:1220)
[Fri Aug 30 10:55:51 CEST 2019][INFO] [SUB] 	at java.util.ServiceLoader$LazyClassPathLookupIterator.hasNext(ServiceLoader.java:1264)
[Fri Aug 30 10:55:51 CEST 2019][INFO] [SUB] 	at java.util.ServiceLoader$2.hasNext(ServiceLoader.java:1299)
[Fri Aug 30 10:55:51 CEST 2019][INFO] [SUB] 	at java.util.ServiceLoader$3.hasNext(ServiceLoader.java:1384)
[Fri Aug 30 10:55:51 CEST 2019][INFO] [SUB] 	at sun.util.resources.Bundles$2.run(Bundles.java:255)
[Fri Aug 30 10:55:51 CEST 2019][INFO] [SUB] 	at sun.util.resources.Bundles$2.run(Bundles.java:253)
[Fri Aug 30 10:55:51 CEST 2019][INFO] [SUB] 	at java.security.AccessController.doPrivileged(AccessController.java:68)
[Fri Aug 30 10:55:51 CEST 2019][INFO] [SUB] 	at sun.util.resources.Bundles.loadBundleFromProviders(Bundles.java:252)
[Fri Aug 30 10:55:51 CEST 2019][INFO] [SUB] 	at sun.util.resources.Bundles.findBundleOf(Bundles.java:201)
[Fri Aug 30 10:55:51 CEST 2019][INFO] [SUB] 	at sun.util.resources.Bundles.loadBundleOf(Bundles.java:145)
[Fri Aug 30 10:55:51 CEST 2019][INFO] [SUB] 	at sun.util.resources.Bundles.of(Bundles.java:106)
[Fri Aug 30 10:55:51 CEST 2019][INFO] [SUB] 	at sun.util.resources.LocaleData$1.run(LocaleData.java:185)
[Fri Aug 30 10:55:51 CEST 2019][INFO] [SUB] 	at sun.util.resources.LocaleData$1.run(LocaleData.java:182)
[Fri Aug 30 10:55:51 CEST 2019][INFO] [SUB] 	at java.security.AccessController.doPrivileged(AccessController.java:68)
[Fri Aug 30 10:55:51 CEST 2019][INFO] [SUB] 	at sun.util.resources.LocaleData.getBundle(LocaleData.java:182)
[Fri Aug 30 10:55:51 CEST 2019][INFO] [SUB] 	at sun.util.resources.LocaleData.getNumberFormatData(LocaleData.java:178)
[Fri Aug 30 10:55:51 CEST 2019][INFO] [SUB] 	at sun.util.locale.provider.LocaleResources.getDecimalFormatSymbolsData(LocaleResources.java:177)
[Fri Aug 30 10:55:51 CEST 2019][INFO] [SUB] 	at java.text.DecimalFormatSymbols.initialize(DecimalFormatSymbols.java:628)
[Fri Aug 30 10:55:51 CEST 2019][INFO] [SUB] 	at java.text.DecimalFormatSymbols.<init>(DecimalFormatSymbols.java:113)
[Fri Aug 30 10:55:51 CEST 2019][INFO] [SUB] 	at sun.util.locale.provider.DecimalFormatSymbolsProviderImpl.getInstance(DecimalFormatSymbolsProviderImpl.java:85)
[Fri Aug 30 10:55:51 CEST 2019][INFO] [SUB] 	at java.text.DecimalFormatSymbols.getInstance(DecimalFormatSymbols.java:180)
[Fri Aug 30 10:55:51 CEST 2019][INFO] [SUB] 	at be.digitalsolutions.maventestproject.Hello.<init>(Hello.java:153)
[Fri Aug 30 10:55:51 CEST 2019][INFO] [SUB] 	at be.digitalsolutions.maventestproject.Hello.main(Hello.java:178)
[Fri Aug 30 10:55:51 CEST 2019][INFO] [SUB] Trying DecimalFormatSymbols.getInstance(Locale.ENGLISH)
[Fri Aug 30 10:55:51 CEST 2019][INFO] [SUB] Ok for Locale.ENGLISH
[Fri Aug 30 10:55:51 CEST 2019][INFO] [SUB] By By Hello

**Comment by sdavids** [comment] 2020-12-02 01:54
The excellent I18N features of Java are a major selling point vs. the poor support in Rust and Go.

**Comment by d-kozak** [comment] 2021-05-31 12:25
I've just tried the provided code snippet on build from current master and did not get NPE, I got what seems to be a correct output:

```
java.util.GregorianCalendar[time=1622463457582,areFieldsSet=true,areAllFieldsSet=true,lenient=true,
zone=sun.util.calendar.ZoneInfo[id="GMT",offset=0,dstSavings=0,useDaylight=false,transitions=0,lastRule=null],
firstDayOfWeek=2,minimalDaysInFirstWeek=4,ERA=1,YEAR=2021,MONTH=4,WEEK_OF_YEAR=22,WEEK_OF_MONTH=5,
DAY_OF_MONTH=31,DAY_OF_YEAR=151,DAY_OF_WEEK=2,DAY_OF_WEEK_IN_MONTH=5,AM_PM=1,HOUR=0,
HOUR_OF_DAY=12,MINUTE=17,SECOND=37,MILLISECOND=582,ZONE_OFFSET=0,DST_OFFSET=0]
```

Can you please clarify if you still get NPE? 

With regards to localization, now you can change the default locale as well as include multiple locales, see the [updated documentation](https://www.graalvm.org/reference-manual/native-image/Resources/#locales) for details. We are also experimenting with including all locales by default, but it is not set because it increases the image size.

**Comment by d-kozak** [comment] 2021-06-07 13:28
I'm closing the issue assuming the problem is fixed. If you by any chance still experience it, please reopen.

**Closed by d-kozak** 2021-06-07 13:28 UTC
Labels: native-image, spring
