### ISSUE TITLE
Fatal error:com.oracle.svm.core.util.VMError$HostedError: Resource path contains backslash!

### ISSUE THREAD

**Issue by bodiam** [oracle/graal#4002] opened 2021-11-09 14:04 UTC
**Describe the issue**

On my Mac, using GraalVM CE 21.3.0, I'm trying out the native-image builder, using the Example.java listed in the documentation. Compiling is fine, but when I use the native-image builder, I get the following error:

```
~/Downloads ❯ native-image Example
[example:2391]    classlist:   1,237.52 ms,  0.96 GB
[example:2391]        (cap):   3,298.18 ms,  0.96 GB
[example:2391]        setup:   6,471.21 ms,  0.96 GB
[example:2391]     analysis:   4,496.13 ms,  1.71 GB
Fatal error:com.oracle.svm.core.util.VMError$HostedError: Resource path contains backslash!
```

**Steps to reproduce the issue**

Use the Example.java from here: https://www.graalvm.org/reference-manual/native-image/#build-a-native-image

~/Downloads ❯ vim Example.java
~/Downloads ❯ javac Example.java
~/Downloads ❯ native-image Example

**Describe GraalVM and your environment:**

openjdk version "11.0.13" 2021-10-19
OpenJDK Runtime Environment GraalVM CE 21.3.0 (build 11.0.13+7-jvmci-21.3-b05)
OpenJDK 64-Bit Server VM GraalVM CE 21.3.0 (build 11.0.13+7-jvmci-21.3-b05, mixed mode, sharing)

 - JDK major version: **11**
 - OS: **macOS Monterey**
 - Architecture: **AMD64**

**More details**
Consider adding the `--native-image-info` and  `--verbose` flags when building your native image and paste output below.

Add any other information about the problem here. Especially important are stack traces or log output. Feel free to link to gists or to screenshots if necessary.
```
~/Downloads ❯ native-image Example
[example:2391]    classlist:   1,237.52 ms,  0.96 GB
[example:2391]        (cap):   3,298.18 ms,  0.96 GB
[example:2391]        setup:   6,471.21 ms,  0.96 GB
[example:2391]     analysis:   4,496.13 ms,  1.71 GB
Fatal error:com.oracle.svm.core.util.VMError$HostedError: Resource path contains backslash!
	at com.oracle.svm.core.util.VMError.shouldNotReachHere(VMError.java:68)
	at com.oracle.svm.core.util.VMError.guarantee(VMError.java:89)
	at com.oracle.svm.hosted.ResourcesFeature.matches(ResourcesFeature.java:334)
	at com.oracle.svm.hosted.ResourcesFeature.scanDirectory(ResourcesFeature.java:288)
	at com.oracle.svm.hosted.ResourcesFeature.lambda$duringAnalysis$2(ResourcesFeature.java:226)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
	at java.base/java.util.stream.DistinctOps$1$2.accept(DistinctOps.java:175)
	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1655)
	at java.base/java.util.stream.Streams$ConcatSpliterator.forEachRemaining(Streams.java:735)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:497)
	at com.oracle.svm.hosted.ResourcesFeature.duringAnalysis(ResourcesFeature.java:223)
	at com.oracle.svm.hosted.NativeImageGenerator.lambda$runPointsToAnalysis$12(NativeImageGenerator.java:727)
	at com.oracle.svm.hosted.FeatureHandler.forEachFeature(FeatureHandler.java:73)
	at com.oracle.svm.hosted.NativeImageGenerator.runPointsToAnalysis(NativeImageGenerator.java:727)
	at com.oracle.svm.hosted.NativeImageGenerator.doRun(NativeImageGenerator.java:529)
	at com.oracle.svm.hosted.NativeImageGenerator.run(NativeImageGenerator.java:488)
	at com.oracle.svm.hosted.NativeImageGeneratorRunner.buildImage(NativeImageGeneratorRunner.java:403)
	at com.oracle.svm.hosted.NativeImageGeneratorRunner.build(NativeImageGeneratorRunner.java:569)
	at com.oracle.svm.hosted.NativeImageGeneratorRunner.main(NativeImageGeneratorRunner.java:122)
	at com.oracle.svm.hosted.NativeImageGeneratorRunner$JDK9Plus.main(NativeImageGeneratorRunner.java:599)
```

**Comment by bodiam** [comment] 2021-11-09 14:09
I've also tried running the native-image with the following argument: `native-image -H:Log=registerResource: Example`

But that results in this:

```
~/Downloads ❯ native-image -H:Log=registerResource: Example
[example:2531]    classlist:   1,068.43 ms,  0.96 GB
[example:2531]        (cap):   2,901.60 ms,  0.96 GB
[example:2531]        setup:   4,397.10 ms,  0.96 GB
[Use -Dgraal.LogFile=<path> to redirect Graal log output to a file.]
[thread:1] scope: main
  [thread:1] scope: main.registerResource
  ServiceLoaderFeature: registerResource: META-INF/services/java.nio.file.spi.FileSystemProvider
  [thread:1] scope: main.registerResource
  ServiceLoaderFeature: registerResource: META-INF/services/jdk.internal.logger.DefaultLoggerFinder
  [thread:1] scope: main.registerResource
  ServiceLoaderFeature: registerResource: META-INF/services/sun.util.resources.LocaleData$CommonResourceBundleProvider
  [thread:1] scope: main.registerResource
  ServiceLoaderFeature: registerResource: META-INF/services/sun.util.resources.LocaleData$SupplementaryResourceBundleProvider
  [thread:1] scope: main.registerResource
  Resources have been added by ServiceLoaderFeature. Automatic registration can be disabled with -H:-UseServiceLoaderFeature
[example:2531]     analysis:   6,225.15 ms,  2.31 GB
Fatal error:com.oracle.svm.core.util.VMError$HostedError: Resource path contains backslash!
	at com.oracle.svm.core.util.VMError.shouldNotReachHere(VMError.java:68)
	at com.oracle.svm.core.util.VMError.guarantee(VMError.java:89)
       ... etc ...
```

**Comment by oubidar-Abderrahim** [comment] 2021-11-12 13:19
Thank you for reporting this, we will take a look into it and get back to you

**Comment by oubidar-Abderrahim** [comment] 2021-11-15 15:27
I couldn't reproduce the issue on my macOS Catalina, this could be a specific issue with macOS Monterey but I have no way to confirm this.

**Comment by epragtbeamtree** [comment] 2021-11-22 07:41
@oubidar-Abderrahim no problem, I'll try to look into it myself. I've never debugged Graal however, is there an easy way to run Graal from my IDE (IntelliJ) so I can set a few breakpoints or so?

**Comment by petermz** [comment] 2021-11-22 09:31
I think the easiest way to debug native-image is to run it with --debug-attach[:port] , then attach your IDE. Default port is 8000.

**Comment by olpaw** [comment] 2022-03-31 08:23
Fixed with https://github.com/oracle/graal/pull/4395

**Closed by olpaw** 2022-03-31 08:23 UTC
Labels: bug, native-image
