### ISSUE TITLE
Unexpected ClassCastException when compiling simple script

### ISSUE THREAD

**Issue by wildmaples** [oracle/graal#4213] opened 2022-01-14 20:32 UTC
**Describe the issue**
There seems to be a problem where a method is not compiled and the exception is hard to interpret. More specifically, it's only happening on [this branch](https://github.com/Shopify/truffleruby/tree/call-target-agnostic-kwargs) on TruffleRuby. It seems like it could be from a recent [frameslot fix](https://github.com/oracle/graal/commit/def50a7810dd841e0536a3ca11e46a188b943d74). 

I understand it's a large change but we're trying to get unblocked to run some benchmarks. Would appreciate some help in what the issue could be.

The full stack trace is pasted below. 

cc: @lukasstadler 

**Steps to reproduce the issue**
Please include both build steps as well as run steps
1. Checkout [this branch on TruffleRuby](https://github.com/Shopify/truffleruby/tree/call-target-agnostic-kwargs)
2. Run/compile a simple script such as the one below

```ruby
def foo(a:, b:)
  a + b
end

loop do
  foo(a: rand(100), b: rand(100))
end
```

**Describe GraalVM and your environment:**
 - GraalVM version (latest snapshot builds can be found [here](https://github.com/graalvm/graalvm-ce-dev-builds/releases)), or commit id if built from source: **a16215e337f**
 - JDK major version: **[e.g.:8]**
 - OS: macOS Monterey 
 - Architecture: Rosetta / x86_64

**More details**

```
[thread:17] scope: TruffleCompilerThread-17
  [thread:17] scope: TruffleCompilerThread-17.Truffle
  Context: Truffle<Object#foo()>
    [thread:17] scope: TruffleCompilerThread-17.Truffle.CreateGraph
    Context: StructuredGraph:444{Object#foo, HotSpotMethod<OptimizedCallTarget.profiledPERoot(Object[])>}
        [thread:17] scope: TruffleCompilerThread-17.Truffle.CreateGraph.AgnosticInliningPhase.TrufflePartialEscape
        Context: StructuredGraph:444{Object#foo, HotSpotMethod<OptimizedCallTarget.profiledPERoot(Object[])>}
              [thread:17] scope: TruffleCompilerThread-17.Truffle.CreateGraph.AgnosticInliningPhase.TrufflePartialEscape.PartialEscapePhase.iteration 0.EffectsPhaseWithSchedule
              Exception raised in scope TruffleCompilerThread-17.Truffle.CreateGraph.AgnosticInliningPhase.TrufflePartialEscape.PartialEscapePhase.iteration 0.EffectsPhaseWithSchedule: java.lang.ClassCastException: class org.graalvm.compiler.nodes.ValuePhiNode cannot be cast to class org.graalvm.compiler.nodes.virtual.VirtualObjectNode (org.graalvm.compiler.nodes.ValuePhiNode and org.graalvm.compiler.nodes.virtual.VirtualObjectNode are in module jdk.internal.vm.compiler of loader 'platform')
              	at jdk.internal.vm.compiler/org.graalvm.compiler.truffle.compiler.nodes.frame.VirtualFrameSetNode.virtualize(VirtualFrameSetNode.java:96)
              	at jdk.internal.vm.compiler/org.graalvm.compiler.virtual.phases.ea.PartialEscapeClosure.virtualize(PartialEscapeClosure.java:312)
              	at jdk.internal.vm.compiler/org.graalvm.compiler.virtual.phases.ea.PartialEscapeClosure.processVirtualizable(PartialEscapeClosure.java:308)
              	at jdk.internal.vm.compiler/org.graalvm.compiler.virtual.phases.ea.PartialEscapeClosure.processNodeInternal(PartialEscapeClosure.java:237)
              	at jdk.internal.vm.compiler/org.graalvm.compiler.virtual.phases.ea.PartialEscapeClosure.processNode(PartialEscapeClosure.java:210)
              	at jdk.internal.vm.compiler/org.graalvm.compiler.virtual.phases.ea.PEReadEliminationClosure.processNode(PEReadEliminationClosure.java:100)
              	at jdk.internal.vm.compiler/org.graalvm.compiler.virtual.phases.ea.PEReadEliminationClosure.processNode(PEReadEliminationClosure.java:78)
              	at jdk.internal.vm.compiler/org.graalvm.compiler.virtual.phases.ea.EffectsClosure.processBlock(EffectsClosure.java:265)
              	at jdk.internal.vm.compiler/org.graalvm.compiler.virtual.phases.ea.EffectsClosure.processBlock(EffectsClosure.java:72)
              	at jdk.internal.vm.compiler/org.graalvm.compiler.phases.graph.ReentrantBlockIterator.apply(ReentrantBlockIterator.java:152)
              	at jdk.internal.vm.compiler/org.graalvm.compiler.phases.graph.ReentrantBlockIterator.apply(ReentrantBlockIterator.java:124)
              	at jdk.internal.vm.compiler/org.graalvm.compiler.virtual.phases.ea.EffectsPhase.runAnalysis(EffectsPhase.java:104)
              	at jdk.internal.vm.compiler/org.graalvm.compiler.virtual.phases.ea.PartialEscapePhase.run(PartialEscapePhase.java:122)
              	at jdk.internal.vm.compiler/org.graalvm.compiler.virtual.phases.ea.PartialEscapePhase.run(PartialEscapePhase.java:76)
              	at jdk.internal.vm.compiler/org.graalvm.compiler.phases.BasePhase.apply(BasePhase.java:221)
              	at jdk.internal.vm.compiler/org.graalvm.compiler.phases.BasePhase.apply(BasePhase.java:155)
              	at jdk.internal.vm.compiler/org.graalvm.compiler.truffle.compiler.PartialEvaluator.partialEscape(PartialEvaluator.java:403)
              	at jdk.internal.vm.compiler/org.graalvm.compiler.truffle.compiler.PartialEvaluator.truffleTier(PartialEvaluator.java:568)
              	at jdk.internal.vm.compiler/org.graalvm.compiler.truffle.compiler.phases.inlining.GraphManager.peRoot(GraphManager.java:94)
              	at jdk.internal.vm.compiler/org.graalvm.compiler.truffle.compiler.phases.inlining.CallNode.makeRoot(CallNode.java:109)
              	at jdk.internal.vm.compiler/org.graalvm.compiler.truffle.compiler.phases.inlining.CallTree.<init>(CallTree.java:51)
              	at jdk.internal.vm.compiler/org.graalvm.compiler.truffle.compiler.phases.inlining.AgnosticInliningPhase.run(AgnosticInliningPhase.java:81)
              	at jdk.internal.vm.compiler/org.graalvm.compiler.truffle.compiler.phases.inlining.AgnosticInliningPhase.run(AgnosticInliningPhase.java:38)
              	at jdk.internal.vm.compiler/org.graalvm.compiler.phases.BasePhase.apply(BasePhase.java:221)
              	at jdk.internal.vm.compiler/org.graalvm.compiler.phases.BasePhase.apply(BasePhase.java:155)
              	at jdk.internal.vm.compiler/org.graalvm.compiler.truffle.compiler.PartialEvaluator.inliningGraphPE(PartialEvaluator.java:643)
              	at jdk.internal.vm.compiler/org.graalvm.compiler.truffle.compiler.PartialEvaluator.evaluate(PartialEvaluator.java:348)
              	at jdk.internal.vm.compiler/org.graalvm.compiler.truffle.compiler.TruffleCompilerImpl.compileAST(TruffleCompilerImpl.java:507)
              	at jdk.internal.vm.compiler/org.graalvm.compiler.truffle.compiler.TruffleCompilerImpl$TruffleCompilationWrapper.performCompilation(TruffleCompilerImpl.java:718)
              	at jdk.internal.vm.compiler/org.graalvm.compiler.truffle.compiler.TruffleCompilerImpl$TruffleCompilationWrapper.performCompilation(TruffleCompilerImpl.java:656)
              	at jdk.internal.vm.compiler/org.graalvm.compiler.core.CompilationWrapper.run(CompilationWrapper.java:223)
              	at jdk.internal.vm.compiler/org.graalvm.compiler.truffle.compiler.TruffleCompilerImpl.actuallyCompile(TruffleCompilerImpl.java:331)
              	at jdk.internal.vm.compiler/org.graalvm.compiler.truffle.compiler.TruffleCompilerImpl.doCompile(TruffleCompilerImpl.java:285)
              	at jdk.internal.vm.compiler/org.graalvm.compiler.truffle.runtime.GraalTruffleRuntime.compileImpl(GraalTruffleRuntime.java:768)
              	at jdk.internal.vm.compiler/org.graalvm.compiler.truffle.runtime.GraalTruffleRuntime.doCompile(GraalTruffleRuntime.java:744)
              	at jdk.internal.vm.compiler/org.graalvm.compiler.truffle.runtime.GraalTruffleRuntime.doCompile(GraalTruffleRuntime.java:723)
              	at jdk.internal.vm.compiler/org.graalvm.compiler.truffle.runtime.CompilationTask$1.accept(CompilationTask.java:50)
              	at jdk.internal.vm.compiler/org.graalvm.compiler.truffle.runtime.CompilationTask$1.accept(CompilationTask.java:44)
              	at jdk.internal.vm.compiler/org.graalvm.compiler.truffle.runtime.CompilationTask.call(CompilationTask.java:225)
              	at jdk.internal.vm.compiler/org.graalvm.compiler.truffle.runtime.CompilationTask.call(CompilationTask.java:42)
              	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
              	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
              	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
              	at java.base/java.lang.Thread.run(Thread.java:829)
              	at jdk.internal.vm.compiler/org.graalvm.compiler.truffle.runtime.BackgroundCompileQueue$TruffleCompilerThreadFactory$1.run(BackgroundCompileQueue.java:286)

              Context obj org.graalvm.compiler.nodes.StructuredGraph$ScheduleResult@1c54b338
              Context obj org.graalvm.compiler.virtual.phases.ea.PartialEscapePhase@1dbc551d
Dumping IGV graphs in /Users/mapleong/src/github.com/Shopify/truffleruby/graal_dumps/2022.01.14.11.02.22.371
              Context obj StructuredGraph:444{Object#foo, HotSpotMethod<OptimizedCallTarget.profiledPERoot(Object[])>}
              Context obj org.graalvm.compiler.truffle.compiler.phases.inlining.AgnosticInliningPhase@73552b5b
              Context obj Truffle<Object#foo()>
[engine] opt failed id=1483  Object#foo                                         |Tier 2|Time 1221(-192654427+192655647)ms|Reason: java.lang.ClassCastException: class org.graalvm.compiler.nodes.ValuePhiNode cannot be cast to class org.graalvm.compiler.nodes.virtual.VirtualObjectNode (org.graalvm.compiler.nodes.ValuePhiNode and org.graalvm.compiler.nodes.virtual.VirtualObjectNode are in module jdk.internal.vm.compiler of loader 'platform')|Timestamp 192655649052125|Src foo.rb:1```

**Comment by nirvdrum** [comment] 2022-01-18 20:21
@wildmaples and I spent some time stepping through this code today. The issue appears to be in: 

https://github.com/oracle/graal/blob/6ffdd9760d7d1da4e6ae7f2bd70bcf830ac4f351/compiler/src/org.graalvm.compiler.truffle.compiler/src/org/graalvm/compiler/truffle/compiler/nodes/frame/VirtualFrameSetNode.java#L96

The issue can be reliably reproduced within a TruffleRuby branch (not _master_), but we were unable to create a smaller reproduction. We did collect some data, however.

| Expression | Type |
|------------|------|
| type | VirtualFrameAccessType.Legacy |
| valueKind | JavaKind.Object |
| frame.getPrimitiveArray(type) | VirtualArray. “31|VirtualArray (1) J[4]” (stamp: ObjectStamp “a! long[]”) |
| primitiveAlias | ValuePhiNode |

We've added a guard that eliminates the issue in #4233. But, it's unclear whether that's the proper fix.

**Comment by lukasstadler** [comment] 2022-01-19 08:06
I'm taking a look. It might be a race between execution and compilation, and those are notoriously hard to reproduce.

**Comment by lukasstadler** [comment] 2022-01-19 09:04
unrelated, but for reference: I wasn't able to build the branch from scratch, but building the base revision first and then updating to the branch worked.

**Comment by lukasstadler** [comment] 2022-01-19 09:26
How exactly did you build and run the example? I'm unable to reproduce the problem so far.

**Comment by eregon** [comment] 2022-01-19 10:58
@lukasstadler You need:
```
bin/jt build --env jvm-ce
bin/jt -u jvm-ce ruby test.rb
```
And `test.rb` is the above snippet.

See https://github.com/oracle/truffleruby/blob/master/doc/contributor/workflow.md for more details.

**Comment by lukasstadler** [comment] 2022-01-19 12:04
Ok, I'll try with jt, running the above example with sdk/latest_graalvm_home/bin/ruby didn't produce the error.

**Comment by eregon** [comment] 2022-01-19 12:33
Note, there is another error (Partial evaluation did not reduce value to a constant, is a regular compiler node), which can be avoided by commenting out the `CompilerAsserts.partialEvaluationConstant(descriptor);` in RubyArguments.java:234.

**Comment by lukasstadler** [comment] 2022-01-19 12:36
I can reproduce the problem now, looking at it now.

**Comment by eregon** [comment] 2022-01-19 12:36
I pushed a commit to that branch commenting out that partialEvaluationConstant which does not hold yet.

**Comment by lukasstadler** [comment] 2022-01-20 12:10
As far as I can tell, this error is caused by calls to Frame.getValue that are in PE'd code.
That shouldn't cause exception in the compiler, of course, but even if it works, it will likely produce non-optimal code and/or lead to unnecessary deoptimizations.
Nevertheless, I'll create a fix for this.

**Comment by lukasstadler** [comment] 2022-01-20 12:10
tracked internally as GR-36493

**Comment by chrisseaton** [comment] 2022-01-20 13:18
> As far as I can tell, this error is caused by calls to Frame.getValue that are in PE'd code.

That sounds like that could be the case yes - we'll look for that.

**Comment by lukasstadler** [comment] 2022-01-31 09:32
this is fixed with https://github.com/oracle/graal/commit/d7a3d5f5665283c5848907b5df6cc6b807b98cea

**Closed by lukasstadler** 2022-01-31 09:32 UTC
Labels: bug
