### ISSUE TITLE
Add iOS support to Substrate VM

### ISSUE THREAD

**Issue by sirthias** [oracle/graal#373] opened 2018-04-23 14:31 UTC
If Substract VM allowed for writing libraries in any of the supported languages (most importantly Java) and these libraries could be called into from iOS application code (written in Swift or Objective-C) then this would be a complete game changer for the "holy grail" of mobile development: Joint code bases for truly native mobile applications.

Rich client logic could then be written purely in Java, packaged as a library and be usable from thin layers of UI code on either platform. Currently this is not properly possible.
There are a few tools promising a solution in that area (e.g. Robo VM or Multi-OS-Engine), but they all come with quite a few strings attached and severely lack the technological soundness of Graal.

It'd be absolutely awesome if Graal would finally be the tool to properly bridge this so far insurmountable chasm between the two major mobile universes.

**Comment by cstancu** [comment] 2018-04-23 21:00
The Truffle languages can be supported as long as Truffle runs in interpreter mode. You won't get the same performance as with a JIT but it would still be useful for certain scenarios.

**Comment by sirthias** [comment] 2018-04-24 09:40
Ok, great. Thank you, @cstancu!

**Comment by zaharidichev** [comment] 2018-05-22 07:56
@cstancu Thanks for the time to elaborate on all the details. So it appears to me that the sequence of steps is:

**Comment by zaharidichev** [comment] 2018-05-22 08:02
Hi there @cstancu Thanks a lot for elaborating on these topics. So it appears to me that the two major pieces of work are finishing the AArch64 compiler backend and then providing support for that in SVM.  Is there any kind of board outlining planned broken down work on any of these major tasks. Just asking because if there is any way to help, I would be more than glad to (although the matter can be at times intimidating). I see @daniel-stewart-qdt is doing some work on AArch64, so maybe he can provide some info on what the next planned steps are as well. In any case, willing to help where and how I can :)

**Comment by ScalaWilliam** [comment] 2018-10-27 11:10
This is interesting.

**Comment by priand** [comment] 2019-01-11 02:49
@cstancu Any ETA on the iOS support? As @sirthias  said, having a AOT compiler for JVM based languages will be a game changer for the Java community.

**Comment by sanzinger** [comment] 2019-01-14 08:45
We have no ETA for this. We are currently working on SubstrateVM on AArch64 for Linux. IOther platforms are not decided yet.

I hope this answers the original question.

**Comment by sanzinger** [comment] 2019-01-16 08:42
At the moment we do not have a decision if we are going to support iOS. At the moment we are occupied getting AArch64/Linux running.

I think we get a clear picture how iOS goes, when we have completed AArch64/Linux in a usable state.

**Comment by sirthias** [comment] 2019-01-16 11:08
Thank you for this update and re-opening the ticket, @sanzinger!
Much appreciated!

We are keeping our thumbs crossed for iOS support eventually making it onto the Graal roadmap.
We still think it would be absolutely awesome to have and would unlock a ton of opportunities on many fronts.

**Comment by teras** [comment] 2019-04-14 11:59
So, now that the AArch64/Linux is merged, any news about supporting iOS now?

**Comment by vjovanov** [comment] 2019-12-09 20:57
We support deploying to iOS via a Maven plugin. You can find an example at:

  https://github.com/gluonhq/client-samples

You have the examples for iOS:
  
  https://github.com/gluonhq/client-samples/tree/master/Maven/HelloFX

At this point, I would still advise using the LLVM backend as it is more complete.

**Closed** 2019-12-09 21:04 UTC
Labels: feature, native-image

**Comment by highleverage** [comment] 2020-04-30 10:43
> We support deploying to iOS via a Maven plugin. You can find examples at:
> 
> https://github.com/gluonhq/client-samples
> 
> You have an example for iOS at:
> 
> https://github.com/gluonhq/client-samples/tree/master/Maven/HelloFX
> 
> At this point, I would still advise using the LLVM backend as it is more complete.
> 
> In the future, we might support generating iOS binaries directly from GraalVM, but it is not certain if/when this will happen.

Hello, could you please share any guide where I can read about how exactly it could be done? I mean, I have a jar that I can compile as a native library for OS X and Linux, but how I could compile it for iOS?

**Comment by vjovanov** [comment] 2020-04-30 11:04
@johanvos how far are we from building shared libraries for iOS?

**Comment by sirthias** [comment] 2020-05-01 08:28
Shared library support for iOS would be absolutely fabulous!!
If it's available - or as soon as it's available - I'd be extremely eager to try it out and promote it (e.g. with blog posts, talks, etc.).

It's the original graal "feature" that this ticket was all about.

**Comment by CedricGatay** [comment] 2020-05-04 07:06
@sirthias you can take a look at the issue I made here (https://github.com/gluonhq/substrate/issues/47) and the links to my forked repositories to have a starting point for building iOS static libraries.

It is however an abandoned project on my side, as the results were not convincing enough for the time being, we decided to switch to K/Native instead.

**Comment by sirthias** [comment] 2020-05-04 08:46
Thank you so much for the pointer, @CedricGatay, I hadn't seen your work there yet.
A largish Scala-based shared lib is my exact first use case, so you breaking the ground there is highly relevant for us.

What exactly wasn't "convincing enough" and the trigger for you to abandon your project?

**Comment by CedricGatay** [comment] 2020-05-04 08:49
There was the following concerns : 

 * hacks around loading native libraries (JNI on devices)
 * final artifact size (over 200Mb)
 * general stability, it would randomly crash on device without a readable backtrace
 * build time / reproducibility was also present (but not the factor that made us abandon this, as we know it will be better and better).

**Comment by sirthias** [comment] 2020-05-04 09:07
Ok, thank you for these details!
I guess we could live with all but your 3rd point, but maybe it's related to your first.

I'll definitely play around with your forks and try to get sth off the ground.
The good thing is that, in our use case, the shared library would simply be a heap of rather complicated business logic and nothing that needs interacting with native libs.

It would be great though to have proper threading support. Do you have any perspective on that? Did you encounter any issues wrt thread scheduling/concurrency abstractions?
Without having given it a lot of thought yet I'd assume the substrate-based shared lib to behave like any other native ios library, with the ability to start and use "its own" threads or simply run on the caller thread.
Are there any gotchas wrt the memory model? I would expect graal to make sure that all the JVM guarantees are properly upheld whatever the target platform but could imagine that there are certain edges cases that one should be aware of.

**Comment by CedricGatay** [comment] 2020-05-04 09:12
As far I remember, I had no concurrency issues / memory leaks during my testings (the framework is using akka / scala and makes use of concurrency).

I don't know if the random crashes were due to JNI loading ,but I sincerely doubt it, as it was rather random and backtrace were not necessary involving native code. However I might have done things the wrong way (and Graal have evolved too).

One of the "difficult" things was finding the proper LLVM / Graal combination to make the build "pass", afterwards it runs "properly".

**Comment by sirthias** [comment] 2020-05-04 09:22
Ok, thank you, Cedric!

**Comment by vjovanov** [comment] 2020-05-04 09:23
@CedricGatay we have made quite a few improvements in the last couple of months: 
- The LLVM is shipped with Graal so there are no difficulties with finding the right version. 
- The LLVM backend passes all our tests.
- The debug symbols are coming soon so the stack traces should become usable.
- The build-time is improved quite a bit.

We are currently working on improving testing on mobile devices. 

I was wondering about the artifact size, was it 200 MB with JavaFX or just your code? 
Asking because a lot of the overhead comes from JavaFX at the moment. For the shared library use case @sirthias is referring to, I don't expect the binary to be large.

**Comment by CedricGatay** [comment] 2020-05-04 09:26
Glad that most of the issues are being fixed @vjovanov  ! 

The binary size was coming from transitive dependencies I guess from the project I was building to native (https://github.com/ACINQ/eclair) without the GUI part (so without JFX parts). But it gets scala + akka as a base.

**Comment by vjovanov** [comment] 2020-05-04 09:29
> It would be great though to have proper threading support. Do you have any perspective on that? Did you encounter any issues wrt thread scheduling/concurrency abstractions?

You can both start new threads and use the OS threads that are passed through the entry points. The memory model is the same as on the JVM.

**Comment by sirthias** [comment] 2020-05-04 09:45
> The memory model is the same as on the JVM.

Thank you, @vjovanov, that's what I assumed, as otherwise lots of things would fall apart.

**Comment by nhoughto** [comment] 2020-05-04 09:46
The shared library is super interesting, compelling use case for us would be no jni etc. like kotlin mpp but without having to deal with kotlin migrations 🤔

https://kotlinlang.org/docs/reference/multiplatform.html

**Comment by ScalaWilliam** [comment] 2021-03-20 22:12
@sanzinger @vjovanov  when I google 'graalvm ios', I get to this github issue, and I get the impression that iOS would not be supported by GraalVM.

But then there are pages like this https://github.com/lazar-mitrovic/GraalREPL

What is the situation? Can you share a clarification? It seems users could be very confused. 

I only know to look into this beyond this GitHub issue because I am familiar with JavaFX/ScalaFX, Gluon and the iOS announcements earlier.

**Comment by frank-dspeed** [comment] 2021-08-19 13:19
@ScalaWilliam long story short it is working already but there are edge cases like os specific parts for example "Only Interpreter Mode" that is what your seeing in that example 

So iOS is fully supported including webview via javaFx and so on.

I am Not aware of the shared lib stuff but for application development it is working.

**Comment by insinfo** [comment] 2022-05-02 19:53
is it already possible to compile a native shared library written in java for iOS with GraalVM?

**Comment by frank-dspeed** [comment] 2022-05-03 04:39
@insinfo your correct this is possible but not supported at present but the moving parts are in place even jvm on jvm works in android

**Comment by LifeIsStrange** [comment] 2022-07-31 13:25
It seems support for shared libraries on IOS is there! (not yet upstreamed) 
https://github.com/gluonhq/substrate/commit/a1a6a37826bd5139b0905064d436d7b07da1ccbb
@vjovanov @jperedadnr
Hope that means we are not far from a well working IOS support and from upstreaming to improve the default experience.

**Comment by frank-dspeed** [comment] 2022-08-01 03:57
@LifeIsStrange that is only a example that builds for ios everything is from graalvm upstream glueon did not invent anything there :)

**Comment by hooji** [comment] 2025-02-03 20:55
So, can we write a full app in Java (including access to Apple APIs) and compile to native?  If so, any tutorials/examples?
