### ISSUE TITLE
[GR-54058] Serialization of float[] or other arrays is not supported in Native Image

### ISSUE THREAD

**Issue by imgoby** [oracle/graal#8470] opened 2024-02-29 03:12 UTC
1. OS: Centos 7.9

2. jdk version:
```
sdk install java 22.3.r17-nik
sdk use java 22.3.r17-nik
sdk default java 22.3.r17-nik
```

3.code:  HelloWorld.java

```
import sun.reflect.ReflectionFactory;
import java.io.ObjectStreamClass;
import java.io.Serializable;
import java.lang.reflect.Constructor;
import java.lang.reflect.Field;
import java.lang.reflect.Method;

public class HelloWorld {
     public static void main(String[] args) throws Exception{

        Class clazz= float[].class;
        Constructor c = java.lang.Object.class.getDeclaredConstructor((Class[]) null);
        c = ReflectionFactory.getReflectionFactory().newConstructorForSerialization(clazz, c);
         System.out.println("Hello, Native World!");
     }
 }

```

serialization-config.json is follow:
```
[
  {
    "name": "[F"
  },
  {
    "name": "float[]"
  },
  {
    "name": "java.lang.Float[]"
  },
  {
    "name": "java.lang.Float"
  }
]
```
or :
```
{
  "types": [
  {
    "name": "[F"
  },
  {
    "name": "float[]"
  },
  {
    "name": "java.lang.Float[]"
  },
  {
    "name": "java.lang.Float"
  }],
  "lambdaCapturingTypes": [],
  "proxies": []
}
```

4. step:
javac HelloWorld.java
native-image HelloWorld  --no-fallback -H:ReflectionConfigurationFiles=r.json -H:SerializationConfigurationFiles=serialization-config.json

Exception is as as follow:

```
[root@localhost example]# ./helloworld 
Exception in thread "main" com.oracle.svm.core.jdk.UnsupportedFeatureError: SerializationConstructorAccessor class not found for declaringClass: [F (targetConstructorClass: java.lang.Object). Usually adding [F to serialization-config.json fixes the problem.
	at org.graalvm.nativeimage.builder/com.oracle.svm.core.util.VMError.unsupportedFeature(VMError.java:92)
	at org.graalvm.nativeimage.builder/com.oracle.svm.core.reflect.serialize.SerializationSupport.getSerializationConstructorAccessor(SerializationSupport.java:143)
	at java.base@17.0.10/jdk.internal.reflect.MethodAccessorGenerator.generateSerializationConstructor(MethodAccessorGenerator.java:61)
	at java.base@17.0.10/jdk.internal.reflect.ReflectionFactory.generateConstructor(ReflectionFactory.java:463)
	at java.base@17.0.10/jdk.internal.reflect.ReflectionFactory.newConstructorForSerialization(ReflectionFactory.java:376)
	at jdk.unsupported@17.0.10/sun.reflect.ReflectionFactory.newConstructorForSerialization(ReflectionFactory.java:100)
	at HelloWorld.main(HelloWorld.java:13)


```

**Comment by fernando-valdez** [comment] 2024-03-01 02:31
Hi. Can you please share more details about this issue? what version of GraalVM are you using? how did you create the native image? what OS are you using? 
And finally, share the steps we need to take to reproduce this issue.

**Comment by imgoby** [comment] 2024-03-01 02:39
OS: Centos 7.9
I use native-maven-plugin in spring boot application

 ```
<plugin>
                        <groupId>org.graalvm.buildtools</groupId>
                        <artifactId>native-maven-plugin</artifactId>
                        <version>${native-maven-plugin.version}</version>
                        <configuration>
                            <skip>true</skip>
                            <classesDirectory>${project.build.outputDirectory}</classesDirectory>
                            <metadataRepository>
                                <enabled>true</enabled>
                            </metadataRepository>
                            <requiredVersion>22.3</requiredVersion>
                            <buildArgs>
                                 -H:+AddAllCharsets  --add-modules=jdk.incubator.foreign --add-opens=java.base/java.lang=ALL-UNNAMED --add-opens=java.base/java.math=ALL-UNNAMED --add-opens=java.base/java.util=ALL-UNNAMED --add-opens=java.base/java.util.concurrent=ALL-UNNAMED  --add-opens=java.base/java.text=ALL-UNNAMED --add-opens=java.sql/java.sql=ALL-UNNAMED --add-opens=java.base/java.util.concurrent.atomic=ALL-UNNAMED --add-opens=java.base/java.net=ALL-UNNAMED
                            </buildArgs>
                        </configuration>
                        <executions>
                            <execution>
                                <id>add-reachability-metadata</id>
                                <goals>
                                    <goal>add-reachability-metadata</goal>
                                </goals>
                            </execution>
                        </executions>
                    </plugin>
```
2. jdk version:
```
sdk install java 22.3.r17-nik
sdk use java 22.3.r17-nik
sdk default java 22.3.r17-nik
```

3.code:

        ```
Class clazz= float[].class;
        Class curCl = clazz;
        while (Serializable.class.isAssignableFrom(curCl)) {
            curCl = curCl.getSuperclass();

            if (curCl == null) {

                return ;
            }
        }

        Constructor c = curCl.getDeclaredConstructor((Class[]) null);
        c = ReflectionFactory.getReflectionFactory().newConstructorForSerialization(clazz, c);
```

**Comment by fniephaus** [comment] 2024-03-01 17:24
@imgoby could you please try with Oracle GraalVM for JDK 17 (`sdk install java 17.0.10-graal`), or CE? Maybe this issue was already fixed in that release.

**Comment by imgoby** [comment] 2024-03-02 01:36
I try to use this version: java 17.0.10-graal

the problem is the same.


![1709343336117](https://github.com/oracle/graal/assets/27885492/840a1b02-490f-4dfe-8db2-b33cd26336fb)

**Comment by imgoby** [comment] 2024-03-04 01:36
@fniephaus 
@fernando-valdez Is there any ways?

**Comment by mukel** [comment] 2024-03-04 07:14
Looks like your `serialization-config.json` doesn't follow the JSON schema described in https://www.graalvm.org/latest/reference-manual/native-image/metadata/#serialization-metadata-in-json  (types must be declared under the "types" key)
Something like this may work:
```JSON
{
  "types": [
    { "name": "[F" }
  ]
}
```

**Comment by imgoby** [comment] 2024-03-04 08:12
I tried this way before.It doesn't work. @mukel

**Comment by fernando-valdez** [comment] 2024-03-04 19:34
@imgoby, can you please confirm is this is happening in the non-community edition? please try `java 17.0.10-graal` instead of `java 17.0.9-graalce`

**Comment by imgoby** [comment] 2024-03-05 01:31
Yes, it is indeed。
neither  java 17.0.10-graal or java 17.0.9-graalce,It has the same exception.

this is a small project,you can reproduce it:

https://github.com/imgoby/graalvm-array-serialization

**Comment by imgoby** [comment] 2024-05-07 01:15
Is there any progress?

**Comment by fernando-valdez** [comment] 2024-05-14 02:35
I shared this issue with the native image team. Here is the internal ticket GR-54058

**Closed** 2024-09-24 14:01 UTC
Labels: bug, native-image
