### ISSUE TITLE
LLVM for ARM64

### ISSUE THREAD

**Issue by johanvos** [oracle/graal#1090] opened 2019-03-20 15:56 UTC
I added some arm64 specific code for the LLVM backend to https://github.com/johanvos/graal/tree/llvmarm64 (most of the changes coming from https://github.com/loicottet/graal/tree/lottet/aarch64-squashed)

When trying to compile HelloWorld using
mx native-image -H:CompilerBackend=llvm -H:-MultiThreaded -H:-SpawnIsolates -Dsvm.platform=org.graalvm.nativeimage.Platform\$LINUX_AArch6
4 -H:+ReportExceptionStackTraces -cp . HelloWorld

However, it generates invalid llvm bitcode.
I get the following issue in LLVMCompilerBackend.emitBackEnd:

```
 Both operands to a binary operator are not of the same type!
  %145 = sub i32 53, i64 %144

[skip]
Fatal error: org.graalvm.compiler.debug.GraalError: LLVM module verification failed
        at method: void com.oracle.svm.core.handles.ObjectHandlesImpl.destroy(ObjectHandle)  [Direct call from void IsolateEnterStub.JNIFunctions_DeleteGlobalRef_c71a3e460362f01015ed635c54f794c25408f058(JNIEnvironment, JNIObjectHandle)]
        at org.graalvm.compiler.core.llvm.LLVMGenerationResult.getBitcode(LLVMGenerationResult.java:90)
        at org.graalvm.compiler.core.llvm.LLVMGenerationResult.populate(LLVMGenerationResult.java:155)
        at com.oracle.svm.core.graal.llvm.SubstrateLLVMGenerationResult.populate(SubstrateLLVMGenerationResult.java:53)
        at org.graalvm.compiler.core.llvm.LLVMCompilerBackend.emitBackEnd(LLVMCompilerBackend.java:45)
        at com.oracle.svm.core.graal.llvm.SubstrateLLVMBackend.emitBackEnd(SubstrateLLVMBackend.java:113)
        at jdk.internal.vm.compiler/org.graalvm.compiler.core.GraalCompiler.compile(GraalCompiler.java:145)

```

**Comment by loicottet** [comment] 2019-03-22 08:50
I suspect the `numberOfLeadingZeros` intrinsic in `ObjectHandlesImpl.getBucketIndex` returning a long instead of the expected int is the cause of this. I have pushed a patch to https://github.com/loicottet/graal/tree/lottet/aarch64-squashed, it should do the trick.

**Comment by bobmcwhirter** [comment] 2019-04-03 18:16
fwiw, all of the `aarch64-squashed` bits have been merged into master now.

Pull https://github.com/oracle/graal/pull/1128 is still outstanding.  

Dunno if this affects LLVM at all though.

**Comment by vjovanov** [comment] 2019-08-29 06:21
Yes, we have made it possible. The PR in LLVM is (not) being reviewed; it would be good if you would ask for it on the LLVM mailing list and review. 

All the details are here: 

  https://github.com/oracle/graal/blob/master/substratevm/LLVM-NEW-BACKEND.md

It works very well and we will have the complete tests for native-image running on ARM64.

**Comment by vjovanov** [comment] 2022-11-10 12:56
This has been implemented successfully.

**Closed by vjovanov** 2022-11-10 12:56 UTC
