### ISSUE TITLE
native-image-agent does not merge reflect-config.json as expected

### ISSUE THREAD

**Issue by belu** [oracle/graal#3192] opened 2021-02-07 08:48 UTC
**Describe the issue**
For generating the native build configs I use the `native-image-agent` with `config-merge-dir`.
As there are different code paths in the application I run it twice. In the first run, `java.util.Optional` is added with the field `value` and `allowUnsafeAccess: true`. However, on the second run the `allowUnsafeAccess` is removed.

**Steps to reproduce the issue**
1. `git clone https://github.com/belu/graalvm-native-merge-config-issue.git`
2. `mvn clean package`
3. `java -agentlib:native-image-agent=config-merge-dir=config -jar target/*-runner.jar`
4. Stop the application after a few seconds by pressing CTRL+C
5. `grep -3 "java.util.Optional" config/reflect-config.json`
6. Note the field with `allowUnsafeAccess`
7. `java -agentlib:native-image-agent=config-merge-dir=config -jar target/*-runner.jar`
8. Again stop the application by pressing CTRL+C
9. `grep -3 "java.util.Optional" config/reflect-config.json`
10. The `allowUnsafeAccess` is gone.

**Describe GraalVM and your environment:**
 - GraalVM version **GraalVM CE 21.1.0-dev (build 11.0.10+8-jvmci-21.0-b06)**
 - JDK major version: **11**
 - OS: **Linux**
 - Architecture: **AMD64**

**More details**
Note that the built native executable does not run with this reproducer. However, with the version I got here it does not start with the merged configs. Only if I add the allowUnsafeAccess manually then the native executable runs fine.

If you want to reproduce again, please delete the `config` and `data` directory first.

**Comment by oubidar-Abderrahim** [comment] 2021-02-08 12:35
Could you please include the native-image command you use to generate the native-image?
Does this behavior occur with GraalVM CE java11 21.0.0 or 20.3.0?

**Comment by belu** [comment] 2021-02-08 17:44
@oubidar-Abderrahim 

The command to generate the image is:
`mvn package -Pnative`

As stated above, the reproducer does not contain all the code to make the native-image run. Some Substitutions are missing, too. However, the reproducer shows the wrongly generated `reflect-config.json`.

Using GraalVM CE 21.1.0-dev (build 11.0.10+8-jvmci-21.0-b06).

**Comment by oubidar-Abderrahim** [comment] 2021-02-23 09:43
Tracked internally at GR-29319

**Comment by belu** [comment] 2021-02-27 17:59
@oubidar-Abderrahim 
Fyi, just pushed the code (substitutions) so you can build & run the application. Please see the updated README.md in the
project on how to reproduce the issue.

**Comment by gradinac** [comment] 2021-03-01 18:03
Hey @belu!
This seems to be reproducible even without configuration merging - in my case, it was enough to leave the app running for a bit more. I suspect I've found the culprit - once the fix has been reviewed and merged, I'll let you know. If you also wish to try the fix out, I can either create a public PR or I can give you the diff that you can apply to Graal.

**Comment by belu** [comment] 2021-03-01 18:15
@gradinac
Great! No hurry, I will try it with the next CE release that contains the fix.

**Comment by gradinac** [comment] 2021-03-02 14:37
Hey @belu!
The fix for the issue has been merged to master (https://github.com/oracle/graal/commit/d704ad5be087ee8a4f71f215aac7217430d9c079). If you want, you can test it once the latest GraalVM CE dev build is out here: https://github.com/graalvm/graalvm-ce-dev-builds/releases (the latest dev builds do not seem to be available right now, but this is a temporary outage).

**Comment by belu** [comment] 2021-03-06 15:56
@gradinac 
Just tested with the latest dev build and confirm the issue is fixed. Thanks!

**Comment by gradinac** [comment] 2021-03-06 18:29
Hey @belu, I'm glad to hear that! :)
I'll close this issue - if you hit any other problems, please let us know.

**Closed by gradinac** 2021-03-06 18:29 UTC
Labels: agent, bug
