### ISSUE TITLE
[native-image] UnsupportedFeatureError: Unimplemented: sun.nio.ch.DatagramChannelImpl.send0(boolean, FileDescriptor, long, int, InetAddress, int)

### ISSUE THREAD

**Issue by wkgcass** [oracle/graal#971] opened 2019-02-10 14:56 UTC
Hi, I'm trying to build an app with `native-image`.  
But I got this error when calling this method: `int DatagramChannel.send(ByteBuffer, SocketAddress)`.

The java lib part of the stacktrace:

```
com.oracle.svm.core.jdk.UnsupportedFeatureError: Unimplemented: sun.nio.ch.DatagramChannelImpl.send0(boolean, FileDescriptor, long, int, InetAddress, int)
	at com.oracle.svm.core.util.VMError.unsupportedFeature(VMError.java:109)
	at sun.nio.ch.DatagramChannelImpl.send0(DatagramChannelImpl.java:114)
	at sun.nio.ch.DatagramChannelImpl.sendFromNativeBuffer(DatagramChannelImpl.java:521)
	at sun.nio.ch.DatagramChannelImpl.send(DatagramChannelImpl.java:483)
	at sun.nio.ch.DatagramChannelImpl.send(DatagramChannelImpl.java:462)
```

Is there any plan to support it in the future?

**Comment by wkgcass** [comment] 2019-02-10 14:58
The version I am using is:

```
native-image --version
GraalVM Version 1.0.0-rc12
```

**Comment by cstancu** [comment] 2019-02-10 20:47
@wkgcass `sun.nio.ch.DatagramChannelImpl` is currently not currently supported, however, we plan to support it in the future. This is a duplicate of https://github.com/oracle/graal/issues/474.

**Closed by cstancu** 2019-02-10 20:47 UTC
