### ISSUE TITLE
Native Image of Micronaut App which uses Apache POI fails at runtime

### ISSUE THREAD

**Issue by sdelamo** [oracle/graal#1993] opened 2019-12-16 11:50 UTC
Steps to reproduce. 

Clone [micronaut-guides/micronaut-file-download-excel repository and checkout graalvm branch](https://github.com/micronaut-guides/micronaut-file-download-excel/tree/graalvm) branch. 

Generate the native image:

```
$ sdk use java 19.3.0.r8-grl 
$ ./gradlew clean :complete:assemble
$ % native-image --no-server -cp build/libs/complete-0.1-all.jar
```

Execute the native image:

```
$ ./micronautguide
```

Navigate to localhost:8080 click the `Excel` button. 

You will see: 

```
12:28:33.671 [pool-2-thread-2] ERROR i.m.h.s.netty.RoutingInBoundHandler - Unexpected error occurred: null
java.lang.ExceptionInInitializerError: null
	at com.oracle.svm.core.hub.ClassInitializationInfo.initialize(ClassInitializationInfo.java:290)
	at java.lang.Class.ensureInitialized(DynamicHub.java:475)
	at org.openxmlformats.schemas.spreadsheetml.x2006.main.CTWorkbook$Factory.newInstance(Unknown Source)
	at org.apache.poi.xssf.usermodel.XSSFWorkbook.onWorkbookCreate(XSSFWorkbook.java:456)
	at org.apache.poi.xssf.usermodel.XSSFWorkbook.<init>(XSSFWorkbook.java:259)
	at org.apache.poi.xssf.usermodel.XSSFWorkbook.<init>(XSSFWorkbook.java:253)
	at org.apache.poi.xssf.usermodel.XSSFWorkbook.<init>(XSSFWorkbook.java:241)
	at builders.dsl.spreadsheet.builder.poi.PoiSpreadsheetBuilder.create(PoiSpreadsheetBuilder.java:18)
	at example.micronaut.BookExcelServiceImpl.excelFileFromBooks(BookExcelServiceImpl.java:23)
	at example.micronaut.HomeController.excel(HomeController.java:31)
	at example.micronaut.$HomeControllerDefinition$$exec2.invokeInternal(Unknown Source)
	at io.micronaut.context.AbstractExecutableMethod.invoke(AbstractExecutableMethod.java:145)
	at io.micronaut.context.DefaultBeanContext$BeanExecutionHandle.invoke(DefaultBeanContext.java:2844)
	at io.micronaut.web.router.AbstractRouteMatch.execute(AbstractRouteMatch.java:235)
	at io.micronaut.web.router.RouteMatch.execute(RouteMatch.java:122)
	at io.micronaut.http.server.netty.RoutingInBoundHandler.lambda$buildResultEmitter$17(RoutingInBoundHandler.java:1400)
	at io.reactivex.internal.operators.flowable.FlowableCreate.subscribeActual(FlowableCreate.java:71)
	at io.reactivex.Flowable.subscribe(Flowable.java:14918)
	at io.reactivex.Flowable.subscribe(Flowable.java:14865)
	at io.micronaut.reactive.rxjava2.RxInstrumentedFlowable.subscribeActual(RxInstrumentedFlowable.java:68)
	at io.reactivex.Flowable.subscribe(Flowable.java:14918)
	at io.reactivex.internal.operators.flowable.FlowableMap.subscribeActual(FlowableMap.java:37)
	at io.reactivex.Flowable.subscribe(Flowable.java:14918)
	at io.reactivex.Flowable.subscribe(Flowable.java:14865)
	at io.micronaut.reactive.rxjava2.RxInstrumentedFlowable.subscribeActual(RxInstrumentedFlowable.java:68)
	at io.reactivex.Flowable.subscribe(Flowable.java:14918)
	at io.reactivex.internal.operators.flowable.FlowableSwitchIfEmpty.subscribeActual(FlowableSwitchIfEmpty.java:32)
	at io.reactivex.Flowable.subscribe(Flowable.java:14918)
	at io.reactivex.Flowable.subscribe(Flowable.java:14865)
	at io.micronaut.reactive.rxjava2.RxInstrumentedFlowable.subscribeActual(RxInstrumentedFlowable.java:68)
	at io.reactivex.Flowable.subscribe(Flowable.java:14918)
	at io.reactivex.Flowable.subscribe(Flowable.java:14865)
	at io.micronaut.reactive.rxjava2.RxInstrumentedFlowable.subscribeActual(RxInstrumentedFlowable.java:68)
	at io.reactivex.Flowable.subscribe(Flowable.java:14918)
	at io.reactivex.internal.operators.flowable.FlowableSwitchMap.subscribeActual(FlowableSwitchMap.java:49)
	at io.reactivex.Flowable.subscribe(Flowable.java:14918)
	at io.reactivex.Flowable.subscribe(Flowable.java:14865)
	at io.micronaut.reactive.rxjava2.RxInstrumentedFlowable.subscribeActual(RxInstrumentedFlowable.java:68)
	at io.reactivex.Flowable.subscribe(Flowable.java:14918)
	at io.reactivex.Flowable.subscribe(Flowable.java:14868)
	at io.micronaut.http.context.ServerRequestTracingPublisher.lambda$subscribe$0(ServerRequestTracingPublisher.java:52)
	at io.micronaut.http.context.ServerRequestContext.with(ServerRequestContext.java:52)
	at io.micronaut.http.context.ServerRequestTracingPublisher.subscribe(ServerRequestTracingPublisher.java:52)
	at io.reactivex.internal.operators.flowable.FlowableFromPublisher.subscribeActual(FlowableFromPublisher.java:29)
	at io.reactivex.Flowable.subscribe(Flowable.java:14918)
	at io.reactivex.Flowable.subscribe(Flowable.java:14865)
	at io.micronaut.reactive.rxjava2.RxInstrumentedFlowable.subscribeActual(RxInstrumentedFlowable.java:68)
	at io.reactivex.Flowable.subscribe(Flowable.java:14918)
	at io.reactivex.Flowable.subscribe(Flowable.java:14865)
	at io.reactivex.internal.operators.flowable.FlowableSubscribeOn$SubscribeOnSubscriber.run(FlowableSubscribeOn.java:82)
	at io.reactivex.internal.schedulers.ExecutorScheduler$ExecutorWorker$BooleanRunnable.run(ExecutorScheduler.java:288)
	at io.reactivex.internal.schedulers.ExecutorScheduler$ExecutorWorker.run(ExecutorScheduler.java:253)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
	at com.oracle.svm.core.thread.JavaThreads.threadStartRoutine(JavaThreads.java:479)
	at com.oracle.svm.core.posix.thread.PosixJavaThreads.pthreadStartRoutine(PosixJavaThreads.java:193)
Caused by: java.lang.RuntimeException: Cannot load SchemaTypeSystem. Unable to load class with name schemaorg_apache_xmlbeans.system.sD023D6490046BA0250A839A9AD24C443.TypeSystemHolder. Make sure the generated binary files are on the classpath.
	at org.apache.xmlbeans.XmlBeans.typeSystemForClassLoader(XmlBeans.java:788)
	at org.openxmlformats.schemas.spreadsheetml.x2006.main.CTWorkbook.<clinit>(Unknown Source)
	at com.oracle.svm.core.hub.ClassInitializationInfo.invokeClassInitializer(ClassInitializationInfo.java:350)
	at com.oracle.svm.core.hub.ClassInitializationInfo.initialize(ClassInitializationInfo.java:270)
	... 56 common frames omitted
Caused by: java.lang.ClassNotFoundException: schemaorg_apache_xmlbeans.system.sD023D6490046BA0250A839A9AD24C443.TypeSystemHolder
	at com.oracle.svm.core.hub.ClassForNameSupport.forName(ClassForNameSupport.java:60)
	at java.lang.ClassLoader.loadClass(Target_java_lang_ClassLoader.java:131)
	at org.apache.xmlbeans.XmlBeans.typeSystemForClassLoader(XmlBeans.java:774)
	... 59 common frames omitted
```

This app is using [Spreadsheet builder](http://spreadsheet.dsl.builders) which has a transitive dependency to Apache POI. Probably the most common dependency to work with Excel files. 

## Notes: 

I provided reflection configuration file for [XMLBeans](https://xmlbeans.apache.org).

It is under `complete/src/main/graal/reflect.json` with  packages `org.apache.xmlbeans` and `org.openxmlformats` entries obtained with the tracing agent. 

My `native-image.properties` files look like: 

`src/main/resources/META-INF/native-image/example.micronaut/micronautguide/native-image.properties`

```
Args = -H:IncludeResources=logback.xml|application.yml|.*/*.html \
       -H:Name=micronautguide \
       -H:IncludeResourceBundles=org.apache.xmlbeans.impl.regex.message \
       -H:Class=example.micronaut.Application 
```

I needed to specify `IncludeResourceBundles` to get rid of: 

```
Caused by: java.lang.RuntimeException: Installation Problem???  Couldn't load messages: Resource bundle not found org.apache.xmlbeans.impl.regex.message. Register the resource bundle using the option -H:IncludeResourceBundles=org.apache.xmlbeans.impl.regex.message.
	at org.apache.xmlbeans.impl.regex.RegexParser.setLocale(RegexParser.java:88)
	at org.apache.xmlbeans.impl.regex.RegexParser.<init>(RegexParser.java:78)
	at org.apache.xmlbeans.impl.regex.ParserForXMLSchema.<init>(ParserForXMLSchema.java:28)
	at org.apache.xmlbeans.impl.regex.RegularExpression.setPattern(RegularExpression.java:2996)
	at org.apache.xmlbeans.impl.regex.RegularExpression.setPattern(RegularExpression.java:3009)
	at org.apache.xmlbeans.impl.regex.RegularExpression.<init>(RegularExpression.java:2975)
	at org.apache.xmlbeans.impl.regex.SchemaRegularExpression.<init>(SchemaRegularExpression.java:27)
	at org.apache.xmlbeans.impl.regex.SchemaRegularExpression.<init>(SchemaRegularExpression.java:23)
	at org.apache.xmlbeans.impl.regex.SchemaRegularExpression$1.<init>(SchemaRegularExpression.java:44)
	at org.apache.xmlbeans.impl.regex.SchemaRegularExpression.buildKnownPatternMap(SchemaRegularExpression.java:43)
	at org.apache.xmlbeans.impl.regex.SchemaRegularExpression.<clinit>(SchemaRegularExpression.java:38)
	at com.oracle.svm.core.hub.ClassInitializationInfo.invokeClassInitializer(ClassInitializationInfo.java:350)
	at com.oracle.svm.core.hub.ClassInitializationInfo.initialize(ClassInitializationInfo.java:270)
	... 68 common frames omitted
```

Any ideas?

**Comment by vjovanov** [comment] 2019-12-20 18:04
OK, this seems as a configuration issue. The first thing I did is execute the program with the agent:
```
$JAVA_HOME/bin/java -agentlib:native-image-agent=config-output-dir=/tmp/excel -jar ./complete/build/libs/complete-0.1-all.jar
```
and after building an image with `-H:ConfigurationFileDirectories=/tmp/excel` we unfortunately get a failure due to an issue in routing:
```
{"message":"More than 1 route matched the incoming request. The following routes matched /: GET - /, GET - /","_links":{"self":{"href":"/","templated":false}}}
```
This is caused by the duplication of files in the resource bundles. @peter-hofer  I think the image should work the same if there are multiple resource definitions?
Now, I apply the following diff to the resources: 
```
2a3
>     {"pattern":"\\QMETA-INF/http/mime.types\\E"}, 
3a5,9
>     {"pattern":"\\QMETA-INF/services/io.micronaut.context.env.PropertySourceLoader\\E"}, 
>     {"pattern":"\\QMETA-INF/services/io.micronaut.core.beans.BeanIntrospectionReference\\E"}, 
>     {"pattern":"\\QMETA-INF/services/io.micronaut.http.HttpResponseFactory\\E"}, 
>     {"pattern":"\\QMETA-INF/services/io.micronaut.inject.BeanConfiguration\\E"}, 
>     {"pattern":"\\QMETA-INF/services/io.micronaut.inject.BeanDefinitionReference\\E"}, 
6a13
>     {"pattern":"\\Qapplication.yml\\E"}, 
9a17
>     {"pattern":"\\Qlogback.xml\\E"}, ```
and build an image. We reach way further, but the image now fails with `java.lang.ClassNotFoundException: com.sun.org.apache.xerces.internal.jaxp.DocumentBuilderFactoryImpl`. The reason is that the agent does not track this part of the JDK although it should (we are working on it). We can now add the following to the reflection config files: 
```
{
  "name":"com.sun.org.apache.xalan.internal.xsltc.trax.TransformerFactoryImpl",
  "methods":[{"name":"<init>","parameterTypes":[] }]
},
{
  "name":"com.sun.org.apache.xerces.internal.jaxp.DocumentBuilderFactoryImpl",
  "methods":[{"name":"<init>","parameterTypes":[] }]
},
{
  "name":"com.sun.org.apache.xerces.internal.jaxp.SAXParserFactoryImpl",
  "methods":[{"name":"<init>","parameterTypes":[] }]
},
```
Then, I hit the issue that the agent does not collect the resource bundles (known issue, working on it). This can be fixed by adding:`-H:IncludeResourceBundles=com.sun.org.apache.xml.internal.serializer.utils.SerializerMessages`

Then, the agent seems to have missed the `output_xml.properties`. If we add them manually, our resource handling doesn't seem to fetch them. I will investigate this futher next week.

**Comment by peter-hofer** [comment] 2020-01-07 12:49
> OK, this seems as a configuration issue. [...] This is caused by the duplication of files in the resource bundles. @peter-hofer I think the image should work the same if there are multiple resource definitions?

I'm not too familiar with the resource (bundle) code, and I feel like there's some missing context here (and with the diff you pasted next).

> Now, I apply the following diff to the resources:[...] and build an image. We reach way further, but the image now fails with `java.lang.ClassNotFoundException: com.sun.org.apache.xerces.internal.jaxp.DocumentBuilderFactoryImpl`. The reason is that the agent does not track this part of the JDK although it should (we are working on it).

Indeed, #1982.

> We can now add the following to the reflection config files: [...] Then, I hit the issue that the agent does not collect the resource bundles (known issue, working on it). This can be fixed by adding:`-H:IncludeResourceBundles=com.sun.org.apache.xml.internal.serializer.utils.SerializerMessages`

Indeed, #1880.

> Then, the agent seems to have missed the `output_xml.properties`. If we add them manually, our resource handling doesn't seem to fetch them. I will investigate this futher next week.

Please keep us posted. It can also be that this file isn't accessed during the run with the agent, or in a different way. It can be useful to check the agent's raw trace file.

**Comment by eginez** [comment] 2020-01-22 00:42
@sdelamo On top of the changes describe above. For java 8 you need 3 more configuration steps that will allow you to run the service
1. Add `resources.jar` to your native-image class path eg:
```
native-image ... -cp $GRAAL_HOME/jre/lib/resources.jar
```
2. Add the properties file required by java.xml package to your `resources-config.json` file eg:
``` 
    {"pattern":"com/sun/org/apache/xml/internal/serializer/output_xml.properties"}
```
3. Finally add all charsets to native-image build process. This is necessary for java.xml packages
eg
```
-H:+AddAllCharsets 
```
That should allow you to run with java 8.

For java 11, the necessary resources are inside the `java.xml` module which does not expose the necessary resources by default.  We are still working on java 11 module support and currently we don't have a way to specify arbitrary modules during image creation, making this bug tricky on java 11.

**Comment by boonyasukd** [comment] 2020-01-22 06:40
Hi all,
I also previously reported a related issue back in Sep 2019 (#1648), and even back then it seems the JDK resource hasn't been properly picked up when attempting to create a native image (specifically, the resource is: `com/sun/org/apache/xml/internal/serializer/output_xml.properties`). So if the team can solve the problem, my issue can also be closed.

**Comment by eginez** [comment] 2020-01-29 17:55
@boonyasukd that's correct native-image was not find the resources because they were not in the classpath. This has been fixed with https://github.com/oracle/graal/commit/563408ea34f8593f488e1b8cd6d7101effb91f2d

**Closed by eginez** 2020-01-29 17:55 UTC
Labels: bug, native-image
