### ISSUE TITLE
[svm] truffleruby can't start when /dev/shm is not mounted

### ISSUE THREAD

**Issue by liamwhite** [oracle/graal#305] opened 2018-02-19 22:42 UTC
```
$ strace graalvm-0.31/bin/ruby --native -e 'Process.exit(0)'
execve("graalvm-0.31/bin/ruby", ["graalvm-0.31/bin/ruby", "--native", "-e", "Process.exit(0)"], [/* 22 vars */]) = 0

...

statfs("/dev/shm/", {f_type=TMPFS_MAGIC, f_bsize=4096, f_blocks=2044018, f_bfree=2044018, f_bavail=2044018, f_files=2044018, f_ffree=2043495, f_fsid={val=[0, 0]}, f_namelen=255, f_frsize=4096, f_flags=ST_VALID|ST_NOSUID|ST_RELATIME}) = 0
futex(0x7f0e38205330, FUTEX_WAKE_PRIVATE, 2147483647) = 0
open("/dev/shm/sem.cSunMiscSignal-3926", O_RDWR|O_NOFOLLOW) = -1 ENOENT (No such file or directory)
getpid()                                = 3926
lstat("/dev/shm/usldvC", 0x7ffd971943f0) = -1 ENOENT (No such file or directory)
open("/dev/shm/usldvC", O_RDWR|O_CREAT|O_EXCL, 0600) = -1 EACCES (Permission denied)
write(2, "Util_sun_misc_Signal.ensureIniti"..., 71) = 71

Util_sun_misc_Signal.ensureInitialized: CSunMiscSignal.create() failed.
```

Running on the JVM works.
Complete backtrace [here](https://gist.github.com/liamwhite/affa7d31550269881a024b2fb48fcad6).

**Comment by chrisseaton** [comment] 2018-02-19 22:43
Posted here because we think it's a problem with the SVM implementation of signals, rather than a TruffleRuby problem.

**Comment by Peter-B-Kessler** [comment] 2019-02-04 23:57
What is the operating system on which this failure occurs?  The SubstrateVM code is trying to make a `sem_open` syscall, but the kernel says that syscall is not implemented ("errno: 38  Function not implemented").   We test on Darwin and some Linuxes, and seem to be able to create kernel semaphores.  

Or, you might not have `O_RDWR|O_CREAT|O_EXCL` permissions on `/dev/shm/usldvC`, ("EACCES (Permission denied)") but I do not know why that would be.  My visibility ends where the syscall is made, and all I get back is the `errno`.  Your `strace` shows more details of our syscall, but how that is connected to `/dev/shm/usldvC` is still a mystery.  

The "cSunMiscSignal-3926" in there is the name SubstrateVM makes up for the semaphore for your process.  (You show `getpid()` returning `3926`.)  But in the SubstrateVM code (https://github.com/oracle/graal/blob/master/substratevm/src/com.oracle.svm.native.libchelper/src/cSunMiscSignal.c#L115) I see the `getpid()` call happening *before* the call to `sem_open` (with the pid encoded in the name).  Maybe the `strace` output is jumbled?  The other syscall in that path is `sem_unlink` (with the same semaphore name as was used for the `sem_open`).  But if your kernel implements `sem_open` I would expect it to implement `sem_unlink`.

**Comment by Peter-B-Kessler** [comment] 2019-02-05 21:53
I *think* my `strace` shows:
```
    # Checking that "/dev/shm" exists: which it does.
statfs("/dev/shm", ....) = 0
    # Checking if "/dev/shm/sem.cSunMiscSignal-66724" already exists, which it does not.
open("/dev/shm/sem.cSunMiscSignal-66724", O_RDWR|O_NOFOLLOW) = -1
    # Checking if a temporary file in "/dev/shm" exists, which it does not.
lstat("/dev/shm/sem.7SGlpJ", 0x7ffe8acbe6b0) = -1
    # Opening the temporary file, returning file descriptor 9.
open("/dev/shm/sem.7SGlpJ", O_RDWR|O_CREAT|O_EXCL, 0600) = 9
    # Writing the contents of the temporary file, which works.
write(9, "\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0", 32) = 32
    # Map the file at file descriptor 9 into the address space.
mmap(NULL, 32, PROT_READ|PROT_WRITE, MAP_SHARED, 9, 0) = 0x7f4573fd8000
    # Linking the temporary file under its real name, which works.
link("/dev/shm/sem.7SGlpJ", "/dev/shm/sem.cSunMiscSignal-66724") = 0
    # Unlinking the temporary file name, so that 
    # the file is only accessible under its real name.
unlink("/dev/shm/sem.7SGlpJ") = 0
    # Closing the temporary file.
close(9) = 0
    # Unlinking the file under its real name, so that 
    # the semaphore will be destroyed when the last user is done with it.
unlink("/dev/shm/sem.cSunMiscSignal-66724") = 0
```
I think that corresponds to 
```
cSunMiscSignal_semaphore = sem_open(cSunMiscSignal_semaphoreName, ....);
sem_unlink(cSunMiscSignal_semaphoreName);
```

**Comment by liamwhite** [comment] 2019-02-07 11:02
@Peter-B-Kessler try running svm in a debootstrap chroot; mount /proc and /dev, because they are necessary, but do not mount /dev/shm. That is how I ran into this error. (Linux 4.19.0, Debian stretch)

**Comment by chrisseaton** [comment] 2019-02-07 11:38
@liamwhite is that something we can do in a Docker image? Can you help us recreate it?

**Comment by Peter-B-Kessler** [comment] 2019-02-07 19:10
SubstrateVM does not explicitly use /dev/shm.  If it is used in the implementation of the semaphore functions from the libc on your platform, then I would say that /dev/shm is "necessary".

**Comment by chrisseaton** [comment] 2019-02-08 10:08
Yes I think we're likely to just note in documentation that you may need to mount `/dev/shm` and close this as not a bug.

**Comment by chrisseaton** [comment] 2019-02-10 16:18
Documentation fix is on the way.

**Comment by chrisseaton** [comment] 2019-02-11 12:34
We've documented that you may struggle to run TruffleRuby if you unmount system file systems such as `/dev/shm`.

https://github.com/oracle/truffleruby/tree/56e619506e7265f34f4e981e9072ed902f2b1e53#system-compatibility

Closing as won't-fix, but thanks for the issue.

**Closed by chrisseaton** 2019-02-11 12:34 UTC
Labels: bug, substrate
