### ISSUE TITLE
High RSS usage on GraalVM CE 19.3.1 Java11 as compared to vanilla openjdk11

### ISSUE THREAD

**Issue by tporeba** [oracle/graal#2224] opened 2020-03-05 15:17 UTC
**Describe the issue**
I want to use GraalVM to run a JSR223 application, after switching from openjdk11 to GraalVM I observe significant increase in usage of native memory (RSS on Linux) - my app requires more than twice amount of memory as compared to standard openjdk11. Just after starting GraalVM requires 200MB of native memory as comapred to 85MB in openjdk. After handling some traffic GraalVM grows to nearly 500MB, while openjdk stays under 200MB.

The app is running with `-Xms64m -Xmx128m -server`. 

I do not actively use any GraalVM features yet, but I plan to use graal.js.  I cannot provide the code but if the problem isn't general, I can try to reproduce it on some standalone example app I can provide. 

Below you can see the output of `top` command for 5 processes of the same application, with the same settings after handling few-minute traffic (executing some scripts via JSR223) for both graalvm and openjdk. 

<details><summary>Openjdk top output</summary>

```
  PID USER      PR  NI    VIRT    RES    SHR S %CPU %MEM     TIME+ COMMAND                                                                                      
 4638 tporeba   20   0 2230888 166168  27712 S  0,3  2,0   0:15.49 /usr/lib/jvm/java-11-openjdk-amd64/bin/java 
 4681 tporeba   20   0 2226792 161196  27564 S  0,3  2,0   0:13.25 /usr/lib/jvm/java-11-openjdk-amd64/bin/java 
 4625 tporeba   20   0 2232936 158944  27456 S  0,3  1,9   0:14.04 /usr/lib/jvm/java-11-openjdk-amd64/bin/java 
 4651 tporeba   20   0 2230888 158568  27856 S  0,3  1,9   0:12.45 /usr/lib/jvm/java-11-openjdk-amd64/bin/java 
 4668 tporeba   20   0 2226792 158168  27408 S  0,3  1,9   0:12.50 /usr/lib/jvm/java-11-openjdk-amd64/bin/java 
```

</details>

<details><summary>GraalVM top output</summary>

```
 PID USER      PR  NI    VIRT    RES    SHR S %CPU %MEM     TIME+ COMMAND                                                                                      
 4170 tporeba   20   0 2547060 473196  59404 S  0,3  5,8   0:16.56 /opt/graalvm-ce-java11-19.3.1/bin/java 
 4182 tporeba   20   0 2540200 472520  59684 S  0,3  5,8   0:15.39 /opt/graalvm-ce-java11-19.3.1/bin/java 
 4193 tporeba   20   0 2542248 463636  60136 S  0,3  5,7   0:13.45 /opt/graalvm-ce-java11-19.3.1/bin/java 
 4208 tporeba   20   0 2538152 459720  60080 S  0,0  5,6   0:13.25 /opt/graalvm-ce-java11-19.3.1/bin/java 
 4219 tporeba   20   0 2536104 458912  59408 S  0,3  5,6   0:14.30 /opt/graalvm-ce-java11-19.3.1/bin/java 
```

</details>

I tried to use [Native Memory Tracking](https://docs.oracle.com/en/java/javase/11/vm/native-memory-tracking.html) to get some insights on where is that memory going. But while for openjdk11 it shows more or less same amout as RSS (+-30MB), for GraalVM it is nowhere near (300MB off).

<details><summary>OpenJDK VM.native_memory</summary>

```
4638:

Native Memory Tracking:

Total: reserved=1495376KB, committed=133156KB
-                 Java Heap (reserved=131072KB, committed=65600KB)
                            (mmap: reserved=131072KB, committed=65600KB) 
 
-                     Class (reserved=1073876KB, committed=26580KB)
                            (classes #4748)
                            (  instance classes #4462, array classes #286)
                            (malloc=724KB #13336) 
                            (mmap: reserved=1073152KB, committed=25856KB) 
                            (  Metadata:   )
                            (    reserved=24576KB, committed=23040KB)
                            (    used=22396KB)
                            (    free=644KB)
                            (    waste=0KB =0,00%)
                            (  Class space:)
                            (    reserved=1048576KB, committed=2816KB)
                            (    used=2542KB)
                            (    free=274KB)
                            (    waste=0KB =0,00%)
 
-                    Thread (reserved=17550KB, committed=1542KB)
                            (thread #17)
                            (stack: reserved=17468KB, committed=1460KB)
                            (malloc=61KB #104) 
                            (arena=21KB #33)
 
-                      Code (reserved=248726KB, committed=15490KB)
                            (malloc=1038KB #3790) 
                            (mmap: reserved=247688KB, committed=14452KB) 
 
-                        GC (reserved=638KB, committed=430KB)
                            (malloc=206KB #606) 
                            (mmap: reserved=432KB, committed=224KB) 
 
-                  Compiler (reserved=295KB, committed=295KB)
                            (malloc=164KB #6850) 
                            (arena=131KB #5)
 
-                  Internal (reserved=569KB, committed=569KB)
                            (malloc=537KB #1032) 
                            (mmap: reserved=32KB, committed=32KB) 
 
-                     Other (reserved=10KB, committed=10KB)
                            (malloc=10KB #2) 
 
-                    Symbol (reserved=3762KB, committed=3762KB)
                            (malloc=3115KB #45026) 
                            (arena=648KB #1)
 
-    Native Memory Tracking (reserved=1442KB, committed=1442KB)
                            (malloc=237KB #3372) 
                            (tracking overhead=1205KB)
 
-        Shared class space (reserved=16940KB, committed=16940KB)
                            (mmap: reserved=16940KB, committed=16940KB) 
 
-               Arena Chunk (reserved=175KB, committed=175KB)
                            (malloc=175KB) 
 
-                   Logging (reserved=4KB, committed=4KB)
                            (malloc=4KB #189) 
 
-                 Arguments (reserved=21KB, committed=21KB)
                            (malloc=21KB #495) 
 
-                    Module (reserved=228KB, committed=228KB)
                            (malloc=228KB #1728) 
 
-              Synchronizer (reserved=59KB, committed=59KB)
                            (malloc=59KB #497) 
 
-                 Safepoint (reserved=8KB, committed=8KB)
                            (mmap: reserved=8KB, committed=8KB) 
```

</details>

<details><summary>GraalVM VM.native_memory</summary>

```
4170:

Native Memory Tracking:

Total: reserved=1505003KB, committed=143783KB
-                 Java Heap (reserved=131072KB, committed=65600KB)
                            (mmap: reserved=131072KB, committed=65600KB) 
 
-                     Class (reserved=1080124KB, committed=34412KB)
                            (classes #6000)
                            (  instance classes #5646, array classes #354)
                            (malloc=828KB #15873) 
                            (mmap: reserved=1079296KB, committed=33584KB) 
                            (  Metadata:   )
                            (    reserved=30720KB, committed=29872KB)
                            (    used=29175KB)
                            (    free=697KB)
                            (    waste=0KB =0,00%)
                            (  Class space:)
                            (    reserved=1048576KB, committed=3712KB)
                            (    used=3325KB)
                            (    free=387KB)
                            (    waste=0KB =0,00%)
 
-                    Thread (reserved=19598KB, committed=1718KB)
                            (thread #17)
                            (stack: reserved=19516KB, committed=1636KB)
                            (malloc=61KB #104) 
                            (arena=21KB #33)
 
-                      Code (reserved=248605KB, committed=16657KB)
                            (malloc=917KB #3777) 
                            (mmap: reserved=247688KB, committed=15740KB) 
 
-                        GC (reserved=655KB, committed=447KB)
                            (malloc=223KB #642) 
                            (mmap: reserved=432KB, committed=224KB) 
 
-                  Compiler (reserved=332KB, committed=332KB)
                            (malloc=234KB #9062) 
                            (arena=98KB #4)
 
-                     JVMCI (reserved=24KB, committed=24KB)
                            (malloc=24KB #98) 
 
-                  Internal (reserved=622KB, committed=622KB)
                            (malloc=590KB #1201) 
                            (mmap: reserved=32KB, committed=32KB) 
 
-                     Other (reserved=10KB, committed=10KB)
                            (malloc=10KB #2) 
 
-                    Symbol (reserved=4927KB, committed=4927KB)
                            (malloc=4183KB #57731) 
                            (arena=744KB #1)
 
-    Native Memory Tracking (reserved=1682KB, committed=1682KB)
                            (malloc=202KB #2872) 
                            (tracking overhead=1480KB)
 
-        Shared class space (reserved=16836KB, committed=16836KB)
                            (mmap: reserved=16836KB, committed=16836KB) 
 
-               Arena Chunk (reserved=163KB, committed=163KB)
                            (malloc=163KB) 
 
-                   Logging (reserved=4KB, committed=4KB)
                            (malloc=4KB #185) 
 
-                 Arguments (reserved=21KB, committed=21KB)
                            (malloc=21KB #501) 
 
-                    Module (reserved=258KB, committed=258KB)
                            (malloc=258KB #2062) 
 
-              Synchronizer (reserved=63KB, committed=63KB)
                            (malloc=63KB #529) 
 
-                 Safepoint (reserved=8KB, committed=8KB)
                            (mmap: reserved=8KB, committed=8KB) 
```

</details>

**Expected behavior**
I understand that GraalVM has some additional memory requirements, but I would like to bring it down to be closer to vanilla openjdk. What is using that memory? Is it configurable? Why isn't it listed in Native Memory Tracking dump?

**Have you verified this issue still happens when using the latest snapshot?**
Yes, it is reproducible in recent 20.1.0 snapshots.

**Describe GraalVM and your environment :**
 - GraalVM version or commit id if built from source: **19.3.1**
 - CE or EE: **CE**
 - JDK version: **JDK11**
 - OS and OS Version: **Ubuntu Linux 18.04**
 - Architecture: **amd64**
 - The output of `java -Xinternalversion`: 
```
OpenJDK 64-Bit Server VM (11.0.6+9-jvmci-19.3-b07) for linux-amd64 JRE (11.0.6+9-jvmci-19.3-b07), built on Jan 13 2020 20:43:28 by "buildslave" with gcc 7.3.0
```

**Comment by dougxc** [comment] 2020-03-05 16:05
This could be due to the memory usage of libgraal. To test that hypothesis, you can play around with the [XOptions](https://github.com/oracle/graal/blob/c9660b245d17cbc94c53170b17edbe5cb7c93fce/substratevm/src/com.oracle.svm.core/src/com/oracle/svm/core/option/XOptions.java#L76-L79) `-Dlibgraal.Xmx` and `-Dlibgraal.Xmn` (e.g. `-Dlibgraal.Xmx128M -Dlibgraal.Xmn64m`).  This memory is the SVM heap allocated by libgraal and it does not participate in Native Memory Tracking. We're currently working on changes to try tune the libgraal heaps sizes automatically.

**Comment by tporeba** [comment] 2020-03-05 16:32
@dougxc Wow, this looks to be it. 
What are the default values? Can you point me to some docs on how to adjust those heap parameters. I don't want to bring them down too low without knowing what are the consequences.

**Comment by dougxc** [comment] 2020-03-05 16:33
I'm not exactly sure what the default values are. Someone from the SVM team can probably shed more light on them - @christianwimmer ?

**Comment by tporeba** [comment] 2020-04-06 16:39
@christianwimmer Any recommendations on how much memory give to the `libgraal.Xmx` ? What are the defaults? What resources should I give to this SVM heap for a relatively lightweight java process with java heap of 128MB?

**Comment by dougxc** [comment] 2020-04-06 18:25
@tporeba you could add the `-Dlibgraal.PrintGC=true` to see what GC is happening in libgraal and use that to experiment with different heap values for libgraal.

**Comment by christianwimmer** [comment] 2020-04-07 00:03
The maximum heap size (`Xmx`) is not much of a concern since the GC does not fill it up, but instead balances incremental and full GC time. What you want to set is the young generation size (`-Xmn`) which is always filled before a GC. The default young generation size is 256 MByte.

An appropriate value depends on the number of compilation threads (which depends on the number of cores). Currently all compilation threads share one heap. If you set the young generation size too low, compilation throughput will suffer and your application will take longer to warm up.

But you can definitely experiment with young generation sizes of 32 MByte or lower and see what happens.

**Comment by tporeba** [comment] 2020-04-07 09:21
@christianwimmer Thank you for your advice. 

Now I'm running with `libgraal.Xmx` set to ~50MB, which solved my initial problem of unrestricted growth of native memory. But dig into the subject to understand what is the price I pay (in terms of performance probably).

This a 4 core system.

I didn't restrict `libgraal.Xmn`, so I guess it is effectively `libgraal.Xmn`==`libgraal.Xmx`==50MB for me now. I will try with `libgraal.Xmn=32MB`, `libgraal.Xmx=50MB` and do some performance tests with the switch suggested by dougxc.

**Comment by tporeba** [comment] 2020-07-29 12:51
I'm experience now mysterious deaths of GraalVM processes after rollout to high-load environment (production), see my [post on graalvm slack](https://graalvm.slack.com/archives/CNBFR78F9/p1596019223300000).
Can this be due to too low `libgraal.Xmx` setting? 
No stacktrace, no heapdump, no fatal log file, no coredump is produced, so its hard to investigate.

When I set this `libgraal.Xmx` ridiculously low (=3m) on my test server this also ends up with a similar result (no error, no dumps), the process just ends with error code 99.

**Comment by dougxc** [comment] 2020-07-30 11:24
Is the exit code from your dead process `99`? If so, then the recent addition of [routing libgraal fatal errors](https://github.com/oracle/graal/commit/35bf3cf6416#diff-df558f09ed25300d846138332a3a3d6cR153) to [HotSpot's fatal error handling](https://github.com/graalvm/labs-openjdk-11/blob/master/src/hotspot/share/jvmci/jvmciRuntime.cpp#L835-L836) may be useful. You can try your workload on a [recent GraalVM CE nightly](https://github.com/graalvm/graalvm-ce-dev-builds/releases) to see if it provides more info.

**Comment by tporeba** [comment] 2020-07-30 17:18
Yes, now I can confirm that this is an OOM from native libgraal, with error code `99`.
This is what I get on stderr (it just took me a while to fix some other bug of mine that sent it to nowhere):

`java.lang.OutOfMemoryError: Garbage-collected heap size exceeded.`

We've got this for `-Dlibgraal.Xmx=44m` and same for `-Dlibgraal.Xmx=90m` - doubling the `Xmx` doesn't seem to fix the problem. I will do some runs with that `-Dlibgraal.PrintGC=true` to show you GC behaviour for different settings.

Could it be the fault of setting just `-Dlibgraal.Xmx`, but not `-Dlibgraal.Xmn` ? 

If I find a way to reproduce it somewhere else then production then I will be more than happy to test nightly or 20.x, unfortunately for now all I have is production with GraalVM 19.3.1 CE JDK11.

**Comment by tporeba** [comment] 2020-07-31 12:59
> @tporeba you could add the `-Dlibgraal.PrintGC=true` to see what GC is happening in libgraal and use that to experiment with different heap values for libgraal. I'd be very interested in any results you can share.

Here are some examples from different settings of `libgraal.Xmx` and `libgraal.Xmn`. 
Each file is the log from the same workload of ~10minutes wall time.

[libgraal.Xmx=44m.log](https://github.com/oracle/graal/files/5007093/libgraal.Xmx.44m.log)
[libgraal.Xmx=128m.log](https://github.com/oracle/graal/files/5007094/libgraal.Xmx.128m.log)
[libgraal.Xmx=44m_libgraal.Xmn=22m.log](https://github.com/oracle/graal/files/5007096/libgraal.Xmx.44m_libgraal.Xmn.22m.log)
[libgraal.Xmx=128m_libgraal.Xmn=32m.log](https://github.com/oracle/graal/files/5007097/libgraal.Xmx.128m_libgraal.Xmn.32m.log)

These are successful runs that did not end with an OOM, if I find a way to reproduce it - I will post its GC log too.

It is a nice surprise to me that my current setting `-Dlibgraal.Xmx=44m` looks better than `-Dlibgraal.Xmx=44m -Dlibgraal.Xmn=22m`, with the latter ending up with only Full GCs but no incremental ones. I think this means that default `Xmn` is a better selection in my case, probably `Xmn=22m` would be too big.

**Comment by christianwimmer** [comment] 2020-07-31 15:36
Setting the maximum memory size of libgraal to something small (especially only a few MByte like you do) of course reduces the maximum memory usage of the compiler. But it also means that large methods cannot be compiled because the compiler runs out of memory. The VM crash in that case certainly can and needs to be improved, to just a regular compilation bailout. But in general I don't think it is a good idea to limit the maximum compiler memory size that much.

Setting the young generation size (`Xmn`) is certainly a valid optimization. But since the GC does not wait until the old generation "fills up" before doing a full collection, but instead balances young and old GC time, there should not be any need to set `Xmx`.

**Comment by dougxc** [comment] 2020-07-31 21:48
@tporeba do you have an hs-err crash log now? I'm curious as to why the OOME does not simply result in a bailout. Or maybe you know @christianwimmer why the OOME is not being thrown and caught by the `CompilationWrapper` class?

**Comment by tporeba** [comment] 2020-08-10 10:48
@christianwimmer I never planned to force it to run on a few MB - I'm running on `libgraal.Xmx` ~50-100MB. Those 3MB was just an experiment to check if OOM from SVM gives same symptoms as I get on production and it does.

I limited the memory to stop unrestricted growth of RSS memory in the system in the first place, which could reach over 800MB for GraalVM for the process that should stay well below 300MB (like openjdk11). If setting just `libgraal.Xmn` will keep RSS low same as setting `libraal.Xmx`, then I can try it out too. 

@dougxc No hs-err crash is created. Just this single line on stderr: `java.lang.OutOfMemoryError: Garbage-collected heap size exceeded.` and return code `99`.

Funny thing that the change from `libgraal.Xmx=44m` to `libgraal.Xmx=90m` didn't reduce the frequency of error. It doesn't seem also to be caused by some specific business code - failures seem to occur randomly on business logic code that is also  executed hundreds of times successfully. Maybe some rare, unusually high peak in memory needed?

**Comment by dougxc** [comment] 2020-08-10 11:19
@tporeba it's unfortunately very hard to investigate further from my end without the hs-err crash log. As I mentioned [above](https://github.com/oracle/graal/issues/2224#issuecomment-666308234), this requires running on a recent snapshot binary.

If you cannot reproduce on a snapshot, that also indicates the problem may have been subsequently solved.

**Comment by tporeba** [comment] 2020-08-12 09:18
After replacing `libgraal.Xmx=44m` with `libgraal.Xmn=11m` the problem of crashes and OOMs seem to go away while the process still uses more or less the same amount of system memory. So now i just have a soft limit on `Xmn` instead of hard limit on `Xmx`, just like christianwimmer suggested.

Thanks for help and support!

Last question: Is there any way to read the effective value of `libgraal.Xmx` from a running process? What is the default when I don't set it? I may need to set it explicitly, and initially I wanted to use the same value as default.

**Comment by tporeba** [comment] 2020-08-12 10:49
I've found that `-Dlibgraal.VerboseGC=true` makes the `-Dlibgraal.PrintGC=true` print more data, including the calculated Xmx and Xmn sizes for SVM.

By default `libgraal.Xmx` was set to 80% of physical memory on the host machine.

**Comment by christianwimmer** [comment] 2021-11-04 17:02
GraalVM 22.0 enables a new GC policy that should reduce the memory footprint already. Especially, it starts with a more conservative young generation size and then grows automatically based on GC overhead.

Memory sizes are aware of cgroup.

**Comment by Stono** [comment] 2021-11-04 17:11
Ah interesting, seeing as we're just experimenting at the moment we may well be best waiting for that.
Is there a release schedule or estimated release date for 22?

**Comment by christianwimmer** [comment] 2021-11-04 17:16
You can use the daily 22.0 snapshot builds for experiments. Release will be in January.

**Comment by Stono** [comment] 2021-11-04 17:16
Great, thanks for your responses.

**Comment by fernando-valdez** [comment] 2024-01-18 01:24
Most memory issues had been addressed in later releases. I am closing this ticket as there this issue no longer applies.

**Closed by fernando-valdez** 2024-01-18 01:24 UTC
Labels: bug
