### ISSUE TITLE
feature: apple m1 architecture support

### ISSUE THREAD

**Issue by auula** [oracle/graal#4668] opened 2022-06-24 06:12 UTC
Hello, I just learned about this project recently. Does apple arm m1 support it? And recently I saw a new project called Leyden on Twitter, what is the difference between this and graal? Thank you for making Java support static compilation. I hope Graal will get better and better. I have another idea to let more people know about graal. Few people in China know about the graal compiler project, and there is also a lack of related technical communities. , I hope graal can get better and better, thank you.🤝

**Comment by fniephaus** [comment] 2022-06-24 20:24
We have added experimental M1 support to CE and will do the same to EE soon. Closing this as a duplicate of https://github.com/oracle/graal/issues/2666.

**Closed by fniephaus** 2022-06-24 20:24 UTC
Labels: duplicate, feature
