### ISSUE TITLE
NPE when running native-image tool

### ISSUE THREAD

**Issue by joprice** [oracle/graal#723] opened 2018-10-06 20:11 UTC
I get an NPE when building this project: https://github.com/OlegIlyenko/sangria-http4s-graalvm-example/issues/2. The issue contains the original stacktrace. 

It should be reproducible since it uses a docker image for graal: https://github.com/OlegIlyenko/sangria-http4s-graalvm-example/blob/65e84d6c8e00724cfa4ce87edff704e776fb79b6/packaging.sbt#L56 

The image generation can be run via the 'nativeImage' task: `sbt nativeImage`.

**Comment by cstancu** [comment] 2018-10-11 03:52
It looks like the docker container comes packaged with its own `native-image` version. Is it possible to tell the `sbt` task to pick up my local `native-image`? (cc: @OlegIlyenko).

**Comment by joprice** [comment] 2018-10-11 03:59
You should be able to change the string "tenshi/graalvm-native-image" to your local image, then start a new sbt session, or run `reload` in an existing session (sbt requires a restart or to be told explicitly to pick up changes to the build definition).

**Comment by OlegIlyenko** [comment] 2018-10-11 08:28
@cstancu sure, I think you can change [`dockerProcess` command](https://github.com/OlegIlyenko/sangria-http4s-graalvm-example/blob/65e84d6c8e00724cfa4ce87edff704e776fb79b6/packaging.sbt#L53-L62) like this:

```scala
  val dockerProcess = Seq(
    "native-image"
    "--verbose",
    "-cp", classpathStr,
    s"-H:Name=${relativePath(imagePath.relativeTo(baseDir).get)}",
    s"-H:Class=$main",
    "-H:+ReportUnsupportedElementsAtRuntime"
  ) ++ nativeImageResources.value.fold(Seq.empty[String])(r ⇒ Seq("-H:IncludeResources=" + r))
```

this should use local native-image. i also realized that my docker container is [still at rc5](https://github.com/OlegIlyenko/graalvm-native-image/blob/master/Dockerfile#L10). i'll try to update it later today.

**Comment by cstancu** [comment] 2018-10-11 19:22
Thanks! I was able to reproduce it with @OlegIlyenko suggestion and latest `native-image`. The NPE hides the original problem which seems to be that during native image writing we try to write the field `public static Episode$ Episode$.MODULE$` into the image heap without having previously seen it during the analysis. I will deffer this to @vjovanov since he is more familiar with scala internals.

**Comment by vjovanov** [comment] 2018-12-03 17:23
This should be fixed now. Thanks for reporting!

**Closed** 2018-12-03 17:23 UTC
Labels: bug, substrate
