### ISSUE TITLE
Native image hangs in GC

### ISSUE THREAD

**Issue by qdeee** [oracle/graal#2981] opened 2020-11-12 16:35 UTC
Hello!
I have java-application compiled with native-image. It works fine with Graal version 19.0.2.

Now I try to update Graal to 20.2.0. Application starts and hangs after few seconds.
I enabled debug info for the image, here is the GDB trace:
```
(gdb) info threads
  Id   Target Id         Frame
  26   Thread 0x7f4b6a0ff700 (LWP 71) "ackTracePrinter" 0x00007f4b6c8a9c9d in poll () at ../sysdeps/unix/syscall-template.S:81
  25   Thread 0x7f4b696ff700 (LWP 72) "nPool-worker-25" pthread_cond_wait@@GLIBC_2.3.2 () at ../nptl/sysdeps/unix/sysv/linux/x86_64/pthread_cond_wait.S:185
  24   Thread 0x7f4b63fff700 (LWP 73) "nPool-worker-18" __lll_lock_wait () at ../nptl/sysdeps/unix/sysv/linux/x86_64/lowlevellock.S:135
  23   Thread 0x7f4b637fe700 (LWP 76) "eep-Alive-Timer" __lll_lock_wait () at ../nptl/sysdeps/unix/sysv/linux/x86_64/lowlevellock.S:135
  22   Thread 0x7f4b60dff700 (LWP 77) "yResolverThread" __lll_lock_wait () at ../nptl/sysdeps/unix/sysv/linux/x86_64/lowlevellock.S:135
  21   Thread 0x7f4b4ffff700 (LWP 78) "TaskPipeline" pthread_cond_timedwait@@GLIBC_2.3.2 () at ../nptl/sysdeps/unix/sysv/linux/x86_64/pthread_cond_timedwait.S:238
  20   Thread 0x7f4b625ff700 (LWP 80) "rBackgroundTask" __lll_lock_wait () at ../nptl/sysdeps/unix/sysv/linux/x86_64/lowlevellock.S:135
  19   Thread 0x7f4b4effd700 (LWP 81) "teTimePublisher" __lll_lock_wait () at ../nptl/sysdeps/unix/sysv/linux/x86_64/lowlevellock.S:135
  18   Thread 0x7f4b4e3ff700 (LWP 82) "log-uploader" pthread_cond_wait@@GLIBC_2.3.2 () at ../nptl/sysdeps/unix/sysv/linux/x86_64/pthread_cond_wait.S:185
  17   Thread 0x7f4b4f7fe700 (LWP 84) "port-checker" __lll_lock_wait () at ../nptl/sysdeps/unix/sysv/linux/x86_64/lowlevellock.S:135
  16   Thread 0x7f4b4cbff700 (LWP 85) "slave-killer" __lll_lock_wait () at ../nptl/sysdeps/unix/sysv/linux/x86_64/lowlevellock.S:135
  15   Thread 0x7f4b4d5ff700 (LWP 87) "}@1605182221056" pthread_cond_wait@@GLIBC_2.3.2 () at ../nptl/sysdeps/unix/sysv/linux/x86_64/pthread_cond_wait.S:185
  14   Thread 0x7f4b373ff700 (LWP 91) "ce{task.LAUNCH}" __lll_lock_wait () at ../nptl/sysdeps/unix/sysv/linux/x86_64/lowlevellock.S:135
  13   Thread 0x7f4b363ff700 (LWP 92) "herTask{LAUNCH}" 0x00007f4b6d1b63ad in read () at ../sysdeps/unix/syscall-template.S:81
  12   Thread 0x7f4b35bfe700 (LWP 93) "apshot-uploader" __lll_lock_wait () at ../nptl/sysdeps/unix/sysv/linux/x86_64/lowlevellock.S:135
  11   Thread 0x7f4b353fd700 (LWP 94) "sEventPublisher" __lll_lock_wait () at ../nptl/sysdeps/unix/sysv/linux/x86_64/lowlevellock.S:135
  10   Thread 0x7f4b34bfc700 (LWP 95) "dummy" pthread_cond_timedwait@@GLIBC_2.3.2 () at ../nptl/sysdeps/unix/sysv/linux/x86_64/pthread_cond_timedwait.S:238
  9    Thread 0x7f4b1bfff700 (LWP 99) "ss.job-command}" __lll_lock_wait () at ../nptl/sysdeps/unix/sysv/linux/x86_64/lowlevellock.S:135
  8    Thread 0x7f4b1b7fe700 (LWP 101) "Logs-Writer-0" __lll_lock_wait () at ../nptl/sysdeps/unix/sysv/linux/x86_64/lowlevellock.S:135
  7    Thread 0x7f4b1affd700 (LWP 102) "Logs-Writer-1" pthread_cond_wait@@GLIBC_2.3.2 () at ../nptl/sysdeps/unix/sysv/linux/x86_64/pthread_cond_wait.S:185
  6    Thread 0x7f4b1a7fc700 (LWP 103) "Logs-Writer-2" pthread_cond_wait@@GLIBC_2.3.2 () at ../nptl/sysdeps/unix/sysv/linux/x86_64/pthread_cond_wait.S:185
  5    Thread 0x7f4b19ffb700 (LWP 104) "Logs-Writer-3" pthread_cond_wait@@GLIBC_2.3.2 () at ../nptl/sysdeps/unix/sysv/linux/x86_64/pthread_cond_wait.S:185
  4    Thread 0x7f4b197fa700 (LWP 105) "YtLogTransfer-0" __lll_lock_wait () at ../nptl/sysdeps/unix/sysv/linux/x86_64/lowlevellock.S:135
  3    Thread 0x7f4b18ff9700 (LWP 106) "YtLogTransfer-1" pthread_cond_wait@@GLIBC_2.3.2 () at ../nptl/sysdeps/unix/sysv/linux/x86_64/pthread_cond_wait.S:185
* 2    Thread 0x7f4af7fff700 (LWP 107) "Logs-Writer-3" com.oracle.svm.core.thread.Safepoint.Master.waitForSafepoints(java.lang.String)()void () at com/oracle/svm/core/thread/Safepoint.java:688
  1    Thread 0x7f4b6d8df780 (LWP 70) "job_launcher_na" pthread_cond_wait@@GLIBC_2.3.2 () at ../nptl/sysdeps/unix/sysv/linux/x86_64/pthread_cond_wait.S:185

(gdb) thread 2
[Switching to thread 2 (Thread 0x7f4af7fff700 (LWP 107))]
#0  com.oracle.svm.core.thread.Safepoint.Master.waitForSafepoints(java.lang.String)()void () at com/oracle/svm/core/thread/Safepoint.java:688
688	com/oracle/svm/core/thread/Safepoint.java: No such file or directory.

(gdb) bt
#0  com.oracle.svm.core.thread.Safepoint.Master.waitForSafepoints(java.lang.String)()void () at com/oracle/svm/core/thread/Safepoint.java:688
#1  0x00000000008e5cf8 in com.oracle.svm.core.thread.Safepoint.Master.freeze(java.lang.String)()void () at com/oracle/svm/core/thread/Safepoint.java:570
#2  0x00000000008e7a4b in com.oracle.svm.core.thread.VMOperationControl.WorkQueues.executeAllQueuedVMOperations()void () at com/oracle/svm/core/thread/VMOperationControl.java:543
#3  0x00000000008e7915 in com.oracle.svm.core.thread.VMOperationControl.WorkQueues.enqueueAndExecute(com.oracle.svm.core.thread.VMOperation, com.oracle.svm.core.thread.NativeVMOperationData)()void ()
    at com/oracle/svm/core/thread/VMOperationControl.java:481
#4  0x00000000008e8078 in com.oracle.svm.core.thread.VMOperationControl.enqueue(com.oracle.svm.core.thread.VMOperation, com.oracle.svm.core.thread.NativeVMOperationData)()void ()
    at com/oracle/svm/core/thread/VMOperationControl.java:264
#5  0x00000000008a5a0d in com.oracle.svm.core.genscavenge.GCImpl.collectWithoutAllocating(com.oracle.svm.core.heap.GCCause)()void () at com/oracle/svm/core/thread/VMOperationControl.java:227
#6  0x00000000008ac6a7 in com.oracle.svm.core.genscavenge.HeapPolicy.SometimesCollectOnAllocation.maybeCauseCollection()void () at com/oracle/svm/core/genscavenge/HeapPolicy.java:385
#7  0x00000000008b0d6a in com.oracle.svm.core.genscavenge.ThreadLocalAllocation.allocateNewInstance(java.lang.Class, com.oracle.svm.core.genscavenge.ThreadLocalAllocation$Descriptor, boolean)()void ()
    at com/oracle/svm/core/genscavenge/HeapPolicy.java:91
#8  0x00000000008b16ec in com.oracle.svm.core.genscavenge.ThreadLocalAllocation.slowPathNewInstanceWithoutAllocating(java.lang.Class)()void ()
    at com/oracle/svm/core/threadlocal/FastThreadLocalBytes.java:62
#9  0x00000000008b1687 in com.oracle.svm.core.genscavenge.ThreadLocalAllocation.slowPathNewInstance(org.graalvm.compiler.word.Word)()void () at com/oracle/svm/core/genscavenge/GCImpl.java:960
#10 0x00000000008d9dc2 in com.oracle.svm.core.posix.thread.PosixJavaThreads.setNativeName(java.lang.Thread, java.lang.String)()void () at org/graalvm/compiler/replacements/AllocationSnippets.java:62
#11 0x00000000008d9749 in com.oracle.svm.core.posix.thread.PosixJavaThreads.beforeThreadRun(java.lang.Thread)()void () at java/lang/Thread.java:1142
#12 0x00000000008e440d in com.oracle.svm.core.thread.JavaThreads.threadStartRoutine(org.graalvm.nativeimage.ObjectHandle)()void () at com/oracle/svm/core/thread/JavaThreads.java:83
#13 0x0000000000898590 in com.oracle.svm.core.code.IsolateEnterStub.PosixJavaThreads_pthreadStartRoutine_e1f4a8c0039f8337338252cd8734f63a79b5e3df(com.oracle.svm.core.thread.JavaThreads$ThreadStartData)()void () at com/oracle/svm/core/posix/thread/PosixJavaThreads.java:192
#14 0x00007f4b6d1af184 in start_thread (arg=0x7f4af7fff700) at pthread_create.c:312
#15 0x00007f4b6c8b703d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:111
```

As you can see, many threads are waiting in `__lll_lock_wait () at ../nptl/sysdeps/unix/sysv/linux/x86_64/lowlevellock.S:135`. I checked that all these threads are waiting for the mutex owned by thread # 2:
```
(gdb) thread 16
[Switching to thread 16 (Thread 0x7f4b4cbff700 (LWP 85))]
#0  __lll_lock_wait () at ../nptl/sysdeps/unix/sysv/linux/x86_64/lowlevellock.S:135
135	../nptl/sysdeps/unix/sysv/linux/x86_64/lowlevellock.S: No such file or directory.
(gdb) bt
#0  __lll_lock_wait () at ../nptl/sysdeps/unix/sysv/linux/x86_64/lowlevellock.S:135
#1  0x00007f4b6d1b1649 in _L_lock_909 () from /lib/x86_64-linux-gnu/libpthread.so.0
#2  0x00007f4b6d1b1470 in __GI___pthread_mutex_lock (mutex=0x7f4b6b031c08) at ../nptl/pthread_mutex_lock.c:79
#3  0x00000000008d959d in com.oracle.svm.core.posix.pthread.PthreadVMMutex.lockNoTransition()void () at com/oracle/svm/core/posix/pthread/PthreadVMLockSupport.java:177
#4  0x00000000008e6c47 in com.oracle.svm.core.thread.Safepoint.notInlinedLockNoTransition()void () at com/oracle/svm/core/thread/Safepoint.java:311
#5  0x00000000008e6a02 in com.oracle.svm.core.thread.Safepoint.freezeAtSafepoint(int, boolean)()void () at com/oracle/svm/core/thread/Safepoint.java:305
#6  0x00000000008e6ca0 in com.oracle.svm.core.thread.Safepoint.slowPathSafepointCheck(int, boolean)()void () at com/oracle/svm/core/thread/Safepoint.java:218
#7  0x00000000008e69da in com.oracle.svm.core.thread.Safepoint.enterSlowPathTransitionFromNativeToNewStatus(int)()void () at com/oracle/svm/core/thread/Safepoint.java:493
#8  0x00000000008da39c in com.oracle.svm.core.posix.thread.PosixParkEvent.condTimedWait(long)()void () at com/oracle/svm/core/thread/Safepoint.java:419
#9  0x00000000008e3bda in com.oracle.svm.core.thread.JavaThreads.park(long)()void () at com/oracle/svm/core/thread/JavaThreads.java:710
#10 0x0000000001eb3419 in sun.misc.Unsafe.park(boolean, long)()void () at sun/misc/Unsafe.java:52
#11 0x000000000169d7a9 in java.util.concurrent.locks.LockSupport.parkNanos(java.lang.Object, long)()void () at java/util/concurrent/locks/LockSupport.java:215
#12 0x0000000001695bdf in java.util.concurrent.locks.AbstractQueuedSynchronizer.ConditionObject.awaitNanos(long)()void () at java/util/concurrent/locks/AbstractQueuedSynchronizer.java:2079
#13 0x0000000001681eb7 in java.util.concurrent.ScheduledThreadPoolExecutor.DelayedWorkQueue.take()void () at java/util/concurrent/ScheduledThreadPoolExecutor.java:1093
#14 0x0000000001681b73 in java.util.concurrent.ScheduledThreadPoolExecutor.DelayedWorkQueue.take()void () at java/util/concurrent/locks/ReentrantLock.java:809
#15 0x000000000168e047 in java.util.concurrent.ThreadPoolExecutor.getTask()void () at java/util/concurrent/ThreadPoolExecutor.java:1074
#16 0x000000000168f5d4 in java.util.concurrent.ThreadPoolExecutor.runWorker(java.util.concurrent.ThreadPoolExecutor$Worker)()void () at java/util/concurrent/ThreadPoolExecutor.java:1134
#17 0x000000000168b12a in java.util.concurrent.ThreadPoolExecutor.Worker.run()void () at java/util/concurrent/ThreadPoolExecutor.java:624
#18 0x000000000131603a in java.lang.Thread.run()void () at java/lang/Thread.java:747
#19 0x00000000008e447c in com.oracle.svm.core.thread.JavaThreads.threadStartRoutine(org.graalvm.nativeimage.ObjectHandle)()void () at com/oracle/svm/core/thread/JavaThreads.java:519
#20 0x0000000000898590 in com.oracle.svm.core.code.IsolateEnterStub.PosixJavaThreads_pthreadStartRoutine_e1f4a8c0039f8337338252cd8734f63a79b5e3df(com.oracle.svm.core.thread.JavaThreads$ThreadStartData)()void () at com/oracle/svm/core/posix/thread/PosixJavaThreads.java:192
#21 0x00007f4b6d1af184 in start_thread (arg=0x7f4b4cbff700) at pthread_create.c:312
#22 0x00007f4b6c8b703d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:111
(gdb) f 2
#2  0x00007f4b6d1b1470 in __GI___pthread_mutex_lock (mutex=0x7f4b6b031c08) at ../nptl/pthread_mutex_lock.c:79
79	../nptl/pthread_mutex_lock.c: No such file or directory.
(gdb) print mutex.__data.__owner
$1 = 107
(gdb) thread find 107
Thread 2 has target id 'Thread 0x7f4af7fff700 (LWP 107)'
```

As I understood, GC can't complete because of infinite `com.oracle.svm.core.thread.Safepoint.Master.waitForSafepoints`.

**Steps to reproduce the issue**
This bug is consistently reproduced. Unfortunately I can't provide the application's code (NDA). But I may provide any additional information that may help to fix the problem.

**Describe GraalVM and your environment:**
 - GraalVM version: **CE 20.2.0; 0445418ace3c7190934fa5390001220599669898 (built from source)**
 - JDK major version: **8**
 - OS: **Linux 14.04**
 - Architecture: **AMD64**
 - Build command:
```
${JAVA_HOME}/bin/native-image \
-jar ${SHADED_JAR} \
-H:Name="${RESULT_BINARY}" \
-H:GenerateDebugInfo=1 \
--no-server \
--no-fallback \
--enable-url-protocols=https,http \
--initialize-at-build-time \
--report-unsupported-elements-at-runtime \
--allow-incomplete-classpath \
-H:IncludeResources='.*properties/context.properties|.*scripts/redirect.py' \
-H:DynamicProxyConfigurationResources=graal/proxy.json \
-Djava.net.preferIPv6Addresses=true
```

**Comment by oubidar-Abderrahim** [comment] 2020-11-16 14:51
Do you experience this issue while running your jar using GraalVM 20.2.0? or it only happens in native-image.

Could you please try with the latest release (20.3.0)? since some known Deadlock issues were solved in that version.

Also if you could provide a small reproducer that does not expose your application's mechanics but could help pinpoint the inner function causing this issue? that would be much appreciated.

**Comment by qdeee** [comment] 2020-11-17 17:01
Hi, Abderrahim Oubidar!

> Do you experience this issue while running your jar using GraalVM 20.2.0? or it only happens in native-image.
It only happens in native-image.

> Could you please try with the latest release (20.3.0)? since some known Deadlock issues were solved in that version.
Where can I download release 20.3.0? I see only 20.2.0 on the releases page: https://github.com/graalvm/graalvm-ce-builds/releases . Also I built GraalVM from source 5 days ago (commit 0445418ace3c7190934fa5390001220599669898) and got the same error.

> Also if you could provide a small reproducer that does not expose your application's mechanics but could help pinpoint the inner function causing this issue? that would be much appreciated.
Unfortunately, now I can't provide such reproducer, it'll take some time to extract independent minimal app :(

**Comment by fernando-valdez** [comment] 2024-01-17 04:00
this issue may be fixed in the latest snapshot, please try it and let us know if the problem persists.

**Comment by qdeee** [comment] 2024-01-17 10:31
Actually, we migrated to 22.0.0.2 and it seems that problem is fixed. I think, this issue may be closed :)

**Closed** 2024-01-17 14:41 UTC
Labels: bug, native-image
