### ISSUE TITLE
NullPointerException when using spring cloud

### ISSUE THREAD

**Issue by itzikiusa** [oracle/graal#2595] opened 2020-06-20 11:38 UTC
Using Spring boot version 2.3.1 with r2dbc
creating native image works well and boot up speed is pretty good (0.3s vs vs 3.2s)
how ever when adding spring cloud config with spring cloud dependencies, getting the following error: NullPointerException (stack trace is below)

using graalvm version 20.1.0
spring boot 2.3.1
spring cloud Hoxton.SR5
JDK 8(graalvm - build 25.252-b09-jvmci-20.1-b02)
MacOS

**More details**
running the following sh file:
```#!/usr/bin/env bash

ARTIFACT=${1}
MAINCLASS=${2}
VERSION=${3}

JAR="${ARTIFACT}-${VERSION}.jar"

rm -rf target
mkdir -p target/native-image
mvn -ntp package
rm -f $ARTIFACT
cd target/native-image
jar -xvf ../$JAR
cp -R META-INF BOOT-INF/classes

LIBPATH=`find BOOT-INF/lib | tr '\n' ':'`
CP=BOOT-INF/classes:$LIBPATH
GRAALVM_VERSION=`native-image --version`

time native-image \
  --verbose \
  -H:EnableURLProtocols=http \
  -H:+RemoveSaturatedTypeFlows \
  -H:Name=$ARTIFACT \
  -Dspring.native.verbose=true \
  -Dspring.native.remove-jmx-support=true \
  -Dspring.native.remove-spel-support=true \
  -Dspring.native.remove-yaml-support=true \
  --allow-incomplete-classpath \
  --initialize-at-build-time=io.netty.util.internal.logging.Log4JLogger \
  -cp $CP $MAINCLASS`


and this is the stack trace

`12:51:42.623 [ForkJoinPool-2-worker-2] DEBUG io.netty.channel.nio.NioEventLoop - -Dio.netty.selectorAutoRebuildThreshold: 512
[r2dbctest:5180]     analysis:  25,963.70 ms,  4.36 GB
Fatal error:java.lang.NullPointerException
	at com.oracle.graal.pointsto.flow.MethodTypeFlow.getParsingContext(MethodTypeFlow.java:99)
	at com.oracle.graal.pointsto.util.AnalysisError.parsingContext(AnalysisError.java:122)
	at com.oracle.graal.pointsto.util.AnalysisError.access$000(AnalysisError.java:37)
	at com.oracle.graal.pointsto.util.AnalysisError$ParsingError.message(AnalysisError.java:97)
	at com.oracle.graal.pointsto.util.AnalysisError$ParsingError.<init>(AnalysisError.java:87)
	at com.oracle.graal.pointsto.util.AnalysisError.parsingError(AnalysisError.java:138)
	at com.oracle.graal.pointsto.flow.MethodTypeFlow.doParse(MethodTypeFlow.java:336)
	at com.oracle.graal.pointsto.flow.MethodTypeFlow.ensureParsed(MethodTypeFlow.java:311)
	at com.oracle.graal.pointsto.flow.MethodTypeFlow.addContext(MethodTypeFlow.java:112)
	at com.oracle.graal.pointsto.DefaultAnalysisPolicy$DefaultVirtualInvokeTypeFlow.onObservedUpdate(DefaultAnalysisPolicy.java:228)
	at com.oracle.graal.pointsto.flow.TypeFlow.notifyObservers(TypeFlow.java:470)
	at com.oracle.graal.pointsto.flow.TypeFlow.update(TypeFlow.java:542)
	at com.oracle.graal.pointsto.BigBang$2.run(BigBang.java:530)
	at com.oracle.graal.pointsto.util.CompletionExecutor.lambda$execute$0(CompletionExecutor.java:173)
	at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1402)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
Error: Image build request failed with exit status 1
com.oracle.svm.driver.NativeImage$NativeImageError: Image build request failed with exit status 1
	at com.oracle.svm.driver.NativeImage.showError(NativeImage.java:1541)
	at com.oracle.svm.driver.NativeImage.build(NativeImage.java:1299)
	at com.oracle.svm.driver.NativeImage.performBuild(NativeImage.java:1260)
	at com.oracle.svm.driver.NativeImage.main(NativeImage.java:1219)`

**Comment by aclement** [comment] 2020-06-29 15:16
Just to say I have seen this too - someone raised it against our project but I think it is a GraalVM issue (https://github.com/spring-projects-experimental/spring-graalvm-native/issues/184).  If you need another repro project:

```
git clone git@github.com:joshlong/gateway-and-graalvm.git
cd gateway-and-graalvm
./compile.sh
```
I've tried it with Graal 20.1 (Java8) and Graal 20.2 dev (20200627) (Java8):

```
Fatal error:java.lang.NullPointerException
	at com.oracle.graal.pointsto.flow.MethodTypeFlow.getParsingContext(MethodTypeFlow.java:99)
	at com.oracle.graal.pointsto.util.AnalysisError.parsingContext(AnalysisError.java:122)
	at com.oracle.graal.pointsto.util.AnalysisError.access$000(AnalysisError.java:37)
	at com.oracle.graal.pointsto.util.AnalysisError$ParsingError.message(AnalysisError.java:97)
	at com.oracle.graal.pointsto.util.AnalysisError$ParsingError.<init>(AnalysisError.java:87)
	at com.oracle.graal.pointsto.util.AnalysisError.parsingError(AnalysisError.java:138)
	at com.oracle.graal.pointsto.flow.MethodTypeFlow.doParse(MethodTypeFlow.java:336)
	at com.oracle.graal.pointsto.flow.MethodTypeFlow.ensureParsed(MethodTypeFlow.java:311)
	at com.oracle.graal.pointsto.flow.MethodTypeFlow.addContext(MethodTypeFlow.java:112)
	at com.oracle.graal.pointsto.DefaultAnalysisPolicy$DefaultVirtualInvokeTypeFlow.onObservedUpdate(DefaultAnalysisPolicy.java:228)
	at com.oracle.graal.pointsto.flow.TypeFlow.notifyObservers(TypeFlow.java:470)
	at com.oracle.graal.pointsto.flow.TypeFlow.update(TypeFlow.java:542)
	at com.oracle.graal.pointsto.BigBang$2.run(BigBang.java:530)

```

**Comment by aclement** [comment] 2020-06-29 15:23
Actually!  I had installed the Graal 20.2 but hadn't run that pesky `gu install native-image` command.  With that run, and NOW definitely running 20.2 dev, it seems to get past the NPE. So maybe already fixed at least for my sample. @itzikiusa - could be worth trying with 20.2 ( https://github.com/graalvm/graalvm-ce-dev-builds/releases )

**Comment by itzikiusa** [comment] 2020-06-29 17:53
i'm using maven plugin for the native image
the latest version over there is 20.1.0
i'll wait for the official release to come and try it, in general i saw a note that spring cloud not supported yet but only spring functions. will be good idea to make it general available though.

if it will happen on spring framework 5.3 this will be great
my guess it will take few more releases until this thing will happen.

be happy to help anyway i can :)

**Comment by aclement** [comment] 2020-06-29 18:35
Hey, yep, spring cloud isn't really supported yet. The issue I linked to in the spring-graalvm-native project compiles with 20.2 (no NPE) but the resulting image doesn't run due to other issues in the spring area we need to address. Quite a few folks seem to be trying spring cloud so we'll get there soon hopefully.

**Comment by cstancu** [comment] 2020-07-12 23:46
Likely a duplicate of https://github.com/oracle/graal/issues/2518

**Closed by cstancu** 2020-07-12 23:46 UTC
Labels: bug, native-image
