### ISSUE TITLE
graalvm-ce  native-image complains main class not found

### ISSUE THREAD

**Issue by springland** [oracle/graal#6127] opened 2023-03-06 00:52 UTC
**Describe the issue**

Version   ghcr.io/graalvm/graalvm-ce:22.3.1

native-image  complains  main class cannot be found from classpath or module but java -jar works well

**Steps to reproduce the issue**

I build a docker image to illustrate it

execute docker run -it springland/springboot3native

once get to the bash of the container

java -jar springboot3.jar    runs well

command  native-image -jar springboot3.jar springboot3native  returns the below error

================================================================================
GraalVM Native Image: Generating 'springboot3native' (executable)...
================================================================================
[1/7] Initializing...                                            (0.0s @ 0.14GB)
Error: Main entry point class 'com.example.springboot3.Springboot3demoApplication' neither found on the classpath nor on the modulepath.
classpath: '/app/springboot3.jar'
modulepath: '/opt/graalvm-ce-java17-22.3.1/lib/svm/library-support.jar'
Error: Use -H:+ReportExceptionStackTraces to print stacktrace of underlying exception
Error: Image build request failed with exit status 1

**Describe GraalVM and your environment:**
 - GraalVM version: ghcr.io/graalvm/graalvm-ce:22.3.1
 - JDK major version: ** Open JDK 17 **
 - OS: **Ubuntu 22.04 LTS**
 - Architecture: **AMD64**

**More details**

Dockerfile
FROM ghcr.io/graalvm/graalvm-ce:22.3.1

WORKDIR /app

RUN gu install native-image

COPY target/springboot3-0.0.1-SNAPSHOT.jar  springboot3.jar

ENTRYPOINT bash
```

**Comment by donaldofr** [comment] 2023-03-09 02:35
I'm having a similar issue.  

Warning: Ignoring server-mode native-image argument --no-server.
========================================================================================================================
GraalVM Native Image: Generating 'com.example.native_test.nativetestapplication' (executable)...
========================================================================================================================
[1/7] Initializing...                                                                                    (0.0s @ 0.13GB)
Error: Main entry point class 'com.example.native_test.NativeTestApplication' neither found on the classpath nor on the modulepath.
classpath: 'Z:\projects\maven\native_test\target\native_test-0.0.1-SNAPSHOT.jar'
modulepath: 'Z:\Programs\java\graalvm-ce-java17-22.3.1\lib\svm\library-support.jar'
Error: Use -H:+ReportExceptionStackTraces to print stacktrace of underlying exception
Error: Image build request failed with exit status 1

The classpath shows the uber jar (native_test-0.0.1-SNAPSHOT.jar)  which has the main entry point class but it still complains that class is not found on the classpath.

**Comment by oubidar-Abderrahim** [comment] 2023-03-10 10:05
Hi, Thank you for reaching out, could you please share a reproducer code with steps to reproduce the issue? Thanks

**Comment by springland** [comment] 2023-03-10 11:56
> Hi, Thank you for reaching out, could you please share a reproducer code with steps to reproduce the issue? Thanks

Yes. I have build a docker image on docker hub to reproduce it
The below are the steps

1) docker run -it springland/springboot3native -- bash   ( login to docker)
2) java -jar springboot3.jar  ( run jar directly  , this works well  ) 
3) native-image -jar springboot3.jar springboot3native ( this throws error com.example.springboot3.Springboot3demoApplication is not available)

since graavlvm jre can run it the class com.example.springboot3.Springboot3demoApplication must be in the jar file. for some reason native-image does not recongnize it.

**Comment by donaldofr** [comment] 2023-03-14 16:18
Any update on this?

**Comment by oubidar-Abderrahim** [comment] 2023-03-24 11:11
Could you please share an example without needing to login to docker? a GitHub repo I can pull and build the image locally will be helpful

**Comment by vinc3nz** [comment] 2023-03-24 16:09
The same bug persists for me: I am running Windows 10 with GraalVM ```
java version "17.0.6" 2023-01-17 LTS
Java(TM) SE Runtime Environment GraalVM EE 22.3.1 (build 17.0.6+9-LTS-jvmci-22.3-b11)
Java HotSpot(TM) 64-Bit Server VM GraalVM EE 22.3.1 (build 17.0.6+9-LTS-jvmci-22.3-b11, mixed mode, sharing)
```

The Class clearly exists in the given jar file. It does not work with -jar file.jar and -cp file.jar app.main. The Main class is splitted to Main and Main$1, but that shouldn't be a problem I hope. When trying with a class only calling the other main (and therefore is not splitted) it gives the same result.

**Comment by vinc3nz** [comment] 2023-03-28 15:17
Can anyone of you compile a single class? As for me it fails with an error complaining about my processor and it's architecture but it should be ok. Would be interesting to see if it is an issue only with the jar
#6301

**Comment by kgonia** [comment] 2023-04-28 11:57
I have the same issue. I was able to generate native image with Spring boot starter 3.0.6 yesterday... and now it's not working. I'm unable to tell what change since

**Comment by kgonia** [comment] 2023-04-28 12:23
I found the difference!

working command

`.\mvnw.cmd -Pnative package`

not working command

`.\mvnw.cmd native:compile-no-fork -f pom.xml`

I tried to use second one because of warning

`[WARNING] 'native:build' goal is deprecated. Use 'native:compile-no-fork' instead.`

but it looks like this one isn't working

I see one one in thread is using maven but maybe it will be some clue

**Comment by hendrikdenner** [comment] 2023-04-28 15:43
@oubidar-Abderrahim is the issue resolved, or are you planning on answering again?

**Comment by inpu** [comment] 2023-06-04 12:06
I have the same issue. Simple [repo for test here](https://github.com/inpu/nativebuild-issue).

```
------------------------------------------------------------
Gradle 7.2
------------------------------------------------------------

Build time:   2021-08-17 09:59:03 UTC
Revision:     a773786b58bb28710e3dc96c4d1a7063628952ad

Kotlin:       1.5.21
Groovy:       3.0.8
Ant:          Apache Ant(TM) version 1.10.9 compiled on September 27 2020
JVM:          17.0.7 (GraalVM Community 17.0.7+7-jvmci-22.3-b18)
OS:           Linux 5.19.0-43-generic amd64
```

build:
```
./gradlew build

BUILD SUCCESSFUL in 1s
4 actionable tasks: 4 up-to-date
```

Run app:
```
./gradlew clean bootRun

> Task :bootRun

  .   ____          _            __ _ _
 /\\ / ___'_ __ _ _(_)_ __  __ _ \ \ \ \
( ( )\___ | '_ | '_| | '_ \/ _` | \ \ \ \
 \\/  ___)| |_)| | | | | || (_| |  ) ) ) )
  '  |____| .__|_| |_|_| |_\__, | / / / /
 =========|_|==============|___/=/_/_/_/
 :: Spring Boot ::                (v2.4.5)

2023-06-04 15:04:11.966  INFO 25862 --- [           main] org.ntbuild.Main                         : Starting Main using Java 17.0.7 on nt with PID 25862 
2023-06-04 15:04:11.968  INFO 25862 --- [           main] org.ntbuild.Main                         : No active profile set, falling back to default profiles: default
2023-06-04 15:04:12.219  INFO 25862 --- [           main] org.ntbuild.Main                         : Started Main in 0.47 seconds (JVM running for 0.674)
Hello world!!!

BUILD SUCCESSFUL in 1s
5 actionable tasks: 4 executed, 1 up-to-date


```

./gradlew nativeCompile
```
...
========================================================================================================================
GraalVM Native Image: Generating 'nativebuild-issue' (executable)...
========================================================================================================================
[1/7] Initializing...                                                                                    (0,0s @ 0,28GB)
Error: Main entry point class 'org.ntbuild.Main' neither found on the classpath nor on the modulepath.
```

But class org.ntbuild.Main is present in nativecompile-classpath-1.0-SNAPSHOT.jar

**Comment by fniephaus** [comment] 2023-07-06 11:53
I am improving the error message so that it always include info about the classpath and modulepath (see https://github.com/oracle/graal/pull/6942/commits/747bd2b46b915968b6bb339ca076b6ae4f855c66).

It seems that for some reason, both paths are empty in your reproducer. Maybe @sdeleuze could help figure out why that would be the case. I also see a `nativecompile-classpath-1.0-SNAPSHOT.jar` and it does include a `org.ntbuild.Main`, but in the `BOOT-INF` directory:
```bash
nativebuild-issue$ jar tf ./build/libs/nativecompile-classpath-1.0-SNAPSHOT.jar | grep Main
BOOT-INF/classes/org/ntbuild/Main.class
org/springframework/boot/loader/MainMethodRunner.class
```

Is this expected? Should users ever be setting the main entry point in Spring Boot apps, @sdeleuze?

**Comment by sdeleuze** [comment] 2023-07-07 09:31
This project is using Spring Boot 2.4 which does not support native image. It should use at least Spring Boot 3.

**Comment by fniephaus** [comment] 2023-07-07 10:05
Thank you, @sdeleuze! Given that the reproducer uses an old SB version without Native Image support, and the fact that we've improved the error message to always show module and classpath, I'm closing this ticket. Feel free to add any comments in case something isn't clear.

**Closed by fniephaus** 2023-07-07 10:05 UTC
Labels: bug, spring

**Comment by Nefariusmag** [comment] 2023-07-16 07:48
The same problem, but use Spring Boot 3.1

**Comment by anastasiya-asenchik** [comment] 2023-07-19 14:53
Hi all,

Having the same problem, Spring Boot version is 3.0.8, GraalVm version is 23.0.0 and Java version is 17.

**Comment by anastasiya-asenchik** [comment] 2023-07-20 15:34
Update to my previous comment:

Found some workarounds for creating native image with spring and adding it to Docker container. For everyone interested pushed my pet project to github: [graalvm-project](https://github.com/anastasiya-asenchik/graalvm-project)

**Comment by YeudaBy** [comment] 2023-07-28 02:25
I have the same issue with micronout 3.9.2.

**Comment by sdeleuze** [comment] 2023-08-01 07:33
You can't just do `native-image -jar graalvm-project-0.0.1-SNAPSHOT.jar` with a Spring Boot application, the executable JAR structure is not understood by `native-image`.

**Comment by anastasiya-asenchik** [comment] 2023-08-01 11:07
> You can't just do `native-image -jar graalvm-project-0.0.1-SNAPSHOT.jar` with a Spring Boot application, the executable JAR structure is not understood by `native-image`.

So the only way to build native image from Spring boot application is to use `mvn -Pnative native:compile` command and then run executable file?

**Comment by sdeleuze** [comment] 2023-10-25 05:09
Please attach a repro to allow us to have a look.

**Comment by lamar666666** [comment] 2023-11-10 06:46
he error message is as follows:


> Unresolveable build extension: Plugin org.graalvm.buildtools:native-maven-plugin:0.9.22 or one of its dependencies could not be resolved: The following artifacts could not be resolved: org.graalvm.sdk:graal-sdk:jar:22.0.0 (absent): Could not transfer artifact org.graalvm.sdk:graal-sdk:jar:22.0.0 from/to central (https://repo.maven.apache.org/maven2): Premature end of Content-Length delimited message body (expected: 623,771; received: 584,704) @



Version based:java17、springboot：3.1.0
This is my Dockerfile file：

```
ROM vegardit/graalvm-maven:latest-java17 as builder

WORKDIR /app

COPY pom.xml /app/
COPY src /app/src/

#Download time link timeout
COPY syft_0.84.0_linux_amd64.tar.gz /app
COPY junit-jupiter-params-5.8.1.jar /app
COPY objectfile-22.0.0.jar /app
COPY groovy-bom-4.0.12.pom.xml /app
COPY objectfile-22.0.0.jar /app

RUN mvn -Pnative native:compile -DskipTests

FROM mirekphd/jenkins-jdk17-on-ubuntu2204:latest

COPY --from=builder /app/target/milvus-native /app/

CMD ["/app/milvus-native"]
```

This is my pom file：
[pom.zip](https://github.com/oracle/graal/files/13316402/pom.zip)

Can someone help me solve the problem？
