### ISSUE TITLE
Throwable.addSuppressed() doesn’t add a suppressed exception

### ISSUE THREAD

**Issue by swankjesse** [oracle/graal#3008] opened 2020-11-21 23:18 UTC
**Describe the issue**
Suppressed exceptions are not retained on Throwable.

**Steps to reproduce the issue**
This is very straightforward to reproduce. Here’s a very standard `build.gradle`:

`build.gradle:`
```
plugins {
  id "com.palantir.graal" version "0.7.2"
}

dependencies {
}

graal {
  mainClass "test.SuppressedExceptionTest"
  outputName "SuppressedExceptionTest"
  graalVersion "20.3.0"
  javaVersion "11"
}
```

And a test class:

`src/main/java/test/SuppressedExceptionTest.java`
```
package test;

class SuppressedExceptionTest {
  public static void main(String[] args) {
    Exception exception = new Exception("boom");
    exception.addSuppressed(new Exception("suppressed"));
    if (exception.getSuppressed().length != 1) {
      throw new AssertionError("expected a suppressed exception");
    }
    System.out.println("SUCCESS");
  }
}
```

Then at a shell:
```
$ gradle nativeImage
$ ./build/graal/SuppressedExceptionTest
```

Expected output:
```
SUCCESS
```

Actual output:
```
Exception in thread "main" java.lang.AssertionError: expected a suppressed exception
	at test.SuppressedExceptionTest.main(SuppressedExceptionTest.java:8)
```

**Describe GraalVM and your environment:**
 - GraalVM: 20.3.0
 - JDK: jdk-11.0.6
 - OS: macOS 10.15.7 Catalina
 - Architecture: 2.4 GHz 8-Core Intel Core i9

**Comment by oubidar-Abderrahim** [comment] 2020-11-24 09:44
The issue is tracked internally on GR-27667

**Comment by christianwimmer** [comment] 2020-12-04 05:14
That was a historic restriction that is no longer necessary. Fixed in https://github.com/oracle/graal/commit/12011052a067fd0dfd195e37856147e0a70f89e0

**Closed by christianwimmer** 2020-12-04 05:14 UTC
Labels: bug, native-image
