### ISSUE TITLE
Binary size increases more than 2x with option -H:+ReportUnsupportedElementsAtRuntime

### ISSUE THREAD

**Issue by borkdude** [oracle/graal#410] opened 2018-05-07 18:56 UTC
I compiled [this clojure project](https://gitlab.com/konrad.mrozek/cljfmt-graalvm) using `native-image` without and with the option `-H:+ReportUnsupportedElementsAtRuntime`.

Compiled without the option:

```
-rwxr-xr-x   1 Borkdude  staff  9408992 May  4 13:04 cljfmt
```

Compiled with the option:
```
-rwxr-xr-x   1 Borkdude  staff  23209488 May  7 09:52 cljfmt
```

As you can see the size increases more than 2x with the option. I had a discussion about this with https://twitter.com/cstancu and he suggested I post an issue about this, so here we go.

I'm running GraalVM EE 1.0.0-rc1 on MacOS High Sierra 10.13.4

**Comment by Peter-B-Kessler** [comment] 2018-05-07 22:06
I do *not* see this result when building the JavaScript image on GraalVM EE on MacOS El Capitan (10.11.6).
```
Darwin $ ./native-image --language:js -H:Name=svmbuild/js-image
....
Darwin $ ./native-image --language:js -H:+ReportUnsupportedElementsAtRuntime -H:Name=svmbuild/js-image+ReportUnsupportedElementsAtRuntime
....
Darwin ls -l svmbuild/js-image*
-rwxr-xr-x  1 pbkessle  staff  74187912 May  7 14:37 svmbuild/js-image
-rwxr-xr-x  1 pbkessle  staff  74188016 May  7 14:39 svmbuild/js-image+ReportUnsupportedElementsAtRuntime
```
The image built with `-H:+ReportUnsupportedElementsAtRuntime` is slightly larger, but not enough to complain about.

I get similar results on Linux.

**Comment by borkdude** [comment] 2018-05-08 07:16
I'm not complaining, just reporting. Also, what would be the reason for 2x size? I attached the jar file in question, so you don't have to install leiningen (the Clojure build toold).

[cljfmt-graalvm-0.1.0-SNAPSHOT-standalone.jar.zip](https://github.com/oracle/graal/files/1982701/cljfmt-graalvm-0.1.0-SNAPSHOT-standalone.jar.zip)

**Comment by thomaswue** [comment] 2018-05-08 13:07
Thanks for posting @borkdude. This is indeed unexpected. Would assume this has to be the same size.

**Comment by cstancu** [comment] 2019-03-14 22:54
@borkdude thank you for your report. I am closing this issue as I cannot reproduce it anymore. If there ever was a problem it has been fixed in the meantime.
```
$ native-image -jar target/cljfmt-graalvm-0.1.0-SNAPSHOT-standalone.jar -H:Name="cljfmt"
...
$ native-image --report-unsupported-elements-at-runtime -jar target/cljfmt-graalvm-0.1.0-SNAPSHOT-standalone.jar -H:Name="cljfmt-report-enabled"
...
$ ls -l
...
-rwxrwxr-x 1 cdrtz cdrtz 8256624 Mar 14 15:48 cljfmt
-rwxrwxr-x 1 cdrtz cdrtz 8256624 Mar 14 15:49 cljfmt-report-enabled
...
```

**Closed by cstancu** 2019-03-14 22:54 UTC
Labels: bug, substrate
