### ISSUE TITLE
[native-image] llvm (*env)->ThrowNew fails

### ISSUE THREAD

**Issue by johanvos** [oracle/graal#2090] opened 2020-01-22 19:21 UTC
When using llvm, calling` (*env)->ThrowNew` from native code fails

Java app:
```
package hello;

import java.net.SocketTimeoutException;

public class HelloWorld {

    public static void main(String[] args) {
        HelloWorld hw = new HelloWorld();
        hw.doJava();
    }

    public void doJava() {
        try {
            System.out.println("Hello World!!");
            System.loadLibrary("native");
            doSomething();
        }
        catch (SocketTimeoutException ste) {
            System.err.println("All good, we got a SocketTimeoutException");
            ste.printStackTrace();
        } catch (Exception e) {
            System.err.println("NOT good, we got another Exception");
            e.printStackTrace();
        }
    }

    public native void doSomething() throws SocketTimeoutException;

}

```

native code:
```
#include "jni.h"
#include <stdio.h>

JNIEXPORT jint JNICALL
JNI_OnLoad_native(JavaVM *vm, void *reserved)
{
#ifdef JNI_VERSION_1_8
    JNIEnv *env;
    if ((*vm)->GetEnv(vm, (void **)&env, JNI_VERSION_1_8) != JNI_OK) {
        return JNI_VERSION_1_4;
    }
    return JNI_VERSION_1_8;
#else
    return JNI_VERSION_1_4;
#endif
}

void throwByName(JNIEnv *env, const char *name, const char *msg)
{
    jclass cls = (*env)->FindClass(env, name);
    if (cls != 0) (*env)->ThrowNew(env, cls, msg);
}

JNIEXPORT void JNICALL Java_hello_HelloWorld_doSomething(JNIEnv *env, jobject obj) {
    fprintf(stderr, "in native, throw a sockettimeout now\n");
    throwByName(env, "java/net/SocketTimeoutException", "waiting for too long");
}
```

output when running on mac:

```
Hello World!!
in native, throw a sockettimeout now
thrownew
classhandle = 0x10085ddc8
clazz = java.lang.Class@0x113abddc8 : java.net.SocketTimeoutException
ctor = 0x7f6790
messageHandle = 0x4
env = 0x7fd9cd808b60
funcs = 0x113a83d28
NewObjectWithObjectArgFP = 0x10d8b7880
ex = 0x5
All good, we got a SocketTimeoutException
java.net.SocketTimeoutException: waiting for too long
	at com.oracle.svm.jni.JNIJavaCallWrappers.jniInvoke_VARARGS:Ljava_net_SocketTimeoutException_2_0002e_0003cinit_0003e_00028Ljava_lang_String_2_00029V(JNIJavaCallWrappers.java:0)
	at com.oracle.svm.jni.functions.JNIFunctions$NewObjectWithObjectArgFunctionPointer.invoke(JNIFunctions.java)
	at com.oracle.svm.jni.functions.JNIFunctions.ThrowNew(JNIFunctions.java:802)
	at hello.HelloWorld.doSomething(HelloWorld.java)
	at hello.HelloWorld.doJava(HelloWorld.java:42)
	at hello.HelloWorld.main(HelloWorld.java:35)

```

output when running on ios after compilation with LLVM:

```
[Wed Jan 22 20:07:14 CET 2020][INFO] [SUB] Hello World!!
[Wed Jan 22 20:07:14 CET 2020][INFO] [SUB] in native, throw a sockettimeout now
[Wed Jan 22 20:07:14 CET 2020][INFO] [SUB] thrownew
[Wed Jan 22 20:07:14 CET 2020][INFO] [SUB] classhandle = 0x6
[Wed Jan 22 20:07:14 CET 2020][INFO] [SUB] clazz = java.lang.Class@0x10159fb58 : java.net.SocketTimeoutException
[Wed Jan 22 20:07:14 CET 2020][INFO] [SUB] ctor = 0x10155b8f8
[Wed Jan 22 20:07:14 CET 2020][INFO] [SUB] messageHandle = 0x7
[Wed Jan 22 20:07:14 CET 2020][INFO] [SUB] env = 0x2833b8a80
[Wed Jan 22 20:07:14 CET 2020][INFO] [SUB] funcs = 0x1014ac530
[Wed Jan 22 20:07:14 CET 2020][INFO] [SUB] NewObjectWithObjectArgFP = 0x10021a63c
[Wed Jan 22 20:07:14 CET 2020][INFO] [SUB] major issue in getObject
[Wed Jan 22 20:07:14 CET 2020][INFO] [SUB] invalid object handle at 0x17004ab30
[Wed Jan 22 20:07:14 CET 2020][INFO] [SUB] NOT good, we got another Exception
[Wed Jan 22 20:07:14 CET 2020][INFO] [SUB] java.lang.RuntimeException: Invalid object handle
[Wed Jan 22 20:07:14 CET 2020][INFO] [SUB] 	at com.oracle.svm.jni.JNIObjectHandles.getObject(JNIObjectHandles.java:132)
[Wed Jan 22 20:07:14 CET 2020][INFO] [SUB] 	at com.oracle.svm.jni.JNIGeneratedMethodSupport.unboxHandle(JNIGeneratedMethodSupport.java:77)
[Wed Jan 22 20:07:14 CET 2020][INFO] [SUB] 	at com.oracle.svm.jni.JNIJavaCallWrappers.jniInvoke_VARARGS:Ljava_net_SocketTimeoutException_2_0002e_0003cinit_0003e_00028Ljava_lang_String_2_00029V(JNIJavaCallWrappers.java:0)
[Wed Jan 22 20:07:14 CET 2020][INFO] [SUB] 	at com.oracle.svm.jni.functions.JNIFunctions$NewObjectWithObjectArgFunctionPointer.invoke(JNIFunctions.java)
[Wed Jan 22 20:07:14 CET 2020][INFO] [SUB] 	at com.oracle.svm.jni.functions.JNIFunctions.ThrowNew(JNIFunctions.java:802)
[Wed Jan 22 20:07:14 CET 2020][INFO] [SUB] 	at hello.HelloWorld.doSomething(HelloWorld.java)
[Wed Jan 22 20:07:14 CET 2020][INFO] [SUB] 	at hello.HelloWorld.doJava(HelloWorld.java:42)
[Wed Jan 22 20:07:14 CET 2020][INFO] [SUB] 	at hello.HelloWorld.main(HelloWorld.java:35)
[Wed Jan 22 20:07:14 CET 2020][INFO] [SUB] [GVM] Finished running GVM, done with isolatehread
```

The additional debug info comes from debug info I added in GraalVM:
```
diff --git a/substratevm/src/com.oracle.svm.jni/src/com/oracle/svm/jni/JNIObjectHandles.java b/substratevm/src/com.oracle.svm.jni/src/com/oracle/svm/jni/JNIObjectHandles.java
index b95c534c01a..94f119ab0cc 100644
--- a/substratevm/src/com.oracle.svm.jni/src/com/oracle/svm/jni/JNIObjectHandles.java
+++ b/substratevm/src/com.oracle.svm.jni/src/com/oracle/svm/jni/JNIObjectHandles.java
@@ -24,6 +24,7 @@
  */
 package com.oracle.svm.jni;
 
+import com.oracle.svm.core.log.Log;
 import org.graalvm.compiler.api.replacements.Fold;
 import org.graalvm.compiler.word.Word;
 import org.graalvm.nativeimage.CurrentIsolate;
@@ -125,6 +126,9 @@ public final class JNIObjectHandles {
         if (JNIGlobalHandles.isInRange(handle)) {
             return JNIGlobalHandles.getObject(handle);
         }
+        Log log = Log.log().autoflush(true);
+        log.string("major issue in getObject").newline();
+        log.string("invalid object handle at ").hex(handle).newline();
         throw new RuntimeException("Invalid object handle");
     }
 
diff --git a/substratevm/src/com.oracle.svm.jni/src/com/oracle/svm/jni/functions/JNIFunctions.java b/substratevm/src/com.oracle.svm.jni/src/com/oracle/svm/jni/functions/JNIFunctions.java
index 2a227f2686e..040d4427a11 100644
--- a/substratevm/src/com.oracle.svm.jni/src/com/oracle/svm/jni/functions/JNIFunctions.java
+++ b/substratevm/src/com.oracle.svm.jni/src/com/oracle/svm/jni/functions/JNIFunctions.java
@@ -785,11 +785,22 @@ final class JNIFunctions {
     @CEntryPoint(exceptionHandler = JNIExceptionHandlerReturnZero.class)
     @CEntryPointOptions(prologue = JNIEnvEnterReturnEDetachedOnFailurePrologue.class, publishAs = Publish.NotPublished, include = CEntryPointOptions.NotIncludedAutomatically.class)
     static int ThrowNew(JNIEnvironment env, JNIObjectHandle clazzHandle, CCharPointer message) throws Throwable {
+        Log log = Log.log().autoflush(true);
+        log.string("thrownew").newline();
+        log.string("classhandle = ").hex(clazzHandle).newline();
         Class<?> clazz = JNIObjectHandles.getObject(clazzHandle);
+        log.string("clazz = ").object(clazz).string(" : ").string(clazz.getName()).newline();
         JNIMethodId ctor = Support.getMethodID(clazz, "<init>", "(Ljava/lang/String;)V", false);
+        log.string("ctor = ").hex(ctor).newline();
         JNIObjectHandle messageHandle = NewStringUTF(env, message);
+        log.string("messageHandle = ").hex(messageHandle).newline();
+        log.string("env = ").hex(env).newline();
+        log.string("funcs = ").hex(env.getFunctions()).newline();
+//        log.string("funcs = ").string(env.getFunctions().getClass().getName()).newline();
         NewObjectWithObjectArgFunctionPointer newObject = (NewObjectWithObjectArgFunctionPointer) env.getFunctions().getNewObject();
+        log.string("NewObjectWithObjectArgFP = ").hex(newObject).newline();
         JNIObjectHandle exception = newObject.invoke(env, clazzHandle, ctor, messageHandle);
+        log.string("ex = ").hex(exception).newline();
         throw (Throwable) JNIObjectHandles.getObject(exception);
     }

```

**Comment by vjovanov** [comment] 2020-01-27 16:15
From a previous discussion with @johanvos:
The Invalid object handle issue (which leads to an issue when e.g. throwing a SocketTimeoutException from native code (in libnet.a)) comes from an invalid handle passed to JNIGeneratedMethodSupport.unboxHandle and I think there is a fair chance that this is called by code that is generated by JNIJavaCallWrapperMethod.loadAndUnboxArguments since that one has a number of calls to said unboxHandle method in a block that is checked for iOS and Windows:
9:56
      // Windows CallVariant.VA_LIST is identical to CallVariant.ARRAY
        // iOS CallVariant.VARARGS stores values as an array on the stack
        if ((OS.getCurrent() == OS.DARWIN && Platform.includedIn(Platform.AARCH64.class) && callVariant == CallVariant.VARARGS) ||
                        (OS.getCurrent() == OS.WINDOWS && callVariant == CallVariant.VA_LIST) || callVariant == CallVariant.ARRAY) {

**Comment by lazar-mitrovic** [comment] 2020-01-29 16:26
Issue is not reproducible on Android
```
[Wed Jan 29 17:23:08 CET 2020][INFO] [SUB] D/GraalCompiled( 7727): Hello World!!
[Wed Jan 29 17:23:08 CET 2020][INFO] [SUB] E/GraalGluon( 7727): launcher, nativeSurfaceRedrawNeeded called. Invoke method on glass_monocle
[Wed Jan 29 17:23:08 CET 2020][INFO] [SUB] D/GraalCompiled( 7727): in native, throw a sockettimeout now
[Wed Jan 29 17:23:08 CET 2020][INFO] [SUB] D/GraalCompiled( 7727): All good, we got a SocketTimeoutException
[Wed Jan 29 17:23:08 CET 2020][INFO] [SUB] D/GraalCompiled( 7727): 
[Wed Jan 29 17:23:08 CET 2020][INFO] [SUB] D/GraalCompiled( 7727): java.net.SocketTimeoutException: waiting for too long
[Wed Jan 29 17:23:08 CET 2020][INFO] [SUB] D/GraalCompiled( 7727): 
[Wed Jan 29 17:23:08 CET 2020][INFO] [SUB] D/GraalCompiled( 7727):      at com.oracle.svm.jni.JNIJavaCallWrappers.jniInvoke_VARARGS:Ljava_net_SocketTimeoutException_2_0002e_0003cinit_0003e_00028Ljav
[Wed Jan 29 17:23:08 CET 2020][INFO] [SUB] D/GraalCompiled( 7727): a_lang_String_2_00029V(JNIJavaCallWrappers.java:0)
[Wed Jan 29 17:23:08 CET 2020][INFO] [SUB] D/GraalCompiled( 7727): 
[Wed Jan 29 17:23:08 CET 2020][INFO] [SUB] D/GraalCompiled( 7727):      at com.oracle.svm.jni.functions.JNIFunctions$NewObjectWithObjectArgFunctionPointer.invoke(JNIFunctions.java)
[Wed Jan 29 17:23:08 CET 2020][INFO] [SUB] D/GraalCompiled( 7727): 
[Wed Jan 29 17:23:08 CET 2020][INFO] [SUB] D/GraalCompiled( 7727):      at com.oracle.svm.jni.functions.JNIFunctions.ThrowNew(JNIFunctions.java:792)
[Wed Jan 29 17:23:08 CET 2020][INFO] [SUB] D/GraalCompiled( 7727): 
[Wed Jan 29 17:23:08 CET 2020][INFO] [SUB] D/GraalCompiled( 7727):      at hello.HelloWorld.doSomething(HelloWorld.java)
[Wed Jan 29 17:23:08 CET 2020][INFO] [SUB] D/GraalCompiled( 7727): 
[Wed Jan 29 17:23:08 CET 2020][INFO] [SUB] D/GraalCompiled( 7727):      at hello.HelloWorld.doJava(HelloWorld.java:16)
[Wed Jan 29 17:23:08 CET 2020][INFO] [SUB] D/GraalCompiled( 7727): 
[Wed Jan 29 17:23:08 CET 2020][INFO] [SUB] D/GraalCompiled( 7727):      at hello.HelloWorld.main(HelloWorld.java:9)
[Wed Jan 29 17:23:08 CET 2020][INFO] [SUB] D/GraalCompiled( 7727): 
```

**Comment by lazar-mitrovic** [comment] 2020-02-03 17:08
This could be relevant: [link](https://developer.apple.com/library/archive/documentation/Xcode/Conceptual/iPhoneOSABIReference/Articles/ARM64FunctionCallingConventions.html#//apple_ref/doc/uid/TP40013702-SW3)

> In the generic procedure call standard, all function arguments passed on the stack consume slots in multiples of 8 bytes. In iOS, this requirement is dropped, and values consume only the space required. For example, on entry to the function in Listing 1, s0 occupies 1 byte at sp and s1 occupies 1 byte at sp+1. Padding is still inserted on the stack to satisfy arguments’ alignment requirements.

> The generic procedure call standard requires that arguments with 16-byte alignment passed in integer registers begin at an even-numbered xN, skipping a previous odd-numbered xN if necessary. The iOS ABI drops this requirement. For example, in Listing 2, the parameter x1_x2 does indeed get passed in x1 and x2 instead of x2 and x3.

> The general ABI specifies that it is the callee’s responsibility to sign or zero-extend arguments having fewer than 32 bits, and that unused bits in a register are unspecified. In iOS, however, the caller must perform such extensions, up to 32 bits.

**Comment by loicottet** [comment] 2020-02-19 08:54
Fixed by [70df79](https://github.com/oracle/graal/commit/70df793378acdf08a9baceffb8676ed78c57f80b)

**Closed by loicottet** 2020-02-19 08:54 UTC
Labels: native-image
