### ISSUE TITLE
Native image not running successfully with Spring Boot version 3.0.6

### ISSUE THREAD

**Issue by BullyWiiPlaza** [oracle/graal#6500] opened 2023-04-26 13:57 UTC
**Describe the issue**
When I try to compile my Spring Boot version `3.0.6` REST API to a native image on Windows, I get an exception upon running the project. The same project runs fine using Spring Boot version `3.0.5`.

**Steps to reproduce the issue**
Check out [this](https://stackoverflow.com/questions/76110898) question on StackOverflow for more details.

**Describe GraalVM and your environment:**
 - GraalVM version: `graalvm-ee-java19-windows-amd64-22.3.1`
 - JDK major version: `19`
 - OS:  `Windows 11 Pro`
 - Architecture: `AMD64`

**Comment by fniephaus** [comment] 2023-04-27 07:35
Thanks for the report, @BullyWiiPlaza. @sdeleuze could you take a look at this please?

**Comment by sdeleuze** [comment] 2023-04-27 08:15
Likely a duplicate of https://github.com/oracle/graalvm-reachability-metadata/issues/273 so I close it.

**Closed by sdeleuze** 2023-04-27 08:15 UTC
Labels: bug
