### ISSUE TITLE
[native-image] Netty Vert.x PoC - NoSuchMethodException

### ISSUE THREAD

**Issue by Jotschi** [oracle/graal#1261] opened 2019-05-10 20:59 UTC
I have just updated the PoC project I created a while ago to utilize GraalVM 19. I have also applied the latest changes which were suggested by @vjovanov in https://github.com/netty/netty/pull/9118

Building works just fine using:

```
native-image \
 --verbose \
 --no-server \
 --allow-incomplete-classpath \
 -Dio.netty.noUnsafe=true \
 -H:Name=hello-world \
 --initialize-at-build-time=io.netty \
 --initialize-at-build-time=io.vertx \
 --initialize-at-build-time=ch.qos.logback \
 --initialize-at-build-time=org.slf4j \
 --initialize-at-build-time=com.fasterxml.jackson \
 --initialize-at-run-time=io.netty.handler.codec.http.HttpObjectEncoder,io.netty.handler.codec.http.websocketx.WebSocket00FrameEncoder \
 -H:+ReportUnsupportedElementsAtRuntime \
 -Dfile.encoding=UTF-8 \
 --no-fallback \
 -jar target/vertx-graalvm-native-image-test-0.0.1-SNAPSHOT.jar
```
I however get a `NoSuchMethodException` during runtime which I can't really explain. I double checked all classes involved. The signatures seem to be okay.

```
java.lang.NoSuchMethodException: io.netty.channel.DefaultChannelPipeline$TailContext.channelRegistered(io.netty.channel.ChannelHandlerContext)
        at java.lang.Class.getMethod(DynamicHub.java:973)
        at io.netty.channel.ChannelHandlerMask$2.run(ChannelHandlerMask.java:166)
        at io.netty.channel.ChannelHandlerMask$2.run(ChannelHandlerMask.java:163)
        at java.security.AccessController.doPrivileged(AccessController.java:83)
        at io.netty.channel.ChannelHandlerMask.isSkippable(ChannelHandlerMask.java:163)
        at io.netty.channel.ChannelHandlerMask.mask0(ChannelHandlerMask.java:91)
        at io.netty.channel.ChannelHandlerMask.mask(ChannelHandlerMask.java:76)
        at io.netty.channel.AbstractChannelHandlerContext.<init>(AbstractChannelHandlerContext.java:104)
        at io.netty.channel.DefaultChannelPipeline$TailContext.<init>(DefaultChannelPipeline.java:1246)
        at io.netty.channel.DefaultChannelPipeline.<init>(DefaultChannelPipeline.java:97)
        at io.netty.channel.AbstractChannel.newChannelPipeline(AbstractChannel.java:119)
        at io.netty.channel.AbstractChannel.<init>(AbstractChannel.java:86)
        at io.netty.bootstrap.FailedChannel.<init>(FailedChannel.java:33)
        at io.netty.bootstrap.AbstractBootstrap.initAndRegister(AbstractBootstrap.java:330)
        at io.netty.bootstrap.AbstractBootstrap.register(AbstractBootstrap.java:234)
        at io.netty.resolver.dns.DnsNameResolver.<init>(DnsNameResolver.java:420)
        at io.netty.resolver.dns.DnsNameResolverBuilder.build(DnsNameResolverBuilder.java:430)
        at io.vertx.core.impl.resolver.DnsResolverProvider$1$1.newNameResolver(DnsResolverProvider.java:186)
        at io.netty.resolver.dns.DnsAddressResolverGroup.newResolver(DnsAddressResolverGroup.java:94)
        at io.netty.resolver.dns.DnsAddressResolverGroup.newResolver(DnsAddressResolverGroup.java:79)
        at io.netty.resolver.AddressResolverGroup.getResolver(AddressResolverGroup.java:69)
        at io.vertx.core.impl.resolver.DnsResolverProvider$1.newResolver(DnsResolverProvider.java:190)
        at io.netty.resolver.AddressResolverGroup.getResolver(AddressResolverGroup.java:69)
        at io.vertx.core.impl.AddressResolver.resolveHostname(AddressResolver.java:82)
        at io.vertx.core.impl.VertxImpl.resolveAddress(VertxImpl.java:804)
        at io.vertx.core.net.impl.AsyncResolveConnectHelper.doBind(AsyncResolveConnectHelper.java:82)
        at io.vertx.core.http.impl.HttpServerImpl.listen(HttpServerImpl.java:304)
        at io.vertx.core.http.impl.HttpServerImpl.listen(HttpServerImpl.java:190)
        at io.vertx.core.http.impl.HttpServerImpl.listen(HttpServerImpl.java:181)
        at de.jotschi.examples.Runner.main(Runner.java:35)
java.lang.IllegalStateException: failed to create a new resolver
        at io.netty.resolver.AddressResolverGroup.getResolver(AddressResolverGroup.java:72)
        at io.vertx.core.impl.resolver.DnsResolverProvider$1.newResolver(DnsResolverProvider.java:190)
        at io.netty.resolver.AddressResolverGroup.getResolver(AddressResolverGroup.java:69)
        at io.vertx.core.impl.AddressResolver.resolveHostname(AddressResolver.java:82)
        at io.vertx.core.impl.VertxImpl.resolveAddress(VertxImpl.java:804)
        at io.vertx.core.net.impl.AsyncResolveConnectHelper.doBind(AsyncResolveConnectHelper.java:82)
        at io.vertx.core.http.impl.HttpServerImpl.listen(HttpServerImpl.java:304)
        at io.vertx.core.http.impl.HttpServerImpl.listen(HttpServerImpl.java:190)
        at io.vertx.core.http.impl.HttpServerImpl.listen(HttpServerImpl.java:181)
        at de.jotschi.examples.Runner.main(Runner.java:35)
Caused by: java.lang.NoSuchMethodException: io.netty.channel.DefaultChannelPipeline$TailContext.channelRegistered(io.netty.channel.ChannelHandlerContext)
        at java.lang.Class.getMethod(DynamicHub.java:973)
        at io.netty.channel.ChannelHandlerMask$2.run(ChannelHandlerMask.java:166)
        at io.netty.channel.ChannelHandlerMask$2.run(ChannelHandlerMask.java:163)
        at java.security.AccessController.doPrivileged(AccessController.java:83)
        at io.netty.channel.ChannelHandlerMask.isSkippable(ChannelHandlerMask.java:163)
        at io.netty.channel.ChannelHandlerMask.mask0(ChannelHandlerMask.java:91)
        at io.netty.channel.ChannelHandlerMask.mask(ChannelHandlerMask.java:76)
        at io.netty.channel.AbstractChannelHandlerContext.<init>(AbstractChannelHandlerContext.java:104)
        at io.netty.channel.DefaultChannelPipeline$TailContext.<init>(DefaultChannelPipeline.java:1246)
        at io.netty.channel.DefaultChannelPipeline.<init>(DefaultChannelPipeline.java:97)
        at io.netty.channel.AbstractChannel.newChannelPipeline(AbstractChannel.java:119)
        at io.netty.channel.AbstractChannel.<init>(AbstractChannel.java:86)
        at io.netty.bootstrap.FailedChannel.<init>(FailedChannel.java:33)
        at io.netty.bootstrap.AbstractBootstrap.initAndRegister(AbstractBootstrap.java:330)
        at io.netty.bootstrap.AbstractBootstrap.register(AbstractBootstrap.java:234)
        at io.netty.resolver.dns.DnsNameResolver.<init>(DnsNameResolver.java:420)
        at io.netty.resolver.dns.DnsNameResolverBuilder.build(DnsNameResolverBuilder.java:430)
        at io.vertx.core.impl.resolver.DnsResolverProvider$1$1.newNameResolver(DnsResolverProvider.java:186)
        at io.netty.resolver.dns.DnsAddressResolverGroup.newResolver(DnsAddressResolverGroup.java:94)
        at io.netty.resolver.dns.DnsAddressResolverGroup.newResolver(DnsAddressResolverGroup.java:79)
        at io.netty.resolver.AddressResolverGroup.getResolver(AddressResolverGroup.java:69)
        ... 9 more
```

Build Logs: https://gist.github.com/Jotschi/3d3d96dcb376a2f6afad6a3f9c277d6b
Project: https://github.com/Jotschi/vertx-graalvm-native-image-test/tree/graalvm-19

**Comment by vjovanov** [comment] 2019-05-10 21:20
Have you tried refining the reflection configuration? This seems like reflection was not configured correctly. 

You can try using the new agent to get the right config:

  https://github.com/oracle/graal/blob/master/substratevm/CONFIGURE.md

**Comment by pmlopes** [comment] 2019-05-10 21:22
@vjovanov this issue reproduces the netty DNS problem I messaged you before. So it looks like we're missing some metadata or substitution there.

**Comment by Jotschi** [comment] 2019-05-10 21:23
Adding ` -Dvertx.disableDnsResolver=true` to the execution of the image will workaround the _netty DNS problem_ but the initial NoSuchMethodException remains. I'll take a look at the reflection configuration.

**Comment by vjovanov** [comment] 2019-05-10 21:47
I think it is just the reflection configuration. You can have multiple runs now with different configurations (e.g., one with DNS and one without). Simply aggregate those configs and all should work.

**Comment by Jotschi** [comment] 2019-05-10 22:22
@vjovanov Thanks for the hint. The agent is really helpful. I however get:

```
SEVERE: java.lang.NoSuchMethodException: io.netty.bootstrap.ServerBootstrap$1.channelRegistered(io.netty.channel.ChannelHandlerContext)
```
The agent does not generate a reflection config for this class. I assume it is an anonymous inner class of ServerBootstrap. I'm currently trying to add the reflection config but so far I was not successful.

**Comment by vjovanov** [comment] 2019-05-10 22:26
@peter-hofer any idea why this could be happening? Is there any special treatment of inner classes in the agent or reflection?

**Comment by Jotschi** [comment] 2019-05-10 22:28
@vjovanov 
https://gist.github.com/Jotschi/9aa9f44653e1d004b875bab0a10c1575

**Comment by vjovanov** [comment] 2019-05-10 22:30
I don't see `io.netty.bootstrap.ServerBootstrap$1` with a method `channelRegistered` in the config.

**Comment by Jotschi** [comment] 2019-05-10 22:34
@vjovanov Adding

```
  {
    "name":"io.netty.bootstrap.ServerBootstrap$1",
    "methods":[
      {"name":"channelRegistered","parameterTypes":["io.netty.channel.ChannelHandlerContext"] }
    ]
  },
```
results in:

```
Error: Error parsing reflection configuration in jar:file:/home/jotschi/workspaces/mesh/vertx-graalvm-native-image-test/target/vertx-graalvm-native-image-test-0.0.1-SNAPSHOT.jar!/META-INF/native-image/io.netty/transport/reflection-config.json:
Method io.netty.bootstrap.ServerBootstrap$1.channelRegistered(ChannelHandlerContext) not found
Verify that the configuration matches the schema described in the -H:PrintFlags=+ output for option ReflectionConfigurationResources.
Error: Use -H:+ReportExceptionStackTraces to print stacktrace of underlying exception
Error: Image build request failed with exit status 1
```

**Comment by Jotschi** [comment] 2019-05-10 23:46
I can however workaround this problem by patching Netty and explicitly listing following method in the AIC.

```
      	@Override
       	public void channelRegistered(ChannelHandlerContext ctx) throws Exception {
       		super.channelRegistered(ctx);
       	}
```

I think the reflection config should also work without changing the class. I have not yet tried whether using `allDeclaredMethods` in the declaration would be another workaround for this.

@pmlopes The same problem also occurred in `io.vertx.core.http.impl.HttpServerImpl#listen` (FYI)

**Comment by pmlopes** [comment] 2019-05-11 12:07
This is a major regression as with `rc16` no flags nor config was needed as long the latest stable netty package was used.

**Comment by pmlopes** [comment] 2019-05-11 12:08
Also note that "patching" netty or vertx in this way is not a fix, as this "patches" will not end up upstream just like that.

**Comment by Jotschi** [comment] 2019-05-11 12:17
@pmlopes I agree. I just wanted to show that explicitly declaring the method will resolve the problem. This information may be useful when debugging the problem.

My last status is that the image builds and can be started. I got it so far that a connection to the socket could be established but no response was send to the client.

**Comment by pmlopes** [comment] 2019-05-11 13:08
@Jotschi @vjovanov I can build a vertx + netty 4.1.30 app with 19.0.0 [hi.zip](https://github.com/oracle/graal/files/3169051/hi.zip) So it should be a matter of flags here. The reproducer attached shows it.

**Comment by Jotschi** [comment] 2019-05-11 13:16
@pmlopes The example works for me too. I'll take a look at my PoC and check whats the difference.

**Comment by Jotschi** [comment] 2019-05-11 13:29
The example app will not build once Netty gets bumped to `4.1.31`.

**Comment by pmlopes** [comment] 2019-05-11 13:40
This example uses a netty version without native image substitutions or properties. With the new netty then the included substitutions and properties must be reviewed...

**Comment by pmlopes** [comment] 2019-05-11 15:53
@Jotschi I've updated the versions on my example, in the `pom.xml` i've changed the vert.x version from `3.7.0.` to `3.7.1-SNAPSHOT`:

```xml
<version>3.7.1-SNAPSHOT</version>
```

Which means it will pull netty `4.1.34.Final` (the last version before the graal specific metadata and substitutions was added) and it still works and builds like before. I do believe that there could be something messed up on later releases as the previous flags + new flags get messed up.

**Comment by peter-hofer** [comment] 2019-05-13 01:58
> @peter-hofer any idea why this could be happening? Is there any special treatment of inner classes in the agent or reflection?
There is no special treatment of inner classes, nor should it be necessary. I tried this code myself, bX the agent write a trace file, and didn't find `ServerBootstrap` anywhere in the trace. I'm not familiar with any of the Netty/Vert.x-specific properties/substitutions/configuration, is it possible that the code just takes a different path on SVM?

**Comment by cvgaviao** [comment] 2019-09-11 14:24
> I don't see `io.netty.bootstrap.ServerBootstrap$1` with a method `channelRegistered` in the config.
> 
> The agent should add this method if it was used.

Seems that the correct class is `io.netty.bootstrap.ServerBootstrap.ServerBootstrapAcceptor` that is a private class and the method `channelRegistered`comes from its parent `io.netty.channel.ChannelInboundHandlerAdapter`

**Comment by spockz** [comment] 2020-05-10 10:22
I am having the same issue with https://github.com/spockz/finatra-graalvm-test/commit/cdd67879030de3b0585a75af952887d2fe5256d0 which is using Netty 4.1.47. @cvgaviao did you manage to fix/work around it in the mean time? I also have the entries you mention above in my reflect-config.json.

**Comment by cvgaviao** [comment] 2020-05-17 22:36
@spockz, unfortunately, no. Also there are other issues preventing netty and vert.x to run as a native image(#1902).

**Comment by jvican** [comment] 2020-11-11 16:10
> @vjovanov Adding
> 
> ```
>   {
>     "name":"io.netty.bootstrap.ServerBootstrap$1",
>     "methods":[
>       {"name":"channelRegistered","parameterTypes":["io.netty.channel.ChannelHandlerContext"] }
>     ]
>   },
> ```
> 
> results in:
> 
> ```
> Error: Error parsing reflection configuration in jar:file:/home/jotschi/workspaces/mesh/vertx-graalvm-native-image-test/target/vertx-graalvm-native-image-test-0.0.1-SNAPSHOT.jar!/META-INF/native-image/io.netty/transport/reflection-config.json:
> Method io.netty.bootstrap.ServerBootstrap$1.channelRegistered(ChannelHandlerContext) not found
> Verify that the configuration matches the schema described in the -H:PrintFlags=+ output for option ReflectionConfigurationResources.
> Error: Use -H:+ReportExceptionStackTraces to print stacktrace of underlying exception
> Error: Image build request failed with exit status 1
> ```

Looks like the latest graalvm native image 20.2 fixed this, so adding the aforementioned missing methods for `io.netty.bootstrap.ServerBootstrap$1` to the `reflect-config.json` file removes the runtime errors. There will be some warnings during image creation but they can safely be ignored.

**Comment by vjovanov** [comment] 2020-11-20 11:15
Excellent, can we close this issue?

**Closed** 2020-11-20 11:18 UTC
Labels: native-image
