### ISSUE TITLE
[native-image] Fails with java.lang.ArrayIndexOutOfBoundsException: -1

### ISSUE THREAD

**Issue by melix** [oracle/graal#430] opened 2018-05-22 14:35 UTC
## Context

Trying to build a native image of the Gradle launcher. This is the very first time I'm trying `native-image`, so there's obviously not a lot of details here. It means that fixing this issue would probably be not enough to generate a working image.

Nevertheless, it can be reproduced by running `native-image` on a Gradle installation.

`/opt/DEV/graalvm-1.0.0-rc1/bin/native-image -cp lib/gradle-launcher-4.9.jar -H:Name=native-gradle -H:Class=org.gradle.launcher.GradleMain -H:+ReportUnsupportedElementsAtRuntime --verbose`

Yields:

```
Build on Server(pid: 30616, port: 26681)
SendBuildRequest [
-task=com.oracle.svm.hosted.NativeImageGeneratorRunner
-imagecp
/opt/DEV/graalvm-1.0.0-rc1/jre/lib/svm/builder/svm.jar:/opt/DEV/graalvm-1.0.0-rc1/jre/lib/svm/builder/pointsto.jar:/opt/DEV/graalvm-1.0.0-rc1/jre/lib/svm/builder/objectfile.jar:/opt/DEV/graalvm-1.0.0-rc1/jre/lib/jvmci/jvmci-api.jar:/opt/DEV/graalvm-1.0.0-rc1/jre/lib/jvmci/graal.jar:/opt/DEV/graalvm-1.0.0-rc1/jre/lib/jvmci/jvmci-hotspot.jar:/opt/DEV/graalvm-1.0.0-rc1/jre/lib/boot/graaljs-scriptengine.jar:/opt/DEV/graalvm-1.0.0-rc1/jre/lib/boot/graal-sdk.jar:/opt/DEV/graalvm-1.0.0-rc1/jre/lib/svm/library-support.jar:/home/cchampeau/DEV/gradle-source-build/lib/gradle-launcher-4.9.jar
-H:Path=/home/cchampeau/DEV/gradle-source-build
-H:Name=native-gradle
-H:Class=org.gradle.launcher.GradleMain
-H:+ReportUnsupportedElementsAtRuntime
-H:CLibraryPath=/opt/DEV/graalvm-1.0.0-rc1/jre/lib/svm/clibraries/linux-amd64
]
   classlist:     158.62 ms
       (cap):     675.37 ms
       setup:     927.45 ms
    analysis:   2,029.47 ms
fatal error: java.lang.ArrayIndexOutOfBoundsException: -1
	at com.oracle.graal.pointsto.flow.MethodFlowsGraph.linkClones(MethodFlowsGraph.java:259)
	at com.oracle.graal.pointsto.flow.MethodTypeFlow.addContext(MethodTypeFlow.java:118)
	at com.oracle.graal.pointsto.flow.StaticInvokeTypeFlow.update(InvokeTypeFlow.java:344)
	at com.oracle.graal.pointsto.BigBang$2.run(BigBang.java:498)
	at com.oracle.graal.pointsto.util.CompletionExecutor.lambda$execute$0(CompletionExecutor.java:172)
	at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1402)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
Error: Processing image build request failed
```

The run above is with a custom Gradle distribution (built from sources / `master`), but I could reproduce the same with a downloaded Gradle 4.7 distribution.

Thanks!

**Comment by cstancu** [comment] 2018-05-22 23:58
Thank you for your report. This is the same problem as https://github.com/oracle/graal/issues/418. It is due to the old JSR/RET subroutines. I reproduced it with Gradle 4.7 which is Java version 49, i.e., Java 1.5. I will push a fix for it soon.

**Comment by melix** [comment] 2018-05-23 11:26
Thanks for the answer. For the record, the launcher jar uses classes version 49 for silly reasons: Gradle only supports running on JDK 7+ (soon JDK 8+ only), but we still want to provide a nice error messages to users who are on older JDKs, so we need to be able to run on JDK 5 to say we need 7 :D

**Comment by cstancu** [comment] 2018-05-24 18:44
The `ArrayIndexOutOfBoundsException` is fixed in https://github.com/oracle/graal/commit/c066358c0cd8e792b82d5d81ed0963b9e950f613. Now the image builds (you can try [building from source](https://github.com/oracle/graal/tree/master/substratevm#quick-start)), however it throws a `NullPointerExceptionAtRuntime` at run time from `org.gradle.internal.installation.CurrentGradleInstallationLocator.locateViaClassLoader(CurrentGradleInstallationLocator.java:37)` since we don't currently have support for class loaders and always return `null` from `java.lang.Class.getClassLoader()`. Returning `null` from `java.lang.Class.getClassLoader()` is legal as per the javadoc:
```
Returns the class loader for the class.  Some implementations may use null to represent the bootstrap class loader. This method will return null in such implementations if this class was loaded by the bootstrap class loader.
```
So our implementation acts as if all the classes are returned by the bootstrap class loader. We should have limited support for `ClassLoader`s soon, i.e., returning a synthetic class loader object to cope with situations like this, and as long as `org.gradle.internal.installation.beacon.InstallationBeacon` is registered using the reflection mechanism it should work. Although in this case it will work even without registering the `InstallationBeacon` class since there is a fail safe mechanism if the class is missing:
```
private static CurrentGradleInstallation locateViaClassLoader(ClassLoader classLoader) {
        Class<?> clazz;
        try {
            clazz = classLoader.loadClass(BEACON_CLASS_NAME);
        } catch (ClassNotFoundException e) {
            clazz = CurrentGradleInstallationLocator.class;
        }
        return locateViaClass(clazz);
}
```

**Closed by cstancu** 2018-05-24 18:44 UTC
Labels: bug, substrate

**Comment by cstancu** [comment] 2018-05-24 19:00
By the way this is the stack trace for the NPE:
```
$ ./native-gradle 
java.lang.NullPointerException
	at java.lang.Throwable.<init>(Throwable.java:250)
	at java.lang.Exception.<init>(Exception.java:54)
	at java.lang.RuntimeException.<init>(RuntimeException.java:51)
	at java.lang.NullPointerException.<init>(NullPointerException.java:60)
	at com.oracle.svm.core.snippets.SnippetRuntime.throwNullPointerException(SnippetRuntime.java:206)
	at org.gradle.internal.installation.CurrentGradleInstallationLocator.locateViaClassLoader(CurrentGradleInstallationLocator.java:37)
	at org.gradle.internal.installation.CurrentGradleInstallationLocator.locate(CurrentGradleInstallationLocator.java:31)
	at org.gradle.internal.installation.CurrentGradleInstallation.locate(CurrentGradleInstallation.java:46)
	at org.gradle.internal.installation.CurrentGradleInstallation.get(CurrentGradleInstallation.java:41)
	at org.gradle.launcher.bootstrap.ProcessBootstrap.runNoExit(ProcessBootstrap.java:46)
	at org.gradle.launcher.bootstrap.ProcessBootstrap.run(ProcessBootstrap.java:37)
	at org.gradle.launcher.GradleMain.main(GradleMain.java:23)
	at com.oracle.svm.reflect.proxies.Proxy_11_GradleMain_main.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.oracle.svm.core.JavaMainWrapper.run(JavaMainWrapper.java:171)
	at Lcom/oracle/svm/core/code/CEntryPointCallStubs;.com_002eoracle_002esvm_002ecore_002eJavaMainWrapper_002erun_0028int_002corg_002egraalvm_002enativeimage_002ec_002etype_002eCCharPointerPointer_0029(generated:0)
```
