### ISSUE TITLE
[native-image][netty] java.lang.NoSuchFieldException: tclass

### ISSUE THREAD

**Issue by vongosling** [oracle/graal#1063] opened 2019-03-13 09:17 UTC
when I build (command :native-image -jar DLedger.jar -H:+ReportExceptionStackTraces )the dledger uber jar[1] into native image, I got the error info like the following:

Build on Server(pid: 69038, port: 62141)
[DLedger:69038]    classlist:   1,005.27 ms
[DLedger:69038]        (cap):   3,174.09 ms
[DLedger:69038]        setup:   3,600.55 ms
[DLedger:69038]     analysis:   3,039.22 ms
Error: Error encountered while parsing io.netty.util.concurrent.DefaultPromise.setValue0(java.lang.Object)
Parsing context:
	parsing io.netty.util.concurrent.DefaultPromise.setFailure0(DefaultPromise.java:543)
	parsing io.netty.util.concurrent.DefaultPromise.setFailure(DefaultPromise.java:119)
	parsing io.netty.channel.DefaultChannelPromise.setFailure(DefaultChannelPromise.java:87)
	parsing io.netty.bootstrap.AbstractBootstrap.initAndRegister(AbstractBootstrap.java:317)
	parsing io.netty.bootstrap.Bootstrap.doConnect(Bootstrap.java:134)
	parsing io.netty.bootstrap.Bootstrap.connect(Bootstrap.java:116)
	parsing org.apache.rocketmq.remoting.netty.NettyRemotingClient.createChannel(NettyRemotingClient.java:485)
	parsing org.apache.rocketmq.remoting.netty.NettyRemotingClient.getAndCreateChannel(NettyRemotingClient.java:407)
	parsing org.apache.rocketmq.remoting.netty.NettyRemotingClient.invokeAsync(NettyRemotingClient.java:522)
...
Original error: org.graalvm.compiler.java.BytecodeParser$BytecodeParserError: com.oracle.svm.core.util.VMError$HostedError: java.lang.NoSuchFieldException: tclass
	at parsing io.netty.util.concurrent.DefaultPromise.setValue0(DefaultPromise.java:547)
	at org.graalvm.compiler.java.BytecodeParser.throwParserError(BytecodeParser.java:2435)

I try to solve the problem by tracking the netty source code, the problem is 
1. the code line prompt is not correct(DefaultPromise.setFailure0 is not in the 543 line)
2. I could not find the tclass filed even though I javap the class file.

Anyone could help me to review the problem, many thanks advance:-)
 

[1] https://github.com/openmessaging/openmessaging-storage-dledger

**Comment by cstancu** [comment] 2019-03-13 18:49
#### Short version: 
This can be solved by adding `-Dio.netty.noUnsafe=true` to your `native-image` command: `native-image  -jar target/DLedger.jar -Dio.netty.noUnsafe=true`.

#### Long version:

Looking at your project dependecies I see that `rocketmq-remoting-4.3.2` brings in  `netty-4.0.42`, an older version of `netty`. Running `mvn dependency:tree` shows:
```
[INFO] +- org.apache.rocketmq:rocketmq-remoting:jar:4.3.2:compile
[INFO] |  +- com.alibaba:fastjson:jar:1.2.51:compile
[INFO] |  +- io.netty:netty-all:jar:4.0.42.Final:compile
[INFO] |  +- org.apache.rocketmq:rocketmq-logging:jar:4.3.2:compile
[INFO] |  \- io.netty:netty-tcnative-boringssl-static:jar:1.1.33.Fork26:compile
...
```
Maybe that's why you saw an inconsistency in the error line.

The problem is with the [`io.netty.util.internal.UnsafeAtomicReferenceFieldUpdater`](https://github.com/netty/netty/blob/netty-4.0.42.Final/common/src/main/java/io/netty/util/internal/UnsafeAtomicReferenceFieldUpdater.java) class. We expect that all classes that extend `AtomicReferenceFieldUpdater` have a [`tclass`](https://github.com/oracle/graal/blob/master/substratevm/src/com.oracle.svm.core/src/com/oracle/svm/core/jdk/RecomputedFields.java#L339) field which is not true for the custom `io.netty.util.internal.UnsafeAtomicReferenceFieldUpdater` used by the [`io.netty.util.concurrent.DefaultPromise.RESULT_UPDATER`](https://github.com/netty/netty/blob/netty-4.0.42.Final/common/src/main/java/io/netty/util/concurrent/DefaultPromise.java#L51) field accessed by `io.netty.util.concurrent.DefaultPromise.setValue0()` method. Threfore, when we try to reflectively access the `tclass` field via reflection we get the `java.lang.NoSuchFieldException: tclass`.

Later versions of `netty` have updated the [`io.netty.util.concurrent.DefaultPromise.RESULT_UPDATER`](https://github.com/netty/netty/blob/netty-4.1.34.Final/common/src/main/java/io/netty/util/concurrent/DefaultPromise.java#L40) to use the standard `java.util.concurrent.atomic.AtomicReferenceFieldUpdater` and this problem goes away. Disabling unsafe in the earlier `netty` version has the same effect, i.e., it uses an `AtomicReferenceFieldUpdater` for the `RESULT_UPDATER`:

```
 static {
        @SuppressWarnings("rawtypes")
        AtomicReferenceFieldUpdater<DefaultPromise, Object> updater =
                PlatformDependent.newAtomicReferenceFieldUpdater(DefaultPromise.class, "result");
        RESULT_UPDATER = updater == null ? AtomicReferenceFieldUpdater.newUpdater(DefaultPromise.class,
                                                                                  Object.class, "result") : updater;
    }
```

#### Addendum
Getting `netty` to run on `native-image` requires a few more settings. You can read more about it in [this article](https://medium.com/graalvm/instant-netty-startup-using-graalvm-native-image-generation-ed6f14ff7692) which comes with [an example](https://github.com/cstancu/netty-native-demo) which provides all the config files and settings that you need.

**Comment by vongosling** [comment] 2019-03-14 03:16
@cstancu Thanks for your kindly explanation. Actually, I have read the article that you provided.  you are right if I hope to native-image netty. that's quite a tedious task. Do your team have any plan to support easily netty native image?

**Comment by cstancu** [comment] 2019-03-14 06:06
@vongosling yes, we aim for full out-of-the-box support for netty in the long run. Some issues will be solved on our side as the project evolves, other issues will probably need changes on the netty side. In the meantime, we plan to roll out a repository that centralizes configurations and substitutions required to make third-party frameworks, such as netty, GraalVM `native-image` compatible and that you can simply use as a maven dependency for your project. This would be an intermediate step, the end goal being to make such a repo obsolete when the third party frameworks adapt and/or integrate GraalVM specific settings and configurations.

I'll close this issue as the `-Dio.netty.noUnsafe=true` option mentioned above fixes the reported problem.

**Closed by cstancu** 2019-03-14 06:06 UTC
Labels: substrate

**Comment by vongosling** [comment] 2019-03-14 06:25
@cstancu Yep, disable noUnsafe config surely resolve my problem.
