### ISSUE TITLE
LINK error when building image on window 2019

### ISSUE THREAD

**Issue by machaval** [oracle/graal#3171] opened 2021-01-30 18:40 UTC
**Describe the issue**

I'm running the build of my project on window 2019.  And it is failing with 

```
LINK : fatal error LNK1171: unable to load mspdbcore.dll (error code: 1455)
	at com.oracle.svm.hosted.image.NativeBootImageViaCC.handleLinkerFailure(NativeBootImageViaCC.java:474)
	at com.oracle.svm.hosted.image.NativeBootImageViaCC.write(NativeBootImageViaCC.java:441)
	at com.oracle.svm.hosted.NativeImageGenerator.doRun(NativeImageGenerator.java:685)
	at com.oracle.svm.hosted.NativeImageGenerator.lambda$run$0(NativeImageGenerator.java:476)
	at java.base/java.util.concurrent.ForkJoinTask$AdaptedRunnableAction.exec(ForkJoinTask.java:1407)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
Error: Image build request failed with exit status 1
```

This build use to run with older 20.x versions of graal. I've updated because I was looking for the serialization feature.

Please see the log in 

https://github.com/mulesoft-labs/data-weave-native/runs/1795694523?check_suite_focus=true

**Comment by mcraj017** [comment] 2021-02-02 08:18
@machaval thanks for reporting the issue
Please provide me the reproducer

**Comment by machaval** [comment] 2021-02-24 01:53
One update is that it works with 20.2 but not with 20.3 or 21. Cloning the repo with `./gradlew native-cli:nativeImage`

**Comment by mcraj017** [comment] 2021-02-25 08:00
@machaval thanks for the reproducer
I did try this on windows 10 and it works, so its specific to window 2019 
I will check further and get back to you

**Comment by mcraj017** [comment] 2021-03-02 07:09
@machaval I checked with our dev team, and its most probably a config issue
could you please confirm that using the same is not happening with other versions?

**Comment by mcraj017** [comment] 2021-04-07 06:20
Closing the issue as user did not respond in the last month

**Closed by mcraj017** 2021-04-07 06:20 UTC
Labels: bug, native-image

**Comment by alexarchambault** [comment] 2021-04-24 10:16
FWIW, I'm running into the same issue on GitHub Actions, on a `windows-latest` worker, using GraalVM `20.3.1.2`:
```text
LINK : fatal error LNK1171: unable to load mspdbcore.dll (error code: 1455)
	at com.oracle.svm.hosted.image.NativeBootImageViaCC.handleLinkerFailure(NativeBootImageViaCC.java:463)
	at com.oracle.svm.hosted.image.NativeBootImageViaCC.write(NativeBootImageViaCC.java:430)
	at com.oracle.svm.hosted.NativeImageGenerator.doRun(NativeImageGenerator.java:678)
	at com.oracle.svm.hosted.NativeImageGenerator.lambda$run$0(NativeImageGenerator.java:469)
	at java.base/java.util.concurrent.ForkJoinTask$AdaptedRunnableAction.exec(ForkJoinTask.java:1407)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
Error: Image build request failed with exit status 1
```
Running into that in a private code base, which should be made public in the coming days. I can come up with a repro by then.

**Comment by iamrecursion** [comment] 2021-05-20 07:32
I've reported this [here](https://github.com/actions/virtual-environments/issues/3420) as an issue with the runner virtual environment as I cannot reproduce it locally for the life of me.

**Comment by iamrecursion** [comment] 2021-06-14 12:15
We're still seeing this. We can't reproduce it locally but we've got it failing consistently on CI [here](https://github.com/enso-org/enso/runs/2819385888).

**Comment by machaval** [comment] 2021-06-14 12:25
From what I was able to debug. The problem is an OutOfMemory problem. Looks like new version of compiler requires more memory and it fails with this error now. But the underlying problem is an OutOfMemory.
