### ISSUE TITLE
Windows 10 OS Locale switch to Chinese, Execute *.exe throw java.lang.NoSuchMethodError: java.lang.String.([B)V on Runtime

### ISSUE THREAD

**Issue by iwangxiaodong** [oracle/graal#2333] opened 2020-04-10 02:26 UTC
**Describe the issue**

My windows 10 OS Locale is **Chinese (simplified, China)**,

Though Graal native-image **build is succeeded**,

But runtime execute hi.exe is NoSuchMethodError.

I switch OS Locale to **English** it works!

**Steps to reproduce the issue**

First switch OS Locale to Chinese (simplified, China)

  SET GRAALVM_HOME="G:\...\graalvm-ce-java11-20.0.0\"
  SET PATH="%PATH%;%GRAALVM_HOME%\bin\"
  gu available
  gu install native-image
  other ...

```
import java.net.InetAddress;
import java.net.UnknownHostException;
public class Hi {
  public static void main(String[] args) {
    System.out.println("Hello, World!");
    InetAddress inetAddress;
    try {
        inetAddress = InetAddress.getLocalHost();
        System.out.println("IP of my system is: " + inetAddress.getHostAddress());
        System.out.println("Name of my system is: " + inetAddress.getHostName());
    } catch (UnknownHostException ex) {
        System.err.println(ex);
    }
  }
}
```
C:\Users\xiaodong\Desktop\demo>java Hi
Picked up JAVA_TOOL_OPTIONS: "-Dfile.encoding=UTF-8"
Hello, World!
IP of my system is: 192.168.1.239
Name of my system is: DESKTOP-1234567

C:\Users\xiaodong\Desktop\demo> native-image Hi
Picked up JAVA_TOOL_OPTIONS: "-Dfile.encoding=UTF-8"
[hi:13176] classlist: 1,109.85 ms, 1.00 GB
[hi:13176] (cap): 2,128.20 ms, 1.23 GB
[hi:13176] setup: 3,831.19 ms, 1.23 GB
[hi:13176] (typeflow): 6,434.27 ms, 1.67 GB
[hi:13176] (objects): 5,804.55 ms, 1.67 GB
[hi:13176] (features): 290.73 ms, 1.67 GB
[hi:13176] analysis: 12,814.14 ms, 1.67 GB
[hi:13176] (clinit): 165.90 ms, 1.67 GB
[hi:13176] universe: 460.63 ms, 1.67 GB
[hi:13176] (parse): 1,036.31 ms, 2.01 GB
[hi:13176] (inline): 978.26 ms, 2.01 GB
[hi:13176] (compile): 6,578.22 ms, 2.01 GB
[hi:13176] compile: 8,965.07 ms, 2.01 GB
[hi:13176] image: 898.84 ms, 2.01 GB
[hi:13176] write: 272.64 ms, 2.01 GB
[hi:13176] [total]: 28,564.20 ms, 2.01 GB

C:\Users\xiaodong\Desktop\demo> hi.exe
Hello, World!
Exception in thread "main" java.lang.NoSuchMethodError: java.lang.String.([B)V
at com.oracle.svm.jni.functions.JNIFunctions$Support.getMethodID(JNIFunctions.java:1095)
at com.oracle.svm.jni.functions.JNIFunctions$Support.getMethodID(JNIFunctions.java:1080)
at com.oracle.svm.jni.functions.JNIFunctions.GetMethodID(JNIFunctions.java:384)
at java.net.Inet6AddressImpl.getLocalHostName(Inet6AddressImpl.java)
at java.net.InetAddress.getLocalHost(InetAddress.java:1623)
at Hi.main(Hi.java:8)

**Describe GraalVM and your environment:**
 - GraalVM version: **graalvm-ce-java11-windows-amd64-20.0.0.zip**
 - JDK major version: **JDK 11**
 - OS: **Windows 10**
 - Architecture: **x64**

**More details**
None.

**Comment by christianwimmer** [comment] 2020-10-02 18:52
I could not reproduce the issue locally. But I identified and fixed a probably cause in https://github.com/oracle/graal/commit/18eeb1e98428a7272d0d4fab9f9be017827f3e28 - the method name passed to `GetMethodID` was decoded using the current charset instead of using UTF-8. That can lead to a wrong decoding of the C string `<init>`.

I'm closing the issue. If you can still reproduce with my fix, please re-open. In that case, I need more detailed information about the charset and locale used in the failing image.

**Closed by christianwimmer** 2020-10-02 18:52 UTC
Labels: bug, native-image
