### ISSUE TITLE
Windows 11 - Native Image Issue: java.nio.file.InvalidPathException: Illegal char <> at index n

### ISSUE THREAD

**Issue by engineersunit** [oracle/graal#6648] opened 2023-05-21 14:15 UTC
# Issue

When I try to create native images on windows 11 OS system, I am getting below error consistently: 

# Environment
The environment specification details are following:

## OS
OS: Windows 11 Pro
Version: 22H2
OS Build: 22621.1702

## Hardware
Processor: 12th Gen Intel(R) Core(TM) i7-1270P   2.20 GHz
System Type 64-bit operating system, x64-based processor

## Software
GraalVM: GraalVM CE 22.3.2 (build 17.0.7+7-jvmci-22.3-b18)
Microsoft Visual Studio Build Tools: 2022 (17.6.0)
Maven:  3.9.2
x64 Native Tools Command Prompt for VS: 2022
 
## Installation Steps
Windows Installation Guide Followed: 
Installation on Windows Platforms: https://www.graalvm.org/latest/docs/getting-started/windows/
Using GraalVM and Native Image on Windows 10 by Olga Gupalo: https://medium.com/graalvm/using-graalvm-and-native-image-on-windows-10-9954dc071311

# Steps to reproduce

## Command Used:

```
git clone https://github.com/engineersunit/microservice-helidon.git
mvn clean package -Pnative-image
```

## Application: 
Generated from Helidon CLI https://helidon.io/docs/latest/#/about/cli
GitHub: https://github.com/engineersunit/microservice-helidon

# Error:

Content of FIle target\tmp\native-image-4262774999037715045.args

[native-image-4262774999037715045.args.txt](https://github.com/oracle/graal/files/11524749/native-image-4262774999037715045.args.txt)

```
[INFO] Executing: E:\graalvm-ce-java17-windows-amd64-22.3.2\graalvm-ce-java17-22.3.2\bin\native-image.cmd @target\tmp\native-image-4262774999037715045.args
Exception in thread "main" java.nio.file.InvalidPathException: Illegal char <> at index 3: D:\MyCodeRepos\helidon\helidon_cli\quickstart-se\target\classes
        at java.base@17.0.7/sun.nio.fs.WindowsPathParser.normalize(WindowsPathParser.java:182)
        at java.base@17.0.7/sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:153)
        at java.base@17.0.7/sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:77)
        at java.base@17.0.7/sun.nio.fs.WindowsPath.parse(WindowsPath.java:92)
        at java.base@17.0.7/sun.nio.fs.WindowsFileSystem.getPath(WindowsFileSystem.java:232)
        at java.base@17.0.7/java.nio.file.Path.of(Path.java:147)
        at java.base@17.0.7/java.nio.file.Paths.get(Paths.java:69)
        at org.graalvm.nativeimage.builder/com.oracle.svm.core.util.ClasspathUtils.stringToClasspath(ClasspathUtils.java:52)
        at org.graalvm.nativeimage.driver/com.oracle.svm.driver.NativeImage.addCustomImageClasspath(NativeImage.java:1582)
        at org.graalvm.nativeimage.driver/com.oracle.svm.driver.DefaultOptionHandler.processClasspathArgs(DefaultOptionHandler.java:417)
        at org.graalvm.nativeimage.driver/com.oracle.svm.driver.DefaultOptionHandler.consume(DefaultOptionHandler.java:69)
        at org.graalvm.nativeimage.driver/com.oracle.svm.driver.NativeImage$NativeImageArgsProcessor.apply(NativeImage.java:1512)
        at org.graalvm.nativeimage.driver/com.oracle.svm.driver.DefaultOptionHandler.consume(DefaultOptionHandler.java:204)
        at org.graalvm.nativeimage.driver/com.oracle.svm.driver.NativeImage$NativeImageArgsProcessor.apply(NativeImage.java:1512)
        at org.graalvm.nativeimage.driver/com.oracle.svm.driver.NativeImage.processNativeImageArgs(NativeImage.java:1770)
        at org.graalvm.nativeimage.driver/com.oracle.svm.driver.NativeImage.completeImageBuild(NativeImage.java:959)
        at org.graalvm.nativeimage.driver/com.oracle.svm.driver.NativeImage.build(NativeImage.java:1417)
        at org.graalvm.nativeimage.driver/com.oracle.svm.driver.NativeImage.performBuild(NativeImage.java:1387)
        at org.graalvm.nativeimage.driver/com.oracle.svm.driver.NativeImage.main(NativeImage.java:1374)
```

**Comment by fniephaus** [comment] 2023-05-22 08:21
This appears to be a duplicate of https://github.com/oracle/graal/issues/6417. Please use a [dev build](https://github.com/graalvm/graalvm-ce-dev-builds/releases) to verify that we have fixed it. The fix will ship with the upcoming GraalVM for JDK17/20 releases on June 13.

**Closed by fniephaus** 2023-05-22 08:21 UTC
Labels: bug

**Comment by engineersunit** [comment] 2023-05-22 10:35
The reported issue is resolved now with the latest dev build. 
But still we are facing the following new issue. Please help!

`Unable to run 'C:\Users\SUNITG~1\AppData\Local\Temp\SVM-519542167864450455\AMD64LibCHelperDirectives.exe' to compute offsets in C data structures. Is it possible that your antivirus software interferes and puts the resulting file into quarantine?`


# GraalVM Native Image Error Report


```java
com.oracle.svm.core.util.VMError$HostedError: Unable to run 'C:\Users\SUNITG~1\AppData\Local\Temp\SVM-519542167864450455\AMD64LibCHelperDirectives.exe' to compute offsets in C data structures. Is it possible that your antivirus software interferes and puts the resulting file into quarantine?
	at org.graalvm.nativeimage.builder/com.oracle.svm.core.util.VMError.shouldNotReachHere(VMError.java:86)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.c.CAnnotationProcessor.makeQuery(CAnnotationProcessor.java:142)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.c.CAnnotationProcessor.process(CAnnotationProcessor.java:118)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.c.NativeLibraries.finish(NativeLibraries.java:559)
```

**Comment by engineersunit** [comment] 2023-05-22 10:39
[svm_err_b_20230522T160248.378_pid13920.md](https://github.com/oracle/graal/files/11530027/svm_err_b_20230522T160248.378_pid13920.md)

Error report

**Comment by fniephaus** [comment] 2023-05-22 12:40
> But still we are facing the following new issue. Please help!

The error message shows the following question:

> Is it possible that your antivirus software interferes and puts the resulting file into quarantine?

Can you rule that out?

**Comment by engineersunit** [comment] 2023-05-23 05:46
Hello @fniephaus 

Thanks I am checking this internally.

**Comment by engineersunit** [comment] 2023-05-24 06:55
Hello @fniephaus 

I discussed this internally. 

I need help in finding out if it is possible to configure the location where the folder and file "SVM-nnn\AMD64LibCHelperDirectives.exe" is created and used by the GraalVM build?

If we can configure this using a system variable then we can hopefully confirm to a possible AntiVirus policy.

**Comment by fniephaus** [comment] 2023-05-24 07:05
You can set a different temp directory using `-H:TempDirectory=/target/tmp`. Note that this is a non-API option.

**Comment by engineersunit** [comment] 2023-05-24 07:15
@fniephaus  Thanks a lot for your time and quick help.

Using the `-H:TempDirectory` option with a folder value (`<project>/target/tmp`) different from Window's `%temp%` location, I was able to generate the native image and it really runs really fast 👍
