### ISSUE TITLE
Native Image Issues in windows 10.

### ISSUE THREAD

**Issue by SuperStarDeveloper** [oracle/graal#6650] opened 2023-05-22 05:08 UTC
**Describe GraalVM and your environment :**
 - 22.3.0
 - CE
 - JDK version: JDK 17
 - OS and OS Version: windows 10 pro
 - Architecture: amd64
 - The output of `java -Xinternalversion`:
 
OpenJDK 64-Bit Server VM (17.0.5+8-jvmci-22.3-b08) for windows-amd64 JRE (17.0.5+8-jvmci-22.3-b08), built on Oct 19 2022 02:02:43 by "" with MS VC++ 17.1 (VS2022)

(https://github.com/graalvm/graalvm-ce-builds/releases/download/vm-22.3.0/graalvm-ce-java17-windows-amd64-22.3.0.zip)

installed visual studio community 2022-17.6.0
https://prnt.sc/AujcxRxBEjO-

and I have build my java project, so I have a jar file. it is working in cmd. so I have tried to create native image.
now in linux, generated it. but in windows 10, I face an issues.

https://prnt.sc/_CF7gQMnsdNS

**Comment by fniephaus** [comment] 2023-05-24 07:11
This appears to be an identical duplicate of https://github.com/oracle/graal/issues/6664.

**Closed by fniephaus** 2023-05-24 07:11 UTC
Labels: native-image
