### ISSUE TITLE
[GR-54752] Very slow warmup with Graal Compiler JIT (in a Netty-based application)

### ISSUE THREAD

**Issue by guilgaly** [oracle/graal#9115] opened 2024-06-14 07:15 UTC
**Describe the issue**

Running the Gatling load testing tool (which relies heavily on Netty internally) on GraalVM CE, we have noticed very slow warmups compared to running with the traditionnal C2 JIT compiler (with the warmup period taking 5 times as long or more).

We also observe this with a simplified use case built directly with Netty. We are particularly interested in GraalVM because of Truffle, but our reproducer here is purely in Java.

Are these long warmup times to be expected at the moment with the Graal JIT compiler or would you consider there is something specific going on here? Are there plans for improvements? Are there tuning options we should investigate?

**Steps to reproduce the issue**

We have a simplified reproducer here: https://github.com/gatling/bug-report-graal-compiler-warmup

It runs a simple HTTP server and client (both based on Netty) in the same process. The client opens n connections, performs the same HTTP request over and over again on each connection, and logs the total throughput every quarter of a second.

Results of our tests can be seen here (with the data also converted to more readable graphs in the HTML files): https://github.com/gatling/bug-report-graal-compiler-warmup/tree/main/test-results/2024-06-11. They all run on the same machine, using either Azul Zulu (so with the usual C2 JIT compiler), GraalVM CE, or Oracle GraalVM. The stable throughput after the warm-up period is quite comparable, but the warm-up times are very different:

- With Zulu, it takes about 7 seconds.
- With GraalVM CE, it takes about 45 seconds (including more than 30 seconds to reach just half of the final througput).
- With Oracle GraalVM, it takes about 25 seconds (although at least we reach about 80% of the final throuput after about 12 seconds).

**Describe GraalVM and your environment:**

 - GraalVM version:
   - GraalVM CE: **CE 22.0.1+8.1 (build 22.0.1+8-jvmci-b01)**
   - Oracle GraalVM: **22.0.1+8.1 (build 22.0.1+8-jvmci-b01)**
   - Azul Zulu (for reference comparison): **Zulu22.30+13-CA (build 22.0.1+8)**
 - JDK major version: **22**
 - OS: **Amazon Linux 2**
 - Architecture: **AMD64** (tested on an AWS EC2 C6i.2xlarge instance)

**More details**

Please don't hesitate to let us know if we can provide usefull additional test data, try out different tuning options, etc.

**Comment by davleopo** [comment] 2024-06-14 08:29
thank you @guilgaly  for your report. Depending on a particular workload warmup can be faster/slower with different JITs - there are many things that influence it. Without having looked into the workload in detail the differences you are seeing are large enough to potentially indicate a bug on our side. We will have a look and get back to you.

@rmosaner  can you have a look at the reproducer?

BTW: did you also try native image (https://www.graalvm.org/latest/reference-manual/native-image/) ?

**Comment by rmosaner** [comment] 2024-06-14 08:58
I will have a look.
This is tracked internally as [GR-54752]

**Comment by slandelle** [comment] 2024-06-14 10:22
> BTW: did you also try native image (https://www.graalvm.org/latest/reference-manual/native-image/) ?

@davleopo We haven't. We're not there yet at Gatling. Our focus with GraalVM for now is Truffle/GraalJS.

**Comment by rmosaner** [comment] 2024-08-20 07:41
Hi @guilgaly 

we found that the warmup problems in your application are caused by multiple things:

**1) Graal uses fewer compiler threads compared to running with C2**
This can be tweaked by playing around with option _-XX:JVMCINativeLibraryThreadFraction_. On my machine, a value of 0.8 resulted in the same number of compiler threads as when run with C2. This should reduce the warmup significantly.

**2) GraalVM CE: inlining is less powerful wrt handling recursion**
You can terminate the inlining sooner by setting _-Dgraal.MethodInlineBailoutLimit=500_ (or even smaller). The default value of 5000 seems to be too large.

**3) Oracle GraalVM: aggressive speculation**
Oracle GraalVM does multiple re-compiles before achieving high peak performance. We found that some re-compiles were based on speculations which would always fail.

We just merged PRs to lower the MethodInlineBailoutLimit for GraalVM CE to 1000 and to fix multiple unnecessary speculations for Oracle GraalVM. Together with the increase of compiler threads this significantly improved the warmup on our side.

**Comment by guilgaly** [comment] 2024-08-21 07:58
Hi @rmosaner

Thanks a lot for the investigation and for your feedback!

That's great news, and we'll be sure to rerun our tests with all of this and see the difference it makes. Regarding the fixes merged for point number 3, I guess that means they will be included in the next dev release on https://github.com/graalvm/graalvm-ce-dev-builds/releases/ if we want to give them a try before the next stable release?

**Comment by rmosaner** [comment] 2024-08-22 14:03
The changes from point 3 will be part or Oracle GraalVM 24 which will be released in spring 2025 (https://www.graalvm.org/release-calendar/). 
Early access builds for Oracle GraalVM can be found here: https://github.com/graalvm/oracle-graalvm-ea-builds
The one that contains the corresponding fix should be released in one or two weeks. 

However, the biggest warmup improvements for Oracle GraalVM were already seen after increasing the number of compiler threads.

I am closing this issue for now - thanks for reporting! 
Please reach out in case of any remaining or future problems.

**Closed by rmosaner** 2024-08-22 14:03 UTC
Labels: bug, compiler
