### ISSUE TITLE
When Building native image java.lang.ClassCastException: class com.oracle.graal.pointsto.heap.ImageHeapInstance cannot be cast to class com.oracle.svm.core.meta.DirectSubstrateObjectConstant  is thrown

### ISSUE THREAD

**Issue by akainz** [oracle/graal#7328] opened 2023-09-02 09:55 UTC
When building with the JDK 21 community nightly (GraalVM CE 23.1.0-dev-20230817_2024) I get the following error
  

```
[2/8] Performing analysis...  []                                                                        (19.1s @ 1.53GB)
   18,045 reachable types   (76.4% of   23,626 total)
   26,655 reachable fields  (50.3% of   52,985 total)
   51,786 reachable methods (27.1% of  190,884 total)
   12,139 types, 5,187 fields, and 19,342 methods registered for reflection
        3 native libraries: crypt32, ncrypt, winhttp

Fatal error: com.oracle.graal.pointsto.util.AnalysisError$ParsingError: Error encountered while parsing com.fasterxml.jackson.core.io.doubleparser.JavaBigIntegerFromCharSequence.parseHexDigits(JavaBigIntegerFromCharSequence.java:85)
Parsing context:
   at com.fasterxml.jackson.core.io.doubleparser.JavaBigIntegerFromCharSequence.parseBigIntegerLiteral(JavaBigIntegerFromCharSequence.java:54)
   at com.fasterxml.jackson.core.io.doubleparser.JavaBigIntegerParser.parseBigInteger(JavaBigIntegerParser.java:79)
   at com.fasterxml.jackson.core.io.BigIntegerParser.parseWithFastParser(BigIntegerParser.java:21)
   at com.fasterxml.jackson.core.io.NumberInput.parseBigInteger(NumberInput.java:504)
   at com.fasterxml.jackson.core.base.ParserBase._getBigInteger(ParserBase.java:1239)
   at com.fasterxml.jackson.core.base.ParserBase.convertNumberToInt(ParserBase.java:1040)
   at com.fasterxml.jackson.core.base.ParserBase.getIntValue(ParserBase.java:769)
   at com.fasterxml.jackson.datatype.jsr310.deser.YearDeserializer.deserialize(YearDeserializer.java:87)
   at com.fasterxml.jackson.datatype.jsr310.deser.YearDeserializer.deserialize(YearDeserializer.java:36)
   at com.fasterxml.jackson.databind.deser.std.StdDelegatingDeserializer.deserializeWithType(StdDelegatingDeserializer.java:192)
   at com.fasterxml.jackson.databind.deser.impl.TypeWrappedDeserializer.deserialize(TypeWrappedDeserializer.java:74)
   at com.fasterxml.jackson.databind.deser.DefaultDeserializationContext._unwrapAndDeserialize(DefaultDeserializationContext.java:356)
   at com.fasterxml.jackson.dataformat.xml.deser.XmlDeserializationContext.readRootValue(XmlDeserializationContext.java:88)
   at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4825)
   at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3772)
   at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3740)
   at com.lookeen.backend.config.lookeen.LookeenConfiguration.readConfig(LookeenConfiguration.java:88)
   at static root method.(Unknown Source)

        at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.util.AnalysisError.parsingError(AnalysisError.java:149)
        at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.flow.MethodTypeFlow.createFlowsGraph(MethodTypeFlow.java:184)
        at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.flow.MethodTypeFlow.ensureFlowsGraphCreated(MethodTypeFlow.java:153)
        at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.flow.MethodTypeFlow.getOrCreateMethodFlowsGraphInfo(MethodTypeFlow.java:111)
        at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.typestate.DefaultSpecialInvokeTypeFlow.lambda$onObservedUpdate$0(DefaultSpecialInvokeTypeFlow.java:88)
        at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.util.LightImmutableCollection.forEach(LightImmutableCollection.java:90)
        at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.typestate.DefaultSpecialInvokeTypeFlow.onObservedUpdate(DefaultSpecialInvokeTypeFlow.java:87)
        at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.flow.TypeFlow.update(TypeFlow.java:620)
        at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.PointsToAnalysis$1.run(PointsToAnalysis.java:491)
        at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.util.CompletionExecutor.executeCommand(CompletionExecutor.java:187)
        at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.util.CompletionExecutor.lambda$executeService$0(CompletionExecutor.java:171)
        at java.base/java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1423)
        at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:387)
        at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1312)
        at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1843)
        at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1808)
        at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:188)
Caused by: java.lang.ClassCastException: class com.oracle.graal.pointsto.heap.ImageHeapInstance cannot be cast to class com.oracle.svm.core.meta.DirectSubstrateObjectConstant (com.oracle.graal.pointsto.heap.ImageHeapInstance is in module org.graalvm.nativeimage.pointsto of loader 'app'; com.oracle.svm.core.meta.DirectSubstrateObjectConstant is in module org.graalvm.nativeimage.builder of loader 'app')
        at org.graalvm.nativeimage.builder/com.oracle.svm.core.meta.SubstrateObjectConstant.asObject(SubstrateObjectConstant.java:68)
        at org.graalvm.nativeimage.builder/com.oracle.svm.core.graal.meta.SubstrateSnippetReflectionProvider.asObject(SubstrateSnippetReflectionProvider.java:57)
        at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.ameta.AnalysisMethodHandleAccessProvider.toOriginalConstant(AnalysisMethodHandleAccessProvider.java:81)
        at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.ameta.AnalysisMethodHandleAccessProvider.resolveLinkToTarget(AnalysisMethodHandleAccessProvider.java:75)
        at jdk.internal.vm.compiler/org.graalvm.compiler.replacements.nodes.MethodHandleNode.getLinkToTarget(MethodHandleNode.java:232)
        at jdk.internal.vm.compiler/org.graalvm.compiler.replacements.nodes.MethodHandleNode.tryResolveTargetInvoke(MethodHandleNode.java:111)
        at jdk.internal.vm.compiler/org.graalvm.compiler.replacements.nodes.MethodHandleWithExceptionNode.trySimplify(MethodHandleWithExceptionNode.java:74)
        at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.phases.InlineBeforeAnalysisGraphDecoder.handleMethodHandle(InlineBeforeAnalysisGraphDecoder.java:350)
        at jdk.internal.vm.compiler/org.graalvm.compiler.nodes.GraphDecoder.processNextNode(GraphDecoder.java:924)
        at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.phases.InlineBeforeAnalysisGraphDecoder.processNextNode(InlineBeforeAnalysisGraphDecoder.java:344)
        at jdk.internal.vm.compiler/org.graalvm.compiler.nodes.GraphDecoder.decode(GraphDecoder.java:650)
        at jdk.internal.vm.compiler/org.graalvm.compiler.replacements.PEGraphDecoder.decode(PEGraphDecoder.java:892)
        at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.phases.InlineBeforeAnalysis.decodeGraph(InlineBeforeAnalysis.java:76)
        at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.flow.MethodTypeFlowBuilder.parse(MethodTypeFlowBuilder.java:194)
        at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.flow.MethodTypeFlowBuilder.apply(MethodTypeFlowBuilder.java:606)
        at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.flow.MethodTypeFlow.createFlowsGraph(MethodTypeFlow.java:167)
```

**Comment by fniephaus** [comment] 2023-09-04 10:44
This is a duplicate of #7301.

**Closed by fniephaus** 2023-09-04 10:44 UTC
Labels: bug, native-image
