### ISSUE TITLE
[native-image] [Windows] System.getProperty("user.name") returns "somebody"

### ISSUE THREAD

**Issue by Skhmt** [oracle/graal#2055] opened 2020-01-08 18:44 UTC
Using `System.getProperty("user.name")` properly works as a .jar, but when using native-image on Windows, it always returns `somebody`, not the actual username. Similarly, `System.getProperty("user.home")` returns something like `C:\Users\somebody`.

**Comment by cstancu** [comment] 2020-01-08 22:56
Duplicate of #1630 . Fixed by https://github.com/oracle/graal/commit/924c8d07c613a7465e8b77abd33a666f16f5666f.

**Closed by cstancu** 2020-01-08 22:56 UTC
