### ISSUE TITLE
GraalVm 22.0.0.2: IllegalStateException: The Context is already closed.

### ISSUE THREAD

**Issue by matteobertozzi** [oracle/graal#4264] opened 2022-01-26 13:33 UTC
**Describe the issue**
if I reuse the engine Context.newBuilder("js").engine(...)
after a few runs (e.g. 20 executions) of executions I get: IllegalStateException: The Context is already closed.
If I create a Context without specify the engine everything seems to work.
going back to 21.3.0 I don't see the problem.

**Steps to reproduce the issue**
1. git clone https://github.com/matteobertozzi/graalvm22-issue.git
2. mvn clean test -Dtest=TestGraal22CtxClosed

**Describe GraalVM and your environment:**
 - GraalVM Community Edition 22.0.0.2 (vm-22.0.0.2  bd6570e)
 - JDK major version: 17
 - OS: macOS Monterey
 - Architecture: AMD64

**More details**
To reproduce the problem the unit test TestGraal22CtxClosed.java in the repo contains
a JS script that is an async function that calls a java method
java calls the main() and when the promise is complete tries to call the Value.getMember()
After few runs (the test has a loop that does the same thing for few times) I get the exception below
```
java.lang.IllegalStateException: The Context is already closed.
	at org.graalvm.truffle/com.oracle.truffle.polyglot.PolyglotEngineException.illegalState(PolyglotEngineException.java:129)
	at org.graalvm.truffle/com.oracle.truffle.polyglot.PolyglotContextImpl.checkClosed(PolyglotContextImpl.java:1103)
	at org.graalvm.truffle/com.oracle.truffle.polyglot.PolyglotContextImpl.enterThreadChanged(PolyglotContextImpl.java:702)
	at org.graalvm.truffle/com.oracle.truffle.polyglot.PolyglotEngineImpl.enterCached(PolyglotEngineImpl.java:1991)
	at org.graalvm.truffle/com.oracle.truffle.polyglot.HostToGuestRootNode.execute(HostToGuestRootNode.java:110)
	at jdk.internal.vm.compiler/org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.executeRootNode(OptimizedCallTarget.java:655)
	at jdk.internal.vm.compiler/org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.profiledPERoot(OptimizedCallTarget.java:627)
	at jdk.internal.vm.compiler/org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.doInvoke(OptimizedCallTarget.java:544)
	at jdk.internal.vm.compiler/org.graalvm.compiler.truffle.runtime.GraalRuntimeSupport.callProfiled(GraalRuntimeSupport.java:235)
	at org.graalvm.truffle/com.oracle.truffle.polyglot.PolyglotValueDispatch$InteropValue.getArrayElement(PolyglotValueDispatch.java:2120)
	at org.graalvm.sdk/org.graalvm.polyglot.Value.getArrayElement(Value.java:295)
	at org.graalvm.truffle/com.oracle.truffle.polyglot.PolyglotValueDispatch$InteropValue$MemberSet$1.next(PolyglotValueDispatch.java:2802)
	at org.graalvm.truffle/com.oracle.truffle.polyglot.PolyglotValueDispatch$InteropValue$MemberSet$1.next(PolyglotValueDispatch.java:2790)
	at demo.TestGraal22CtxClosed$JsPromiseCatcher.dumpResult(TestGraal22CtxClosed.java:111)

```

**Comment by chumer** [comment] 2022-01-26 14:03
Already tracked internally with GR-36613.

**Comment by chumer** [comment] 2022-01-26 19:30
Thank you very much for the excellent bug report.

I could reproduce the bug. Fix is in progress.
The only reliable workaround I can see is turning off code caching by not specifying an explicit engine in `Context.Builder`.

**Comment by leomc2005** [comment] 2022-03-03 19:57
Any predictions on when it will be fixed? 
The workaround causes considerable performance degradation.
I'm considering going back to 21.3.0.

**Comment by chumer** [comment] 2022-03-30 19:05
Sorry didn't update the issue. This was fixed a while a go on latest CE build:
https://github.com/graalvm/graalvm-ce-dev-builds/releases/tag/22.1.0-dev-20220328_0754

**Closed by chumer** 2022-03-30 19:05 UTC
Labels: bug

**Comment by chumer** [comment] 2022-03-30 19:07
This is the fix:
https://github.com/oracle/graal/commit/fe09ce8786264ca5ef67c405fe5fba3c5d0d8f4f

Internally tracked as GR-36613.

**Comment by Co-Maheshh** [comment] 2023-09-07 14:16
Hi @chumer   I am also getting same error. i am using graalvm sdk 22.2 and same version for graal js.                     
so which version i need to use to resolve this error ?

**Comment by chumer** [comment] 2023-09-19 17:38
@Co-Maheshh this was fixed with graalvm-22.0.0

**Comment by in-fke** [comment] 2024-06-11 12:22
I am using 23.0.4 and my suspicion is that this kind of bug still exists.
The reason why I am using the code below is that I wanted:

1. a specific Engine to be able to influence the `logHandler`
1. some global bindings that would work for every context, ended up "copying" them

Or is it something else I am doing wrong? Adding Bindings to `ScriptContext.GLOBAL_SCOPE` - they were not visible in the script.

My code is basically like this:
```
// once
engine = Engine.newBuilder("js").build();
scriptEngine = GraalJSScriptEngine.create(engine, Context.newBuilder());

// then, more often, block like this
Bindings bindings = new SimpleBindings();
scriptContext.setBindings(bindings, ScriptContext.ENGINE_SCOPE);
context = scriptEngine.getPolyglotContext(scriptContext);
context.enter();
scriptEngine.eval(source, scriptContext);
...
scriptEngine.eval(source, scriptContext); // sporadically fails with "The Context is already closed."
context.leave();
context.close(false);
```

```
Caused by: java.lang.IllegalStateException: The Context is already closed.
	at com.oracle.truffle.polyglot.PolyglotEngineException.closedException(PolyglotEngineException.java:139) ~[truffle-api-22.3.5.jar:?]
	at com.oracle.truffle.polyglot.PolyglotContextImpl.checkClosedOrDisposing(PolyglotContextImpl.java:1257) ~[truffle-api-22.3.5.jar:?]
	at com.oracle.truffle.polyglot.PolyglotContextImpl.enterThreadChanged(PolyglotContextImpl.java:808) ~[truffle-api-22.3.5.jar:?]
	at com.oracle.truffle.polyglot.PolyglotEngineImpl.enterCached(PolyglotEngineImpl.java:2026) ~[truffle-api-22.3.5.jar:?]
	at com.oracle.truffle.polyglot.PolyglotEngineImpl.enter(PolyglotEngineImpl.java:1973) ~[truffle-api-22.3.5.jar:?]
	at com.oracle.truffle.polyglot.OtherContextGuestObject.sendImpl(OtherContextGuestObject.java:136) ~[truffle-api-22.3.5.jar:?]
	at com.oracle.truffle.polyglot.OtherContextGuestObject$Send.doCached(OtherContextGuestObject.java:113) ~[truffle-api-22.3.5.jar:?]
	at com.oracle.truffle.polyglot.OtherContextGuestObjectGen$ReflectionLibraryExports$Cached.executeAndSpecialize(OtherContextGuestObjectGen.java:136) ~[truffle-api-22.3.5.jar:?]
	at com.oracle.truffle.polyglot.OtherContextGuestObjectGen$ReflectionLibraryExports$Cached.send(OtherContextGuestObjectGen.java:93) ~[truffle-api-22.3.5.jar:?]
	at com.oracle.truffle.api.interop.InteropLibraryGen$Proxy.isNull(InteropLibraryGen.java:2417) ~[truffle-api-22.3.5.jar:?]
	at com.oracle.truffle.js.nodes.unary.JSIsNullOrUndefinedNode.doJSValueOrForeign(JSIsNullOrUndefinedNode.java:159) ~[js-22.3.5.jar:?]
	at com.oracle.truffle.js.nodes.unary.JSIsNullOrUndefinedNodeGen.executeAndSpecialize(JSIsNullOrUndefinedNodeGen.java:469) ~[js-22.3.5.jar:?]
	at com.oracle.truffle.js.nodes.unary.JSIsNullOrUndefinedNodeGen.execute(JSIsNullOrUndefinedNodeGen.java:262) ~[js-22.3.5.jar:?]
	at com.oracle.truffle.js.nodes.binary.JSLogicalNode.execute(JSLogicalNode.java:64) ~[js-22.3.5.jar:?]
	at com.oracle.truffle.js.nodes.JavaScriptNode.executeBoolean(JavaScriptNode.java:168) ~[js-22.3.5.jar:?]
	at com.oracle.truffle.js.nodes.control.IfNode.executeCondition(IfNode.java:236) ~[js-22.3.5.jar:?]
	at com.oracle.truffle.js.nodes.control.IfNode.execute(IfNode.java:159) ~[js-22.3.5.jar:?]
	at com.oracle.truffle.js.nodes.JavaScriptNodeWrapper.executeVoid(JavaScriptNodeWrapper.java:240) ~[js-22.3.5.jar:?]
	at com.oracle.truffle.js.nodes.control.AbstractBlockNode.executeVoid(AbstractBlockNode.java:80) ~[js-22.3.5.jar:?]
	at com.oracle.truffle.js.nodes.control.AbstractBlockNode.executeVoid(AbstractBlockNode.java:55) ~[js-22.3.5.jar:?]
	at com.oracle.truffle.api.impl.DefaultBlockNode.executeGeneric(DefaultBlockNode.java:63) ~[truffle-api-22.3.5.jar:?]
	at com.oracle.truffle.js.nodes.control.AbstractBlockNode.execute(AbstractBlockNode.java:75) ~[js-22.3.5.jar:?]
	at com.oracle.truffle.js.nodes.binary.DualNode.execute(DualNode.java:119) ~[js-22.3.5.jar:?]
	at com.oracle.truffle.js.nodes.function.FunctionBodyNode.execute(FunctionBodyNode.java:73) ~[js-22.3.5.jar:?]
	at com.oracle.truffle.js.nodes.function.FunctionRootNode.executeInRealm(FunctionRootNode.java:149) ~[js-22.3.5.jar:?]
	at com.oracle.truffle.js.runtime.JavaScriptRealmBoundaryRootNode.execute(JavaScriptRealmBoundaryRootNode.java:88) ~[js-22.3.5.jar:?]
	at com.oracle.truffle.api.impl.DefaultCallTarget.callDirectOrIndirect(DefaultCallTarget.java:85) ~[truffle-api-22.3.5.jar:?]
	at com.oracle.truffle.api.impl.DefaultDirectCallNode.call(DefaultDirectCallNode.java:59) ~[truffle-api-22.3.5.jar:?]
	at com.oracle.truffle.js.lang.JavaScriptLanguage$ParsedProgramRoot.execute(JavaScriptLanguage.java:245) ~[js-22.3.5.jar:?]
	at com.oracle.truffle.api.impl.DefaultCallTarget.callDirectOrIndirect(DefaultCallTarget.java:85) ~[truffle-api-22.3.5.jar:?]
	at com.oracle.truffle.api.impl.DefaultCallTarget.call(DefaultCallTarget.java:102) ~[truffle-api-22.3.5.jar:?]
	at com.oracle.truffle.polyglot.PolyglotContextImpl.eval(PolyglotContextImpl.java:1470) ~[truffle-api-22.3.5.jar:?]
	at com.oracle.truffle.polyglot.PolyglotContextDispatch.eval(PolyglotContextDispatch.java:63) ~[truffle-api-22.3.5.jar:?]
	at org.graalvm.polyglot.Context.eval(Context.java:399) ~[graal-sdk-22.3.5.jar:?]
	at com.oracle.truffle.js.scriptengine.GraalJSScriptEngine.eval(GraalJSScriptEngine.java:478) ~[js-scriptengine-22.3.5.jar:?]
	at com.oracle.truffle.js.scriptengine.GraalJSScriptEngine.eval(GraalJSScriptEngine.java:420) ~[js-scriptengine-22.3.5.jar:?]
```

**Comment by in-fke** [comment] 2024-06-11 12:25
https://github.com/oracle/graal/issues/631
