### ISSUE TITLE
debuginfotest broken: DwarfDebugInfo throws AssertionError

### ISSUE THREAD

**Issue by fniephaus** [oracle/graal#4328] opened 2022-02-15 14:55 UTC
The debuginfotest has started to fail due to https://github.com/oracle/graal/commit/9fe1533c04071569c855643eaa33f2550c1de84d:

```
Fatal error: java.lang.AssertionError
	at com.oracle.objectfile.elf.dwarf.DwarfDebugInfo.setLineIndex(DwarfDebugInfo.java:637)
	at com.oracle.objectfile.elf.dwarf.DwarfSectionImpl.setLineIndex(DwarfSectionImpl.java:537)
------------------------------------------------------------------------------------------------------------------------
	at com.oracle.objectfile.elf.dwarf.DwarfLineSectionImpl.createContent(DwarfLineSectionImpl.java:157)
                        12.2s (7.4% of total time) in 45 GCs | Peak RSS: 2.82GB | CPU load: 1.90
------------------------------------------------------------------------------------------------------------------------
Produced artifacts:
 /home/runner/work/graal/graal/substratevm/svmbuild/hello.hello.build_artifacts.txt
========================================================================================================================
Failed generating 'hello.hello' after 2m 43s.
	at com.oracle.objectfile.elf.dwarf.DwarfSectionImpl.getOrDecideSize(DwarfSectionImpl.java:411)
	at com.oracle.objectfile.elf.ELFUserDefinedSection.getOrDecideSize(ELFUserDefinedSection.java:105)
	at com.oracle.objectfile.ObjectFile.bake(ObjectFile.java:1660)
	at com.oracle.objectfile.ObjectFile.write(ObjectFile.java:1272)
	at com.oracle.svm.hosted.image.NativeImage.lambda$write$0(NativeImage.java:176)
	at com.oracle.objectfile.ObjectFile.withDebugContext(ObjectFile.java:1836)
	at com.oracle.svm.hosted.image.NativeImage.write(NativeImage.java:175)
	at com.oracle.svm.hosted.image.NativeImageViaCC.write(NativeImageViaCC.java:415)
	at com.oracle.svm.hosted.NativeImageGenerator.doRun(NativeImageGenerator.java:693)
	at com.oracle.svm.hosted.NativeImageGenerator.run(NativeImageGenerator.java:512)
	at com.oracle.svm.hosted.NativeImageGeneratorRunner.buildImage(NativeImageGeneratorRunner.java:422)
	at com.oracle.svm.hosted.NativeImageGeneratorRunner.build(NativeImageGeneratorRunner.java:597)
	at com.oracle.svm.hosted.NativeImageGeneratorRunner.main(NativeImageGeneratorRunner.java:128)
	at com.oracle.svm.hosted.NativeImageGeneratorRunner$JDK9Plus.main(NativeImageGeneratorRunner.java:627)
```
https://github.com/oracle/graal/runs/5194911891?check_suite_focus=true#step:9:2387

#### Line of interest
https://github.com/oracle/graal/blob/0a46643f4017b515d062f2737d9fbcc0c5234066/substratevm/src/com.oracle.objectfile/src/com/oracle/objectfile/elf/dwarf/DwarfDebugInfo.java#L637

**Comment by fniephaus** [comment] 2022-02-15 14:56
@zakkak or @adinn, could you please take a look at this?

**Comment by adinn** [comment] 2022-02-17 16:59
Foivos' proposed fix resolves this issue but it is not really a fully correct solution because it is fixing the symptom not the cause.

This problem happens when passing line information for a compiled method to the debug info generator. Specifically, a source position associated with generated code is being used to identify line numbers for both the leaf inline method that the code is derived from and caller methods up to the outermost compiled method.

Source positions include a reference to an associated ResolvedJavaMethod. The code that Foivos patched expects this to be either a HostedMethod or a HotspotResolvedJavaMethodImpl. The latter is used as a unique key to identify the debug info associated with the method. The former gets unwrapped to derive either an underlying HotspotResolvedJavaMethodImpl (which may involve traversing a substitution) or a custom substitution method wiich will serve as a unique key. This unwrapping ensures that mixed use of either type of reference always associate debuginfo for what is essentially the same method with a single unique target.

What is actually turning up is an AnalysisMethod, specifically an instance of PointsToAnalysis. The method in question is 

    org.graalvm.compiler.replacements.StringLatin1Snippets.indexOf(byte[], int, byte[], int, int)

which is inlined into method

    java.lang.String.indexOf(byte[], byte, int, java.lang.String, int)

As the debug code currently stands this Analysis method does not get unwrapped. In consequence it results in a secondary target for the debug info for the inlined method, alongisde other unwrapped references which identify the underlying HotspotResolvedJavaMethodImpl. Later processing encounters the same method in two different guises and tries to index associated debug information twice. The problem cannot be resolved by keeping two records as that would mean debug info derived from different references to the same method will not be correctly collated and assimilated.

Clearly, a way to fix this is to detect an Analysis method and unwrap it one less time than the corresponding HostedMethod to get to the same unique key. That is what Foivos' patch does. However, I don't believe we should really be seeing instances of AnalysisMethod (or AnalysisType) in the compiler output and I think we should consider an alternative fix.

The compiler is fed with input graphs that *mostly* employ the HostedXXX wrappers to reference Java types, methods and fields. In a small number of cases the graph contains unwrapped references to HotspotResolvedJavaXXXImpl instances. These creep in for various reasons because the transformation from Hotspot to Hosted universe is not 100% complete (e.g. the example we saw some time back in class Class where a dependent generic type was not transformed). If the compiler is operating correctly then the generated ouptuts, CompiledMethod instances and structures embedded within them, such as source node positions, should only ever contain references to HostedXXX HotspotResolvedJavaXXXImpl instances.

Clearly, after the change mentioned above [9fe1533](https://github.com/oracle/graal/commit/9fe1533c04071569c855643eaa33f2550c1de84d) some of the new code is installing a source position which references an unwrapped AnalysisMethod when it should be referencing a HostedMethod that wraps it.

Rather than trying to trap and patch these errors in the debug code I think the correct fix would be to locate the incorrect compiler code and change it to insert the appropriate HostedMethod. It would also be good at some point to add some asserts to the debug info code to ensure that it only gets fed the expected HostedXXX types. That has not been done at present because we know it will definitely run up against cases where the HotspotXXX types sneak through. We could perhaps assert that results are either HostedXXX types or HotspotXXX types but unfortunately the Hotspot types are not publicly visible.

For now, I suggest we go with Foivos fix to get the debuginfotest working again. Without the test being run on a regular basis we will get more errors like this introduced that will be very hard to diagnose and fix.

**Closed** 2022-02-22 23:07 UTC
Labels: bug, native-image
