### ISSUE TITLE
com.oracle.svm.core.jdk.UnsupportedFeatureError: OperatingSystemMXBean 

### ISSUE THREAD

**Issue by RafaelCavazza** [oracle/graal#3289] opened 2021-03-18 12:51 UTC
We are trying to collect some runtime and system metrics using the com.sun.management.OperatingSystemMXBean.

Stack Trace:
````
com.oracle.svm.core.jdk.UnsupportedFeatureError: OperatingSystemMXBean methods
        at com.oracle.svm.core.util.VMError.unsupportedFeature(VMError.java:87)
        at com.oracle.svm.core.jdk.management.SubstrateOperatingSystemMXBean.getFreePhysicalMemorySize(SubstrateOperatingSystemMXBean.java:109)
        at arch.monitoring.opentelemetry.metric.enviroment.SystemMetrics.lambda$initCollectors$3(SystemMetrics.java:49)
        at arch.monitoring.opentelemetry.metric.observer.OpenTelemetryDoubleValueObserver$Builder.lambda$setUpdater$0(OpenTelemetryDoubleValueObserver.java:34)
        at io.opentelemetry.sdk.metrics.AsynchronousInstrumentAccumulator.lambda$doubleAsynchronousAccumulator$2(AsynchronousInstrumentAccumulator.java:40)
        at io.opentelemetry.sdk.metrics.AsynchronousInstrumentAccumulator.collectAll(AsynchronousInstrumentAccumulator.java:74)
        at io.opentelemetry.sdk.metrics.AbstractAsynchronousInstrument.collectAll(AbstractAsynchronousInstrument.java:23)
        at io.opentelemetry.sdk.metrics.SdkMeter.collectAll(SdkMeter.java:102)
        at io.opentelemetry.sdk.metrics.SdkMeterProvider.collectAllMetrics(SdkMeterProvider.java:69)
        at arch.monitoring.opentelemetry.metric.MyIntervalMetricReader$Exporter.run(MyIntervalMetricReader.java:79)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
        at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.lang.Thread.run(Thread.java:834)
        at com.oracle.svm.core.thread.JavaThreads.threadStartRoutine(JavaThreads.java:519)
        at com.oracle.svm.core.posix.thread.PosixJavaThreads.pthreadStartRoutine(PosixJavaThreads.java:192)

````

Our code: 
```
var operatingSystemMXBean = (com.sun.management.OperatingSystemMXBean) ManagementFactory.getOperatingSystemMXBean();

var freeMemory = operatingSystemMXBean.getFreePhysicalMemorySize();
```
GraalVM Version
openjdk version "11.0.10" 2021-01-19
OpenJDK Runtime Environment GraalVM CE 21.0.0.2 (build 11.0.10+8-jvmci-21.0-b06)
OpenJDK 64-Bit Server VM GraalVM CE 21.0.0.2 (build 11.0.10+8-jvmci-21.0-b06, mixed mode, sharing)

Enviroment: 
 - OS: macOS Catalina - 10.15.7 (19H15)
 - Architecture: AMD64

**Comment by mcraj017** [comment] 2021-03-22 06:49
@RafaelCavazza thanks for reporting the issue
we will take a look and get back to you

**Comment by mcraj017** [comment] 2021-03-22 06:54
I tried a simple sysout with GraalVM CE 21.0.0.2 and it worked
please provide specific reproduer :
```
import java.lang.management.ManagementFactory;
class Main{
    public static void main(String[] args) {
        var operatingSystemMXBean = (com.sun.management.OperatingSystemMXBean) ManagementFactory.getOperatingSystemMXBean();
        var freeMemory = operatingSystemMXBean.getFreePhysicalMemorySize();
        System.out.println(freeMemory);
    }
}
```
output
```
$ java Main.java 
861347840
```

**Comment by RafaelCavazza** [comment] 2021-03-23 03:09
Hi @mcraj017!

Thanks for the response.

I built the native-image using: 
```mvn clean package -DskipTests  -Pnative```

Then a ran the binary using: ```./target/MY_PROJECT```

My code:

````
public class App {
    public static void main(String[] args) {

        var operatingSystemMXBean = (com.sun.management.OperatingSystemMXBean) ManagementFactory.getOperatingSystemMXBean();
        var freeMemory = operatingSystemMXBean.getFreePhysicalMemorySize();
        System.out.println("Free memory:" + freeMemory);
    }
}
````
The error: 
````
Exception in thread "main" com.oracle.svm.core.jdk.UnsupportedFeatureError: OperatingSystemMXBean methods
        at com.oracle.svm.core.util.VMError.unsupportedFeature(VMError.java:87)
        at com.oracle.svm.core.jdk.management.SubstrateOperatingSystemMXBean.getFreePhysicalMemorySize(SubstrateOperatingSystemMXBean.java:109)
        at inter.App.main(App.java:13)
````

**Comment by mcraj017** [comment] 2021-03-24 07:21
@RafaelCavazza thanks I am able to reproduce it and it will be resolved in future releases

**Comment by ehsmeng-graalvm** [comment] 2021-04-01 21:26
Hi, I have a trivial tomcat example that seems to produce the same error

Caused by: com.oracle.svm.core.jdk.UnsupportedFeatureError: Setting a custom URLStreamHandlerFactory.
	at com.oracle.svm.core.util.VMError.unsupportedFeature(VMError.java:87)
	at java.net.URL.setURLStreamHandlerFactory(URL.java:78)
	at org.apache.catalina.webresources.TomcatURLStreamHandlerFactory.<init>(TomcatURLStreamHandlerFactory.java:130)
	at org.apache.catalina.webresources.TomcatURLStreamHandlerFactory.getInstanceInternal(TomcatURLStreamHandlerFactory.java:53)
	at org.apache.catalina.webresources.TomcatURLStreamHandlerFactory.register(TomcatURLStreamHandlerFactory.java:77)
	at org.apache.catalina.webresources.StandardRoot.registerURLStreamHandlerFactory(StandardRoot.java:699)
	at org.apache.catalina.webresources.StandardRoot.initInternal(StandardRoot.java:682)
	at org.apache.catalina.util.LifecycleBase.init(LifecycleBase.java:107)

Are you interested in a new trouble report with this and/or have the code from a public github account? Or is it just the same thing anyway?

**Comment by RafaelCavazza** [comment] 2021-05-12 19:26
Hi guys! 

Any update on this issue?

**Comment by ade90036** [comment] 2022-02-14 15:26
hi @mcraj017 any ETA of this fix? Is there a potential work around?

**Closed** 2022-03-21 18:35 UTC
Labels: bug, native-image
