### ISSUE TITLE
"Detected a started Thread in the image heap" when running native-image with small number of threads

### ISSUE THREAD

**Issue by fcurts** [oracle/graal#662] opened 2018-09-09 00:48 UTC
In an attempt to find the root cause for https://github.com/oracle/graal/issues/661, I experimented with running native-image with a smaller number of threads (`-H:NumberOfThreads`) and analysis threads (`-H:NumberOfAnalysisThreads`), for example (1, 1), (2, 1), or (4, 2). Doing so always gives the error below, although my static initializers don't start a thread. (However, one static initializer uses the polyglot API to evaluate my Truffle language's standard library - perhaps that starts a thread?) The small number of threads might be a red herring; perhaps running with a higher number of threads deadlocks before getting to this point (https://github.com/oracle/graal/issues/661). GraalVM CE 1.0.0-rc6, macOS. Problem doesn't exist with rc5 and earlier rc's.

```
Error: Detected a started Thread in the image heap. Threads running in the image generator are no longer running at image run time. The object was probably created by a class initializer and is reachable from a static field. By default, all class initialization is done during native image building.You can manually delay class initialization to image run time by using the option --delay-class-initialization-to-runtime=<class-name>. Or you can write your own initialization methods and call them explicitly from your main entry point.
Trace:  object com.oracle.truffle.polyglot.PolyglotThreadInfo
        object java.util.HashMap$Node
        object java.util.HashMap$Node[]
        object java.util.HashMap
        object com.oracle.truffle.polyglot.PolyglotContextImpl
        object com.oracle.truffle.polyglot.PolyglotLanguageContext
        object com.oracle.truffle.polyglot.HostLanguage$HostContext
        object com.oracle.truffle.polyglot.PolyglotLanguage$ContextProfile
        object com.oracle.truffle.polyglot.PolyglotLanguage
        object com.oracle.truffle.polyglot.PolyglotEngineImpl
        object XXX
        object java.lang.Object[]
        object org.graalvm.collections.EconomicMapImpl
        object XXX
        method XXX
Call path from entry point to XXX: 
        at XXX
        at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
        at java.util.stream.SpinedBuffer.forEach(SpinedBuffer.java:246)
        at java.util.stream.SpinedBuffer.toString(SpinedBuffer.java:269)
        at java.lang.String.valueOf(String.java:2994)
        at java.lang.StringBuilder.append(StringBuilder.java:131)
        at com.oracle.svm.core.amd64.AMD64CPUFeatureAccess.verifyHostSupportsArchitecture(AMD64CPUFeatureAccess.java:165)
        at com.oracle.svm.core.JavaMainWrapper.run(JavaMainWrapper.java:138)
        at com.oracle.svm.core.code.CEntryPointCallStubs.com_002eoracle_002esvm_002ecore_002eJavaMainWrapper_002erun_0028int_002corg_002egraalvm_002enativeimage_002ec_002etype_002eCCharPointerPointer_0029(generated:0)
```

**Comment by chumer** [comment] 2018-09-18 19:48
Keeping a polyglot context in the image heap alive is not quite supported yet. We have plans to support it, but it is not yet implemented.

In the meantime instead of preinitializing the polyglot Context in a static initializer you can preinitialize and include a single first context when building the image. 

To achive this your language needs to implement: http://www.graalvm.org/truffle/javadoc/com/oracle/truffle/api/TruffleLanguage.html#patchContext-C-com.oracle.truffle.api.TruffleLanguage.Env-

And you can trigger the preinitialization by providing `-Dpolyglot.engine.PreinitializeContexts=<languageIds>` for example `-Dpolyglot.engine.PreinitializeContexts=js,python` when building the native-image. This will automatically run language context initialization when the native image is created.

If you now native-image compile and run: 
```
public static void main(String[] args) {
    Context context = Context.create();
    context.initialize("yourLanguage");
}
```
it should complete very quickly and not require context initialization as it can reuse the preinitialized context. Note that this only works for the first context that is created.

Preinitializing the context is essential to get the startup time of your language down in an SVM image. We use this feature for most of our languages.

**Comment by fcurts** [comment] 2018-11-14 01:43
> Keeping a polyglot context in the image heap alive is not quite supported yet.

I have a static initializer that creates a context, runs some Truffle code, then closes the context. Does this count as "Keeping a polyglot context in the image heap alive"? As far as I can tell, my own code doesn't hold on to the context.

> And you can trigger the preinitialization by providing -Dpolyglot.engine.PreinitializeContexts=<languageIds>

Here is what I tried:
* implement the `TruffleLanguage.patchContext` method to just return `true` (my context doesn't use anything from `TruffleLanguage.Env`)
* pass `-Dpolyglot.engine.PreinitializeContexts=<my-language-id>` to the native-image command (also tried `-J-D`)

However, I'm still getting the exact same error.

**Comment by chumer** [comment] 2018-11-14 11:14
> Does this count as "Keeping a polyglot context in the image heap alive"?

No, but it could explain the problem you are seeing. You should be able to run a polyglot context in static initializer and close it afterwards, but if you don't hold on to it, it should be fine. We will investigate whether that problem can be reproduced that way.

Are you sure you are also not holding on to any values of that context?

**Comment by chumer** [comment] 2018-11-14 11:17
If it is a problem on our side it should be reproducible by:
```
static {
  try (Context c = Context.create()) {
    c.initialize("js");
  }
}
public static void main(String[] args) {
  try (Context c = Context.create()) {
    c.initialize("js");
  }
}
```

**Comment by fcurts** [comment] 2018-11-14 11:42
> Are you sure you are also not holding on to any values of that context?

Yes I'm pretty sure. I've double-checked that in this particular case, the only field of my context remains uninitialized (`null`), which is expected.

**Comment by fcurts** [comment] 2018-11-14 11:53
The static initializer essentially looks like this:

```
Context context = Context.create("my-id");
context.initialize("my-id");
context.enter();
try {
  // run some Truffle code
} finally {
  context.leave();
}
context.close(true); // not in a finally-block for some technical reason
```

**Comment by tzezula** [comment] 2018-11-15 17:31
I hope the problem is the same as in case of `js` where the `static` field generated by the Truffle DSL holds a `RootNode` which references the `PolyglotContextImpl`. I will fix the DSL.
Just make sure you don't hold any `RootNode`s in static references in your code.

**Comment by fcurts** [comment] 2018-11-15 20:53
My code does hold `RootNodes` in static references by design, but those root nodes don't reference `PolyglotContextImpl` (unless you are saying this happens under the hood).

**Comment by tzezula** [comment] 2018-11-23 10:30
Should be fixed by: https://github.com/oracle/graal/commit/5af1dc323021a4b434657d98c313bd5f9e2ddca7

**Closed by tzezula** 2018-11-23 10:30 UTC

**Comment by fcurts** [comment] 2018-12-21 21:10
@tzezula Unfortunately, I'm getting the exact same error/trace with rc-10.
