### ISSUE TITLE
GraalVM CE-23.0 jdk-17.0.7 native-image build fails due to over resource consumption

### ISSUE THREAD

**Issue by amizurov** [oracle/graal#6845] opened 2023-06-20 20:33 UTC
**Describe the issue**
Hi, folks. After updating to the new version of GraalVM ([graalvm-community-jdk-17.0.7_linux-x64_bin.tar.gz](https://github.com/graalvm/graalvm-ce-builds/releases/download/jdk-17.0.7/graalvm-community-jdk-17.0.7_linux-x64_bin.tar.gz)) we faced with some problem while building the native-image and over resource consumption.

**Steps to reproduce the issue**
1. Build a spring-boot-application.
2. Copy a jar to the docker container with GraalVM, unpack them and run native-image build.
3.  DOCKER>Error: Image build request for 'native-application' (pid: 54, path: /build/native-image) failed with exit status 30

The consumption of resources for [graalvm-community-jdk-17.0.7_linux-x64_bin.tar.gz](https://github.com/graalvm/graalvm-ce-builds/releases/download/jdk-17.0.7/graalvm-community-jdk-17.0.7_linux-x64_bin.tar.gz) and logs:
 
<img width="1202" alt="Screenshot 2023-06-20 at 21 29 04" src="https://github.com/oracle/graal/assets/8257855/22505f8f-02d5-4da8-9904-b99c0730084e">

```
 native-image -H:Name=native-application -cp BOOT-INF/classes:BOOT-INF/lib:BOOT-INF/lib/...
...
[INFO] DOCKER> Field org.springframework.web.servlet.support.RequestContext#jstlPresent set to false at build time
20:14:56   [INFO] DOCKER> [2/8] Performing analysis...  [********]                                                              (1069.8s @ 3.73GB)
20:14:56   GC warning: 932.0s spent in 476 GCs during the last stage, taking up 87.10% of the time.
20:14:56   [INFO] DOCKER> Please ensure more than 5.41GB of memory is available for Native Image
20:14:56               to reduce GC overhead and improve image build time.
20:14:56   [INFO] DOCKER> 50,243 (93.15%) of 53,938 types reachable
20:14:56   [INFO] DOCKER> 85,705 (71.26%) of 120,269 fields reachable
20:14:56   [INFO] DOCKER> 238,809 (64.35%) of 371,121 methods reachable
20:14:56   [INFO] DOCKER> 15,885 types, 4,181 fields, and 27,178 methods registered for reflection
20:14:56   [INFO] DOCKER> 71 types,    78 fields, and    59 methods registered for JNI access
20:14:56          4 native libraries: dl, pthread, rt, z
20:25:00   [INFO] DOCKER>
20:25:00   
20:25:11   [INFO] DOCKER>=== Image generator watchdog detected no activity. This can be a sign of a deadlock during image building. Dumping all stack traces. Current time: Tue Jun 20 19:25:00 GMT 2023
20:25:11   
20:25:23   [INFO] DOCKER>"main" Id=1 in RUNNABLE
20:25:26   [INFO] DOCKER>
20:25:26   
20:25:26   [INFO] DOCKER>    at java.base@17.0.7/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
20:25:26       at java.base@17.0.7/java.lang.reflect.Method.invoke(Method.java:568)
20:25:26       at platform/jdk.internal.vm.compiler/org.graalvm.compiler.hotspot.meta.HotSpotSnippetReflectionProvider.originalMethod(HotSpotSnippetReflectionProvider.java:170)
20:25:26       at app/org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.infrastructure.OriginalMethodProvider.getJavaMethod(OriginalMethodProvider.java:49)
20:25:26   
20:25:26   [INFO] DOCKER>    at app/org.graalvm.nativeimage.builder/com.oracle.svm.hosted.annotation.SubstrateAnnotationExtractor.findRoot(SubstrateAnnotationExtractor.java:453)
20:25:26       at app/org.graalvm.nativeimage.builder/com.oracle.svm.hosted.annotation.SubstrateAnnotationExtractor.getAnnotationData(SubstrateAnnotationExtractor.java:188)
20:25:26       at app/org.graalvm.nativeimage.builder/com.oracle.svm.hosted.annotation.SubstrateAnnotationExtractor.extractAnnotation(SubstrateAnnotationExtractor.java:123)
20:25:26       at app/org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.meta.AnalysisElement.getAnnotation(AnalysisElement.java:61)
20:25:26       at app/org.graalvm.nativeimage.builder/com.oracle.svm.hosted.meta.UniverseBuilder.makeMethod(UniverseBuilder.java:312)
20:25:26       at app/org.graalvm.nativeimage.builder/com.oracle.svm.hosted.meta.UniverseBuilder.build(UniverseBuilder.java:156)
20:25:26       at app/org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGenerator.doRun(NativeImageGenerator.java:601)
20:25:26       at app/org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGenerator.run(NativeImageGenerator.java:539)
20:25:26       at app/org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGeneratorRunner.buildImage(NativeImageGeneratorRunner.java:408)
20:25:26       at app/org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGeneratorRunner.build(NativeImageGeneratorRunner.java:612)
20:25:26       at app/org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGeneratorRunner.start(NativeImageGeneratorRunner.java:134)
20:25:26       at app/org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGeneratorRunner.main(NativeImageGeneratorRunner.java:94)
20:25:26   
20:25:26   "Reference Handler" Id=2 in RUNNABLE
20:25:26       at java.base@17.0.7/java.lang.ref.Reference.waitForReferencePendingList(Native Method)
20:25:26       at java.base@17.0.7/java.lang.ref.Reference.processPendingReferences(Reference.java:253)
20:25:26       at java.base@17.0.7/java.lang.ref.Reference$ReferenceHandler.run(Reference.java:215)
20:25:26   
20:25:26   "Finalizer" Id=3 in WAITING on lock=java.lang.ref.ReferenceQueue$Lock@2c6b6344
20:25:26       at java.base@17.0.7/java.lang.Object.wait(Native Method)
20:25:26       at java.base@17.0.7/java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:155)
20:25:26       at java.base@17.0.7/java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:176)
20:25:26       at java.base@17.0.7/java.lang.ref.Finalizer$FinalizerThread.run(Finalizer.java:172)
20:25:26   
20:25:26   "Signal Dispatcher" Id=4 in RUNNABLE
20:25:26   
20:25:26   "JVMCI-native CompilerThread0" Id=7 in RUNNABLE
20:25:26   
20:25:26   "Common-Cleaner" Id=11 in TIMED_WAITING on lock=java.lang.ref.ReferenceQueue$Lock@22ac88b9
20:25:26       at java.base@17.0.7/java.lang.Object.wait(Native Method)
20:25:26       at java.base@17.0.7/java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:155)
20:25:26       at java.base@17.0.7/jdk.internal.ref.CleanerImpl.run(CleanerImpl.java:140)
20:25:26       at java.base@17.0.7/java.lang.Thread.run(Thread.java:833)
20:25:26       at java.base@17.0.7/jdk.internal.misc.InnocuousThread.run(InnocuousThread.java:162)
20:25:26   
20:25:26   "Notification Thread" Id=12 in RUNNABLE
20:25:26   
20:25:26   "native-image pid watcher" Id=13 in TIMED_WAITING on lock=java.util.TaskQueue@26930834
20:25:26       at java.base@17.0.7/java.lang.Object.wait(Native Method)
20:25:26       at java.base@17.0.7/java.util.TimerThread.mainLoop(Timer.java:563)
20:25:26       at java.base@17.0.7/java.util.TimerThread.run(Timer.java:516)
20:25:26   
20:25:26   "Thread-1" Id=14 in RUNNABLE
20:25:26       at java.management@17.0.7/sun.management.ThreadImpl.dumpThreads0(Native Method)
20:25:26       at java.management@17.0.7/sun.management.ThreadImpl.dumpAllThreads(ThreadImpl.java:521)
20:25:26       at java.management@17.0.7/sun.management.ThreadImpl.dumpAllThreads(ThreadImpl.java:509)
20:25:26       at app/org.graalvm.nativeimage.builder/com.oracle.svm.hosted.DeadlockWatchdog.threadDump(DeadlockWatchdog.java:124)
20:25:26       at app/org.graalvm.nativeimage.builder/com.oracle.svm.hosted.DeadlockWatchdog.watchdogThread(DeadlockWatchdog.java:81)
20:25:26       at app/org.graalvm.nativeimage.builder/com.oracle.svm.hosted.DeadlockWatchdog$$Lambda$140/0x00000007c018da18.run(Unknown Source)
20:25:26       at java.base@17.0.7/java.lang.Thread.run(Thread.java:833)
20:25:26   
20:25:26   "Timer-0" Id=28 in TIMED_WAITING on lock=java.util.TaskQueue@63918282
20:25:26       at java.base@17.0.7/java.lang.Object.wait(Native Method)
20:25:26       at java.base@17.0.7/java.util.TimerThread.mainLoop(Timer.java:563)
20:25:26       at java.base@17.0.7/java.util.TimerThread.run(Timer.java:516)
20:25:26   
20:25:26   
20:25:26   === Memory statistics (in MB):
20:25:26   === Used heap size: 4301
20:25:26   === Free heap size: 472
20:25:26   === Maximum heap size: 4301
20:25:26   === Image generator watchdog is aborting image generation. To configure the watchdog, use the options -H:DeadlockWatchdogInterval=10 and -H:+DeadlockWatchdogExitOnTimeout
20:25:26   
20:25:35   [INFO] DOCKER>Error: Image build request for 'native-application' (pid: 54, path: /build/native-image) failed with exit status 30
20:25:35   
20:25:36   [INFO] DOCKER> Removing intermediate container e0c0dee4eca6
```

The consumption of resources for [graalvm-ce-java17-linux-amd64-22.3.2.tar.gz](https://github.com/graalvm/graalvm-ce-builds/releases/download/vm-22.3.2/graalvm-ce-java17-linux-amd64-22.3.2.tar.gz) and logs:
<img width="1194" alt="Screenshot 2023-06-20 at 22 13 54" src="https://github.com/oracle/graal/assets/8257855/c60a7f94-93db-4d1f-9336-31a1e577271a">

```
native-image -H:Name=native-application -cp BOOT-INF/classes:BOOT-INF/lib:BOOT-INF/lib/...
...
[INFO] DOCKER> Field org.springframework.web.servlet.support.RequestContext#jstlPresent set to false at build time
10:37:16   [INFO] DOCKER>
10:39:22   [INFO] DOCKER> [2/7] Performing analysis...  [************]                                                           (208.6s @ 4.83GB)
10:39:22     50,563 (94.38%) of 53,572 classes reachable
10:39:22   [INFO] DOCKER> 84,699 (71.30%) of 118,799 fields reachable
10:39:22   [INFO] DOCKER> 235,688 (64.06%) of 367,893 methods reachable
10:39:22      3,672 classes, 4,183 fields, and 26,409 methods registered for reflection
10:39:22         72 classes,    78 fields, and    62 methods registered for JNI access
10:39:22          6 native libraries: dl, m, pthread, rt, stdc++, z
10:39:53   [INFO] DOCKER> [3/7] Building universe...                                                                              (31.3s @ 3.57GB)
10:40:07   [INFO] DOCKER> [4/7] Parsing methods...      [****]                                                                    (14.6s @ 4.16GB)
10:40:17   [INFO] DOCKER> [5/7] Inlining methods...     [****]                                                                     (8.3s @ 4.56GB)
10:41:49   [INFO] DOCKER> [6/7] Compiling methods...    [*********]                                                               (92.1s @ 4.15GB)
10:42:29   [INFO] DOCKER> [7/7] Creating image...                                                                                 (16.1s @ 4.40GB)
10:42:29    102.12MB (43.40%) for code area:   157,726 compilation units
10:42:29    121.98MB (51.84%) for image heap:  924,917 objects and 4,704 resources
10:42:29     11.20MB ( 4.76%) for other data
10:42:29    235.30MB in total
10:42:29   ------------------------------------------------------------------------------------------------------------------------
10:42:29   Top 10 packages in code area:                               Top 10 object types in image heap:
10:42:29      5.92MB org.apache.kafka.common.message                     38.77MB byte[] for embedded resources
10:42:29      3.53MB jdk.proxy4                                          21.79MB byte[] for code metadata
10:42:29      1.65MB sun.security.ssl                                    12.61MB java.lang.Class
10:42:29      1.27MB java.util                                            9.47MB byte[] for java.lang.String
10:42:29    934.81KB java.lang.invoke                                     8.93MB java.lang.String
10:42:29    862.38KB com.oracle.svm.core.code                             6.32MB byte[] for general heap data
10:42:29    828.17KB org.apache.camel.impl.engine                         4.24MB com.oracle.svm.core.hub.DynamicHubCompanion
10:42:29    719.33KB com.sun.crypto.provider                              3.80MB byte[] for reflection metadata
10:42:29    717.17KB org.hibernate.dialect                                1.75MB c.o.svm.core.hub.DynamicHub$ReflectionMetadata
10:42:29    620.88KB java.lang                                            1.72MB java.lang.String[]
10:42:29     84.01MB for 2070 more packages                              11.93MB for 8924 more object types
10:42:29   ------------------------------------------------------------------------------------------------------------------------
10:42:29   [INFO] DOCKER> 62.3s (14.8% of total time) in 223 GCs | Peak RSS: 6.84GB | CPU load: 2.83
10:42:29   ------------------------------------------------------------------------------------------------------------------------
10:42:29   Produced artifacts:
10:42:29    /build/native-image/native-application (executable)
10:42:29    /build/native-image/native-application.build_artifacts.txt (txt)
10:42:29   ========================================================================================================================
10:42:29   Finished generating 'native-application' in 6m 59s.

```
**Describe GraalVM and your environment:**
 - GraalVM version ([graalvm-community-jdk-17.0.7_linux-x64_bin.tar.gz](https://github.com/graalvm/graalvm-ce-builds/releases/download/jdk-17.0.7/graalvm-community-jdk-17.0.7_linux-x64_bin.tar.gz))
 - JDK major version: **[17.0.7]**
 - OS: **[Linux]**
 - Architecture: **[AMD64]**

**More details:**
I'm also built it on local machine (MacOS, arm64), the exception was little bit different:
```
DOCKER> Field org.springframework.web.servlet.support.RequestContext#jstlPresent set to false at build time
[INFO] DOCKER> 
[INFO] DOCKER> [2/8] Performing analysis...  [*********]                                                              (220.1s @ 4.08GB)
[INFO] DOCKER> 50,241 (93.16%) of 53,927 types reachable
[INFO] DOCKER> 85,696 (71.31%) of 120,171 fields reachable
[INFO] DOCKER> 238,809 (64.35%) of 371,109 methods reachable
[INFO] DOCKER> 15,883 types, 4,181 fields, and 27,178 methods
[INFO] DOCKER> registered for reflection
      71 types,    78 fields, and    59 methods
[INFO] DOCKER> registered for JNI access
[INFO] DOCKER> 4 native libraries:
[INFO] DOCKER> dl, pthread, rt, z
[INFO] DOCKER> [3/8] Building universe...                                                                              (64.1s @ 4.21GB)
[INFO] DOCKER> [91mError: Image build request for 'native-application' (pid: 56, path: /build/native-image) failed with exit status 137
```

After that i'm increase memory to 10GB and everything look good, but a build time increased significantly:
```Finished generating 'native-application' in 12m 47s in a previous setup it took about 5-6m.```

**Comment by fniephaus** [comment] 2023-06-21 10:50
Hi @amizurov, thanks for the extensive bug report. Could you share more details on the docker environment? is your build going through some buildpack or what container are you using? Also, could you maybe run your Native Image build with `-J-XshowSettings:vm` and report the max heap value of a 22.3 build process vs the latest GraalVM release?

**Comment by amizurov** [comment] 2023-06-21 15:59
> Hi @amizurov, thanks for the extensive bug report. Could you share more details on the docker environment? is your build going through some buildpack or what container are you using? Also, could you maybe run your Native Image build with `-J-XshowSettings:vm` and report the max heap value of a 22.3 build process vs the latest GraalVM release?

Hi @fniephaus, thanks for the quick response. I try to do my best and provide more details.

- _is your build going through some buildpack or what container are you using?_ 

No we use our own docker file to building native-image like so:
```
# The native builder image with installed GraalVM CE and native-image
FROM @graalvm.native.image@ as builder

WORKDIR /build/native-image

COPY /@apring.aot.application@.jar /build/native-image/native-application.jar

ARG COMPRESSION_METHOD=none
RUN ["/bin/bash", "-c", "set -ex \
         && jar -xvf native-application.jar >/dev/null 2>&1 \
         && cp -R META-INF BOOT-INF/classes \
         && native-image -H:Name=native-application -cp BOOT-INF/classes:`find BOOT-INF/lib | tr '\n' ':'` \
         && if [[ $COMPRESSION_METHOD == 'upx' ]]; then \
              upx --lzma --best -o ../native-application native-application; \
            else \
              mv native-application ..; \
            fi"]

# The deployment Image
FROM @deplyoment.base.image@

COPY --from=builder /build/native-application            /opt/app/native-application
ENTRYPOINT ["/opt/app/native-application"]
```

- _Also, could you maybe run your Native Image build with -J-XshowSettings:vm and report the max heap value_

[graalvm-community-jdk-17.0.7](https://github.com/graalvm/graalvm-ce-builds/releases/download/jdk-17.0.7/graalvm-community-jdk-17.0.7_linux-x64_bin.tar.gz) with `-J-XshowSettings:vm` failed:

```
[INFO] DOCKER>VM settings:

[INFO] DOCKER>    Stack Size: 10.00M
[INFO] DOCKER>    Max. Heap Size (Estimated): 3.97G
     Using VM: OpenJDK 64-Bit Server VM
 
     Property settings:
  
  [INFO] DOCKER>    com.oracle.graalvm.isaot = true
  
  [INFO] DOCKER>    file.encoding = ANSI_X3.4-1968
      file.separator = /
      graalvm.ForcePolyglotInvalid = true
  [INFO] DOCKER>
      graalvm.locatorDisabled = true
  
  [INFO] DOCKER>    java.awt.headless =
  [INFO] DOCKER>true
  [INFO] DOCKER>
      java.class.path =
  [INFO] DOCKER>
      java.class.version = 61.0
      java.home = /opt/java/graalvm-ce-jdk-17.0.7
      java.io.tmpdir = /tmp
  
  [INFO] DOCKER>    java.lang.invoke.InnerClassLambdaMetafactory.initializeLambdas = false
  [INFO] DOCKER>
  
  [INFO] DOCKER>    java.library.path =
  [INFO] DOCKER>/usr/java/packages/lib
  [INFO] DOCKER>
  
  [INFO] DOCKER>        /usr/lib64
          /lib64
  
  [INFO] DOCKER>        /lib
  [INFO] DOCKER>
  
  [INFO] DOCKER>        /usr/lib
  
  [INFO] DOCKER>    java.runtime.name =
  [INFO] DOCKER>OpenJDK Runtime Environment
  
  [INFO] DOCKER>    java.runtime.version =
  [INFO] DOCKER>17.0.7+7-jvmci-23.0-b12
  [INFO] DOCKER>
  
  [INFO] DOCKER>    java.specification.name =
  [INFO] DOCKER>Java Platform API Specification
  [INFO] DOCKER>
      java.specification.vendor = Oracle Corporation
      java.specification.version = 17
      java.system.class.loader = com.oracle.svm.hosted.NativeImageSystemClassLoader
      java.vendor = GraalVM Community
      java.vendor.url = https://www.graalvm.org/
      java.vendor.url.bug = https://github.com/oracle/graal/issues
      java.vendor.version = GraalVM CE 17.0.7+7.1
      java.version = 17.0.7
      java.version.date = 2023-04-18
  
  [INFO] DOCKER>    java.vm.compressedOopsMode =
  [INFO] DOCKER>Zero based
  
  [INFO] DOCKER>    java.vm.info = mixed mode
      java.vm.name = OpenJDK 64-Bit Server VM
      java.vm.specification.name = Java Virtual Machine Specification
      java.vm.specification.vendor = Oracle Corporation
      java.vm.specification.version = 17
      java.vm.vendor = GraalVM Community
      java.vm.version = 17.0.7+7-jvmci-23.0-b12
      jdk.debug = release
      jdk.internal.lambda.disableEagerInitialization = true
      jdk.internal.lambda.eagerlyInitialize = false
      jdk.internal.vm.ci.enabled = true
      jdk.module.main = org.graalvm.nativeimage.builder
      jdk.module.path = /opt/java/graalvm-ce-jdk-17.0.7/lib/truffle/truffle-api.jar
          /opt/java/graalvm-ce-jdk-17.0.7/lib/svm/builder/svm.jar
          /opt/java/graalvm-ce-jdk-17.0.7/lib/svm/builder/objectfile.jar
          /opt/java/graalvm-ce-jdk-17.0.7/lib/svm/builder/native-image-base.jar
          /opt/java/graalvm-ce-jdk-17.0.7/lib/svm/builder/pointsto.jar
      line.separator = \n
      native.encoding = ANSI_X3.4-1968
      org.graalvm.vendor = GraalVM Community
      org.graalvm.vendorurl = https://www.graalvm.org/
      org.graalvm.vendorversion = GraalVM CE 17.0.7+7.1
      org.graalvm.version = 23.0.0
      os.arch = amd64
      os.name = Linux
      os.version = 5.4.0-152-generic
      path.separator = :
      substratevm.HostLibC = glibc
      substratevm.IgnoreGraalVersionCheck = true
      sun.arch.data.model = 64
      sun.boot.library.path = /opt/java/graalvm-ce-jdk-17.0.7/lib
      sun.cpu.endian = little
      sun.io.unicode.encoding = UnicodeLittle
      sun.java.command = org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGeneratorRunner -watchpid 31 --image-args-file=/tmp/native-image570355058893567905.args
     ....
     ....
  === Memory statistics (in MB):
   === Used heap size: 4054
   === Free heap size: 490
   === Maximum heap size: 4062
   === Image generator watchdog is aborting image generation. To configure the watchdog, use the options -H:DeadlockWatchdogInterval=10 and -H:+DeadlockWatchdogExitOnTimeout
   
[INFO] DOCKER>Error: Image build request for 'native-application' (pid: 54, path: /build/native-image) failed with exit status 30
``` 

[graalvm-ce-java17-linux-amd64-22.3.2](https://github.com/graalvm/graalvm-ce-builds/releases/download/vm-22.3.2/graalvm-ce-java17-linux-amd64-22.3.2.tar.gz) with `-J-XshowSettings:vm` successful:

```
[INFO] DOCKER>VM settings:
  
  [INFO] DOCKER>    Stack Size: 10.00M
  
  [INFO] DOCKER>    Min. Heap Size: 1.00G
      Max. Heap Size: 6.18G
  [INFO] DOCKER>
  
  [INFO] DOCKER>    Using VM: OpenJDK 64-Bit Server VM
  [INFO] DOCKER>
  
  [INFO] DOCKER>
  
  [INFO] DOCKER>Property settings:
  
  [INFO] DOCKER>    com.oracle.graalvm.isaot = true
  [INFO] DOCKER>
      file.encoding =
  [INFO] DOCKER>ANSI_X3.4-1968
  [INFO] DOCKER>
  
  [INFO] DOCKER>    file.separator =
  [INFO] DOCKER>/
  
  [INFO] DOCKER>    graalvm.ForcePolyglotInvalid = true
  [INFO] DOCKER>
      graalvm.locatorDisabled =
  [INFO] DOCKER>true
      java.awt.headless = true
      java.class.path =
      java.class.version = 61.0
      java.home = /opt/graalvm-ce-java17-22.3.2
      java.io.tmpdir = /tmp
      java.lang.invoke.InnerClassLambdaMetafactory.initializeLambdas = false
      java.library.path = /usr/java/packages/lib
          /usr/lib64
          /lib64
          /lib
          /usr/lib
      java.runtime.name = OpenJDK Runtime Environment
      java.runtime.version = 17.0.7+7-jvmci-22.3-b18
      java.specification.name = Java Platform API Specification
      java.specification.vendor = Oracle Corporation
      java.specification.version = 17
      java.system.class.loader = com.oracle.svm.hosted.NativeImageSystemClassLoader
      java.vendor = GraalVM Community
      java.vendor.url = https://www.graalvm.org/
      java.vendor.url.bug = https://github.com/oracle/graal/issues
      java.vendor.version = GraalVM CE 22.3.2
      java.version = 17.0.7
      java.version.date = 2023-04-18
      java.vm.compressedOopsMode = Zero based
      java.vm.info = mixed mode
      java.vm.name = OpenJDK 64-Bit Server VM
      java.vm.specification.name = Java Virtual Machine Specification
      java.vm.specification.vendor = Oracle Corporation
      java.vm.specification.version = 17
      java.vm.vendor = GraalVM Community
      java.vm.version = 17.0.7+7-jvmci-22.3-b18
      jdk.debug = release
      jdk.internal.lambda.disableEagerInitialization = true
      jdk.internal.lambda.eagerlyInitialize = false
      jdk.internal.vm.ci.enabled = true
      jdk.module.main = org.graalvm.nativeimage.builder
      jdk.module.path = /opt/graalvm-ce-java17-22.3.2/lib/truffle/truffle-api.jar
          /opt/graalvm-ce-java17-22.3.2/lib/svm/builder/svm.jar
          /opt/graalvm-ce-java17-22.3.2/lib/svm/builder/objectfile.jar
          /opt/graalvm-ce-java17-22.3.2/lib/svm/builder/native-image-base.jar
          /opt/graalvm-ce-java17-22.3.2/lib/svm/builder/pointsto.jar
  
  [INFO] DOCKER>    line.separator =
  [INFO] DOCKER>\n
  [INFO] DOCKER>
  
  [INFO] DOCKER>    native.encoding =
  [INFO] DOCKER>ANSI_X3.4-1968
  
  [INFO] DOCKER>    org.graalvm.version =
  [INFO] DOCKER>22.3.2
  
  [INFO] DOCKER>    os.arch =
  [INFO] DOCKER>amd64
  
  [INFO] DOCKER>    os.name = Linux
  [INFO] DOCKER>
      os.version =
  [INFO] DOCKER>5.4.0-152-generic
  [INFO] DOCKER>
  
  [INFO] DOCKER>    path.separator = :
  [INFO] DOCKER>
  
  [INFO] DOCKER>    substratevm.IgnoreGraalVersionCheck =
  [INFO] DOCKER>true
  
  [INFO] DOCKER>    sun.arch.data.model =
  [INFO] DOCKER>64
  [INFO] DOCKER>
  
  [INFO] DOCKER>    sun.boot.library.path =
  [INFO] DOCKER>/opt/graalvm-ce-java17-22.3.2/lib
  [INFO] DOCKER>
  
  [INFO] DOCKER>    sun.cpu.endian =
  [INFO] DOCKER>little
  [INFO] DOCKER>
  
  [INFO] DOCKER>    sun.io.unicode.encoding =
  [INFO] DOCKER>UnicodeLittle
  
  [INFO] DOCKER>    sun.java.command =
  [INFO] DOCKER>org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGeneratorRunner -watchpid 31 --image-args-file=/tmp/native-image11440685210887572138.args
 ...
 ...
[INFO] DOCKER> 48.9s (12.7% of total time) in 211 GCs | Peak RSS: 6.80GB | CPU load: 2.74
   ------------------------------------------------------------------------------------------------------------------------
   Produced artifacts:
    /build/native-image/native-application (executable)
    /build/native-image/native-application.build_artifacts.txt (txt)
   ========================================================================================================================
   Finished generating 'native-application' in 6m 22s.
```

Hmm.. 
- Max. Heap Size (Estimated): 3.97G  
- Max. Heap Size: 6.18G 
is different between this 2 builds.

**Comment by fniephaus** [comment] 2023-06-21 17:10
> I try to do my best and provide more details.

Thanks for taking the time to help investigate this further!

> Max. Heap Size: 3.97G vs. 6.18G

That's very interesting. What is the memory limit for these containers? The screenshot in the original post mentions "7915mb", so maybe the containers have access to something like 8 GB?

In the past, a lot of users have experienced crashes due to OOM kills, especially when using containers. For this reason, 
 the Native Image build process now takes available memory into account to size the max Java heap of the process. So a lower max heap in the new release suggests that there are more processes running in the container that use a significant amount of memory.

Could you determine available memory in your container right before the Native Image build process starts (e.g., by running the `free` command)? You may also want to list all processes running in the container and sort them by RSS (via `ps aux --sort -rss` for example).

**Comment by amizurov** [comment] 2023-06-21 22:18
> That's very interesting. What is the memory limit for these containers? The screenshot in the original post mentions "7915mb", so maybe the containers have access to something like 8 GB?

Yes you are right 8GB on build agent (host machine with containerd) without docker container limits: 
```
free
               total        used        free      shared  buff/cache   available
Mem:         8105032     1289876     1544524        1504     5270632     6536924
Swap:        8388604       12032     8376572
```

```
ps aux --sort -rss
USER         PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
root           1  0.0  0.0   4620  3820 pts/0    Ss   22:13   0:00 /bin/bash
root          12  0.0  0.0   7052  1608 pts/0    R+   22:16   0:00 ps aux --sort -rss
```

**Comment by fniephaus** [comment] 2023-06-22 06:38
Thanks for those numbers, @amizurov.

It seems that only ~80% of those 8GB are available. Nonetheless, 3.97GB is still off by more than 2GB from the 6.24GB available memory.

Let me see if I can reproduce this with PetClinic and a 8GB container. If not, a reproducer may help.

**Comment by amizurov** [comment] 2023-06-28 11:23
> et me see if I can reproduce this with PetClinic and a 8GB container. If not, a reproducer may help.

Hi @fniephaus. So after some investigation i found the solution for our case (J-XX:MaxRAMPercentage=85 -J-XshowSettings:vm) and now the Max. Heap Size (Estimated): 5,86 looks similar with previous. 
So, the main problem here is that the new algorithm takes into account other processes that are running on the host computer, and sets less memory for the heap, but the build cannot complete correctly because more resources are needed to build a native-image and we are stuck here (frequent GCs, CPU overloading). I think that this problem can be appeared not only for us.

**Comment by fniephaus** [comment] 2023-10-31 09:54
We have revised the max heap logic and the changes ship with the JDK 21 release. The new logic falls back to 85% of total memory if not enough free memory (8GB) is found:

https://github.com/oracle/graal/blob/97a8bb6194babca0c326e2f9279774a05fd7a995/substratevm/src/com.oracle.svm.driver/src/com/oracle/svm/driver/MemoryUtil.java#L71-L102

I'm closing this for now. Feel free to re-open again if you have any further suggestions.

**Closed by fniephaus** 2023-10-31 09:54 UTC
Labels: bug, native-image

**Comment by yashodgayashan** [comment] 2023-12-18 00:26
I have encountered the same issue and to solve this I had to increase the DeadlockWatchDog interval. In some cases, the executable building process is terminated once the WatchDog identifies that is a Deadlock. 

**Solution**

```
-H:DeadlockWatchdogInterval=<time-in-seconds>
```
