### ISSUE TITLE
bin/gu fails to install `ruby`

### ISSUE THREAD

**Issue by phykos** [oracle/graal#2780] opened 2020-08-23 14:38 UTC
**Describe GraalVM and your environment :*Manjaro RPi 4 AArch64*
 - GraalVM version or commit id if built from source: **20.2.0-dev**
 - CE or EE: **CE**
 - JDK version: **Java 11**
 - OS and OS Version: **GNU/Linux Manjaro**
 - Architecture: **AArch64**
 - The output of `java -Xinternalversion`:
```
 **OpenJDK 64-Bit Server VM (11.0.8+10-jvmci-20.2-b03) for linux-aarch64 JRE (11.0.8+10-jvmci-20.2-b03), built on Jul 20 2020 17:29:19 by "buildslave" with gcc 7.3.1 20180303 (Red Hat 7.3.1-5)
**
```

**Have you verified this issue still happens when using the latest snapshot?**
Yes, indeed I downloaded the VM from graalvm/graalvm-ce-builds

**Describe the issue**
`bin/gu` isn't able to download the right component catalog, more specifically, it fails to `install ruby`

**Code snippet or code repository that reproduces the issue**
```
**bin/gu install ruby**
```

**Steps to reproduce the issue**
Please include both build steps as well as run steps
1. Step one [downloaded and extracted the tarball]
2. Step two [`bin/gu install ruby`]

**Expected behavior**
The previous snapshot downloaded the catalog from `raw.githubusercontent.com` and installed TruffleRuby just fine, and I was expecting that to happen, instead I got the following output:
```
Downloading: Component catalog from www.graalvm.org
Error: Unknown component: ruby
```

**Comment by mcraj017** [comment] 2020-08-23 22:46
@phykos Thanks for reporting the issue,

But, As I have checked the issue is not present in the final release of graalvm-ce-java11-20.2.0 
You can download it from here https://github.com/graalvm/graalvm-ce-builds/releases/tag/vm-20.2.0

and if you want to use the latest pre-release build, you can download from the below link
I have checked and there is no issue in downloading ruby in this built too
https://github.com/graalvm/graalvm-ce-dev-builds/releases/tag/20.3.0-dev-20200822_0158

I am closing this issue, now as there is no issue with the latest releases
and I have notified the release team about the same

**Closed by mcraj017** 2020-08-23 22:46 UTC
Labels: tools
