### ISSUE TITLE
Error: com.oracle.svm.hosted.substitute.DeletedElementException: Unsupported method java.lang.ClassLoader.defineClass1

### ISSUE THREAD

**Issue by viktorklang** [oracle/graal#2369] opened 2020-04-20 17:39 UTC
**Describe the issue**
native-image generation fails with the given stack trace below

**Steps to reproduce the issue**
Currently only available in my work-in-progress branch of cloudstate.io

**Describe GraalVM and your environment:**
 - GraalVM version: CE 20.0
 - JDK major version: **[e.g.:8]**
 - OS: **macOS Catalina**
 - Architecture: **[e.g.: Intel x86-64]**

**More details**

```
[error] Error: com.oracle.svm.hosted.substitute.DeletedElementException: Unsupported method java.lang.ClassLoader.defineClass1(ClassLoader, String, byte[], int, int, ProtectionDomain, String) is reachable
[error] To diagnose the issue, you can add the option --report-unsupported-elements-at-runtime. The unsupported element is then reported at run time when it is accessed the first time.
[error] Detailed message:
[error] Trace:
[error] 	at parsing java.lang.ClassLoader.defineClass(ClassLoader.java:1016)
[error] Call path from entry point to java.lang.ClassLoader.defineClass(String, byte[], int, int, ProtectionDomain):
[error] 	at java.lang.ClassLoader.defineClass(ClassLoader.java:1014)
[error] 	at java.lang.ClassLoader.defineClass(ClassLoader.java:877)
[error] 	at com.oracle.svm.reflect.ClassLoader_defineClass_c6c343b4d6dc22ca64eb2d8503b13ac9c340dcb3_4697.invoke(Unknown Source)
[error] 	at java.lang.reflect.Method.invoke(Method.java:566)
[error] 	at com.oracle.svm.core.hub.DynamicHub.initEnumConstantsAtRuntime(DynamicHub.java:458)
[error] 	at com.oracle.svm.core.hub.DynamicHub.lambda$initEnumConstantsAtRuntime$1(DynamicHub.java:438)
[error] 	at com.oracle.svm.core.hub.DynamicHub$$Lambda$783/0x00000007c212e040.get(Unknown Source)
[error] 	at com.oracle.svm.core.jdk.SystemPropertiesSupport.initializeLazyValue(SystemPropertiesSupport.java:190)
[error] 	at com.oracle.svm.core.jdk.SystemPropertiesSupport.getProperty(SystemPropertiesSupport.java:143)
[error] 	at com.oracle.svm.core.jdk.Target_java_lang_System.getProperty(JavaLangSubstitutions.java:340)
[error] 	at com.oracle.svm.jni.JNIJavaCallWrappers.jniInvoke_VA_LIST:Ljava_lang_System_2_0002egetProperty_00028Ljava_lang_String_2_00029Ljava_lang_String_2(generated:0)
[error] com.oracle.svm.core.util.UserError$UserException: com.oracle.svm.hosted.substitute.DeletedElementException: Unsupported method java.lang.ClassLoader.defineClass1(ClassLoader, String, byte[], int, int, ProtectionDomain, String) is reachable
[error] To diagnose the issue, you can add the option --report-unsupported-elements-at-runtime. The unsupported element is then reported at run time when it is accessed the first time.
[error] Detailed message:
[error] Trace:
[error] 	at parsing java.lang.ClassLoader.defineClass(ClassLoader.java:1016)
[error] Call path from entry point to java.lang.ClassLoader.defineClass(String, byte[], int, int, ProtectionDomain):
[error] 	at java.lang.ClassLoader.defineClass(ClassLoader.java:1014)
[error] 	at java.lang.ClassLoader.defineClass(ClassLoader.java:877)
[error] 	at com.oracle.svm.reflect.ClassLoader_defineClass_c6c343b4d6dc22ca64eb2d8503b13ac9c340dcb3_4697.invoke(Unknown Source)
[error] 	at java.lang.reflect.Method.invoke(Method.java:566)
[error] 	at com.oracle.svm.core.hub.DynamicHub.initEnumConstantsAtRuntime(DynamicHub.java:458)
[error] 	at com.oracle.svm.core.hub.DynamicHub.lambda$initEnumConstantsAtRuntime$1(DynamicHub.java:438)
[error] 	at com.oracle.svm.core.hub.DynamicHub$$Lambda$783/0x00000007c212e040.get(Unknown Source)
[error] 	at com.oracle.svm.core.jdk.SystemPropertiesSupport.initializeLazyValue(SystemPropertiesSupport.java:190)
[error] 	at com.oracle.svm.core.jdk.SystemPropertiesSupport.getProperty(SystemPropertiesSupport.java:143)
[error] 	at com.oracle.svm.core.jdk.Target_java_lang_System.getProperty(JavaLangSubstitutions.java:340)
[error] 	at com.oracle.svm.jni.JNIJavaCallWrappers.jniInvoke_VA_LIST:Ljava_lang_System_2_0002egetProperty_00028Ljava_lang_String_2_00029Ljava_lang_String_2(generated:0)
[error] 	at com.oracle.svm.core.util.UserError.abort(UserError.java:79)
[error] 	at com.oracle.svm.hosted.FallbackFeature.reportAsFallback(FallbackFeature.java:221)
[error] 	at com.oracle.svm.hosted.NativeImageGenerator.runPointsToAnalysis(NativeImageGenerator.java:741)
[error] 	at com.oracle.svm.hosted.NativeImageGenerator.doRun(NativeImageGenerator.java:530)
[error] 	at com.oracle.svm.hosted.NativeImageGenerator.lambda$run$0(NativeImageGenerator.java:445)
[error] 	at java.base/java.util.concurrent.ForkJoinTask$AdaptedRunnableAction.exec(ForkJoinTask.java:1407)
[error] 	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
[error] 	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
[error] 	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
[error] 	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
[error] 	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:177)
[error] Caused by: com.oracle.graal.pointsto.constraints.UnsupportedFeatureException: com.oracle.svm.hosted.substitute.DeletedElementException: Unsupported method java.lang.ClassLoader.defineClass1(ClassLoader, String, byte[], int, int, ProtectionDomain, String) is reachable
[error] To diagnose the issue, you can add the option --report-unsupported-elements-at-runtime. The unsupported element is then reported at run time when it is accessed the first time.
[error] Detailed message:
[error] Trace:
[error] 	at parsing java.lang.ClassLoader.defineClass(ClassLoader.java:1016)
[error] Call path from entry point to java.lang.ClassLoader.defineClass(String, byte[], int, int, ProtectionDomain):
[error] 	at java.lang.ClassLoader.defineClass(ClassLoader.java:1014)
[error] 	at java.lang.ClassLoader.defineClass(ClassLoader.java:877)
[error] 	at com.oracle.svm.reflect.ClassLoader_defineClass_c6c343b4d6dc22ca64eb2d8503b13ac9c340dcb3_4697.invoke(Unknown Source)
[error] 	at java.lang.reflect.Method.invoke(Method.java:566)
[error] 	at com.oracle.svm.core.hub.DynamicHub.initEnumConstantsAtRuntime(DynamicHub.java:458)
[error] 	at com.oracle.svm.core.hub.DynamicHub.lambda$initEnumConstantsAtRuntime$1(DynamicHub.java:438)
[error] 	at com.oracle.svm.core.hub.DynamicHub$$Lambda$783/0x00000007c212e040.get(Unknown Source)
[error] 	at com.oracle.svm.core.jdk.SystemPropertiesSupport.initializeLazyValue(SystemPropertiesSupport.java:190)
[error] 	at com.oracle.svm.core.jdk.SystemPropertiesSupport.getProperty(SystemPropertiesSupport.java:143)
[error] 	at com.oracle.svm.core.jdk.Target_java_lang_System.getProperty(JavaLangSubstitutions.java:340)
[error] 	at com.oracle.svm.jni.JNIJavaCallWrappers.jniInvoke_VA_LIST:Ljava_lang_System_2_0002egetProperty_00028Ljava_lang_String_2_00029Ljava_lang_String_2(generated:0)
[error] 	at com.oracle.graal.pointsto.constraints.UnsupportedFeatures.report(UnsupportedFeatures.java:126)
[error] 	at com.oracle.svm.hosted.NativeImageGenerator.runPointsToAnalysis(NativeImageGenerator.java:738)
[error] 	... 8 more
[error] Caused by: com.oracle.svm.hosted.substitute.DeletedElementException: Unsupported method java.lang.ClassLoader.defineClass1(ClassLoader, String, byte[], int, int, ProtectionDomain, String) is reachable
[error] To diagnose the issue, you can add the option --report-unsupported-elements-at-runtime. The unsupported element is then reported at run time when it is accessed the first time.
[error] 	at com.oracle.svm.hosted.substitute.AnnotationSubstitutionProcessor.lookup(AnnotationSubstitutionProcessor.java:183)
[error] 	at com.oracle.graal.pointsto.infrastructure.SubstitutionProcessor$ChainedSubstitutionProcessor.lookup(SubstitutionProcessor.java:128)
[error] 	at com.oracle.graal.pointsto.infrastructure.SubstitutionProcessor$ChainedSubstitutionProcessor.lookup(SubstitutionProcessor.java:128)
[error] 	at com.oracle.graal.pointsto.meta.AnalysisUniverse.lookupAllowUnresolved(AnalysisUniverse.java:397)
[error] 	at com.oracle.graal.pointsto.infrastructure.WrappedConstantPool.lookupMethod(WrappedConstantPool.java:116)
[error] 	at jdk.internal.vm.compiler/org.graalvm.compiler.java.BytecodeParser.lookupMethodInPool(BytecodeParser.java:4285)
[error] 	at com.oracle.svm.hosted.phases.SharedGraphBuilderPhase$SharedBytecodeParser.lookupMethodInPool(SharedGraphBuilderPhase.java:107)
[error] 	at jdk.internal.vm.compiler/org.graalvm.compiler.java.BytecodeParser.lookupMethod(BytecodeParser.java:4279)
[error] 	at jdk.internal.vm.compiler/org.graalvm.compiler.java.BytecodeParser.genInvokeStatic(BytecodeParser.java:1656)
[error] 	at jdk.internal.vm.compiler/org.graalvm.compiler.java.BytecodeParser.processBytecode(BytecodeParser.java:5288)
[error] 	at jdk.internal.vm.compiler/org.graalvm.compiler.java.BytecodeParser.iterateBytecodesForBlock(BytecodeParser.java:3397)
[error] 	at jdk.internal.vm.compiler/org.graalvm.compiler.java.BytecodeParser.processBlock(BytecodeParser.java:3204)
[error] 	at jdk.internal.vm.compiler/org.graalvm.compiler.java.BytecodeParser.build(BytecodeParser.java:1085)
[error] 	at jdk.internal.vm.compiler/org.graalvm.compiler.java.BytecodeParser.buildRootMethod(BytecodeParser.java:979)
[error] 	at jdk.internal.vm.compiler/org.graalvm.compiler.java.GraphBuilderPhase$Instance.run(GraphBuilderPhase.java:84)
[error] 	at jdk.internal.vm.compiler/org.graalvm.compiler.phases.Phase.run(Phase.java:49)
[error] 	at jdk.internal.vm.compiler/org.graalvm.compiler.phases.BasePhase.apply(BasePhase.java:197)
[error] 	at jdk.internal.vm.compiler/org.graalvm.compiler.phases.Phase.apply(Phase.java:42)
[error] 	at jdk.internal.vm.compiler/org.graalvm.compiler.phases.Phase.apply(Phase.java:38)
[error] 	at com.oracle.graal.pointsto.flow.MethodTypeFlowBuilder.parse(MethodTypeFlowBuilder.java:221)
[error] 	at com.oracle.graal.pointsto.flow.MethodTypeFlowBuilder.apply(MethodTypeFlowBuilder.java:340)
[error] 	at com.oracle.graal.pointsto.flow.MethodTypeFlow.doParse(MethodTypeFlow.java:310)
[error] 	at com.oracle.graal.pointsto.flow.MethodTypeFlow.ensureParsed(MethodTypeFlow.java:300)
[error] 	at com.oracle.graal.pointsto.flow.MethodTypeFlow.addContext(MethodTypeFlow.java:107)
[error] 	at com.oracle.graal.pointsto.flow.SpecialInvokeTypeFlow.onObservedUpdate(InvokeTypeFlow.java:421)
[error] 	at com.oracle.graal.pointsto.flow.TypeFlow.notifyObservers(TypeFlow.java:344)
[error] 	at com.oracle.graal.pointsto.flow.TypeFlow.update(TypeFlow.java:386)
[error] 	at com.oracle.graal.pointsto.BigBang$2.run(BigBang.java:511)
[error] 	at com.oracle.graal.pointsto.util.CompletionExecutor.lambda$execute$0(CompletionExecutor.java:171)
[error] 	at java.base/java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1426)
[error] 	... 5 more
[error] Error: Image build request failed with exit status 1
[error] com.oracle.svm.driver.NativeImage$NativeImageError: Image build request failed with exit status 1
[error] 	at com.oracle.svm.driver.NativeImage.showError(NativeImage.java:1527)
[error] 	at com.oracle.svm.driver.NativeImage.build(NativeImage.java:1289)
[error] 	at com.oracle.svm.driver.NativeImage.performBuild(NativeImage.java:1250)
[error] 	at com.oracle.svm.driver.NativeImage.main(NativeImage.java:1209)
[error] 	at com.oracle.svm.driver.NativeImage$JDK9Plus.main(NativeImage.java:1707)
```

**Comment by martinformanko** [comment] 2020-04-28 17:10
I have the same problem, in my case it started with adding micronaut dependency.

**Comment by arielcarrera** [comment] 2020-08-21 04:39
Same problem. It is due to some @Delete substitutions:

[jdk8](https://github.com/oracle/graal/blob/717f60177580d0f53f74b119c877b5ba2ada0614/substratevm/src/com.oracle.svm.core/src/com/oracle/svm/core/jdk/Target_java_lang_ClassLoader.java#L359) and [jdk11](https://github.com/oracle/graal/blob/717f60177580d0f53f74b119c877b5ba2ada0614/substratevm/src/com.oracle.svm.core/src/com/oracle/svm/core/jdk/Target_java_lang_ClassLoader.java#L371) at Target_jdk_internal_loader_URLClassPath class.

**Comment by cstancu** [comment] 2020-09-24 03:46
I'll close this in favor of https://github.com/oracle/graal/issues/2369 which has the same stack trace but also includes a reproducible.

**Closed by cstancu** 2020-09-24 03:46 UTC
Labels: bug, native-image
