### ISSUE TITLE
 Instrument calculateContextHeapSize() AssertionError: org.graalvm.polyglot.Value should not be reachable

### ISSUE THREAD

**Issue by matteobertozzi** [oracle/graal#4266] opened 2022-01-27 10:38 UTC
**Describe the issue**
env.calculateContextHeapSize() gives: AssertionError: org.graalvm.polyglot.Value should not be reachable

**Steps to reproduce the issue**
Please include both build steps as well as run steps
1. git clone https://github.com/matteobertozzi/graalvm22-issue.git
2. ./run-instrument-test.sh 

**Describe GraalVM and your environment:**
 - GraalVM Community Edition 22.0.0.2 (vm-22.0.0.2 bd6570e)
 - JDK major version: 17
 - OS: macOS Monterey
 - Architecture: AMD64

**More details**
To reproduce the problem the unit test TestDemoInstrument.java in the repo contains a script running with the instrument attached. (there is a run-instrument-test.sh to build the jar with the instrument and then run the test with -Dtruffle.class.path.append).
The instrument listen for new "contexts" and there is a thread calling calculateHeapSize() on active contexts. in the test there is only one engine/context running.
```
java.lang.AssertionError: org.graalvm.polyglot.Value should not be reachable
	at org.graalvm.truffle/com.oracle.truffle.polyglot.ObjectSizeCalculator.isContextHeapBoundary(ObjectSizeCalculator.java:272)
	at org.graalvm.truffle/com.oracle.truffle.polyglot.ObjectSizeCalculator.canProceed(ObjectSizeCalculator.java:333)
	at org.graalvm.truffle/com.oracle.truffle.polyglot.ObjectSizeCalculator.access$500(ObjectSizeCalculator.java:87)
	at org.graalvm.truffle/com.oracle.truffle.polyglot.ObjectSizeCalculator$ArrayElementsVisitor.visit(ObjectSizeCalculator.java:354)
	at org.graalvm.truffle/com.oracle.truffle.polyglot.ObjectSizeCalculator.visit(ObjectSizeCalculator.java:244)
	at org.graalvm.truffle/com.oracle.truffle.polyglot.ObjectSizeCalculator.calculateObjectSize(ObjectSizeCalculator.java:207)
	at org.graalvm.truffle/com.oracle.truffle.polyglot.PolyglotContextImpl.calculateHeapSize(PolyglotContextImpl.java:1725)
	at org.graalvm.truffle/com.oracle.truffle.polyglot.EngineAccessor$EngineImpl.calculateContextHeapSize(EngineAccessor.java:1395)
	at org.graalvm.truffle/com.oracle.truffle.api.instrumentation.TruffleInstrument$Env.calculateContextHeapSize(TruffleInstrument.java:1091)
	at demo.DemoInstrument$EnvListener.computeHeapSize(DemoInstrument.java:225)
	at demo.DemoInstrument$EnvListener.updateStats(DemoInstrument.java:205)
	at demo.DemoInstrument$Demo.run(DemoInstrument.java:133)
	at java.base/java.lang.Thread.run(Thread.java:833)
```

**Comment by chumer** [comment] 2022-01-27 11:24
@jchalou  can you please take care of this? While you are at it, it would be useful to have some information which field was last read when this error occured. Also, can we check this in the gate please?

**Comment by jchalou** [comment] 2022-02-01 10:51
Cause is known, fix is on the way.

**Comment by jchalou** [comment] 2022-02-04 09:33
The issue is fixed by https://github.com/oracle/graal/commit/3d94e74fdd6b1d51b1fb90db357403dd5bc87cca. Next dev build will include the fix.

**Comment by wirthi** [comment] 2022-10-06 12:44
Should be fixed as reported above. Closing this ticket.

**Closed by wirthi** 2022-10-06 12:44 UTC
Labels: bug
