### ISSUE TITLE
[native-image] Failing with 'type not available on this platform SVMHotSpotGraalRuntimeMBean

### ISSUE THREAD

**Issue by aclement** [oracle/graal#1922] opened 2019-12-03 22:09 UTC
Upgrading springmvc+tomcat app to Graal 19.3 (Java8) on mac mojave:
```
[tc:26773]     analysis:  30,524.44 ms
Fatal error: com.oracle.graal.pointsto.constraints.UnsupportedFeatureException: type is not available in this platform: org.graalvm.compiler.hotspot.management.libgraal.runtime.SVMHotSpotGraalRuntimeMBean
	at com.oracle.graal.pointsto.meta.AnalysisUniverse.createType(AnalysisUniverse.java:214)
	at com.oracle.graal.pointsto.meta.AnalysisUniverse.lookupAllowUnresolved(AnalysisUniverse.java:205)
	at com.oracle.graal.pointsto.meta.AnalysisUniverse.lookup(AnalysisUniverse.java:182)
	at com.oracle.graal.pointsto.meta.AnalysisUniverse.lookup(AnalysisUniverse.java:75)
	at com.oracle.graal.pointsto.infrastructure.UniverseMetaAccess$1.apply(UniverseMetaAccess.java:52)
	at com.oracle.graal.pointsto.infrastructure.UniverseMetaAccess$1.apply(UniverseMetaAccess.java:49)
	at java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1660)
	at com.oracle.graal.pointsto.infrastructure.UniverseMetaAccess.lookupJavaType(UniverseMetaAccess.java:84)
	at com.oracle.graal.pointsto.meta.AnalysisMetaAccess.lookupJavaType(AnalysisMetaAccess.java:47)
	at com.oracle.graal.pointsto.ObjectScanner.doScan(ObjectScanner.java:337)
	at com.oracle.graal.pointsto.ObjectScanner.access$400(ObjectScanner.java:62)
	at com.oracle.graal.pointsto.ObjectScanner$3$1.run(ObjectScanner.java:414)
	at com.oracle.graal.pointsto.util.CompletionExecutor.lambda$execute$0(CompletionExecutor.java:171)
	at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1402)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
Error: Image build request failed with exit status 1
```

Something I am doing wrong?

**Comment by aclement** [comment] 2019-12-04 03:36
Some repro steps (I think):
```
git clone git@github.com:spring-projects-experimental/spring-graal-native.git
git checkout upgrade_19_3
cd spring-graal-native/spring-graal-native-feature
mvn clean package
cd ../spring-graal-native-samples/springmvc-tomcat
./compile.sh
```

**Comment by cstancu** [comment] 2019-12-04 19:15
Duplicate of https://github.com/oracle/graal/issues/1931?

**Comment by tzezula** [comment] 2019-12-09 07:18
The `SVMHotSpotGraalRuntimeMBean` is annotated by `@Platforms(Platform.HOSTED_ONLY.class)` as this class should not be pulled into a native image. It's a Hotspot side of the `GraalRuntimeMBean` which is defined by the `libjvmcicompiler` using JNI. I will take a look how class becomes reachable.

**Comment by tzezula** [comment] 2019-12-10 16:55
I am unable to reproduce the problem.
@aclement, if you are still able to reproduce the problem, can you please attach the analyses call tree, generated by `-H:+PrintAnalysisCallTree` option?
Thanks

**Comment by aclement** [comment] 2019-12-10 20:29
@tzezula hmm, I'm having trouble recreating myself! On graal master (today) everything runs clean, on the steps above with the 19.3 release (java 8) I am hitting:
```
Undefined symbols for architecture x86_64:
  "_Java_sun_misc_Unsafe_defineClass", referenced from:
      ___svm_cglobaldata_base in clr.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

	at com.oracle.svm.hosted.image.NativeBootImageViaCC.write(NativeBootImageViaCC.java:382)
	at com.oracle.svm.hosted.NativeImageGenerator.doRun(NativeImageGenerator.java:652)
```

which seems tied up with issue #1920.

However, as I say, that seems to be gone in master now too - although not sure which commit fixed it.

**Comment by eginez** [comment] 2019-12-10 21:20
This is issue has been fixed in head of master by commit https://github.com/oracle/graal/commit/cfef71c13cab78d5fafeaed20ef0828e83503bc1

**Closed** 2019-12-10 21:20 UTC
