### ISSUE TITLE
how to save llvm IR cache during compiling image by native-image

### ISSUE THREAD

**Issue by AliredDevils** [oracle/graal#1416] opened 2019-06-21 06:39 UTC
Hi,
  I want to get the LLVM IR(bitcode cache) when i use the native-image tool to compile image from java.
 The steps as follow:
(1)create my HelloWorld.java,and compile to "class" file;
(2)modify the "LLVMNativeImageCodeCache.java" file:
   1) open llvm debug info
   2) enable "DumpLLVMStackMap" option feature
   3) save llvm bitcode cache to a local file
(3) `mx build`
(4)`mx native-image HelloWorld`

But i find that:
- native image could be compiled successfully
- could not find the local file which will have the llvm bitcode cache

My question is :how could i get the LLVM bitcode cache ?Should i open some native-image configuration or set some properties?

Thanks

**Comment by dougxc** [comment] 2019-06-21 08:01
@loicottet maybe you could answer this?

**Comment by davidHisense** [comment] 2019-06-24 01:18
Hi @loicottet  can you give some suggestions? Thanks

**Comment by loicottet** [comment] 2019-06-26 15:20
Sorry for the late reply, I somehow missed the Github notifications.

The DumpLLVMStackMap option is probably not the solution you're looking for, as it is simply a debugging tool outputting information about the machine code emitted by LLVM, not the bitcode itself.
The bitcode file is stored in a temporary folder. There's currently no option to get this folder, but you can get it from `LLVMNativeImageCodeCache` (it's the `basePath` field).
The backend now uses parallel compilation so there's not a single bitcode file getting compiled by default. You can use the `-H:LLVMBatchesPerThread=0` option to force a single bitcode file to be created. The file will then be in the temporary folder with the name `b0.bc`.
On the other hand, if you're looking for the code of a single function, you can use `-H:LLVMBatchesPerThread=-1` to compile every function individually. Each function will have its bitcode in a separate file named `f<function-id>.bc` in the temporary folder. To find the `<function-id>` of a method, you can use `-H:DumpLLVMStackMap`. There's a table at the end of the outputted file matching functions to their identifier.

**Comment by davidHisense** [comment] 2019-06-28 09:05
@loicottet   Thanks for the reply.But i also could not get the LLVM IR bitcode follow the last methods.And my steps as bellow:

1. update the graal source code to the newest(master branch)

2.modify the 'svm' source code to get the temporary folder(native-image-llvm)

- force a single bitcode file to be created
diff --git a/substratevm/src/com.oracle.svm.core.graal.llvm/src/com/oracle/svm/core/graal/llvm/LLVMNativeImageCodeCache.java b/substratevm/src/com.oracle.svm.core.graal.llvm/src/com/oracle/svm/core/graal/llvm/LLVMNativeImageCodeCache.java
index dafad65..b17f5d1 100644
--- a/substratevm/src/com.oracle.svm.core.graal.llvm/src/com/oracle/svm/core/graal/llvm/LLVMNativeImageCodeCache.java
+++ b/substratevm/src/com.oracle.svm.core.graal.llvm/src/com/oracle/svm/core/graal/llvm/LLVMNativeImageCodeCache.java
@@ -107,6 +107,9 @@ public class LLVMNativeImageCodeCache extends NativeImageCodeCache {
 
         try {
             basePath = Files.createTempDirectory("native-image-llvm");
             System.out.println("=========================>\n");
             System.out.println("Here to copy and save the tmp file to my own!!!");
             System.out.println("<=========================\n");
             if (LLVMOptions.DumpLLVMStackMap.hasBeenSet()) {
                 stackMapDump = new FileWriter(LLVMOptions.DumpLLVMStackMap.getValue());
             } else {
diff --git a/substratevm/src/com.oracle.svm.core.graal.llvm/src/com/oracle/svm/core/graal/llvm/LLVMOptions.java b/substratevm/src/com.oracle.svm.core.graal.llvm/src/com/oracle/svm/core/graal/llvm/LLVMOptions.java
index 9335f4b..b78f265 100644
--- a/substratevm/src/com.oracle.svm.core.graal.llvm/src/com/oracle/svm/core/graal/llvm/LLVMOptions.java
+++ b/substratevm/src/com.oracle.svm.core.graal.llvm/src/com/oracle/svm/core/graal/llvm/LLVMOptions.java
@@ -31,11 +31,11 @@ import org.graalvm.compiler.options.OptionType;
 public class LLVMOptions {
 
     @Option(help = "Include debugging info in the generated image (for LLVM backend).")//

     public static final HostedOptionKey<Integer> IncludeLLVMDebugInfo = new HostedOptionKey<>(3);
 
     @Option(help = "Dump contents of the generated stackmap to the specified file")/
     public static final HostedOptionKey<String> DumpLLVMStackMap = new HostedOptionKey<>("/home/wenzhuo/svm.txt");
 
     @Option(help = "How many batches per thread should be used for LLVM compilation. 0 means a single batch, -1 means all functions separately", type = OptionType.Expert)//

     public static final HostedOptionKey<Integer> LLVMBatchesPerThread = new HostedOptionKey<>(0);
 }

3. Compile all Java and native code in substratevm:
- build script
`cd substratevm`
`mx build`
- build (java) class
`javac HelloWorld.java`
- build native image
`mx native-image HelloWorld`

4. Check the LLVM IR bitcode
`find ./* -name *.bc`
But i could not find any bitcode file(LLVM IR)?? 

5.Debug the native image generation process 
 It seems that 'mx native-image HelloWorld' tool not invoke the LLVMNativeImageCodeCache class ?

So whether it will invoke svm_llvm or graal_llvm during the native image building? Or could you give some steps details to get the LLVM IR(bitcode) during java class compiling to native image?
Best Regards.

**Comment by loicottet** [comment] 2019-06-28 09:16
Are you setting the `-H:CompilerBackend=llvm` option? If this is not the case Graal will use its standard backend which doesn't use LLVM.

**Comment by davidHisense** [comment] 2019-07-01 08:47
After add the `-H:CompilerBackend=llvm` option for native image building,it fails with error shown.
Running Environment:
- Ubuntu 16.04
- LLVM 6.0.1
- graal community newest version(master)

To reproduce the issue:
-  cd graal/substratevm
- mx build
- mx native-image -H:CompilerBackend=llvm helloworld

Another test method:
- disable llvm version check
- Using llvm-3.8 (9.0.0svn)  version

Error:

> Fatal error: org.graalvm.compiler.graph.GraalGraphError: java.lang.ClassCastException: jdk.vm.ci.code.RegisterValue cannot be cast to org.graalvm.compiler.core.llvm.LLVMUtils$LLVMVariable
at node: 13|WriteCurrentVMThread
at method: IsolateThread com.oracle.svm.core.c.function.CEntryPointBuiltins.createIsolate()  [Direct call from IsolateThread IsolateEnterStub.CEntryPointBuiltins_createIsolate_315bd7239ea2b5ed6515910416de2648c30349ea()]
	at org.graalvm.compiler.core.llvm.NodeLLVMBuilder.doBlock(NodeLLVMBuilder.java:222)
	at org.graalvm.compiler.core.llvm.LLVMGenerationPhase.run(LLVMGenerationPhase.java:38)
	at org.graalvm.compiler.core.llvm.LLVMCompilerBackend.emitLLVM(LLVMCompilerBackend.java:65)
	at org.graalvm.compiler.core.llvm.LLVMCompilerBackend.emitBackEnd(LLVMCompilerBackend.java:42)
	at com.oracle.svm.core.graal.llvm.SubstrateLLVMBackend.emitBackEnd(SubstrateLLVMBackend.java:108)
	at org.graalvm.compiler.core.GraalCompiler.compile(GraalCompiler.java:145)
	at org.graalvm.compiler.core.GraalCompiler.compileGraph(GraalCompiler.java:129)
	at com.oracle.svm.hosted.code.CompileQueue.defaultCompileFunction(CompileQueue.java:955)
	at com.oracle.svm.hosted.code.CompileQueue.doCompile(CompileQueue.java:918)
	at com.oracle.svm.hosted.code.CompileQueue$CompileTask.run(CompileQueue.java:259)
	at com.oracle.graal.pointsto.util.CompletionExecutor.lambda$execute$0(CompletionExecutor.java:171)
	at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1402)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
Caused by: java.lang.ClassCastException: jdk.vm.ci.code.RegisterValue cannot be cast to org.graalvm.compiler.core.llvm.LLVMUtils$LLVMVariable
	at org.graalvm.compiler.core.llvm.LLVMGenerator.emitMove(LLVMGenerator.java:499)
	at com.oracle.svm.core.graal.nodes.WriteCurrentVMThreadNode.generate(WriteCurrentVMThreadNode.java:57)
	at org.graalvm.compiler.core.llvm.NodeLLVMBuilder.emitNode(NodeLLVMBuilder.java:265)
	at org.graalvm.compiler.core.llvm.NodeLLVMBuilder.doRoot(NodeLLVMBuilder.java:255)
	at org.graalvm.compiler.core.llvm.NodeLLVMBuilder.doBlock(NodeLLVMBuilder.java:218)
	... 15 more


> Fatal error: org.graalvm.compiler.graph.GraalGraphError: org.graalvm.compiler.debug.GraalError: should not reach here: unknown operand: r15|i64
	at node: 12|ReadRegisterFloating
	at method: int com.oracle.svm.core.graal.snippets.CEntryPointSnippets.reportException(Throwable)  [Direct call from IsolateThread IsolateEnterStub.CEntryPointBuiltins_attachThread_5e4ff7ed3f8f48e5e8436a4175371632ade676a8(Isolate)]
	at org.graalvm.compiler.graph.GraalGraphError.transformAndAddContext(GraalGraphError.java:136)
	at org.graalvm.compiler.core.llvm.NodeLLVMBuilder.doBlock(NodeLLVMBuilder.java:220)
	at org.graalvm.compiler.core.llvm.LLVMGenerationPhase.run(LLVMGenerationPhase.java:38)
	at org.graalvm.compiler.core.llvm.LLVMCompilerBackend.emitLLVM(LLVMCompilerBackend.java:65)
	at org.graalvm.compiler.core.llvm.LLVMCompilerBackend.emitBackEnd(LLVMCompilerBackend.java:42)
	at com.oracle.svm.core.graal.llvm.SubstrateLLVMBackend.emitBackEnd(SubstrateLLVMBackend.java:108)
	at org.graalvm.compiler.core.GraalCompiler.compile(GraalCompiler.java:145)
	at org.graalvm.compiler.core.GraalCompiler.compileGraph(GraalCompiler.java:129)
	at com.oracle.svm.hosted.code.CompileQueue.defaultCompileFunction(CompileQueue.java:955)
	at com.oracle.svm.hosted.code.CompileQueue.doCompile(CompileQueue.java:918)
	at com.oracle.svm.hosted.code.CompileQueue$CompileTask.run(CompileQueue.java:259)
	at com.oracle.graal.pointsto.util.CompletionExecutor.lambda$execute$0(CompletionExecutor.java:171)
	at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1402)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
Caused by: org.graalvm.compiler.debug.GraalError: should not reach here: unknown operand: r15|i64
	at org.graalvm.compiler.debug.GraalError.shouldNotReachHere(GraalError.java:51)
	at org.graalvm.compiler.core.llvm.NodeLLVMBuilder.setResult(NodeLLVMBuilder.java:591)
	at com.oracle.svm.core.graal.nodes.ReadRegisterFloatingNode.generate(ReadRegisterFloatingNode.java:80)
	at org.graalvm.compiler.core.llvm.NodeLLVMBuilder.emitNode(NodeLLVMBuilder.java:265)
	at org.graalvm.compiler.core.llvm.NodeLLVMBuilder.doRoot(NodeLLVMBuilder.java:255)
	at org.graalvm.compiler.core.llvm.NodeLLVMBuilder.doBlock(NodeLLVMBuilder.java:218)
	... 15 more

Would the llvm-CompilerBackend be another standard backend ? Or it only could be a test or debug method?

**Comment by loicottet** [comment] 2019-07-01 08:49
The LLVM backend currently doesn't support isolates and multithreading, adding `-H:-SpawnIsolates` and `-H:-MultiThreading` should solve this.

**Comment by dougxc** [comment] 2019-07-01 09:06
@loicottet is it possible to detect these incompatibilities during native-image startup so we can either emit a clearer and more actionable error message or automatically make the configuration change (with a warning message) that you're suggesting?

**Comment by loicottet** [comment] 2019-07-01 09:20
https://github.com/oracle/graal/pull/1456, multithreading support should be merged soon

**Comment by davidHisense** [comment] 2019-07-01 11:04
@loicottet 
I update the source codes,but could not find `MultiThreading` option, whether you have merge the solution or not? Can you give the commit ID ?
thanks

**Comment by loicottet** [comment] 2019-07-01 12:06
Whoops, the option is `-H:-MultiThreaded`, sorry for the typo.

**Comment by AliredDevils** [comment] 2019-07-01 12:12
@loicottet 
The solution mis-understand for me:

- Need to  `
Install mx and point JAVA_HOME to a JVMCI-enabled JDK 8.`

- But only `JavaVersionUtil.JAVA_SPEC > 8` could support the `-H:-SpawnIsolates` and `-H:-MultiThreading` options

The source code:

- substratevm/src/com.oracle.svm.core/src/com/oracle/svm/core/SubstrateOptions.java 

`

     if ("llvm".equals(newValue) && JavaVersionUtil.JAVA_SPEC > 8) {
                EmitStringEncodingSubstitutions.update(values, false);
                if ((Boolean) values.get(SpawnIsolates)) {
                    System.out.println("Isolates are currently not supported by the LLVM backend. The build will continue with isolates disabled.");
                   SpawnIsolates.update(values, false);
                }
                if ((Boolean) values.get(MultiThreaded)) {
                    System.out.println("Multithreading is currently not supported by the LLVM backend. The build will continue with multithreading disabled.");
                    MultiThreaded.update(values, false);
                }
      }

`

It means if i use the JVMCI-enabled JDK 8 version,the options `-H:-SpawnIsolates` and `-H:-MultiThreading` will do nothing.

**Comment by loicottet** [comment] 2019-07-01 12:19
This code doesn't make sense indeed. I've updated the PR, it should work now. Otherwise you can simply manually set `-H:-MultiThreaded -H:-SpawnIsolates` when invoking `mx native-image`

**Comment by AliredDevils** [comment] 2019-07-02 03:21
Yeap， i  have got the LLVM bitcode.Thank you very much.

There are still questions for me:

- Whether the llvm backend compiler method only aims to be compatatible with LLVM?

- Can not run the `b0.bc` by `lli` command tool.( `-H:LLVMBatchesPerThread=0`)

- Should the llvm-backend be a standard backend in the future ?

**Comment by loicottet** [comment] 2019-07-02 13:10
> Whether the llvm backend compiler method only aims to be compatatible with LLVM?

I'm not sure I fully understand what you mean by that. The LLVM backend uses LLVM as a replacement for the original GraalVM backend.

> Can not run the b0.bc by lli command tool.( -H:LLVMBatchesPerThread=0)

The bitcode file emitted currently only contains the code of the program, and the data is linked into the object file afterwards, so `b0.bc` is not interpretable as is. It's on my long-term to-do list to integrate the code and data into a single LLVM file, but this requires quite a bit of work.

> Should the llvm-backend be a standard backend in the future ?

On x86_64, the LLVM backend was meant as a side backend to work alongside, and potentially complement, the original backend. Now the LLVM backend makes it easier to target new architectures so it may be the primary backend for some architectures in the future.

**Comment by AliredDevils** [comment] 2019-07-04 10:23
Thanks.
If the file format such as bellow:
- `b0.bc` : contains the code of program ?

- `b0.o`: contains the data ?

1. `llc -filetype=obj b0.bc` : compares the origin and the new one,there are many differences between them.This is all right?
2. How could i compile the executable file by the generated '.bc'  and '.o' files in the  temporary folder?
    - I have tested that: `clang llvm.o`,but it got errors:

> (.text+0xb5c82): undefined reference to `constant_EconomicMapImpl_setValue_e5d2bf5a610c5981bb9ed05ff8672560d297ab86#1'
llvm.o: In function `EconomicMapImpl__toString__e96f83c6e45ef0372c9aef3d19300c9bbe398e4d':
(.text+0xb5dbe): undefined reference to `constant_EconomicMapImpl_toString_e96f83c6e45ef0372c9aef3d19300c9bbe398e4d#0'
llvm.o: In function `EconomicMapImpl__toString__e96f83c6e45ef0372c9aef3d19300c9bbe398e4d':
(.text+0xb5dd8): undefined reference to `constant_EconomicMapImpl_toString_e96f83c6e45ef0372c9aef3d19300c9bbe398e4d#1'
llvm.o: In function `EconomicMapImpl__toString__e96f83c6e45ef0372c9aef3d19300c9bbe398e4d':
(.text+0xb5de1): undefined reference to `constant_EconomicMapImpl_toString_e96f83c6e45ef0372c9aef3d19300c9bbe398e4d#2'
llvm.o: In function `EconomicMapImpl__toString__e96f83c6e45ef0372c9aef3d19300c9bbe398e4d':
(.text+0xb5e0b): undefined reference to `constant_EconomicMapImpl_toString_e96f83c6e45ef0372c9aef3d19300c9bbe398e4d#3'
llvm.o: In function `EconomicMapImpl__toString__e96f83c6e45ef0372c9aef3d19300c9bbe398e4d':
(.text+0xb5e5c): undefined reference to `constant_EconomicMapImpl_toString_e96f83c6e45ef0372c9aef3d19300c9bbe398e4d#4'
llvm.o: In function `EconomicMapImpl__toString__e96f83c6e45ef0372c9aef3d19300c9bbe398e4d':
(.text+0xb5f23): undefined reference to `constant_EconomicMapImpl_toString_e96f83c6e45ef0372c9aef3d19300c9bbe398e4d#5'
llvm.o: In function `EconomicMapImpl__toString__e96f83c6e45ef0372c9aef3d19300c9bbe398e4d':
(.text+0xb5f5a): undefined reference to `constant_EconomicMapImpl_toString_e96f83c6e45ef0372c9aef3d19300c9bbe398e4d#6'
llvm.o: In function `EconomicMapImpl__toString__e96f83c6e45ef0372c9aef3d19300c9bbe398e4d':
(.text+0xb5fa0): undefined reference to `constant_EconomicMapImpl_toString_e96f83c6e45ef0372c9aef3d19300c9bbe398e4d#7'
llvm.o: In function `EconomicMapImpl__toString__e96f83c6e45ef0372c9aef3d19300c9bbe398e4d':
(.text+0xb5fdd): undefined reference to `constant_EconomicMapImpl_toString_e96f83c6e45ef0372c9aef3d19300c9bbe398e4d#8'
llvm.o: In function `EconomicMapImpl__toString__e96f83c6e45ef0372c9aef3d19300c9bbe398e4d':
(.text+0xb5fe7): undefined reference to `constant_EconomicMapImpl_toString_e96f83c6e45ef0372c9aef3d19300c9bbe398e4d#9'
llvm.o: In function `EconomicMapImpl__toString__e96f83c6e45ef0372c9aef3d19300c9bbe398e4d':
(.text+0xb5ff1): undefined reference to `constant_EconomicMapImpl_toString_e96f83c6e45ef0372c9aef3d19300c9bbe398e4d#10'
llvm.o: In function `EconomicMapImpl__toString__e96f83c6e45ef0372c9aef3d19300c9bbe398e4d':
(.text+0xb62aa): undefined reference to `constant_EconomicMapImpl_toString_e96f83c6e45ef0372c9aef3d19300c9bbe398e4d#11'
llvm.o: In function `EconomicMapImpl__toString__e96f83c6e45ef0372c9aef3d19300c9bbe398e4d':
(.text+0xb62e9): undefined reference to `constant_EconomicMapImpl_toString_e96f83c6e45ef0372c9aef3d19300c9bbe398e4d#12'
llvm.o: In function `CompressEncoding_equals_ca0f07bff0c43227dc5448144be26bc68597667b':
(.text+0xb64e7): undefined reference to `constant_CompressEncoding_equals_ca0f07bff0c43227dc5448144be26bc68597667b#0'
clang-6.0: error: linker command failed with exit code 1 (use -v to see invocation)

 - `clang b0.o`, it got errors too:

> b0.o: In function `EconomicMapImpl__setHashArray__4f029254d2bf31ccf205f8ca8645fdd2f5b2d1a3':
llvm-link:(.text+0x94897): undefined reference to `constant_EconomicMapImpl_setHashArray_4f029254d2bf31ccf205f8ca8645fdd2f5b2d1a3#0'
b0.o: In function `EconomicMapImpl__setValue__e5d2bf5a610c5981bb9ed05ff8672560d297ab86':
llvm-link:(.text+0x949b1): undefined reference to `constant_EconomicMapImpl_setValue_e5d2bf5a610c5981bb9ed05ff8672560d297ab86#0'
llvm-link:(.text+0x94a08): undefined reference to `constant_EconomicMapImpl_setValue_e5d2bf5a610c5981bb9ed05ff8672560d297ab86#0'
llvm-link:(.text+0x94a2c): undefined reference to `constant_EconomicMapImpl_setValue_e5d2bf5a610c5981bb9ed05ff8672560d297ab86#1'
b0.o: In function `EconomicMapImpl__toString__e96f83c6e45ef0372c9aef3d19300c9bbe398e4d':
llvm-link:(.text+0x94b47): undefined reference to `constant_EconomicMapImpl_toString_e96f83c6e45ef0372c9aef3d19300c9bbe398e4d#0'
llvm-link:(.text+0x94b5f): undefined reference to `constant_EconomicMapImpl_toString_e96f83c6e45ef0372c9aef3d19300c9bbe398e4d#1'
llvm-link:(.text+0x94b68): undefined reference to `constant_EconomicMapImpl_toString_e96f83c6e45ef0372c9aef3d19300c9bbe398e4d#2'
llvm-link:(.text+0x94b6f): undefined reference to `constant_EconomicMapImpl_toString_e96f83c6e45ef0372c9aef3d19300c9bbe398e4d#0'
llvm-link:(.text+0x94b93): undefined reference to `constant_EconomicMapImpl_toString_e96f83c6e45ef0372c9aef3d19300c9bbe398e4d#3'
llvm-link:(.text+0x94bc5): undefined reference to `constant_EconomicMapImpl_toString_e96f83c6e45ef0372c9aef3d19300c9bbe398e4d#0'
llvm-link:(.text+0x94be9): undefined reference to `constant_EconomicMapImpl_toString_e96f83c6e45ef0372c9aef3d19300c9bbe398e4d#4'
llvm-link:(.text+0x94c69): undefined reference to `constant_EconomicMapImpl_toString_e96f83c6e45ef0372c9aef3d19300c9bbe398e4d#5'
llvm-link:(.text+0x94c78): undefined reference to `constant_EconomicMapImpl_toString_e96f83c6e45ef0372c9aef3d19300c9bbe398e4d#0'
llvm-link:(.text+0x94c9c): undefined reference to `constant_EconomicMapImpl_toString_e96f83c6e45ef0372c9aef3d19300c9bbe398e4d#6'
llvm-link:(.text+0x94ce9): undefined reference to `constant_EconomicMapImpl_toString_e96f83c6e45ef0372c9aef3d19300c9bbe398e4d#7'
llvm-link:(.text+0x94d0b): undefined reference to `constant_EconomicMapImpl_toString_e96f83c6e45ef0372c9aef3d19300c9bbe398e4d#8'
llvm-link:(.text+0x94d12): undefined reference to `constant_EconomicMapImpl_toString_e96f83c6e45ef0372c9aef3d19300c9bbe398e4d#9'
llvm-link:(.text+0x94d1d): undefined reference to `constant_EconomicMapImpl_toString_e96f83c6e45ef0372c9aef3d19300c9bbe398e4d#10'
llvm-link:(.text+0x94f7b): undefined reference to `constant_EconomicMapImpl_toString_e96f83c6e45ef0372c9aef3d19300c9bbe398e4d#11'
llvm-link:(.text+0x94f8a): undefined reference to `constant_EconomicMapImpl_toString_e96f83c6e45ef0372c9aef3d19300c9bbe398e4d#0'
llvm-link:(.text+0x94faa): undefined reference to `constant_EconomicMapImpl_toString_e96f83c6e45ef0372c9aef3d19300c9bbe398e4d#12'
b0.o: In function `CompressEncoding__equals__ca0f07bff0c43227dc5448144be26bc68597667b':
llvm-link:(.text+0x95040): undefined reference to `constant_CompressEncoding_equals_ca0f07bff0c43227dc5448144be26bc68597667b#0'
clang-6.0: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by loicottet** [comment] 2019-07-04 12:50
`b0.bc` contains LLVM bitcode corresponding to part of the code of the program, while `b0.o` is the machine code obtained from compiling this bitcode. Then all these object files are linked into a single `llvm.o` file, which holds the code for the whole program.
The data of the program is contained in another object file, named like the final executable (e.g. helloworld.o), that is generated separately and stored in a different temporary folder.
Those two object files are finally linked together to give the final executable. This happens during the native-image building process, there’s no need to do it manually.

**Comment by AliredDevils** [comment] 2019-07-24 12:28
@loicottet 
For the llvm comipler,can you give some instructions about how to split the program code into code->code and code->data ?The program will contains：
-  Code section 
- RO-data section
- RW-data section 
-  ZI-data section
So,the code section will be compiled to bitcode and generated the `llvm.o` file,the other data section would be compiled to data object file(e.g `helloworld.o`)?
Another question is that whether the code->code and code->data be generated from the LIR(graal IR) files.So the native image generating steps as follows, correct or not?
java class(or jar file) -> LIR(graal IR) -> llvm bitcode(b0.o) and data object file -> native image

At last, i want to enhance the native image security by obfuscating the llvm bitcode.

**Comment by loicottet** [comment] 2019-07-25 06:21
This is correct. I'll add that the data sections are filled with both values defined in the code as well as some other Graal-specific data that the program needs to run, and that is not explicitly modeled by the Graal IR.

**Comment by AliredDevils** [comment] 2019-07-31 03:41
@loicottet 
I check the binary file which compiled by llvm-backend compiler,and it seems that `local symbols` could not be removed.

Further testing for `local symbols`,i use the `-s` insteading of `-Wl,-x` to compile again, and the result binary file generated successfully without local symbols.

Does the `-Wl,-x` compiling option not work for the llvm-backend compiler?

**Comment by loicottet** [comment] 2019-07-31 08:44
Does using the `-H:+DeleteLocalSymbols` option of `native-image` remove the local symbols from the final binary? This should set `-Wl,-x` at the right place.

**Comment by AliredDevils** [comment] 2019-07-31 10:01
> Does using the `-H:+DeleteLocalSymbols` option of `native-image` remove the local symbols from the final binary? This should set `-Wl,-x` at the right place.

The `DeleteLocalSymbols` option has been enabled by default as bellow:

    src/com.oracle.svm.core/src/com/oracle/svm/core/SubstrateOptions.java:325:    public static final HostedOptionKey<Boolean> DeleteLocalSymbols = new HostedOptionKey<>(true);

**Comment by loicottet** [comment] 2019-08-02 10:23
What exactly are the symbols you're trying to delete, and in which file?

**Closed** 2022-04-05 13:30 UTC
Labels: native-image
