### ISSUE TITLE
Native Image doesn't work on Windows 10 since graalvm-ce-java11-windows-amd64-20.3.1

### ISSUE THREAD

**Issue by kwang1** [oracle/graal#3140] opened 2021-01-21 04:47 UTC
**Describe the issue**

graalvm-ce-java11-windows-amd64-20.2.0 works fine on my Windows 10, but since graalvm-ce-java11-windows-amd64-20.3.1, I got following exception. I also tried graalvm-ce-java11-21.0.0, it has the same problem.

**Steps to reproduce the issue**
Please include both build steps as well as run steps
1. create a empty micronaut project with micronaut cli `mn create-app com.example.app`, micronaut version is 2.2.3.
2. run `gradlew assemble`
3. run `native-image -jar "<full-path-to-jar>/app-0.1-all.jar`

**Describe GraalVM and your environment:**
 - GraalVM version **graalvm-ce-java11-windows-amd64-20.3.1**
 - JDK major version: **JDK 11**
 - OS: **Windows**
 - Architecture: **[AMD64]**

**More details**
```
   G:\MyStuff\My Projects\trade-recorder>native-image -jar build/libs/trade-recorder-0.1-all.jar -H:+ReportExceptionStackTraces
[trade-recorder-0.1-all:10300]    classlist:   1,594.24 ms,  0.94 GB
[trade-recorder-0.1-all:10300]        setup:     288.41 ms,  0.94 GB
Error: Incompatible change of initialization policy for com.sun.jndi.dns.DnsClient: trying to change RUN_TIME from the command line to RERUN Contains Random references, therefore can't be included in the image heap.
com.oracle.svm.core.util.UserError$UserException: Incompatible change of initialization policy for com.sun.jndi.dns.DnsClient: trying to change RUN_TIME from the command line to RERUN Contains Random references, therefore can't be included in the image heap.
        at com.oracle.svm.core.util.UserError.abort(UserError.java:68)
        at com.oracle.svm.hosted.classinitialization.ClassInitializationConfiguration.insertRec(ClassInitializationConfiguration.java:99)
        at com.oracle.svm.hosted.classinitialization.ClassInitializationConfiguration.insertRec(ClassInitializationConfiguration.java:113)
        at com.oracle.svm.hosted.classinitialization.ClassInitializationConfiguration.insertRec(ClassInitializationConfiguration.java:113)
        at com.oracle.svm.hosted.classinitialization.ClassInitializationConfiguration.insertRec(ClassInitializationConfiguration.java:113)
        at com.oracle.svm.hosted.classinitialization.ClassInitializationConfiguration.insertRec(ClassInitializationConfiguration.java:113)
        at com.oracle.svm.hosted.classinitialization.ClassInitializationConfiguration.insertRec(ClassInitializationConfiguration.java:113)
        at com.oracle.svm.hosted.classinitialization.ClassInitializationConfiguration.insert(ClassInitializationConfiguration.java:64)
        at com.oracle.svm.hosted.classinitialization.ConfigurableClassInitialization.rerunInitialization(ConfigurableClassInitialization.java:253)
        at com.oracle.svm.hosted.jdk.JDKInitializationFeature.afterRegistration(JDKInitializationFeature.java:123)
        at com.oracle.svm.hosted.NativeImageGenerator.lambda$setupNativeImage$11(NativeImageGenerator.java:839)
        at com.oracle.svm.hosted.FeatureHandler.forEachFeature(FeatureHandler.java:70)
        at com.oracle.svm.hosted.NativeImageGenerator.setupNativeImage(NativeImageGenerator.java:839)
        at com.oracle.svm.hosted.NativeImageGenerator.doRun(NativeImageGenerator.java:554)
        at com.oracle.svm.hosted.NativeImageGenerator.lambda$run$0(NativeImageGenerator.java:469)
        at java.base/java.util.concurrent.ForkJoinTask$AdaptedRunnableAction.exec(ForkJoinTask.java:1407)
        at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
        at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
        at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
        at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
        at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
Error: Image build request failed with exit status 1
```

**Comment by minhdtb** [comment] 2021-01-22 03:13
Same error today

**Comment by kkriske** [comment] 2021-01-22 11:15
Are you by any chance compiling a micronaut app? If so it should be fixed by using the upcomming 2.3.0 release that may come out any moment.
I had the same exact issue because `com.sun.jndi.dns.DnsClient` is marked for runtime initialization in a config file (in my case, provided by micronaut). Some config somewhere will probably have done the same for you.

**Comment by mcraj017** [comment] 2021-01-25 07:28
@kwang1 Thanks for reporting the issue
please provide the reproducer

**Comment by krisfoster** [comment] 2021-01-27 20:29
I had the same issue. Seems to be resolved by updating micronaut and then updating the version of the micronaut libs in the  gradle.properties & the build.gradle files. This has worked for me so far - though I am thinking I should double check this

**Comment by kwang1** [comment] 2021-02-01 05:53
> Are you by any chance compiling a micronaut app? If so it should be fixed by using the upcomming 2.3.0 release that may come out any moment.
> I had the same exact issue because `com.sun.jndi.dns.DnsClient` is marked for runtime initialization in a config file (in my case, provided by micronaut). Some config somewhere will probably have done the same for you.
> 
> Fix is to remove the config entry.

Yes, @kkriske. I did run 'native-image' on the jar generated by micronaut. After I upgrade micronaut to 2.3.0, no exceptions at all.
Thanks a lot.

**Comment by kwang1** [comment] 2021-02-01 06:01
> @kwang1 Thanks for reporting the issue
> please provide the reproducer

Hi @mcraj017 , do you mean how to test? I just added those steps.
Would this be an issue of Micronuat or Native image?

Thanks

**Comment by mcraj017** [comment] 2021-02-01 10:23
@kwang1 Its a micronaut issue, if upgrading micronaut solves the issue
do you still need any help?

**Comment by mcraj017** [comment] 2021-03-19 06:26
@kwang1 closing this issue as there is no response from user from last 1 month

**Closed by mcraj017** 2021-03-19 06:26 UTC
Labels: bug, native-image
