### ISSUE TITLE
Possible formatting directive from Object.toString() not escaped

### ISSUE THREAD

**Issue by ryanhall07** [oracle/graal#2715] opened 2020-07-27 21:31 UTC
**Describe the issue**
```
Caused by: java.util.UnknownFormatConversionException: Conversion = 'l'
	at java.util.Formatter$FormatSpecifier.conversion(Formatter.java:2691)
	at java.util.Formatter$FormatSpecifier.<init>(Formatter.java:2720)
	at java.util.Formatter.parse(Formatter.java:2560)
	at java.util.Formatter.format(Formatter.java:2501)
	at java.util.Formatter.format(Formatter.java:2455)
	at java.lang.String.format(String.java:2940)
	at com.oracle.svm.core.util.UserError.abort(UserError.java:68)
```

After attaching the debugger I was able to grab the string format causing the error.

```
Image heap writing found an object whose class was not seen as instantiated during static analysis. Did a static field or an object referenced from a static field change during native image generation? For example, a lazily initialized cache could have been initialized during image generation, in which case you need to force eager initialization of the cache before static analysis or reset the cache using a field value recomputation.
  object: ch.qos.logback.classic.pattern.DateConverter@614231e5 of class: ch.qos.logback.classic.pattern.DateConverter
  reachable through:
    object: PatternLayout("%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n")  of class: PatternLayout
```

`PatternLayout` from logback contains the pattern in the `toString()` impl. https://github.com/qos-ch/logback/blob/4dd08e68321548cd85251ec389f5a832505e1268/logback-core/src/main/java/ch/qos/logback/core/pattern/PatternLayoutBase.java#L129

**Comment by jramirez-isc** [comment] 2020-08-10 21:13
Hi @ryanhall07 
Do you have a reproducer for this issue?

We have a small example using logback to produce logs in native-image using latest GraalVM CE but couldn't reproduce the issue.

**Comment by ryanhall07** [comment] 2020-08-10 21:21
I was able to reproduce the issue with a `PatternLayout` using the pattern `"%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"`

```
val layout = PatternLayout()
layout.pattern = "%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"
layout.start()
val encoder = LayoutWrappingEncoder<ILoggingEvent>()
encoder.layout = layout
encoder.start()
val appender = ConsoleAppender<ILoggingEvent>()
appender.encoder = encoder
appender.start()
logger.addAppender(appender)
```

**Comment by jramirez-isc** [comment] 2020-08-11 15:33
@ryanhall07 I'm using this Java class with the pattern "%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"

```
import ch.qos.logback.classic.LoggerContext;
import org.slf4j.LoggerFactory;
import ch.qos.logback.classic.Logger;
import ch.qos.logback.classic.PatternLayout;
import ch.qos.logback.classic.spi.ILoggingEvent;
import ch.qos.logback.core.ConsoleAppender;
import ch.qos.logback.core.encoder.LayoutWrappingEncoder;
public class App {
    public static void main( String[] args ) {
        Logger rootLogger = (Logger)LoggerFactory.getLogger(Logger.ROOT_LOGGER_NAME);
        LoggerContext loggerContext = rootLogger.getLoggerContext();
        // we are not interested in auto-configuration
        loggerContext.reset();
        PatternLayout layout = new PatternLayout();
        layout.setPattern("%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n");
        layout.setContext(loggerContext);
        layout.start();
        LayoutWrappingEncoder<ILoggingEvent> encoder = new LayoutWrappingEncoder<>();
        encoder.setLayout(layout);
        encoder.setContext(loggerContext);
        encoder.start();
        ConsoleAppender<ILoggingEvent> appender = new ConsoleAppender<>();
        appender.setEncoder(encoder);
        appender.setContext(loggerContext);
        appender.start();
        rootLogger.addAppender(appender);
        for(int i=0; i < 7; i++) {
            rootLogger.info("Example log from {}", App.class.getSimpleName());
            try {
		        Thread.sleep(2000);
	        } catch (Exception e) {
	        }
        }
    }
}
```
This works on GraalVM 20.0.0, 20.1.0 and 20.1.1. Have you tried with one of those versions?

Also, make sure to use the [native-image-agent](https://github.com/oracle/graal/blob/master/substratevm/CONFIGURE.md#assisted-configuration-of-native-image-builds) to generate the reflect config.

**Comment by oubidar-Abderrahim** [comment] 2020-08-25 08:44
I will close this issue as unreproducible. If you still think this should be open, please re-open it and provide a reproducer for this issue.

**Closed** 2020-08-25 08:45 UTC
Labels: bug, native-image
