### ISSUE TITLE
native-image 20.2.0: Scala application does not run anymore

### ISSUE THREAD

**Issue by informarte** [oracle/graal#2928] opened 2020-10-18 16:53 UTC
**Description of the issue**

Compiling a Scala application with native-image 20.2.0 results in a non-working binary. Interestingly, compiling the same code with native-image 20.1.0 results in a working binary.

**Environment**

- GraalVM version: CE 20.2.0
- JDK major version: 11
- OS: Linux 5.4.0 (Ubuntu 20.04)
- Architecture: x86_64

**Steps to reproduce the issue**

```
git clone https://github.com/informarte/yuck.git
cd yuck
git checkout native-image-20.2.0-compilation-issue
make -f Makefile.native native-image
./out/yuck/native-image/yuck
```
Expected outcome and what compilation with native-image 20.1.0 will give you:
```
Error: Missing argument FlatZinc file
Try --help for more information.
```
Output of binary compiled with native-image 20.2.0:
```
Exception in thread "main" com.oracle.svm.core.jdk.UnsupportedFeatureError: Invoke with MethodHandle argument could not be reduced to at most a single call or single field access. The method handle must be a compile time constant, e.g., be loaded from a `static final` field. Method that contains the method handle invocation: java.lang.invoke.LambdaForm$MH/249588653.invoke_MT(Object, Object)
	at com.oracle.svm.core.util.VMError.unsupportedFeature(VMError.java:86)
	at scala.runtime.Statics.releaseFence(Statics.java:148)
	at scala.collection.immutable.$colon$colon.<init>(List.scala:623)
	at scala.collection.immutable.List.prependedAll(List.scala:153)
	at scala.collection.immutable.List$.from(List.scala:651)
	at scala.collection.immutable.List$.from(List.scala:648)
	at scala.collection.IterableFactory.apply(Factory.scala:103)
	at scala.collection.IterableFactory.apply$(Factory.scala:103)
	at scala.collection.immutable.List$.apply(List.scala:648)
	at yuck.flatzinc.FlatZincSolverConfiguration$.apply$default$16(FlatZincSolverConfiguration.scala:37)
	at yuck.flatzinc.runner.FlatZincRunner$CommandLine$.apply$default$4(FlatZincRunner.scala:29)
	at yuck.flatzinc.runner.FlatZincRunner$CommandLineParser.<init>(FlatZincRunner.scala:38)
	at yuck.flatzinc.runner.FlatZincRunner$.main(FlatZincRunner.scala:97)
	at yuck.flatzinc.runner.FlatZincRunner.main(FlatZincRunner.scala)
```

**Comment by informarte** [comment] 2020-10-18 17:27
I double-checked with GraalVM CE 20.3.0-dev-20201017_0226 and ran into the same issue.

**Comment by oubidar-Abderrahim** [comment] 2020-10-19 10:15
I couldn't reproduce the issue because of this error when running the make `command`:
```
/bin/sh: 1: mill: not found
mkdir -p out/yuck/native-image
native-image \
    --no-fallback -H:+TraceClassInitialization -Djava.util.logging.manager=yuck.util.logging.ManagedLogManager --initialize-at-build-time=scala.runtime.Statics\$VM --report-unsupported-elements-at-runtime --no-server \
    --class-path  \
    -H:Name=out/yuck/native-image/yuck \
    -H:ReflectionConfigurationFiles=src/graalvm/reflect-config.json \
    yuck.flatzinc.runner.FlatZincRunner
[yuck.flatzinc.runner.flatzincrunner:17842]    classlist:   3,415.46 ms,  0.96 GB
Error: Main entry point class 'yuck.flatzinc.runner.FlatZincRunner' not found.
Error: Use -H:+ReportExceptionStackTraces to print stacktrace of underlying exception
Error: Image build request failed with exit status 1
Makefile.native:14: recipe for target 'out/yuck/native-image/yuck' failed
make: *** [out/yuck/native-image/yuck] Error 1
```
Is there something missing?

**Comment by informarte** [comment] 2020-10-19 11:20
I am sorry, this was a bug in the Makefile.
Please pull and try again.

**Comment by oubidar-Abderrahim** [comment] 2020-10-19 13:06
I see that you're using `-H:ReflectionConfigurationFiles=src/graalvm/reflect-config.json`, did you generated this file with the agent or manually? did you try re-generating the config files using the agent with 20.2.0?

**Comment by informarte** [comment] 2020-10-19 14:44
`reflect-config.json` was created manually.
Since the binary produced by native-image 2.1.0 works fine, I think that the Reflection configuration is complete.

**Comment by informarte** [comment] 2020-10-19 15:02
I tried the agent; it suggested to extend my `reflect-config.json` with:

```
[
{
  "name":"java.lang.invoke.VarHandle"
},
{
  "name":"yuck.core.BooleanValue[]"
},
{
  "name":"yuck.core.IntegerValue[]"
}
]
```

Extending the configuration did not help, however: The resulting binary throws as reported above.

**Comment by gergo-** [comment] 2020-10-20 13:35
For reference, when working on Yuck's `native-image-performance-issue` branch for #2542 , I also had trouble building the newest version of that branch with GraalVM 20.2. It also failed with the same `MethodHandle` error message.
There the problem was with this commit: https://github.com/informarte/yuck/commit/c62d0cd45c3208e9c8557551a3e9cf36bb506914, the one before it worked. However, I don't see a direct correspondence of that code with code on the `native-image-20.2.0-compilation-issue` branch.

It would be good to see if this can be bisected to a smallish Yuck commit that first shows the problem, but if I understand correctly, the build system was recently swapped out, so this would be tedious.

**Comment by oubidar-Abderrahim** [comment] 2020-10-20 14:42
An internal ticket was created to investigate and fix this issue (GR-26843)

**Comment by informarte** [comment] 2020-10-20 15:34
Don't get confused by the `native-image-performance-issue` branch, it's an old branch. The `native-image-20.2.0-compilation-issue` branch is based on my latest release and, yes, the build system has been swapped out. The code in informarte/yuck@c62d0cd was added at some point to obtain a working binary but later removed because it was not necessary any more. (I can't remember the details, though.) Anyway, the code and build configuration on `native-image-20.2.0-compilation-issue` yields a working binary with 20.1.0 but not with 20.2.0. So either there is a regression in native-image or the build configuration needs massaging. It might make sense to binary search the dev releases between 20.1.0 and 20.2.0 to find the issue.

**Comment by swwins** [comment] 2020-10-28 20:32
I was using GraalVM with a simple scalafx/scala program and when executing the native-image command, it worked great with
the graalvm-ce-java11-20.1.0 version. But it would not work with the graalvm-ce-java11-20.2.0 version. So I compared files and
noticed that the newer version was missing two files in it's bin directory. They are: native-image and rebuild-images. Those two
files are in the graalvm-ce-java11-20.1.0 version. I hope I am understanding all this correctly.

**Comment by oubidar-Abderrahim** [comment] 2021-02-22 09:57
Could you please verify if the issue is still reproducible using the latest GraalVM 21.0.0.2?

**Comment by usommerl** [comment] 2021-02-25 16:20
@oubidar-Abderrahim I had the same issue in a different scala application (See usommerl/graalnative4s#16). In my case, the issue was not reproducible with GraalVM 21.0.0.2.

**Comment by oubidar-Abderrahim** [comment] 2021-03-01 12:03
Thank you @usommerl, I checked [usommerl/graalnative4s#16](https://github.com/usommerl/graalnative4s/issues/16). 20.3.x is LTS so if there is a bug in a prior version it will be fixed in that branch.

The latest 20.3.x currently is 20.3.1.2, please try this version and see if you can reproduce this issue.

**Comment by usommerl** [comment] 2021-03-01 20:13
@oubidar-Abderrahim Thanks! I didn't know that 20.3 is an LTS release. I have run the tracing agent again and build an image with 20.3.1.2. Unfortunately, the issue is still reproducible with this version.

**Comment by oubidar-Abderrahim** [comment] 2021-03-02 10:35
@usommerl Can you provide a reproducer? a smaller one would be perfect. And we will target a fix for it in the next 20.3.x release.

**Comment by usommerl** [comment] 2021-03-03 21:34
@oubidar-Abderrahim I have created a considerably smaller example application that tries to log a single line. Obviously, the issue is triggered by the logging framework. See [usommerl/graal2928](https://github.com/usommerl/graal2928)

**Comment by oubidar-Abderrahim** [comment] 2021-03-08 15:36
@usommerl I am so sorry to say this, but after checking with the development team, it looks like this is not a bug but rather a limitation of using `Method handles` in native-image. We have some support for it in 21.0.0 but it is still not complete and experimental, therefore it cannot be backported to 20.3.x

My apologies.

**Comment by usommerl** [comment] 2021-03-08 17:34
@oubidar-Abderrahim  No worries! It didn't take much effort to create the example and I have already migrated to 21.0.x with the application where the issue originally appeared. The experimental features in 21.0.x work great for me 😄

**Comment by oubidar-Abderrahim** [comment] 2021-03-10 10:31
@informarte I will close this issue. if you still face the same error with 21.0.0.2 please re-open it.

**Closed by oubidar-Abderrahim** 2021-03-10 10:31 UTC
Labels: bug, native-image

**Comment by informarte** [comment] 2021-05-06 19:53
native-image 21.1.0 produces a working binary.
