### ISSUE TITLE
jaotc: org.graalvm.compiler.graph.GraalGraphError

### ISSUE THREAD

**Issue by tianxiaogu** [oracle/graal#289] opened 2018-01-25 08:07 UTC
A generated class ([C0.class](https://drive.google.com/open?id=1mNTrDSKDt0d33DzKT-6Ls0r2Wez93iDT)) triggers the following `GraalGraphError` by simply invoking `jaotc --output C0.so C0.class`.

```
Error: Failed compilation: C0.M0([CLC0;[Ljava/lang/Comparable;[B[Ljava/lang/Double;[FF[Ljava/lang/Short;LC0;)F: \
        org.graalvm.compiler.graph.GraalGraphError: \
        org.graalvm.compiler.debug.GraalError: \
        NormalizeCompareNode connected to \
        org.graalvm.compiler.nodes.calc.IntegerBelowNode$BelowOp@77b378be (int[16777215|0xffffff] 20|NormalizeCompare false)
	        at node: 125||<|
```

The error **may** be caused by `fcmp`. In the generated method `M0`, a `fcmp` pushed an `int` on the stack, which is further used as the operand of the following `anewarray`.

**Comment by dougxc** [comment] 2018-01-25 08:29
I cannot reproduce this issue:
```
dsimon@freddy /m/p/U/d/Downloads> java -version
java version "9"
Java(TM) SE Runtime Environment (build 9+181)
Java HotSpot(TM) 64-Bit Server VM (build 9+181, mixed mode)
dsimon@freddy /m/p/U/d/Downloads> jaotc --output C0.so C0.class
dsimon@freddy /m/p/U/d/Downloads> java -XX:AOTLibrary=./C0.so C0
dsimon@freddy /m/p/U/d/Downloads>
```
Which JDK 9 version are you using?

**Comment by tianxiaogu** [comment] 2018-01-25 08:37
Hi Doug, I am sorry for not providing the version info.
The exception is triggered in the head of JDK.
I filed an issue here since the exception (`GraalGraphError`) seems to belong to the graal project.

```
$ ./openjdk/jdk/build/linux-x86_64-normal-server-release/jdk/bin/java --version
openjdk 10-internal 2018-03-20
OpenJDK Runtime Environment (build 10-internal+0-adhoc.t.jdk)
OpenJDK 64-Bit Server VM (build 10-internal+0-adhoc.t.jdk, mixed mode)
```

**Comment by axel22** [comment] 2018-02-03 12:05
This should be fixed now:

https://github.com/oracle/graal/commit/6ef1baa3db76ee93e997f4a98fd2c30893b3970b

**Closed** 2018-02-03 12:05 UTC
