### ISSUE TITLE
GraalVM js debug devtools is not accessible in the lasted chrome 118.0.5993.89

### ISSUE THREAD

**Issue by chenjie100** [oracle/graal#7636] opened 2023-10-20 06:27 UTC
When debug js in Chrome open: devtools://devtools/bundled/js_app.html?ws=127.0.0.1:61775/1E828627BBFA81AF25EDE97FD2F
No source code appears and cannot be debugged。

**Comment by hamzaGhaissi** [comment] 2023-10-20 13:35
Hi can you please provide:

- GraalVm version
- JDK version
- OS & architecture
- A minimal reproducer and steps

**Comment by chenjie100** [comment] 2023-10-23 01:50
GraalVm version： 23.0
JDK version: 17.0.8+9-LTS-jvmci-23.0-b14
OS & architecture：Windows 10 amd64
A minimal reproducer and steps：
1, Write any js and start to debug in chrome devtools.
2, In Chrome open: devtools://devtools/bundled/js_app.html?ws=127.0.0.1:50144/someUrl
3, No source code to display and cannot be debugged。

**Comment by martinhiller** [comment] 2023-10-23 12:41
To make the reproduction more concrete:

1. Launch the following main class:

```
import org.graalvm.polyglot.Context;

public class DebugTest {

	public static void main(String[] args) throws Exception {
		try (Context context = Context.newBuilder("js")
				.option("inspect", "4242")
				.option("inspect.Suspend", "false")
				.option("inspect.WaitAttached", "true")
				.option("inspect.Path", "debug")
				.build()) {
			context.eval("js", """
					(function () {
						debugger;
						return 41 + 1;
					})()
					""");
		}
	}
}
```

2. Open the DevTools URL (printed by GraalVM to the stderr) in any recent Chromium browser: `devtools://devtools/bundled/js_app.html?ws=127.0.0.1:4242/debug`

**Result:**

The DevTools open but no source code is shown, and no debugging is possible. According to the [protocol monitor](https://github.com/oracle/graal/files/13070124/ProtocolMonitor-20231023T142513.json), GraalVM sends the browser 3 events, but no further communication takes place. The Java code blocks until the DevTools page is manually closed again.

![image](https://github.com/oracle/graal/assets/7996680/32859ebf-f04d-46d3-a26e-c8a00e165123)

**Comment by hamzaGhaissi** [comment] 2023-10-24 09:05
Thanks @martinhiller issue was found on windows, and we are looking into it

**Comment by hamzaGhaissi** [comment] 2023-10-24 11:32
@zebhlindqvist , I found same issue with Chromium 118.0.5993.70 ubuntu arm64, can you please provide me with Chromium 116.x that you have used ?

**Comment by zebhlindqvist** [comment] 2023-10-24 12:37
@hamzaGhaissi

I didn't find a way to download an older version of Chrome/Chromium. I just happed to find that version installed on a computer that wasn't updated.

One easy way I found was to use Electron.
See https://github.com/zebhlindqvist/electron-devtools

Electron 26.4.1 has Chromium 116.0.5845.228 built in.

**Comment by martinhiller** [comment] 2023-10-24 14:25
Another way are the [Chrome for Testing](https://googlechromelabs.github.io/chrome-for-testing/) downloads:

Chrome 117 (still works):

[Chrome 117.0.5938.149 for Win64](https://edgedl.me.gvt1.com/edgedl/chrome/chrome-for-testing/117.0.5938.149/win64/chrome-win64.zip)
[Chrome 117.0.5938.149 for Linux64](https://edgedl.me.gvt1.com/edgedl/chrome/chrome-for-testing/117.0.5938.149/linux64/chrome-linux64.zip)

Chrome 118 (not anymore):

[Chrome 118.0.5993.70 for Win64](https://edgedl.me.gvt1.com/edgedl/chrome/chrome-for-testing/118.0.5993.70/win64/chrome-win64.zip)
[Chrome 118.0.5993.70 for Linux64](https://edgedl.me.gvt1.com/edgedl/chrome/chrome-for-testing/118.0.5993.70/linux64/chrome-linux64.zip)

**Comment by hamzaGhaissi** [comment] 2023-10-25 13:55
Issue was identified on the latest builds of chrome/chromium, and we are looking into it

**Comment by chenjie100** [comment] 2023-11-09 06:43
I found a possible reason that GraalVM did not send the source code to chrome devtools.

**Comment by oghmjos** [comment] 2023-11-10 11:36
Issue is actual for google-chrome-stable-119.0.6045.105-1.x86_64, but works correctly for google-chrome-stable-117.0.5938.132-1.x86_64 (Linux).   No info that Chrome devTools changed something in API for source code, looks like there were only cosmetic changes: [Streamlined workspace in the Sources panel ](https://developer.chrome.com/blog/new-in-devtools-118/#sources)

**Comment by entlicher** [comment] 2023-11-15 12:41
This was fixed by https://github.com/oracle/graal/commit/db409848581fb94cf7ff7b1aab07465b8a7c1947
We will backport the fix to the releases of GraalVM.

**Closed by entlicher** 2023-11-15 12:41 UTC
Labels: bug

**Comment by chenjie100** [comment] 2023-11-17 03:32
@entlicher That's great, where can I download the update patch or completed graalvm please? Thank you.

**Comment by jkevan** [comment] 2023-11-27 17:17
After struggling to install a previous version of Google Chrome ...
To workaround the issue and be able to use the debugger here is what I did:

Edit your host file with:
```
0.0.0.0 brave-update.brave.com
0.0.0.0 updates.bravesoftware.com
```
This will block Brave browser update domains (The simplest way I found to disable auto update of Brave...)

Then you can download in the assets of: https://github.com/brave/brave-browser/releases/tag/v1.58.137 A version of Brave browser that match you arch.
This version of Brave is based on Chromium 117 and the debugger is working again.
