### ISSUE TITLE
[native-image] Output name is wrong if `-language` is used after `-H:Name`

### ISSUE THREAD

**Issue by nhoughto** [oracle/graal#1032] opened 2019-03-04 01:10 UTC
The order of arguments given to `native-image` seems to impact the name of the binary being built.

if you do:
`native-image -language:js -H:Name=blah` the name will be `blah`
```
Build on Server(pid: 26792, port: 59302)
[blah:26792]    classlist:   3,242.34 ms
[blah:26792]        (cap):   1,157.11 ms
...
```

if you do:
`native-image -H:Name=blah -language:js` the name will be `js`
```
Build on Server(pid: 26792, port: 59302)
[js:26792]    classlist:   3,242.34 ms
[js:26792]        (cap):   1,157.11 ms
...
```

Obviously this means you need to worry about argument ordering (generally a solvable problem), it becomes a problem when argument ordering isn't exposed to the user like when using a gradle plugin or similar.

**Comment by uschi2000** [comment] 2019-03-04 08:33
@olpaw Could you indicate whether you consider this a bug (which will be fixed), or intended behavior (that won't be changed)? In the latter case, we will fix our Gradle plugin accordingly, see https://github.com/palantir/gradle-graal/issues/63 .

**Comment by olpaw** [comment] 2019-03-04 08:56
@uschi2000 this is intended behavior. Macro options (like `--language:js`) are allowed to expand to any other options. Thus if a macro option includes `-H:Name=js` you have to pass an alternative name with `-H:Name=<myname>` after the macro option to ensure the image with be named `<myname>`.

**Closed by olpaw** 2019-03-04 08:56 UTC
Labels: substrate
