### ISSUE TITLE
Native image generator should be able to accept incomplete classpath only for certain packages/classes

### ISSUE THREAD

**Issue by pivovarit** [oracle/graal#2120] opened 2020-01-31 16:14 UTC
Related to: https://github.com/oracle/graal/issues/597

----
For now, `--allow-incomplete-classpath` is a global switch, but it would be great if there was a possibility to cherry-pick classes/packages that should not be resolved during image building.

I'd imagine that most users would want to by default accept complete classpaths with small exceptions.

For example, `hazelcast` depends on jcache which is scope-provided and optional, but in order to be able to build a native image, it's necessary to provide a dependency that might never be used.

It would be great if users could pass arguments like:
`--ignore-type-errors=javax.cache` which would act like `--allow-incomplete-classpath` but just for types belonging to `javax.cache` package.

I'd like to volunteer to implement the feature if it gets accepted.

**Comment by cstancu** [comment] 2020-02-03 20:11
Duplicate of #1664

**Comment by pivovarit** [comment] 2020-02-03 20:11
🙈

**Closed** 2020-02-03 20:11 UTC
Labels: feature, native-image
