### ISSUE TITLE
NumberFormatException in native-image

### ISSUE THREAD

**Issue by mipastgt** [oracle/graal#2677] opened 2020-07-15 09:41 UTC
**Describe the issue**
When I try to create a native image for Android via the Gluon client-maven-plugin I get a NumberFormatException inside native-image.
```
...
[de.mpmediasoft.mpcopilot.main.mobile.gui.main.mpcopilotapp2:15345]    classlist:   3,969.71 ms,  0.94 GB
[de.mpmediasoft.mpcopilot.main.mobile.gui.main.mpcopilotapp2:15345]        (cap):     190.07 ms,  0.93 GB
[de.mpmediasoft.mpcopilot.main.mobile.gui.main.mpcopilotapp2:15345]        setup:     704.47 ms,  0.93 GB
Fatal error:java.lang.NumberFormatException
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
	at java.base/java.util.concurrent.ForkJoinTask.getThrowableException(ForkJoinTask.java:603)
	at java.base/java.util.concurrent.ForkJoinTask.get(ForkJoinTask.java:1006)
	at com.oracle.svm.hosted.NativeImageGenerator.run(NativeImageGenerator.java:478)
	at com.oracle.svm.hosted.NativeImageGeneratorRunner.buildImage(NativeImageGeneratorRunner.java:349)
	at com.oracle.svm.hosted.NativeImageGeneratorRunner.build(NativeImageGeneratorRunner.java:508)
	at com.oracle.svm.hosted.NativeImageGeneratorRunner.main(NativeImageGeneratorRunner.java:114)
	at com.oracle.svm.hosted.NativeImageGeneratorRunner$JDK9Plus.main(NativeImageGeneratorRunner.java:537)
Caused by: java.lang.NumberFormatException: null
	at java.base/java.lang.Integer.parseInt(Integer.java:614)
	at java.base/java.lang.Integer.parseInt(Integer.java:770)
	at com.oracle.svm.hosted.c.query.QueryResultParser.parseIntegerProperty(QueryResultParser.java:232)
	at com.oracle.svm.hosted.c.query.QueryResultParser.visitStructFieldInfo(QueryResultParser.java:144)
	at com.oracle.svm.hosted.c.info.StructFieldInfo.accept(StructFieldInfo.java:74)
	at com.oracle.svm.hosted.c.info.InfoTreeVisitor.processChildren(InfoTreeVisitor.java:31)
	at com.oracle.svm.hosted.c.query.QueryResultParser.visitStructInfo(QueryResultParser.java:134)
	at com.oracle.svm.hosted.c.info.StructInfo.accept(StructInfo.java:62)
	at com.oracle.svm.hosted.c.info.InfoTreeVisitor.processChildren(InfoTreeVisitor.java:31)
	at com.oracle.svm.hosted.c.info.InfoTreeVisitor.visitNativeCodeInfo(InfoTreeVisitor.java:36)
	at com.oracle.svm.hosted.c.info.NativeCodeInfo.accept(NativeCodeInfo.java:57)
	at com.oracle.svm.hosted.c.query.QueryResultParser.parse(QueryResultParser.java:78)
	at com.oracle.svm.hosted.c.CAnnotationProcessorCache.get(CAnnotationProcessorCache.java:114)
	at com.oracle.svm.hosted.c.CAnnotationProcessor.process(CAnnotationProcessor.java:83)
	at com.oracle.svm.hosted.c.NativeLibraries.finish(NativeLibraries.java:520)
	at com.oracle.svm.hosted.NativeImageGenerator.processNativeLibraryImports(NativeImageGenerator.java:1536)
	at com.oracle.svm.hosted.NativeImageGenerator.setupNativeLibraries(NativeImageGenerator.java:1034)
	at com.oracle.svm.hosted.NativeImageGenerator.setupNativeImage(NativeImageGenerator.java:867)
	at com.oracle.svm.hosted.NativeImageGenerator.doRun(NativeImageGenerator.java:551)
	at com.oracle.svm.hosted.NativeImageGenerator.lambda$run$0(NativeImageGenerator.java:466)
	at java.base/java.util.concurrent.ForkJoinTask$AdaptedRunnableAction.exec(ForkJoinTask.java:1407)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:177)
Error: Image build request failed with exit status 1
com.oracle.svm.driver.NativeImage$NativeImageError: Image build request failed with exit status 1
	at com.oracle.svm.driver.NativeImage.showError(NativeImage.java:1558)
	at com.oracle.svm.driver.NativeImage.build(NativeImage.java:1308)
	at com.oracle.svm.driver.NativeImage.performBuild(NativeImage.java:1269)
	at com.oracle.svm.driver.NativeImage.main(NativeImage.java:1228)
	at com.oracle.svm.driver.NativeImage$JDK9Plus.main(NativeImage.java:1740)
```
The bad thing is that the error message is not providing any context. No filename, no linenumber, no String. So it is impossible for me to further track this down.

**Steps to reproduce the issue**
I can't provide any simple example for this.

**Describe GraalVM and your environment:**
 - GraalVM snapshot version Tue Jul 14 02:27:16 GMT 2020
 - JDK major version: **11**
 - OS: **[e.g. Linux Ubuntu 20.04]**
 - Architecture: **[e.g.: AMD64]**

**Comment by lazar-mitrovic** [comment] 2020-07-15 15:26
This is caused by CAP cache provided by Gluon not being up to date. 
I filed a PR which should add a explanation when CAP cache value is missing https://github.com/oracle/graal/pull/2674

**Comment by mipastgt** [comment] 2020-07-15 15:42
Thank you very much for providing this feedback. Do you know when the OCA-signing will be done so that this can be integrated?

**Comment by cstancu** [comment] 2020-09-23 06:56
Fixed by https://github.com/oracle/graal/pull/2674.

**Closed by cstancu** 2020-09-23 06:56 UTC
Labels: bug, native-image
